SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO















CREATE TRIGGER [INSERT_FACTEXP] ON dbo.FACTEXP 
FOR INSERT
AS
SET NOCOUNT ON
declare @CF_CONS_EXP char(1), @FE_USACONSOLIDADO char(1)


	select @FE_USACONSOLIDADO=FE_USACONSOLIDADO from inserted
	select @CF_CONS_EXP=CF_CONS_EXP from configuracion


	if not update(FE_FOLIO)
	UPDATE FACTEXP
	SET FE_FOLIO=UPPER(RTRIM(FE_FOLIO))
	WHERE FE_CODIGO IN (SELECT FE_CODIGO FROM INSERTED)


	IF @CF_CONS_EXP='S' and @FE_USACONSOLIDADO<>'S'
	update factexp
	set FE_USACONSOLIDADO='S'
	where fe_codigo in (select fe_codigo from inserted)

	
	if exists (select * from factexpdet where fe_codigo in (select fe_codigo from inserted))
	UPDATE dbo.FACTEXPDET
	SET     dbo.FACTEXPDET.FED_DESTNAFTA= CASE 
	when dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT CF_PAIS_MX FROM CONFIGURACION) THEN 'M'
	 when dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT CF_PAIS_USA FROM CONFIGURACION) or dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT CF_PAIS_CA FROM CONFIGURACION)
	then 'N'  WHEN 	  dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT PA_CODIGO FROM PAIS WHERE SPI_CODIGO IN ( SELECT SPI_CODIGO FROM SPI WHERE SPI_CLAVE='MX-UE')) 
	then 'U' when 	  dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT PA_CODIGO FROM PAIS WHERE SPI_CODIGO IN ( SELECT SPI_CODIGO FROM SPI WHERE SPI_CLAVE='AELC')) 
	then 'A'  else 'F' end
	FROM         dbo.FACTEXPDET INNER JOIN
	                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      dbo.DIR_CLIENTE ON dbo.FACTEXP.DI_DESTFIN = dbo.DIR_CLIENTE.DI_INDICE
	WHERE     (dbo.FACTEXP.FE_CODIGO in (select fe_codigo from inserted))















GO
