SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[INCOTERMS] (
		[IT_CODIGO]       [smallint] IDENTITY(1, 1) NOT NULL,
		[IT_CLAVE]        [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IT_NOMBRE]       [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IT_NAME]         [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IT_TIPO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IT_OBSOLETO]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_INCOTERMS]
		UNIQUE
		NONCLUSTERED
		([IT_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCOTERMS]
	ADD
	CONSTRAINT [PK_INCOTERMS]
	PRIMARY KEY
	NONCLUSTERED
	([IT_CLAVE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCOTERMS]
	ADD
	CONSTRAINT [DF_INCOTERMS_IT_NOMBRE]
	DEFAULT ('') FOR [IT_NOMBRE]
GO
ALTER TABLE [dbo].[INCOTERMS]
	ADD
	CONSTRAINT [DF_INCOTERMS_IT_OBSOLETO]
	DEFAULT ('N') FOR [IT_OBSOLETO]
GO
ALTER TABLE [dbo].[INCOTERMS]
	ADD
	CONSTRAINT [DF_INCOTERMS_IT_TIPO]
	DEFAULT ('') FOR [IT_TIPO]
GO
ALTER TABLE [dbo].[INCOTERMS] SET (LOCK_ESCALATION = TABLE)
GO
