SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORDCOMPRACONTRIBUCION] (
		[OR_CODIGO]            [int] NOT NULL,
		[CON_CODIGO]           [int] NOT NULL,
		[ORC_CONTRIBPOR]       [decimal](38, 6) NOT NULL,
		[ORC_CONTRIBTOTUS]     [decimal](38, 6) NOT NULL,
		[ORC_TIPOVALOR]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDCOMPRACONTRIBUCION]
	ADD
	CONSTRAINT [PK_ORDCOMPRACONTRIBUCION]
	PRIMARY KEY
	NONCLUSTERED
	([OR_CODIGO], [CON_CODIGO], [ORC_CONTRIBPOR])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDCOMPRACONTRIBUCION]
	ADD
	CONSTRAINT [DF_ORDCOMPRACONTRIBUCION_ORC_CONTRIBPOR]
	DEFAULT ((-1)) FOR [ORC_CONTRIBPOR]
GO
ALTER TABLE [dbo].[ORDCOMPRACONTRIBUCION]
	ADD
	CONSTRAINT [DF_ORDCOMPRACONTRIBUCION_ORC_CONTRIBTOTUS]
	DEFAULT (0) FOR [ORC_CONTRIBTOTUS]
GO
ALTER TABLE [dbo].[ORDCOMPRACONTRIBUCION] SET (LOCK_ESCALATION = TABLE)
GO
