SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[AGENCIACONEXIONDET] (
		[AGD_CODIGO]     [int] IDENTITY(1, 1) NOT NULL,
		[AGC_CODIGO]     [int] NOT NULL,
		[ARC_CODIGO]     [int] NOT NULL,
		CONSTRAINT [IX_AGENCIACONEXIONDET]
		UNIQUE
		NONCLUSTERED
		([AGD_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIACONEXIONDET]
	ADD
	CONSTRAINT [PK_AGENCIACONEXIONDET]
	PRIMARY KEY
	NONCLUSTERED
	([AGC_CODIGO], [ARC_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIACONEXIONDET] SET (LOCK_ESCALATION = TABLE)
GO
