SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ENTRADA_B] (
		[EB_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[EB_CLAVE]      [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EB_DESC]       [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_ENTRADA_B]
		UNIQUE
		NONCLUSTERED
		([EB_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENTRADA_B]
	ADD
	CONSTRAINT [PK_ENTRADA_B]
	PRIMARY KEY
	NONCLUSTERED
	([EB_CLAVE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENTRADA_B] SET (LOCK_ESCALATION = TABLE)
GO
