SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AREAPRODUC] (
		[ARE_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[ARE_NOMBRE]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ARE_DESC]           [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARE_UBICACION]      [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARE_MOTIVO]         [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARE_CONTROLCAL]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_AREAPRODUC]
		UNIQUE
		NONCLUSTERED
		([ARE_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AREAPRODUC]
	ADD
	CONSTRAINT [PK_AREAPRODUC]
	PRIMARY KEY
	NONCLUSTERED
	([ARE_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[AREAPRODUC] SET (LOCK_ESCALATION = TABLE)
GO
