SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPEXCELRETRA] (
		[ORDEN]            [int] IDENTITY(1, 1) NOT NULL,
		[NOPARTE]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CANTIDAD]         [decimal](38, 6) NULL,
		[NOPARTEAUX]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FOLIO]            [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NOPARTEPT]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TIPODESCARGA]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_IMPEXCELRETRA]
		UNIQUE
		NONCLUSTERED
		([ORDEN])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPEXCELRETRA] SET (LOCK_ESCALATION = TABLE)
GO
