SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTROIDENTIFICA] (
		[MIID_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[MA_CODIGO]           [int] NOT NULL,
		[IDE_CODIGO]          [int] NOT NULL,
		[IDED_CODIGO]         [int] NULL,
		[MIID_DESC]           [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MIID_DESC2]          [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_CODIGO2]        [int] NULL,
		[MIID_MOVIMIENTO]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MIID_DESC3]          [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_CODIGO3]        [int] NULL,
		CONSTRAINT [IX_MAESTROIDENTIFICA]
		UNIQUE
		NONCLUSTERED
		([MIID_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROIDENTIFICA]
	ADD
	CONSTRAINT [PK_MAESTROIDENTIFICA]
	PRIMARY KEY
	CLUSTERED
	([MA_CODIGO], [IDE_CODIGO])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROIDENTIFICA]
	ADD
	CONSTRAINT [DF_MAESTROIDENTIFICA_MIID_DESC]
	DEFAULT ('') FOR [MIID_DESC]
GO
ALTER TABLE [dbo].[MAESTROIDENTIFICA]
	ADD
	CONSTRAINT [DF_MAESTROIDENTIFICA_MIID_MOVIMIENTO]
	DEFAULT ('E') FOR [MIID_MOVIMIENTO]
GO
ALTER TABLE [dbo].[MAESTROIDENTIFICA] SET (LOCK_ESCALATION = TABLE)
GO
