SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPR1HIST] (
		[R1H_CODIGO]             [int] IDENTITY(1, 1) NOT NULL,
		[PI_CODIGO]              [int] NOT NULL,
		[R1H_PEDIMENTOR1ANT]     [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AGT_R1ANT]              [int] NOT NULL,
		[R1H_FECHAPAGO]          [datetime] NULL,
		[R1H_OBSERVAANT]         [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AD_CODIGOANT]           [int] NULL,
		CONSTRAINT [IX_PEDIMPR1HIST]
		UNIQUE
		NONCLUSTERED
		([R1H_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPR1HIST]
	ADD
	CONSTRAINT [PK_PEDIMPR1HIST]
	PRIMARY KEY
	CLUSTERED
	([R1H_PEDIMENTOR1ANT], [AGT_R1ANT])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPR1HIST] SET (LOCK_ESCALATION = TABLE)
GO
