SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[FACTEXPDESP] (
		[FEI_CODIGO]         [int] NOT NULL,
		[FE_CODIGO]          [int] NOT NULL,
		[MA_CODIGO]          [int] NOT NULL,
		[FEI_PORCENTAJE]     [decimal](38, 6) NOT NULL,
		[FEI_TOTALPESO]      [decimal](38, 6) NULL,
		[FEI_TOTALCOSTO]     [decimal](38, 6) NULL,
		CONSTRAINT [IX_FACTEXPDESP]
		UNIQUE
		NONCLUSTERED
		([FEI_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDESP]
	ADD
	CONSTRAINT [PK_FACTEXPDESP]
	PRIMARY KEY
	NONCLUSTERED
	([FE_CODIGO], [MA_CODIGO])
	ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [IX_FACTEXPDESP_1]
	ON [dbo].[FACTEXPDESP] ([FE_CODIGO], [FEI_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDESP] SET (LOCK_ESCALATION = TABLE)
GO
