SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURAFOLIOENT] (
		[CFE_TIPO]          [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TQ_CODIGO]         [smallint] NOT NULL,
		[TF_CODIGO]         [smallint] NOT NULL,
		[PR_CODIGO]         [int] NOT NULL,
		[CFE_PREFIJO]       [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFE_SUFIJO]        [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFE_CONTADOR]      [int] NOT NULL,
		[CFE_ACTIVO]        [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFE_PRINCIPAL]     [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFE_ENTSAL]        [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAFOLIOENT]
	ADD
	CONSTRAINT [PK_CONFIGURAFOLIOENT]
	PRIMARY KEY
	NONCLUSTERED
	([CFE_TIPO], [TQ_CODIGO], [TF_CODIGO], [PR_CODIGO], [CFE_ENTSAL])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAFOLIOENT]
	ADD
	CONSTRAINT [DF_CONFIGURAFOLIOENT_CFE_CONTADOR]
	DEFAULT (1) FOR [CFE_CONTADOR]
GO
ALTER TABLE [dbo].[CONFIGURAFOLIOENT]
	ADD
	CONSTRAINT [DF_CONFIGURAFOLIOENT_CFE_PREFIJO]
	DEFAULT ('') FOR [CFE_PREFIJO]
GO
ALTER TABLE [dbo].[CONFIGURAFOLIOENT]
	ADD
	CONSTRAINT [DF_CONFIGURAFOLIOENT_CFE_SUFIJO]
	DEFAULT ('') FOR [CFE_SUFIJO]
GO
ALTER TABLE [dbo].[CONFIGURAFOLIOENT]
	ADD
	CONSTRAINT [DF_CONFIGURAFOLIOENT_CFE_TIPO]
	DEFAULT ('N') FOR [CFE_TIPO]
GO
ALTER TABLE [dbo].[CONFIGURAFOLIOENT]
	ADD
	CONSTRAINT [DF_CONFIGURAFOLIOENT_PR_CODIGO]
	DEFAULT (0) FOR [PR_CODIGO]
GO
ALTER TABLE [dbo].[CONFIGURAFOLIOENT]
	ADD
	CONSTRAINT [DF_CONFIGURAFOLIOENT_TF_CODIGO]
	DEFAULT (0) FOR [TF_CODIGO]
GO
ALTER TABLE [dbo].[CONFIGURAFOLIOENT]
	ADD
	CONSTRAINT [DF_CONFIGURAFOLIOENT_TQ_CODIGO]
	DEFAULT (0) FOR [TQ_CODIGO]
GO
ALTER TABLE [dbo].[CONFIGURAFOLIOENT] SET (LOCK_ESCALATION = TABLE)
GO
