SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPBANCO] (
		[PBA_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[PI_CODIGO]         [int] NOT NULL,
		[BAN_CODIGO]        [int] NOT NULL,
		[PBA_NOCAJA]        [smallint] NULL,
		[PBA_OPERACION]     [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PBA_FECHA]         [datetime] NULL,
		[PBA_HORA]          [datetime] NULL,
		[PBA_FIRMA]         [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PBA_IMPORTE]       [decimal](38, 6) NULL,
		[PBA_EFECTIVO]      [decimal](38, 6) NULL,
		CONSTRAINT [IX_PEDIMPBANCO]
		UNIQUE
		NONCLUSTERED
		([PBA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPBANCO]
	ADD
	CONSTRAINT [PK_PEDIMPBANCO]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPBANCO] SET (LOCK_ESCALATION = TABLE)
GO
