SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CUESTIONPPSPT] (
		[PP_CODIGO]         [int] NOT NULL,
		[PPP_CODIGO]        [int] NOT NULL,
		[MA_CODIGO]         [int] NOT NULL,
		[MA_NOPARTE]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AR_EXPMX]          [int] NULL,
		[AR_IMPFO]          [int] NULL,
		[PPP_RATEIMPFO]     [decimal](38, 6) NULL,
		[PPP_RATEEXPMX]     [decimal](38, 6) NULL,
		[PA_DESTINO]        [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUESTIONPPSPT]
	ADD
	CONSTRAINT [PK_CUESTIONPPSPT_1]
	PRIMARY KEY
	NONCLUSTERED
	([PPP_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUESTIONPPSPT]
	ADD
	CONSTRAINT [DF_CUESTIONPPSPT_MA_NOPARTE]
	DEFAULT ('') FOR [MA_NOPARTE]
GO
ALTER TABLE [dbo].[CUESTIONPPSPT] SET (LOCK_ESCALATION = TABLE)
GO
