SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPDEF] (
		[FE_CODIGO]      [int] NOT NULL,
		[FE_DEFTXT1]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FE_DEFTXT2]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FE_DEFNO1]      [int] NOT NULL,
		[FE_DEFNO2]      [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDEF]
	ADD
	CONSTRAINT [PK_FACTEXPDEF]
	PRIMARY KEY
	NONCLUSTERED
	([FE_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDEF_MA_DEFNO1]
	DEFAULT (0) FOR [FE_DEFNO1]
GO
ALTER TABLE [dbo].[FACTEXPDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDEF_MA_DEFNO2]
	DEFAULT (0) FOR [FE_DEFNO2]
GO
ALTER TABLE [dbo].[FACTEXPDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDEF_MA_DEFTXT1]
	DEFAULT ('') FOR [FE_DEFTXT1]
GO
ALTER TABLE [dbo].[FACTEXPDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDEF_MA_DEFTXT2]
	DEFAULT ('') FOR [FE_DEFTXT2]
GO
ALTER TABLE [dbo].[FACTEXPDEF] SET (LOCK_ESCALATION = TABLE)
GO
