SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PERMISOPLANTA] (
		[PE_CODIGO]         [int] NOT NULL,
		[DI_PLANTA]         [int] NOT NULL,
		[PEL_PRINCIPAL]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISOPLANTA]
	ADD
	CONSTRAINT [PK_PERMISOPLANTA]
	PRIMARY KEY
	NONCLUSTERED
	([PE_CODIGO], [DI_PLANTA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISOPLANTA]
	ADD
	CONSTRAINT [DF__PERMISOPL__PEL_P__4DEF1CB7]
	DEFAULT ('N') FOR [PEL_PRINCIPAL]
GO
ALTER TABLE [dbo].[PERMISOPLANTA] SET (LOCK_ESCALATION = TABLE)
GO
