SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONTRATO] (
		[TRA_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[CL_CODIGO]          [int] NOT NULL,
		[DI_CODIGO]          [int] NOT NULL,
		[TRA_PERIODOINI]     [datetime] NOT NULL,
		[TRA_PERIODOFIN]     [datetime] NOT NULL,
		[TRA_PAISES]         [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TRA_COMENTA]        [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_CONTRATO]
		UNIQUE
		NONCLUSTERED
		([TRA_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRATO]
	ADD
	CONSTRAINT [PK_CONTRATO]
	PRIMARY KEY
	CLUSTERED
	([CL_CODIGO], [TRA_PERIODOINI], [TRA_PERIODOFIN])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRATO] SET (LOCK_ESCALATION = TABLE)
GO
