SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPORTFIELDS] (
		[IMF_CODIGO]                [int] IDENTITY(1, 1) NOT NULL,
		[IMF_FIELDNAME]             [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_FIELDTYPE]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_SIZE]                  [int] NULL,
		[IMF_TYPEOBJET]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_TABLENAME]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_DISPLAYLABEL]          [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_DISPLAYLABELING]       [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_REQUIRED]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_SACARMAESTRO]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_DISPLAYTABLE]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_DISPLAYFIELD]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_DISPLAYFIELDING]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_LINKFIELD]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_CODIGO]                [smallint] NULL,
		[IMF_DEFAULT]               [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_AGRUP]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_SELECTMASTER]          [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_TABLATEXTO]            [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_PARAIMPORT]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_PARAREPORT]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_PARABUSQUEDA]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_DESC]                  [varchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_DESCING]               [varchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_CAMPOING]              [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_CAMPOINGTXT]           [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMF_ORDENSELECTMASTER]     [int] NOT NULL,
		CONSTRAINT [IX_IMPORTFIELDS]
		UNIQUE
		NONCLUSTERED
		([IMF_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTFIELDS]
	ADD
	CONSTRAINT [PK_IMPORTFIELDS]
	PRIMARY KEY
	NONCLUSTERED
	([IMF_FIELDNAME], [IMF_TABLENAME], [IMF_ORDENSELECTMASTER])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTFIELDS]
	ADD
	CONSTRAINT [DF_IMPORTFIELDS_IMF_FIELDNAME]
	DEFAULT ('') FOR [IMF_FIELDNAME]
GO
ALTER TABLE [dbo].[IMPORTFIELDS]
	ADD
	CONSTRAINT [DF_IMPORTFIELDS_IMF_ORDENSELECTMASTER]
	DEFAULT (0) FOR [IMF_ORDENSELECTMASTER]
GO
ALTER TABLE [dbo].[IMPORTFIELDS]
	ADD
	CONSTRAINT [DF_IMPORTFIELDS_IMF_PARABUSQUEDA]
	DEFAULT ('S') FOR [IMF_PARABUSQUEDA]
GO
ALTER TABLE [dbo].[IMPORTFIELDS]
	ADD
	CONSTRAINT [DF_IMPORTFIELDS_IMF_PARAIMPORT]
	DEFAULT ('S') FOR [IMF_PARAIMPORT]
GO
ALTER TABLE [dbo].[IMPORTFIELDS]
	ADD
	CONSTRAINT [DF_IMPORTFIELDS_IMF_PARAREPORT]
	DEFAULT ('S') FOR [IMF_PARAREPORT]
GO
ALTER TABLE [dbo].[IMPORTFIELDS] SET (LOCK_ESCALATION = TABLE)
GO
