SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REVORIGENREP] (
		[RV_CODIGO]     [int] IDENTITY(1, 1) NOT NULL,
		[RV_FOLIO]      [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RV_INICIO]     [datetime] NOT NULL,
		[RV_FINAL]      [datetime] NOT NULL,
		[RV_CE]         [decimal](38, 6) NOT NULL,
		[RV_CDV]        [decimal](38, 6) NOT NULL,
		[RV_CO]         [decimal](38, 6) NOT NULL,
		[RV_CDR]        [decimal](38, 6) NOT NULL,
		[RV_MONTO]      [decimal](38, 6) NOT NULL,
		CONSTRAINT [IX_REVORIGENREP]
		UNIQUE
		NONCLUSTERED
		([RV_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REVORIGENREP]
	ADD
	CONSTRAINT [PK_REVORIGENREP]
	PRIMARY KEY
	NONCLUSTERED
	([RV_FOLIO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[REVORIGENREP]
	ADD
	CONSTRAINT [DF_REVORIGENREP_RV_MONTO]
	DEFAULT (0) FOR [RV_MONTO]
GO
ALTER TABLE [dbo].[REVORIGENREP] SET (LOCK_ESCALATION = TABLE)
GO
