SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ARANCELCONTRIB] (
		[ARC_CODIGO]     [int] IDENTITY(1, 1) NOT NULL,
		[AR_CODIGO]      [int] NOT NULL,
		[ES_CODIGO]      [int] NOT NULL,
		[PA_CODIGO]      [int] NOT NULL,
		[CON_CODIGO]     [int] NOT NULL,
		[ARS_TASA]       [decimal](38, 6) NOT NULL,
		[ARS_CASO]       [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_ARANCELCONTRIB]
		UNIQUE
		NONCLUSTERED
		([ARC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARANCELCONTRIB]
	ADD
	CONSTRAINT [PK_ARANCELCONTRIB]
	PRIMARY KEY
	NONCLUSTERED
	([AR_CODIGO], [ES_CODIGO], [PA_CODIGO], [CON_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARANCELCONTRIB]
	ADD
	CONSTRAINT [DF_ARANCELCONTRIB_ARS_TASA]
	DEFAULT ((-1)) FOR [ARS_TASA]
GO
ALTER TABLE [dbo].[ARANCELCONTRIB]
	ADD
	CONSTRAINT [DF_ARANCELCONTRIB_ES_CODIGO]
	DEFAULT (0) FOR [ES_CODIGO]
GO
ALTER TABLE [dbo].[ARANCELCONTRIB]
	ADD
	CONSTRAINT [DF_ARANCELCONTRIB_PA_CODIGO]
	DEFAULT (0) FOR [PA_CODIGO]
GO
ALTER TABLE [dbo].[ARANCELCONTRIB] SET (LOCK_ESCALATION = TABLE)
GO
