SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURACONTRIBTPAGO] (
		[CFC_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[CP_CODIGO]          [int] NOT NULL,
		[CON_CODIGO]         [smallint] NOT NULL,
		[CFC_MOVIMIENTO]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PG_CODIGO]          [smallint] NULL,
		CONSTRAINT [IX_CONFIGURACONTRIBTPAGO]
		UNIQUE
		NONCLUSTERED
		([CFC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURACONTRIBTPAGO]
	ADD
	CONSTRAINT [PK_CONFIGURACONTRIBTPAGO]
	PRIMARY KEY
	CLUSTERED
	([CP_CODIGO], [CON_CODIGO], [CFC_MOVIMIENTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURACONTRIBTPAGO] SET (LOCK_ESCALATION = TABLE)
GO
