SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TIPO] (
		[TI_CODIGO]           [smallint] IDENTITY(1, 1) NOT NULL,
		[TI_NOMBRE]           [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TI_NAME]             [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TI_CATEG]            [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TI_CATEGM]           [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TI_DICTAMEN]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TI_PAGACONTRIB]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TI_CARGO]            [int] NULL,
		[TI_PERMCIAMESES]     [decimal](38, 6) NOT NULL,
		CONSTRAINT [IX_TIPO]
		UNIQUE
		CLUSTERED
		([TI_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TIPO]
	ADD
	CONSTRAINT [PK_TIPO]
	PRIMARY KEY
	NONCLUSTERED
	([TI_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TIPO]
	ADD
	CONSTRAINT [DF_TIPO_TI_CATEG]
	DEFAULT ('') FOR [TI_CATEG]
GO
ALTER TABLE [dbo].[TIPO]
	ADD
	CONSTRAINT [DF_TIPO_TI_CATEGM]
	DEFAULT ('') FOR [TI_CATEGM]
GO
ALTER TABLE [dbo].[TIPO]
	ADD
	CONSTRAINT [DF_TIPO_TI_DICTAMEN]
	DEFAULT ('') FOR [TI_DICTAMEN]
GO
ALTER TABLE [dbo].[TIPO]
	ADD
	CONSTRAINT [DF_TIPO_TI_NAME]
	DEFAULT ('') FOR [TI_NAME]
GO
ALTER TABLE [dbo].[TIPO]
	ADD
	CONSTRAINT [DF_TIPO_TI_PERMCIAMESES]
	DEFAULT ((-1)) FOR [TI_PERMCIAMESES]
GO
ALTER TABLE [dbo].[TIPO] SET (LOCK_ESCALATION = TABLE)
GO
