SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TVALORA] (
		[TV_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[TV_CLAVE]      [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TV_DESC]       [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_TVALORA]
		UNIQUE
		NONCLUSTERED
		([TV_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TVALORA]
	ADD
	CONSTRAINT [PK_TVALORA]
	PRIMARY KEY
	NONCLUSTERED
	([TV_CLAVE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TVALORA] SET (LOCK_ESCALATION = TABLE)
GO
