SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPIDENTIFICA] (
		[PII_CODIGO]       [int] NOT NULL,
		[PI_CODIGO]        [int] NOT NULL,
		[IDE_CODIGO]       [int] NOT NULL,
		[IDED_CODIGO]      [int] NULL,
		[PII_DESC]         [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PII_DESC2]        [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_CODIGO2]     [int] NULL,
		[PII_DESC3]        [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_CODIGO3]     [int] NULL,
		CONSTRAINT [IX_PEDIMPIDENTIFICA]
		UNIQUE
		NONCLUSTERED
		([PII_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPIDENTIFICA]
	ADD
	CONSTRAINT [PK_PEDIMPIDENTIFICA]
	PRIMARY KEY
	NONCLUSTERED
	([PII_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPIDENTIFICA]
	ADD
	CONSTRAINT [DF_PEDIMPIDENTIFICA_PII_DESC]
	DEFAULT ('') FOR [PII_DESC]
GO
ALTER TABLE [dbo].[PEDIMPIDENTIFICA] SET (LOCK_ESCALATION = TABLE)
GO
