SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DESVIACION] (
		[DEV_CODIGO]          [int] IDENTITY(1, 1) NOT NULL,
		[DEV_FOLIOCAMBIO]     [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_CODIGONVO]        [int] NOT NULL,
		[DEV_FECHAINI]        [datetime] NOT NULL,
		[DEV_FECHAFIN]        [datetime] NOT NULL,
		[DEV_CANTIDAD]        [decimal](38, 6) NOT NULL,
		[DEV_SALDO]           [decimal](38, 6) NOT NULL,
		[DEV_HABILITADO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DEV_USO_SALDO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_NOPARTEPADRE]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_NOPARTEORIG]      [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_NOPARTENVO]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DEV_TIPOSUST]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DEV_CONSUMO]         [decimal](38, 6) NOT NULL,
		CONSTRAINT [IX_DESVIACION]
		UNIQUE
		NONCLUSTERED
		([DEV_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [PK_DESVIACION]
	PRIMARY KEY
	CLUSTERED
	([MA_NOPARTEPADRE], [MA_NOPARTEORIG], [DEV_FECHAINI])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [DF_DESVIACION_DEV_CANTIDAD]
	DEFAULT (0) FOR [DEV_CANTIDAD]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [DF_DESVIACION_DEV_CONSUMO]
	DEFAULT (0) FOR [DEV_CONSUMO]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [DF_DESVIACION_DEV_FECHAFIN]
	DEFAULT ('01/01/9999') FOR [DEV_FECHAFIN]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [DF_DESVIACION_DEV_FECHAINI]
	DEFAULT ('01/01/1999') FOR [DEV_FECHAINI]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [DF_DESVIACION_DEV_HABILITADO]
	DEFAULT ('N') FOR [DEV_HABILITADO]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [DF_DESVIACION_DEV_SALDO]
	DEFAULT (0) FOR [DEV_SALDO]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [DF_DESVIACION_DEV_TIPOSUST]
	DEFAULT ('I') FOR [DEV_TIPOSUST]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [DF_DESVIACION_DEV_USO_SALDO]
	DEFAULT ('N') FOR [DEV_USO_SALDO]
GO
ALTER TABLE [dbo].[DESVIACION]
	ADD
	CONSTRAINT [DF_DESVIACION_MA_NOPARTEPADRE]
	DEFAULT ('') FOR [MA_NOPARTEPADRE]
GO
ALTER TABLE [dbo].[DESVIACION] SET (LOCK_ESCALATION = TABLE)
GO
