SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIDOCONTRIBUCION] (
		[PD_CODIGO]            [int] NOT NULL,
		[CON_CODIGO]           [int] NOT NULL,
		[PDC_CONTRIBPOR]       [decimal](38, 6) NOT NULL,
		[PDC_CONTRIBTOTUS]     [decimal](38, 6) NOT NULL,
		[PDC_TIPOVALOR]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIDOCONTRIBUCION]
	ADD
	CONSTRAINT [PK_PEDIDOCONTRIBUCION]
	PRIMARY KEY
	NONCLUSTERED
	([PD_CODIGO], [CON_CODIGO], [PDC_CONTRIBPOR])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIDOCONTRIBUCION]
	ADD
	CONSTRAINT [DF_PEDIDOCONTRIBUCION_PDC_CONTRIBPOR]
	DEFAULT ((-1)) FOR [PDC_CONTRIBPOR]
GO
ALTER TABLE [dbo].[PEDIDOCONTRIBUCION]
	ADD
	CONSTRAINT [DF_PEDIDOCONTRIBUCION_PDC_CONTRIBTOTUS]
	DEFAULT (0) FOR [PDC_CONTRIBTOTUS]
GO
ALTER TABLE [dbo].[PEDIDOCONTRIBUCION] SET (LOCK_ESCALATION = TABLE)
GO
