SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTROALM] (
		[MA_CODIGO]               [int] NOT NULL,
		[MAA_FECHAREVISION]       [datetime] NULL,
		[MAA_MINALM]              [decimal](38, 6) NOT NULL,
		[MAA_MAXALM]              [decimal](38, 6) NOT NULL,
		[MAA_MINGEN]              [decimal](38, 6) NOT NULL,
		[MAA_MAXGEN]              [decimal](38, 6) NOT NULL,
		[TA_CODIGO]               [smallint] NULL,
		[MAA_INSPECCION]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAA_SIZELOTE]            [decimal](38, 6) NOT NULL,
		[MAA_POLITICACOMPRAS]     [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[US_COMPRADOR]            [int] NULL,
		[MAA_PUNTOREORDEN]        [decimal](38, 6) NOT NULL,
		[MAA_REQUISICIONAUT]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PR_CODIGO]               [int] NULL,
		[MAA_BARCODE]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MAA_BARCODEALT]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MAA_ULTIMACOMPRA]        [datetime] NULL,
		[MAA_ULTIMOPROVEE]        [int] NULL,
		[MAA_ULTIMOCOSTO]         [decimal](38, 6) NOT NULL,
		[MAA_ULTIMACANT]          [decimal](38, 6) NOT NULL,
		[MAA_TIEMPOSURTIDO]       [decimal](38, 6) NULL,
		[MAA_CONTROLLOTE]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MAA_LOTESIZE]            [decimal](38, 6) NULL,
		[MAA_ROTACIONINV]         [decimal](38, 6) NULL,
		[MAA_CLASS_ABC]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MAA_TIEMPOGARANTIA]      [decimal](38, 6) NULL,
		[MAA_CAVIDADES]           [decimal](38, 6) NULL,
		[MAA_TIEMPOCICLO]         [decimal](38, 6) NULL,
		[MAA_PORMEZCLA]           [decimal](38, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [PK_MAESTROALM]
	PRIMARY KEY
	NONCLUSTERED
	([MA_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_FECHAREVISION]
	DEFAULT (convert(varchar(10),getdate(),101)) FOR [MAA_FECHAREVISION]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_INSPECCION]
	DEFAULT ('N') FOR [MAA_INSPECCION]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_MAXALM]
	DEFAULT (0) FOR [MAA_MAXALM]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_MAXGEN]
	DEFAULT (0) FOR [MAA_MAXGEN]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_MINALM]
	DEFAULT (0) FOR [MAA_MINALM]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_MINGEN]
	DEFAULT (0) FOR [MAA_MINGEN]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_PUNTOREORDEN]
	DEFAULT (0) FOR [MAA_PUNTOREORDEN]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_REQUISICIONAUT]
	DEFAULT ('N') FOR [MAA_REQUISICIONAUT]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_SIZELOTE]
	DEFAULT (1) FOR [MAA_SIZELOTE]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_ULTIMACANT]
	DEFAULT (0) FOR [MAA_ULTIMACANT]
GO
ALTER TABLE [dbo].[MAESTROALM]
	ADD
	CONSTRAINT [DF_MAESTROALM_MAA_ULTIMOCOSTO]
	DEFAULT (0) FOR [MAA_ULTIMOCOSTO]
GO
ALTER TABLE [dbo].[MAESTROALM] SET (LOCK_ESCALATION = TABLE)
GO
