SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENCIAPAGDETFRANJA] (
		[AGPF_INDICED]     [int] IDENTITY(1, 1) NOT NULL,
		[AGPD_INDICED]     [int] NOT NULL,
		[AGPF_RUBRO]       [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AGPF_VALOR]       [decimal](38, 6) NOT NULL,
		CONSTRAINT [IX_AGENCIAPAGDETFRANJA]
		UNIQUE
		NONCLUSTERED
		([AGPF_INDICED])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIAPAGDETFRANJA]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDETFRANJA_AGPF_VALOR]
	DEFAULT (0) FOR [AGPF_VALOR]
GO
ALTER TABLE [dbo].[AGENCIAPAGDETFRANJA] SET (LOCK_ESCALATION = TABLE)
GO
