SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MUNICIPIO] (
		[MU_CODIGO]     [int] IDENTITY(1, 1) NOT NULL,
		[MU_NOMBRE]     [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MU_CLAVE]      [int] NOT NULL,
		[ES_CODIGO]     [int] NOT NULL,
		CONSTRAINT [IX_MUNICIPIO]
		UNIQUE
		NONCLUSTERED
		([MU_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MUNICIPIO]
	ADD
	CONSTRAINT [PK_MUNICIPIO]
	PRIMARY KEY
	CLUSTERED
	([MU_NOMBRE], [MU_CLAVE], [ES_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MUNICIPIO] SET (LOCK_ESCALATION = TABLE)
GO
