SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PlntUsedTbls] (
,
		CONSTRAINT [IX_PlntUsedTbls]
		UNIQUE
		NONCLUSTERED
		()
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PlntUsedTbls] SET (LOCK_ESCALATION = TABLE)
GO
