SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ERRORBANCO] (
		[ERB_NUMERO]     [smallint] NOT NULL,
		[ERB_DESC]       [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERRORBANCO]
	ADD
	CONSTRAINT [PK_ERRORBANCO]
	PRIMARY KEY
	CLUSTERED
	([ERB_NUMERO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERRORBANCO] SET (LOCK_ESCALATION = TABLE)
GO
