SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPCOMPENSA] (
		[COM_CODIGO]          [int] IDENTITY(1, 1) NOT NULL,
		[PI_CODIGO]           [int] NOT NULL,
		[COM_FOLIO]           [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[COM_IGICOMPENSA]     [decimal](38, 6) NOT NULL,
		[COM_DTACOMPENSA]     [decimal](38, 6) NOT NULL,
		[COM_CCCOMPENSA]      [decimal](38, 6) NOT NULL,
		[COM_IGIPEND]         [decimal](38, 6) NOT NULL,
		[COM_DTAPEND]         [decimal](38, 6) NOT NULL,
		[COM_CCPEND]          [decimal](38, 6) NOT NULL,
		[PI_ORIGINAL]         [int] NOT NULL,
		[COM_ORIGINALIGI]     [decimal](38, 6) NOT NULL,
		[COM_ORIGINALDTA]     [decimal](38, 6) NOT NULL,
		[COM_ORIGINALCC]      [decimal](38, 6) NOT NULL,
		[PI_R1]               [int] NOT NULL,
		[PI_R1IGI]            [decimal](38, 6) NOT NULL,
		[PI_R1DTA]            [decimal](38, 6) NOT NULL,
		[PI_R1CC]             [decimal](38, 6) NOT NULL,
		CONSTRAINT [IX_PEDIMPCOMPENSA]
		UNIQUE
		NONCLUSTERED
		([COM_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [PK_PEDIMPCOMPENSA]
	PRIMARY KEY
	NONCLUSTERED
	([PI_CODIGO], [PI_ORIGINAL])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_CCCOMPENSA]
	DEFAULT (0) FOR [COM_CCCOMPENSA]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_CCPEND]
	DEFAULT (0) FOR [COM_CCPEND]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_DTACOMPENSA]
	DEFAULT (0) FOR [COM_DTACOMPENSA]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_DTAPEND]
	DEFAULT (0) FOR [COM_DTAPEND]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_FOLIO]
	DEFAULT ('') FOR [COM_FOLIO]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_IGICOMPENSA]
	DEFAULT (0) FOR [COM_IGICOMPENSA]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_IGIPEND]
	DEFAULT (0) FOR [COM_IGIPEND]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_ORIGINALCC]
	DEFAULT (0) FOR [COM_ORIGINALCC]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_ORIGINALDTA]
	DEFAULT (0) FOR [COM_ORIGINALDTA]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_COM_ORIGINALIGI]
	DEFAULT (0) FOR [COM_ORIGINALIGI]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_PI_R1CC]
	DEFAULT (0) FOR [PI_R1CC]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_PI_R1DTA]
	DEFAULT (0) FOR [PI_R1DTA]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA]
	ADD
	CONSTRAINT [DF_PEDIMPCOMPENSA_PI_R1IGI]
	DEFAULT (0) FOR [PI_R1IGI]
GO
ALTER TABLE [dbo].[PEDIMPCOMPENSA] SET (LOCK_ESCALATION = TABLE)
GO
