SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENCIADEL] (
		[AG_CODIGO]     [int] NULL,
		[AG_NOMBRE]     [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIADEL] SET (LOCK_ESCALATION = TABLE)
GO
