SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PEDIMPGUARDA] (
		[PI_CODIGO]       [int] NOT NULL,
		[FACT_CODIGO]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPGUARDA]
	ADD
	CONSTRAINT [PK_PEDIMPGUARDA]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO], [FACT_CODIGO])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPGUARDA] SET (LOCK_ESCALATION = TABLE)
GO
