SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RESINASFACTURAS] (
		[RF_Codigo]              [int] IDENTITY(1, 1) NOT NULL,
		[RF_CodigoDocumento]     [int] NULL,
		[RF_TipoDocumento]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TQ_Codigo]              [int] NULL,
		CONSTRAINT [IX_RESINASFACTURAS]
		UNIQUE
		NONCLUSTERED
		([RF_Codigo])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESINASFACTURAS]
	ADD
	CONSTRAINT [PK_RESINASFACTURAS]
	PRIMARY KEY
	CLUSTERED
	([RF_Codigo])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESINASFACTURAS] SET (LOCK_ESCALATION = TABLE)
GO
