SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTROAUXDET] (
		[MA_CODIGO]        [int] NOT NULL,
		[MAXD_AFFCODE]     [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MAXD_AFFQUAL]     [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MAXD_CODIGO]      [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROAUXDET]
	ADD
	CONSTRAINT [PK_MAESTROAUXDET]
	PRIMARY KEY
	NONCLUSTERED
	([MAXD_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROAUXDET] SET (LOCK_ESCALATION = TABLE)
GO
