SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COMPARACIONINVFISICO] (
		[CIF_CODIGO]                [int] IDENTITY(1, 1) NOT NULL,
		[CIF_NOPARTE]               [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CIF_CANTIDAD]              [decimal](36, 6) NULL,
		[CIF_CANTIDADEXISTENTE]     [decimal](38, 6) NULL,
		[CIF_CANTIDADRESTANTE]      [decimal](38, 6) NULL,
		[CIF_ESTATUS]               [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CIF_NOPARTEAUX]            [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPARACIONINVFISICO]
	ADD
	CONSTRAINT [PK_COMPARACIONINVFISICO]
	PRIMARY KEY
	CLUSTERED
	([CIF_CODIGO])
	ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_COMPARACIONINVFISICO]
	ON [dbo].[COMPARACIONINVFISICO] ([CIF_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPARACIONINVFISICO] SET (LOCK_ESCALATION = TABLE)
GO
