SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[UPDATEINFO] (
		[UI_ORDEN]           [smallint] NULL,
		[UI_VERSION]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[UI_STORED]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[UI_DESCRIPCION]     [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UPDATEINFO]
	ADD
	CONSTRAINT [PK_UPDATEINFO]
	PRIMARY KEY
	NONCLUSTERED
	([UI_STORED])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[UPDATEINFO] SET (LOCK_ESCALATION = TABLE)
GO
