SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CATTEXTIL] (
		[CX_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[CX_CORTO]      [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CX_NOMBRE]     [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CX_NAME]       [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_CATTEXTIL]
		UNIQUE
		CLUSTERED
		([CX_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATTEXTIL]
	ADD
	CONSTRAINT [PK_CATEGORIA]
	PRIMARY KEY
	NONCLUSTERED
	([CX_CORTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATTEXTIL]
	ADD
	CONSTRAINT [DF_CATTEXTIL_CX_NAME]
	DEFAULT ('') FOR [CX_NAME]
GO
ALTER TABLE [dbo].[CATTEXTIL]
	ADD
	CONSTRAINT [DF_CATTEXTIL_CX_NOMBRE]
	DEFAULT ('') FOR [CX_NOMBRE]
GO
ALTER TABLE [dbo].[CATTEXTIL] SET (LOCK_ESCALATION = TABLE)
GO
