SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BOM_ARANCEL] (
		[BA_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[MA_CODIGO]        [int] NOT NULL,
		[AR_CODIGO]        [int] NOT NULL,
		[BA_TIPOCOSTO]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BA_COSTO]         [decimal](38, 6) NOT NULL,
		[BA_GRAVABLE]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_BOM_ARANCEL]
		UNIQUE
		NONCLUSTERED
		([BA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOM_ARANCEL]
	ADD
	CONSTRAINT [PK_BOM_ARANCEL]
	PRIMARY KEY
	NONCLUSTERED
	([MA_CODIGO], [AR_CODIGO], [BA_TIPOCOSTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOM_ARANCEL]
	ADD
	CONSTRAINT [DF_BOM_ARANCEL_BA_COSTO]
	DEFAULT (0) FOR [BA_COSTO]
GO
ALTER TABLE [dbo].[BOM_ARANCEL]
	ADD
	CONSTRAINT [DF_BOM_ARANCEL_BA_GRAVABLE]
	DEFAULT ('N') FOR [BA_GRAVABLE]
GO
ALTER TABLE [dbo].[BOM_ARANCEL] SET (LOCK_ESCALATION = TABLE)
GO
