SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[RelacionFEDSecuencia] (
		[FED_INDICED]          [int] NOT NULL,
		[FED_PIDSECUENCIA]     [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RelacionFEDSecuencia] SET (LOCK_ESCALATION = TABLE)
GO
