SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TEMP_INVENTARIOS] (
		[ID]               [int] IDENTITY(1, 1) NOT NULL,
		[MA_CODIGO]        [int] NULL,
		[PI_FOLIO]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PI_FECHA]         [datetime] NULL,
		[PID_INDICED]      [int] NULL,
		[NOPARTE]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PID_SALDOGEN]     [decimal](38, 6) NOT NULL,
		[FED_SALDOGEN]     [decimal](38, 6) NOT NULL,
		[END_SALDOGEN]     [decimal](38, 6) NOT NULL,
		[TIPO]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MA_GENERICO]      [int] NULL,
		CONSTRAINT [IX_TEMP_INVENTARIOS]
		UNIQUE
		NONCLUSTERED
		([ID])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMP_INVENTARIOS]
	ADD
	CONSTRAINT [DF_TEMP_INVENTARIOS_END_SALDOGEN]
	DEFAULT (0) FOR [END_SALDOGEN]
GO
ALTER TABLE [dbo].[TEMP_INVENTARIOS]
	ADD
	CONSTRAINT [DF_TEMP_INVENTARIOS_FED_SALDOGEN]
	DEFAULT (0) FOR [FED_SALDOGEN]
GO
ALTER TABLE [dbo].[TEMP_INVENTARIOS]
	ADD
	CONSTRAINT [DF_TEMP_INVENTARIOS_PID_SALDOGEN]
	DEFAULT (0) FOR [PID_SALDOGEN]
GO
ALTER TABLE [dbo].[TEMP_INVENTARIOS] SET (LOCK_ESCALATION = TABLE)
GO
