SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CENTROCOSTO] (
		[CC_CODIGO]     [int] IDENTITY(1, 1) NOT NULL,
		[CC_DESC]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CC_MO]         [decimal](38, 6) NOT NULL,
		[CC_GASIND]     [decimal](38, 6) NULL,
		CONSTRAINT [IX_CENTROCOSTO]
		UNIQUE
		NONCLUSTERED
		([CC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CENTROCOSTO]
	ADD
	CONSTRAINT [PK_CENTROCOSTO]
	PRIMARY KEY
	NONCLUSTERED
	([CC_DESC])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CENTROCOSTO] SET (LOCK_ESCALATION = TABLE)
GO
