SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ADUANA] (
		[AD_CODIGO]      [int] IDENTITY(1, 1) NOT NULL,
		[AD_CLAVE]       [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AD_SECCION]     [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AD_NOMBRE]      [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_ADUANA]
		UNIQUE
		NONCLUSTERED
		([AD_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADUANA]
	ADD
	CONSTRAINT [PK_ADUANA]
	PRIMARY KEY
	NONCLUSTERED
	([AD_CLAVE], [AD_SECCION])
	ON [PRIMARY]
GO
CREATE CLUSTERED INDEX [IX_ADUANA_1]
	ON [dbo].[ADUANA] ([AD_CODIGO], [AD_CLAVE], [AD_SECCION])
	WITH ( FILLFACTOR = 90)
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADUANA] SET (LOCK_ESCALATION = TABLE)
GO
