SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMENTOAVANCE] (
		[DSK_MENSAJENO]     [decimal](38, 6) NOT NULL,
		[DSK_INFO]          [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DSK_INFOING]       [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DSK_HORA]          [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMENTOAVANCE] SET (LOCK_ESCALATION = TABLE)
GO
