SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPDETCUENTA] (
		[PIUD_CODIGO]               [int] IDENTITY(1, 1) NOT NULL,
		[PIB_INDICEB]               [int] NOT NULL,
		[PI_CODIGO]                 [int] NOT NULL,
		[BAN_CODIGO]                [smallint] NOT NULL,
		[PIUD_NOCUENTA]             [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PIUD_FOLIOCONSTANCIA]      [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PIUD_FECHACONSTANCIA]      [datetime] NULL,
		[PIUD_TIPOCUENTA]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PIUD_CLAVEGARANTIA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PIUD_VALORUNIT_TITULO]     [decimal](38, 6) NULL,
		[PIUD_IMPORTETOTAL]         [decimal](38, 6) NULL,
		[PIUD_CANTIDAD]             [decimal](38, 6) NULL,
		[PIUD_CANTTITULOS]          [decimal](38, 6) NULL,
		CONSTRAINT [IX_PEDIMPDETCUENTA]
		UNIQUE
		NONCLUSTERED
		([PIUD_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPDETCUENTA]
	ADD
	CONSTRAINT [PK_PEDIMPDETCUENTA]
	PRIMARY KEY
	CLUSTERED
	([PIB_INDICEB], [BAN_CODIGO], [PIUD_NOCUENTA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPDETCUENTA] SET (LOCK_ESCALATION = TABLE)
GO
