SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOCALIDADALM] (
		[LOC_CODIGO]     [int] IDENTITY(1, 1) NOT NULL,
		[LOC_NOMBRE]     [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FALM_CORTO]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_LOCALIDADALM]
		UNIQUE
		NONCLUSTERED
		([LOC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOCALIDADALM]
	ADD
	CONSTRAINT [PK_LOCALIDADALM]
	PRIMARY KEY
	NONCLUSTERED
	([LOC_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOCALIDADALM] SET (LOCK_ESCALATION = TABLE)
GO
