SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ACTUALIZAMASA] (
		[AM_CODIGO]         [int] NOT NULL,
		[AM_NOMBRESP]       [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AM_TABLAFECTA]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AM_DESC]           [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_ACTUALIZAMASA]
		UNIQUE
		CLUSTERED
		([AM_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTUALIZAMASA]
	ADD
	CONSTRAINT [PK_ACTUALIZAMASA]
	PRIMARY KEY
	NONCLUSTERED
	([AM_NOMBRESP])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTUALIZAMASA] SET (LOCK_ESCALATION = TABLE)
GO
