SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ALMACEN] (
		[ALM_CODIGO]           [smallint] NOT NULL,
		[ALM_CORTO]            [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ALM_NOMBRE]           [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ALM_NAME]             [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TAL_CODIGO]           [int] NOT NULL,
		[ALM_OBSERVA]          [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ALM_UBICACION]        [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ALM_TEL]              [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ALM_FAX]              [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ALM_EMAIL]            [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ALM_SOLOREVISION]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ALM_CANTANAQUEL]      [smallint] NULL,
		[ALM_USALOCALIDAD]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALMACEN]
	ADD
	CONSTRAINT [PK_ALMACEN]
	PRIMARY KEY
	NONCLUSTERED
	([ALM_CORTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALMACEN]
	ADD
	CONSTRAINT [DF_ALMACEN_ALM_SOLOREVISION]
	DEFAULT ('S') FOR [ALM_SOLOREVISION]
GO
ALTER TABLE [dbo].[ALMACEN]
	ADD
	CONSTRAINT [DF_ALMACEN_ALM_USALOCALIDAD]
	DEFAULT ('N') FOR [ALM_USALOCALIDAD]
GO
ALTER TABLE [dbo].[ALMACEN] SET (LOCK_ESCALATION = TABLE)
GO
