SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MENSAJESIMPORTACIONRESINAS] (
		[MR_Codigo]      [int] IDENTITY(1, 1) NOT NULL,
		[IR_Codigo]      [int] NULL,
		[MR_Mensaje]     [varchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_MENSAJESIMPORTACIONRESINAS]
		UNIQUE
		NONCLUSTERED
		([MR_Codigo])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MENSAJESIMPORTACIONRESINAS]
	ADD
	CONSTRAINT [PK_MENSAJESIMPORTACIONRESINAS]
	PRIMARY KEY
	CLUSTERED
	([MR_Codigo])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MENSAJESIMPORTACIONRESINAS] SET (LOCK_ESCALATION = TABLE)
GO
