SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ENTSALALMDET] (
		[EN_CODIGO]            [int] NOT NULL,
		[END_INDICED]          [int] NOT NULL,
		[END_NOPARTE]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[END_NOMBRE]           [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[END_NAME]             [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[END_CANT]             [decimal](38, 6) NOT NULL,
		[END_CANTORIGINAL]     [decimal](38, 6) NULL,
		[END_COS_UNI]          [decimal](38, 6) NOT NULL,
		[END_COS_TOT]          [decimal](38, 6) NOT NULL,
		[END_PRECIOVENTA]      [decimal](38, 6) NOT NULL,
		[END_PRECIOCOMPRA]     [decimal](38, 6) NOT NULL,
		[TI_CODIGO]            [int] NULL,
		[END_CAN_ALM]          [decimal](38, 6) NOT NULL,
		[ME_CODIGO]            [int] NOT NULL,
		[MA_CODIGO]            [int] NOT NULL,
		[ME_ALM]               [int] NULL,
		[END_OBSERVA]          [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[EQ_ALM]               [decimal](28, 14) NOT NULL,
		[END_CUENTA]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_CODIGO]            [int] NULL,
		[FI_FOLIO]             [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FID_INDICED]          [int] NULL,
		[CL_CODIGO]            [int] NULL,
		[OT_CODIGO]            [int] NULL,
		[END_NOORDEN]          [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_ORD_COMP]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[OR_CODIGO]            [int] NULL,
		[ORD_INDICED]          [int] NULL,
		[END_FECHARECSAL]      [datetime] NULL,
		[END_DEFTXT1]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_DEFTXT2]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_DEFNO3]           [decimal](38, 6) NULL,
		[END_DEFNO4]           [decimal](38, 6) NULL,
		[END_FECHA_STRUCT]     [datetime] NULL,
		[END_TIPODESCARGA]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[END_NOTACREDITO]      [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MA_EMPAQUE]           [int] NULL,
		[END_CANTEMP]          [decimal](38, 6) NOT NULL,
		[END_TIPOENTSAL]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_LOTE]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_ESTATUSMAT]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_FAMILIA]           [int] NULL,
		[END_CONTROLLOTE]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_TIP_ENS]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_TRANSFORMADO]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[OTD_INDICED]          [int] NULL,
		[END_PASILLO]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_NIVEL]            [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_LOCALIDAD]        [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [PK_ENTSALALMDET]
	PRIMARY KEY
	NONCLUSTERED
	([END_INDICED])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_CANT]
	DEFAULT (0) FOR [END_CANT]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_CANTEMP]
	DEFAULT (0) FOR [END_CANTEMP]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_CANTORIGINAL]
	DEFAULT (0) FOR [END_CANTORIGINAL]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_COS_UNI]
	DEFAULT (0) FOR [END_COS_UNI]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_DEFTXT1]
	DEFAULT ('') FOR [END_DEFTXT1]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_DEFTXT2]
	DEFAULT ('') FOR [END_DEFTXT2]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_ESTATUSMAT]
	DEFAULT ('N') FOR [END_ESTATUSMAT]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_LOCALIDAD]
	DEFAULT ('') FOR [END_LOCALIDAD]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_NIVEL]
	DEFAULT ('') FOR [END_NIVEL]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_PASILLO]
	DEFAULT ('') FOR [END_PASILLO]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_PRECIOCOMPRA]
	DEFAULT (0) FOR [END_PRECIOCOMPRA]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_PRECIOVENTA]
	DEFAULT (0) FOR [END_PRECIOVENTA]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_TIPODESCARGA]
	DEFAULT ('N') FOR [END_TIPODESCARGA]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_TIPOENTSAL]
	DEFAULT ('N') FOR [END_TIPOENTSAL]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_END_TRANSFORMADO]
	DEFAULT ('N') FOR [END_TRANSFORMADO]
GO
ALTER TABLE [dbo].[ENTSALALMDET]
	ADD
	CONSTRAINT [DF_ENTSALALMDET_EQ_ALM]
	DEFAULT (1) FOR [EQ_ALM]
GO
ALTER TABLE [dbo].[ENTSALALMDET] SET (LOCK_ESCALATION = TABLE)
GO
