SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURACOSTSUB] (
		[TI_CODIGO]     [smallint] NOT NULL,
		[CFC_TIPO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURACOSTSUB]
	ADD
	CONSTRAINT [PK_CONFIGURACOSTSUB]
	PRIMARY KEY
	NONCLUSTERED
	([TI_CODIGO], [CFC_TIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURACOSTSUB] SET (LOCK_ESCALATION = TABLE)
GO
