SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CERTORIGMPDET] (
		[CMP_CODIGO]          [int] NOT NULL,
		[MA_CODIGO]           [int] NOT NULL,
		[CMP_CLASE]           [int] NULL,
		[CMP_FABRICA]         [int] NULL,
		[CMP_CRITERIO]        [int] NULL,
		[CMP_NETCOST]         [int] NULL,
		[CMP_OTRASINST]       [int] NULL,
		[CMP_CANT]            [decimal](38, 6) NULL,
		[ME_CODIGO]           [int] NULL,
		[CMP_FACTURA]         [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PA_CLASE]            [int] NOT NULL,
		[AR_CODIGO]           [int] NULL,
		[AR_ALTER]            [int] NULL,
		[PR_CODIGO]           [int] NULL,
		[CMP_FRACCION]        [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CMP_FRACCIONALT]     [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CMP_DESCRIP]         [varchar](305) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CMP_NOPARTE]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CMP_NOPARTEAUX]      [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CERTORIGMPDET]
	ADD
	CONSTRAINT [PK_CERTORIGMPNOPARTE]
	PRIMARY KEY
	NONCLUSTERED
	([CMP_CODIGO], [MA_CODIGO], [CMP_FACTURA], [PA_CLASE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CERTORIGMPDET]
	ADD
	CONSTRAINT [DF_CERTORIGMPDET_CMP_CLASE]
	DEFAULT (1) FOR [CMP_CLASE]
GO
ALTER TABLE [dbo].[CERTORIGMPDET]
	ADD
	CONSTRAINT [DF_CERTORIGMPDET_CMP_CRITERIO]
	DEFAULT (0) FOR [CMP_CRITERIO]
GO
ALTER TABLE [dbo].[CERTORIGMPDET]
	ADD
	CONSTRAINT [DF_CERTORIGMPDET_CMP_DESCRIP]
	DEFAULT ('') FOR [CMP_DESCRIP]
GO
ALTER TABLE [dbo].[CERTORIGMPDET]
	ADD
	CONSTRAINT [DF_CERTORIGMPDET_CMP_FABRICA]
	DEFAULT (0) FOR [CMP_FABRICA]
GO
ALTER TABLE [dbo].[CERTORIGMPDET]
	ADD
	CONSTRAINT [DF_CERTORIGMPDET_CMP_FACTURA]
	DEFAULT ('') FOR [CMP_FACTURA]
GO
ALTER TABLE [dbo].[CERTORIGMPDET]
	ADD
	CONSTRAINT [DF_CERTORIGMPDET_CMP_NETCOST]
	DEFAULT (0) FOR [CMP_NETCOST]
GO
ALTER TABLE [dbo].[CERTORIGMPDET]
	ADD
	CONSTRAINT [DF_CERTORIGMPDET_PA_CLASE]
	DEFAULT (154) FOR [PA_CLASE]
GO
CREATE NONCLUSTERED INDEX [IX_CERTORIGMPDET]
	ON [dbo].[CERTORIGMPDET] ([MA_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CERTORIGMPDET_1]
	ON [dbo].[CERTORIGMPDET] ([ME_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CERTORIGMPDET_2]
	ON [dbo].[CERTORIGMPDET] ([PA_CLASE])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CERTORIGMPDET_3]
	ON [dbo].[CERTORIGMPDET] ([CMP_FRACCION])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CERTORIGMPDET_4]
	ON [dbo].[CERTORIGMPDET] ([PR_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CERTORIGMPDET] SET (LOCK_ESCALATION = TABLE)
GO
