SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPDETPERM] (
		[PIP_INDICE]      [int] NOT NULL,
		[PIB_INDICEB]     [int] NOT NULL,
		[PI_CODIGO]       [int] NOT NULL,
		[IDE_CODIGO]      [int] NULL,
		[PE_CODIGO]       [int] NOT NULL,
		[PIP_FOLIO]       [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PIP_FIRMA]       [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PIP_VALOR]       [decimal](38, 6) NULL,
		[PIP_CANT]        [decimal](38, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPDETPERM]
	ADD
	CONSTRAINT [PK_PEDIMPDETPERM]
	PRIMARY KEY
	NONCLUSTERED
	([PIB_INDICEB], [PE_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPDETPERM]
	ADD
	CONSTRAINT [DF_PEDIMPDETPERM_PIP_FIRMA]
	DEFAULT ('') FOR [PIP_FIRMA]
GO
ALTER TABLE [dbo].[PEDIMPDETPERM]
	ADD
	CONSTRAINT [DF_PEDIMPDETPERM_PIP_FOLIO]
	DEFAULT ('') FOR [PIP_FOLIO]
GO
ALTER TABLE [dbo].[PEDIMPDETPERM]
	ADD
	CONSTRAINT [DF_PEDIMPDETPERM_PIP_INDICE]
	DEFAULT ((-1)) FOR [PIP_INDICE]
GO
ALTER TABLE [dbo].[PEDIMPDETPERM] SET (LOCK_ESCALATION = TABLE)
GO
