SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ARANCELDEL] (
		[AR_CODIGO]       [int] NULL,
		[AR_FRACCION]     [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARANCELDEL] SET (LOCK_ESCALATION = TABLE)
GO
