SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONEXIONARCHIVO] (
		[ARC_CODIGO]             [int] NOT NULL,
		[ARC_DESC]               [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARC_SEPARACAMPO]        [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARC_SEPARALINEA]        [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_CODIGO]             [int] NOT NULL,
		[ARC_NOMBREARCHIVO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARC_ARCHIVO]            [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARC_FROMNOMARCHIVO]     [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARC_SIZECAMPOFIJO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ARC_SEPARADECIMAL]      [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARC_DOCMULTIPLES]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ARC_QUERYMOSTRAR]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ARC_TIPO]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONEXIONARCHIVO]
	ADD
	CONSTRAINT [PK_CONEXIONARCHIVO]
	PRIMARY KEY
	NONCLUSTERED
	([ARC_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONEXIONARCHIVO]
	ADD
	CONSTRAINT [DF_CONEXIONARCHIVO_ARC_DOCMULTIPLES]
	DEFAULT ('N') FOR [ARC_DOCMULTIPLES]
GO
ALTER TABLE [dbo].[CONEXIONARCHIVO]
	ADD
	CONSTRAINT [DF_CONEXIONARCHIVO_ARC_QUERYMOSTRAR]
	DEFAULT ('') FOR [ARC_QUERYMOSTRAR]
GO
ALTER TABLE [dbo].[CONEXIONARCHIVO] SET (LOCK_ESCALATION = TABLE)
GO
