SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CO2009] (
		[Parte]       [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Ttasa]       [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Tratado]     [float] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CO2009] SET (LOCK_ESCALATION = TABLE)
GO
