SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[RECARGO] (
		[REC_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[REC_YEAR]       [smallint] NOT NULL,
		[REC_MES]        [smallint] NOT NULL,
		[REC_TASA]       [decimal](38, 6) NULL,
		[REC_FECINI]     [datetime] NOT NULL,
		CONSTRAINT [IX_RECARGO]
		UNIQUE
		NONCLUSTERED
		([REC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECARGO]
	ADD
	CONSTRAINT [PK_RECARGO]
	PRIMARY KEY
	NONCLUSTERED
	([REC_YEAR], [REC_MES])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECARGO] SET (LOCK_ESCALATION = TABLE)
GO
