SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TEMBARQUE] (
		[TQ_CODIGO]      [smallint] IDENTITY(1, 1) NOT NULL,
		[TQ_NOMBRE]      [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TQ_NAME]        [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TQ_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TQ_MAIN]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TQ_TI_DESC]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_TEMBARQUE]
		UNIQUE
		NONCLUSTERED
		([TQ_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMBARQUE]
	ADD
	CONSTRAINT [PK_TEMBARQUE]
	PRIMARY KEY
	NONCLUSTERED
	([TQ_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TEMBARQUE] SET (LOCK_ESCALATION = TABLE)
GO
