SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPDOCIMAGEN] (
		[FER_CODIGO]            [int] NOT NULL,
		[FEM_ORDEN]             [int] NOT NULL,
		[FEM_NOMBREARCHIVO]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FEM_RUTAARCHIVO]       [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDOCIMAGEN]
	ADD
	CONSTRAINT [PK_FACTEXPDOCIMAGEN]
	PRIMARY KEY
	CLUSTERED
	([FER_CODIGO], [FEM_NOMBREARCHIVO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDOCIMAGEN] SET (LOCK_ESCALATION = TABLE)
GO
