SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUB_Importado] (
		[MA_NOPARTE]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CP_CLAVE]       [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUB_Importado] SET (LOCK_ESCALATION = TABLE)
GO
