SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DECANUALNVA] (
		[DAN_CODIGO]                      [int] NOT NULL,
		[DAN_INICIO]                      [datetime] NOT NULL,
		[DAN_FINAL]                       [datetime] NOT NULL,
		[CL_CODIGO]                       [int] NOT NULL,
		[DAN_1ERANIO]                     [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DAN_TOTADMIN1]                   [int] NULL,
		[DAN_TOTOBRERO1]                  [int] NULL,
		[DAN_2DOANIO]                     [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DAN_TOTADMIN2]                   [int] NULL,
		[DAN_TOTOBRERO2]                  [int] NULL,
		[DAN_ORIGENINVER1]                [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DAN_VALORINVER1]                 [decimal](38, 6) NULL,
		[DAN_ORIGENINVER2]                [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DAN_VALORINVER2]                 [decimal](38, 6) NULL,
		[DAN_IMPTEMPACTFIJUSD]            [decimal](38, 6) NOT NULL,
		[DAN_IMPTEMPACTFIJ]               [decimal](38, 6) NOT NULL,
		[DAN_IMPTEMPMATUSD]               [decimal](38, 6) NOT NULL,
		[DAN_IMPTEMPMAT]                  [decimal](38, 6) NOT NULL,
		[DAN_IMPDEFINITIVASACTFIJUSD]     [decimal](38, 6) NOT NULL,
		[DAN_IMPDEFINITIVASACTFIJ]        [decimal](38, 6) NOT NULL,
		[DAN_IMPDEFINITIVASMATUSD]        [decimal](38, 6) NOT NULL,
		[DAN_IMPDEFINITIVASMAT]           [decimal](38, 6) NOT NULL,
		[DAN_MERCADONACACTFIJUSD]         [decimal](38, 6) NOT NULL,
		[DAN_MERCADONACACTFIJ]            [decimal](38, 6) NOT NULL,
		[DAN_MERCADONACMATUSD]            [decimal](38, 6) NOT NULL,
		[DAN_MERCADONACMAT]               [decimal](38, 6) NOT NULL,
		[DAN_IMPTEMPCATEG1]               [decimal](38, 6) NOT NULL,
		[DAN_IMPTEMPCATEG2]               [decimal](38, 6) NOT NULL,
		[DAN_IMPTEMPCATEG3Y4]             [decimal](38, 6) NOT NULL,
		[DAN_IMPTEMPINDCATEG1]            [decimal](38, 6) NOT NULL,
		[DAN_IMPTEMPINDCATEG2]            [decimal](38, 6) NOT NULL,
		[DAN_IMPTEMPINDCATEG3Y4]          [decimal](38, 6) NOT NULL,
		[DAN_VENTATOTAL]                  [decimal](38, 6) NOT NULL,
		[DAN_TOTALEXP]                    [decimal](38, 6) NOT NULL,
		[DAN_TOTALIMP]                    [decimal](38, 6) NOT NULL,
		[DAN_IMPUESTOTALPAG]              [decimal](38, 6) NOT NULL,
		[DAN_IMPUESTOTALXPAG]             [decimal](38, 6) NOT NULL,
		[DAN_VENTATOTALISR]               [decimal](38, 6) NOT NULL,
		[DAN_TOTALEXPISR]                 [decimal](38, 6) NOT NULL,
		[DAN_TOTALIMPISR]                 [decimal](38, 6) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [PK_DECANUALNVA]
	PRIMARY KEY
	NONCLUSTERED
	([DAN_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_CL_CODIGO]
	DEFAULT (1) FOR [CL_CODIGO]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPDEFINITIVASACTFIJ]
	DEFAULT (0) FOR [DAN_IMPDEFINITIVASACTFIJ]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPDEFINITIVASACTFIJUSD]
	DEFAULT (0) FOR [DAN_IMPDEFINITIVASACTFIJUSD]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPDEFINITIVASMAT]
	DEFAULT (0) FOR [DAN_IMPDEFINITIVASMAT]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPDEFINITIVASMATUSD]
	DEFAULT (0) FOR [DAN_IMPDEFINITIVASMATUSD]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPACTFIJ]
	DEFAULT (0) FOR [DAN_IMPTEMPACTFIJ]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPACTFIJUSD]
	DEFAULT (0) FOR [DAN_IMPTEMPACTFIJUSD]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPCATEG1]
	DEFAULT (0) FOR [DAN_IMPTEMPCATEG1]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPCATEG2]
	DEFAULT (0) FOR [DAN_IMPTEMPCATEG2]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPCATEG3Y4]
	DEFAULT (0) FOR [DAN_IMPTEMPCATEG3Y4]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPINDCATEG1]
	DEFAULT (0) FOR [DAN_IMPTEMPINDCATEG1]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPINDCATEG2]
	DEFAULT (0) FOR [DAN_IMPTEMPINDCATEG2]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPINDCATEG3Y4]
	DEFAULT (0) FOR [DAN_IMPTEMPINDCATEG3Y4]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPMAT]
	DEFAULT (0) FOR [DAN_IMPTEMPMAT]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPTEMPMATUSD]
	DEFAULT (0) FOR [DAN_IMPTEMPMATUSD]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPUESTOTALPAG]
	DEFAULT (0) FOR [DAN_IMPUESTOTALPAG]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_IMPUESTOTALXPAG]
	DEFAULT (0) FOR [DAN_IMPUESTOTALXPAG]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_MERCADONACACTFIJ]
	DEFAULT (0) FOR [DAN_MERCADONACACTFIJ]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_MERCADONACACTFIJUSD]
	DEFAULT (0) FOR [DAN_MERCADONACACTFIJUSD]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_MERCADONACMAT]
	DEFAULT (0) FOR [DAN_MERCADONACMAT]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_MERCADONACMATUSD]
	DEFAULT (0) FOR [DAN_MERCADONACMATUSD]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_TOTALEXP]
	DEFAULT (0) FOR [DAN_TOTALEXP]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_TOTALEXPISR]
	DEFAULT (0) FOR [DAN_TOTALEXPISR]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_TOTALIMP]
	DEFAULT (0) FOR [DAN_TOTALIMP]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_TOTALIMPISR]
	DEFAULT (0) FOR [DAN_TOTALIMPISR]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_VALORINVER2]
	DEFAULT (0) FOR [DAN_VALORINVER2]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_VENTATOTAL]
	DEFAULT (0) FOR [DAN_VENTATOTAL]
GO
ALTER TABLE [dbo].[DECANUALNVA]
	ADD
	CONSTRAINT [DF_DECANUALNVA_DAN_VENTATOTALISR]
	DEFAULT (0) FOR [DAN_VENTATOTALISR]
GO
ALTER TABLE [dbo].[DECANUALNVA] SET (LOCK_ESCALATION = TABLE)
GO
