SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DESTRUCCIONDESP] (
		[FE_CODIGO]         [int] NOT NULL,
		[DD_HORA]           [smallint] NULL,
		[DD_ENCARGADO]      [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DD_TESTIGO1]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DD_TESTIGO2]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DD_TIPOIDENT1]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DD_TIPOIDENT2]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DD_IDENTNO1]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DD_IDENTNO2]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DD_FECHA1]         [datetime] NULL,
		[DD_FECHA2]         [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DESTRUCCIONDESP]
	ADD
	CONSTRAINT [PK_DESTRUCCIONDESP]
	PRIMARY KEY
	NONCLUSTERED
	([FE_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[DESTRUCCIONDESP]
	ADD
	CONSTRAINT [DF_DESTRUCCIONDESP_DD_ENCARGADO]
	DEFAULT ('') FOR [DD_ENCARGADO]
GO
ALTER TABLE [dbo].[DESTRUCCIONDESP]
	ADD
	CONSTRAINT [DF_DESTRUCCIONDESP_DD_IDENTNO1]
	DEFAULT ('') FOR [DD_IDENTNO1]
GO
ALTER TABLE [dbo].[DESTRUCCIONDESP]
	ADD
	CONSTRAINT [DF_DESTRUCCIONDESP_DD_IDENTNO2]
	DEFAULT ('') FOR [DD_IDENTNO2]
GO
ALTER TABLE [dbo].[DESTRUCCIONDESP]
	ADD
	CONSTRAINT [DF_DESTRUCCIONDESP_DD_TESTIGO1]
	DEFAULT ('') FOR [DD_TESTIGO1]
GO
ALTER TABLE [dbo].[DESTRUCCIONDESP]
	ADD
	CONSTRAINT [DF_DESTRUCCIONDESP_DD_TESTIGO2]
	DEFAULT ('') FOR [DD_TESTIGO2]
GO
ALTER TABLE [dbo].[DESTRUCCIONDESP]
	ADD
	CONSTRAINT [DF_DESTRUCCIONDESP_DD_TIPOIDENT1]
	DEFAULT ('') FOR [DD_TIPOIDENT1]
GO
ALTER TABLE [dbo].[DESTRUCCIONDESP]
	ADD
	CONSTRAINT [DF_DESTRUCCIONDESP_DD_TIPOIDENT2]
	DEFAULT ('') FOR [DD_TIPOIDENT2]
GO
ALTER TABLE [dbo].[DESTRUCCIONDESP] SET (LOCK_ESCALATION = TABLE)
GO
