SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DIR_CLIENTE] (
		[DI_INDICE]         [int] IDENTITY(1, 1) NOT NULL,
		[CL_CODIGO]         [int] NOT NULL,
		[DI_IDENTIF]        [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DI_CALLE]          [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DI_NOEXT]          [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DI_NOINT]          [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DI_COL]            [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DI_CP]             [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DI_POBOX]          [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DI_CIUDAD]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DI_MUNIC]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ES_CODIGO]         [int] NULL,
		[PA_CODIGO]         [int] NULL,
		[DI_REFER]          [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DI_TEL1]           [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DI_TEL2]           [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DI_FAX]            [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DI_FISCAL]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DI_EMAIL]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PU_CODIGO]         [int] NOT NULL,
		[ADL_IDADMON]       [smallint] NULL,
		[DI_COD_FAB]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DI_LOCPLANTA]      [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DI_PLANTA]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DI_TIPO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MU_CODIGO]         [int] NULL,
		[DI_FECHAINI]       [datetime] NOT NULL,
		[DI_FECHAFIN]       [datetime] NOT NULL,
		[DI_ENVIARSAAI]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_DIR_CLIENTE]
		UNIQUE
		NONCLUSTERED
		([DI_INDICE])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [PK_DIR_CLIENTE]
	PRIMARY KEY
	NONCLUSTERED
	([CL_CODIGO], [DI_IDENTIF])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_ENVIARSAAI]
	DEFAULT ('S') FOR [DI_ENVIARSAAI]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_FAX]
	DEFAULT ('') FOR [DI_FAX]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_FECHAFIN]
	DEFAULT ('01/01/9999') FOR [DI_FECHAFIN]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_FECHAINI]
	DEFAULT ('01/01/1999') FOR [DI_FECHAINI]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_FISCAL]
	DEFAULT ('N') FOR [DI_FISCAL]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_NOINT]
	DEFAULT ('') FOR [DI_NOINT]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_POBOX]
	DEFAULT ('') FOR [DI_POBOX]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_TEL1]
	DEFAULT ('') FOR [DI_TEL1]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_TEL2]
	DEFAULT ('') FOR [DI_TEL2]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_DI_TIPO]
	DEFAULT ('2') FOR [DI_TIPO]
GO
ALTER TABLE [dbo].[DIR_CLIENTE]
	ADD
	CONSTRAINT [DF_DIR_CLIENTE_PU_CODIGO]
	DEFAULT (2775) FOR [PU_CODIGO]
GO
ALTER TABLE [dbo].[DIR_CLIENTE] SET (LOCK_ESCALATION = TABLE)
GO
