SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTIMPDEF] (
		[FI_CODIGO]      [int] NOT NULL,
		[FI_DEFTXT1]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_DEFTXT2]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_DEFNO1]      [int] NOT NULL,
		[FI_DEFNO2]      [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPDEF]
	ADD
	CONSTRAINT [PK_FACTIMPDEF]
	PRIMARY KEY
	CLUSTERED
	([FI_CODIGO])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPDEF]
	ADD
	CONSTRAINT [DF_FACTIMPDEF_MA_DEFNO1]
	DEFAULT (0) FOR [FI_DEFNO1]
GO
ALTER TABLE [dbo].[FACTIMPDEF]
	ADD
	CONSTRAINT [DF_FACTIMPDEF_MA_DEFNO2]
	DEFAULT (0) FOR [FI_DEFNO2]
GO
ALTER TABLE [dbo].[FACTIMPDEF]
	ADD
	CONSTRAINT [DF_FACTIMPDEF_MA_DEFTXT1]
	DEFAULT ('') FOR [FI_DEFTXT1]
GO
ALTER TABLE [dbo].[FACTIMPDEF]
	ADD
	CONSTRAINT [DF_FACTIMPDEF_MA_DEFTXT2]
	DEFAULT ('') FOR [FI_DEFTXT2]
GO
ALTER TABLE [dbo].[FACTIMPDEF] SET (LOCK_ESCALATION = TABLE)
GO
