SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[INVENTARIOFISDET] (
		[IVF_CODIGO]             [int] NOT NULL,
		[IVFD_INDICED]           [int] NOT NULL,
		[MA_CODIGO]              [int] NOT NULL,
		[IVFD_NOPARTE]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IVFD_NOMBRE]            [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IVFD_NAME]              [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IVFD_CANT]              [decimal](38, 6) NOT NULL,
		[ME_CODIGO]              [int] NOT NULL,
		[MA_GENERICO]            [int] NOT NULL,
		[ME_GENERICO]            [int] NOT NULL,
		[EQ_GENERICO]            [decimal](28, 14) NOT NULL,
		[IVFD_CANT_TRANS]        [decimal](38, 6) NOT NULL,
		[IVFD_CANT_SINTRANS]     [decimal](38, 6) NOT NULL,
		[IVFD_CAN_GEN]           [decimal](38, 6) NOT NULL,
		[TI_CODIGO]              [int] NOT NULL,
		[IVFD_CONCILIADO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IVFD_OBSERVA]           [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IVFD_FEC_STRUCT]        [datetime] NULL,
		[IVFD_RETRABAJO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [PK_INVENTARIOFISDET]
	PRIMARY KEY
	NONCLUSTERED
	([IVFD_INDICED])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_EQ_GENERICO]
	DEFAULT (1) FOR [EQ_GENERICO]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_IVFD_CAN_GEN]
	DEFAULT (0) FOR [IVFD_CAN_GEN]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_IVFD_CANT]
	DEFAULT (0) FOR [IVFD_CANT]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_IVFD_CANT_SINTRANS]
	DEFAULT (0) FOR [IVFD_CANT_SINTRANS]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_IVFD_CANT_TRANS]
	DEFAULT (0) FOR [IVFD_CANT_TRANS]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_IVFD_CONCILIADO]
	DEFAULT ('N') FOR [IVFD_CONCILIADO]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_IVFD_RETRABAJO]
	DEFAULT ('N') FOR [IVFD_RETRABAJO]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_MA_GENERICO]
	DEFAULT (0) FOR [MA_GENERICO]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_ME_GENERICO]
	DEFAULT (0) FOR [ME_GENERICO]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET]
	ADD
	CONSTRAINT [DF_INVENTARIOFISDET_TI_CODIGO]
	DEFAULT (0) FOR [TI_CODIGO]
GO
ALTER TABLE [dbo].[INVENTARIOFISDET] SET (LOCK_ESCALATION = TABLE)
GO
