SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ERRORTRASLADO] (
		[ET_TIPO]            [int] NOT NULL,
		[ET_DESCRIPCION]     [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERRORTRASLADO]
	ADD
	CONSTRAINT [PK_ERRORTRASLADO_1]
	PRIMARY KEY
	CLUSTERED
	([ET_TIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERRORTRASLADO] SET (LOCK_ESCALATION = TABLE)
GO
