SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[FACTEXPINCREMENTA] (
		[FE_CODIGO]     [int] NOT NULL,
		[IC_CODIGO]     [smallint] NOT NULL,
		[FEI_VALOR]     [decimal](38, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPINCREMENTA]
	ADD
	CONSTRAINT [PK_FACTEXPINCREMENTA]
	PRIMARY KEY
	CLUSTERED
	([FE_CODIGO], [IC_CODIGO])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPINCREMENTA] SET (LOCK_ESCALATION = TABLE)
GO
