SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTROEMPAQUEADICIONAL] (
		[MA_EMPAQUE]        [int] NOT NULL,
		[MA_CODIGO]         [int] NOT NULL,
		[MA_NOPARTE]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FEAD_CANTIDAD]     [decimal](38, 6) NOT NULL,
		[MA_GENERICO]       [int] NULL,
		[EQ_GEN]            [decimal](28, 14) NULL,
		[ME_CODIGO]         [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROEMPAQUEADICIONAL]
	ADD
	CONSTRAINT [PK_MaestroEmpaqueAdicional]
	PRIMARY KEY
	NONCLUSTERED
	([MA_EMPAQUE], [MA_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROEMPAQUEADICIONAL] SET (LOCK_ESCALATION = TABLE)
GO
