SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPDET_InformacionBaseParaCalcularPagoArt303] (
		[FED_INDICED]           [int] NOT NULL,
		[FE_CODIGO]             [int] NOT NULL,
		[MA_CODIGO]             [int] NOT NULL,
		[FED_NOMBRE]            [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_NOPARTE]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_NAME]              [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_CODIGO]             [int] NULL,
		[FED_OBSERVA]           [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_CANT]              [decimal](38, 6) NOT NULL,
		[FED_GRA_MP]            [decimal](38, 6) NOT NULL,
		[FED_GRA_MO]            [decimal](38, 6) NOT NULL,
		[FED_GRA_EMP]           [decimal](38, 6) NOT NULL,
		[FED_GRA_ADD]           [decimal](38, 6) NOT NULL,
		[FED_GRA_GI]            [decimal](38, 6) NOT NULL,
		[FED_GRA_GI_MX]         [decimal](38, 6) NOT NULL,
		[FED_NG_MP]             [decimal](38, 6) NOT NULL,
		[FED_NG_EMP]            [decimal](38, 6) NOT NULL,
		[FED_NG_ADD]            [decimal](38, 6) NOT NULL,
		[FED_NG_USA]            [decimal](38, 6) NOT NULL,
		[FED_COS_UNI]           [decimal](38, 6) NOT NULL,
		[FED_COS_TOT]           [decimal](38, 6) NOT NULL,
		[FED_PES_UNI]           [decimal](38, 6) NOT NULL,
		[FED_PES_NET]           [decimal](38, 6) NOT NULL,
		[FED_PES_BRU]           [decimal](38, 6) NOT NULL,
		[FED_PES_UNILB]         [decimal](38, 6) NOT NULL,
		[FED_PES_NETLB]         [decimal](38, 6) NOT NULL,
		[FED_PES_BRULB]         [decimal](38, 6) NOT NULL,
		[FED_SEC_IMP]           [smallint] NULL,
		[FED_DEF_TIP]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_POR_DEF]           [decimal](38, 6) NOT NULL,
		[FED_LOTE]              [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AR_IMPMX]              [int] NOT NULL,
		[AR_EXPMX]              [int] NOT NULL,
		[AR_IMPFO]              [int] NOT NULL,
		[FED_CON_PED]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_GENERICO]           [int] NOT NULL,
		[PA_CODIGO]             [int] NOT NULL,
		[LE_CODIGO]             [int] NULL,
		[LED_INDICED]           [int] NULL,
		[EX_CODIGO]             [int] NULL,
		[FED_ORD_COMP]          [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_NOORDEN]           [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_USO_COMMINV]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EQ_GEN]                [decimal](28, 14) NOT NULL,
		[EQ_IMPFO]              [decimal](28, 14) NOT NULL,
		[EQ_EXPMX]              [decimal](28, 14) NOT NULL,
		[TI_CODIGO]             [smallint] NOT NULL,
		[FED_TENVIO]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_INBOND]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_TIPOINBOND]        [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_RATEEXPMX]         [decimal](38, 6) NOT NULL,
		[FED_RATEIMPFO]         [decimal](38, 6) NOT NULL,
		[FED_RELEMP]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_FECHA_STRUCT]      [datetime] NULL,
		[FED_DISCHARGE]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LE_FOLIO]              [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SPI_CODIGO]            [smallint] NOT NULL,
		[FED_SALDO]             [decimal](38, 6) NOT NULL,
		[FED_RETRABAJO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ADE_CODIGO]            [int] NULL,
		[MA_EMPAQUE]            [int] NOT NULL,
		[FED_CANTEMP]           [decimal](38, 6) NOT NULL,
		[FED_FAC_NUM]           [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_FEC_ENV]           [datetime] NULL,
		[FED_CON_CERTORIG]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_COS_UNI_CO]        [decimal](38, 6) NOT NULL,
		[FED_GRA_MAT_CO]        [decimal](38, 6) NOT NULL,
		[FED_EMP_CO]            [decimal](38, 6) NOT NULL,
		[FED_NG_MAT_CO]         [decimal](38, 6) NOT NULL,
		[FED_VA_CO]             [decimal](38, 6) NOT NULL,
		[FED_CANTGEN]           [decimal](38, 6) NOT NULL,
		[MO_CODIGO]             [int] NULL,
		[FED_DESCARGADO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_PARTTYPE]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ME_GENERICO]           [int] NOT NULL,
		[FED_TIP_ENS]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PID_INDICED]           [int] NOT NULL,
		[MA_NOPARTECL]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ME_AREXPMX]            [int] NOT NULL,
		[FED_NAFTA]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_DEFTXT1]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_DEFTXT2]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_DEFNO3]            [decimal](38, 6) NULL,
		[FED_DEFNO4]            [decimal](38, 6) NULL,
		[PID_INDICEDLIGA]       [int] NOT NULL,
		[PID_INDICEDLIGAR1]     [int] NOT NULL,
		[TCO_CODIGO]            [smallint] NOT NULL,
		[PI_ORIGENKITPADRE]     [int] NOT NULL,
		[CS_CODIGO]             [smallint] NOT NULL,
		[SE_CODIGO]             [smallint] NOT NULL,
		[FED_RELCAJAS]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_INDICED]           [int] NULL,
		[EN_CODIGO]             [int] NULL,
		[FED_SALDOTRANS]        [decimal](38, 6) NOT NULL,
		[FED_USOTRANS]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_USOSALDO]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CL_CODIGO]             [int] NULL,
		[MA_STRUCT]             [int] NULL,
		[FED_DESTNAFTA]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AR_ORIG]               [int] NOT NULL,
		[AR_NG_EMP]             [int] NOT NULL,
		[FED_NOPARTEAUX]        [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ETA_CODIGO]            [int] NOT NULL,
		[FED_NOPARTESTRUCT]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_NG_MX]             [decimal](38, 6) NOT NULL,
		[FED_GENERA_EMPDET]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_GRAVA_VA]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_PARTIDA]           [int] NULL,
		[FED_SECF4]             [int] NULL,
		[FED_PRECIO_UNI]        [decimal](38, 6) NULL,
		[FED_PRECIO_TOT]        [decimal](38, 6) NULL,
		[FED_PIDSECUENCIA]      [int] NULL,
		[FED_FOLIO_CERT]        [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_POR_CERT]          [decimal](38, 6) NULL,
		[PedExp_codigo]         [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDET_InformacionBaseParaCalcularPagoArt303] SET (LOCK_ESCALATION = TABLE)
GO
