SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTIMPEMPAQUE] (
		[FIE_INDICE]          [int] NOT NULL,
		[FI_CODIGO]           [int] NOT NULL,
		[FIE_EMP2_CANT]       [decimal](38, 6) NULL,
		[FIE_TOT_EMP1]        [decimal](38, 6) NULL,
		[FIE_TOT_EMP2]        [decimal](38, 6) NULL,
		[MA_EMP1]             [int] NULL,
		[MA_EMP2]             [int] NULL,
		[FIE_RELEMPAQUE]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIE_RELDETALLE]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FIE_GENERA_EMP1]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIE_CANT_DESP1]      [decimal](38, 6) NOT NULL,
		[FIE_GENERA_EMP2]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIE_CANT_DESP2]      [decimal](38, 6) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPEMPAQUE]
	ADD
	CONSTRAINT [PK_FACTIMPEMPAQUE]
	PRIMARY KEY
	NONCLUSTERED
	([FIE_INDICE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPEMPAQUE]
	ADD
	CONSTRAINT [DF_FACTIMPEMPAQUE_FIE_CANT_DESP1]
	DEFAULT (0) FOR [FIE_CANT_DESP1]
GO
ALTER TABLE [dbo].[FACTIMPEMPAQUE]
	ADD
	CONSTRAINT [DF_FACTIMPEMPAQUE_FIE_CANT_DESP2]
	DEFAULT (0) FOR [FIE_CANT_DESP2]
GO
ALTER TABLE [dbo].[FACTIMPEMPAQUE]
	ADD
	CONSTRAINT [DF_FACTIMPEMPAQUE_FIE_GENERA_EMP1]
	DEFAULT ('D') FOR [FIE_GENERA_EMP1]
GO
ALTER TABLE [dbo].[FACTIMPEMPAQUE]
	ADD
	CONSTRAINT [DF_FACTIMPEMPAQUE_FIE_GENERA_EMP2]
	DEFAULT ('D') FOR [FIE_GENERA_EMP2]
GO
ALTER TABLE [dbo].[FACTIMPEMPAQUE]
	ADD
	CONSTRAINT [DF_FACTIMPEMPAQUE_FIE_RELDETALLE]
	DEFAULT ('N') FOR [FIE_RELDETALLE]
GO
ALTER TABLE [dbo].[FACTIMPEMPAQUE]
	ADD
	CONSTRAINT [DF_FACTIMPEMPAQUE_FIE_RELEMPAQUE]
	DEFAULT ('N') FOR [FIE_RELEMPAQUE]
GO
CREATE NONCLUSTERED INDEX [IX_FACTIMPEMPAQUE]
	ON [dbo].[FACTIMPEMPAQUE] ([FI_CODIGO])
	WITH ( FILLFACTOR = 90)
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPEMPAQUE] SET (LOCK_ESCALATION = TABLE)
GO
