SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTIMPCONT] (
		[FID_INDICED]         [int] NOT NULL,
		[FIC_INDICEC]         [int] NOT NULL,
		[FI_CODIGO]           [int] NULL,
		[FIC_MARCA]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FIC_MODELO]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FIC_SERIE]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FIC_EQUIPADOCON]     [varchar](3100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TCA_CODIGO]          [smallint] NULL,
		[FIC_PELIGROSO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FIC_MILLAGE]         [int] NULL,
		[FIC_DEFTXT]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FIC_DEFNO]           [decimal](38, 6) NULL,
		[FIC_NOACTIVO]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PLC_INDICEC]         [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPCONT]
	ADD
	CONSTRAINT [PK_FACTIMPCONT]
	PRIMARY KEY
	NONCLUSTERED
	([FIC_INDICEC])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPCONT]
	ADD
	CONSTRAINT [DF_FACTIMPCONT_FIC_DEFTXT]
	DEFAULT ('') FOR [FIC_DEFTXT]
GO
ALTER TABLE [dbo].[FACTIMPCONT]
	ADD
	CONSTRAINT [DF_FACTIMPCONT_FIC_EQUIPADOCON]
	DEFAULT ('') FOR [FIC_EQUIPADOCON]
GO
CREATE CLUSTERED INDEX [IX_FACTIMPCONT]
	ON [dbo].[FACTIMPCONT] ([FI_CODIGO], [FID_INDICED])
	WITH ( FILLFACTOR = 90)
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPCONT] SET (LOCK_ESCALATION = TABLE)
GO
