SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ALMACENDESPCAR] (
		[AM_CODIGO]             [int] NOT NULL,
		[AM_REFERADICIONAL]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AM_REFERFECHA]         [datetime] NOT NULL,
		[US_CODIGO]             [int] NULL,
		CONSTRAINT [IX_ALMACENDESPCAR]
		UNIQUE
		NONCLUSTERED
		([AM_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALMACENDESPCAR]
	ADD
	CONSTRAINT [PK_ALMACENDESPCAR]
	PRIMARY KEY
	NONCLUSTERED
	([AM_REFERADICIONAL])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALMACENDESPCAR] SET (LOCK_ESCALATION = TABLE)
GO
