SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPORTACIONEXCEL] (
		[IE_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[IE_IMPFACTEXP]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IE_IMPFACTIMP]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IE_IMPALM]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IE_IMPPROD]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IE_IMPRETRA]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IE_SELFACT]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_IMPORTACIONEXCEL]
		UNIQUE
		NONCLUSTERED
		([IE_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTACIONEXCEL]
	ADD
	CONSTRAINT [DF_IMPORTACIONEXCEL_IE_IMPALM]
	DEFAULT ('N') FOR [IE_IMPALM]
GO
ALTER TABLE [dbo].[IMPORTACIONEXCEL]
	ADD
	CONSTRAINT [DF_IMPORTACIONEXCEL_IE_IMPFACTEXP]
	DEFAULT ('N') FOR [IE_IMPFACTEXP]
GO
ALTER TABLE [dbo].[IMPORTACIONEXCEL]
	ADD
	CONSTRAINT [DF_IMPORTACIONEXCEL_IE_IMPFACTIMP]
	DEFAULT ('N') FOR [IE_IMPFACTIMP]
GO
ALTER TABLE [dbo].[IMPORTACIONEXCEL]
	ADD
	CONSTRAINT [DF_IMPORTACIONEXCEL_IE_IMPPROD]
	DEFAULT ('N') FOR [IE_IMPPROD]
GO
ALTER TABLE [dbo].[IMPORTACIONEXCEL]
	ADD
	CONSTRAINT [DF_IMPORTACIONEXCEL_IE_IMPRETRA]
	DEFAULT ('N') FOR [IE_IMPRETRA]
GO
ALTER TABLE [dbo].[IMPORTACIONEXCEL]
	ADD
	CONSTRAINT [DF_IMPORTACIONEXCEL_IE_SELFACT]
	DEFAULT ('N') FOR [IE_SELFACT]
GO
ALTER TABLE [dbo].[IMPORTACIONEXCEL] SET (LOCK_ESCALATION = TABLE)
GO
