SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGFOLIOMSTR] (
		[CFM_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFM_MASK]        [char](35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFM_USRMASK]     [char](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGFOLIOMSTR]
	ADD
	CONSTRAINT [PK_CONFIGFOLIOMSTR]
	PRIMARY KEY
	NONCLUSTERED
	([CFM_TIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGFOLIOMSTR] SET (LOCK_ESCALATION = TABLE)
GO
