SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURAREVISAVAL] (
		[CFV_FORMATAG]         [int] NOT NULL,
		[CFV_PEDCONSOLIDA]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_NOREMESA]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_NOGUIA]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_CTRANSPOR]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_MEDIOTRANS]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_PLACASMX]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_PLACASUSA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_REGISTRO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_BULTOS]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_NOMBRE]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_COSTOUNI]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_CANTIDAD]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_TARIFAUSA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_TARIFAMX]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_TASAMX]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_GRUPOGEN]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_PESONETO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_PESOBRUTO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_ORDCOMPRA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_ORDTRABAJO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFV_NOENTRADA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [PK_CONFIGURAREVISAVAL]
	PRIMARY KEY
	CLUSTERED
	([CFV_FORMATAG])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_BULTOS]
	DEFAULT ('N') FOR [CFV_BULTOS]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_CANTIDAD]
	DEFAULT ('S') FOR [CFV_CANTIDAD]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_COSTOUNI]
	DEFAULT ('S') FOR [CFV_COSTOUNI]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_CTRANSPOR]
	DEFAULT ('N') FOR [CFV_CTRANSPOR]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_GRUPOGEN]
	DEFAULT ('S') FOR [CFV_GRUPOGEN]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_MEDIOTRANS]
	DEFAULT ('N') FOR [CFV_MEDIOTRANS]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_NOENTRADA]
	DEFAULT ('N') FOR [CFV_NOENTRADA]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_NOGUIA]
	DEFAULT ('N') FOR [CFV_NOGUIA]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_NOMBRE]
	DEFAULT ('N') FOR [CFV_NOMBRE]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_NOREMESA]
	DEFAULT ('N') FOR [CFV_NOREMESA]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_ORDCOMPRA]
	DEFAULT ('N') FOR [CFV_ORDCOMPRA]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_ORDTRABAJO]
	DEFAULT ('N') FOR [CFV_ORDTRABAJO]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_PEDCONSOLIDA]
	DEFAULT ('N') FOR [CFV_PEDCONSOLIDA]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_PESOBRUTO]
	DEFAULT ('N') FOR [CFV_PESOBRUTO]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_PESONETO]
	DEFAULT ('S') FOR [CFV_PESONETO]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_PLACASMX]
	DEFAULT ('N') FOR [CFV_PLACASMX]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_PLACASUSA]
	DEFAULT ('N') FOR [CFV_PLACASUSA]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_REGISTRO]
	DEFAULT ('N') FOR [CFV_REGISTRO]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_TARIFAMX]
	DEFAULT ('S') FOR [CFV_TARIFAMX]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_TARIFAUSA]
	DEFAULT ('N') FOR [CFV_TARIFAUSA]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL]
	ADD
	CONSTRAINT [DF_CONFIGURAREVISAVAL_CFV_TASAMX]
	DEFAULT ('N') FOR [CFV_TASAMX]
GO
ALTER TABLE [dbo].[CONFIGURAREVISAVAL] SET (LOCK_ESCALATION = TABLE)
GO
