SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DEPTOREQAPRUEBA] (
		[DP_CODIGO]         [smallint] NOT NULL,
		[US_CODIGO]         [smallint] NOT NULL,
		[ARQ_TIPO]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[US_SUSTITUTO]      [smallint] NULL,
		[US_SUSTITUTO2]     [smallint] NULL,
		[ARQ_OBSERVA]       [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPTOREQAPRUEBA]
	ADD
	CONSTRAINT [PK_DEPTOREQAPRUEBA]
	PRIMARY KEY
	NONCLUSTERED
	([DP_CODIGO], [US_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPTOREQAPRUEBA]
	ADD
	CONSTRAINT [DF_DEPTOREQAPRUEBA_ARQ_TIPO]
	DEFAULT ('O') FOR [ARQ_TIPO]
GO
ALTER TABLE [dbo].[DEPTOREQAPRUEBA] SET (LOCK_ESCALATION = TABLE)
GO
