SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[LISTAPEDAFECTADOS1] (
		[PI_CODIGO]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LISTAPEDAFECTADOS1] SET (LOCK_ESCALATION = TABLE)
GO
