SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRODUCDET] (
		[PRO_CODIGO]            [int] NOT NULL,
		[PROD_INDICED]          [int] NOT NULL,
		[MA_CODIGO]             [int] NOT NULL,
		[PROD_NOPARTE]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PROD_NOMBRE]           [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PROD_CANT]             [decimal](38, 6) NOT NULL,
		[ME_CODIGO]             [int] NULL,
		[PROD_CANTPEND]         [decimal](38, 6) NULL,
		[PROD_OBSERVA]          [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PROD_FECHA_STRUCT]     [datetime] NULL,
		[PROD_TIPODESCARGA]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_EMPAQUE]            [int] NULL,
		[PROD_CANTEMP]          [decimal](38, 6) NULL,
		[END_INDICED]           [int] NOT NULL,
		[MA_FAMILIA]            [int] NULL,
		[PROD_LIGA]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCDET]
	ADD
	CONSTRAINT [PK_PRODUCDET]
	PRIMARY KEY
	NONCLUSTERED
	([PROD_INDICED])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCDET]
	ADD
	CONSTRAINT [DF_PRODUCDET_END_INDICED]
	DEFAULT ((-1)) FOR [END_INDICED]
GO
ALTER TABLE [dbo].[PRODUCDET]
	ADD
	CONSTRAINT [DF_PRODUCDET_PROD_CANTEMP]
	DEFAULT (0) FOR [PROD_CANTEMP]
GO
ALTER TABLE [dbo].[PRODUCDET]
	ADD
	CONSTRAINT [DF_PRODUCDET_PROD_TIPODESCARGA]
	DEFAULT ('N') FOR [PROD_TIPODESCARGA]
GO
ALTER TABLE [dbo].[PRODUCDET] SET (LOCK_ESCALATION = TABLE)
GO
