SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[MAESTROCATEG] (
		[MA_CODIGO]      [int] NOT NULL,
		[CPE_CODIGO]     [int] NOT NULL,
		[EQ_CANT]        [decimal](28, 14) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROCATEG]
	ADD
	CONSTRAINT [PK_MAESTROCATEG]
	PRIMARY KEY
	CLUSTERED
	([MA_CODIGO], [CPE_CODIGO])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROCATEG]
	ADD
	CONSTRAINT [DF_MAESTROCATEG_EQ_CANT]
	DEFAULT (1) FOR [EQ_CANT]
GO
ALTER TABLE [dbo].[MAESTROCATEG] SET (LOCK_ESCALATION = TABLE)
GO
