SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CHOFER] (
		[CHO_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[CHO_NOMBRE]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CHO_LICENCIA]       [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CHO_GAFETE]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CHO_CURP_SSUSA]     [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_CHOFER]
		UNIQUE
		NONCLUSTERED
		([CHO_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHOFER]
	ADD
	CONSTRAINT [PK_CHOFER]
	PRIMARY KEY
	CLUSTERED
	([CHO_NOMBRE])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHOFER] SET (LOCK_ESCALATION = TABLE)
GO
