SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PERMISOSERVICIOS] (
		[PE_CODIGO]       [int] NOT NULL,
		[PES_DESCRIP]     [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SER_CODIGO]      [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISOSERVICIOS]
	ADD
	CONSTRAINT [PK_PERMISOSERV]
	PRIMARY KEY
	NONCLUSTERED
	([PE_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PERMISOSERVICIOS]
	ON [dbo].[PERMISOSERVICIOS] ([PE_CODIGO])
	WITH ( FILLFACTOR = 90)
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISOSERVICIOS] SET (LOCK_ESCALATION = TABLE)
GO
