SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ELIMINAIDENT] (
		[FI_FOLIO]        [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FID_NOPARTE]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDE_CODIGO]      [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELIMINAIDENT] SET (LOCK_ESCALATION = TABLE)
GO
