SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PEDIMPCONTRIBUCIONDIFR1] (
		[PI_CODIGO]            [int] NOT NULL,
		[CON_CODIGO]           [smallint] NOT NULL,
		[PIF_CONTRIBTOTMN]     [decimal](38, 6) NOT NULL,
		[PG_CODIGO]            [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCONTRIBUCIONDIFR1]
	ADD
	CONSTRAINT [PK_PEDIMPCONTRIBUCIONDIFR1]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO], [CON_CODIGO], [PG_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCONTRIBUCIONDIFR1]
	ADD
	CONSTRAINT [DF_PEDIMPCONTRIBUCIONDIFR1_PG_CODIGO]
	DEFAULT (1) FOR [PG_CODIGO]
GO
ALTER TABLE [dbo].[PEDIMPCONTRIBUCIONDIFR1] SET (LOCK_ESCALATION = TABLE)
GO
