SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[INCREMENTABLE] (
		[IC_CODIGO]         [smallint] IDENTITY(1, 1) NOT NULL,
		[IC_NOMBRE]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IC_NAME]           [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IC_PEDIMENTO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IC_INCREMENTA]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IC_PORENTRADA]     [decimal](38, 6) NOT NULL,
		[IC_PORSALIDA]      [decimal](38, 6) NOT NULL,
		CONSTRAINT [IX_INCREMENTABLE]
		UNIQUE
		NONCLUSTERED
		([IC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCREMENTABLE]
	ADD
	CONSTRAINT [PK_INCREMENTABLE]
	PRIMARY KEY
	NONCLUSTERED
	([IC_NOMBRE], [IC_PEDIMENTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[INCREMENTABLE]
	ADD
	CONSTRAINT [DF_INCREMENTABLE_IC_INCREMENTA]
	DEFAULT ('N') FOR [IC_INCREMENTA]
GO
ALTER TABLE [dbo].[INCREMENTABLE]
	ADD
	CONSTRAINT [DF_INCREMENTABLE_IC_PORENTRADA]
	DEFAULT (0) FOR [IC_PORENTRADA]
GO
ALTER TABLE [dbo].[INCREMENTABLE]
	ADD
	CONSTRAINT [DF_INCREMENTABLE_IC_PORSALIDA]
	DEFAULT (0) FOR [IC_PORSALIDA]
GO
ALTER TABLE [dbo].[INCREMENTABLE] SET (LOCK_ESCALATION = TABLE)
GO
