SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PERMISOAGENCIA] (
		[PE_CODIGO]     [int] NOT NULL,
		[AG_CODIGO]     [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISOAGENCIA]
	ADD
	CONSTRAINT [PK_PERMISOAGENCIA]
	PRIMARY KEY
	NONCLUSTERED
	([PE_CODIGO], [AG_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PERMISOAGENCIA]
	ON [dbo].[PERMISOAGENCIA] ([PE_CODIGO])
	WITH ( FILLFACTOR = 90)
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISOAGENCIA] SET (LOCK_ESCALATION = TABLE)
GO
