SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BUSQUEDASELDET] (
		[BUS_CODIGO]       [int] NOT NULL,
		[BSD_TABLA]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BSD_SELECTED]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUSQUEDASELDET]
	ADD
	CONSTRAINT [PK_BUSQUEDASELDET]
	PRIMARY KEY
	NONCLUSTERED
	([BUS_CODIGO], [BSD_TABLA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUSQUEDASELDET]
	ADD
	CONSTRAINT [DF_BUSQUEDASELDET_BSD_SELECTED]
	DEFAULT ('N') FOR [BSD_SELECTED]
GO
ALTER TABLE [dbo].[BUSQUEDASELDET] SET (LOCK_ESCALATION = TABLE)
GO
