SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TRECIBE] (
		[TRC_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[TRC_NOMBRE]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TRC_NAME]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TRC_ACTIVO]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TRC_TIPO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_TRECIBE]
		UNIQUE
		NONCLUSTERED
		([TRC_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRECIBE]
	ADD
	CONSTRAINT [PK_TRECIBE]
	PRIMARY KEY
	NONCLUSTERED
	([TRC_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TRECIBE]
	ADD
	CONSTRAINT [DF_TRECIBE_TRC_ACTIVO]
	DEFAULT ('S') FOR [TRC_ACTIVO]
GO
ALTER TABLE [dbo].[TRECIBE]
	ADD
	CONSTRAINT [DF_TRECIBE_TRC_TIPO]
	DEFAULT ('X') FOR [TRC_TIPO]
GO
ALTER TABLE [dbo].[TRECIBE] SET (LOCK_ESCALATION = TABLE)
GO
