SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[RelacionFIDIndiced] (
		[FID_INDICED]          [int] NOT NULL,
		[FID_PIDSECUENCIA]     [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RelacionFIDIndiced] SET (LOCK_ESCALATION = TABLE)
GO
