SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PUERTO] (
		[PU_CODIGO]      [int] IDENTITY(1, 1) NOT NULL,
		[PU_NOMBRE]      [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PA_CODIGO]      [int] NOT NULL,
		[PU_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PU_CLA_USA]     [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_PUERTO]
		UNIQUE
		NONCLUSTERED
		([PU_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PUERTO]
	ADD
	CONSTRAINT [PK_PUERTO]
	PRIMARY KEY
	NONCLUSTERED
	([PU_NOMBRE], [PA_CODIGO], [PU_CLA_USA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PUERTO]
	ADD
	CONSTRAINT [DF_PUERTO_PU_CLA_USA]
	DEFAULT ('') FOR [PU_CLA_USA]
GO
ALTER TABLE [dbo].[PUERTO] SET (LOCK_ESCALATION = TABLE)
GO
