SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[SECTORARA] (
		[SA_CODIGO]      [int] IDENTITY(1, 1) NOT NULL,
		[AR_CODIGO]      [int] NOT NULL,
		[SE_CODIGO]      [smallint] NOT NULL,
		[SA_PORCENT]     [decimal](38, 6) NULL,
		[PG_CODIGO]      [smallint] NULL,
		[SA_PERINI]      [datetime] NOT NULL,
		[SA_PERFIN]      [datetime] NOT NULL,
		CONSTRAINT [IX_SECTORARA]
		UNIQUE
		NONCLUSTERED
		([SA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SECTORARA]
	ADD
	CONSTRAINT [PK_SECTORARA]
	PRIMARY KEY
	NONCLUSTERED
	([AR_CODIGO], [SE_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[SECTORARA]
	ADD
	CONSTRAINT [DF_SECTORARA_SA_PERFIN]
	DEFAULT ('1/1/9999') FOR [SA_PERFIN]
GO
ALTER TABLE [dbo].[SECTORARA]
	ADD
	CONSTRAINT [DF_SECTORARA_SA_PERINI]
	DEFAULT ('1/1/1999') FOR [SA_PERINI]
GO
CREATE CLUSTERED INDEX [IX_SECTORARA_1]
	ON [dbo].[SECTORARA] ([AR_CODIGO], [SA_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[SECTORARA] SET (LOCK_ESCALATION = TABLE)
GO
