SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPCONT] (
		[FEC_INDICEC]         [int] NOT NULL,
		[FED_INDICED]         [int] NULL,
		[FE_CODIGO]           [int] NULL,
		[FEC_MARCA]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FEC_MODELO]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FEC_SERIE]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FEC_EQUIPADOCON]     [varchar](3100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FEC_DESCARGADO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PIC_INDICEC]         [int] NOT NULL,
		[FEC_PELIGROSO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FEC_MILLAGE]         [int] NULL,
		[FEC_NOACTIVO]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[LEC_INDICEC]         [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPCONT]
	ADD
	CONSTRAINT [PK_FACTEXPCONT]
	PRIMARY KEY
	NONCLUSTERED
	([FEC_INDICEC])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPCONT]
	ADD
	CONSTRAINT [DF_FACTEXPCONT_FEC_DESCARGADO]
	DEFAULT ('N') FOR [FEC_DESCARGADO]
GO
ALTER TABLE [dbo].[FACTEXPCONT]
	ADD
	CONSTRAINT [DF_FACTEXPCONT_FEC_EQUIPADOCON]
	DEFAULT ('') FOR [FEC_EQUIPADOCON]
GO
ALTER TABLE [dbo].[FACTEXPCONT]
	ADD
	CONSTRAINT [DF_FACTEXPCONT_PIC_INDICEC]
	DEFAULT ((-1)) FOR [PIC_INDICEC]
GO
CREATE NONCLUSTERED INDEX [IX_FACTEXPCONT]
	ON [dbo].[FACTEXPCONT] ([FED_INDICED])
	WITH ( FILLFACTOR = 90)
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPCONT] SET (LOCK_ESCALATION = TABLE)
GO
