SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FASTDET] (
		[FSTD_INDICED]       [int] IDENTITY(1, 1) NOT NULL,
		[FST_CODIGO]         [int] NOT NULL,
		[ET_CODIGO]          [int] NOT NULL,
		[FSTD_TIPOENTRY]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FSTD_UNE]           [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_FASTDET]
		UNIQUE
		NONCLUSTERED
		([FSTD_INDICED])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FASTDET]
	ADD
	CONSTRAINT [PK_FASTDET]
	PRIMARY KEY
	CLUSTERED
	([FST_CODIGO], [ET_CODIGO])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FASTDET]
	ADD
	CONSTRAINT [DF_FASTDET_ET_CODIGO]
	DEFAULT (0) FOR [ET_CODIGO]
GO
ALTER TABLE [dbo].[FASTDET]
	ADD
	CONSTRAINT [DF_FASTDET_FSTD_TIPOENTRY]
	DEFAULT ('N') FOR [FSTD_TIPOENTRY]
GO
ALTER TABLE [dbo].[FASTDET] SET (LOCK_ESCALATION = TABLE)
GO
