SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURAPERMISOREL] (
		[IDE_CODIGO]            [int] NOT NULL,
		[CFR_FILTRO]            [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFR_TIPO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFR_CONDICION]         [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFR_SALDO]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFR_MENSAJE]           [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFR_APLICA]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFR_SALDOCARATULA]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISOREL]
	ADD
	CONSTRAINT [PK_CONFIGURAPERMISOREL]
	PRIMARY KEY
	NONCLUSTERED
	([IDE_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISOREL]
	ADD
	CONSTRAINT [DF_CONFIGURAPERMISOREL_CFR_APLICA]
	DEFAULT ('T') FOR [CFR_APLICA]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISOREL]
	ADD
	CONSTRAINT [DF_CONFIGURAPERMISOREL_CFR_SALDO]
	DEFAULT ('N') FOR [CFR_SALDO]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISOREL]
	ADD
	CONSTRAINT [DF_CONFIGURAPERMISOREL_CFR_SALDOCARATULA]
	DEFAULT ('N') FOR [CFR_SALDOCARATULA]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISOREL]
	ADD
	CONSTRAINT [DF_CONFIGURAPERMISOREL_CFR_TIPO]
	DEFAULT ('E') FOR [CFR_TIPO]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISOREL] SET (LOCK_ESCALATION = TABLE)
GO
