SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTRODEF] (
		[MAD_CODIGO]      [int] NOT NULL,
		[MA_CODIGO]       [int] NOT NULL,
		[MA_DEFTXT1]      [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_DEFTXT2]      [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_DEFTXT3]      [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_DEFBOL1]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_DEFBOL2]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_DEFBOL3]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_DEFNO1]       [int] NOT NULL,
		[MA_DEFNO2]       [int] NOT NULL,
		[MA_DEFNO3]       [int] NOT NULL,
		[MA_DEFDATE1]     [datetime] NULL,
		[MA_DEFDATE2]     [datetime] NULL,
		[MA_DEFDATE3]     [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [PK_MAESTRODEF]
	PRIMARY KEY
	NONCLUSTERED
	([MA_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [DF_MAESTRODEF_MA_DEFBOL1]
	DEFAULT ('N') FOR [MA_DEFBOL1]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [DF_MAESTRODEF_MA_DEFBOL2]
	DEFAULT ('N') FOR [MA_DEFBOL2]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [DF_MAESTRODEF_MA_DEFBOL3]
	DEFAULT ('N') FOR [MA_DEFBOL3]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [DF_MAESTRODEF_MA_DEFNO1]
	DEFAULT (0) FOR [MA_DEFNO1]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [DF_MAESTRODEF_MA_DEFNO2]
	DEFAULT (0) FOR [MA_DEFNO2]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [DF_MAESTRODEF_MA_DEFNO3]
	DEFAULT (0) FOR [MA_DEFNO3]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [DF_MAESTRODEF_MA_DEFTXT1]
	DEFAULT ('') FOR [MA_DEFTXT1]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [DF_MAESTRODEF_MA_DEFTXT2]
	DEFAULT ('') FOR [MA_DEFTXT2]
GO
ALTER TABLE [dbo].[MAESTRODEF]
	ADD
	CONSTRAINT [DF_MAESTRODEF_MA_DEFTXT3]
	DEFAULT ('') FOR [MA_DEFTXT3]
GO
ALTER TABLE [dbo].[MAESTRODEF] SET (LOCK_ESCALATION = TABLE)
GO
