SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ENTRADA_A] (
		[EA_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[EA_CLAVE]      [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EA_CORTO]      [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[EA_NAME]       [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_ENTRADA_A]
		UNIQUE
		NONCLUSTERED
		([EA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENTRADA_A]
	ADD
	CONSTRAINT [PK_ENTRADA_A]
	PRIMARY KEY
	NONCLUSTERED
	([EA_CLAVE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENTRADA_A] SET (LOCK_ESCALATION = TABLE)
GO
