SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RANGOARA] (
		[RA_CODIGO]      [int] NOT NULL,
		[RA_LN_BARR]     [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RA_INICIO]      [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RA_FINAL]       [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RA_BARCODE]     [image] NULL,
		[RA_LN_DESC]     [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_RANGOARA]
		UNIQUE
		NONCLUSTERED
		([RA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RANGOARA]
	ADD
	CONSTRAINT [PK_RANGOARA]
	PRIMARY KEY
	NONCLUSTERED
	([RA_LN_BARR])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[RANGOARA] SET (LOCK_ESCALATION = TABLE)
GO
