SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PERMISODET] (
		[PED_INDICED]          [int] NOT NULL,
		[PE_CODIGO]            [int] NOT NULL,
		[PED_REGISTROTIPO]     [smallint] NULL,
		[MA_GENERICO]          [int] NOT NULL,
		[MA_NOPARTE]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PED_OBSERVA]          [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PED_NOMBRE]           [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TI_CODIGO]            [smallint] NULL,
		[ME_COM]               [int] NULL,
		[AR_IMPMX]             [int] NULL,
		[AR_EXPMX]             [int] NULL,
		[PED_ID_SUBORD]        [int] NOT NULL,
		[PED_CONSECUTIVO]      [int] NULL,
		[PED_CANT]             [decimal](38, 6) NOT NULL,
		[SE_CODIGO]            [int] NULL,
		[PED_COSTO]            [decimal](38, 6) NULL,
		[PED_COSTOT]           [decimal](38, 6) NULL,
		[PED_ENUSO]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PED_SALDO]            [decimal](38, 6) NOT NULL,
		[PED_ENUSOCOSTOT]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PED_SALDOCOSTOT]      [decimal](38, 6) NOT NULL,
		[PED_CAS_NUM]          [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PA_CODIGO]            [int] NULL,
		CONSTRAINT [IX_PERMISODET]
		UNIQUE
		NONCLUSTERED
		([PED_INDICED])
		ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISODET]
	ADD
	CONSTRAINT [PK_PERMISODET]
	PRIMARY KEY
	NONCLUSTERED
	([PE_CODIGO], [MA_GENERICO], [PED_ID_SUBORD])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISODET]
	ADD
	CONSTRAINT [DF_PERMISODET_MA_NOPARTE]
	DEFAULT ('') FOR [MA_NOPARTE]
GO
ALTER TABLE [dbo].[PERMISODET]
	ADD
	CONSTRAINT [DF_PERMISODET_PED_CANT]
	DEFAULT (0) FOR [PED_CANT]
GO
ALTER TABLE [dbo].[PERMISODET]
	ADD
	CONSTRAINT [DF_PERMISODET_PED_ENUSO]
	DEFAULT ('N') FOR [PED_ENUSO]
GO
ALTER TABLE [dbo].[PERMISODET]
	ADD
	CONSTRAINT [DF_PERMISODET_PED_ENUSOCOSTOT]
	DEFAULT ('N') FOR [PED_ENUSOCOSTOT]
GO
ALTER TABLE [dbo].[PERMISODET]
	ADD
	CONSTRAINT [DF_PERMISODET_PED_ID_SUBORD]
	DEFAULT (0) FOR [PED_ID_SUBORD]
GO
ALTER TABLE [dbo].[PERMISODET]
	ADD
	CONSTRAINT [DF_PERMISODET_PED_SALDO]
	DEFAULT (0) FOR [PED_SALDO]
GO
ALTER TABLE [dbo].[PERMISODET]
	ADD
	CONSTRAINT [DF_PERMISODET_PED_SALDOCOSTOT]
	DEFAULT (0) FOR [PED_SALDOCOSTOT]
GO
ALTER TABLE [dbo].[PERMISODET] SET (LOCK_ESCALATION = TABLE)
GO
