SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ACTIVIDAD] (
		[AC_CODIGO]             [int] IDENTITY(1, 1) NOT NULL,
		[AC_CLAVE]              [int] NOT NULL,
		[AC_NOMBRE]             [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AC_FECHACREACION]      [datetime] NULL,
		[AC_FECHAACTUALIZA]     [datetime] NULL,
		[AC_ACTSICEX]           [int] NULL,
		[AC_ACTPROSEC]          [int] NULL,
		CONSTRAINT [IX_ACTIVIDAD]
		UNIQUE
		NONCLUSTERED
		([AC_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTIVIDAD]
	ADD
	CONSTRAINT [PK_ACTIVIDAD]
	PRIMARY KEY
	NONCLUSTERED
	([AC_CLAVE], [AC_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTIVIDAD] SET (LOCK_ESCALATION = TABLE)
GO
