SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENCIAPAGDET] (
		[AGP_CODIGO]          [int] NOT NULL,
		[AGPD_INDICED]        [int] NOT NULL,
		[PI_CODIGO]           [int] NOT NULL,
		[PI_FOLIO]            [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AGPD_PEDTIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AGPD_TOTCONTRIB]     [decimal](38, 6) NOT NULL,
		[AGPD_VALPED]         [decimal](38, 6) NOT NULL,
		[AGPD_FRANJA]         [decimal](38, 6) NOT NULL,
		[AGPD_ANTICIPO]       [decimal](38, 6) NOT NULL,
		[AGPD_PRECIOTOT]      [decimal](38, 6) NOT NULL,
		[AGPD_NOHOJAS]        [smallint] NOT NULL,
		[AGPD_NOFACT]         [smallint] NOT NULL,
		[AGPD_NOVEHI]         [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [PK_AGENCIAPAGDET]
	PRIMARY KEY
	NONCLUSTERED
	([PI_CODIGO], [AGPD_PEDTIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDET_AGPD_ANTICIPO]
	DEFAULT (0) FOR [AGPD_ANTICIPO]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDET_AGPD_FRANJA]
	DEFAULT (0) FOR [AGPD_FRANJA]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDET_AGPD_NOFACT]
	DEFAULT (1) FOR [AGPD_NOFACT]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDET_AGPD_NOHOJAS]
	DEFAULT (1) FOR [AGPD_NOHOJAS]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDET_AGPD_NOVEHI]
	DEFAULT (1) FOR [AGPD_NOVEHI]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDET_AGPD_PEDTIPO]
	DEFAULT ('N') FOR [AGPD_PEDTIPO]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDET_AGPD_PRECIOTOT]
	DEFAULT (0) FOR [AGPD_PRECIOTOT]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDET_AGPD_TOTCONTRIB]
	DEFAULT (0) FOR [AGPD_TOTCONTRIB]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET]
	ADD
	CONSTRAINT [DF_AGENCIAPAGDET_AGPD_VALPED]
	DEFAULT (0) FOR [AGPD_VALPED]
GO
ALTER TABLE [dbo].[AGENCIAPAGDET] SET (LOCK_ESCALATION = TABLE)
GO
