SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REGLAORIGENEXCEPTO] (
		[ARG_CODIGO]       [int] NOT NULL,
		[ARC_EXCEPTO]      [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ARC_EXCEPTOF]     [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGLAORIGENEXCEPTO]
	ADD
	CONSTRAINT [PK_REGLAORIGENEXCEPTO_1]
	PRIMARY KEY
	NONCLUSTERED
	([ARG_CODIGO], [ARC_EXCEPTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGLAORIGENEXCEPTO] SET (LOCK_ESCALATION = TABLE)
GO
