SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTROUBICACION] (
		[MA_CODIGO]         [int] NOT NULL,
		[ALMD_CODIGO]       [int] NOT NULL,
		[MAU_NOPASILLO]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAU_NOANAQUEL]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAU_NOREPISA]      [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROUBICACION]
	ADD
	CONSTRAINT [PK_MAESTROUBICACION]
	PRIMARY KEY
	NONCLUSTERED
	([MA_CODIGO], [ALMD_CODIGO], [MAU_NOPASILLO], [MAU_NOANAQUEL], [MAU_NOREPISA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROUBICACION] SET (LOCK_ESCALATION = TABLE)
GO
