SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SEARCHSPECSITEM] (
		[SSD_CODIGO]     [int] NOT NULL,
		[SSI_ITEM]       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEARCHSPECSITEM] SET (LOCK_ESCALATION = TABLE)
GO
