SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CAPTURAXORDCOMP] (
		[CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[CODIGOFACT]     [int] NOT NULL,
		[TIPOFACT]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NOPARTE]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CANTIDAD]       [decimal](38, 6) NULL,
		[DIFERENCIA]     [decimal](38, 6) NULL,
		[ORD_COMP]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NUM_ENT]        [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[COSTO]          [decimal](38, 6) NULL,
		CONSTRAINT [IX_CAPTURAXORDCOMP]
		UNIQUE
		NONCLUSTERED
		([CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAPTURAXORDCOMP]
	ADD
	CONSTRAINT [DF_CAPTURAXORDCOMP_TIPOFACT]
	DEFAULT ('I') FOR [TIPOFACT]
GO
ALTER TABLE [dbo].[CAPTURAXORDCOMP] SET (LOCK_ESCALATION = TABLE)
GO
