SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGFOLIOSERIAL] (
		[MA_FAMILIA]            [int] NOT NULL,
		[CFS_USRMASK]           [varchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFS_USACONSEC]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFS_SIZECONSEC]        [smallint] NULL,
		[CFS_INIDIGCONSEC]      [smallint] NULL,
		[CFS_NOCONSEC]          [int] NULL,
		[CFS_USAGETDATE]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFS_INIDIGGETDATE]     [smallint] NULL,
		[CFS_MASKGETDATE]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGFOLIOSERIAL]
	ADD
	CONSTRAINT [PK_CONFIGFOLIOSERIAL]
	PRIMARY KEY
	NONCLUSTERED
	([MA_FAMILIA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGFOLIOSERIAL]
	ADD
	CONSTRAINT [DF_CONFIGFOLIOSERIAL_CFS_USACONSEC]
	DEFAULT ('N') FOR [CFS_USACONSEC]
GO
ALTER TABLE [dbo].[CONFIGFOLIOSERIAL] SET (LOCK_ESCALATION = TABLE)
GO
