SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SEARCHSPECS] (
		[SS_CODIGO]       [int] NOT NULL,
		[SS_NOMBRE]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SS_FORMATAG]     [smallint] NULL,
		[SS_DEFAULT]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SS_USERID]       [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEARCHSPECS]
	ADD
	CONSTRAINT [PK_SEARCHSPECS]
	PRIMARY KEY
	NONCLUSTERED
	([SS_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[SEARCHSPECS]
	ADD
	CONSTRAINT [DF_SEARCHSPECS_SS_DEFAULT]
	DEFAULT ('N') FOR [SS_DEFAULT]
GO
ALTER TABLE [dbo].[SEARCHSPECS] SET (LOCK_ESCALATION = TABLE)
GO
