SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[GRIDINFO] (
		[CFG_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[CFG_CAMPOGUIA]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFG_CAMPOVER]      [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFG_TABLA]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFG_CAMPO]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_GRIDINFO]
		UNIQUE
		NONCLUSTERED
		([CFG_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GRIDINFO]
	ADD
	CONSTRAINT [PK_GRIDINFO]
	PRIMARY KEY
	NONCLUSTERED
	([CFG_CAMPOGUIA], [CFG_CAMPOVER], [CFG_TABLA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[GRIDINFO] SET (LOCK_ESCALATION = TABLE)
GO
