SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPORTTABLES] (
		[IMT_CODIGO]             [smallint] NOT NULL,
		[IMT_TEXTOFORMA]         [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_FORMCAPTION]        [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_TABLA]              [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_NUMFORMA]           [int] NULL,
		[IMT_PRIMARYKEY]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_PREFIJO]            [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_IDENTITY]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_PRIMKEYFIELDS]      [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_UPDATEABLE]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_TIPOTABLA]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMT_DISPLAYFIELDS]      [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_TIPOREP]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[UMT_SQLWHEREUPDATE]     [varchar](5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMT_PARABUSQUEDA]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTTABLES]
	ADD
	CONSTRAINT [PK_IMPORTTABLES]
	PRIMARY KEY
	CLUSTERED
	([IMT_CODIGO])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTTABLES]
	ADD
	CONSTRAINT [DF_IMPORTTABLES_IMT_PARABUSQUEDA]
	DEFAULT ('S') FOR [IMT_PARABUSQUEDA]
GO
ALTER TABLE [dbo].[IMPORTTABLES]
	ADD
	CONSTRAINT [DF_IMPORTTABLES_IMT_TIPOTABLA]
	DEFAULT ('D') FOR [IMT_TIPOTABLA]
GO
ALTER TABLE [dbo].[IMPORTTABLES] SET (LOCK_ESCALATION = TABLE)
GO
