SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TempRangoTlc] (
		[MA_NOPARTE]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_TRACEVALUE]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MA_NOPARTEAUX]      [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TempRangoTlc]
	ADD
	CONSTRAINT [DF_TempRangoTlc_MA_NOPARTEAUX]
	DEFAULT ('') FOR [MA_NOPARTEAUX]
GO
ALTER TABLE [dbo].[TempRangoTlc]
	ADD
	CONSTRAINT [DF_TempRangoTlc_NFT_TRACEVALUE]
	DEFAULT ('N') FOR [NFT_TRACEVALUE]
GO
ALTER TABLE [dbo].[TempRangoTlc] SET (LOCK_ESCALATION = TABLE)
GO
