SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REGIMEN] (
		[REG_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[REG_CLAVE]      [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[REG_DESC]       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_REGIMEN]
		UNIQUE
		NONCLUSTERED
		([REG_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGIMEN]
	ADD
	CONSTRAINT [PK_REGIMEN]
	PRIMARY KEY
	NONCLUSTERED
	([REG_CLAVE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGIMEN] SET (LOCK_ESCALATION = TABLE)
GO
