SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPDETPAISFRACCION] (
		[FPF_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[FED_INDICED]       [int] NOT NULL,
		[PA_CODIGO]         [int] NOT NULL,
		[AR_CODIGO]         [int] NOT NULL,
		[FPF_PEDIMENTO]     [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FPF_NOPARTE]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FPF_COSTO]         [decimal](38, 6) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDETPAISFRACCION]
	ADD
	CONSTRAINT [PK_FACTEXPDETPAISFRACCION]
	PRIMARY KEY
	CLUSTERED
	([FPF_CODIGO])
	ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_FACTEXPDETPAISFRACCION]
	ON [dbo].[FACTEXPDETPAISFRACCION] ([FPF_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDETPAISFRACCION] SET (LOCK_ESCALATION = TABLE)
GO
