SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ENTSALALMLISTA] (
		[ENT_INDICER]      [int] NOT NULL,
		[EN_CODIGO]        [int] NOT NULL,
		[END_INDICED]      [int] NOT NULL,
		[MA_HIJO]          [int] NOT NULL,
		[ENT_NOPARTE]      [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ENT_NOMBRE]       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ENT_NAME]         [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ENT_INCORPOR]     [decimal](38, 6) NOT NULL,
		[TI_HIJO]          [smallint] NOT NULL,
		[ME_CODIGO]        [int] NULL,
		[ME_ALM]           [int] NULL,
		[FACTCONV]         [decimal](28, 14) NOT NULL,
		CONSTRAINT [IX_ENTSALALMLISTA]
		UNIQUE
		NONCLUSTERED
		([ENT_INDICER])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENTSALALMLISTA]
	ADD
	CONSTRAINT [PK_ENTSALALMLISTA]
	PRIMARY KEY
	NONCLUSTERED
	([END_INDICED], [MA_HIJO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ENTSALALMLISTA]
	ADD
	CONSTRAINT [DF_ENTSALALMLISTA_ENT_INCORPOR]
	DEFAULT (1) FOR [ENT_INCORPOR]
GO
ALTER TABLE [dbo].[ENTSALALMLISTA]
	ADD
	CONSTRAINT [DF_ENTSALALMLISTA_FACTCONV]
	DEFAULT (1) FOR [FACTCONV]
GO
ALTER TABLE [dbo].[ENTSALALMLISTA] SET (LOCK_ESCALATION = TABLE)
GO
