SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TempBOM_DESCALM] (
		[EN_CODIGO]          [int] NULL,
		[END_INDICED]        [int] NULL,
		[BST_PT]             [int] NOT NULL,
		[BST_HIJO]           [int] NOT NULL,
		[BST_INCORPOR]       [decimal](38, 6) NULL,
		[BST_DISCH]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TI_CODIGO]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_CODIGO]          [int] NULL,
		[FACTCONVALM]        [decimal](28, 14) NOT NULL,
		[BST_PERINI]         [datetime] NULL,
		[BST_PERFIN]         [datetime] NULL,
		[ME_ALM]             [int] NULL,
		[BST_TRANS]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_TIP_ENS]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[END_CANT]           [decimal](38, 6) NULL,
		[BST_NIVEL]          [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BST_TIPODESC]       [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ALM_ORIGEN]         [int] NULL,
		[ALM_DESTINO]        [int] NULL,
		[ALMD_PASILLO]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ALMD_NIVEL]         [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ALMD_LOCALIDAD]     [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TempBOM_DESCALM]
	ADD
	CONSTRAINT [DF_TempBOM_DESCALM_ALMD_LOCALIDAD]
	DEFAULT ('') FOR [ALMD_LOCALIDAD]
GO
ALTER TABLE [dbo].[TempBOM_DESCALM]
	ADD
	CONSTRAINT [DF_TempBOM_DESCALM_ALMD_NIVEL]
	DEFAULT ('') FOR [ALMD_NIVEL]
GO
ALTER TABLE [dbo].[TempBOM_DESCALM]
	ADD
	CONSTRAINT [DF_TempBOM_DESCALM_ALMD_PASILLO]
	DEFAULT ('') FOR [ALMD_PASILLO]
GO
ALTER TABLE [dbo].[TempBOM_DESCALM]
	ADD
	CONSTRAINT [DF_TempBOM_DESCALM_BST_DISCH]
	DEFAULT ('S') FOR [BST_DISCH]
GO
ALTER TABLE [dbo].[TempBOM_DESCALM]
	ADD
	CONSTRAINT [DF_TempBOM_DESCALM_BST_INCORPOR]
	DEFAULT (1) FOR [BST_INCORPOR]
GO
ALTER TABLE [dbo].[TempBOM_DESCALM]
	ADD
	CONSTRAINT [DF_TempBOM_DESCALM_BST_PERFIN]
	DEFAULT ('01/01/9999') FOR [BST_PERFIN]
GO
ALTER TABLE [dbo].[TempBOM_DESCALM]
	ADD
	CONSTRAINT [DF_TempBOM_DESCALM_BST_TRANS]
	DEFAULT ('N') FOR [BST_TRANS]
GO
ALTER TABLE [dbo].[TempBOM_DESCALM]
	ADD
	CONSTRAINT [DF_TempBOM_DESCALM_FACTCONVALM]
	DEFAULT (1) FOR [FACTCONVALM]
GO
ALTER TABLE [dbo].[TempBOM_DESCALM] SET (LOCK_ESCALATION = TABLE)
GO
