SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[ORDTRABAJOEXPLODET] (
		[OTE_INDICED]     [int] NOT NULL,
		[END_INDICED]     [int] NOT NULL,
		[OTED_CANT]       [decimal](38, 6) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDTRABAJOEXPLODET]
	ADD
	CONSTRAINT [PK_ORDTRABAJOEXPLODET]
	PRIMARY KEY
	CLUSTERED
	([OTE_INDICED], [END_INDICED])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDTRABAJOEXPLODET] SET (LOCK_ESCALATION = TABLE)
GO
