SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPEMPAQUE] (
		[FEE_INDICE]         [int] NOT NULL,
		[FE_CODIGO]          [int] NULL,
		[MA_EMP1]            [int] NULL,
		[MA_EMP2]            [int] NULL,
		[FEE_EMP2_CANT]      [decimal](38, 6) NULL,
		[FEE_TOT_EMP1]       [decimal](38, 6) NULL,
		[FEE_TOT_EMP2]       [decimal](38, 6) NULL,
		[FEE_RELEMPAQUE]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPEMPAQUE]
	ADD
	CONSTRAINT [PK_FACTEXPEMPAQUE]
	PRIMARY KEY
	NONCLUSTERED
	([FEE_INDICE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPEMPAQUE]
	ADD
	CONSTRAINT [DF_FACTEXPEMPAQUE_FEE_RELEMPAQUE]
	DEFAULT ('N') FOR [FEE_RELEMPAQUE]
GO
CREATE NONCLUSTERED INDEX [IX_FACTEXPEMPAQUE]
	ON [dbo].[FACTEXPEMPAQUE] ([FE_CODIGO])
	WITH ( FILLFACTOR = 90)
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPEMPAQUE] SET (LOCK_ESCALATION = TABLE)
GO
