SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PAIS] (
		[PA_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[PA_CORTO]          [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PA_NOMBRE]         [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PA_NAME]           [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PA_CLA_PED]        [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PA_ISO]            [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PA_SAAIM3]         [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PA_IATA]           [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SPI_CODIGO]        [smallint] NULL,
		[PA_CODPERMISO]     [int] NULL,
		CONSTRAINT [IX_PAIS]
		UNIQUE
		NONCLUSTERED
		([PA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAIS]
	ADD
	CONSTRAINT [PK_PAIS]
	PRIMARY KEY
	NONCLUSTERED
	([PA_CORTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAIS]
	ADD
	CONSTRAINT [DF_PAIS_PA_CLA_PED]
	DEFAULT ('') FOR [PA_CLA_PED]
GO
ALTER TABLE [dbo].[PAIS]
	ADD
	CONSTRAINT [DF_PAIS_PA_IATA]
	DEFAULT ('') FOR [PA_IATA]
GO
ALTER TABLE [dbo].[PAIS]
	ADD
	CONSTRAINT [DF_PAIS_PA_ISO]
	DEFAULT ('') FOR [PA_ISO]
GO
ALTER TABLE [dbo].[PAIS]
	ADD
	CONSTRAINT [DF_PAIS_PA_SAAIM3]
	DEFAULT ('') FOR [PA_SAAIM3]
GO
CREATE CLUSTERED INDEX [IX_PAIS_1]
	ON [dbo].[PAIS] ([PA_CODIGO], [PA_CORTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAIS] SET (LOCK_ESCALATION = TABLE)
GO
