SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IDENTIFICA] (
		[IDE_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[IDE_CLAVE]          [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDE_NOMBRE]         [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDE_DESC]           [varchar](1500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDE_NIVEL]          [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDE_TIPO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDE_CANTCAMP]       [smallint] NOT NULL,
		[IDE_INCLUIDOAP]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDE_MOTIVO]         [varchar](1500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDE_IDENTPERM]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDE_TABLA]          [int] NOT NULL,
		[IDE_CAMPO]          [int] NOT NULL,
		[IDE_CAMPO2]         [int] NOT NULL,
		[IDE_APLICA]         [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDE_USAFACT]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDE_MOTIVOB]        [varchar](1500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDE_TIPOB]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDE_TABLAB]         [int] NULL,
		[IDE_CAMPOB]         [int] NULL,
		[IDE_CAMPO2B]        [int] NULL,
		[IDE_MOTIVOC]        [varchar](1500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDE_TIPOC]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDE_TABLAC]         [int] NULL,
		[IDE_CAMPOC]         [int] NULL,
		[IDE_CAMPO2C]        [int] NULL,
		[IDE_OBSOLETO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_IDENTIFICA]
		UNIQUE
		NONCLUSTERED
		([IDE_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [PK_IDENTIFICA]
	PRIMARY KEY
	NONCLUSTERED
	([IDE_CLAVE], [IDE_NIVEL], [IDE_IDENTPERM])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_CAMPO]
	DEFAULT (0) FOR [IDE_CAMPO]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_CAMPO2]
	DEFAULT (0) FOR [IDE_CAMPO2]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_CAMPO2B]
	DEFAULT (0) FOR [IDE_CAMPO2B]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_CAMPO2C]
	DEFAULT (0) FOR [IDE_CAMPO2C]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_CAMPOB]
	DEFAULT (0) FOR [IDE_CAMPOB]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_CAMPOC]
	DEFAULT (0) FOR [IDE_CAMPOC]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_CANTCAMP]
	DEFAULT (1) FOR [IDE_CANTCAMP]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_IDENTPERM]
	DEFAULT ('I') FOR [IDE_IDENTPERM]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_INCLUIDOAP]
	DEFAULT ('S') FOR [IDE_INCLUIDOAP]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_NIVEL]
	DEFAULT ('G') FOR [IDE_NIVEL]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_OBSOLETO]
	DEFAULT ('N') FOR [IDE_OBSOLETO]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_TABLA]
	DEFAULT (0) FOR [IDE_TABLA]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_TABLAB]
	DEFAULT (0) FOR [IDE_TABLAB]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_TABLAC]
	DEFAULT (0) FOR [IDE_TABLAC]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_TIPO]
	DEFAULT ('4') FOR [IDE_TIPO]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_TIPOB]
	DEFAULT ('4') FOR [IDE_TIPOB]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_TIPOC]
	DEFAULT ('4') FOR [IDE_TIPOC]
GO
ALTER TABLE [dbo].[IDENTIFICA]
	ADD
	CONSTRAINT [DF_IDENTIFICA_IDE_USAFACT]
	DEFAULT ('S') FOR [IDE_USAFACT]
GO
ALTER TABLE [dbo].[IDENTIFICA] SET (LOCK_ESCALATION = TABLE)
GO
