SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[MAESTROSUST] (
		[MAS_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[MA_CODIGO]         [int] NOT NULL,
		[MA_CODIGOSUST]     [int] NOT NULL,
		[EQ_CANT]           [decimal](28, 14) NOT NULL,
		CONSTRAINT [IX_MAESTROSUST]
		UNIQUE
		NONCLUSTERED
		([MAS_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROSUST]
	ADD
	CONSTRAINT [PK_MAESTROSUST]
	PRIMARY KEY
	NONCLUSTERED
	([MA_CODIGO], [MA_CODIGOSUST])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROSUST]
	ADD
	CONSTRAINT [DF_MAESTROSUST_EQ_CANT]
	DEFAULT (1) FOR [EQ_CANT]
GO
ALTER TABLE [dbo].[MAESTROSUST] SET (LOCK_ESCALATION = TABLE)
GO
