SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPLEMENTAPEDIMPDET] (
		[PI_CODIGOIMP]       [int] NOT NULL,
		[PID_INDICED]        [int] NOT NULL,
		[MA_CODIGO]          [int] NOT NULL,
		[PID_NOPARTE]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PID_NOMBRE]         [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PID_NAME]           [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PID_COS_UNI]        [decimal](38, 6) NOT NULL,
		[PID_COS_UNIGEN]     [decimal](38, 6) NOT NULL,
		[PID_COS_UNIVA]      [decimal](38, 6) NOT NULL,
		[PID_CANT]           [decimal](38, 6) NOT NULL,
		[PID_CAN_AR]         [decimal](38, 6) NOT NULL,
		[PID_CAN_GEN]        [decimal](38, 6) NOT NULL,
		[PID_VAL_ADU]        [decimal](38, 6) NOT NULL,
		[PID_CTOT_DLS]       [decimal](38, 6) NOT NULL,
		[ME_CODIGO]          [int] NULL,
		[ME_GENERICO]        [int] NULL,
		[PID_OBSERVA]        [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MA_GENERICO]        [int] NOT NULL,
		[EQ_GENERICO]        [decimal](28, 14) NOT NULL,
		[EQ_IMPMX]           [decimal](28, 14) NOT NULL,
		[AR_IMPMX]           [int] NULL,
		[ME_ARIMPMX]         [int] NULL,
		[AR_EXPFO]           [int] NULL,
		[PID_RATEEXPFO]      [decimal](38, 6) NULL,
		[PID_SEC_IMP]        [smallint] NULL,
		[PID_DEF_TIP]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PID_POR_DEF]        [decimal](38, 6) NOT NULL,
		[CS_CODIGO]          [smallint] NULL,
		[PID_SALDOGEN]       [decimal](38, 6) NULL,
		[TI_CODIGO]          [smallint] NOT NULL,
		[PA_ORIGEN]          [int] NULL,
		[PA_PROCEDE]         [int] NULL,
		[SPI_CODIGO]         [smallint] NULL,
		[PR_CODIGO]          [int] NULL,
		[EQ_EXPFO]           [decimal](28, 14) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_EQ_EXPFO]
	DEFAULT (1) FOR [EQ_EXPFO]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_EQ_GENERICO]
	DEFAULT (1) FOR [EQ_GENERICO]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_EQ_IMPMX]
	DEFAULT (1) FOR [EQ_IMPMX]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_MA_GENERICO]
	DEFAULT (0) FOR [MA_GENERICO]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_CAN_AR]
	DEFAULT (0) FOR [PID_CAN_AR]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_CAN_GEN]
	DEFAULT (0) FOR [PID_CAN_GEN]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_CANT]
	DEFAULT (0) FOR [PID_CANT]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_COS_UNI]
	DEFAULT (0) FOR [PID_COS_UNI]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_COS_UNIGEN]
	DEFAULT (0) FOR [PID_COS_UNIGEN]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_COS_UNIVA]
	DEFAULT (0) FOR [PID_COS_UNIVA]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_CTOT_DLS]
	DEFAULT (0) FOR [PID_CTOT_DLS]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_DEF_TIP]
	DEFAULT ('G') FOR [PID_DEF_TIP]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_NOPARTE]
	DEFAULT ('') FOR [PID_NOPARTE]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_POR_DEF]
	DEFAULT (0) FOR [PID_POR_DEF]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET]
	ADD
	CONSTRAINT [DF_IMPLEMENTAPEDIMPDET_PID_VAL_ADU]
	DEFAULT (0) FOR [PID_VAL_ADU]
GO
ALTER TABLE [dbo].[IMPLEMENTAPEDIMPDET] SET (LOCK_ESCALATION = TABLE)
GO
