SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTROCARA] (
		[MA_CODIGO]                   [int] NOT NULL,
		[MAC_CARACTERISTICA]          [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAC_VALORCARACTERISTICA]     [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROCARA]
	ADD
	CONSTRAINT [PK_MAESTROCARA]
	PRIMARY KEY
	NONCLUSTERED
	([MA_CODIGO], [MAC_CARACTERISTICA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROCARA] SET (LOCK_ESCALATION = TABLE)
GO
