SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTROREFER] (
		[MA_CODIGO]         [int] NOT NULL,
		[MA_NOPARTE]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_NOPARTEAUX]     [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TI_CODIGO]         [int] NOT NULL,
		[MA_NOMBRE]         [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MA_NAME]           [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ME_COM]            [int] NULL,
		[MA_TIP_ENS]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MA_EST_MAT]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_GENERICO]       [int] NOT NULL,
		[EQ_GEN]            [decimal](28, 14) NOT NULL,
		[MA_PESO_KG]        [decimal](38, 6) NULL,
		[MA_PESO_LB]        [decimal](38, 6) NULL,
		[PA_ORIGEN]         [int] NULL,
		[MA_TRANS]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROREFER]
	ADD
	CONSTRAINT [PK_MAESTROREFER]
	PRIMARY KEY
	CLUSTERED
	([MA_NOPARTE], [MA_NOPARTEAUX])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROREFER]
	ADD
	CONSTRAINT [DF_MAESTROREFER_EQ_GEN]
	DEFAULT (1) FOR [EQ_GEN]
GO
ALTER TABLE [dbo].[MAESTROREFER]
	ADD
	CONSTRAINT [DF_MAESTROREFER_MA_EST_MAT]
	DEFAULT ('A') FOR [MA_EST_MAT]
GO
ALTER TABLE [dbo].[MAESTROREFER]
	ADD
	CONSTRAINT [DF_MAESTROREFER_MA_GENERICO]
	DEFAULT (0) FOR [MA_GENERICO]
GO
ALTER TABLE [dbo].[MAESTROREFER]
	ADD
	CONSTRAINT [DF_MAESTROREFER_MA_NOPARTEAUX]
	DEFAULT ('') FOR [MA_NOPARTEAUX]
GO
ALTER TABLE [dbo].[MAESTROREFER]
	ADD
	CONSTRAINT [DF_MAESTROREFER_TI_CODIGO]
	DEFAULT (16) FOR [TI_CODIGO]
GO
ALTER TABLE [dbo].[MAESTROREFER] SET (LOCK_ESCALATION = TABLE)
GO
