SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPORTARINVFISICO] (
		[IIF_CODIGO]              [int] IDENTITY(1, 1) NOT NULL,
		[IIF_NOPARTE]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IIF_CANTIDAD]            [decimal](18, 0) NULL,
		[IIF_UM]                  [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IIF_TIPOMATERIAL]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IIF_NOPARTEAUX]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IIF_TIPOADQUISICION]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTARINVFISICO]
	ADD
	CONSTRAINT [PK_IMPORTARINVFISICO]
	PRIMARY KEY
	CLUSTERED
	([IIF_CODIGO])
	ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_IMPORTARINVFISICO]
	ON [dbo].[IMPORTARINVFISICO] ([IIF_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTARINVFISICO] SET (LOCK_ESCALATION = TABLE)
GO
