SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CFGCNXDIRECTA] (
		[CCD_FRMTAG]        [int] NOT NULL,
		[CCD_BTNTAG]        [int] NOT NULL,
		[CCD_CADENACNX]     [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CCD_USUARIO]       [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CCD_CLAVE]         [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CCD_ENUNCIADO]     [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CFGCNXDIRECTA] SET (LOCK_ESCALATION = TABLE)
GO
