SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PCKLISTADVERTENCIA] (
		[PLN_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[PL_CODIGO]         [int] NOT NULL,
		[PL_COMENTARIO]     [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_PCKLISTADVERTENCIA]
		UNIQUE
		NONCLUSTERED
		([PLN_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PCKLISTADVERTENCIA] SET (LOCK_ESCALATION = TABLE)
GO
