SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPFP] (
		[PI_CODIGO]     [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PG_CODIGO]     [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMPUESTO]      [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPFP] SET (LOCK_ESCALATION = TABLE)
GO
