SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURAGRID] (
		[CFM_CODIGO]           [int] IDENTITY(1, 1) NOT NULL,
		[CFM_TIPO]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFM_MOSTRAR]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFM_CAMPO]            [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFM_CAMPOLOOKUP]      [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_GRID]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFM_TIPOOPERADOR]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFG_CODIGO]           [int] NULL,
		CONSTRAINT [IX_CONFIGURAGRID]
		UNIQUE
		NONCLUSTERED
		([CFM_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAGRID]
	ADD
	CONSTRAINT [PK_CONFIGURAGRID]
	PRIMARY KEY
	NONCLUSTERED
	([CFM_TIPO], [CFM_CAMPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAGRID]
	ADD
	CONSTRAINT [DF_CONFIGURAGRID_CFM_GRID]
	DEFAULT ('I') FOR [CFM_GRID]
GO
ALTER TABLE [dbo].[CONFIGURAGRID]
	ADD
	CONSTRAINT [DF_CONFIGURAGRID_CFM_MOSTRAR]
	DEFAULT ('S') FOR [CFM_MOSTRAR]
GO
ALTER TABLE [dbo].[CONFIGURAGRID] SET (LOCK_ESCALATION = TABLE)
GO
