SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURATMOVIMIENTO] (
		[TM_CODIGO]     [int] NOT NULL,
		[CFM_TIPO]      [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURATMOVIMIENTO]
	ADD
	CONSTRAINT [PK_CONFIGURATMOVIMIENTO]
	PRIMARY KEY
	NONCLUSTERED
	([TM_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURATMOVIMIENTO] SET (LOCK_ESCALATION = TABLE)
GO
