SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONSECUTIVO] (
		[CV_CODIGO]     [int] NOT NULL,
		[CV_TIPO]       [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CV_TABLA]      [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CV_CAMPO]      [varchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONSECUTIVO]
	ADD
	CONSTRAINT [PK_CONSECUTIVO]
	PRIMARY KEY
	NONCLUSTERED
	([CV_CODIGO], [CV_TIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONSECUTIVO] SET (LOCK_ESCALATION = TABLE)
GO
