SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROGTARCOLA] (
		[PCO_CODIGO]       [int] IDENTITY(1, 1) NOT NULL,
		[PTA_CODIGO]       [int] NOT NULL,
		[PCO_SERVIDOR]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_PROGTARCOLA]
		UNIQUE
		NONCLUSTERED
		([PCO_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROGTARCOLA]
	ADD
	CONSTRAINT [DF_PROGTARCOLA_PTA_CODIGO]
	DEFAULT (0) FOR [PTA_CODIGO]
GO
ALTER TABLE [dbo].[PROGTARCOLA] SET (LOCK_ESCALATION = TABLE)
GO
