SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RELTFACTTEMBAR] (
		[TF_CODIGO]       [smallint] NOT NULL,
		[TQ_CODIGO]       [smallint] NOT NULL,
		[REL_OBSERVA]     [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CP_CODIGO]       [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RELTFACTTEMBAR]
	ADD
	CONSTRAINT [PK_RELTFACTTEMBAR]
	PRIMARY KEY
	NONCLUSTERED
	([TF_CODIGO], [TQ_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[RELTFACTTEMBAR] SET (LOCK_ESCALATION = TABLE)
GO
