SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRODUC] (
		[PRO_CODIGO]      [int] NOT NULL,
		[PRO_FOLIO]       [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRO_FECHA]       [datetime] NOT NULL,
		[US_CODIGO]       [int] NOT NULL,
		[PRO_COMENTA]     [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ARE_CODIGO]      [int] NOT NULL,
		[PRO_ESTATUS]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_PRODUC]
		UNIQUE
		NONCLUSTERED
		([PRO_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUC]
	ADD
	CONSTRAINT [PK_PRODUC]
	PRIMARY KEY
	NONCLUSTERED
	([PRO_FOLIO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUC]
	ADD
	CONSTRAINT [DF_PRODUC_PRO_ESTATUS]
	DEFAULT ('S') FOR [PRO_ESTATUS]
GO
ALTER TABLE [dbo].[PRODUC] SET (LOCK_ESCALATION = TABLE)
GO
