SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXPORTSPECFILES] (
		[EMN_CODIGO]       [int] NOT NULL,
		[EMS_CODIGO]       [int] NOT NULL,
		[EMS_FILENAME]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EMS_KEYVALUE]     [varchar](5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXPORTSPECFILES]
	ADD
	CONSTRAINT [PK_EXPORTSPECFILES]
	PRIMARY KEY
	CLUSTERED
	([EMS_CODIGO], [EMS_FILENAME])
	WITH FILLFACTOR=90
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXPORTSPECFILES]
	ADD
	CONSTRAINT [DF_EXPORTSPECFILES_EMN_CODIGO]
	DEFAULT (0) FOR [EMN_CODIGO]
GO
ALTER TABLE [dbo].[EXPORTSPECFILES] SET (LOCK_ESCALATION = TABLE)
GO
