SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BONDTYPE] (
		[BT_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[BT_CLAVE]      [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BT_NOMBRE]     [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BT_NAME]       [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_BONDTYPE]
		UNIQUE
		NONCLUSTERED
		([BT_CODIGO])
		WITH FILLFACTOR=90
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BONDTYPE]
	ADD
	CONSTRAINT [PK_BONDTYPE]
	PRIMARY KEY
	NONCLUSTERED
	([BT_CLAVE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[BONDTYPE]
	ADD
	CONSTRAINT [DF_BONDTYPE_BT_NOMBRE]
	DEFAULT ('') FOR [BT_NOMBRE]
GO
ALTER TABLE [dbo].[BONDTYPE] SET (LOCK_ESCALATION = TABLE)
GO
