SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[UnitOfMeasureConversion] (
		[Oid]                     [uniqueidentifier] NOT NULL ROWGUIDCOL,
		[UnitOfMeasure]           [uniqueidentifier] NULL,
		[ToUnitOfMeasure]         [uniqueidentifier] NULL,
		[ConversionFactor]        [float] NULL,
		[IsAutoGenerated]         [bit] NULL,
		[OptimisticLockField]     [int] NULL,
		CONSTRAINT [PK_UnitOfMeasureConversion]
		PRIMARY KEY
		CLUSTERED
		([Oid])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UnitOfMeasureConversion]
	WITH NOCHECK
	ADD CONSTRAINT [FK_UnitOfMeasureConversion_ToUnitOfMeasure]
	FOREIGN KEY ([ToUnitOfMeasure]) REFERENCES [dbo].[UnitOfMeasure] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[UnitOfMeasureConversion]
	CHECK CONSTRAINT [FK_UnitOfMeasureConversion_ToUnitOfMeasure]

GO
ALTER TABLE [dbo].[UnitOfMeasureConversion]
	WITH NOCHECK
	ADD CONSTRAINT [FK_UnitOfMeasureConversion_UnitOfMeasure]
	FOREIGN KEY ([UnitOfMeasure]) REFERENCES [dbo].[UnitOfMeasure] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[UnitOfMeasureConversion]
	CHECK CONSTRAINT [FK_UnitOfMeasureConversion_UnitOfMeasure]

GO
CREATE NONCLUSTERED INDEX [iToUnitOfMeasure_UnitOfMeasureConversion]
	ON [dbo].[UnitOfMeasureConversion] ([ToUnitOfMeasure])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iUnitOfMeasure_UnitOfMeasureConversion]
	ON [dbo].[UnitOfMeasureConversion] ([UnitOfMeasure])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[UnitOfMeasureConversion] SET (LOCK_ESCALATION = TABLE)
GO
