SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[WantListItem] (
		[Oid]                                       [uniqueidentifier] NOT NULL ROWGUIDCOL,
		[Item]                                      [uniqueidentifier] NULL,
		[RequestedQuantityDecimalValue]             [decimal](19, 5) NULL,
		[RequestedQuantityStringValue]              [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
		[PurchaserAssignedQuantityDecimalValue]     [decimal](19, 5) NULL,
		[PurchaserAssignedQuantityStringValue]      [nvarchar](100) COLLATE Latin1_General_CI_AS NULL,
		[UnitOfMeasure]                             [uniqueidentifier] NULL,
		[RequestedManufacturer]                     [uniqueidentifier] NULL,
		[RequestedVendor]                           [uniqueidentifier] NULL,
		[RequestedBy]                               [uniqueidentifier] NULL,
		[ProcessedOnBehalfOf]                       [uniqueidentifier] NULL,
		[RequestedOn]                               [datetime] NULL,
		[WorkOrder]                                 [uniqueidentifier] NULL,
		[WorkOrderGroup]                            [uniqueidentifier] NULL,
		[DeferAutoOrderUntil]                       [datetime] NULL,
		[AutoGenerated]                             [bit] NULL,
		[IsCancelled]                               [bit] NULL,
		[IsLegacy]                                  [bit] NULL,
		[IsUrgent]                                  [bit] NULL,
		[MarkForAutoOrder]                          [bit] NULL,
		[PurchaseOrderLineItem]                     [uniqueidentifier] NULL,
		[Note]                                      [nvarchar](2500) COLLATE Latin1_General_CI_AS NULL,
		[OptimisticLockField]                       [int] NULL,
		[GCRecord]                                  [int] NULL,
		CONSTRAINT [PK_WantListItem]
		PRIMARY KEY
		CLUSTERED
		([Oid])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WantListItem]
	WITH NOCHECK
	ADD CONSTRAINT [FK_WantListItem_Item]
	FOREIGN KEY ([Item]) REFERENCES [dbo].[Item] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[WantListItem]
	CHECK CONSTRAINT [FK_WantListItem_Item]

GO
ALTER TABLE [dbo].[WantListItem]
	WITH NOCHECK
	ADD CONSTRAINT [FK_WantListItem_ProcessedOnBehalfOf]
	FOREIGN KEY ([ProcessedOnBehalfOf]) REFERENCES [dbo].[ExtendedSecurityUser] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[WantListItem]
	CHECK CONSTRAINT [FK_WantListItem_ProcessedOnBehalfOf]

GO
ALTER TABLE [dbo].[WantListItem]
	WITH NOCHECK
	ADD CONSTRAINT [FK_WantListItem_PurchaseOrderLineItem]
	FOREIGN KEY ([PurchaseOrderLineItem]) REFERENCES [dbo].[PurchaseOrderLineItem] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[WantListItem]
	CHECK CONSTRAINT [FK_WantListItem_PurchaseOrderLineItem]

GO
ALTER TABLE [dbo].[WantListItem]
	WITH NOCHECK
	ADD CONSTRAINT [FK_WantListItem_RequestedBy]
	FOREIGN KEY ([RequestedBy]) REFERENCES [dbo].[ExtendedSecurityUser] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[WantListItem]
	CHECK CONSTRAINT [FK_WantListItem_RequestedBy]

GO
ALTER TABLE [dbo].[WantListItem]
	WITH NOCHECK
	ADD CONSTRAINT [FK_WantListItem_RequestedManufacturer]
	FOREIGN KEY ([RequestedManufacturer]) REFERENCES [dbo].[Manufacturer] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[WantListItem]
	CHECK CONSTRAINT [FK_WantListItem_RequestedManufacturer]

GO
ALTER TABLE [dbo].[WantListItem]
	WITH NOCHECK
	ADD CONSTRAINT [FK_WantListItem_RequestedVendor]
	FOREIGN KEY ([RequestedVendor]) REFERENCES [dbo].[Vendor] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[WantListItem]
	CHECK CONSTRAINT [FK_WantListItem_RequestedVendor]

GO
ALTER TABLE [dbo].[WantListItem]
	WITH NOCHECK
	ADD CONSTRAINT [FK_WantListItem_UnitOfMeasure]
	FOREIGN KEY ([UnitOfMeasure]) REFERENCES [dbo].[UnitOfMeasure] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[WantListItem]
	CHECK CONSTRAINT [FK_WantListItem_UnitOfMeasure]

GO
ALTER TABLE [dbo].[WantListItem]
	WITH NOCHECK
	ADD CONSTRAINT [FK_WantListItem_WorkOrder]
	FOREIGN KEY ([WorkOrder]) REFERENCES [dbo].[WorkOrder] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[WantListItem]
	CHECK CONSTRAINT [FK_WantListItem_WorkOrder]

GO
ALTER TABLE [dbo].[WantListItem]
	WITH NOCHECK
	ADD CONSTRAINT [FK_WantListItem_WorkOrderGroup]
	FOREIGN KEY ([WorkOrderGroup]) REFERENCES [dbo].[WorkOrderGroup] ([Oid])
	NOT FOR REPLICATION
ALTER TABLE [dbo].[WantListItem]
	CHECK CONSTRAINT [FK_WantListItem_WorkOrderGroup]

GO
CREATE NONCLUSTERED INDEX [iGCRecord_WantListItem]
	ON [dbo].[WantListItem] ([GCRecord])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iItem_WantListItem]
	ON [dbo].[WantListItem] ([Item])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iProcessedOnBehalfOf_WantListItem]
	ON [dbo].[WantListItem] ([ProcessedOnBehalfOf])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iPurchaseOrderLineItem_WantListItem]
	ON [dbo].[WantListItem] ([PurchaseOrderLineItem])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iRequestedBy_WantListItem]
	ON [dbo].[WantListItem] ([RequestedBy])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iRequestedManufacturer_WantListItem]
	ON [dbo].[WantListItem] ([RequestedManufacturer])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iRequestedVendor_WantListItem]
	ON [dbo].[WantListItem] ([RequestedVendor])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iUnitOfMeasure_WantListItem]
	ON [dbo].[WantListItem] ([UnitOfMeasure])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iWorkOrder_WantListItem]
	ON [dbo].[WantListItem] ([WorkOrder])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [iWorkOrderGroup_WantListItem]
	ON [dbo].[WantListItem] ([WorkOrderGroup])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[WantListItem] SET (LOCK_ESCALATION = TABLE)
GO
