SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_temp_CertOrigLista]   as

SET NOCOUNT ON 

UPDATE dbo.CERTORIGMPDET
SET     dbo.CERTORIGMPDET.CMP_CLASE= dbo.NAFTA.NFT_CLASE, dbo.CERTORIGMPDET.CMP_FABRICA= dbo.NAFTA.NFT_FABRICA, 
                      dbo.CERTORIGMPDET.CMP_CRITERIO= dbo.NAFTA.NFT_CRITERIO, dbo.CERTORIGMPDET.CMP_NETCOST= dbo.NAFTA.NFT_NETCOST, 
                      dbo.CERTORIGMPDET.CMP_OTRASINST= dbo.NAFTA.NFT_OTRASINST
FROM         dbo.NAFTA INNER JOIN
                      dbo.CERTORIGMPDET ON dbo.NAFTA.MA_CODIGO = dbo.CERTORIGMPDET.MA_CODIGO



























GO
