SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_ACTUALIZACOSTOTCOSTOFACTEXP] (@FE_CODIGO INT)   as


		ALTER TABLE FACTEXPDET DISABLE trigger [Update_FactExpDet]
	
	
	UPDATE FACTEXPDET
	SET     FACTEXPDET.FED_GRA_MP= MAESTROCOST.MA_GRAV_MP, FACTEXPDET.FED_GRA_MO= MAESTROCOST.MA_GRAV_MO, 
	                      FACTEXPDET.FED_GRA_EMP= MAESTROCOST.MA_GRAV_EMP, FACTEXPDET.FED_GRA_ADD= MAESTROCOST.MA_GRAV_ADD, 
	                      FACTEXPDET.FED_GRA_GI= MAESTROCOST.MA_GRAV_GI, FACTEXPDET.FED_GRA_GI_MX= MAESTROCOST.MA_GRAV_GI_MX, 
	                      FACTEXPDET.FED_NG_MP= MAESTROCOST.MA_NG_MP, FACTEXPDET.FED_NG_EMP= MAESTROCOST.MA_NG_EMP, FACTEXPDET.FED_NG_ADD= 
	                      MAESTROCOST.MA_NG_ADD, FACTEXPDET.FED_NG_USA= MAESTROCOST.MA_NG_USA, FACTEXPDET.FED_COS_UNI= MAESTROCOST.MA_COSTO, 
	                      FACTEXPDET.FED_COS_TOT=FACTEXPDET.FED_CANT*MAESTROCOST.MA_COSTO
	FROM         FACTEXPDET INNER JOIN
	                      MAESTROCOST ON FACTEXPDET.TCO_CODIGO = MAESTROCOST.TCO_CODIGO AND FACTEXPDET.MA_CODIGO = MAESTROCOST.MA_CODIGO
	WHERE     (FACTEXPDET.FE_CODIGO = @FE_CODIGO)
	

	-- actualiza tasas
	UPDATE FACTEXPDET  
	SET FACTEXPDET.FED_RATEIMPFO= ARANCEL.AR_ADVDEF
	FROM  FACTEXPDET INNER JOIN 
	  ARANCEL ON FACTEXPDET.AR_IMPFO = ARANCEL.AR_CODIGO 
	WHERE     FACTEXPDET.FE_CODIGO =@fe_codigo AND FACTEXPDET.FED_NAFTA='N'
	

	UPDATE FACTEXPDET  
	SET FACTEXPDET.FED_RATEIMPFO= 0
	FROM  FACTEXPDET INNER JOIN 
	  ARANCEL ON FACTEXPDET.AR_IMPFO = ARANCEL.AR_CODIGO 
	WHERE     FACTEXPDET.FE_CODIGO =@fe_codigo AND FACTEXPDET.FED_NAFTA='S'

	ALTER TABLE FACTEXPDET ENABLE trigger [Update_FactExpDet]








GO
