SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_IMPEXCELRELENTRYFACT]   as

SET NOCOUNT ON 
DECLARE @NOENTRY VARCHAR(25), @EA_CODIGO INT, @FECHA DATETIME, @ET_CODIGO INT


DELETE FROM IMPORTLOG WHERE IML_CBFORMA=87

if (select count(*) from IMPORTLOG)=0
DBCC CHECKIDENT (IMPORTLOG, RESEED, 0) WITH NO_INFOMSGS


delete from IMPEXCELRELFACTENTRY where FACTURA=''


if exists(SELECT dbo.IMPEXCELRELFACTENTRY.FACTURA
	FROM         dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.IMPEXCELRELFACTENTRY ON dbo.FACTEXP.FE_FOLIO = dbo.IMPEXCELRELFACTENTRY.FACTURA
	WHERE     (dbo.FACTEXP.FE_FOLIO IS NULL))

	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR LA RELACION CON LA FACTURA CON FOLIO : ' +dbo.IMPEXCELRELFACTENTRY.FACTURA +' POR QUE NO EXISTE EN LOS DOCUMENTOS DE SALIDA', 35
	FROM         dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.IMPEXCELRELFACTENTRY ON dbo.FACTEXP.FE_FOLIO = dbo.IMPEXCELRELFACTENTRY.FACTURA
	WHERE     (dbo.FACTEXP.FE_FOLIO IS NULL) 




/* se ejecutan los procedimientos para llenar el detalle */

DECLARE CUR_IMPEXCELRELENTRY CURSOR FOR
	SELECT NOENTRY, isnull((SELECT EA_CODIGO FROM ENTRADA_A WHERE EA_CLAVE=TIPOENTRY),2), FECHA 
	FROM IMPEXCELRELFACTENTRY
	WHERE FACTURA IS NOT NULL AND NOENTRY IS NOT NULL

	GROUP BY NOENTRY, TIPOENTRY, FECHA
OPEN CUR_IMPEXCELRELENTRY
FETCH NEXT FROM CUR_IMPEXCELRELENTRY INTO @NOENTRY, @EA_CODIGO, @FECHA
WHILE (@@FETCH_STATUS = 0) 
BEGIN



	IF NOT EXISTS (SELECT * FROM ENTRYSUM WHERE ET_ENTRY_NO=@NOENTRY)
	BEGIN
		EXEC  SP_GETCONSECUTIVO 'ET', @VALUE = @ET_CODIGO OUTPUT
	
		
		INSERT INTO ENTRYSUM(ET_CODIGO, ET_ENTRY_NO, EA_ENTRADA, EB_ENTRADA, ET_FEC_ENTRY, ET_FEC_ENTRYS, ET_FEC_GEN, ET_FEC_IMP)
		VALUES (@ET_CODIGO, @NOENTRY, @EA_CODIGO, 1, @FECHA, @FECHA, @FECHA, @FECHA)
	END
	ELSE
	SELECT @ET_CODIGO = ET_CODIGO FROM ENTRYSUM WHERE ET_ENTRY_NO=@NOENTRY


	UPDATE FACTEXP
	SET     FACTEXP.ET_CODIGO= @ET_CODIGO
	FROM   FACTEXP WHERE 
	FE_FOLIO IN (SELECT FACTURA FROM IMPEXCELRELFACTENTRY WHERE NOENTRY=@NOENTRY GROUP BY FACTURA)


	DELETE FROM ENTRYSUMARA WHERE ET_CODIGO=@ET_CODIGO
	exec SP_FILLENTRYSUMARA @ET_CODIGO



	FETCH NEXT FROM CUR_IMPEXCELRELENTRY INTO @NOENTRY, @EA_CODIGO, @FECHA
END
CLOSE CUR_IMPEXCELRELENTRY
DEALLOCATE CUR_IMPEXCELRELENTRY





















GO
