SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_ReestructuraSaldosPermisos]   as


			exec  sp_droptable 'indicedPer'

		SELECT KARDESPERMISO.PED_INDICED, FI_CODIGO, PE_CODIGO, FIR_CODIGO
		INTO dbo.indicedPer
		FROM KARDESPERMISO INNER JOIN PERMISODET ON KARDESPERMISO.PED_INDICED=PERMISODET.PED_INDICED
		WHERE KARDESPERMISO.PED_INDICED IS NOT NULL 
		GROUP BY KARDESPERMISO.PED_INDICED, FI_CODIGO, PE_CODIGO, FIR_CODIGO

		UPDATE FACTIMPPERM
		SET FIP_ESTATUSAFECTA=0
		WHERE FIR_CODIGO NOT IN (SELECT FIR_CODIGO FROM indicedPer)

		if exists(select * from indicedPer)
		begin

			UPDATE dbo.PERMISODET
			SET     dbo.PERMISODET.PED_SALDO= round(dbo.VPERMISOSALDO.KAR_SALDO,6),
			dbo.PERMISODET.PED_SALDOCOSTOT= round(dbo.VPERMISOSALDO.KAR_SALDOCOSTOT,6)
			FROM         dbo.PERMISODET INNER JOIN
			                      dbo.VPERMISOSALDO ON dbo.PERMISODET.PED_INDICED = dbo.VPERMISOSALDO.PED_INDICED 
			WHERE (round(dbo.PERMISODET.PED_SALDO,6) <> round(dbo.VPERMISOSALDO.KAR_SALDO,6)
			        or round(dbo.PERMISODET.PED_SALDOCOSTOT,6) <> round(dbo.VPERMISOSALDO.KAR_SALDOCOSTOT,6))
				and dbo.PERMISODET.PED_INDICED IN (SELECT PED_INDICED FROM indicedPer)
		
			UPDATE PERMISODET
			SET PED_ENUSO = 'N'
			FROM PERMISODET 
			WHERE PERMISODET.PED_SALDO = PERMISODET.PED_CANT AND PERMISODET.PED_ENUSO <> 'N' 
			AND PERMISODET.PED_INDICED NOT IN (SELECT PED_INDICED FROM indicedPer)
	
			UPDATE PERMISODET
			SET PED_ENUSOCOSTOT = 'N'
			FROM PERMISODET 
			WHERE PERMISODET.PED_SALDOCOSTOT = PERMISODET.PED_COSTOT AND PERMISODET.PED_ENUSO <> 'N' 
			AND PERMISODET.PED_INDICED NOT IN (SELECT PED_INDICED FROM indicedPer)



			-- los saldos totales en la caratula
			UPDATE dbo.PERMISO
			SET     dbo.PERMISO.PE_SALDO= round(dbo.VPERMISOSALDOTOT.KAR_SALDO,6),
			dbo.PERMISO.PE_SALDOCOSTOT= round(dbo.VPERMISOSALDOTOT.KAR_SALDOCOSTOT,6)
			FROM         dbo.PERMISO INNER JOIN
			                      dbo.VPERMISOSALDOTOT ON dbo.PERMISO.PE_CODIGO = dbo.VPERMISOSALDOTOT.PE_CODIGO 
			WHERE (round(dbo.PERMISO.PE_SALDO,6) <> round(dbo.VPERMISOSALDOTOT.KAR_SALDO,6)
			        or round(dbo.PERMISO.PE_SALDOCOSTOT,6) <> round(dbo.VPERMISOSALDOTOT.KAR_SALDOCOSTOT,6))
				and dbo.PERMISO.PE_CODIGO IN (SELECT PE_CODIGO FROM indicedPer)




			UPDATE PERMISO
			SET PE_ESTATUS='A'
			WHERE PE_SALDO >0	AND (PE_ESTATUS<>'A' OR PE_ESTATUS IS NULL)


			UPDATE PERMISO
			SET PE_ESTATUS='A'
			WHERE PE_SALDOCOSTOT >0	 AND (PE_ESTATUS<>'A' OR PE_ESTATUS IS NULL)
	
		end



		UPDATE PERMISODET
		SET     PERMISODET.PED_SALDO= PERMISODET.PED_CANT, PERMISODET.PED_SALDOCOSTOT= PERMISODET.PED_COSTOT
		FROM         PERMISO INNER JOIN
		                      PERMISODET ON PERMISO.PE_CODIGO = PERMISODET.PE_CODIGO LEFT OUTER JOIN
		                      CONFIGURAPERMISOREL ON PERMISO.IDE_CODIGO = CONFIGURAPERMISOREL.IDE_CODIGO
		WHERE     ((CONFIGURAPERMISOREL.CFR_SALDO = 'S') OR
		                      (CONFIGURAPERMISOREL.CFR_SALDOCARATULA = 'S'))
			AND PERMISODET.PED_INDICED NOT IN (SELECT PED_INDICED FROM indicedPer)



			UPDATE dbo.PERMISO
			SET     dbo.PERMISO.PE_SALDO= isnull((SELECT SUM(PED_CANT) FROM PERMISODET
							WHERE PERMISODET.PE_CODIGO=PERMISO.PE_CODIGO
							GROUP BY PE_CODIGO),0),
			dbo.PERMISO.PE_SALDOCOSTOT= isnull((SELECT     SUM(PED_COSTOT)
							FROM PERMISODET
							WHERE PERMISODET.PE_CODIGO=PERMISO.PE_CODIGO
							GROUP BY PE_CODIGO),0)
			WHERE dbo.PERMISO.PE_CODIGO NOT IN (SELECT PE_CODIGO FROM indicedPer)






	exec  sp_droptable 'indicedPer'




	update permisodet
	set ped_enuso='N'
	where ped_cant = ped_saldo
	
	
	update permisodet
	set ped_enusocostot='N'
	where ped_costot = ped_saldocostot






















GO
