SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[CopiaBom] (@BDOrigen varchar(50), @BDDestino varchar(50))    as


ALTER TABLE [BOM_STRUCT] DISABLE TRIGGER [INSERT_BOM_STRUCT]

exec('insert into BOM_STRUCT(BSU_SUBENSAMBLE, BST_HIJO, BST_INCORPOR, BST_DISCH, ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
                      BST_TRANS, BSU_NOPARTE, BST_NOPARTE, BSU_NOPARTEAUX, BST_NOPARTEAUX, 
                      BST_TIP_ENS, BST_SEC)

SELECT     MAESTRO_1.MA_CODIGO, MAESTRO_2.MA_CODIGO, BOM_STRUCTOrig.BST_INCORPOR, BOM_STRUCTOrig.BST_DISCH, 
                      BOM_STRUCTOrig.ME_CODIGO, BOM_STRUCTOrig.FACTCONV, BOM_STRUCTOrig.BST_PERINI, BOM_STRUCTOrig.BST_PERFIN, BOM_STRUCTOrig.ME_GEN, 
                      BOM_STRUCTOrig.BST_TRANS, BOM_STRUCTOrig.BSU_NOPARTE, 
                      BOM_STRUCTOrig.BST_NOPARTE, BOM_STRUCTOrig.BSU_NOPARTEAUX, BOM_STRUCTOrig.BST_NOPARTEAUX, 
                      BOM_STRUCTOrig.BST_TIP_ENS, BOM_STRUCTOrig.BST_SEC
FROM         MAESTRO MAESTRO_1 INNER JOIN '+@BDOrigen+'.DBO.BOM_STRUCT BOM_STRUCTOrig ON MAESTRO_1.MA_NOPARTE = BOM_STRUCTOrig.BSU_NOPARTE AND 
                      MAESTRO_1.MA_NOPARTEAUX = BOM_STRUCTOrig.BSU_NOPARTEAUX INNER JOIN
                      MAESTRO MAESTRO_2 ON BOM_STRUCTOrig.BST_NOPARTE = MAESTRO_2.MA_NOPARTE AND 
                      BOM_STRUCTOrig.BST_NOPARTEAUX = MAESTRO_2.MA_NOPARTEAUX
WHERE BOM_STRUCTOrig.BSU_NOPARTE+''&''+BOM_STRUCTOrig.BST_NOPARTE+CONVERT(VARCHAR(11),BOM_STRUCTOrig.BST_PERINI,101)
+CONVERT(VARCHAR(11),BOM_STRUCTOrig.BST_PERFIN,101) NOT IN
(SELECT B1.BSU_NOPARTE+''&''+B1.BST_NOPARTE+CONVERT(VARCHAR(11),B1.BST_PERINI,101)
+CONVERT(VARCHAR(11),B1.BST_PERFIN,101) FROM BOM_STRUCT B1)')


ALTER TABLE [BOM_STRUCT] ENABLE TRIGGER [INSERT_BOM_STRUCT]

GO
