SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_InsertaPckListIdentifica] (@fi_codigo int)   as


declare @FIID_CODIGO int, @FID_INDICED int, @IDE_CODIGO int, @IDED_CODIGO int, @MIID_DESC varchar(40), @MIID_DESC2 varchar(40), @IDED_CODIGO2 int

declare Cur_PckListIdentifica cursor for
SELECT     dbo.FACTIMPDET.FID_INDICED, dbo.MAESTROIDENTIFICA.IDE_CODIGO, dbo.MAESTROIDENTIFICA.IDED_CODIGO, dbo.MAESTROIDENTIFICA.MIID_DESC, 
                      dbo.MAESTROIDENTIFICA.MIID_DESC2, dbo.MAESTROIDENTIFICA.IDED_CODIGO2
FROM         dbo.MAESTROIDENTIFICA INNER JOIN
                      dbo.FACTIMPDET ON dbo.MAESTROIDENTIFICA.MA_CODIGO = dbo.FACTIMPDET.MA_CODIGO
WHERE     (dbo.MAESTROIDENTIFICA.MIID_MOVIMIENTO = 'E'  OR
           dbo.MAESTROIDENTIFICA.MIID_MOVIMIENTO = 'A') AND (dbo.FACTIMPDET.FI_CODIGO = @fi_codigo)
GROUP BY dbo.FACTIMPDET.FID_INDICED, dbo.MAESTROIDENTIFICA.IDE_CODIGO, dbo.MAESTROIDENTIFICA.IDED_CODIGO, dbo.MAESTROIDENTIFICA.MIID_DESC, 
                      dbo.MAESTROIDENTIFICA.MIID_DESC2, dbo.MAESTROIDENTIFICA.IDED_CODIGO2
 OPEN Cur_PckListIdentifica


	FETCH NEXT FROM Cur_PckListIdentifica INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @MIID_DESC, @MIID_DESC2, @IDED_CODIGO2

  WHILE (@@fetch_status = 0) 

  BEGIN  


	EXEC  SP_GETCONSECUTIVO 'FIID', @VALUE = @FIID_CODIGO OUTPUT


	if not exists(select * from factimpdetidentifica where fid_indiced=@FID_INDICED and ide_codigo=@IDE_CODIGO)
	insert into FACTIMPDETIDENTIFICA(FIID_CODIGO, FID_INDICED, IDE_CODIGO, IDED_CODIGO, FIID_DESC, FIID_DESC2, IDED_CODIGO2)
	values (@FIID_CODIGO, @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @MIID_DESC, @MIID_DESC2, @IDED_CODIGO2)



	FETCH NEXT FROM Cur_PckListIdentifica INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @MIID_DESC, @MIID_DESC2, @IDED_CODIGO2
END

	CLOSE Cur_PckListIdentifica
	DEALLOCATE Cur_PckListIdentifica


GO
