SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_CANCELARELFACTRANS]  (@pi_exportacion int)   as

SET NOCOUNT ON 
DECLARE @FED_SALDOTRANS decimal(38,6), @FED_CANT decimal(38,6), @RET_CANTDESC decimal(38,6), @FED_INDICED int

declare Cur_CancelPedimentoTrans cursor for
SELECT     TOP 100 PERCENT round(dbo.FACTEXPDET.FED_SALDOTRANS,6), round(dbo.FACTEXPDET.FED_CANT,6), 
                      round(dbo.PEDIMPRELTRANS.RET_CANTDESC,6), dbo.PEDIMPRELTRANS.FED_INDICED
FROM         dbo.FACTEXPDET INNER JOIN
                      dbo.PEDIMPRELTRANS ON dbo.FACTEXPDET.FED_INDICED = dbo.PEDIMPRELTRANS.FED_INDICED INNER JOIN
                      dbo.PEDIMPDET ON dbo.PEDIMPRELTRANS.PID_INDICED = dbo.PEDIMPDET.PID_INDICED
WHERE     (dbo.PEDIMPDET.PI_CODIGO = @pi_exportacion) AND dbo.PEDIMPRELTRANS.FED_INDICED<>0
ORDER BY dbo.PEDIMPRELTRANS.RET_CODIGO DESC

open Cur_CancelPedimentoTrans


	FETCH NEXT FROM Cur_CancelPedimentoTrans INTO @FED_SALDOTRANS, @FED_CANT, @RET_CANTDESC, @FED_INDICED

	WHILE (@@FETCH_STATUS = 0) 
	BEGIN


	UPDATE FACTEXPDET
	SET FED_SALDOTRANS=@FED_SALDOTRANS+@RET_CANTDESC
	WHERE FED_INDICED=@FED_INDICED

	UPDATE FACTEXPDET
	SET PID_INDICEDLIGA=-1
	WHERE FED_INDICED=@FED_INDICED
	
	if @FED_SALDOTRANS = @FED_CANT
	update FACTEXPDET
	set fed_usotrans='N'
	WHERE FED_INDICED=@FED_INDICED	

	FETCH NEXT FROM Cur_CancelPedimentoTrans INTO @FED_SALDOTRANS, @FED_CANT, @RET_CANTDESC, @FED_INDICED
	
	END
	
	CLOSE Cur_CancelPedimentoTrans
	DEALLOCATE Cur_CancelPedimentoTrans


	DELETE FROM PEDIMPRELTRANS
	WHERE PID_INDICED IN (SELECT PID_INDICED FROM PEDIMP WHERE PI_CODIGO=@pi_exportacion)


	UPDATE FACTEXP
	SET PI_TRANS=-1	
	WHERE PI_TRANS=@pi_exportacion

	UPDATE PEDIMP
	SET PI_ESTATUS='T'
	WHERE PI_CODIGO=@pi_exportacion

GO
