SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






































CREATE PROCEDURE [dbo].[SP_ACTUALIZAEQARAPCKLIST] (@PL_codigo int)   as

SET NOCOUNT ON 
		-- existe en equivalencias


		UPDATE PCKLISTDET
		SET ME_ARIMPMX=isnull((SELECT ME_CODIGO FROM ARANCEL WHERE AR_CODIGO=PCKLISTDET.AR_IMPMX),0)
		WHERE PL_CODIGO=@PL_codigo

		if exists (SELECT     dbo.PCKLISTDET.EQ_IMPMX
			FROM         dbo.EQUIVALE INNER JOIN
			                      dbo.PCKLISTDET ON dbo.EQUIVALE.ME_CODIGO2 = dbo.PCKLISTDET.ME_ARIMPMX AND 
			                      dbo.EQUIVALE.ME_CODIGO1 = dbo.PCKLISTDET.ME_CODIGO INNER JOIN
			                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO
				WHERE     (dbo.PCKLIST.PL_CODIGO=@PL_codigo))

			UPDATE dbo.PCKLISTDET
			SET dbo.PCKLISTDET.EQ_IMPMX=dbo.EQUIVALE.EQ_CANT
			FROM         dbo.EQUIVALE INNER JOIN
			                      dbo.PCKLISTDET ON dbo.EQUIVALE.ME_CODIGO2 = dbo.PCKLISTDET.ME_ARIMPMX AND 
			                      dbo.EQUIVALE.ME_CODIGO1 = dbo.PCKLISTDET.ME_CODIGO INNER JOIN
			                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO
				WHERE     (dbo.PCKLIST.PL_CODIGO=@PL_codigo)



		-- ME_ARIMPMX igual a Kg
		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_IMPMX = dbo.PCKLISTDET.PLD_PES_UNI
		FROM  dbo.PCKLISTDET INNER JOIN
                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO
		WHERE (dbo.PCKLIST.PL_CODIGO=@PL_codigo)
			AND dbo.PCKLISTDET.PLD_PES_UNI>0 AND dbo.PCKLISTDET.ME_ARIMPMX in (select ME_KILOGRAMOS from configuracion) 

		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_IMPMX = 1
		FROM  dbo.PCKLISTDET INNER JOIN
                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO
		WHERE (dbo.PCKLIST.PL_CODIGO=@PL_codigo)
			AND (dbo.PCKLISTDET.PLD_PES_UNI is null or  dbo.PCKLISTDET.PLD_PES_UNI=0) 
			AND dbo.PCKLISTDET.ME_ARIMPMX in (select ME_KILOGRAMOS from configuracion) 
			AND dbo.PCKLISTDET.ME_CODIGO not in (SELECT ME_CODIGO1 FROM EQUIVALE
			WHERE     ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))


		-- en base a maestromedida
		UPDATE dbo.PCKLISTDET
		SET     dbo.PCKLISTDET.EQ_IMPMX= dbo.MAESTROMEDIDA.EQ_CANTIDAD
		FROM         dbo.MAESTRO MAESTRO_1 INNER JOIN
	                      dbo.MAESTRO ON MAESTRO_1.MA_CODIGO = dbo.MAESTRO.MA_GENERICO INNER JOIN
	                      dbo.PCKLISTDET INNER JOIN
	                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN
	                      dbo.MAESTROMEDIDA ON dbo.PCKLISTDET.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
	                      dbo.PCKLISTDET.ME_CODIGO = dbo.MAESTROMEDIDA.ME_CODIGO ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
	                      MAESTRO_1.ME_COM = dbo.PCKLISTDET.ME_ARIMPMX
		WHERE (dbo.PCKLIST.PL_CODIGO=@PL_codigo)

		-- sin factor de conversion
		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_IMPMX = 1
		WHERE (dbo.PCKLISTDET.EQ_IMPMX=0 OR dbo.PCKLISTDET.EQ_IMPMX IS NULL)
		AND (dbo.PCKLISTDET.PL_CODIGO=@PL_codigo)

		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_IMPMX = 1
		WHERE (dbo.PCKLISTDET.EQ_IMPMX<>1 )
		AND dbo.PCKLISTDET.ME_ARIMPMX=dbo.PCKLISTDET.ME_CODIGO
		AND (dbo.PCKLISTDET.PL_CODIGO=@PL_codigo)

/* =========================================================== EQ_EXPFO =====================================================*/
		-- existe en equivalencias
		if exists (SELECT     dbo.PCKLISTDET.EQ_EXPFO
				FROM         dbo.EQUIVALE INNER JOIN
				                      dbo.PCKLISTDET ON dbo.EQUIVALE.ME_CODIGO1 = dbo.PCKLISTDET.ME_CODIGO INNER JOIN
				                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN
				                      dbo.ARANCEL ON dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO AND dbo.EQUIVALE.ME_CODIGO2 = dbo.ARANCEL.ME_CODIGO
				WHERE     (dbo.PCKLIST.PL_CODIGO=@PL_codigo))


			UPDATE dbo.PCKLISTDET
			SET dbo.PCKLISTDET.EQ_EXPFO=dbo.EQUIVALE.EQ_CANT
				FROM         dbo.EQUIVALE INNER JOIN
				                      dbo.PCKLISTDET ON dbo.EQUIVALE.ME_CODIGO1 = dbo.PCKLISTDET.ME_CODIGO INNER JOIN
				                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN
				                      dbo.ARANCEL ON dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO AND dbo.EQUIVALE.ME_CODIGO2 = dbo.ARANCEL.ME_CODIGO
				WHERE     (dbo.PCKLIST.PL_CODIGO=@PL_codigo)



		-- ME_ARIMPMX igual a Kg
		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_EXPFO = dbo.PCKLISTDET.PLD_PES_UNI
		FROM  dbo.PCKLISTDET INNER JOIN
                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN ARANCEL ON
		      dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO 			
		WHERE (dbo.PCKLIST.PL_CODIGO=@PL_codigo)
			AND dbo.PCKLISTDET.PLD_PES_UNI>0 AND dbo.ARANCEL.ME_CODIGO in (select ME_KILOGRAMOS from configuracion) 

		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_EXPFO = 1
		FROM  dbo.PCKLISTDET INNER JOIN
                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN ARANCEL ON
		      dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO 			
		WHERE (dbo.PCKLIST.PL_CODIGO=@PL_codigo)
			AND (dbo.PCKLISTDET.PLD_PES_UNI is null or  dbo.PCKLISTDET.PLD_PES_UNI=0) 
			AND dbo.ARANCEL.ME_CODIGO in (select ME_KILOGRAMOS from configuracion) 
			AND dbo.PCKLISTDET.ME_CODIGO not in (SELECT ME_CODIGO1 FROM EQUIVALE
			WHERE     ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))


		-- en base a maestromedida
		UPDATE dbo.PCKLISTDET
		SET     dbo.PCKLISTDET.EQ_EXPFO= dbo.MAESTROMEDIDA.EQ_CANTIDAD
		FROM         dbo.MAESTRO MAESTRO_1 INNER JOIN
	                      dbo.MAESTRO ON MAESTRO_1.MA_CODIGO = dbo.MAESTRO.MA_GENERICO INNER JOIN
	                      dbo.PCKLISTDET INNER JOIN
	                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN
	                      dbo.MAESTROMEDIDA ON dbo.PCKLISTDET.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
	                      dbo.PCKLISTDET.ME_CODIGO = dbo.MAESTROMEDIDA.ME_CODIGO ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO INNER JOIN
	                      dbo.ARANCEL ON dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO AND MAESTRO_1.ME_COM = dbo.ARANCEL.ME_CODIGO
		WHERE (dbo.PCKLIST.PL_CODIGO=@PL_codigo)


	
		-- sin factor de conversion
		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_EXPFO = 1
		WHERE (dbo.PCKLISTDET.EQ_EXPFO=0 OR dbo.PCKLISTDET.EQ_EXPFO IS NULL)
		AND (dbo.PCKLISTDET.PL_CODIGO=@PL_codigo)

		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_EXPFO = 1
		FROM dbo.PCKLISTDET INNER JOIN
	                      dbo.ARANCEL ON dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO 
		WHERE (dbo.PCKLISTDET.EQ_EXPFO<>1 )
		AND dbo.ARANCEL.ME_CODIGO=dbo.PCKLISTDET.ME_CODIGO
		AND (dbo.PCKLISTDET.PL_CODIGO=@PL_codigo)




































GO
