SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CALCULACOSTOLISTA]  (@fed_indiced int)   as

SET NOCOUNT ON 
declare @FED_GRA_MP decimal(38,6), @FED_GRA_EMP decimal(38,6), @FED_NG_MP decimal(38,6), @FED_NG_EMP decimal(38,6), @FED_NG_USA decimal(38,6), @MA_CODIGO INT, @COSTOORIG decimal(38,6),
@FE_CODIGO INT, @fe_fecha datetime, @FED_RETRABAJO CHAR(1)

	SELECT @MA_CODIGO=MA_CODIGO, @FE_CODIGO=FE_CODIGO, @FED_RETRABAJO=FED_RETRABAJO  FROM FACTEXPDET WHERE FED_INDICED=@fed_indiced


	select @fe_fecha=fe_fecha from factexp where fe_codigo=@FE_CODIGO
-- materia prima no gravable
	SELECT     @FED_NG_MP= SUM(MA_COSTO)
	FROM         dbo.VCOSTORETRA
	WHERE     (FETR_INDICED = @fed_indiced) AND (CFT_TIPO <> 'E' and CFT_TIPO <> 'S' and CFT_TIPO <> 'P') AND (MA_SERVICIO = 'S' OR
	                      (MA_DEF_TIP = 'P' AND (PA_ORIGEN IN (SELECT CF_PAIS_MX FROM dbo.CONFIGURACION)
				OR PA_ORIGEN IN (SELECT CF_PAIS_CA FROM dbo.CONFIGURACION) OR
				PA_ORIGEN IN (SELECT CF_PAIS_USA FROM dbo.CONFIGURACION)) AND FETR_NAFTA='S'))

	-- costo de producto terminado cuando entro (debe ser parte del costo no gravable)
	if @FED_RETRABAJO='R'
		SELECT @COSTOORIG= PID_COS_UNI
		FROM PEDIMPDET LEFT OUTER JOIN 
		VPEDIMP ON PEDIMPDET.PI_CODIGO=VPEDIMP.PI_CODIGO 
		WHERE PI_ESTATUS<>'R' AND PID_INDICED IN
			(SELECT PID_INDICED FROM PIDESCARGA WHERE PID_SALDOGEN>0)
			AND MA_CODIGO=@MA_CODIGO AND PI_FEC_ENT IN
			(SELECT MAX(PI_FEC_ENT)
			FROM PEDIMPDET LEFT OUTER JOIN 
			VPEDIMP ON PEDIMPDET.PI_CODIGO=VPEDIMP.PI_CODIGO 
			WHERE PI_ESTATUS<>'R' AND MA_CODIGO=@MA_CODIGO and VPEDIMP.PI_FEC_ENT <= @fe_fecha
			AND PID_INDICED IN (SELECT PID_INDICED FROM PIDESCARGA WHERE PID_SALDOGEN>0))
	ELSE
		SET @COSTOORIG=0

	SET @FED_NG_MP=isnull(@FED_NG_MP,0) + isnull(@COSTOORIG,0)

-- materia prima gravable
	SELECT     @FED_GRA_MP=SUM(MA_COSTO)
	FROM         dbo.VCOSTORETRA
	WHERE     (FETR_INDICED = @fed_indiced) AND (CFT_TIPO <> 'E' and CFT_TIPO <> 'S' and CFT_TIPO <> 'P') AND (MA_SERVICIO = 'N') AND
	                      ((MA_DEF_TIP <> 'P') OR ((PA_ORIGEN NOT IN (SELECT CF_PAIS_MX FROM dbo.CONFIGURACION)
				AND PA_ORIGEN NOT IN (SELECT CF_PAIS_CA FROM dbo.CONFIGURACION) AND
				PA_ORIGEN NOT IN (SELECT CF_PAIS_USA FROM dbo.CONFIGURACION)) OR FETR_NAFTA<>'S'))

-- empaque no gravable
	SELECT     @FED_NG_EMP=SUM(MA_COSTO)
	FROM         dbo.VCOSTORETRA
	WHERE     (FETR_INDICED = @fed_indiced) AND (CFT_TIPO = 'E') AND (MA_SERVICIO = 'S' OR
	                      (MA_DEF_TIP = 'P' AND (PA_ORIGEN IN (SELECT CF_PAIS_MX FROM dbo.CONFIGURACION)
				OR PA_ORIGEN IN (SELECT CF_PAIS_CA FROM dbo.CONFIGURACION) OR
				PA_ORIGEN IN (SELECT CF_PAIS_USA FROM dbo.CONFIGURACION)) AND FETR_NAFTA='S' ))

-- empaque gravable
	SELECT     @FED_GRA_EMP=SUM(MA_COSTO)
	FROM         dbo.VCOSTORETRA
	WHERE     (FETR_INDICED = @fed_indiced) AND (CFT_TIPO = 'E') AND (MA_SERVICIO = 'N') AND
	                      ((MA_DEF_TIP <> 'P') OR ((PA_ORIGEN NOT IN (SELECT CF_PAIS_MX FROM dbo.CONFIGURACION)
				AND PA_ORIGEN NOT IN (SELECT CF_PAIS_CA FROM dbo.CONFIGURACION) AND
				PA_ORIGEN NOT IN (SELECT CF_PAIS_USA FROM dbo.CONFIGURACION)) OR FETR_NAFTA<>'S'))

-- materia prima no gravable USA
	SELECT     @FED_NG_USA=SUM(MA_COSTO)
	FROM         dbo.VCOSTORETRA
	WHERE     (FETR_INDICED = @fed_indiced) AND (CFT_TIPO <> 'E' and CFT_TIPO <> 'S' and CFT_TIPO <> 'P') AND (MA_SERVICIO = 'S' OR
	                      (MA_DEF_TIP = 'P' AND (PA_ORIGEN IN (SELECT CF_PAIS_MX FROM dbo.CONFIGURACION)
				OR PA_ORIGEN IN (SELECT CF_PAIS_CA FROM dbo.CONFIGURACION)) AND FETR_NAFTA='S' ))

	
	UPDATE FACTEXPDET
	SET     FED_GRA_MP=	isnull(@FED_GRA_MP,0), FED_GRA_EMP=isnull(@FED_GRA_EMP,0), FED_NG_MP=isnull(@FED_NG_MP,0), 
		FED_NG_EMP=isnull(@FED_NG_EMP,0), FED_NG_USA=isnull(@FED_NG_USA,0)
	WHERE FED_INDICED=@fed_indiced AND FED_RETRABAJO='D'

	UPDATE FACTEXPDET
	SET     FED_GRA_MP=	isnull(@FED_GRA_MP,0)/FED_CANT, FED_GRA_EMP=isnull(@FED_GRA_EMP,0)/FED_CANT, FED_NG_MP=isnull(@FED_NG_MP,0)/FED_CANT, 
		FED_NG_EMP=isnull(@FED_NG_EMP,0)/FED_CANT, FED_NG_USA=isnull(@FED_NG_USA,0)/FED_CANT
	WHERE FED_INDICED=@fed_indiced AND FED_RETRABAJO<>'D'


	UPDATE FACTEXPDET
	SET FED_COS_UNI=isnull(FED_GRA_MP,0) + isnull(FED_GRA_EMP,0) + isnull(FED_GRA_ADD,0) + isnull(FED_GRA_MO,0) + isnull(FED_GRA_GI_MX,0) +isnull(FED_NG_MP,0) + isnull(FED_NG_EMP,0) + isnull(FED_NG_ADD,0) --+isnull(FED_GRA_GI,0)	
	WHERE FED_INDICED=@fed_indiced AND FED_RETRABAJO<>'D'	

	UPDATE FACTEXPDET
	set FED_COS_TOT = FED_COS_UNI * fed_cant
	from factexpdet where FED_indiced =@fed_indiced 
	and FED_COS_TOT <> (FED_COS_UNI * fed_cant)

GO
