SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_ACTUALIZAINFOANEXAFACTALL]   as

SET NOCOUNT ON 

		-- R1 de entrada
			UPDATE dbo.FACTIMPDET
			SET     dbo.FACTIMPDET.MA_GENERICO= isnull(dbo.PEDIMPDET.MA_GENERICO,0),
			--dbo.FACTIMPDET.EQ_GEN = isnull(dbo.PEDIMPDET.EQ_GENERICO,1),
			--dbo.FACTIMPDET.EQ_IMPMX = isnull(dbo.PEDIMPDET.EQ_IMPMX,1),
			dbo.FACTIMPDET.AR_IMPMX = isnull(dbo.PEDIMPDET.AR_IMPMX,0),
			dbo.FACTIMPDET.AR_EXPFO = isnull(dbo.PEDIMPDET.AR_EXPFO,0),
			dbo.FACTIMPDET.FID_RATEEXPFO = isnull(dbo.PEDIMPDET.PID_RATEEXPFO,-1),
			dbo.FACTIMPDET.FID_SEC_IMP= isnull(dbo.PEDIMPDET.PID_SEC_IMP,0),
			dbo.FACTIMPDET.FID_DEF_TIP = isnull(dbo.PEDIMPDET.PID_DEF_TIP,'G'),
			dbo.FACTIMPDET.FID_POR_DEF = isnull(dbo.PEDIMPDET.PID_POR_DEF,-1),
			dbo.FACTIMPDET.TI_CODIGO = isnull(dbo.PEDIMPDET.TI_CODIGO,0),
			dbo.FACTIMPDET.PA_CODIGO = isnull(dbo.PEDIMPDET.PA_ORIGEN,0),
			dbo.FACTIMPDET.SPI_CODIGO = isnull(dbo.PEDIMPDET.SPI_CODIGO,0),
			dbo.FACTIMPDET.ME_GEN = isnull(dbo.PEDIMPDET.ME_GENERICO,0),
			dbo.FACTIMPDET.ME_ARIMPMX = isnull(dbo.PEDIMPDET.ME_ARIMPMX,0),
			dbo.FACTIMPDET.PR_CODIGO = isnull(dbo.PEDIMPDET.PR_CODIGO,0),
			dbo.FACTIMPDET.CS_CODIGO = isnull(dbo.PEDIMPDET.CS_CODIGO,0),
			dbo.FACTIMPDET.FID_NOMBRE = isnull(dbo.PEDIMPDET.PID_NOMBRE,0)
			FROM         dbo.PEDIMPDET LEFT OUTER JOIN
			                      dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGAR1 
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO='E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE' AND ISNULL(PICF_PEDIMPSINAGRUP,'N')<>'S'




			/*UPDATE dbo.FACTIMPDET
			SET     dbo.FACTIMPDET.EQ_GEN = ROUND(dbo.FACTIMPDET.FID_PES_UNI,6)
			FROM         dbo.PEDIMPDET LEFT OUTER JOIN
			                      dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGAR1 
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO='E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE' AND
			dbo.FACTIMPDET.ME_GEN IN (select ME_KILOGRAMOS from configuracion) and ROUND(dbo.FACTIMPDET.FID_PES_UNI,6) > 0
			 AND ISNULL(PICF_PEDIMPSINAGRUP,'N')<>'S'

			UPDATE dbo.FACTIMPDET
			SET     dbo.FACTIMPDET.EQ_IMPMX =	dbo.FACTIMPDET.EQ_GEN
			FROM         dbo.PEDIMPDET LEFT OUTER JOIN
			                      dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGAR1 
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO='E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE' AND
			dbo.FACTIMPDET.ME_ARIMPMX=dbo.FACTIMPDET.ME_GEN
			 AND ISNULL(PICF_PEDIMPSINAGRUP,'N')<>'S'*/


			UPDATE dbo.FACTIMPDET
			SET     dbo.FACTIMPDET.MA_GENERICO= isnull(dbo.PEDIMPDET.MA_GENERICO,0),
			dbo.FACTIMPDET.EQ_GEN = isnull(dbo.PEDIMPDET.EQ_GENERICO,1),
			dbo.FACTIMPDET.EQ_IMPMX = isnull(dbo.PEDIMPDET.EQ_IMPMX,1),
			dbo.FACTIMPDET.AR_IMPMX = isnull(dbo.PEDIMPDET.AR_IMPMX,0),
			dbo.FACTIMPDET.AR_EXPFO = isnull(dbo.PEDIMPDET.AR_EXPFO,0),
			dbo.FACTIMPDET.FID_RATEEXPFO = isnull(dbo.PEDIMPDET.PID_RATEEXPFO,-1),
			dbo.FACTIMPDET.FID_SEC_IMP= isnull(dbo.PEDIMPDET.PID_SEC_IMP,0),
			dbo.FACTIMPDET.FID_DEF_TIP = isnull(dbo.PEDIMPDET.PID_DEF_TIP,'G'),
			dbo.FACTIMPDET.FID_POR_DEF = isnull(dbo.PEDIMPDET.PID_POR_DEF,-1),
			dbo.FACTIMPDET.TI_CODIGO = isnull(dbo.PEDIMPDET.TI_CODIGO,0),
			dbo.FACTIMPDET.PA_CODIGO = isnull(dbo.PEDIMPDET.PA_ORIGEN,0),
			dbo.FACTIMPDET.SPI_CODIGO = isnull(dbo.PEDIMPDET.SPI_CODIGO,0),
			dbo.FACTIMPDET.ME_GEN = isnull(dbo.PEDIMPDET.ME_GENERICO,0),
			dbo.FACTIMPDET.ME_ARIMPMX = isnull(dbo.PEDIMPDET.ME_ARIMPMX,0),
			dbo.FACTIMPDET.PR_CODIGO = isnull(dbo.PEDIMPDET.PR_CODIGO,0),
			dbo.FACTIMPDET.CS_CODIGO = isnull(dbo.PEDIMPDET.CS_CODIGO,0),
			dbo.FACTIMPDET.FID_NOMBRE = isnull(dbo.PEDIMPDET.PID_NOMBRE,0)
			FROM         dbo.PEDIMPDET LEFT OUTER JOIN
			                      dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGAR1 
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO='E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE' AND ISNULL(PICF_PEDIMPSINAGRUP,'N')='S'

		-- <>R1 de entrada

			UPDATE dbo.FACTIMPDET
			SET     dbo.FACTIMPDET.MA_GENERICO= isnull(dbo.PEDIMPDET.MA_GENERICO,0),
			--dbo.FACTIMPDET.EQ_GEN = isnull(dbo.PEDIMPDET.EQ_GENERICO,1),
			--dbo.FACTIMPDET.EQ_IMPMX = isnull(dbo.PEDIMPDET.EQ_IMPMX,1),
			dbo.FACTIMPDET.AR_IMPMX = isnull(dbo.PEDIMPDET.AR_IMPMX,0),
			dbo.FACTIMPDET.AR_EXPFO = isnull(dbo.PEDIMPDET.AR_EXPFO,0),
			dbo.FACTIMPDET.FID_RATEEXPFO = isnull(dbo.PEDIMPDET.PID_RATEEXPFO,-1),
			dbo.FACTIMPDET.FID_SEC_IMP= isnull(dbo.PEDIMPDET.PID_SEC_IMP,0),
			dbo.FACTIMPDET.FID_DEF_TIP = isnull(dbo.PEDIMPDET.PID_DEF_TIP,'G'),
			dbo.FACTIMPDET.FID_POR_DEF = isnull(dbo.PEDIMPDET.PID_POR_DEF,-1),
			dbo.FACTIMPDET.TI_CODIGO = isnull(dbo.PEDIMPDET.TI_CODIGO,0),
			dbo.FACTIMPDET.PA_CODIGO = isnull(dbo.PEDIMPDET.PA_ORIGEN,0),
			dbo.FACTIMPDET.SPI_CODIGO = isnull(dbo.PEDIMPDET.SPI_CODIGO,0),
			dbo.FACTIMPDET.ME_GEN = isnull(dbo.PEDIMPDET.ME_GENERICO,0),
			dbo.FACTIMPDET.ME_ARIMPMX = isnull(dbo.PEDIMPDET.ME_ARIMPMX,0),
			dbo.FACTIMPDET.PR_CODIGO = isnull(dbo.PEDIMPDET.PR_CODIGO,0),
			dbo.FACTIMPDET.CS_CODIGO = isnull(dbo.PEDIMPDET.CS_CODIGO,0),
			dbo.FACTIMPDET.FID_NOMBRE = isnull(dbo.PEDIMPDET.PID_NOMBRE,0)
			FROM     dbo.PEDIMPDET LEFT OUTER JOIN
			               dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGA
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO='E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE' AND dbo.CONFIGURACLAVEPED.CCP_TIPO<>'CN'
			 AND ISNULL(PICF_PEDIMPSINAGRUP,'N')<>'S'


			/*UPDATE dbo.FACTIMPDET
			SET     dbo.FACTIMPDET.EQ_GEN = ROUND(dbo.FACTIMPDET.FID_PES_UNI,6)
			FROM     dbo.PEDIMPDET LEFT OUTER JOIN
			               dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGA
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO='E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE' AND dbo.CONFIGURACLAVEPED.CCP_TIPO<>'CN' AND
			dbo.FACTIMPDET.ME_GEN IN (select ME_KILOGRAMOS from configuracion) and ROUND(dbo.FACTIMPDET.FID_PES_UNI,6) > 0
			 AND ISNULL(PICF_PEDIMPSINAGRUP,'N')<>'S'

			UPDATE dbo.FACTIMPDET
			SET     dbo.FACTIMPDET.EQ_IMPMX =	dbo.FACTIMPDET.EQ_GEN
			FROM     dbo.PEDIMPDET LEFT OUTER JOIN
			               dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGA
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO='E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE' AND dbo.CONFIGURACLAVEPED.CCP_TIPO<>'CN' AND
			dbo.FACTIMPDET.ME_ARIMPMX=dbo.FACTIMPDET.ME_GEN
			 AND ISNULL(PICF_PEDIMPSINAGRUP,'N')<>'S'*/




			UPDATE dbo.FACTIMPDET
			SET     dbo.FACTIMPDET.MA_GENERICO= isnull(dbo.PEDIMPDET.MA_GENERICO,0),
			dbo.FACTIMPDET.EQ_GEN = isnull(dbo.PEDIMPDET.EQ_GENERICO,1),
			dbo.FACTIMPDET.EQ_IMPMX = isnull(dbo.PEDIMPDET.EQ_IMPMX,1),
			dbo.FACTIMPDET.AR_IMPMX = isnull(dbo.PEDIMPDET.AR_IMPMX,0),
			dbo.FACTIMPDET.AR_EXPFO = isnull(dbo.PEDIMPDET.AR_EXPFO,0),
			dbo.FACTIMPDET.FID_RATEEXPFO = isnull(dbo.PEDIMPDET.PID_RATEEXPFO,-1),
			dbo.FACTIMPDET.FID_SEC_IMP= isnull(dbo.PEDIMPDET.PID_SEC_IMP,0),
			dbo.FACTIMPDET.FID_DEF_TIP = isnull(dbo.PEDIMPDET.PID_DEF_TIP,'G'),
			dbo.FACTIMPDET.FID_POR_DEF = isnull(dbo.PEDIMPDET.PID_POR_DEF,-1),
			dbo.FACTIMPDET.TI_CODIGO = isnull(dbo.PEDIMPDET.TI_CODIGO,0),
			dbo.FACTIMPDET.PA_CODIGO = isnull(dbo.PEDIMPDET.PA_ORIGEN,0),
			dbo.FACTIMPDET.SPI_CODIGO = isnull(dbo.PEDIMPDET.SPI_CODIGO,0),
			dbo.FACTIMPDET.ME_GEN = isnull(dbo.PEDIMPDET.ME_GENERICO,0),
			dbo.FACTIMPDET.ME_ARIMPMX = isnull(dbo.PEDIMPDET.ME_ARIMPMX,0),
			dbo.FACTIMPDET.PR_CODIGO = isnull(dbo.PEDIMPDET.PR_CODIGO,0),
			dbo.FACTIMPDET.CS_CODIGO = isnull(dbo.PEDIMPDET.CS_CODIGO,0),
			dbo.FACTIMPDET.FID_NOMBRE = isnull(dbo.PEDIMPDET.PID_NOMBRE,0)
			FROM     dbo.PEDIMPDET LEFT OUTER JOIN
			               dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGA
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO='E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE' AND dbo.CONFIGURACLAVEPED.CCP_TIPO<>'CN'
			 AND ISNULL(PICF_PEDIMPSINAGRUP,'N')='S'


		-- R1 de salida

			UPDATE dbo.FACTEXPDET
			SET     dbo.FACTEXPDET.MA_GENERICO= isnull(dbo.PEDIMPDET.MA_GENERICO,0),
			--dbo.FACTEXPDET.EQ_GEN = isnull(dbo.PEDIMPDET.EQ_GENERICO,1),
			--dbo.FACTEXPDET.EQ_EXPMX = isnull(dbo.PEDIMPDET.EQ_IMPMX,1),
			dbo.FACTEXPDET.AR_EXPMX = isnull(dbo.PEDIMPDET.AR_IMPMX,0),
			dbo.FACTEXPDET.AR_IMPFO = isnull(dbo.PEDIMPDET.AR_EXPFO,0),
			dbo.FACTEXPDET.FED_RATEIMPFO = isnull(dbo.PEDIMPDET.PID_RATEEXPFO,-1),
			dbo.FACTEXPDET.FED_RATEEXPMX = isnull(dbo.PEDIMPDET.PID_POR_DEF,-1),
			dbo.FACTEXPDET.TI_CODIGO = isnull(dbo.PEDIMPDET.TI_CODIGO,0),
			dbo.FACTEXPDET.SPI_CODIGO = isnull(dbo.PEDIMPDET.SPI_CODIGO,0),
			dbo.FACTEXPDET.ME_GENERICO = isnull(dbo.PEDIMPDET.ME_GENERICO,0),
			dbo.FACTEXPDET.ME_AREXPMX = isnull(dbo.PEDIMPDET.ME_ARIMPMX,0),
			dbo.FACTEXPDET.CS_CODIGO = isnull(dbo.PEDIMPDET.CS_CODIGO,0),
			dbo.FACTEXPDET.SE_CODIGO = isnull(dbo.PEDIMPDET.SE_CODIGO,0),
			dbo.FACTEXPDET.FED_DESTNAFTA = isnull(dbo.PEDIMPDET.PID_REGIONFIN,0),
			dbo.FACTEXPDET.FED_NOMBRE = isnull(dbo.PEDIMPDET.PID_NOMBRE,0)
			FROM         dbo.PEDIMPDET LEFT OUTER JOIN
			                      dbo.FACTEXPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTEXPDET.PID_INDICEDLIGAR1
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO<>'E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO='RE' AND ISNULL(PICF_PEDIMPSINAGRUP,'N')<>'S'



			UPDATE dbo.FACTEXPDET
			SET     dbo.FACTEXPDET.MA_GENERICO= isnull(dbo.PEDIMPDET.MA_GENERICO,0),
			dbo.FACTEXPDET.EQ_GEN = isnull(dbo.PEDIMPDET.EQ_GENERICO,1),
			dbo.FACTEXPDET.EQ_EXPMX = isnull(dbo.PEDIMPDET.EQ_IMPMX,1),
			dbo.FACTEXPDET.AR_EXPMX = isnull(dbo.PEDIMPDET.AR_IMPMX,0),
			dbo.FACTEXPDET.AR_IMPFO = isnull(dbo.PEDIMPDET.AR_EXPFO,0),
			dbo.FACTEXPDET.FED_RATEIMPFO = isnull(dbo.PEDIMPDET.PID_RATEEXPFO,-1),
			dbo.FACTEXPDET.FED_RATEEXPMX = isnull(dbo.PEDIMPDET.PID_POR_DEF,-1),
			dbo.FACTEXPDET.TI_CODIGO = isnull(dbo.PEDIMPDET.TI_CODIGO,0),
			dbo.FACTEXPDET.SPI_CODIGO = isnull(dbo.PEDIMPDET.SPI_CODIGO,0),
			dbo.FACTEXPDET.ME_GENERICO = isnull(dbo.PEDIMPDET.ME_GENERICO,0),
			dbo.FACTEXPDET.ME_AREXPMX = isnull(dbo.PEDIMPDET.ME_ARIMPMX,0),
			dbo.FACTEXPDET.CS_CODIGO = isnull(dbo.PEDIMPDET.CS_CODIGO,0),
			dbo.FACTEXPDET.SE_CODIGO = isnull(dbo.PEDIMPDET.SE_CODIGO,0),
			dbo.FACTEXPDET.FED_DESTNAFTA = isnull(dbo.PEDIMPDET.PID_REGIONFIN,0),
			dbo.FACTEXPDET.FED_NOMBRE = isnull(dbo.PEDIMPDET.PID_NOMBRE,0)
			FROM         dbo.PEDIMPDET LEFT OUTER JOIN
			                      dbo.FACTEXPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTEXPDET.PID_INDICEDLIGAR1
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO<>'E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO='RE' AND ISNULL(PICF_PEDIMPSINAGRUP,'N')='S'


		-- <>R1 de salida

			UPDATE dbo.FACTEXPDET
			SET     dbo.FACTEXPDET.MA_GENERICO= isnull(dbo.PEDIMPDET.MA_GENERICO,0),
			--dbo.FACTEXPDET.EQ_GEN = isnull(dbo.PEDIMPDET.EQ_GENERICO,1),
			--dbo.FACTEXPDET.EQ_EXPMX = isnull(dbo.PEDIMPDET.EQ_IMPMX,1),
			dbo.FACTEXPDET.AR_EXPMX = isnull(dbo.PEDIMPDET.AR_IMPMX,0),
			dbo.FACTEXPDET.AR_IMPFO = isnull(dbo.PEDIMPDET.AR_EXPFO,0),
			dbo.FACTEXPDET.FED_RATEIMPFO = isnull(dbo.PEDIMPDET.PID_RATEEXPFO,-1),
			dbo.FACTEXPDET.FED_RATEEXPMX = isnull(dbo.PEDIMPDET.PID_POR_DEF,-1),
			dbo.FACTEXPDET.TI_CODIGO = isnull(dbo.PEDIMPDET.TI_CODIGO,0),
			dbo.FACTEXPDET.SPI_CODIGO = isnull(dbo.PEDIMPDET.SPI_CODIGO,0),
			dbo.FACTEXPDET.ME_GENERICO = isnull(dbo.PEDIMPDET.ME_GENERICO,0),
			dbo.FACTEXPDET.ME_AREXPMX = isnull(dbo.PEDIMPDET.ME_ARIMPMX,0),
			dbo.FACTEXPDET.CS_CODIGO = isnull(dbo.PEDIMPDET.CS_CODIGO,0),
			dbo.FACTEXPDET.SE_CODIGO = isnull(dbo.PEDIMPDET.SE_CODIGO,0),
			dbo.FACTEXPDET.FED_DESTNAFTA = isnull(dbo.PEDIMPDET.PID_REGIONFIN,0),
			dbo.FACTEXPDET.FED_NOMBRE = isnull(dbo.PEDIMPDET.PID_NOMBRE,0)
			FROM         dbo.PEDIMPDET LEFT OUTER JOIN
			                      dbo.FACTEXPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTEXPDET.PID_INDICEDLIGA
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO<>'E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE'  AND dbo.CONFIGURACLAVEPED.CCP_TIPO<>'CN' AND ISNULL(PICF_PEDIMPSINAGRUP,'N')<>'S'




			UPDATE dbo.FACTEXPDET
			SET     dbo.FACTEXPDET.MA_GENERICO= isnull(dbo.PEDIMPDET.MA_GENERICO,0),
			dbo.FACTEXPDET.EQ_GEN = isnull(dbo.PEDIMPDET.EQ_GENERICO,1),
			dbo.FACTEXPDET.EQ_EXPMX = isnull(dbo.PEDIMPDET.EQ_IMPMX,1),
			dbo.FACTEXPDET.AR_EXPMX = isnull(dbo.PEDIMPDET.AR_IMPMX,0),
			dbo.FACTEXPDET.AR_IMPFO = isnull(dbo.PEDIMPDET.AR_EXPFO,0),
			dbo.FACTEXPDET.FED_RATEIMPFO = isnull(dbo.PEDIMPDET.PID_RATEEXPFO,-1),
			dbo.FACTEXPDET.FED_RATEEXPMX = isnull(dbo.PEDIMPDET.PID_POR_DEF,-1),
			dbo.FACTEXPDET.TI_CODIGO = isnull(dbo.PEDIMPDET.TI_CODIGO,0),
			dbo.FACTEXPDET.SPI_CODIGO = isnull(dbo.PEDIMPDET.SPI_CODIGO,0),
			dbo.FACTEXPDET.ME_GENERICO = isnull(dbo.PEDIMPDET.ME_GENERICO,0),
			dbo.FACTEXPDET.ME_AREXPMX = isnull(dbo.PEDIMPDET.ME_ARIMPMX,0),
			dbo.FACTEXPDET.CS_CODIGO = isnull(dbo.PEDIMPDET.CS_CODIGO,0),
			dbo.FACTEXPDET.SE_CODIGO = isnull(dbo.PEDIMPDET.SE_CODIGO,0),
			dbo.FACTEXPDET.FED_DESTNAFTA = isnull(dbo.PEDIMPDET.PID_REGIONFIN,0),
			dbo.FACTEXPDET.FED_NOMBRE = isnull(dbo.PEDIMPDET.PID_NOMBRE,0)
			FROM         dbo.PEDIMPDET LEFT OUTER JOIN
			                      dbo.FACTEXPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTEXPDET.PID_INDICEDLIGA
				LEFT OUTER JOIN dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO 
				LEFT OUTER JOIN dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO		
				LEFT OUTER JOIN dbo.PEDIMPSAAICONFIG ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPSAAICONFIG.PI_CODIGO		
			WHERE dbo.PEDIMP.PI_TIPO='C' AND dbo.PEDIMP.PI_MOVIMIENTO<>'E' AND dbo.PEDIMP.PI_ESTATUS<>'R' AND
			dbo.CONFIGURACLAVEPED.CCP_TIPO<>'RE'  AND dbo.CONFIGURACLAVEPED.CCP_TIPO<>'CN' AND ISNULL(PICF_PEDIMPSINAGRUP,'N')='S'



GO
