SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO













CREATE PROCEDURE [dbo].[SP_CreaFactExpDetTempF4]   as

declare @FED_INDICED int

	exec sp_droptable 'FactExpDetTempF4'


	CREATE TABLE [dbo].[FactExpDetTempF4](
		[FED_INDICED] [int] IDENTITY (1, 1) NOT NULL ,
		[FE_CODIGO] [int] NOT NULL,
		[MA_CODIGO] [int] NOT NULL,
		[FED_NOMBRE] [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_NOPARTE] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_NAME] [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_CODIGO] [int] NULL,
		[FED_OBSERVA] [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_CANT] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_CANT]  DEFAULT (0),
		[FED_GRA_MP] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_GRA_MP]  DEFAULT (0),
		[FED_GRA_MO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_GRA_MO]  DEFAULT (0),
		[FED_GRA_EMP] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_GRA_EMP]  DEFAULT (0),
		[FED_GRA_ADD] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_GRA_ADD]  DEFAULT (0),
		[FED_GRA_GI] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_GRA_GI]  DEFAULT (0),
		[FED_GRA_GI_MX] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_GRA_GI_MX]  DEFAULT (0),
		[FED_NG_MP] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_NG_MP]  DEFAULT (0),
		[FED_NG_EMP] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_NG_EMP]  DEFAULT (0),
		[FED_NG_ADD] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_NG_ADD]  DEFAULT (0),
		[FED_NG_USA] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_NG_USA]  DEFAULT (0),
		[FED_COS_UNI] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_COS_UNI]  DEFAULT (0),
		[FED_COS_TOT] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_COS_TOT]  DEFAULT (0),
		[FED_PES_UNI] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_PES_UNI]  DEFAULT (0),
		[FED_PES_NET] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_PES_NET]  DEFAULT (0),
		[FED_PES_BRU] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_PES_BRU]  DEFAULT (0),
		[FED_PES_UNILB] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_PES_UNILB]  DEFAULT (0),
		[FED_PES_NETLB] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_PES_NETLB]  DEFAULT (0),
		[FED_PES_BRULB] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_PES_BRULB]  DEFAULT (0),
		[FED_SEC_IMP] [smallint] NULL CONSTRAINT [DF_FactExpDetTempF4_FED_SEC_IMP]  DEFAULT (0),
		[FED_DEF_TIP] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_DEF_TIP]  DEFAULT ('G'),
		[FED_POR_DEF] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_POR_DEF]  DEFAULT ((-1)),
		[FED_LOTE] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AR_IMPMX] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_AR_IMPMX]  DEFAULT (0),
		[AR_EXPMX] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_AR_EXPMX]  DEFAULT (0),
		[AR_IMPFO] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_AR_IMPFO]  DEFAULT (0),
		[FED_CON_PED] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_CON_PED]  DEFAULT ('N'),
		[MA_GENERICO] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_MA_GENERICO]  DEFAULT (0),
		[PA_CODIGO] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_PA_CODIGO]  DEFAULT (0),
		[LE_CODIGO] [int] NULL,
		[LED_INDICED] [int] NULL,
		[EX_CODIGO] [int] NULL,
		[FED_ORD_COMP] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FactExpDetTempF4_FED_ORD_COMP]  DEFAULT (''),
		[FED_NOORDEN] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FactExpDetTempF4_FED_NOORDEN]  DEFAULT (''),
		[FED_USO_COMMINV] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_USO_COMMINV]  DEFAULT ('N'),
		[EQ_GEN] decimal(28,14) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_EQ_GEN]  DEFAULT (1),
		[EQ_IMPFO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_EQ_IMPFO]  DEFAULT (1),		[EQ_EXPMX] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_EQ_EXPMX]  DEFAULT (1),
		[TI_CODIGO] [smallint] NOT NULL,
		[FED_TENVIO] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_INBOND] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_TIPOINBOND] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_RATEEXPMX] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_RATEEXPMX]  DEFAULT ((-1)),
		[FED_RATEIMPFO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_RATEIMPFO]  DEFAULT ((-1)),
		[FED_RELEMP] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_RELEMP]  DEFAULT ('N'),
		[FED_FECHA_STRUCT] [datetime] NULL,
		[FED_DISCHARGE] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_DISCHARGE]  DEFAULT ('S'),
		[LE_FOLIO] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SPI_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_SPI_CODIGO]  DEFAULT (0),
		[FED_SALDO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_SALDO]  DEFAULT (0),
		[FED_RETRABAJO] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_RETRABAJO]  DEFAULT ('N'),
		[ADE_CODIGO] [int] NULL,
		[MA_EMPAQUE] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_MA_EMPAQUE]  DEFAULT (0),
		[FED_CANTEMP] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_CANTEMP]  DEFAULT (0),
		[FED_FAC_NUM] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_FEC_ENV] [datetime] NULL,
		[FED_CON_CERTORIG] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_CON_CERTORIG]  DEFAULT ('N'),
		[FED_COS_UNI_CO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_COS_UNI_CO]  DEFAULT (0),
		[FED_GRA_MAT_CO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_GRA_MAT_CO]  DEFAULT (0),
		[FED_EMP_CO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_EMP_CO]  DEFAULT (0),
		[FED_NG_MAT_CO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_NG_MAT_CO]  DEFAULT (0),
		[FED_VA_CO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_VA_CO]  DEFAULT (0),
		[FED_CANTGEN] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_CANTGEN]  DEFAULT (0),
		[MO_CODIGO] [int] NULL,
		[FED_DESCARGADO] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_DESCARGADO]  DEFAULT ('N'),
		[FED_PARTTYPE] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ME_GENERICO] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_ME_GENERICO]  DEFAULT (0),
		[FED_TIP_ENS] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PID_INDICED] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_PID_INDICED]  DEFAULT ((-1)),
		[MA_NOPARTECL] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ME_AREXPMX] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_ME_AREXPMX]  DEFAULT (0),
		[FED_NAFTA] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_NAFTA]  DEFAULT ('N'),
		[FED_DEFTXT1] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FactExpDetTempF4_FED_DEFTXT1]  DEFAULT (''),
		[FED_DEFTXT2] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_FactExpDetTempF4_FED_DEFTXT2]  DEFAULT (''),
		[FED_DEFNO3] decimal(38,6) NULL,
		[FED_DEFNO4] decimal(38,6) NULL,
		[PID_INDICEDLIGA] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_PID_INDICEDLIGA]  DEFAULT ((-1)),
		[PID_INDICEDLIGAR1] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_PID_INDICEDLIGAR1]  DEFAULT ((-1)),
		[TCO_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_TCO_CODIGO]  DEFAULT (0),
		[PI_ORIGENKITPADRE] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_PI_ORIGENKITPADRE]  DEFAULT ((-1)),
		[CS_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_CS_CODIGO]  DEFAULT (0),
		[SE_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_SE_CODIGO]  DEFAULT (0),
		[FED_RELCAJAS] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[END_INDICED] [int] NULL,
		[EN_CODIGO] [int] NULL,
		[FED_SALDOTRANS] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_SALDOTRANS]  DEFAULT (0),
		[FED_USOTRANS] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_USOTRANS]  DEFAULT ('N'),
		[FED_USOSALDO] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_USOSALDO]  DEFAULT ('N'),
		[CL_CODIGO] [int] NULL,
		[MA_STRUCT] [int] NULL,
		[FED_DESTNAFTA] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AR_ORIG] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_AR_ORIG]  DEFAULT (0),
		[AR_NG_EMP] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_AR_NG_EMP]  DEFAULT (0),
		[FED_NOPARTEAUX] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ETA_CODIGO] [int] NOT NULL CONSTRAINT [DF_FactExpDetTempF4_ETA_CODIGO]  DEFAULT ((-1)),
		[FED_NG_MX] decimal(38,6) NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_NG_MX]  DEFAULT (0),
		[FED_NOPARTESTRUCT] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_GENERA_EMPDET] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactExpDetTempF4_FED_GENERA_EMPDET]  DEFAULT ('D'),
		[FED_SECF4] [int] NULL,
			CONSTRAINT [PK_FactExpDetTempF4] PRIMARY KEY  NONCLUSTERED 
			(
				[FED_INDICED]
			)  ON [PRIMARY] 
		) ON [PRIMARY]
	
		select @FED_INDICED= max(isnull(fed_indiced,0))+1 from factexpdet

		DBCC CHECKIDENT (FactExpDetTempF4, RESEED, @FED_INDICED) WITH NO_INFOMSGS







GO
