SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





































CREATE PROCEDURE [dbo].[SP_ACTUALIZAEQARALISTAEXP] (@LE_codigo int)   as

SET NOCOUNT ON 
		-- existe en equivalencias


/*		UPDATE LISTAEXPDET
		SET ME_AREXPMX=(SELECT ME_CODIGO FROM ARANCEL WHERE AR_CODIGO=LISTAEXPDET.AR_EXPMX)
		WHERE LE_CODIGO=@LE_codigo*/

		if exists (SELECT     dbo.LISTAEXPDET.EQ_EXPMX
		      FROM         dbo.EQUIVALE INNER JOIN
                      dbo.LISTAEXPDET ON dbo.EQUIVALE.ME_CODIGO1 = dbo.LISTAEXPDET.ME_CODIGO INNER JOIN
                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN
                      dbo.ARANCEL ON dbo.LISTAEXPDET.AR_EXPMX = dbo.ARANCEL.AR_CODIGO AND dbo.EQUIVALE.ME_CODIGO2 = dbo.ARANCEL.ME_CODIGO
				WHERE     (dbo.LISTAEXP.LE_CODIGO=@LE_codigo))


			UPDATE dbo.LISTAEXPDET
			SET dbo.LISTAEXPDET.EQ_EXPMX=dbo.EQUIVALE.EQ_CANT
		      FROM         dbo.EQUIVALE INNER JOIN
	                      dbo.LISTAEXPDET ON dbo.EQUIVALE.ME_CODIGO1 = dbo.LISTAEXPDET.ME_CODIGO INNER JOIN
	                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN
	                      dbo.ARANCEL ON dbo.LISTAEXPDET.AR_EXPMX = dbo.ARANCEL.AR_CODIGO AND dbo.EQUIVALE.ME_CODIGO2 = dbo.ARANCEL.ME_CODIGO
				WHERE     (dbo.LISTAEXP.LE_CODIGO=@LE_codigo)



		-- ME_AREXPMX igual a Kg
		UPDATE dbo.LISTAEXPDET
		SET dbo.LISTAEXPDET.EQ_EXPMX = dbo.LISTAEXPDET.LED_PES_UNI
		FROM         dbo.LISTAEXPDET INNER JOIN
                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN
                      dbo.ARANCEL ON dbo.LISTAEXPDET.AR_EXPMX = dbo.ARANCEL.AR_CODIGO
		WHERE (dbo.LISTAEXP.LE_CODIGO=@LE_codigo)
			AND dbo.LISTAEXPDET.LED_PES_UNI>0 AND dbo.ARANCEL.ME_CODIGO in (select ME_KILOGRAMOS from configuracion) 

		UPDATE dbo.LISTAEXPDET
		SET dbo.LISTAEXPDET.EQ_EXPMX = 1
		FROM         dbo.LISTAEXPDET INNER JOIN
                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN
                      dbo.ARANCEL ON dbo.LISTAEXPDET.AR_EXPMX = dbo.ARANCEL.AR_CODIGO
		WHERE (dbo.LISTAEXP.LE_CODIGO=@LE_codigo)
			AND (dbo.LISTAEXPDET.LED_PES_UNI is null or  dbo.LISTAEXPDET.LED_PES_UNI=0) 
			AND dbo.ARANCEL.ME_CODIGO in (select ME_KILOGRAMOS from configuracion) 
			AND dbo.LISTAEXPDET.ME_CODIGO not in (SELECT ME_CODIGO1 FROM EQUIVALE
			WHERE     ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))


		-- en base a maestromedida
		UPDATE dbo.LISTAEXPDET
		SET     dbo.LISTAEXPDET.EQ_EXPMX= dbo.MAESTROMEDIDA.EQ_CANTIDAD
		FROM         dbo.MAESTRO MAESTRO_1 INNER JOIN
                      dbo.MAESTRO ON MAESTRO_1.MA_CODIGO = dbo.MAESTRO.MA_GENERICO INNER JOIN
                      dbo.LISTAEXPDET INNER JOIN
                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN
                      dbo.MAESTROMEDIDA ON dbo.LISTAEXPDET.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
                      dbo.LISTAEXPDET.ME_CODIGO = dbo.MAESTROMEDIDA.ME_CODIGO ON 
                      dbo.MAESTRO.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO INNER JOIN
                      dbo.ARANCEL ON dbo.LISTAEXPDET.AR_EXPMX = dbo.ARANCEL.AR_CODIGO AND MAESTRO_1.ME_COM = dbo.ARANCEL.ME_CODIGO
		WHERE (dbo.LISTAEXP.LE_CODIGO=@LE_codigo)


		-- sin factor de conversion
		UPDATE dbo.LISTAEXPDET
		SET dbo.LISTAEXPDET.EQ_EXPMX = 1
		WHERE (dbo.LISTAEXPDET.EQ_EXPMX=0 OR dbo.LISTAEXPDET.EQ_EXPMX IS NULL)


/* =========================================================== EQ_IMPFO =====================================================*/
		-- existe en equivalencias
		if exists (SELECT     dbo.LISTAEXPDET.EQ_IMPFO
				FROM         dbo.EQUIVALE INNER JOIN
				                      dbo.LISTAEXPDET ON dbo.EQUIVALE.ME_CODIGO1 = dbo.LISTAEXPDET.ME_CODIGO INNER JOIN
				                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN
				                      dbo.ARANCEL ON dbo.LISTAEXPDET.AR_IMPFO = dbo.ARANCEL.AR_CODIGO AND dbo.EQUIVALE.ME_CODIGO2 = dbo.ARANCEL.ME_CODIGO
				WHERE     (dbo.LISTAEXP.LE_CODIGO=@LE_codigo))


			UPDATE dbo.LISTAEXPDET
			SET dbo.LISTAEXPDET.EQ_IMPFO=dbo.EQUIVALE.EQ_CANT
				FROM         dbo.EQUIVALE INNER JOIN
				                      dbo.LISTAEXPDET ON dbo.EQUIVALE.ME_CODIGO1 = dbo.LISTAEXPDET.ME_CODIGO INNER JOIN
				                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN
				                      dbo.ARANCEL ON dbo.LISTAEXPDET.AR_IMPFO = dbo.ARANCEL.AR_CODIGO AND dbo.EQUIVALE.ME_CODIGO2 = dbo.ARANCEL.ME_CODIGO
				WHERE     (dbo.LISTAEXP.LE_CODIGO=@LE_codigo)



		-- ME_AREXPMX igual a Kg
		UPDATE dbo.LISTAEXPDET
		SET dbo.LISTAEXPDET.EQ_IMPFO = dbo.LISTAEXPDET.LED_PES_UNI
		FROM  dbo.LISTAEXPDET INNER JOIN
                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN ARANCEL ON
		      dbo.LISTAEXPDET.AR_IMPFO = dbo.ARANCEL.AR_CODIGO 			
		WHERE (dbo.LISTAEXP.LE_CODIGO=@LE_codigo)
			AND dbo.LISTAEXPDET.LED_PES_UNI>0 AND dbo.ARANCEL.ME_CODIGO in (select ME_KILOGRAMOS from configuracion) 

		UPDATE dbo.LISTAEXPDET
		SET dbo.LISTAEXPDET.EQ_IMPFO = 1
		FROM  dbo.LISTAEXPDET INNER JOIN
                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN ARANCEL ON
		      dbo.LISTAEXPDET.AR_IMPFO = dbo.ARANCEL.AR_CODIGO 			
		WHERE (dbo.LISTAEXP.LE_CODIGO=@LE_codigo)
			AND (dbo.LISTAEXPDET.LED_PES_UNI is null or  dbo.LISTAEXPDET.LED_PES_UNI=0) 
			AND dbo.ARANCEL.ME_CODIGO in (select ME_KILOGRAMOS from configuracion) 
			AND dbo.LISTAEXPDET.ME_CODIGO not in (SELECT ME_CODIGO1 FROM EQUIVALE
			WHERE     ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))


		-- en base a maestromedida
		UPDATE dbo.LISTAEXPDET
		SET     dbo.LISTAEXPDET.EQ_IMPFO= dbo.MAESTROMEDIDA.EQ_CANTIDAD
		FROM         dbo.MAESTRO MAESTRO_1 INNER JOIN
	                      dbo.MAESTRO ON MAESTRO_1.MA_CODIGO = dbo.MAESTRO.MA_GENERICO INNER JOIN
	                      dbo.LISTAEXPDET INNER JOIN
	                      dbo.LISTAEXP ON dbo.LISTAEXPDET.LE_CODIGO = dbo.LISTAEXP.LE_CODIGO INNER JOIN
	                      dbo.MAESTROMEDIDA ON dbo.LISTAEXPDET.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
	                      dbo.LISTAEXPDET.ME_CODIGO = dbo.MAESTROMEDIDA.ME_CODIGO ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO INNER JOIN
	                      dbo.ARANCEL ON dbo.LISTAEXPDET.AR_IMPFO = dbo.ARANCEL.AR_CODIGO AND MAESTRO_1.ME_COM = dbo.ARANCEL.ME_CODIGO
		WHERE (dbo.LISTAEXP.LE_CODIGO=@LE_codigo)


	
		-- sin factor de conversion
		UPDATE dbo.LISTAEXPDET
		SET dbo.LISTAEXPDET.EQ_IMPFO = 1
		WHERE (dbo.LISTAEXPDET.EQ_IMPFO=0 OR dbo.LISTAEXPDET.EQ_IMPFO IS NULL)




































GO
