SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_IMPEXCELPEDIMP] @Codigo int, @clavePed int   as

SET NOCOUNT ON 
DECLARE @CONSECUTIVO INTEGER, @NOPARTE varchar(30), @COSTO decimal(38,6), @CANTIDAD decimal(38,6), @PESO decimal(38,6), @ORIGEN INT,
@PID_indiced INT, @pi_ft_adu decimal(38,9), @PI_TIP_CAM decimal(38,6)
/*Yolanda 2009-01-21*/
DECLARE @TipoEntrada CHAR(1)
SET @TipoEntrada= 'I'


UPDATE dbo.IMPEXCELFACTIMP
SET     dbo.IMPEXCELFACTIMP.COSTO= ISNULL(dbo.VMAESTROCOST.MA_COSTO, 0)
FROM         dbo.IMPEXCELFACTIMP INNER JOIN
                      dbo.MAESTRO ON dbo.IMPEXCELFACTIMP.NOPARTE+'-'+ISNULL(IMPEXCELFACTIMP.NOPARTEAUX,'') = dbo.MAESTRO.MA_NOPARTE+'-'+LTRIM(RTRIM(MAESTRO.MA_NOPARTEAUX)) LEFT OUTER JOIN
                      dbo.VMAESTROCOST ON dbo.MAESTRO.MA_CODIGO = dbo.VMAESTROCOST.MA_CODIGO
where /*Yolanda 2009-01-21*/ maestro.ma_inv_gen = @TipoEntrada


DELETE FROM IMPORTLOG WHERE IML_CBFORMA=35
if (select count(*) from IMPORTLOG)=0

DBCC CHECKIDENT (IMPORTLOG, RESEED, 0) WITH NO_INFOMSGS
delete from IMPEXCELFACTIMP where NOPARTE=''

if exists(SELECT dbo.IMPEXCELFACTIMP.NOPARTE
	FROM         dbo.MAESTRO RIGHT OUTER JOIN 
                     dbo.IMPEXCELFACTIMP ON dbo.IMPEXCELFACTIMP.NOPARTE+'-'+ISNULL(IMPEXCELFACTIMP.NOPARTEAUX,'') = dbo.MAESTRO.MA_NOPARTE+'-'+LTRIM(RTRIM(isnull(MAESTRO.MA_NOPARTEAUX,'')))
	WHERE     (dbo.MAESTRO.MA_NOPARTE+'-'+LTRIM(RTRIM(isnull(MAESTRO.MA_NOPARTEAUX,''))) IS NULL)/*Yolanda 2009-01-21*/ and maestro.ma_inv_gen = @TipoEntrada)

	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR NO. PARTE : ' +dbo.IMPEXCELFACTIMP.NOPARTE+' CON EL AUX.: '+isnull(IMPEXCELFACTIMP.NOPARTEAUX,'') +' POR QUE NO EXISTE EN EL CAT. MAESTRO', 35
	FROM         dbo.MAESTRO RIGHT OUTER JOIN
                              dbo.IMPEXCELFACTIMP ON dbo.MAESTRO.MA_NOPARTE+'-'+LTRIM(RTRIM(isnull(MAESTRO.MA_NOPARTEAUX,''))) = dbo.IMPEXCELFACTIMP.NOPARTE+'-'+ISNULL(IMPEXCELFACTIMP.NOPARTEAUX,'')
	WHERE     (dbo.MAESTRO.MA_NOPARTE+'-'+LTRIM(RTRIM(isnull(MAESTRO.MA_NOPARTEAUX,''))) IS NULL)
	/*Yolanda 2009-01-21*/ and maestro.ma_inv_gen = @TipoEntrada



	if exists (SELECT     dbo.IMPEXCELFACTIMP.NOPARTE
		FROM         dbo.MAESTRO INNER JOIN
                                      dbo.IMPEXCELFACTIMP ON dbo.MAESTRO.MA_NOPARTE+'-'+LTRIM(RTRIM(isnull(MAESTRO.MA_NOPARTEAUX,''))) = dbo.IMPEXCELFACTIMP.NOPARTE+'-'+ISNULL(IMPEXCELFACTIMP.NOPARTEAUX,'')
		WHERE     dbo.MAESTRO.TI_CODIGO NOT IN
                          (SELECT     dbo.RELTEMBTIPO.TI_CODIGO
			FROM         dbo.RELTFACTCLAPED INNER JOIN
			                      dbo.RELTFACTTEMBAR ON dbo.RELTFACTCLAPED.TF_CODIGO = dbo.RELTFACTTEMBAR.TF_CODIGO INNER JOIN
			                      dbo.RELTEMBTIPO ON dbo.RELTFACTTEMBAR.TQ_CODIGO = dbo.RELTEMBTIPO.TQ_CODIGO
			WHERE     (dbo.RELTFACTCLAPED.CP_CODIGO = @clavePed))/*Yolanda 2009-01-21*/ and maestro.ma_inv_gen = @TipoEntrada)

	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR NO. PARTE : ' +dbo.IMPEXCELFACTIMP.NOPARTE+' CON EL AUX.: '+isnull(IMPEXCELFACTIMP.NOPARTEAUX,'')+' POR LA RELACION CLAVE PEDIMENTO-TIPO MATERIAL', 35
		FROM         dbo.MAESTRO INNER JOIN
                                      dbo.IMPEXCELFACTIMP ON dbo.MAESTRO.MA_NOPARTE+'-'+LTRIM(RTRIM(MAESTRO.MA_NOPARTEAUX)) = dbo.IMPEXCELFACTIMP.NOPARTE+'-'+ISNULL(IMPEXCELFACTIMP.NOPARTEAUX,'')
		WHERE     (dbo.MAESTRO.TI_CODIGO NOT IN
                          (SELECT     dbo.RELTEMBTIPO.TI_CODIGO
			FROM         dbo.RELTFACTCLAPED INNER JOIN
			                      dbo.RELTFACTTEMBAR ON dbo.RELTFACTCLAPED.TF_CODIGO = dbo.RELTFACTTEMBAR.TF_CODIGO INNER JOIN
			                      dbo.RELTEMBTIPO ON dbo.RELTFACTTEMBAR.TQ_CODIGO = dbo.RELTEMBTIPO.TQ_CODIGO
			WHERE     (dbo.RELTFACTCLAPED.CP_CODIGO = @clavePed))) and
	'NO SE PUEDE IMPORTAR NO. PARTE : ' +dbo.IMPEXCELFACTIMP.NOPARTE+' CON EL AUX.: '+isnull(IMPEXCELFACTIMP.NOPARTEAUX,'') +' POR QUE NO EXISTE EN EL CAT. MAESTRO' 
	not in (SELECT IML_MENSAJE FROM IMPORTLOG)
	/*Yolanda 2009-01-21*/ and maestro.ma_inv_gen = @TipoEntrada



	SELECT @pi_ft_adu=pi_ft_adu, @PI_TIP_CAM=PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO=@Codigo

	select @consecutivo=cv_codigo from consecutivo
	where cv_tipo = 'PID'

		INSERT INTO PEDIMPDET (PID_INDICED,PI_CODIGO,PID_NOPARTE,PID_COS_UNI,PID_CANT,PID_NOMBRE,PID_NAME,MA_CODIGO,
                                                             TI_CODIGO,PID_POR_DEF,PID_SEC_IMP,SPI_CODIGO,PA_ORIGEN,MA_GENERICO,AR_IMPMX,ME_ARIMPMX,
 				       AR_EXPFO,EQ_IMPMX,EQ_EXPFO,EQ_GENERICO,PID_DEF_TIP, ME_CODIGO, ME_GENERICO, PR_CODIGO, PID_COS_UNIGEN,
				 PID_CAN_GEN, PID_CTOT_DLS, PID_CAN_AR, PID_VAL_ADU, PID_COS_UNIADU, PID_NOPARTEAUX) 

                          SELECT ORDEN+@consecutivo,@Codigo, dbo.IMPEXCELFACTIMP.NOPARTE, dbo.IMPEXCELFACTIMP.COSTO, dbo.IMPEXCELFACTIMP.CANTIDAD, dbo.MAESTRO.MA_NOMBRE, 
		dbo.MAESTRO.MA_NAME, dbo.MAESTRO.MA_CODIGO, dbo.MAESTRO.TI_CODIGO, dbo.GetAdvalorem(dbo.MAESTRO.AR_IMPMX, ISNULL(dbo.IMPEXCELFACTIMP.ORIGEN, dbo.MAESTRO.PA_ORIGEN), isnull(dbo.MAESTRO.MA_DEF_TIP,'G'), isnull(dbo.MAESTRO.MA_SEC_IMP,0), isnull(dbo.MAESTRO.SPI_CODIGO,0)),
		 dbo.MAESTRO.MA_SEC_IMP,ISNULL(dbo.MAESTRO.SPI_CODIGO,0), 
		ISNULL(dbo.IMPEXCELFACTIMP.ORIGEN, dbo.MAESTRO.PA_ORIGEN), dbo.MAESTRO.MA_GENERICO, isnull(dbo.MAESTRO.AR_IMPMX,0), (SELECT isnull(ME_CODIGO,0) 
		FROM ARANCEL WHERE AR_CODIGO=dbo.MAESTRO.AR_IMPMX), isnull(dbo.MAESTRO.AR_EXPFO,0), isnull(dbo.MAESTRO.EQ_IMPMX,1), isnull(dbo.MAESTRO.EQ_EXPFO,1), 
		isnull(dbo.MAESTRO.EQ_GEN,1), dbo.MAESTRO.MA_DEF_TIP, dbo.MAESTRO.ME_COM, (SELECT ME_COM FROM VMAESTRO_GENERICO AS MAESTRO1 
		WHERE MA_CODIGO=dbo.MAESTRO.MA_GENERICO), 	(SELECT PR_CODIGO FROM FACTIMP WHERE PI_CODIGO= @Codigo), dbo.IMPEXCELFACTIMP.COSTO / isnull(dbo.MAESTRO.EQ_GEN,1), 
		isnull(dbo.IMPEXCELFACTIMP.CANTIDAD,0) * isnull(dbo.MAESTRO.EQ_GEN,1), isnull(dbo.IMPEXCELFACTIMP.CANTIDAD,0) * isnull(dbo.IMPEXCELFACTIMP.COSTO,0),
		isnull(dbo.IMPEXCELFACTIMP.CANTIDAD,0) * isnull(dbo.MAESTRO.EQ_IMPMX,0), 
		(isnull(dbo.IMPEXCELFACTIMP.CANTIDAD,0) * isnull(dbo.MAESTRO.EQ_GEN,1)) * (isnull(dbo.IMPEXCELFACTIMP.COSTO,0) / isnull(dbo.MAESTRO.EQ_GEN,1)) * @PI_TIP_CAM * @pi_ft_adu,
		(isnull(dbo.IMPEXCELFACTIMP.COSTO,0) / isnull(dbo.MAESTRO.EQ_GEN,1)) * @PI_TIP_CAM * @pi_ft_adu, maestro.ma_noparteaux 
        	from dbo.IMPEXCELFACTIMP INNER JOIN
		                      dbo.MAESTRO ON dbo.MAESTRO.MA_NOPARTE+'-'+LTRIM(RTRIM(isnull(dbo.MAESTRO.MA_NOPARTEAUX,''))) = dbo.IMPEXCELFACTIMP.NOPARTE+'-'+ISNULL(dbo.IMPEXCELFACTIMP.NOPARTEAUX,'') LEFT OUTER JOIN
		                      dbo.PAIS ON dbo.IMPEXCELFACTIMP.ORIGEN = dbo.PAIS.PA_CORTO
		WHERE     (NOT (dbo.IMPEXCELFACTIMP.COSTO IS NULL)) AND (NOT (dbo.IMPEXCELFACTIMP.PESO IS NULL)) AND 
		                      (NOT (dbo.IMPEXCELFACTIMP.NOPARTE+'-'+ISNULL(IMPEXCELFACTIMP.NOPARTEAUX,'') NOT IN
		                          (SELECT     MA_NOPARTE+'-'+LTRIM(RTRIM(isnull(MA_NOPARTEAUX,'')))
		                            FROM          MAESTRO
		                            WHERE      MA_INV_GEN = 'I' AND TI_CODIGO IN
		                                                       (SELECT     dbo.RELTEMBTIPO.TI_CODIGO
		                                                         FROM          dbo.RELTFACTCLAPED INNER JOIN
		                                                                                dbo.RELTFACTTEMBAR ON dbo.RELTFACTCLAPED.TF_CODIGO = dbo.RELTFACTTEMBAR.TF_CODIGO INNER JOIN
		                                                                                dbo.RELTEMBTIPO ON dbo.RELTFACTTEMBAR.TQ_CODIGO = dbo.RELTEMBTIPO.TQ_CODIGO
		                                                         WHERE      (dbo.RELTFACTCLAPED.CP_CODIGO = @clavePed)) AND MA_EST_MAT = 'A' AND MA_NOPARTE+'-'+LTRIM(RTRIM(isnull(MA_NOPARTEAUX,''))) = NOPARTE+'-'+ISNULL(IMPEXCELFACTIMP.NOPARTEAUX,''))))
		/*Yolanda 2009-01-21*/ and maestro.ma_inv_gen = @TipoEntrada
		ORDER BY dbo.IMPEXCELFACTIMP.ORDEN




	insert into PIDescarga(PI_CODIGO, PID_INDICED, PID_SALDOGEN, MA_CODIGO, MA_GENERICO, PI_FEC_ENT, PI_ACTIVOFIJO, PI_DEFINITIVO, DI_DEST_ORIGEN)
	SELECT PedImpDet.PI_CODIGO, PedImpDet.PID_INDICED, PedImpDet.PID_CAN_GEN, PedImpDet.MA_CODIGO, PedImpDet.MA_GENERICO, PEDIMP.PI_FEC_ENT, 
	'PI_ACTIVOFIJO'=CASE WHEN PEDIMP.CP_CODIGO in (select cp_codigo from configuraclaveped where ccp_tipo in ('IA', 'IB', 'IM')) THEN 'S' ELSE 'N' END,
	'N', PEDIMP.DI_DEST_ORIGEN
	FROM PEDIMP LEFT OUTER JOIN
	                      CLAVEPED ON PEDIMP.CP_CODIGO = CLAVEPED.CP_CODIGO INNER JOIN
	                      PedImpDet ON PEDIMP.PI_CODIGO = PedImpDet.PI_CODIGO
	WHERE (PEDIMP.PI_ACTIVO_DESCARGA = 'S') AND (PEDIMP.PI_MOVIMIENTO='E') 
			and ((CLAVEPED.CP_DESCARGABLE = 'S' and PEDIMP.CP_CODIGO in (select cp_codigo from configuraclaveped where ccp_tipo not in ('RE')))
				or (PEDIMP.CP_CODIGO in (select cp_codigo from configuraclaveped where ccp_tipo in ('RE'))  and PI_GENERASALDOF4 ='S'))
			and (PedImpDet.pid_descargable='S') --AND PID_INDICED NOT IN (SELECT PID_INDICED FROM PIDescarga)
	and PEDIMP.CP_CODIGO in (select cp_codigo from configuraclaveped where ccp_tipo in ('IT', 'IV', 'OC', 'TR', 'VT', 'RG', 'IR', 'IB', 'RE', 'IA', 'IM', 'ED'))
	and  PedImpDet.PI_CODIGO=@Codigo
	ORDER BY PEDIMP.PI_FEC_ENT ASC, PEDIMP.PI_CODIGO ASC



	--if (select CF_USASALDOPEDIMPDEFINITO from configuracion)='S'
	begin
		insert into PIDescarga(PI_CODIGO, PID_INDICED, PID_SALDOGEN, MA_CODIGO, MA_GENERICO, PI_FEC_ENT, PI_ACTIVOFIJO, PI_DEFINITIVO, DI_DEST_ORIGEN)
		SELECT PEDIMPDET.PI_CODIGO, PEDIMPDET.PID_INDICED, 0, PEDIMPDET.MA_CODIGO, PEDIMPDET.MA_GENERICO, PEDIMP.PI_FEC_ENT, 
		'PI_ACTIVOFIJO'=CASE WHEN PEDIMPDET.TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE CFT_TIPO IN('H', 'Q', 'X', 'C')) THEN 'S' ELSE 'N' END,
		'S', PEDIMP.DI_DEST_ORIGEN
		FROM PEDIMP LEFT OUTER JOIN
		                      CLAVEPED ON PEDIMP.CP_CODIGO = CLAVEPED.CP_CODIGO LEFT OUTER JOIN
		                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO 
		WHERE (PEDIMP.PI_MOVIMIENTO='E')  AND PID_INDICED NOT IN (SELECT PID_INDICED FROM PIDescarga)
		and PEDIMP.CP_CODIGO in (select cp_codigo from configuraclaveped where ccp_tipo in ('IE', 'RG', 'SI', 'CN')) 
		and PI_GENERASALDOF4 ='S'
--		(PEDIMP.CP_CODIGO in (select cp_codigo from configuraclaveped where ccp_tipo in ('CN')) and PI_GENERASALDOF4 ='S'))
		and  PedImpDet.PI_CODIGO=@Codigo
		ORDER BY PEDIMP.PI_FEC_ENT ASC, PEDIMP.PI_CODIGO ASC


	end



	exec sp_actualizapedimpvencimiento  @codigo, 1


	select @PID_indiced= max(PID_indiced) from PEDIMPDET

	update consecutivo
	set cv_codigo =  isnull(@PID_indiced,0) + 1
	where cv_tipo = 'PID'

GO
