SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




























CREATE PROCEDURE [dbo].[SP_CreaIMPORTTEMPBOM]   as



exec sp_droptable 'IMPORTTEMPBOM'

CREATE TABLE [dbo].[IMPORTTEMPBOM] (
	[CONSECUTIVO] [int] IDENTITY (1, 1) NOT NULL,
	[BST_INCORPOR] decimal(38,6) NOT NULL CONSTRAINT [DF_ImportTempBOM_BST_INCORPOR] DEFAULT (1),
	[BST_DISCH] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ImportTempBOM_BST_DISCH] DEFAULT ('S'),
	[ME_CODIGO] [int] NULL ,
	[FACTCONV] decimal(28,14) NULL CONSTRAINT [DF_ImportTempBOM_FACTCONV] DEFAULT (1),
	[BST_PERINI] [datetime] NULL CONSTRAINT [DF_IMPORTTEMPBOM_BST_PERINI] DEFAULT ('1/1/1999'),
	[BST_PERFIN] [datetime] NULL CONSTRAINT [DF_IMPORTTEMPBOM_BST_PERFIN] DEFAULT ('1/1/9999'),
	[ME_GEN] [int] NULL ,
	[BST_TRANS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ImportTempBOM_BST_TRANS] DEFAULT ('N'),
	[BSU_NOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BST_NOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BST_PERCAMBIO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ImportTempBOM_BST_PERCAMBIOS] DEFAULT ('N'),
	[BSU_NOPARTEAUX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ImportTempBOM_BSU_NOPARTEAUX] DEFAULT (''),
	[BST_NOPARTEAUX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_ImportTempBOM_BST_NOPARTEAUX] DEFAULT (''),
	[BST_TIP_ENS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BST_SEC] [smallint] NOT NULL CONSTRAINT [DF_ImportTempBOM_BST_SEC] DEFAULT (-1)
) ON [PRIMARY]


CREATE  CLUSTERED  INDEX [IX_IMPORTTEMPBOM] ON [dbo].[IMPORTTEMPBOM]
(
         [BSU_NOPARTE], 
         [BST_NOPARTE], 
         [BST_PERINI], 
         [BST_PERFIN],
         [BST_SEC]
) ON [PRIMARY]



ALTER TABLE [dbo].[IMPORTTEMPBOM] ADD 
	CONSTRAINT [IX_IMPORTTEMPBOM_1] UNIQUE  NONCLUSTERED 
	(
		[CONSECUTIVO]
	) WITH  FILLFACTOR = 90  ON [PRIMARY]




















GO
