SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_IMPORTACTUALIZAEQFACTEXP]   as

SET NOCOUNT ON 

	-- FACTORES DE CONVERSION GRUPO GENERICO
	/*==================================================================*/
		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_GEN=dbo.EQUIVALE.EQ_CANT
		FROM         dbo.EQUIVALE INNER JOIN
		                      dbo.FACTEXPDET ON dbo.EQUIVALE.ME_CODIGO2 = dbo.FACTEXPDET.ME_GENERICO AND 
		                      dbo.EQUIVALE.ME_CODIGO1 = dbo.FACTEXPDET.ME_CODIGO INNER JOIN
		                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE     dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')



		-- ME_GENERICO igual a Kg
		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_GEN = dbo.FACTEXPDET.FED_PES_UNI
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE dbo.FACTEXPDET.FED_PES_UNI>0 AND dbo.FACTEXPDET.ME_GENERICO in (select ME_KILOGRAMOS from configuracion) 
			AND dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')


		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_GEN = 1
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE (dbo.FACTEXPDET.FED_PES_UNI is null or  dbo.FACTEXPDET.FED_PES_UNI=0) 
			AND dbo.FACTEXPDET.ME_GENERICO in (select ME_KILOGRAMOS from configuracion) 
			AND dbo.FACTEXPDET.ME_CODIGO not in (SELECT ME_CODIGO1 FROM EQUIVALE
			WHERE     ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))
			AND dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')



		-- en base a maestromedida
		UPDATE dbo.FACTEXPDET
		SET     dbo.FACTEXPDET.EQ_GEN= dbo.MAESTROMEDIDA.EQ_CANTIDAD
		FROM         dbo.MAESTRO MAESTRO_1 INNER JOIN
	                      dbo.MAESTRO ON MAESTRO_1.MA_CODIGO = dbo.MAESTRO.MA_GENERICO INNER JOIN
	                      dbo.FACTEXPDET INNER JOIN
	                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO INNER JOIN
	                      dbo.MAESTROMEDIDA ON dbo.FACTEXPDET.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
	                      dbo.FACTEXPDET.ME_CODIGO = dbo.MAESTROMEDIDA.ME_CODIGO ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
	                      MAESTRO_1.ME_COM = dbo.FACTEXPDET.ME_GENERICO
		WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
						FROM REGISTROSIMPORTADOS
						WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')


		-- sin factor de conversion
		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_GEN = 1
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE (dbo.FACTEXPDET.EQ_GEN=0 OR dbo.FACTEXPDET.EQ_GEN IS NULL)
			AND dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
			  FROM REGISTROSIMPORTADOS
			  WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')


		-- unidades de medida iguales
		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_GEN = 1
		FROM  dbo.FACTEXPDET INNER JOIN
                            dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE dbo.FACTEXPDET.ME_GENERICO =  dbo.FACTEXPDET.ME_CODIGO 
		  AND dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
			  FROM REGISTROSIMPORTADOS
			  WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')


	

-- FACTORES DE CONVERSION FRACCIONES 
/*===========================================*/

if exists (SELECT dbo.FACTEXPDET.AR_EXPMX FROM dbo.FACTEXP INNER JOIN dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO
WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')
	AND dbo.FACTEXPDET.AR_EXPMX>0)
begin
	-- si existe en equivalencias
		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_EXPMX=dbo.EQUIVALE.EQ_CANT
		FROM dbo.FACTEXPDET INNER JOIN dbo.ARANCEL ON dbo.FACTEXPDET.AR_EXPMX = dbo.ARANCEL.AR_CODIGO INNER JOIN
                      dbo.EQUIVALE ON dbo.FACTEXPDET.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO1 AND dbo.ARANCEL.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO2 INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO 
		WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
			FROM REGISTROSIMPORTADOS
			WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')



	-- si la unidad de medida es kilogramos
		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_EXPMX = dbo.FACTEXPDET.FED_PES_UNI
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')
			AND dbo.FACTEXPDET.FED_PES_UNI>0  AND dbo.FACTEXPDET.ME_AREXPMX in (select ME_KILOGRAMOS from configuracion) 

		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_EXPMX = 1
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')
			AND (dbo.FACTEXPDET.FED_PES_UNI=0 OR dbo.FACTEXPDET.FED_PES_UNI IS NULL)
			AND dbo.FACTEXPDET.ME_AREXPMX in (select ME_KILOGRAMOS from configuracion) 


		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_EXPMX = 1
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE (dbo.FACTEXPDET.FED_PES_UNI=0 OR dbo.FACTEXPDET.FED_PES_UNI IS NULL)
		AND dbo.FACTEXPDET.ME_AREXPMX in (select ME_KILOGRAMOS from configuracion) 
			AND dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')


		-- en base a maestromedida
		UPDATE dbo.FACTEXPDET
		SET     dbo.FACTEXPDET.EQ_EXPMX= dbo.MAESTROMEDIDA.EQ_IMPMX
		FROM         dbo.ARANCEL INNER JOIN
		                      dbo.FACTEXPDET INNER JOIN
		                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO INNER JOIN
		                      dbo.MAESTROMEDIDA ON dbo.FACTEXPDET.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
		                      dbo.FACTEXPDET.ME_CODIGO = dbo.MAESTROMEDIDA.ME_CODIGO ON dbo.ARANCEL.AR_CODIGO = dbo.FACTEXPDET.AR_EXPMX AND 
		                      dbo.ARANCEL.ME_CODIGO = dbo.FACTEXPDET.ME_AREXPMX
		WHERE 	dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')
		AND dbo.MAESTROMEDIDA.EQ_IMPMX IS NOT NULL


		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_EXPMX = 1
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE dbo.FACTEXPDET.ME_AREXPMX = dbo.FACTEXPDET.ME_CODIGO
			AND dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')

end


/* factor de conversion de fraccion importacion usa */


if exists (SELECT dbo.FACTEXPDET.AR_IMPFO FROM dbo.FACTEXP INNER JOIN dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO
WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')
	AND (dbo.FACTEXPDET.AR_IMPFO>0))
begin
	-- si existe en equivalencias
	if exists (SELECT dbo.FACTEXPDET.EQ_IMPFO FROM dbo.FACTEXPDET INNER JOIN dbo.ARANCEL ON dbo.FACTEXPDET.AR_IMPFO= dbo.ARANCEL.AR_CODIGO INNER JOIN
                      dbo.EQUIVALE ON dbo.FACTEXPDET.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO1 AND dbo.ARANCEL.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO2 INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO WHERE 
					dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I'))

		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_IMPFO=dbo.EQUIVALE.EQ_CANT
		FROM dbo.FACTEXPDET INNER JOIN dbo.ARANCEL ON dbo.FACTEXPDET.AR_IMPFO= dbo.ARANCEL.AR_CODIGO INNER JOIN
                      dbo.EQUIVALE ON dbo.FACTEXPDET.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO1 AND dbo.ARANCEL.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO2 INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO 
		WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')



	-- si la unidad de medida es kilogramos
		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_IMPFO = dbo.FACTEXPDET.FED_PES_UNI
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')
			AND dbo.FACTEXPDET.FED_PES_UNI>0 AND dbo.FACTEXPDET.FED_PES_UNI IS NOT NULL
		AND dbo.FACTEXPDET.AR_IMPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO in (select ME_KILOGRAMOS from configuracion) AND AR_CODIGO=dbo.FACTEXPDET.AR_IMPFO)

		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_IMPFO = 1
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')
			AND (dbo.FACTEXPDET.FED_PES_UNI=0 OR dbo.FACTEXPDET.FED_PES_UNI IS NULL)
		AND dbo.FACTEXPDET.AR_IMPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO in (select ME_KILOGRAMOS from configuracion) AND AR_CODIGO=dbo.FACTEXPDET.AR_IMPFO)

		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_IMPFO = 1
		FROM  dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE (dbo.FACTEXPDET.FED_PES_UNI=0 OR dbo.FACTEXPDET.FED_PES_UNI IS NULL)
		AND dbo.FACTEXPDET.AR_IMPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO in (select ME_KILOGRAMOS from configuracion) AND AR_CODIGO=dbo.FACTEXPDET.AR_IMPFO)
		AND dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')


		UPDATE dbo.FACTEXPDET
		SET dbo.FACTEXPDET.EQ_IMPFO = 1
		FROM  dbo.FACTEXPDET INNER JOIN
                           dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
		WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')
		AND dbo.FACTEXPDET.AR_IMPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO=dbo.FACTEXPDET.ME_CODIGO AND AR_CODIGO=dbo.FACTEXPDET.AR_IMPFO)


end



	UPDATE dbo.FACTEXPDET
	SET     dbo.FACTEXPDET.FED_DESTNAFTA= CASE 
	when dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT CF_PAIS_MX FROM CONFIGURACION) THEN 'M'
	 when dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT CF_PAIS_USA FROM CONFIGURACION) or dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT CF_PAIS_CA FROM CONFIGURACION)
	then 'N'  WHEN 	  dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT PA_CODIGO FROM PAIS WHERE SPI_CODIGO IN ( SELECT SPI_CODIGO FROM SPI WHERE SPI_CLAVE='MX-UE')) 
	then 'U' when 	  dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT PA_CODIGO FROM PAIS WHERE SPI_CODIGO IN ( SELECT SPI_CODIGO FROM SPI WHERE SPI_CLAVE='AELC')) 
	then 'A'  else 'F' end
	FROM         dbo.FACTEXPDET INNER JOIN
	                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      dbo.DIR_CLIENTE ON dbo.FACTEXP.DI_DESTFIN = dbo.DIR_CLIENTE.DI_INDICE
	WHERE dbo.FACTEXP.FE_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FE_FOLIO = ','') 
		  FROM REGISTROSIMPORTADOS
		  WHERE RI_REGISTRO LIKE 'FE_FOLIO%' AND RI_TIPO='I')



GO
