SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_IMPORTPTTYCOJUA] (@TABLA VARCHAR(150), @USER INT)   as
			DELETE FROM REGISTROSIMPORTADOS WHERE RI_CBFORMA=28 AND RI_USERID = @USER

exec('UPDATE MAESTRO SET MA_ULTIMAMODIF=GETDATE() 
		  WHERE MA_NOPARTE IN 
			(SELECT MAESTRO'+@USER+'#MA_NOPARTE
			FROM TEMPIMPORT141_'+@USER+'
			 GROUP BY MAESTRO'+@USER+'#MA_NOPARTE)')


exec(' UPDATE MAESTRO 
		  SET MA_EXPENS=isnull(MAESTRO'+@USER+'#MA_EXPENS,''S''), 
			MA_TIP_ENS=MAESTRO'+@USER+'#MA_TIP_ENS, 
			TI_CODIGO=MAESTRO'+@USER+'#TI_CODIGO, 
			MA_NOMBRE=MAESTRO'+@USER+'#MA_NOMBRE, 
			MA_NAME=MAESTRO'+@USER+'#MA_NAME, 
			PA_ORIGEN=MAESTRO'+@USER+'#PA_ORIGEN, 
			PA_PROCEDE=isnull(MAESTRO'+@USER+'#PA_PROCEDE,154), 
			AR_IMPMX=MAESTRO'+@USER+'#AR_IMPMX, 
			AR_EXPMX=MAESTRO'+@USER+'#AR_EXPMX, 
			AR_IMPFO=MAESTRO'+@USER+'#AR_IMPFO, 
			AR_EXPFO=isnull(MAESTRO'+@USER+'#AR_EXPFO,0), 
			MA_DEF_TIP=isnull(MAESTRO'+@USER+'#MA_DEF_TIP,''G''), 
			SE_CODIGO=MAESTRO'+@USER+'#SE_CODIGO, 
			MA_PESO_LB=MAESTRO'+@USER+'#MA_PESO_LB, 
			MA_TIEMPOENSMIN=MAESTRO'+@USER+'#MA_TIEMPOENSMIN, 
			CC_CODIGO=MAESTRO'+@USER+'#CC_CODIGO 
 		  FROM MAESTRO INNER JOIN
		                      TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE
		  WHERE (MAESTRO.MA_INV_GEN = ''I'') and MAESTRO'+@USER+'#MA_TIP_ENS<>''A''')

exec('          UPDATE MAESTRO 
		  SET MA_EXPENS=isnull(MAESTRO'+@USER+'#MA_EXPENS,''S''), 
			MA_TIP_ENS=MAESTRO'+@USER+'#MA_TIP_ENS, 
			TI_CODIGO=MAESTRO'+@USER+'#TI_CODIGO, 
			ME_COM=MAESTRO'+@USER+'#ME_COM, 
			PA_PROCEDE=isnull(MAESTRO'+@USER+'#PA_PROCEDE,154), 
			MA_DEF_TIP=isnull(MAESTRO'+@USER+'#MA_DEF_TIP,''G''), 
			SE_CODIGO=MAESTRO'+@USER+'#SE_CODIGO, 
			MA_PESO_LB=MAESTRO'+@USER+'#MA_PESO_LB, 
			MA_TIEMPOENSMIN=MAESTRO'+@USER+'#MA_TIEMPOENSMIN, 
			CC_CODIGO=MAESTRO'+@USER+'#CC_CODIGO 
 		  FROM MAESTRO INNER JOIN
		                      TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE
		  WHERE (MAESTRO.MA_INV_GEN = ''I'') and MAESTRO'+@USER+'#MA_TIP_ENS=''A''')


	        exec SP_CREATABLALOG 41
	        
exec('      insert into sysusrlog41 (user_id, mov_id, referencia, frmtag, fechahora) 
 	        SELECT     @USER, 2, ''Actualizacion de pt Info. (No. Parte: ''+MAESTRO.MA_NOPARTE+'')'', 41, getdate()
		  FROM MAESTRO INNER JOIN
	                      TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE
	        WHERE (MAESTRO.MA_INV_GEN = ''I'')')


		-- REGISTROS ACTUALIZADOS
exec('  INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO,RI_TIPO,RI_CBFORMA, RI_USERID) 
		SELECT ''MA_NOPARTE = ''+CONVERT(varchar(100),MAESTRO'+@USER+'#MA_NOPARTE)+'', MA_INV_GEN = I, MA_NOPARTEAUX = ''+CONVERT(varchar(100),MAESTRO'+@USER+'#MA_NOPARTEAUX),''A'',28,'+@USER+
		' FROM MAESTRO INNER JOIN
		                    TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE
		WHERE (MAESTRO.MA_INV_GEN = ''I'')')


		-- REGISTROS ANEXADOS
exec('                INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO,RI_TIPO,RI_CBFORMA, RI_USERID) 
		SELECT ''MA_NOPARTE = ''+CONVERT(varchar(100),MAESTRO'+@USER+'#MA_NOPARTE)+'', MA_INV_GEN = I, MA_NOPARTEAUX = ''+CONVERT(varchar(100),MAESTRO'+@USER+'#MA_NOPARTEAUX),''I'',28,'+@USER+
		' FROM TEMPIMPORT141_'+@USER+'
		WHERE MAESTRO'+@USER+'#MA_NOPARTE NOT IN (SELECT MA_NOPARTE FROM MAESTRO WHERE MA_INV_GEN=''I'')')


		exec Sp_GeneraTablaTemp 'MAESTRO'



exec('	    INSERT INTO TempImportMAESTRO (MA_EXPENS ,MA_INV_GEN ,MA_NOPARTEAUX ,MA_TIP_ENS ,MA_NOPARTE ,TI_CODIGO ,MA_NOMBRE ,
		MA_NAME ,ME_COM ,PA_ORIGEN ,PA_PROCEDE ,MA_GENERICO ,AR_IMPMX ,AR_EXPMX ,AR_IMPFO ,AR_EXPFO ,MA_DEF_TIP ,SE_CODIGO ,
		MA_PESO_LB ,MA_TIEMPOENSMIN ,CC_CODIGO) 
		SELECT MAESTRO'+@USER+'#MA_EXPENS, MAESTRO'+@USER+'#MA_INV_GEN, MAESTRO'+@USER+'#MA_NOPARTEAUX, MAESTRO'+@USER+'#MA_TIP_ENS, MAESTRO'+@USER+'#MA_NOPARTE, 
		MAESTRO'+@USER+'#TI_CODIGO, MAESTRO'+@USER+'#MA_NOMBRE, MAESTRO'+@USER+'#MA_NAME, MAESTRO'+@USER+'#ME_COM, MAESTRO'+@USER+'#PA_ORIGEN, MAESTRO'+@USER+'#PA_PROCEDE, 
		(select MA_CODIGO from maestro where ma_inv_gen=''g'' and ma_noparte=''rev''), MAESTRO'+@USER+'#AR_IMPMX, MAESTRO'+@USER+'#AR_EXPMX, MAESTRO'+@USER+'#AR_IMPFO, MAESTRO'+@USER+'#AR_EXPFO, MAESTRO'+@USER+'#MA_DEF_TIP, 
		MAESTRO'+@USER+'#SE_CODIGO, MAESTRO'+@USER+'#MA_PESO_LB, MAESTRO'+@USER+'#MA_TIEMPOENSMIN, MAESTRO'+@USER+'#CC_CODIGO
		FROM TEMPIMPORT141_'+@USER+'
		WHERE MAESTRO'+@USER+'#MA_NOPARTE NOT IN (SELECT MA_NOPARTE FROM MAESTRO WHERE MA_INV_GEN=''I'')')


		INSERT INTO MAESTRO(MA_CODIGO, MA_EXPENS ,MA_INV_GEN ,MA_NOPARTEAUX ,MA_TIP_ENS ,MA_NOPARTE ,TI_CODIGO ,MA_NOMBRE ,
			MA_NAME ,ME_COM ,PA_ORIGEN ,PA_PROCEDE ,MA_GENERICO ,AR_IMPMX ,AR_EXPMX ,AR_IMPFO ,AR_EXPFO ,MA_DEF_TIP ,SE_CODIGO ,
			MA_PESO_LB ,MA_TIEMPOENSMIN ,CC_CODIGO, MA_ULTIMAMODIF)

		SELECT MA_CODIGO, MA_EXPENS ,MA_INV_GEN ,MA_NOPARTEAUX ,MA_TIP_ENS ,MA_NOPARTE ,TI_CODIGO ,MA_NOMBRE ,
			MA_NAME ,ME_COM ,PA_ORIGEN ,PA_PROCEDE ,MA_GENERICO ,AR_IMPMX ,AR_EXPMX ,AR_IMPFO ,AR_EXPFO ,MA_DEF_TIP ,SE_CODIGO ,
			MA_PESO_LB ,MA_TIEMPOENSMIN ,CC_CODIGO, GETDATE()
		FROM TempImportMAESTRO


		declare @maximo int

		select @maximo= max(MA_CODIGO) from MAESTRO

		if exists(select * from maestrorefer) and (select isnull(max(ma_codigo),0) from maestrorefer)>@maximo
		select @maximo= isnull(max(MA_CODIGO),0) from MAESTROREFER

		update consecutivo
		set cv_codigo =  @maximo + 1
		where cv_tipo = 'MA'

		/* ============ ANEXO24 ===========*/

exec('		INSERT INTO ANEXO24(MA_CODIGO)
		SELECT MAESTRO.MA_CODIGO	                  
 		  FROM MAESTRO INNER JOIN
		                      TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE
		  WHERE (MAESTRO.MA_INV_GEN = ''I'') and MAESTRO'+@USER+'#MA_TIP_ENS=''A'' AND MAESTRO.MA_CODIGO NOT IN (SELECT MA_CODIGO FROM ANEXO24)')

		
exec('         UPDATE ANEXO24
		  SET MA_NOMBREFIS=MAESTRO'+@USER+'#MA_NOMBRE, 
			MA_NAMEFIS=MAESTRO'+@USER+'#MA_NAME, 
			PA_ORIGENFIS=MAESTRO'+@USER+'#PA_ORIGEN, 
			AR_EXPMXFIS=MAESTRO'+@USER+'#AR_EXPMX, 
			AR_IMPFOFIS=MAESTRO'+@USER+'#AR_IMPFO
 		  FROM MAESTRO INNER JOIN
		                      TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE
			INNER JOIN ANEXO24 ON MAESTRO.MA_CODIGO=ANEXO24.MA_CODIGO
		  WHERE (MAESTRO.MA_INV_GEN = ''I'') and MAESTRO'+@USER+'#MA_TIP_ENS=''A''')






		/* ============ MARESTROCATEG ===========*/

/*
		DELETE FROM MAESTROCATEG WHERE MA_CODIGO IN
		(SELECT MAESTRO.MA_CODIGO
		FROM TEMPIMPORT141_'+@USER+' INNER JOIN
		     MAESTRO ON TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE = MAESTRO.MA_NOPARTE
		WHERE MAESTROCATEG'+@USER+'#CPE_CODIGO IS NOT NULL
                AND MAESTRO.TI_CODIGO=14
		GROUP BY MAESTRO.MA_CODIGO)



		INSERT INTO MAESTROCATEG (MA_CODIGO,CPE_CODIGO )
		SELECT MAESTRO.MA_CODIGO, MAESTROCATEG'+@USER+'#CPE_CODIGO
		FROM TEMPIMPORT141_'+@USER+' INNER JOIN
		     MAESTRO ON TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE = MAESTRO.MA_NOPARTE
		WHERE CONVERT(VARCHAR(150),MAESTRO.MA_CODIGO)+'-'+CONVERT(VARCHAR(150),MAESTROCATEG'+@USER+'#CPE_CODIGO)
		NOT IN (SELECT CONVERT(VARCHAR(150),MA_CODIGO)+'-'+CONVERT(VARCHAR(150),CPE_CODIGO) FROM MAESTROCATEG)
*/

		/* ============ MARESTRODEF ===========*/

		exec Sp_GeneraTablaTemp 'MAESTRODEF'


exec('		UPDATE MAESTRODEF
		SET  MA_DEFTXT1= TEMPIMPORT141_'+@USER+'.MAESTRODEF'+@USER+'#MA_DEFTXT1, 
		     MA_DEFTXT2=TEMPIMPORT141_'+@USER+'.MAESTRODEF'+@USER+'#MA_DEFTXT2, 
		     MA_DEFNO1=TEMPIMPORT141_'+@USER+'.MAESTRODEF'+@USER+'#MA_DEFNO1, 
		     MA_DEFNO2=TEMPIMPORT141_'+@USER+'.MAESTRODEF'+@USER+'#MA_DEFNO2, 
		     MA_DEFBOL1=TEMPIMPORT141_'+@USER+'.MAESTRODEF'+@USER+'#MA_DEFBOL1, 
		     MA_DEFBOL2=TEMPIMPORT141_'+@USER+'.MAESTRODEF'+@USER+'#MA_DEFBOL2, 
                     MA_DEFDATE1=TEMPIMPORT141_'+@USER+'.MAESTRODEF'+@USER+'#MA_DEFDATE1, 
		     MA_DEFDATE2=TEMPIMPORT141_'+@USER+'.MAESTRODEF'+@USER+'#MA_DEFDATE2,
		     MA_DEFDATE3=TEMPIMPORT141_'+@USER+'.MAESTRODEF'+@USER+'#MA_DEFDATE3
		FROM         TEMPIMPORT141_'+@USER+' INNER JOIN
		                      MAESTRO ON TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE = MAESTRO.MA_NOPARTE INNER JOIN
		                      MAESTRODEF ON MAESTRO.MA_CODIGO = MAESTRODEF.MA_CODIGO')



exec('		insert into TempImportMAESTRODEF (MA_CODIGO,MA_DEFTXT1 ,MA_DEFTXT2 ,MA_DEFBOL1 ,MA_DEFBOL2 ,MA_DEFDATE1 ,MA_DEFDATE2, MA_DEFDATE3, MA_DEFNO1 ,MA_DEFNO2 )
		SELECT MAESTRO.MA_CODIGO, MAESTRODEF'+@USER+'#MA_DEFTXT1 ,MAESTRODEF'+@USER+'#MA_DEFTXT2, MAESTRODEF'+@USER+'#MA_DEFBOL1 ,
		MAESTRODEF'+@USER+'#MA_DEFBOL2 ,MAESTRODEF'+@USER+'#MA_DEFDATE1, MAESTRODEF'+@USER+'#MA_DEFDATE2, MAESTRODEF'+@USER+'#MA_DEFDATE3,
		MAESTRODEF'+@USER+'#MA_DEFNO1, MAESTRODEF'+@USER+'#MA_DEFNO2
		FROM TEMPIMPORT141_'+@USER+' INNER JOIN
		     MAESTRO ON TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE = MAESTRO.MA_NOPARTE
		WHERE MAESTRO.MA_CODIGO NOT IN (SELECT M1.MA_CODIGO FROM MAESTRODEF M1)')


		INSERT INTO MAESTRODEF(MAD_CODIGO, MA_CODIGO,MA_DEFTXT1 ,MA_DEFTXT2 ,MA_DEFBOL1 ,MA_DEFBOL2 ,MA_DEFDATE1 ,MA_DEFDATE2, MA_DEFDATE3, MA_DEFNO1 ,MA_DEFNO2)
		SELECT MAD_CODIGO, MA_CODIGO,MA_DEFTXT1 ,MA_DEFTXT2 ,MA_DEFBOL1 ,MA_DEFBOL2 ,MA_DEFDATE1 ,MA_DEFDATE2, MA_DEFDATE3, MA_DEFNO1 ,MA_DEFNO2
		FROM TempImportMAESTRODEF


		update consecutivo
		set cv_codigo =  isnull((select max(MAD_CODIGO) from MAESTRODEF),0) + 1
		where cv_tipo = 'MAD'


		/* ============ MARESTROCOST ===========*/

  	        exec SP_CREATABLALOG 41
  	        
exec('	    insert into sysusrlog41 (user_id, mov_id, referencia, frmtag, fechahora) 
		SELECT     @USER, 2, ''Act. Imp. Datos, No. Parte: ''+MAESTRO.MA_NOPARTE+'', Costo Unitario: ''+convert(varchar(50),MAESTROCOST.MA_COSTO), 41, getdate()
		FROM         MAESTRO INNER JOIN
		                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO INNER JOIN
		                      TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE AND 
		                      MAESTROCOST.TCO_CODIGO = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#TCO_CODIGO AND 
		                      MAESTROCOST.SPI_CODIGO = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#SPI_CODIGO ')


exec('		UPDATE MAESTROCOST
		SET     MAESTROCOST.MA_COSTO= TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#MA_COSTO,
			MAESTROCOST.MA_GRAV_MO= TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#MA_GRAV_MO
		FROM         MAESTRO INNER JOIN
		                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO INNER JOIN
		                      TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE AND 
		                      MAESTROCOST.TCO_CODIGO = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#TCO_CODIGO AND 
		                      MAESTROCOST.SPI_CODIGO = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#SPI_CODIGO ')


exec('           INSERT INTO MAESTROCOST (MA_CODIGO,SPI_CODIGO ,TCO_CODIGO ,MA_PERINI ,MA_COSTO, MA_GRAV_MO ) 
		   SELECT MAESTRO.MA_CODIGO, MAESTROCOST'+@USER+'#SPI_CODIGO, MAESTROCOST'+@USER+'#TCO_CODIGO, MIN(MAESTROCOST'+@USER+'#MA_PERINI), MAX(MAESTROCOST'+@USER+'#MA_COSTO), max(MAESTROCOST'+@USER+'#MA_GRAV_MO)
		   FROM TEMPIMPORT141_'+@USER+' INNER JOIN
		        MAESTRO ON TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE = MAESTRO.MA_NOPARTE
		   WHERE convert(varchar(150),MAESTRO.MA_CODIGO)+ convert(varchar(150),MAESTROCOST'+@USER+'#SPI_CODIGO)+convert(varchar(150),MAESTROCOST'+@USER+'#TCO_CODIGO) not in
			(select convert(varchar(150),maestrocost.MA_CODIGO)+ convert(varchar(150),maestrocost.SPI_CODIGO)+convert(varchar(150),maestrocost.TCO_CODIGO)
			from maestrocost where maestrocost.ma_codigo=MAESTRO.MA_CODIGO)
		   GROUP BY MAESTRO.MA_CODIGO, MAESTROCOST'+@USER+'#SPI_CODIGO, MAESTROCOST'+@USER+'#TCO_CODIGO')
		


/*                  UPDATE MAESTROCOST 
		  SET MAESTROCOST.MA_PERFIN =convert(varchar(11),getdate()-1,101) 
                  WHERE MAESTROCOST.MAC_CODIGO in (SELECT MAESTROCOST.MAC_CODIGO
						FROM TEMPIMPORT141_'+@USER+' INNER JOIN
						                      MAESTRO ON TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE = MAESTRO.MA_NOPARTE INNER JOIN
						                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO AND 
						                      TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#TCO_CODIGO = MAESTROCOST.TCO_CODIGO AND 
						                      TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#SPI_CODIGO = MAESTROCOST.SPI_CODIGO
						GROUP BY MAESTROCOST.MAC_CODIGO)


		UPDATE MAESTROCOST
		SET     MAESTROCOST.MA_COSTO= TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#MA_COSTO,
			MAESTROCOST.MA_GRAV_MO= TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#MA_GRAV_MO
		FROM         MAESTRO INNER JOIN
		                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO INNER JOIN
		                      TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE AND 
		                      MAESTROCOST.TCO_CODIGO = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#TCO_CODIGO AND 
		                      MAESTROCOST.MA_PERINI = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#MA_PERINI AND 
		                      MAESTROCOST.SPI_CODIGO = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#SPI_CODIGO 


                   INSERT INTO MAESTROCOST (MA_CODIGO,SPI_CODIGO ,TCO_CODIGO ,MA_PERINI ,MA_COSTO, MA_GRAV_MO ) 
		   SELECT MAESTRO.MA_CODIGO, MAESTROCOST'+@USER+'#SPI_CODIGO, MAESTROCOST'+@USER+'#TCO_CODIGO, MAESTROCOST'+@USER+'#MA_PERINI, MAX(MAESTROCOST'+@USER+'#MA_COSTO), max(MAESTROCOST'+@USER+'#MA_GRAV_MO)
		   FROM TEMPIMPORT141_'+@USER+' INNER JOIN
		        MAESTRO ON TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE = MAESTRO.MA_NOPARTE
		   WHERE convert(varchar(150),MAESTRO.MA_CODIGO)+ convert(varchar(150),MAESTROCOST'+@USER+'#SPI_CODIGO)+convert(varchar(150),MAESTROCOST'+@USER+'#TCO_CODIGO)+convert(varchar(150),MAESTROCOST'+@USER+'#MA_PERINI) not in
			(select convert(varchar(150),maestrocost.MA_CODIGO)+ convert(varchar(150),maestrocost.SPI_CODIGO)+convert(varchar(150),maestrocost.TCO_CODIGO)+convert(varchar(150),maestrocost.MA_PERINI) 
			from maestrocost where maestrocost.ma_codigo=MAESTRO.MA_CODIGO)
		   GROUP BY MAESTRO.MA_CODIGO, MAESTROCOST'+@USER+'#SPI_CODIGO, MAESTROCOST'+@USER+'#TCO_CODIGO, MAESTROCOST'+@USER+'#MA_PERINI



              update MAESTROCOST 
	      set MA_GRAV_MO = round(CENTROCOSTO$2453_1.CC_MO*Col_25,6)
              FROM         dbo.TEMPIMPORT141_'+@USER+' INNER JOIN
                      dbo.MAESTRO ON dbo.TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE = dbo.MAESTRO.MA_NOPARTE RIGHT OUTER JOIN
                      dbo.MAESTROCOST ON dbo.TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#TCO_CODIGO = dbo.MAESTROCOST.TCO_CODIGO AND 
                      dbo.TEMPIMPORT141_'+@USER+'.NAFTA'+@USER+'#SPI_CODIGO = dbo.MAESTROCOST.SPI_CODIGO AND 
                      dbo.TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#MA_PERINI = dbo.MAESTROCOST.MA_PERINI AND 
                      dbo.MAESTRO.MA_CODIGO = dbo.MAESTROCOST.MA_CODIGO LEFT OUTER JOIN
                      dbo.CENTROCOSTO CENTROCOSTO$2453_1 ON dbo.MAESTRO.CC_CODIGO = CENTROCOSTO$2453_1.CC_CODIGO
		WHERE CENTROCOSTO$2453_1.CC_MO*Col_25 IS NOT NULL


              update MAESTROCOST 
	      set MA_COSTO = round(( MAESTROCOST.MA_GRAV_EMP+MAESTROCOST.MA_NG_EMP +MAESTROCOST.MA_GRAV_GI_MX +MAESTROCOST.MA_GRAV_GI+MAESTROCOST.MA_GRAV_MO+MAESTROCOST.MA_GRAV_ADD + MAESTROCOST.MA_GRAV_MP +MAESTROCOST.MA_NG_MP ),6)
	      FROM MAESTRO INNER JOIN
                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO INNER JOIN
                      TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE AND 
                      MAESTROCOST.TCO_CODIGO = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#TCO_CODIGO AND 
                      MAESTROCOST.MA_PERINI = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#MA_PERINI AND 
                      MAESTROCOST.SPI_CODIGO = TEMPIMPORT141_'+@USER+'.MAESTROCOST'+@USER+'#SPI_CODIGO 
*/


		/* ============ NAFTA ===========*/
		exec Sp_GeneraTablaTemp 'NAFTA'

exec('	        INSERT INTO TempImportNAFTA (MA_CODIGO,SPI_CODIGO ,PA_CLASE ,NFT_CRITERIO ,NFT_FABRICA ,NFT_PERINI ,NFT_PERFIN ,NFT_NETCOST ,
			NFT_OTRASINST, NFT_CALIFICO, NFT_NOPARTE, NFT_NOPARTEAUX) 
		SELECT MAESTRO.MA_CODIGO, NAFTA'+@USER+'#SPI_CODIGO, NAFTA'+@USER+'#PA_CLASE, NAFTA'+@USER+'#NFT_CRITERIO, NAFTA'+@USER+'#NFT_FABRICA, NAFTA'+@USER+'#NFT_PERINI, 
		  NAFTA'+@USER+'#NFT_PERFIN, NAFTA'+@USER+'#NFT_NETCOST, NAFTA'+@USER+'#NFT_OTRASINST, ''S'', TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE, TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTEAUX
		FROM MAESTRO INNER JOIN
		                    TEMPIMPORT141_'+@USER+' ON MAESTRO.MA_NOPARTE = TEMPIMPORT141_'+@USER+'.MAESTRO'+@USER+'#MA_NOPARTE
		WHERE CONVERT(VARCHAR(150),NAFTA'+@USER+'#NFT_PERINI)+ CONVERT(VARCHAR(150),NAFTA'+@USER+'#SPI_CODIGO)
			NOT IN (SELECT CONVERT(VARCHAR(150),NAFTA.NFT_PERINI)+ CONVERT(VARCHAR(150),NAFTA.SPI_CODIGO)
				FROM NAFTA WHERE NAFTA.MA_CODIGO=MAESTRO.MA_CODIGO)
		AND (MAESTRO.MA_INV_GEN = ''I'') and NAFTA'+@USER+'#SPI_CODIGO=22')
		


		INSERT INTO NAFTA(NFT_CODIGO,MA_CODIGO,SPI_CODIGO ,PA_CLASE ,NFT_CRITERIO ,NFT_FABRICA ,NFT_PERINI ,NFT_PERFIN ,NFT_NETCOST ,
		NFT_OTRASINST, NFT_CALIFICO, NFT_NOPARTE, NFT_NOPARTEAUX)
		SELECT NFT_CODIGO,MA_CODIGO,SPI_CODIGO ,PA_CLASE ,NFT_CRITERIO ,NFT_FABRICA ,NFT_PERINI ,NFT_PERFIN ,NFT_NETCOST ,
		NFT_OTRASINST, NFT_CALIFICO, NFT_NOPARTE, NFT_NOPARTEAUX
		FROM TempImportNAFTA


		update consecutivo
		set cv_codigo =  isnull((select max(NFT_CODIGO) from NAFTA),0) + 1
		where cv_tipo = 'NFT'



UPDATE MAESTRO
SET     MAESTRO.MA_NOMBRE= MAESTRO_1.MA_NOMBRE
FROM         MAESTRO INNER JOIN
                      MAESTRO MAESTRO_1 ON MAESTRO.MA_NAME = MAESTRO_1.MA_NAME AND MAESTRO.AR_IMPMX = MAESTRO_1.AR_IMPMX
WHERE     (MAESTRO.MA_NOMBRE LIKE '%SIN PERMISO%') AND (NOT (MAESTRO_1.MA_NOMBRE LIKE '%SIN PERMISO%') AND 
                      MAESTRO_1.MA_NOMBRE <> '')


UPDATE ANEXO24
SET     ANEXO24.MA_NOMBREFIS= MAESTRO_1.MA_NOMBRE
FROM         MAESTRO INNER JOIN
                      MAESTRO MAESTRO_1 ON MAESTRO.AR_IMPMX = MAESTRO_1.AR_IMPMX INNER JOIN
                      ANEXO24 ON MAESTRO.MA_CODIGO = ANEXO24.MA_CODIGO AND MAESTRO_1.MA_NAME = ANEXO24.MA_NAMEFIS
WHERE     (NOT (MAESTRO_1.MA_NOMBRE LIKE '%SIN PERMISO%')) AND (MAESTRO_1.MA_NOMBRE <> '') AND 
                      (ANEXO24.MA_NOMBREFIS LIKE '%SIN PERMISO%')


		IF (SELECT AR_RETORNOUSA FROM CONFIGURACION) IS NOT NULL
		UPDATE MAESTRO
		SET MAESTRO.AR_IMPFOUSA=(SELECT AR_RETORNOUSA FROM CONFIGURACION)
		WHERE MA_CODIGO IN
		(SELECT     MAESTRO.MA_CODIGO
		FROM         MAESTRO INNER JOIN
		                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO INNER JOIN
		                      ARANCEL ON MAESTRO.AR_IMPFOUSA = ARANCEL.AR_CODIGO
		WHERE     (NOT (ARANCEL.AR_FRACCION LIKE '980%')) AND (CONFIGURATIPO.CFT_TIPO <> 'S' AND
		                      CONFIGURATIPO.CFT_TIPO <> 'P'))


		IF (SELECT AR_INSERTO FROM CONFIGURACION) IS NOT NULL
		UPDATE MAESTRO
		SET MAESTRO.AR_IMPFOUSA=(SELECT AR_INSERTO FROM CONFIGURACION)
		WHERE MA_CODIGO IN
		(SELECT     MAESTRO.MA_CODIGO
		FROM         MAESTRO INNER JOIN
		                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO INNER JOIN
		                      ARANCEL ON MAESTRO.AR_IMPFOUSA = ARANCEL.AR_CODIGO
		WHERE     NOT (ARANCEL.AR_FRACCION LIKE '980%') AND ((CONFIGURATIPO.CFT_TIPO = 'S' OR
		                      CONFIGURATIPO.CFT_TIPO = 'P') AND MAESTRO.MA_TIP_ENS<>'A' AND MAESTRO.MA_TIP_ENS<>'C'))


		UPDATE MAESTROCOST
		SET     MA_COSTO= ROUND(MA_GRAV_MP + MA_GRAV_ADD + MA_GRAV_EMP + MA_GRAV_GI + MA_GRAV_GI_MX + MA_GRAV_MO + MA_NG_MP +
		                      MA_NG_ADD + MA_NG_EMP,6)
		FROM         MAESTROCOST
		WHERE TCO_CODIGO=1 AND
		MA_COSTO<> ROUND(MA_GRAV_MP + MA_GRAV_ADD + MA_GRAV_EMP + MA_GRAV_GI + MA_GRAV_GI_MX + MA_GRAV_MO + MA_NG_MP +
		                      MA_NG_ADD + MA_NG_EMP,6)


		UPDATE MAESTRO
		SET     MA_DISCHARGE='N'
		WHERE MA_TIP_ENS='F' AND (MA_DISCHARGE='S' OR MA_DISCHARGE IS NULL)












GO
