SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO







CREATE PROCEDURE [dbo].[CopiaCertOrigen] (@BDOrigen varchar(50), @BDDestino varchar(50))    as




		exec CopiaClientes @BDOrigen, @BDDestino

	IF  NOT EXISTS (SELECT name 
		   FROM  [tempdb].dbo.sysobjects 
		   WHERE  (name = '##CERTORIGMP' )
		   AND 	 ( type = 'U'))
	begin
		CREATE TABLE [##CERTORIGMP] (
			[CMP_CODIGO] [int] IDENTITY (1, 1) NOT NULL ,
			[CMP_IFECHA] [datetime] NOT NULL ,
			[CMP_VFECHA] [datetime] NOT NULL ,
			[PR_CODIGO] [int] NOT NULL CONSTRAINT [DF_CERTORIGMP_PR_CODIGO] DEFAULT (1),
			[DI_PROD] [int] NULL ,
			[CL_IMP] [int] NOT NULL ,
			[DI_IMP] [int] NULL ,
			[SPI_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_CERTORIGMP_SPI_CODIGO] DEFAULT (22),
			[CMP_TIPO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CERTORIGMP_CMP_TIPO] DEFAULT ('P'),
			[US_CODIGO] [smallint] NULL ,
			[CMP_FOLIO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
			[CMP_FECHA] [datetime] NULL ,
			[CL_EXP] [int] NULL ,
			[DI_EXP] [int] NULL ,
			[CMP_AFFIDAVIT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CERTORIGMP_CMP_AFFIDAVIT] DEFAULT ('N'),
			[CMP_DECLARAPROD] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CERTORIGMP_CMP_DECLARAPROD] DEFAULT ('N'),
			[CMP_OBSERVA] [varchar] (1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[CMP_FECHATRANS] [datetime] NULL ,
			[CMP_MODIFICABLE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CERTORIGMP_CMP_MODIFICABLE] DEFAULT ('S'),
			[CMP_ESTATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CERTORIGMP_CMP_ESTATUS] DEFAULT ('V'),
			CONSTRAINT [PK_CERTORIGMP] PRIMARY KEY  NONCLUSTERED 
			(
				[CMP_IFECHA],
				[CMP_VFECHA],
				[PR_CODIGO],
				[CL_IMP],
				[CMP_TIPO],
				[CMP_FOLIO]
			)  ON [PRIMARY] ,
			CONSTRAINT [IX_CERTORIGMP] UNIQUE  NONCLUSTERED 
			(
				[CMP_CODIGO]
			)  ON [PRIMARY] 
		) ON [PRIMARY]
	end


	DECLARE @MAXIMO INT

	SELECT @MAXIMO=ISNULL(MAX(CMP_CODIGO),0)+1 FROM CERTORIGMP
	
	DBCC CHECKIDENT ([##CERTORIGMP], RESEED, @MAXIMO)


	EXEC('INSERT INTO ##CERTORIGMP(CMP_IFECHA, CMP_VFECHA, SPI_CODIGO, CMP_TIPO, CMP_FOLIO, 
	                      CMP_FECHA, CMP_AFFIDAVIT, CMP_DECLARAPROD, CMP_OBSERVA, 
	                      CMP_FECHATRANS, CMP_MODIFICABLE, CMP_ESTATUS, PR_CODIGO, CL_IMP, CL_EXP)
	
	SELECT     CERTORIGMP1.CMP_IFECHA, CERTORIGMP1.CMP_VFECHA, CERTORIGMP1.SPI_CODIGO, CERTORIGMP1.CMP_TIPO, CERTORIGMP1.CMP_FOLIO, 
	                      CERTORIGMP1.CMP_FECHA, CERTORIGMP1.CMP_AFFIDAVIT, CERTORIGMP1.CMP_DECLARAPROD, CERTORIGMP1.CMP_OBSERVA, 
	                      CERTORIGMP1.CMP_FECHATRANS, CERTORIGMP1.CMP_MODIFICABLE, CERTORIGMP1.CMP_ESTATUS,
		(SELECT CL_CODIGO FROM CLIENTE WHERE CL_RAZON=CLIENTE_1.CL_RAZON) AS PR_CODIGO,
		ISNULL((SELECT CL_CODIGO FROM CLIENTE WHERE CL_RAZON=CLIENTE_2.CL_RAZON),1) AS CL_IMP,
		(SELECT CL_CODIGO FROM CLIENTE WHERE CL_RAZON=CLIENTE_3.CL_RAZON) AS CL_EXP
	FROM         '+@BDOrigen+'.DBO.CLIENTE CLIENTE_1 INNER JOIN
	                      '+@BDOrigen+'.DBO.CERTORIGMP CERTORIGMP1 ON CLIENTE_1.CL_CODIGO = CERTORIGMP1.PR_CODIGO INNER JOIN
	                      '+@BDOrigen+'.DBO.CLIENTE CLIENTE_2 ON CERTORIGMP1.CL_IMP = CLIENTE_2.CL_CODIGO INNER JOIN
	                      '+@BDOrigen+'.DBO.CLIENTE CLIENTE_3 ON CERTORIGMP1.CL_EXP = CLIENTE_3.CL_CODIGO
	WHERE     (CERTORIGMP1.CMP_TIPO <> ''P'') AND
	CERTORIGMP1.CMP_FOLIO NOT IN (SELECT CMP_FOLIO FROM CERTORIGMP)')


	update consecutivo
	set cv_codigo =  isnull((select max(CMP_CODIGO) from CERTORIGMP),0) + 1
	where cv_tipo = 'CMP'



	INSERT INTO CERTORIGMP(CMP_CODIGO, CMP_IFECHA, CMP_VFECHA, SPI_CODIGO, CMP_TIPO, CMP_FOLIO, 
	                      CMP_FECHA, CMP_AFFIDAVIT, CMP_DECLARAPROD, CMP_OBSERVA, 
	                      CMP_FECHATRANS, CMP_MODIFICABLE, CMP_ESTATUS, PR_CODIGO, CL_IMP, CL_EXP)

	SELECT CMP_CODIGO, CMP_IFECHA, CMP_VFECHA, SPI_CODIGO, CMP_TIPO, CMP_FOLIO, 
	                      CMP_FECHA, CMP_AFFIDAVIT, CMP_DECLARAPROD, CMP_OBSERVA, 
	                      CMP_FECHATRANS, CMP_MODIFICABLE, CMP_ESTATUS, PR_CODIGO, CL_IMP, CL_EXP
	FROM ##CERTORIGMP

	EXEC('DELETE FROM CERTORIGMPDET WHERE CMP_CODIGO IN (SELECT CMP_CODIGO FROM CERTORIGMP WHERE CMP_FOLIO IN (SELECT CERTORIGMP1.CMP_FOLIO FROM '+@BDOrigen+'.DBO.CERTORIGMP CERTORIGMP1))')
	
	
	
	EXEC('INSERT INTO CERTORIGMPDET (CMP_CODIGO, MA_CODIGO, CMP_CLASE, CMP_FABRICA, CMP_CRITERIO, CMP_NETCOST, CMP_OTRASINST, CMP_CANT, 
	                      ME_CODIGO, CMP_FACTURA, PA_CLASE, CMP_FRACCION, CMP_FRACCIONALT, CMP_DESCRIP)
	
	SELECT     CERTORIGMP_1.CMP_CODIGO, MAESTRO_1.MA_CODIGO, MAX(CERTORIGMPDET.CMP_CLASE), MAX(CERTORIGMPDET.CMP_FABRICA), 
	                      MAX(CERTORIGMPDET.CMP_CRITERIO), MAX(CERTORIGMPDET.CMP_NETCOST), MAX(CERTORIGMPDET.CMP_OTRASINST), MAX(CERTORIGMPDET.CMP_CANT), 
	                      MAX(CERTORIGMPDET.ME_CODIGO), MAX(CERTORIGMPDET.CMP_FACTURA), CERTORIGMPDET.PA_CLASE, MAX(CERTORIGMPDET.CMP_FRACCION), 
	                      MAX(CERTORIGMPDET.CMP_FRACCIONALT), MAX(CERTORIGMPDET.CMP_DESCRIP)
	FROM         '+@BDOrigen+'.DBO.CERTORIGMPDET CERTORIGMPDET INNER JOIN
	                      '+@BDOrigen+'.DBO.CERTORIGMP CERTORIGMP ON CERTORIGMPDET.CMP_CODIGO = CERTORIGMP.CMP_CODIGO INNER JOIN
	                      CERTORIGMP CERTORIGMP_1 ON CERTORIGMP.CMP_FOLIO = CERTORIGMP_1.CMP_FOLIO INNER JOIN
	                      MAESTRO ON CERTORIGMPDET.MA_CODIGO = MAESTRO.MA_CODIGO INNER JOIN
	                      MAESTRO MAESTRO_1 ON MAESTRO.MA_NOPARTE = MAESTRO_1.MA_NOPARTE AND MAESTRO.MA_INV_GEN = MAESTRO_1.MA_INV_GEN
	GROUP BY CERTORIGMP_1.CMP_CODIGO, MAESTRO_1.MA_CODIGO, CERTORIGMPDET.PA_CLASE')
	
	
	DROP TABLE ##CERTORIGMP

GO
