SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE dbo.SP_DescargaCancelaOrdTrabajo (@Pro_codigo Int)  as

SET NOCOUNT ON 
DECLARE @OTD_INDICED int, @OT_CODIGO int, @OTDSALDO decimal(38,6), @LIP_CANTDESC decimal(38,6), @OTD_SIZELOTE decimal(38,6), @PROD_INDICED int,
@PRODSALDO decimal(38,6), @OTDP_INDICEP INT, @OTDPSALDO decimal(38,6), @OTDP_SIZELOTE decimal(38,6)
	

	DECLARE curOrdTrabajoCancel CURSOR FOR
		SELECT     TOP 100 PERCENT dbo.PRODUCLIGA.OTD_INDICED, dbo.ORDTRABAJODET.OT_CODIGO, dbo.PRODUCLIGA.LIP_CANTDESC,
		dbo.PRODUCLIGA.PROD_INDICED, dbo.PRODUCLIGA.OTDP_INDICEP
		FROM         dbo.PRODUCLIGA INNER JOIN
		                      dbo.ORDTRABAJODET ON dbo.PRODUCLIGA.OTD_INDICED = dbo.ORDTRABAJODET.OTD_INDICED INNER JOIN
		                      dbo.PRODUCDET ON dbo.PRODUCLIGA.PROD_INDICED = dbo.PRODUCDET.PROD_INDICED
		WHERE     (dbo.PRODUCDET.PRO_CODIGO = @Pro_codigo)
	OPEN curOrdTrabajoCancel
	FETCH NEXT FROM curOrdTrabajoCancel INTO @OTD_INDICED, @OT_CODIGO, @LIP_CANTDESC, @PROD_INDICED, @OTDP_INDICEP
		WHILE (@@fetch_status <> -1)
		BEGIN  --1

		if @OT_CODIGO is not null and @OT_CODIGO<>-1
		begin

			
						SELECT @PRODSALDO = isnull(PROD_CANTPEND,0) FROM PRODUCDET 
						WHERE PROD_INDICED = @PROD_INDICED
	
						SELECT @OTDSALDO = isnull(OTD_SALDO,0), @OTD_SIZELOTE = OTD_SIZELOTE 
						FROM ORDTRABAJODET WHERE OTD_INDICED = @OTD_INDICED
					
		
						UPDATE ORDTRABAJODET 
						SET OTD_SALDO = (@OTDSALDO + @LIP_CANTDESC) 
						WHERE OTD_INDICED = @OTD_INDICED
			
					
						IF (@OTDSALDO = @OTD_SIZELOTE )
						UPDATE ORDTRABAJODET 
						SET OTD_ENUSO = 'N' 
						WHERE OTD_INDICED = @OTD_INDICED
		
		
						IF @OTDP_INDICEP<>0	
						begin
							SELECT @OTDPSALDO = isnull(OTDP_SALDO,0), @OTDP_SIZELOTE = OTDP_CANT 
							FROM ORDTRABAJODETENTPARCIAL WHERE OTDP_INDICEP = @OTDP_INDICEP
					
		
							UPDATE ORDTRABAJODETENTPARCIAL
							SET OTDP_SALDO = (@OTDPSALDO + @LIP_CANTDESC) 
							WHERE OTDP_INDICEP = @OTDP_INDICEP
				
						
							IF (@OTDPSALDO = @OTDP_SIZELOTE )
							UPDATE ORDTRABAJODETENTPARCIAL
							SET OTDP_ENUSO = 'N' 
							WHERE OTDP_INDICEP = @OTDP_INDICEP
		
						end
		
						UPDATE PRODUCDET 
						SET PROD_CANTPEND = (@PRODSALDO + @LIP_CANTDESC) 
						WHERE PROD_INDICED = @PROD_INDICED

		end
	FETCH NEXT FROM curOrdTrabajoCancel INTO @OTD_INDICED, @OT_CODIGO, @LIP_CANTDESC, @PROD_INDICED, @OTDP_INDICEP
	end


	CLOSE curOrdTrabajoCancel
	DEALLOCATE curOrdTrabajoCancel


	delete from producliga where prod_indiced in 
	(select prod_indiced from producdet where pro_codigo=@pro_codigo)

	exec SP_ACTUALIZAESTATUSPRODUC @pro_codigo



























GO
