SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE PROCEDURE [dbo].[SP_CreaTEMPBOM_UNNIVEL]   as

	
		if not exists (select * from dbo.sysobjects where name='TEMPBOM_UNNIVEL')
	begin
		CREATE TABLE [dbo].[TEMPBOM_UNNIVEL] (
			[CONSECUTIVO] [int] IDENTITY (1, 1) NOT NULL ,
			[BST_PT] [int] NOT NULL ,
			[BST_PERTENECE] [int] NULL ,
			[BST_HIJO] [int] NOT NULL ,
			[BST_ENTRAVIGOR] [datetime] NULL ,
			[BST_INCORPOR] decimal(38,6) NOT NULL CONSTRAINT [DF_TEMPBOM_UNNIVEL_BST_INCORPOR] DEFAULT (1),
			[BST_INCORPORTOTAL] decimal(38,6) NOT NULL CONSTRAINT [DF_TEMPBOM_UNNIVEL_BST_INCORPORTOTAL] DEFAULT (1),
			[BST_DISCH] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_TEMPBOM_UNNIVEL_BST_DISCH] DEFAULT ('S'),
			[TI_CODIGO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[ME_CODIGO] [int] NULL ,
			[FACTCONV] decimal(28,14) NOT NULL CONSTRAINT [DF_TEMPBOM_UNNIVEL_FACTCONV] DEFAULT (1),
			[BST_PERINI] [datetime] NULL ,
			[BST_PERFIN] [datetime] NULL CONSTRAINT [DF_TEMPBOM_UNNIVEL_BST_PERFIN] DEFAULT ('01/01/9999'),
			[ME_GEN] [int] NULL ,
			[MA_TIP_ENS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[BST_NIVEL] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[BST_PTNOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[BST_HIJONOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[BST_PTNOMBRE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[BST_HIJONOMBRE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
		) ON [PRIMARY]
		
		ALTER TABLE [dbo].[TEMPBOM_UNNIVEL] ADD 
			CONSTRAINT [IX_TEMPBOM_UNNIVEL] UNIQUE  NONCLUSTERED 
			(
				[CONSECUTIVO]
			) WITH  FILLFACTOR = 90  ON [PRIMARY]
	end

GO
