SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_InsertaListaExpIncrementables] (@FE_codigo int)  as


		UPDATE FACTEXPINCREMENTA
	SET FEI_VALOR= (SELECT SUM(dbo.LISTAEXPINCREMENTA.LEI_VALOR) 
			FROM         dbo.LISTAEXPINCREMENTA INNER JOIN
			                      dbo.FACTEXPDET ON dbo.LISTAEXPINCREMENTA.LE_CODIGO = dbo.FACTEXPDET.LE_CODIGO
			WHERE dbo.LISTAEXPINCREMENTA.IC_CODIGO=FACTEXPINCREMENTA.IC_CODIGO 
			AND (dbo.FACTEXPDET.FE_CODIGO = FACTEXPINCREMENTA.FE_CODIGO))
	WHERE FACTEXPINCREMENTA.FE_CODIGO=@FE_codigo

	INSERT INTO FACTEXPINCREMENTA(FE_CODIGO, IC_CODIGO, FEI_VALOR)
	SELECT     dbo.FACTEXPDET.FE_CODIGO, dbo.LISTAEXPINCREMENTA.IC_CODIGO, SUM(dbo.LISTAEXPINCREMENTA.LEI_VALOR) 
	FROM         dbo.LISTAEXPINCREMENTA INNER JOIN
	                      dbo.FACTEXPDET ON dbo.LISTAEXPINCREMENTA.LE_CODIGO = dbo.FACTEXPDET.LE_CODIGO
	WHERE dbo.LISTAEXPINCREMENTA.IC_CODIGO NOT IN (SELECT IC_CODIGO FROM FACTEXPINCREMENTA WHERE FE_CODIGO=@FE_codigo)
	GROUP BY dbo.FACTEXPDET.FE_CODIGO, dbo.LISTAEXPINCREMENTA.IC_CODIGO
	HAVING      (dbo.FACTEXPDET.FE_CODIGO = @FE_codigo)


GO
