SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_temp_13019]   as

		UPDATE    PEDIMP
	SET              PI_FEC_ENTPED = PI_FEC_ENT
	WHERE     (PI_FEC_ENTPED IS NULL)


	UPDATE    FACTEXPDET
	SET              FED_PARTTYPE = 'R'
	WHERE     (FED_RETRABAJO = 'R') AND (FED_PARTTYPE <> 'R' OR
	                      FED_PARTTYPE IS NULL)


	UPDATE dbo.FACTEXPDET
	SET     dbo.FACTEXPDET.FED_PARTTYPE='A'
	FROM         dbo.FACTEXPDET INNER JOIN
	                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      dbo.TEMBARQUE ON dbo.FACTEXP.TQ_CODIGO = dbo.TEMBARQUE.TQ_CODIGO
	WHERE     (dbo.FACTEXPDET.FED_RETRABAJO = 'N') AND (dbo.FACTEXPDET.FED_PARTTYPE <> 'A' OR
	                      dbo.FACTEXPDET.FED_PARTTYPE IS NULL) AND (dbo.TEMBARQUE.TQ_NOMBRE <> 'DESPERDICIO')
		AND (dbo.FACTEXPDET.TI_CODIGO=14 OR dbo.FACTEXPDET.TI_CODIGO=16)


	UPDATE dbo.FACTEXPDET
	SET     dbo.FACTEXPDET.FED_PARTTYPE='S'
	FROM         dbo.FACTEXPDET INNER JOIN
	                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      dbo.TEMBARQUE ON dbo.FACTEXP.TQ_CODIGO = dbo.TEMBARQUE.TQ_CODIGO
	WHERE     (dbo.FACTEXPDET.FED_RETRABAJO = 'N') AND (dbo.FACTEXPDET.FED_PARTTYPE <> 'S' OR
	                      dbo.FACTEXPDET.FED_PARTTYPE IS NULL) AND (dbo.TEMBARQUE.TQ_NOMBRE = 'DESPERDICIO')

	UPDATE dbo.FACTEXPDET
	SET     dbo.FACTEXPDET.FED_PARTTYPE='U'
	FROM         dbo.FACTEXPDET INNER JOIN
	                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      dbo.TEMBARQUE ON dbo.FACTEXP.TQ_CODIGO = dbo.TEMBARQUE.TQ_CODIGO
	WHERE     (dbo.FACTEXPDET.FED_RETRABAJO = 'N') AND (dbo.FACTEXPDET.FED_PARTTYPE IS NULL)



























GO
