SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [SP_PROCDESCARGAS1] (@ERROR int OUTPUT) AS    begin tran UPDATE FACTEXP SET FE_SEL='N',FE_AUXDESC='N' where FE_SEL='S' or FE_AUXDESC='S'   commit tran Return @@Error

GO
