SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
































CREATE PROCEDURE [dbo].[SP_temp_13030]   as


		INSERT INTO MAESTROCATEG(MA_CODIGO, CPE_CODIGO, EQ_CANT)
	
	SELECT     MA_CODIGO, MA_GENERICO, EQ_GEN
	FROM         MAESTRO
	WHERE MA_GENERICO>0
	AND CONVERT(VARCHAR(50),MA_CODIGO)+ CONVERT(VARCHAR(50),MA_GENERICO) NOT IN (SELECT CONVERT(VARCHAR(50),MA_CODIGO)+ CONVERT(VARCHAR(50),CPE_CODIGO) FROM MAESTROCATEG)

	
	UPDATE CERTORIGMPDET
	SET     CERTORIGMPDET.AR_CODIGO= MAESTRO.AR_EXPMX, CERTORIGMPDET.AR_ALTER= MAESTRO.AR_IMPFO
	FROM         CERTORIGMPDET INNER JOIN
	                      MAESTRO ON CERTORIGMPDET.MA_CODIGO = MAESTRO.MA_CODIGO


	delete from configurapermisorel where ide_codigo=66


DECLARE @CL_MATRIZ INT
	

	INSERT INTO CLIENTEENTIDADES(TF_CODIGO, OM_TIPO)
	SELECT     TF_CODIGO, 'E'
	FROM         VTFACTURAENT
	WHERE CONVERT(VARCHAR(15),TF_CODIGO)+'E' NOT IN (SELECT CONVERT(VARCHAR(15),TF_CODIGO)+'E' FROM CLIENTEENTIDADES)
	
	
	
	INSERT INTO CLIENTEENTIDADES(TF_CODIGO, OM_TIPO)
	SELECT     TF_CODIGO, 'S'
	FROM         VTFACTURASAL
	WHERE CONVERT(VARCHAR(15),TF_CODIGO)+'S' NOT IN (SELECT CONVERT(VARCHAR(15),TF_CODIGO)+'S' FROM CLIENTEENTIDADES)
	

	
	SELECT @CL_MATRIZ=CL_MATRIZ FROM CLIENTE WHERE CL_EMPRESA='S'
	
	
	UPDATE CLIENTEENTIDADES
	SET     PR_CODIGO=@CL_MATRIZ, CL_PROD=@CL_MATRIZ, CL_VEND=@CL_MATRIZ, CL_EXP=@CL_MATRIZ, CL_EXPFIN=@CL_MATRIZ,
	CL_DESTINI=1, CL_DESTFIN=1, CL_COMP=1, CL_COMPFIN=1, CL_IMP=1
	WHERE     (OM_TIPO = 'E')
	
	
	UPDATE CLIENTEENTIDADES
	SET     PR_CODIGO=1, CL_PROD=1, CL_VEND=1, CL_EXP=1, CL_EXPFIN=1,
	CL_DESTINI=@CL_MATRIZ, CL_DESTFIN=@CL_MATRIZ, CL_COMP=@CL_MATRIZ, CL_COMPFIN=@CL_MATRIZ, CL_IMP=@CL_MATRIZ
	WHERE     (OM_TIPO = 'S')






























GO
