SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [SP_TEMPIMPORT1] AS
DECLARE @Col_2 varchar(8000),@Col_3 varchar(8000),@Col_4 varchar(8000),@Col_5 varchar(8000),@Col_6 varchar(8000),@Col_7 varchar(8000),@MAESTROCOST#MA_COSTO float,@MAESTRO#MA_INV_GEN char,@MAESTRO#MA_NOPARTEAUX varchar(8000),@MAESTROCOST#TCO_CODIGO smallint,@MAESTRO#MA_NOPARTE varchar(8000),@MAESTROCOST#MA_GRAV_MP float,@MAESTROCOST#MA_NG_MP float,@MAESTROCOST#MA_GRAV_EMP float,@MAESTROCOST#MA_NG_EMP float,@MAESTROCOST#MA_GRAV_ADD float,@MAESTROCOST#MA_GRAV_MO float
DECLARE @ACTUALIZA bit,@ANEXA bit,@CONSECUTIVO int,@CONSDET int,@CONSANEX int,@CONSCONT int
DECLARE @CAMPOSMASTER varchar(255),@temp_str varchar(20)
SELECT @ACTUALIZA=1
SELECT @ANEXA=0
DELETE FROM REGISTROSIMPORTADOS
-- Variables para campos de caratula
-- Variables para campos de detalle
-- Variables para campos de detalle
-- Variables para campos de detalle
-- Variables para campos de detalle
-- Variables para campos de detalle
-- Variables para campos de detalle
DECLARE CUR_TEMPIMPORT1 CURSOR FOR
SELECT MAX(Col_2),MAX(Col_3),MAX(Col_4),MAX(Col_5),MAX(Col_6),MAX(Col_7),MAESTRO0#MA_INV_GEN,MAESTRO0#MA_NOPARTEAUX,MAESTRO0#MA_NOPARTE FROM TEMPIMPORT1 GROUP BY MAESTRO0#MA_INV_GEN,MAESTRO0#MA_NOPARTEAUX,MAESTRO0#MA_NOPARTE
OPEN CUR_TEMPIMPORT1
FETCH NEXT FROM CUR_TEMPIMPORT1 INTO @Col_2 ,@Col_3 ,@Col_4 ,@Col_5 ,@Col_6 ,@Col_7 ,@MAESTRO#MA_INV_GEN ,@MAESTRO#MA_NOPARTEAUX ,@MAESTRO#MA_NOPARTE 
WHILE (@@FETCH_STATUS = 0)
BEGIN
   IF EXISTS(SELECT MA_CODIGO FROM MAESTRO WHERE MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX)
  BEGIN
          IF @ACTUALIZA=1
          BEGIN
                  UPDATE MAESTRO SET MA_ULTIMAMODIF=GETDATE() WHERE MA_CODIGO=@CONSECUTIVO 
                  SELECT @CONSECUTIVO=(SELECT MA_CODIGO FROM MAESTRO  WHERE MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX)
                  UPDATE MAESTRO SET MA_INV_GEN=@MAESTRO#MA_INV_GEN, MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX, MA_NOPARTE=@MAESTRO#MA_NOPARTE WHERE MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX
               INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO,RI_TIPO) VALUES                                               ('MA_NOPARTE = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTE)+', '+'MA_INV_GEN = '+CONVERT(varchar(100),@MAESTRO#MA_INV_GEN)+', '+'MA_NOPARTEAUX = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTEAUX),'A')
                      DECLARE CUR_TEMPIMPORT1DET CURSOR FOR
                       SELECT MAX(Col_2),MAX(Col_3),MAX(Col_4),MAX(Col_5),MAX(Col_6),MAX(Col_7),MAX(MAESTROCOST0#MA_COSTO),MAX(MAESTROCOST0#TCO_CODIGO),MAX(MAESTROCOST0#MA_GRAV_MP),MAX(MAESTROCOST0#MA_NG_MP),MAX(MAESTROCOST0#MA_GRAV_EMP),MAX(MAESTROCOST0#MA_NG_EMP),MAX(MAESTROCOST0#MA_GRAV_ADD),MAX(MAESTROCOST0#MA_GRAV_MO) FROM TEMPIMPORT1  WHERE MAESTRO0#MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MAESTRO0#MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MAESTRO0#MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX
                      OPEN CUR_TEMPIMPORT1DET
                      FETCH NEXT FROM CUR_TEMPIMPORT1DET INTO @Col_2 ,@Col_3 ,@Col_4 ,@Col_5 ,@Col_6 ,@Col_7 ,@MAESTROCOST#MA_COSTO ,@MAESTROCOST#TCO_CODIGO ,@MAESTROCOST#MA_GRAV_MP ,@MAESTROCOST#MA_NG_MP ,@MAESTROCOST#MA_GRAV_EMP ,@MAESTROCOST#MA_NG_EMP ,@MAESTROCOST#MA_GRAV_ADD ,@MAESTROCOST#MA_GRAV_MO 
                      WHILE (@@FETCH_STATUS = 0)
                      BEGIN
                             IF NOT EXISTS (SELECT MA_CODIGO,TCO_CODIGO FROM MAESTROCOST WHERE MA_CODIGO = @CONSECUTIVO AND MA_CODIGO=@CONSECUTIVO AND TCO_CODIGO=@MAESTROCOST#TCO_CODIGO)
                    BEGIN
                         IF ISNULL(convert(varchar(10),@CONSECUTIVO),'zzzzzzzz') <> 'zzzzzzzz' AND ISNULL(convert(varchar(10),@MAESTROCOST#TCO_CODIGO),'zzzzzzzz') <> 'zzzzzzzz'
                                INSERT INTO MAESTROCOST (MA_CODIGO,MA_COSTO ,TCO_CODIGO ,MA_GRAV_MP ,MA_NG_MP ,MA_GRAV_EMP ,MA_NG_EMP ,MA_GRAV_ADD ,MA_GRAV_MO ) VALUES (@CONSECUTIVO,@MAESTROCOST#MA_COSTO ,@MAESTROCOST#TCO_CODIGO ,@MAESTROCOST#MA_GRAV_MP ,@MAESTROCOST#MA_NG_MP ,@MAESTROCOST#MA_GRAV_EMP ,@MAESTROCOST#MA_NG_EMP ,@MAESTROCOST#MA_GRAV_ADD ,@MAESTROCOST#MA_GRAV_MO )
                    END
                          ELSE
                          BEGIN
                                 UPDATE MAESTROCOST SET MA_COSTO=@MAESTROCOST#MA_COSTO, TCO_CODIGO=@MAESTROCOST#TCO_CODIGO, MA_GRAV_MP=@MAESTROCOST#MA_GRAV_MP, MA_NG_MP=@MAESTROCOST#MA_NG_MP, MA_GRAV_EMP=@MAESTROCOST#MA_GRAV_EMP, MA_NG_EMP=@MAESTROCOST#MA_NG_EMP, MA_GRAV_ADD=@MAESTROCOST#MA_GRAV_ADD, MA_GRAV_MO=@MAESTROCOST#MA_GRAV_MO WHERE MA_CODIGO = @CONSECUTIVO AND MA_CODIGO=@CONSECUTIVO AND TCO_CODIGO=@MAESTROCOST#TCO_CODIGO
                          END
                      FETCH NEXT FROM CUR_TEMPIMPORT1DET INTO @Col_2 ,@Col_3 ,@Col_4 ,@Col_5 ,@Col_6 ,@Col_7 ,@MAESTROCOST#MA_COSTO ,@MAESTROCOST#TCO_CODIGO ,@MAESTROCOST#MA_GRAV_MP ,@MAESTROCOST#MA_NG_MP ,@MAESTROCOST#MA_GRAV_EMP ,@MAESTROCOST#MA_NG_EMP ,@MAESTROCOST#MA_GRAV_ADD ,@MAESTROCOST#MA_GRAV_MO 
        END
        CLOSE CUR_TEMPIMPORT1DET
        DEALLOCATE CUR_TEMPIMPORT1DET
          END
  END
  FETCH NEXT FROM CUR_TEMPIMPORT1 INTO @Col_2 ,@Col_3 ,@Col_4 ,@Col_5 ,@Col_6 ,@Col_7 ,@MAESTRO#MA_INV_GEN ,@MAESTRO#MA_NOPARTEAUX ,@MAESTRO#MA_NOPARTE 
END
CLOSE CUR_TEMPIMPORT1
DEALLOCATE CUR_TEMPIMPORT1
GO
