SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_FILLBOMARANCEL]  @macodigo int   as

SET NOCOUNT ON 
DECLARE @BA_CODIGO INT, @MA_CODIGO INT,@AR_CODIGO INT, @BA_TIPOCOSTO varchar(1), @BA_COSTO decimal(38,6), @VALUE INT,
 @Fecha DateTime, @INSERTO INT, @EMPAQUE INT, @AR_IMPFO INT

	SET @Fecha =convert(datetime, convert(varchar(11), getdate(),101))


DELETE FROM dbo.TempBOM_CALCULABASE WHERE BST_PT = @macodigo

    exec SP_FILL_BOMDESCTEMPbase @macodigo

DELETE FROM BOM_ARANCEL WHERE MA_CODIGO=@macodigo

SELECT @INSERTO=AR_INSERTO, @EMPAQUE=AR_EMPAQUEUSA FROM CONFIGURACION



SELECT @AR_IMPFO=isnull(AR_IMPFO,0) FROM MAESTRO WHERE MA_CODIGO= @macodigo 



--MA_GRAV_MP (BOM_ARANCEL 1)
	INSERT INTO BOM_ARANCEL (MA_CODIGO, AR_CODIGO, BA_TIPOCOSTO, BA_COSTO)

	SELECT     dbo.TempBOM_CALCULABASE.BST_PT, @AR_IMPFO, '1', 
                            round(SUM(dbo.TempBOM_CALCULABASE.BST_COSTO/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(dbo.TempBOM_CALCULABASE.FACTCONV,1) * dbo.TempBOM_CALCULABASE.BST_INCORPOR ),6) AS BA_COSTO
	FROM         dbo.TempBOM_CALCULABASE LEFT OUTER JOIN
	                      dbo.MAESTRO ON dbo.TempBOM_CALCULABASE.BST_HIJO = dbo.MAESTRO.MA_CODIGO
	WHERE dbo.TempBOM_CALCULABASE.BST_TIPOCOSTO NOT IN ('D', 'C', 'F', 'Z', 'G', 'H', 'S')
		AND (dbo.TempBOM_CALCULABASE.BST_DISCH = 'S') AND (dbo.TempBOM_CALCULABASE.BST_PT = @macodigo) 	
	GROUP BY dbo.TempBOM_CALCULABASE.BST_PT


	if not exists(select * from BOM_ARANCEL where ma_codigo = @macodigo and BA_TIPOCOSTO='1') and
	 EXISTS(SELECT * FROM TempBOM_CALCULABASE WHERE BST_PT =@macodigo AND BST_TIPOCOSTO='S')
	begin
		INSERT INTO BOM_ARANCEL (MA_CODIGO, AR_CODIGO, BA_TIPOCOSTO, BA_COSTO)
		values( @macodigo, @AR_IMPFO, '1', 0)

	end


	IF EXISTS(SELECT * FROM TempBOM_CALCULABASE WHERE BST_PT =@macodigo AND BST_TIPOCOSTO='S')
	UPDATE BOM_ARANCEL
	SET BA_COSTO=BA_COSTO+
			(SELECT      round(SUM(((VMAESTROCOST.MA_GRAV_MP + VMAESTROCOST.MA_GRAV_ADD + VMAESTROCOST.MA_GRAV_EMP+VMAESTROCOST.MA_NG_MP + VMAESTROCOST.MA_NG_ADD)-VMAESTROCOST.MA_NG_USA)/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(dbo.TempBOM_CALCULABASE.FACTCONV,1) * dbo.TempBOM_CALCULABASE.BST_INCORPOR ),6) AS BA_COSTO
			FROM         VMAESTROCOST RIGHT OUTER JOIN
			                      TempBOM_CALCULABASE ON VMAESTROCOST.MA_CODIGO = TempBOM_CALCULABASE.BST_HIJO LEFT OUTER JOIN
			                      MAESTRO ON TempBOM_CALCULABASE.BST_HIJO = MAESTRO.MA_CODIGO
			WHERE     (TempBOM_CALCULABASE.BST_TIPOCOSTO IN ('S')) AND (TempBOM_CALCULABASE.BST_DISCH = 'S') AND (TempBOM_CALCULABASE.BST_PT = @macodigo)
			GROUP BY TempBOM_CALCULABASE.BST_PT)
	WHERE MA_CODIGO=@macodigo AND BA_TIPOCOSTO='1'



--MA_NG_MX (BOM_ARANCEL Z)
	/*INSERT INTO BOM_ARANCEL (MA_CODIGO, AR_CODIGO, BA_TIPOCOSTO, BA_COSTO)

	SELECT     dbo.TempBOM_CALCULABASE.BST_PT, ISNULL(dbo.TempBOM_CALCULABASE.AR_CODIGO, dbo.MAESTRO.AR_IMPFO), 'Z', 
	                     round(SUM(dbo.TempBOM_CALCULABASE.BST_INCORPOR * ISNULL(dbo.TempBOM_CALCULABASE.BST_COSTO,0)),6) AS BA_COSTO
	FROM         dbo.TempBOM_CALCULABASE LEFT OUTER JOIN
	                      dbo.MAESTRO ON dbo.TempBOM_CALCULABASE.BST_HIJO = dbo.MAESTRO.MA_CODIGO
	WHERE dbo.TempBOM_CALCULABASE.BST_TIPOCOSTO IN ('Z', 'G', 'H')
		AND(dbo.TempBOM_CALCULABASE.BST_DISCH = 'S') AND (dbo.TempBOM_CALCULABASE.BST_PT = @macodigo) 	
	GROUP BY ISNULL(dbo.TempBOM_CALCULABASE.AR_CODIGO, dbo.MAESTRO.AR_IMPFO), dbo.TempBOM_CALCULABASE.BST_PT*/
	

--MA_NG_EMP (BOM_ARANCEL 3)
	INSERT INTO BOM_ARANCEL (MA_CODIGO, AR_CODIGO, BA_TIPOCOSTO, BA_COSTO)

	SELECT     dbo.TempBOM_CALCULABASE.BST_PT, @EMPAQUE, '3', 
                            round(SUM(dbo.TempBOM_CALCULABASE.BST_COSTO/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(dbo.TempBOM_CALCULABASE.FACTCONV,1) * dbo.TempBOM_CALCULABASE.BST_INCORPOR ),6) AS BA_COSTO
	FROM         dbo.TempBOM_CALCULABASE LEFT OUTER JOIN
	                      dbo.MAESTRO ON dbo.TempBOM_CALCULABASE.BST_HIJO = dbo.MAESTRO.MA_CODIGO
	WHERE dbo.TempBOM_CALCULABASE.BST_TIPOCOSTO IN ('F')
		AND (dbo.TempBOM_CALCULABASE.BST_DISCH = 'S') AND (dbo.TempBOM_CALCULABASE.BST_PT = @macodigo) 	
	GROUP BY dbo.TempBOM_CALCULABASE.BST_PT


	if not exists(select * from BOM_ARANCEL where ma_codigo = @macodigo and BA_TIPOCOSTO='3') and
	 EXISTS(SELECT * FROM TempBOM_CALCULABASE WHERE BST_PT =@macodigo AND BST_TIPOCOSTO='S')
	begin
		INSERT INTO BOM_ARANCEL (MA_CODIGO, AR_CODIGO, BA_TIPOCOSTO, BA_COSTO)
		values( @macodigo, @EMPAQUE, '3', 0)

	end


	IF EXISTS(SELECT * FROM TempBOM_CALCULABASE WHERE BST_PT =@macodigo AND BST_TIPOCOSTO='S')
	UPDATE BOM_ARANCEL
	SET BA_COSTO=BA_COSTO+
			(SELECT      round(SUM(VMAESTROCOST.MA_NG_EMP/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(dbo.TempBOM_CALCULABASE.FACTCONV,1) * dbo.TempBOM_CALCULABASE.BST_INCORPOR ),6) AS BA_COSTO
			FROM         VMAESTROCOST RIGHT OUTER JOIN
			                      TempBOM_CALCULABASE ON VMAESTROCOST.MA_CODIGO = TempBOM_CALCULABASE.BST_HIJO LEFT OUTER JOIN
			                      MAESTRO ON TempBOM_CALCULABASE.BST_HIJO = MAESTRO.MA_CODIGO
			WHERE     (TempBOM_CALCULABASE.BST_TIPOCOSTO IN ('S')) AND (TempBOM_CALCULABASE.BST_DISCH = 'S') AND (TempBOM_CALCULABASE.BST_PT = @macodigo)
			GROUP BY TempBOM_CALCULABASE.BST_PT)
	WHERE MA_CODIGO=@macodigo AND BA_TIPOCOSTO='3'


--MA_NG_USA (BOM_ARANCEL N)
	INSERT INTO BOM_ARANCEL (MA_CODIGO, AR_CODIGO, BA_TIPOCOSTO, BA_COSTO)

	SELECT     dbo.TempBOM_CALCULABASE.BST_PT, @INSERTO, 'N', 
                            round(SUM(dbo.TempBOM_CALCULABASE.BST_COSTO/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(dbo.TempBOM_CALCULABASE.FACTCONV,1) * dbo.TempBOM_CALCULABASE.BST_INCORPOR ),6) AS BA_COSTO
	FROM         dbo.TempBOM_CALCULABASE LEFT OUTER JOIN
	                      dbo.MAESTRO ON dbo.TempBOM_CALCULABASE.BST_HIJO = dbo.MAESTRO.MA_CODIGO
	WHERE dbo.TempBOM_CALCULABASE.BST_TIPOCOSTO IN ('D', 'C')
	AND (dbo.TempBOM_CALCULABASE.BST_DISCH = 'S') AND (dbo.TempBOM_CALCULABASE.BST_PT = @macodigo) 	
	GROUP BY dbo.TempBOM_CALCULABASE.BST_PT

	if not exists(select * from BOM_ARANCEL where ma_codigo = @macodigo and BA_TIPOCOSTO='N') and
	 EXISTS(SELECT * FROM TempBOM_CALCULABASE WHERE BST_PT =@macodigo AND BST_TIPOCOSTO='S')
	begin
		INSERT INTO BOM_ARANCEL (MA_CODIGO, AR_CODIGO, BA_TIPOCOSTO, BA_COSTO)
		values( @macodigo, @INSERTO, 'N', 0)

	end

	IF EXISTS(SELECT * FROM TempBOM_CALCULABASE WHERE BST_PT =@macodigo AND BST_TIPOCOSTO='S')
	UPDATE BOM_ARANCEL
	SET BA_COSTO=BA_COSTO+
			(SELECT      round(SUM(VMAESTROCOST.MA_NG_USA/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(dbo.TempBOM_CALCULABASE.FACTCONV,1) * dbo.TempBOM_CALCULABASE.BST_INCORPOR ),6) AS BA_COSTO
			FROM         VMAESTROCOST RIGHT OUTER JOIN
			                      TempBOM_CALCULABASE ON VMAESTROCOST.MA_CODIGO = TempBOM_CALCULABASE.BST_HIJO LEFT OUTER JOIN
			                      MAESTRO ON TempBOM_CALCULABASE.BST_HIJO = MAESTRO.MA_CODIGO
			WHERE     (TempBOM_CALCULABASE.BST_TIPOCOSTO IN ('S')) AND (TempBOM_CALCULABASE.BST_DISCH = 'S') AND (TempBOM_CALCULABASE.BST_PT = @macodigo)
			GROUP BY TempBOM_CALCULABASE.BST_PT)
	WHERE MA_CODIGO=@macodigo AND BA_TIPOCOSTO='N'

	--DELETE FROM dbo.TempBOM_CALCULABASE WHERE BST_PT = @macodigo

	DELETE FROM BOM_ARANCEL WHERE MA_CODIGO = @macodigo AND BA_COSTO=0





GO
