SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






































CREATE PROCEDURE [dbo].[SP_ACTUALIZATASAPCKLIST]  (@pl_codigo int)   as

SET NOCOUNT ON 

declare @PLD_indiced int

	if not exists(select * from arancel where convert(varchar(11),AR_ULTMODIFTIGIE,101)= convert(varchar(11),getdate(),101))
	exec SP_ACTUALIZAARANCELBASETIGIE


	-- actualiza tasas
	UPDATE PCKLISTDET  
	SET PCKLISTDET.PLD_POR_DEF= ARANCEL.AR_ADVDEF, PCKLISTDET.SPI_CODIGO=0, 
	PCKLISTDET.PLD_SEC_IMP=0 
	FROM  PCKLISTDET INNER JOIN 
	  ARANCEL ON PCKLISTDET.AR_IMPMX = ARANCEL.AR_CODIGO 
	WHERE     (PCKLISTDET.PLD_DEF_TIP = 'G') AND PCKLISTDET.PL_CODIGO =@pl_codigo
	AND PCKLISTDET.PLD_SALDO >0
	
	UPDATE PCKLISTDET  
	SET PCKLISTDET.PLD_POR_DEF= ARANCEL.AR_PORCENT_8VA, PCKLISTDET.SPI_CODIGO=0, 
	PCKLISTDET.PLD_SEC_IMP=0 
	FROM  PCKLISTDET INNER JOIN 
	  ARANCEL ON PCKLISTDET.AR_IMPMX = ARANCEL.AR_CODIGO 
	WHERE     (PCKLISTDET.PLD_DEF_TIP = 'R') AND PCKLISTDET.PL_CODIGO =@pl_codigo
	AND PCKLISTDET.PLD_SALDO >0
	
	UPDATE PCKLISTDET  
	SET PCKLISTDET.PLD_POR_DEF= PAISARA.PAR_BEN, PCKLISTDET.PLD_SEC_IMP=0, PCKLISTDET.SPI_CODIGO=22 
	FROM PCKLISTDET INNER JOIN 
	PAISARA ON PCKLISTDET.AR_IMPMX = PAISARA.AR_CODIGO AND PCKLISTDET.PA_CODIGO = PAISARA.PA_CODIGO 
	WHERE (PCKLISTDET.PLD_DEF_TIP = 'P') AND PCKLISTDET.PL_CODIGO = @pl_codigo
	AND PCKLISTDET.PA_CODIGO =233 	AND PCKLISTDET.PLD_SALDO >0

	UPDATE PCKLISTDET  
	SET PCKLISTDET.PLD_POR_DEF= PAISARA.PAR_BEN, PCKLISTDET.PLD_SEC_IMP=0
	FROM PCKLISTDET INNER JOIN 
	PAISARA ON PCKLISTDET.AR_IMPMX = PAISARA.AR_CODIGO AND PCKLISTDET.SPI_CODIGO = PAISARA.SPI_CODIGO 
	WHERE (PCKLISTDET.PLD_DEF_TIP = 'P') AND PCKLISTDET.PL_CODIGO = @pl_codigo
	AND PCKLISTDET.PA_CODIGO <>233 	AND PCKLISTDET.PLD_SALDO >0



	UPDATE PCKLISTDET
	SET     PCKLISTDET.PLD_SEC_IMP= (SELECT SE_CODIGO FROM CONFIGURACION)
	FROM         PCKLISTDET
	WHERE     (PCKLISTDET.PLD_DEF_TIP = 'S') AND (PCKLISTDET.PLD_SEC_IMP = 0 OR
	                      PCKLISTDET.PLD_SEC_IMP IS NULL) AND (PCKLISTDET.PL_CODIGO = @pl_codigo)
	AND PCKLISTDET.PLD_SALDO >0

	UPDATE PCKLISTDET
	SET     PCKLISTDET.PLD_SEC_IMP= MAESTRO.MA_SEC_IMP
	FROM         PCKLISTDET INNER JOIN
	                      MAESTRO ON PCKLISTDET.MA_CODIGO = MAESTRO.MA_CODIGO
	WHERE     (PCKLISTDET.PLD_DEF_TIP = 'S') AND (PCKLISTDET.PLD_SEC_IMP = 0 OR
	                      PCKLISTDET.PLD_SEC_IMP IS NULL) AND (MAESTRO.MA_SEC_IMP > 0) AND (PCKLISTDET.PL_CODIGO = @pl_codigo)
	AND PCKLISTDET.PLD_SALDO >0
	
	UPDATE PCKLISTDET  
	SET   PCKLISTDET.PLD_POR_DEF= SECTORARA.SA_PORCENT, PCKLISTDET.SPI_CODIGO=0 
	FROM  PCKLISTDET INNER JOIN 
	 SECTORARA ON PCKLISTDET.AR_IMPMX = SECTORARA.AR_CODIGO AND 
	 PCKLISTDET.PLD_SEC_IMP = SECTORARA.SE_CODIGO 
	WHERE (PCKLISTDET.PLD_DEF_TIP = 'S') AND PCKLISTDET.PL_CODIGO = @pl_codigo 
	AND PCKLISTDET.PLD_SALDO >0


	if (SELECT CF_SINGENERICOUM FROM CONFIGURACION)='S'
	and exists (SELECT MA_GENERICO FROM PCKLISTDET WHERE MA_GENERICO = 0 AND PL_CODIGO = @pl_codigo AND AR_IMPMX > 0)
	begin
		EXEC SP_ADDGENERICOS
	
		UPDATE PCKLISTDET
		SET     PCKLISTDET.MA_GENERICO= MAESTRO.MA_GENERICO, PCKLISTDET.EQ_GEN= MAESTRO.EQ_GEN, PCKLISTDET.ME_GEN= 
		                      MAESTRO_1.ME_COM
		FROM         MAESTRO INNER JOIN
		                      PCKLISTDET ON MAESTRO.MA_CODIGO = PCKLISTDET.MA_CODIGO AND 
		                      MAESTRO.MA_GENERICO <> PCKLISTDET.MA_GENERICO INNER JOIN
		                      MAESTRO MAESTRO_1 ON MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO
		WHERE     (PCKLISTDET.PL_CODIGO = @pl_codigo)
		AND PCKLISTDET.PLD_SALDO >0
	end

--	IF EXISTS (SELECT EQ_IMPMX FROM PCKLISTDET WHERE (ME_CODIGO <> ME_ARIMPMX) AND (EQ_IMPMX = 1))
	EXEC SP_ACTUALIZAEQARAPCKLIST @pl_codigo
/*
	UPDATE MAESTRO
	SET     MAESTRO.AR_IMPMX=PCKLISTDET.AR_IMPMX, MAESTRO.AR_EXPMX=PCKLISTDET.AR_IMPMX,  
		         MAESTRO.MA_SEC_IMP=PCKLISTDET.PLD_SEC_IMP, 
	                      MAESTRO.MA_DEF_TIP=PCKLISTDET.PLD_DEF_TIP, 
	                      MAESTRO.SPI_CODIGO=PCKLISTDET.SPI_CODIGO, MAESTRO.EQ_IMPMX=PCKLISTDET.EQ_IMPMX
	FROM         PCKLISTDET INNER JOIN
	                      MAESTRO ON PCKLISTDET.MA_CODIGO = MAESTRO.MA_CODIGO
	WHERE     (PCKLISTDET.PL_CODIGO =@pl_codigo)

*/
























GO
