SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_ExpBomInvFis] (@CodigoFactura Int)   as

SET NOCOUNT ON 
declare @IVFD_INDICED INT, @BST_PT INT, @IVFD_CAN_GEN decimal(38,6), @IVFD_FEC_STRUCT DATETIME, @countbom int

/* se corren los stored para cada uno de los pt o sub del detalle de la factura*/


declare CUR_DETALLEFACTPT cursor for
-- selecciona Producto Terminados o Subensambles para esa Factura
SELECT     INVENTARIOFISDET.IVFD_INDICED, INVENTARIOFISDET.MA_CODIGO, INVENTARIOFISDET.IVFD_CAN_GEN AS IVFD_CAN_GEN, 
           INVENTARIOFISDET.IVFD_FEC_STRUCT
FROM       INVENTARIOFISDET LEFT OUTER JOIN
           CONFIGURATIPO ON INVENTARIOFISDET.TI_CODIGO = CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
	   MAESTRO ON MAESTRO.MA_CODIGO = INVENTARIOFISDET.MA_CODIGO
WHERE     (CONFIGURATIPO.CFT_TIPO = 'S' OR CONFIGURATIPO.CFT_TIPO = 'P') AND 
          (INVENTARIOFISDET.IVF_CODIGO = @CodigoFactura) AND 
          (INVENTARIOFISDET.IVFD_RETRABAJO = 'N' or INVENTARIOFISDET.IVFD_RETRABAJO = 'C') AND 
          (MAESTRO.MA_TIP_ENS = 'F' OR MAESTRO.MA_TIP_ENS = 'E') AND 
          (INVENTARIOFISDET.IVFD_CAN_GEN > 0)  --  AND dbo.FACTEXPDET.FED_DESCARGADO='N'
ORDER BY INVENTARIOFISDET.MA_CODIGO


 OPEN CUR_DETALLEFACTPT

  FETCH NEXT FROM CUR_DETALLEFACTPT
	INTO @IVFD_INDICED, @BST_PT, @IVFD_CAN_GEN, @IVFD_FEC_STRUCT

  WHILE (@@fetch_status = 0) 
  BEGIN  
	--PRINT @BST_PT

	select @countbom = count(*) from bom_struct where  bsu_subensamble=@BST_PT and bst_perini<=@IVFD_FEC_STRUCT and bst_perfin>=@IVFD_FEC_STRUCT

	if exists(select * from bom_desctemp where fed_indiced=@IVFD_INDICED and FACT_INV='I')
	delete from bom_desctemp where fed_indiced=@IVFD_INDICED and FACT_INV='I'

	if @countbom >0
	EXEC SP_FILL_BOM_DESCTEMP_INV @IVFD_INDICED, @BST_PT, @IVFD_FEC_STRUCT, @IVFD_CAN_GEN, @CODIGOFACTURA

	  FETCH NEXT FROM CUR_DETALLEFACTPT
	INTO @IVFD_INDICED, @BST_PT, @IVFD_CAN_GEN, @IVFD_FEC_STRUCT

END

	CLOSE CUR_DETALLEFACTPT
	DEALLOCATE CUR_DETALLEFACTPT






































GO
