SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_creaBOM_ESTRUCTDESC]   as


if not exists (select * from dbo.sysobjects where name='BOM_ESTRUCTDESC')
CREATE TABLE [dbo].[BOM_ESTRUCTDESC] (
	[BST_PT] [int] NULL ,
	[BST_ENTRAVIGOR] [datetime] NULL ,
	[BST_HIJO] [int] NOT NULL ,
	[BST_INCORPOR] [decimal](38,6) NOT NULL CONSTRAINT [DF_BOM_ESTRUCTDESC_BST_INCORPOR] DEFAULT (1),
	[BST_DISCH] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_BOM_ESTRUCTDESC_BST_DISCH] DEFAULT ('S'),
	[TI_CODIGO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ME_CODIGO] [int] NULL ,
	[FACTCONV] [decimal](38,6) NOT NULL CONSTRAINT [DF_BOM_ESTRUCTDESC_FACTCONV] DEFAULT (1),
	[BST_PERINI] [datetime] NULL ,
	[BST_PERFIN] [datetime] NULL CONSTRAINT [DF_BOM_ESTRUCTDESC_BST_PERFIN] DEFAULT ('01/01/9999'),
	[ME_GEN] [int] NULL ,
	[BST_TRANS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_BOM_ESTRUCTDESC_BST_TRANS] DEFAULT ('N'),
	[BST_TIPOCOSTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BST_DESP] [decimal](38,6) NOT NULL CONSTRAINT [DF_BOM_ESTRUCTDESC_BST_DESP] DEFAULT (0),
	[BST_MERMA] [decimal](38,6) NOT NULL CONSTRAINT [DF_BOM_ESTRUCTDESC_BST_MERMA] DEFAULT (0),
	[MA_TIP_ENS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BST_NIVEL] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BST_TIPODESC] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BST_PERTENECE] [int] NULL 
) ON [PRIMARY]

GO
