SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[SP_IMPGENLISTA_CAMPOS]  @TABLA varchar(100), @TablaTEMPIMPORT1 varchar(100), @CAMPOS varchar(4096)  OUTPUT, @CAMPOSINSERT varchar(4096) OUTPUT, @LOCALESINSERT varchar(4096) OUTPUT, @LOCALES varchar(4096) OUTPUT,@EXTERNOS varchar(4096) OUTPUT,@ARCHIVO varchar(4096) OUTPUT    as

SET NOCOUNT ON 
DECLARE @temp_str varchar(100),@TABLA_TEMP varchar(100),@campo_str varchar(100)

SELECT @CAMPOS='',@LOCALES='',@EXTERNOS='',@CAMPOSINSERT='',@LOCALESINSERT='',@ARCHIVO = ''


DECLARE CUR_CAMPOS CURSOR FOR
/*
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TABLA
AND COLUMN_NAME 
IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TEMPIMPORT1')
*/
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TablaTEMPIMPORT1
AND TABLE_SCHEMA='DBO'
AND CHARINDEX('#',COLUMN_NAME) <> 0 AND CHARINDEX(@TABLA,SUBSTRING(COLUMN_NAME,1,CHARINDEX('#',COLUMN_NAME)))>0

OPEN CUR_CAMPOS
FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
WHILE (@@FETCH_STATUS = 0) 
BEGIN

	SELECT @TABLA_TEMP=SUBSTRING (@temp_str,1,CHARINDEX('#',@temp_str)-1)		
	IF @TABLA = @TABLA_TEMP
	BEGIN
		SELECT @campo_str=SUBSTRING (@temp_str,CHARINDEX('#',@temp_str)+1,LEN(@temp_str))
		IF @CAMPOS <> ''
			SELECT @CAMPOS = @CAMPOS+','+@temp_str+' ', @LOCALES = @LOCALES+',@'+@temp_str+' '
		ELSE
			SELECT @CAMPOS = @temp_str+' ', @LOCALES = '@'+@temp_str+' '
		 IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TABLA AND
	                                              COLUMN_NAME=@campo_str)
		BEGIN
			IF @CAMPOSINSERT<>'' 
				SELECT @CAMPOSINSERT=@CAMPOSINSERT+','+@campo_str+' ', @LOCALESINSERT = @LOCALESINSERT+',@'+@temp_str+' '
			ELSE
				SELECT @CAMPOSINSERT=@campo_str+' ', @LOCALESINSERT = '@'+@temp_str+' '
		END
	END	
	FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
END
CLOSE CUR_CAMPOS
DEALLOCATE CUR_CAMPOS



DECLARE CUR_CAMPOS CURSOR FOR
/*
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TABLA  AND IS_NULLABLE='No'
AND COLUMN_DEFAULT IS NULL AND COLUMN_NAME NOT IN 
(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TEMPIMPORT1')
AND COLUMN_NAME NOT IN (SELECT IMR_FIELDCONSEC FROM IMPORTTABLESDETCONT WHERE IMR_TABLA=@TABLA)
*/
SELECT IMF_FIELDNAME   FROM IMPORTFIELDS WHERE IMF_SELECTMASTER <>''  AND 
IMF_TABLENAME=@TABLA 
AND (IMF_TABLENAME+'#'+IMF_FIELDNAME) NOT IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TablaTEMPIMPORT1
AND CHARINDEX('#',COLUMN_NAME) <> 0)

OPEN CUR_CAMPOS
FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
WHILE (@@FETCH_STATUS = 0) 
BEGIN
	IF @EXTERNOS <> ''
		SELECT @EXTERNOS = @EXTERNOS+','+@temp_str+' '
	ELSE
   		SELECT @EXTERNOS = @temp_str+' '

	
	FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
END
CLOSE CUR_CAMPOS
DEALLOCATE CUR_CAMPOS



DECLARE CUR_CAMPOS CURSOR FOR
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TablaTEMPIMPORT1
AND TABLE_SCHEMA='DBO'
AND CHARINDEX('#',COLUMN_NAME) = 0
OPEN CUR_CAMPOS
FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
WHILE (@@FETCH_STATUS = 0) 
BEGIN
	
	IF @ARCHIVO<>'' 
		SELECT @ARCHIVO=@ARCHIVO+',@'+@temp_str+' '
	ELSE
		SELECT @ARCHIVO='@'+@temp_str+' '
	
	FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
END
CLOSE CUR_CAMPOS
DEALLOCATE CUR_CAMPOS



GO
