SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO














CREATE PROCEDURE [dbo].[SP_IMPEXCELBOM] (@bsu_subensamble int)   as

SET NOCOUNT ON 
declare @NOPARTE varchar(30), @NOPARTEAUX varchar(30), @BSU_NOPARTE varchar(30), @BSU_NOPARTEAUX varchar(10), @BST_PERINI datetime, @BST_PERFIN datetime
/*Yolanda 2009-01-21*/
DECLARE @TipoEntrada CHAR(1)
SET @TipoEntrada= 'I'
set @BST_PERINI='01/01/1990' 
set @BST_PERFIN='01/01/9999'

DELETE FROM IMPORTLOG WHERE IML_CBFORMA=18
if (select count(*) from IMPORTLOG)=0
DBCC CHECKIDENT (IMPORTLOG, RESEED, 0) WITH NO_INFOMSGS

	delete from IMPEXCELBOM where NOPARTE=''
	DECLARE CUR_IMPHIJOEXCEL CURSOR FOR
	SELECT NOPARTE, NOPARTEAUX FROM IMPEXCELBOM
	WHERE NOPARTE+'-'+isnull(NOPARTEAUX,'') NOT IN
	(SELECT MA_NOPARTE+'-'+rtrim(ltrim(isnull(MA_NOPARTEAUX,''))) FROM MAESTRO WHERE MA_INV_GEN = 'I' 
	                                             AND MA_EST_MAT = 'A') 
	OPEN CUR_IMPHIJOEXCEL
	FETCH NEXT FROM CUR_IMPHIJOEXCEL INTO @NOPARTE, @NOPARTEAUX
	WHILE (@@FETCH_STATUS = 0) 
	BEGIN
		INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
		VALUES ('NO SE PUEDE IMPORTAR NO. DE PARTE : '+@NOPARTE+' CON EL AUX.: '+@NOPARTEAUX +' PORQUE NO
		SE ENCUENTRA EN EL CATALOGO MAESTRO O ESTA ACTIVO', 18)
		FETCH NEXT FROM CUR_IMPHIJOEXCEL INTO @NOPARTE, @NOPARTEAUX
	END
	CLOSE CUR_IMPHIJOEXCEL
	DEALLOCATE CUR_IMPHIJOEXCEL

	select @BSU_NOPARTE= ma_noparte, @BSU_NOPARTEAUX= MA_NOPARTEAUX from maestro where ma_codigo=@BSU_SUBENSAMBLE

/* se ejecutan los procedimientos para llenar la estructura */
	INSERT INTO dbo.BOM_STRUCT (BSU_SUBENSAMBLE, BST_HIJO, BST_INCORPOR, BST_DISCH, ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, 
	                      ME_GEN, BST_TRANS, BSU_NOPARTE, BST_NOPARTE, BSU_NOPARTEAUX, BST_NOPARTEAUX, BST_TIP_ENS)
	
	SELECT     @BSU_SUBENSAMBLE, dbo.MAESTRO.MA_CODIGO, isnull(dbo.IMPEXCELBOM.CANTIDAD,1), dbo.MAESTRO.MA_DISCHARGE, dbo.MAESTRO.ME_COM, 
	                      dbo.MAESTRO.EQ_GEN, @BST_PERINI, @BST_PERFIN, MAESTRO_1.ME_COM, 'N', 
	                      @BSU_NOPARTE, dbo.MAESTRO.MA_NOPARTE, @BSU_NOPARTEAUX, dbo.MAESTRO.MA_NOPARTEAUX, dbo.MAESTRO.MA_TIP_ENS
	FROM         dbo.MAESTRO MAESTRO_1 RIGHT OUTER JOIN
	                      dbo.MAESTRO ON MAESTRO_1.MA_CODIGO = dbo.MAESTRO.MA_GENERICO RIGHT OUTER JOIN
                                  IMPEXCELBOM ON MAESTRO.MA_NOPARTE+'-'+rtrim(ltrim(isnull(MAESTRO.MA_NOPARTEAUX,''))) = IMPEXCELBOM.NOPARTE+'-'+isnull(IMPEXCELBOM.NOPARTEAUX,'')
	 where dbo.MAESTRO.MA_CODIGO not in
		(select bst_hijo from bom_struct where bsu_subensamble=@bsu_subensamble
		and bst_perini=@BST_PERINI and bst_perfin=@BST_PERFIN)
	/*Yolanda 2009-01-21*/ and maestro.ma_inv_gen = @TipoEntrada
	ORDER BY ORDEN
GO
