SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_fillpedexpCompl] (@picodigo int,  @user int)    as

SET NOCOUNT ON 
declare @pid_indiced int, @maximo int, @FechaActual varchar(10), @hora varchar(15), @em_codigo int

	ALTER TABLE PEDIMPDET DISABLE TRIGGER insert_pedimpdet

	select @em_codigo=em_codigo from intradeglobal.dbo.empresa where em_corto in
	(select replace(convert(sysname,db_name()),'intrade',''))


select @FechaActual = convert(varchar(10), getdate(),101)
select @hora =substring(convert(varchar(100),getdate(),9),13,8)+' '+substring(convert(varchar(100),getdate(),9),25,2)




	insert into IntradeGlobal.dbo.Avance (sysuslst_id, ava_mensajeno, ava_info, ava_infoing, ava_fecha, ava_hora, em_codigo)
	values (@user, 2, 'Llenando tabla temporal de detalle ', 'Filling Temporary Detail Table ', convert(varchar(10),@FechaActual,101), @hora, @em_codigo)


	TRUNCATE TABLE TempPedImpDet

		--print 'borrando detalles temp'

	dbcc checkident (TempPedimpdet, reseed, 1) WITH NO_INFOMSGS

	SELECT     @maximo= isnull(MAX(PID_INDICED),0)+1
	FROM         PEDIMPDET


	insert into TempPedImpDet(PI_CODIGO, MA_CODIGO, PID_NOPARTE, PID_NOMBRE, PID_NAME, PID_COS_UNI, PID_COS_UNIADU, PID_COS_UNIGEN, PID_COS_UNIVA, 
                      PID_COS_UNIMATGRA, PID_CANT, PID_CAN_AR, PID_CAN_GEN, PID_VAL_ADU, PID_CTOT_DLS, 
                      ME_CODIGO, ME_GENERICO, MA_GENERICO, EQ_GENERICO, EQ_IMPMX, AR_IMPMX, ME_ARIMPMX, AR_EXPFO, 
                      PID_RATEEXPFO, PID_SEC_IMP, PID_DEF_TIP, PID_POR_DEF, CS_CODIGO, TI_CODIGO, PA_ORIGEN, 
                      PA_PROCEDE, SPI_CODIGO, PR_CODIGO, SE_CODIGO, PID_REGIONFIN, PID_PAGACONTRIB, PID_NOPARTEAUX)
	
	
	SELECT     @PICODIGO, PEDIMPDET.MA_CODIGO, MAX(PEDIMPDET.PID_NOPARTE), MAX(PEDIMPDET.PID_NOMBRE), MAX(PEDIMPDET.PID_NAME), 
	                      PEDIMPDET.PID_COS_UNI, PEDIMPDET.PID_COS_UNIADU, PEDIMPDET.PID_COS_UNIGEN, PEDIMPDET.PID_COS_UNIVA, 
	                      PEDIMPDET.PID_COS_UNIMATGRA, SUM(PEDIMPDET.PID_CANT), SUM(PEDIMPDET.PID_CAN_AR), 
	                      SUM(PEDIMPDET.PID_CAN_GEN), SUM(PEDIMPDET.PID_VAL_ADU), SUM(PEDIMPDET.PID_CTOT_DLS), 
	                      MAX(PEDIMPDET.ME_CODIGO), MAX(PEDIMPDET.ME_GENERICO), PEDIMPDET.MA_GENERICO, MAX(PEDIMPDET.EQ_GENERICO), 
	                      MAX(PEDIMPDET.EQ_IMPMX), MAX(PEDIMPDET.AR_IMPMX), MAX(PEDIMPDET.ME_ARIMPMX), MAX(PEDIMPDET.AR_EXPFO), 
	                      MAX(PEDIMPDET.PID_RATEEXPFO), MAX(PEDIMPDET.PID_SEC_IMP), MAX(PEDIMPDET.PID_DEF_TIP), PEDIMPDET.PID_POR_DEF, 
	                      MAX(PEDIMPDET.CS_CODIGO), MAX(PEDIMPDET.TI_CODIGO), PEDIMPDET.PA_ORIGEN, 
	                      PEDIMPDET.PA_PROCEDE, MAX(PEDIMPDET.SPI_CODIGO), MAX(PEDIMPDET.PR_CODIGO), 
	                      MAX(PEDIMPDET.SE_CODIGO), PEDIMPDET.PID_REGIONFIN, PEDIMPDET.PID_PAGACONTRIB, MAX(PEDIMPDET.PID_NOPARTEAUX)
	FROM         PEDIMPDET INNER JOIN
	                      PEDIMP ON PEDIMPDET.PI_CODIGO = PEDIMP.PI_CODIGO
	WHERE     (PEDIMP.PI_COMPLEMENTA = @PICODIGO)
	GROUP BY PEDIMPDET.MA_CODIGO, PEDIMPDET.PID_COS_UNI, PEDIMPDET.PID_COS_UNIADU, PEDIMPDET.PID_COS_UNIGEN, 
	                      PEDIMPDET.PID_COS_UNIVA, PEDIMPDET.PID_COS_UNIMATGRA, PEDIMPDET.MA_GENERICO, 
	                      PEDIMPDET.PID_POR_DEF, PEDIMPDET.PA_ORIGEN, PEDIMPDET.PA_PROCEDE, 
	                      PEDIMPDET.PID_REGIONFIN, PEDIMPDET.PID_PAGACONTRIB


	INSERT INTO PEDIMPDET (PI_CODIGO, PID_INDICED, MA_CODIGO, PID_NOPARTE, PID_NOMBRE, PID_NAME, PID_COS_UNI, PID_COS_UNIADU, PID_COS_UNIGEN, 
	                      PID_COS_UNIVA, PID_COS_UNIMATGRA, PID_CANT, PID_CAN_AR, PID_CAN_GEN, PID_VAL_ADU, PID_CTOT_DLS, ME_CODIGO, ME_GENERICO, 
	                      MA_GENERICO, EQ_GENERICO, EQ_IMPMX, AR_IMPMX, ME_ARIMPMX, AR_EXPFO, PID_RATEEXPFO, PID_SEC_IMP, PID_DEF_TIP, PID_POR_DEF, 
	                      CS_CODIGO, TI_CODIGO, PA_ORIGEN, PA_PROCEDE, SPI_CODIGO, PR_CODIGO, PID_IMPRIMIR, PID_GENERA_EMP, 
	                      PID_CANT_DESP, PID_DESCARGABLE, PID_MA_CODIGOPADREKIT, PID_REGIONFIN, SE_CODIGO, PID_PAGACONTRIB, PID_NOPARTEAUX)

	SELECT     PI_CODIGO, PID_INDICED+@maximo, MA_CODIGO, PID_NOPARTE, PID_NOMBRE, PID_NAME, PID_COS_UNI, PID_COS_UNIADU, PID_COS_UNIGEN, 
	                      PID_COS_UNIVA, PID_COS_UNIMATGRA, PID_CANT, PID_CAN_AR, PID_CAN_GEN, PID_VAL_ADU, PID_CTOT_DLS, ME_CODIGO, ME_GENERICO, 
	                      MA_GENERICO, EQ_GENERICO, EQ_IMPMX, AR_IMPMX, ME_ARIMPMX, AR_EXPFO, PID_RATEEXPFO, PID_SEC_IMP, PID_DEF_TIP, PID_POR_DEF, 
	                      CS_CODIGO, TI_CODIGO, PA_ORIGEN, PA_PROCEDE, SPI_CODIGO, PR_CODIGO, PID_IMPRIMIR, PID_GENERA_EMP, 
	                      PID_CANT_DESP, PID_DESCARGABLE, PID_MA_CODIGOPADREKIT, PID_REGIONFIN, SE_CODIGO, PID_PAGACONTRIB, PID_NOPARTEAUX
	FROM         TempPedImpDet
	where pi_codigo=@picodigo  order by pid_indiced

	UPDATE PEDIMPDET
	SET PEDIMPDET.PID_INDICEDLIGA=PEDIMPDETCOMP.PID_INDICED
	FROM PEDIMPDET INNER JOIN PEDIMPDET PEDIMPDETCOMP ON
	  PEDIMPDET.MA_CODIGO=PEDIMPDETCOMP.MA_CODIGO AND 
	  PEDIMPDET.PID_COS_UNI = PEDIMPDETCOMP.PID_COS_UNI AND  
	  PEDIMPDET.PID_COS_UNIADU = PEDIMPDETCOMP.PID_COS_UNIADU AND  
	  PEDIMPDET.PID_COS_UNIGEN = PEDIMPDETCOMP.PID_COS_UNIGEN AND  
	  PEDIMPDET.PID_COS_UNIVA = PEDIMPDETCOMP.PID_COS_UNIVA AND  
	  PEDIMPDET.PID_COS_UNIMATGRA = PEDIMPDETCOMP.PID_COS_UNIMATGRA AND  
	  PEDIMPDET.MA_GENERICO = PEDIMPDETCOMP.MA_GENERICO AND  
	  PEDIMPDET.PID_POR_DEF = PEDIMPDETCOMP.PID_POR_DEF AND  
	  PEDIMPDET.PA_ORIGEN = PEDIMPDETCOMP.PA_ORIGEN AND  
	  PEDIMPDET.PA_PROCEDE = PEDIMPDETCOMP.PA_PROCEDE AND  
	  PEDIMPDET.PID_REGIONFIN = PEDIMPDETCOMP.PID_REGIONFIN AND  
	  PEDIMPDET.PID_PAGACONTRIB = PEDIMPDETCOMP.PID_PAGACONTRIB INNER JOIN PEDIMP ON
	  PEDIMPDET.PI_CODIGO = PEDIMP.PI_CODIGO
	  WHERE PEDIMP.PI_COMPLEMENTA = @PICODIGO


select @Pid_indiced= max(pid_indiced) from pedimpdet

	update consecutivo
	set cv_codigo =  isnull(@pid_indiced,0) + 1
	where cv_tipo = 'PID'


	ALTER TABLE PEDIMPDET ENABLE TRIGGER insert_pedimpdet




GO
