SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





































CREATE PROCEDURE [dbo].[SP_ACTUALIZATASALISTAEXP]  (@LE_codigo int)   as

SET NOCOUNT ON 

declare @LED_indiced int

	if not exists(select * from arancel where convert(varchar(11),AR_ULTMODIFTIGIE,101)= convert(varchar(11),getdate(),101))
	exec SP_ACTUALIZAARANCELBASETIGIE



	-- actualiza tasas
	UPDATE LISTAEXPDET  
	SET LISTAEXPDET.LED_RATEIMPFO= ARANCEL.AR_ADVDEF
	FROM  LISTAEXPDET INNER JOIN 
	  ARANCEL ON LISTAEXPDET.AR_IMPFO = ARANCEL.AR_CODIGO 
	WHERE     LISTAEXPDET.LE_CODIGO =@LE_codigo
	

	if (SELECT CF_SINGENERICOUM FROM CONFIGURACION)='S'
	and exists (SELECT MA_GENERICO FROM LISTAEXPDET WHERE MA_GENERICO = 0 AND LE_CODIGO = @LE_codigo AND AR_IMPFO > 0)
	begin
		EXEC SP_ADDGENERICOS
	
		UPDATE LISTAEXPDET
		SET     LISTAEXPDET.MA_GENERICO= MAESTRO.MA_GENERICO, LISTAEXPDET.EQ_GEN= MAESTRO.EQ_GEN, LISTAEXPDET.ME_GEN= 
		                      MAESTRO_1.ME_COM
		FROM         MAESTRO INNER JOIN
		                      LISTAEXPDET ON MAESTRO.MA_CODIGO = LISTAEXPDET.MA_CODIGO AND 
		                      MAESTRO.MA_GENERICO <> LISTAEXPDET.MA_GENERICO INNER JOIN
		                      MAESTRO MAESTRO_1 ON MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO
		WHERE     (LISTAEXPDET.LE_CODIGO = @LE_codigo)
	end

	EXEC SP_ACTUALIZAEQARALISTAEXP @LE_codigo
/*
	UPDATE MAESTRO
	SET     MAESTRO.AR_IMPFO=LISTAEXPDET.AR_IMPFO, MAESTRO.AR_EXPMX=LISTAEXPDET.AR_EXPMX,
                      MAESTRO.EQ_EXPMX=LISTAEXPDET.EQ_EXPMX
	FROM         LISTAEXPDET INNER JOIN
	                      MAESTRO ON LISTAEXPDET.MA_CODIGO = MAESTRO.MA_CODIGO
	WHERE     (LISTAEXPDET.LE_CODIGO =@LE_codigo)

*/
























GO
