SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO































CREATE PROCEDURE [dbo].[SP_ACTUALIZAEQARANCELFACTIMPALL] (@FI_fechaini datetime, @FI_fechafin datetime)   as

SET NOCOUNT ON 

if exists (SELECT dbo.FACTIMPDET.AR_IMPMX FROM dbo.FACTIMP INNER JOIN dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) AND dbo.FACTIMPDET.AR_IMPMX>0)
begin
	-- si existe en equivalencias
	if exists (SELECT dbo.FACTIMPDET.EQ_IMPMX FROM dbo.FACTIMPDET INNER JOIN dbo.ARANCEL ON dbo.FACTIMPDET.AR_IMPMX = dbo.ARANCEL.AR_CODIGO INNER JOIN
                      dbo.EQUIVALE ON dbo.FACTIMPDET.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO1 AND dbo.ARANCEL.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO2 INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin)) 

		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_IMPMX=dbo.EQUIVALE.EQ_CANT
		FROM dbo.FACTIMPDET INNER JOIN dbo.ARANCEL ON dbo.FACTIMPDET.AR_IMPMX = dbo.ARANCEL.AR_CODIGO INNER JOIN
                      dbo.EQUIVALE ON dbo.FACTIMPDET.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO1 AND dbo.ARANCEL.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO2 INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO 
		WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 


	-- si la unidad de medida es kilogramos
		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_IMPMX = dbo.FACTIMPDET.FID_PES_UNI
		FROM  dbo.FACTIMPDET INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO
		WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 
			AND dbo.FACTIMPDET.FID_PES_UNI>0  AND dbo.FACTIMPDET.ME_ARIMPMX in (select ME_KILOGRAMOS from configuracion) 

		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_IMPMX = 1
		FROM  dbo.FACTIMPDET INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO
		WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 
			AND (dbo.FACTIMPDET.FID_PES_UNI=0 OR dbo.FACTIMPDET.FID_PES_UNI IS NULL)
			AND dbo.FACTIMPDET.ME_ARIMPMX in (select ME_KILOGRAMOS from configuracion) 


		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_IMPMX = 1
		WHERE (dbo.FACTIMPDET.FID_PES_UNI=0 OR dbo.FACTIMPDET.FID_PES_UNI IS NULL)
		AND dbo.FACTIMPDET.ME_ARIMPMX in (select ME_KILOGRAMOS from configuracion) 


		-- en base a maestromedida
		UPDATE dbo.FACTIMPDET
		SET     dbo.FACTIMPDET.EQ_IMPMX= dbo.MAESTROMEDIDA.EQ_IMPMX
		FROM         dbo.ARANCEL INNER JOIN
		                      dbo.FACTIMPDET INNER JOIN
		                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO INNER JOIN
		                      dbo.MAESTROMEDIDA ON dbo.FACTIMPDET.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
		                      dbo.FACTIMPDET.ME_CODIGO = dbo.MAESTROMEDIDA.ME_CODIGO ON dbo.ARANCEL.AR_CODIGO = dbo.FACTIMPDET.AR_IMPMX AND 
		                      dbo.ARANCEL.ME_CODIGO = dbo.FACTIMPDET.ME_ARIMPMX
		WHERE  (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 
		AND dbo.MAESTROMEDIDA.EQ_IMPMX IS NOT NULL

end


/* factor de conversion de fraccion importacion usa */


if exists (SELECT dbo.FACTIMPDET.AR_EXPFO FROM dbo.FACTIMP INNER JOIN dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) AND (dbo.FACTIMPDET.AR_EXPFO>0))
begin
	-- si existe en equivalencias
	if exists (SELECT dbo.FACTIMPDET.EQ_EXPFO FROM dbo.FACTIMPDET INNER JOIN dbo.ARANCEL ON dbo.FACTIMPDET.AR_EXPFO= dbo.ARANCEL.AR_CODIGO INNER JOIN
                      dbo.EQUIVALE ON dbo.FACTIMPDET.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO1 AND dbo.ARANCEL.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO2 INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO WHERE 
			(dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin))

		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_EXPFO=dbo.EQUIVALE.EQ_CANT
		FROM dbo.FACTIMPDET INNER JOIN dbo.ARANCEL ON dbo.FACTIMPDET.AR_EXPFO= dbo.ARANCEL.AR_CODIGO INNER JOIN
                      dbo.EQUIVALE ON dbo.FACTIMPDET.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO1 AND dbo.ARANCEL.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO2 INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO 
		WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 


	-- si la unidad de medida es kilogramos
		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_EXPFO = dbo.FACTIMPDET.FID_PES_UNI
		FROM  dbo.FACTIMPDET INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO
		WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 
			AND dbo.FACTIMPDET.FID_PES_UNI>0 AND dbo.FACTIMPDET.FID_PES_UNI IS NOT NULL
		AND dbo.FACTIMPDET.AR_EXPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO in (select ME_KILOGRAMOS from configuracion) AND AR_CODIGO=dbo.FACTIMPDET.AR_EXPFO)

		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_EXPFO = 1
		FROM  dbo.FACTIMPDET INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO
		WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 
			AND (dbo.FACTIMPDET.FID_PES_UNI=0 OR dbo.FACTIMPDET.FID_PES_UNI IS NULL)
		AND dbo.FACTIMPDET.AR_EXPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO in (select ME_KILOGRAMOS from configuracion) AND AR_CODIGO=dbo.FACTIMPDET.AR_EXPFO)

		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_EXPFO = 1
		WHERE (dbo.FACTIMPDET.FID_PES_UNI=0 OR dbo.FACTIMPDET.FID_PES_UNI IS NULL)
		AND dbo.FACTIMPDET.AR_EXPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO in (select ME_KILOGRAMOS from configuracion) AND AR_CODIGO=dbo.FACTIMPDET.AR_EXPFO)


end


if exists (SELECT dbo.FACTIMPDET.AR_EXPFO FROM dbo.FACTIMP INNER JOIN dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) AND (dbo.FACTIMPDET.AR_EXPFO>0))
begin
	-- si existe en equivalencias
	if exists (SELECT dbo.FACTIMPDET.EQ_EXPFO2 FROM dbo.FACTIMPDET INNER JOIN dbo.ARANCEL ON dbo.FACTIMPDET.AR_EXPFO= dbo.ARANCEL.AR_CODIGO INNER JOIN
                      dbo.EQUIVALE ON dbo.FACTIMPDET.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO1 AND dbo.ARANCEL.ME_CODIGO2 = dbo.EQUIVALE.ME_CODIGO2 INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO WHERE 
			(dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin))

		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_EXPFO2=dbo.EQUIVALE.EQ_CANT
		FROM dbo.FACTIMPDET INNER JOIN dbo.ARANCEL ON dbo.FACTIMPDET.AR_EXPFO= dbo.ARANCEL.AR_CODIGO INNER JOIN
                      dbo.EQUIVALE ON dbo.FACTIMPDET.ME_CODIGO = dbo.EQUIVALE.ME_CODIGO1 AND dbo.ARANCEL.ME_CODIGO2 = dbo.EQUIVALE.ME_CODIGO2 INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO 
		WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 


	-- si la unidad de medida es kilogramos
		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_EXPFO2 = dbo.FACTIMPDET.FID_PES_UNI
		FROM  dbo.FACTIMPDET INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO
		WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 
			AND dbo.FACTIMPDET.FID_PES_UNI>0 AND dbo.FACTIMPDET.FID_PES_UNI IS NOT NULL
		AND dbo.FACTIMPDET.AR_EXPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion) AND AR_CODIGO=dbo.FACTIMPDET.AR_EXPFO)

		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_EXPFO2 = 1
		FROM  dbo.FACTIMPDET INNER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO
		WHERE (dbo.FACTIMP.FI_FECHA >= @fi_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @fi_fechafin) 
			AND (dbo.FACTIMPDET.FID_PES_UNI=0 OR dbo.FACTIMPDET.FID_PES_UNI IS NULL)
		AND dbo.FACTIMPDET.AR_EXPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion) AND AR_CODIGO=dbo.FACTIMPDET.AR_EXPFO)

		UPDATE dbo.FACTIMPDET
		SET dbo.FACTIMPDET.EQ_EXPFO2 = 1
		WHERE (dbo.FACTIMPDET.FID_PES_UNI=0 OR dbo.FACTIMPDET.FID_PES_UNI IS NULL)
		AND dbo.FACTIMPDET.AR_EXPFO IN (SELECT AR_CODIGO FROM ARANCEL WHERE ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion) AND AR_CODIGO=dbo.FACTIMPDET.AR_EXPFO)


end


/*declare @ar_codigo int, @ar_fraccion varchar(30)

declare cur_actualizaeqarancelfactimpall cursor for
	SELECT dbo.FACTIMPDET.AR_IMPMX 
	FROM dbo.FACTIMP INNER JOIN dbo.FACTIMPDET 
		ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
	WHERE (dbo.FACTIMP.FI_FECHA >= @FI_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @FI_fechafin) 
	UNION 
	SELECT dbo.FACTIMPDET.AR_EXPFO 
	FROM dbo.FACTIMP INNER JOIN dbo.FACTIMPDET 
		ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
	WHERE (dbo.FACTIMP.FI_FECHA >= @FI_fechaini) AND (dbo.FACTIMP.FI_FECHA <= @FI_fechafin) 


open cur_actualizaeqarancelfactimpall


	FETCH NEXT FROM cur_actualizaeqarancelfactimpall INTO @ar_codigo

	WHILE (@@FETCH_STATUS = 0) 
	BEGIN

	select @ar_fraccion=ar_fraccion from arancel where ar_codigo=@ar_codigo

	print '<==========' + convert(varchar(50), @ar_codigo) +' '+ @ar_fraccion + '==========>' 


	EXEC SP_ACTUALIZAEQARANCELFACTIMP @ar_codigo, @FI_fechaini, @FI_fechafin


	FETCH NEXT FROM cur_actualizaeqarancelfactimpall INTO @ar_codigo

END

CLOSE cur_actualizaeqarancelfactimpall
DEALLOCATE cur_actualizaeqarancelfactimpall

*/































GO
