SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE PROCEDURE dbo.SP_EXHIBITC_247( @CS_CODIGO INT)    as

SET NOCOUNT ON 
 /* Eliminar los registros anteriores */
if exists (select * FROM COSTSUBBASC247DET  WHERE CS_CODIGO = @CS_CODIGO)
  DELETE FROM COSTSUBBASC247DET  WHERE CS_CODIGO = @CS_CODIGO

 /* Insertar los registros declarados a partir del exhibit B y el A a Detalle*/
 INSERT  INTO COSTSUBBASC247DET( CS_CODIGO, AR_CODIGO, PA_CODIGO, CSBD_RATE,CSBD_DUTVALWOMPF, CSBD_DUTVALWMPF, MA_NAFTA,
 CSBD_DUTVAL,CSBD_4ACTUAL, CSBD_CANT,  SPI_CODIGO, PU_CODIGO)
/* SELECT CS_CODIGO,AR_CODIGO, PA_CODIGO, ETA_RATE, ETA_WOMPF, ETA_WMPF, MA_NAFTA, (ISNULL(ETA_WOMPF,0)+ ISNULL(ETA_WMPF,0)),
CSA_DUTVALUE, CSB_CANT, SPI_CODIGO, PU_CODIGO
 FROM  VEXHIBIT_CDUTVALDET WHERE  CS_CODIGO = @CS_CODIGO AND ETA_RATE IS NOT NULL*/

SELECT VEXHIBIT_B_BASE247.CS_CODIGO,  VEXHIBIT_B_BASE247.AR_CODIGO,  VEXHIBIT_B_BASE247.PA_CODIGO,  VEXHIBIT_B_BASE247.ETA_RATE, 
    SUM(VEXHIBIT_B_BASE247.ETA_WOMPF) AS ETA_WOMPF,  SUM(VEXHIBIT_B_BASE247.ETA_WMPF) AS ETA_WMPF, 
    MAX(VEXHIBIT_B_BASE247.MA_NAFTA) AS MA_NAFTA,  ISNULL(SUM(VEXHIBIT_B_BASE247.ETA_WOMPF),0) + ISNULL(SUM(VEXHIBIT_B_BASE247.ETA_WMPF),0),
    COSTSUBA.CSA_DUTVALUE, SUM(VEXHIBIT_B_BASE247.ETA_CANT) AS CSB_CANT, MAX(VEXHIBIT_B_BASE247.SPI_CODIGO) AS SPI_CODIGO, 
     VEXHIBIT_B_BASE247.PU_ENTRADA AS PU_CODIGO
FROM VEXHIBIT_B_BASE247 LEFT OUTER JOIN
    COSTSUBA ON 
    VEXHIBIT_B_BASE247.CS_CODIGO = COSTSUBA.CS_CODIGO
WHERE VEXHIBIT_B_BASE247.CS_CODIGO=@CS_CODIGO AND ETA_RATE IS NOT NULL 
GROUP BY VEXHIBIT_B_BASE247.CS_CODIGO, 
    VEXHIBIT_B_BASE247.ETA_RATE, 
    VEXHIBIT_B_BASE247.AR_CODIGO, 
    VEXHIBIT_B_BASE247.PA_CODIGO, 
    VEXHIBIT_B_BASE247.PU_ENTRADA, 
    COSTSUBA.CSA_DUTVALUE

/*========================================  CALCULOS  ==================================*/

-- Update a detalle, de los campos CSBD_3PORCENTO y CSBD_3PORCENTW (se genera calculo)
UPDATE COSTSUBBASC247DET
SET COSTSUBBASC247DET.CSBD_3PORCENTO = ISNULL(COSTSUBBASC247DET.CSBD_DUTVALWOMPF/TOT.DUTVALTOT,0),
        CSBD_3PORCENTW=ISNULL(COSTSUBBASC247DET.CSBD_DUTVALWMPF/TOT.DUTVALTOT,0)
FROM (SELECT SUM(ETA_COS_TOT) AS DUTVALTOT, CS_CODIGO, ET_CODIGO FROM VEXHIBIT_B_BASE247 GROUP BY  CS_CODIGO, ET_CODIGO) AS TOT
WHERE COSTSUBBASC247DET.CS_CODIGO = TOT.CS_CODIGO  AND DUTVALTOT>0
AND COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO


UPDATE COSTSUBBASC247DET
SET CSBD_3TOT = CSBD_3PORCENTW + CSBD_3PORCENTO
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO

UPDATE COSTSUBBASC247DET
SET CSBD_5PRORATIO = CSBD_3PORCENTO * CSBD_4ACTUAL
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO


UPDATE COSTSUBBASC247DET
SET CSBD_5PRORATIW = CSBD_3PORCENTW * CSBD_4ACTUAL
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO


UPDATE COSTSUBBASC247DET
SET CSBD_5TOT = CSBD_5PRORATIO + CSBD_5PRORATIW
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO


UPDATE COSTSUBBASC247DET
SET  CSBD_6DUTYACTUALO = CSBD_5PRORATIO * (CSBD_RATE/100)
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO


UPDATE COSTSUBBASC247DET
SET CSBD_6DUTYACTUALW = CSBD_5PRORATIW * (CSBD_RATE/100)
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO

UPDATE COSTSUBBASC247DET
SET CSBD_6TOT = CSBD_6DUTYACTUALO + CSBD_6DUTYACTUALW
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO

UPDATE COSTSUBBASC247DET
SET  CSBD_7DUTYPAIDO = CSBD_DUTVALWOMPF * (CSBD_RATE/100)
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO


UPDATE COSTSUBBASC247DET
SET CSBD_7DUTYPAIDW = CSBD_DUTVALWMPF * (CSBD_RATE/100)
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO


UPDATE COSTSUBBASC247DET
SET    CSBD_7TOT = CSBD_7DUTYPAIDO + CSBD_7DUTYPAIDW
FROM COSTSUBBASC247DET
WHERE COSTSUBBASC247DET.CS_CODIGO = @CS_CODIGO




GO
