SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


























CREATE PROCEDURE [dbo].[SP_IMPORTACTUALIZAATADOFITYCO] (@TABLA VARCHAR(150), @USER INT)   as



UPDATE FACTIMPDET
SET FACTIMPDET.FID_CANTEMP=1, FACTIMPDET.MA_EMPAQUE=37275
FROM         FACTIMP INNER JOIN
                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO
WHERE FACTIMPDET.FID_INDICED IN 
	(SELECT     MIN(FD2.FID_INDICED)
	FROM         FACTIMP F2 INNER JOIN
	                      FACTIMPDET FD2 ON F2.FI_CODIGO = FD2.FI_CODIGO
	WHERE F2.FI_CODIGO=FACTIMPDET.FI_CODIGO
	GROUP BY FD2.FID_OBSERVA, F2.FI_FOLIO)
AND FACTIMP.FI_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FI_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FI_FOLIO%' AND RI_TIPO='I')


Declare @X Int,@POS Varchar(100)

	Select FID_INDICED,FI_CODIGO,FID_RELCAJAS 
	Into dbo.[#TempX] 
	From FACTIMPDET 
	where Not FID_OBSERVA is NULL
	AND FID_CANTEMP=1
	AND FI_CODIGO IN (SELECT FI_CODIGO FROM FACTIMP WHERE FACTIMP.FI_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FI_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FI_FOLIO%' AND RI_TIPO='I'))
	Order by FID_INDICED


	
	SET @X=0
	SET @POS=''
	
	Update #Tempx 
	SET FID_RELCAJAS=@X,@X=CASE WHEN @POS = FI_CODIGO THEN @X+1 ELSE 1 END,@POS=CASE WHEN @POS = FI_CODIGO THEN @POS ELSE FI_CODIGO END
	
	
	Update FACTIMPDET 
	SET FID_RELCAJAS=T.FID_RELCAJAS 
	From #Tempx T inner join FACTIMPDET on T.FID_INDICED=FACTIMPDET.FID_INDICED
	WHERE FACTIMPDET.FI_CODIGO IN (SELECT FI_CODIGO FROM FACTIMP WHERE FACTIMP.FI_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FI_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FI_FOLIO%' AND RI_TIPO='I'))


UPDATE FACTIMP
SET FI_TOTALB=
	ISNULL((SELECT     SUM(FACTIMPDET.FID_CANTEMP)
	FROM         FACTIMPDET
	WHERE FACTIMPDET.FI_CODIGO=FACTIMP.FI_CODIGO),0)
WHERE FACTIMP.FI_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FI_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FI_FOLIO%' AND RI_TIPO='I')




UPDATE FACTIMP
SET     FI_INVOICETYPE=
                          (SELECT     FI_INVOICETYPE
                            FROM          CLIENTE
                            WHERE      CL_EMPRESA = 'S'), 
FI_FOOTER=
                          (SELECT     FI_FOOTER
                            FROM          CLIENTE
                            WHERE      CL_EMPRESA = 'S'), 
FI_HEADER=
                          (SELECT     FI_HEADER
                            FROM          CLIENTE
                            WHERE      CL_EMPRESA = 'S'), 
FI_DESCRIPTION1=
                          (SELECT     FI_DESC_GRAL
                            FROM          CLIENTE
                            WHERE      CL_EMPRESA = 'S'),
FI_DESCRIPTION2=''
FROM         FACTIMP
WHERE FACTIMP.FI_FOLIO IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FI_FOLIO = ','') 
					FROM REGISTROSIMPORTADOS
					WHERE RI_REGISTRO LIKE 'FI_FOLIO%' AND RI_TIPO='I')

























GO
