SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

/* inserta en la tabla TempBOM_NIVEL  para calculo de costos de todos los productos*/
CREATE PROCEDURE [dbo].[SP_FILL_BOM_UNNIVEL] (@FECHA_STRUCT varchar(20), @PARTES VARCHAR(8000), @BorrarTabla char(1)='S')   as

--SET NOCOUNT ON 



exec('exec sp_CreaTEMPBOM_UNNIVEL

	delete from bom_struct where bsu_subensamble = bst_hijo ')


	if @BorrarTabla='S'
	truncate table TEMPBOM_UNNIVEL 

exec('DECLARE @existe INT, @BST_TIPODESC CHAR(1), @NIVEL SMALLINT
	/*if (select COUNT(*) from bom_struct where ti_codigo is null)	>0
	UPDATE BOM_STRUCT
	SET     BOM_STRUCT.TI_CODIGO=MAESTRO.TI_CODIGO
	FROM         BOM_STRUCT INNER JOIN
	                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO
	WHERE  BOM_STRUCT.TI_CODIGO<>MAESTRO.TI_CODIGO OR (BOM_STRUCT.TI_CODIGO IS NULL)
	*/



	SET @NIVEL=1

			


		insert into TEMPBOM_UNNIVEL(BST_HIJO, BST_INCORPORTOTAL, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, 
		    BST_PERFIN, ME_GEN, MA_TIP_ENS, BST_NIVEL, BST_PERTENECE, BST_PT, BST_ENTRAVIGOR, BST_PTNOPARTE,
			BST_HIJONOPARTE, BST_PTNOMBRE, BST_HIJONOMBRE)

		SELECT     BOM_STRUCT.BST_HIJO, BOM_STRUCT.BST_INCORPOR, BOM_STRUCT.BST_INCORPOR,
			         ''BST_DISCH''=case when BOM_STRUCT.BST_TIP_ENS = ''F'' then ''N'' else BOM_STRUCT.BST_DISCH end,
		                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
		                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, 
		                      REPLACE(BOM_STRUCT.BST_TIP_ENS,''A'',''F''), ''1'', 
			        BOM_STRUCT.BSU_SUBENSAMBLE, BOM_STRUCT.BSU_SUBENSAMBLE, '+@FECHA_STRUCT+' , BOM_STRUCT.BSU_NOPARTE, 
			        BOM_STRUCT.BST_NOPARTE, ISNULL(MAESTRO.MA_NOMBRE,MAESTROREFER.MA_NOMBRE), ISNULL(MAESTROSUB.MA_NOMBRE, MAESTROSUBREFER.MA_NOMBRE)
		FROM         BOM_STRUCT LEFT OUTER JOIN
		                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO  LEFT OUTER JOIN
		                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
		                      MAESTRO MAESTROSUB ON BOM_STRUCT.BSU_SUBENSAMBLE = MAESTROSUB.MA_CODIGO  LEFT OUTER JOIN
		                      MAESTROREFER ON BOM_STRUCT.BST_HIJO = MAESTROREFER.MA_CODIGO  LEFT OUTER JOIN
		                      MAESTROREFER MAESTROSUBREFER ON BOM_STRUCT.BSU_SUBENSAMBLE = MAESTROSUBREFER.MA_CODIGO
		WHERE     BOM_STRUCT.BSU_NOPARTE IN ('+@PARTES+')
			AND (BOM_STRUCT.BST_HIJO IS NOT NULL) 
			AND (BOM_STRUCT.BST_INCORPOR > 0) AND BOM_STRUCT.BST_PERINI <='+@FECHA_STRUCT+'  AND 
			BOM_STRUCT.BST_PERFIN >= '+@FECHA_STRUCT+' 




		inicio0:
	
		SET @nivel=@nivel+1

	
				insert into TEMPBOM_UNNIVEL (BST_HIJO, BST_INCORPORTOTAL, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, 
				    FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, MA_TIP_ENS, BST_NIVEL, BST_PT, BST_PERTENECE, BST_ENTRAVIGOR, BST_PTNOPARTE,
				BST_HIJONOPARTE, BST_PTNOMBRE, BST_HIJONOMBRE)
	
				SELECT     BOM_STRUCT.BST_HIJO, TEMPBOM_UNNIVEL.BST_INCORPORTOTAL * BOM_STRUCT.BST_INCORPOR AS BST_INCORPORTOTAL, 
					   TEMPBOM_UNNIVEL.BST_INCORPOR, ''BST_DISCH''=case when BOM_STRUCT.BST_TIP_ENS = ''F'' then ''N'' else BOM_STRUCT.BST_DISCH end,
				                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
				                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, REPLACE(BOM_STRUCT.BST_TIP_ENS,''A'',''F''), CONVERT(VARCHAR(20),@nivel), 
					        BST_PT, BSU_SUBENSAMBLE, BST_ENTRAVIGOR,  BST_PTNOPARTE, 
			       		        BOM_STRUCT.BST_NOPARTE, ISNULL(MAESTRO.MA_NOMBRE,MAESTROREFER.MA_NOMBRE), ISNULL(MAESTROSUB.MA_NOMBRE, MAESTROSUBREFER.MA_NOMBRE)
				FROM         TEMPBOM_UNNIVEL INNER JOIN
	                      		BOM_STRUCT ON TEMPBOM_UNNIVEL.BST_HIJO = BOM_STRUCT.BSU_SUBENSAMBLE AND
				                      BOM_STRUCT.BST_PERINI <= TEMPBOM_UNNIVEL.BST_ENTRAVIGOR AND 
				                      BOM_STRUCT.BST_PERFIN >= TEMPBOM_UNNIVEL.BST_ENTRAVIGOR LEFT OUTER JOIN
				                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO  LEFT OUTER JOIN
				                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
				                      MAESTRO MAESTROSUB ON TEMPBOM_UNNIVEL.BST_PT = MAESTROSUB.MA_CODIGO LEFT OUTER JOIN
				                      MAESTROREFER ON BOM_STRUCT.BST_HIJO = MAESTROREFER.MA_CODIGO  LEFT OUTER JOIN
				                      MAESTROREFER MAESTROSUBREFER ON TEMPBOM_UNNIVEL.BST_PT = MAESTROSUBREFER.MA_CODIGO
				WHERE (TEMPBOM_UNNIVEL.MA_TIP_ENS =''F'' OR TEMPBOM_UNNIVEL.MA_TIP_ENS IS NULL)
					AND CONVERT(INT,TEMPBOM_UNNIVEL.BST_NIVEL)=@nivel-1
				AND BOM_STRUCT.BST_HIJO IS NOT NULL AND BOM_STRUCT.BST_INCORPOR > 0


			if (SELECT     COUNT(*)
			    FROM         TEMPBOM_UNNIVEL
			    WHERE     CONVERT(INT,TEMPBOM_UNNIVEL.BST_NIVEL) =@nivel-1
			    AND (TI_CODIGO=''S'' OR TI_CODIGO=''P'') 
			    AND MA_TIP_ENS<>''P'' AND MA_TIP_ENS<>''C'')>0
	
			set @existe=1
			else
			set @existe=0
	
	
		while (@existe>0)	
		begin
	
			goto inicio0
	
	
		end


		delete from TEMPBOM_UNNIVEL where BST_DISCH=''N''
')
GO
