SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




























-- Created by MLOPEZ
CREATE PROCEDURE dbo.SP_HAYDOCUMENTOS (@FACTAGRUPADA INTEGER, @TIPO CHAR, @EXISTE CHAR OUTPUT)   as

BEGIN
    --  VALORES PARA  @EXISTE
    --
    --    'S'  -- Sin Documentos 
    --    'C'  -- Con Documentos

    DECLARE @TEMP  INTEGER
    SET @EXISTE = 'S'
    IF @TIPO = 'X'
    BEGIN
--        SET  @TEMP = (SELECT  COUNT(*) FROM ENTRYSUM WHERE FE_CODIGO = @FACTAGRUPADA AND ET_TIPOFACT = 'A')
--        IF @TEMP > 0 SET @EXISTE = 'C'
        SET @TEMP = (SELECT COUNT(*) FROM COMMINV WHERE FE_CODIGO = @FACTAGRUPADA AND IV_TIPOFACT = 'A')
        IF @TEMP > 0 SET @EXISTE = 'C'
        SET @TEMP = (SELECT COUNT(*)  FROM CANADACINV WHERE FE_CODIGO = @FACTAGRUPADA AND CD_TIPOFACT = 'A')
        IF @TEMP > 0 SET @EXISTE = 'C'
    END
END



GO
