SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE dbo.SP_TMP ( @VALOR INTEGER)   as

BEGIN 
    INSERT INTO TVALORA (TV_CODIGO,TV_CLAVE) 
    SELECT @VALOR, AD_CLAVE FROM ADUANA WHERE AD_CODIGO IN ( 1,2,3);
END;


GO
