SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_PREVIADESCFALTANTES] (@FE_CODIGO VARCHAR(50))   as



--Yolanda Avila (2009-11-16)  --Regreso de version a la 33
--exec('exec sp_droptable ''TempFaltantes'+@fe_codigo+'''')
exec('if exists (SELECT name FROM dbo.sysobjects WHERE dbo.sysobjects.name = ''TempFaltantes'+@fe_codigo+''') drop table TempFaltantes'+@fe_codigo+'')
exec('CREATE TABLE [dbo].[TempFaltantes'+@fe_codigo+'] (
	[Codigo] [int] IDENTITY (1, 1) NOT NULL ,
	[FE_FOLIO] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FE_FECHA] [datetime] NULL,
	[TF_NOMBRE] [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BST_HIJO] [int] NULL,
	[BST_NOPARTE] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MA_NOMBRE] [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GRUPOGEN] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PA_CORTO] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ME_CORTOGEN] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOPARTEPADRE] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FED_CANT] decimal(38,6) NULL,
	[BST_INCORPORGEN] decimal(38,6) NULL,
	[CANT_A_DESC] decimal(38,6) NULL ,
	[SALDOACTUAL] decimal(38,6) NULL ,
	[SALDONVO] decimal(38,6) NULL ,
		CONSTRAINT [IX_TempFaltantes'+@fe_codigo+'] UNIQUE  NONCLUSTERED 
		(
			[Codigo]
		) WITH  FILLFACTOR = 90  ON [PRIMARY] 
) ON [PRIMARY]')


exec('INSERT INTO TempFaltantes'+@fe_codigo+'(FE_FOLIO, FE_FECHA, TF_NOMBRE, BST_HIJO, BST_NOPARTE, MA_NOMBRE, GRUPOGEN, PA_CORTO, ME_CORTOGEN, 
                      NOPARTEPADRE, FED_CANT, BST_INCORPORGEN, CANT_A_DESC)

SELECT     TOP 100 PERCENT FACTEXP.FE_FOLIO, FACTEXP.FE_FECHA, TFACTURA.TF_NOMBRE, BOM_DESCTEMP.BST_HIJO, MAESTRO_2.MA_NOPARTE AS BST_NOPARTE, 
                      MAESTRO_2.MA_NOMBRE, MAESTRO_3.MA_NOPARTE AS GRUPOGEN, PAIS.PA_CORTO, MEDIDA.ME_CORTO, 
                      FACTEXPDET.FED_NOPARTE AS NOPARTEPADRE, ROUND(SUM(BOM_DESCTEMP.FED_CANT),6) AS FED_CANT, 
                      ROUND(SUM(BOM_DESCTEMP.BST_INCORPOR * ISNULL(BOM_DESCTEMP.FACTCONV, 1)),6) AS BST_INCORPORGEN, 
                      ROUND(SUM(BOM_DESCTEMP.FED_CANT * BOM_DESCTEMP.BST_INCORPOR * ISNULL(BOM_DESCTEMP.FACTCONV, 1)),6) 
                      AS CANT_A_DESC
FROM         dbo.PAIS RIGHT OUTER JOIN
                      dbo.MAESTRO MAESTRO_2 ON dbo.PAIS.PA_CODIGO = MAESTRO_2.PA_ORIGEN LEFT OUTER JOIN
                      dbo.MAESTRO MAESTRO_3 ON MAESTRO_2.MA_GENERICO = MAESTRO_3.MA_CODIGO RIGHT OUTER JOIN
                      dbo.BOM_DESCTEMP INNER JOIN
                      dbo.FACTEXP ON dbo.BOM_DESCTEMP.FE_CODIGO = dbo.FACTEXP.FE_CODIGO INNER JOIN
                      dbo.TFACTURA ON dbo.FACTEXP.TF_CODIGO = dbo.TFACTURA.TF_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_DESCTEMP.BST_PT = MAESTRO_1.MA_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.BOM_DESCTEMP.ME_GEN = dbo.MEDIDA.ME_CODIGO ON 
                      MAESTRO_2.MA_CODIGO = dbo.BOM_DESCTEMP.BST_HIJO LEFT OUTER JOIN
                      dbo.FACTEXPDET ON dbo.BOM_DESCTEMP.FED_INDICED = dbo.FACTEXPDET.FED_INDICED
WHERE     (BOM_DESCTEMP.BST_DISCH = ''S'') AND (BOM_DESCTEMP.FE_CODIGO = '+@fe_codigo+')
GROUP BY MAESTRO_2.MA_NOPARTE, MAESTRO_1.MA_NOPARTE, FACTEXP.FE_FOLIO, FACTEXP.FE_FECHA, TFACTURA.TF_NOMBRE, 
                      MEDIDA.ME_CORTO, MAESTRO_3.MA_NOPARTE, PAIS.PA_CORTO, MAESTRO_2.MA_NOMBRE, BOM_DESCTEMP.BST_HIJO, FACTEXPDET.FED_NOPARTE
ORDER BY BST_NOPARTE, NOPARTEPADRE')


exec('UPDATE TempFaltantes'+@fe_codigo+' SET SALDOACTUAL=
	isnull((SELECT 	round(SUM((PID_SALDOGEN-ISNULL(PID_CONGELASUBMAQ,0))),6)
	FROM         PIDescarga 
	WHERE     (PI_DEFINITIVO =''N'') AND (PI_ACTIVOFIJO = ''N'') 
	AND (PID_SALDOGEN-ISNULL(PID_CONGELASUBMAQ,0))>0
	AND PIDescarga.PID_SALDOGEN > 0 AND PI_FEC_ENT<=FE_FECHA 
	AND PIDescarga.pid_fechavence>=FE_FECHA
	AND PIDescarga.ma_codigo=BST_HIJO),0)')




	EXEC('Select CODIGO, BST_HIJO, SALDOACTUAL, SALDONVO, CANT_A_DESC, CANT_A_DESC AS CANT_A_DESCSUM
	Into dbo.[#TempFaltantes] 
	From TempFaltantes'+@fe_codigo+'  
	Order by BST_HIJO, CODIGO

	
	
	Declare @SALDO Int, @POS int, @CANT_A_DESCSUM decimal(38,6)

	SET @SALDO=0
	SET @POS=0

	Update #TempFaltantes 
	SET CANT_A_DESCSUM =round(ISNULL((SELECT SUM(T.CANT_A_DESC) FROM  #TempFaltantes T WHERE T.BST_HIJO=#TempFaltantes.BST_HIJO AND T.CODIGO<#TempFaltantes.CODIGO),0),6) 
	

	Update #TempFaltantes 
	SET SALDOACTUAL=CASE WHEN @POS = BST_HIJO THEN round(SALDOACTUAL-CANT_A_DESCSUM,6) ELSE SALDOACTUAL END, 
	@POS=CASE WHEN @POS = BST_HIJO THEN @POS ELSE BST_HIJO END,
	SALDONVO=(CASE WHEN SALDOACTUAL=0 THEN 0 - (CANT_A_DESCSUM+CANT_A_DESC) ELSE 
		round((CASE WHEN @POS = BST_HIJO THEN round(SALDOACTUAL-CANT_A_DESCSUM,6) ELSE SALDOACTUAL END)-CANT_A_DESC,6) END)



	Update TempFaltantes'+@fe_codigo+'  
	SET SALDOACTUAL=T.SALDOACTUAL,
	SALDONVO=T.SALDONVO
	From #TempFaltantes T inner join TempFaltantes'+@fe_codigo+'   on T.CODIGO=TempFaltantes'+@fe_codigo+' .CODIGO')



	
	exec('SELECT     BST_HIJO, SUM(FED_CANT) AS FED_CANT, SUM(CANT_A_DESC) AS CANT_A_DESC,
	(SELECT MAX(T1.CODIGO) FROM TempFaltantes'+@fe_codigo+'  T1 WHERE T1.BST_HIJO=TempFaltantes'+@fe_codigo+'.BST_HIJO) AS CODIGOMAX,
	(SELECT MIN(T2.CODIGO) FROM TempFaltantes'+@fe_codigo+'  T2 WHERE T2.BST_HIJO=TempFaltantes'+@fe_codigo+'.BST_HIJO) AS CODIGOMIN, BST_NOPARTE
	INTO dbo.[#MAXIMO]
	FROM         TempFaltantes'+@fe_codigo+' 
	GROUP BY BST_HIJO, BST_NOPARTE
	
	INSERT INTO TempFaltantes'+@fe_codigo+'(BST_HIJO,  FED_CANT, CANT_A_DESC, SALDONVO, SALDOACTUAL, MA_NOMBRE, BST_NOPARTE)
	SELECT BST_HIJO,  FED_CANT, CANT_A_DESC, (SELECT SALDONVO FROM TempFaltantes'+@fe_codigo+' WHERE CODIGO=CODIGOMAX),
	(SELECT SALDOACTUAL FROM TempFaltantes'+@fe_codigo+' WHERE CODIGO=CODIGOMIN), ''  TOTALES  '', BST_NOPARTE
	FROM #MAXIMO')

GO
