SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO































CREATE PROCEDURE [dbo].[SP_ACTUALIZATASAPCKLISTF1]   as

SET NOCOUNT ON 


	if not exists(select * from arancel where convert(varchar(11),AR_ULTMODIFTIGIE,101)= convert(varchar(11),getdate(),101))
	exec SP_ACTUALIZAARANCELBASETIGIE


	-- actualiza tasas
	UPDATE PCKLISTDET  
	SET PCKLISTDET.PLD_POR_DEF= ARANCEL.AR_ADVDEF, PCKLISTDET.SPI_CODIGO=0, 
	PCKLISTDET.PLD_SEC_IMP=0 
	FROM  PCKLISTDET INNER JOIN 
	  ARANCEL ON PCKLISTDET.AR_IMPMX = ARANCEL.AR_CODIGO 
	WHERE     (PCKLISTDET.PLD_DEF_TIP = 'G') AND PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%')
	AND PCKLISTDET.PLD_SALDO >0
	
	UPDATE PCKLISTDET  
	SET PCKLISTDET.PLD_POR_DEF= ARANCEL.AR_PORCENT_8VA, PCKLISTDET.SPI_CODIGO=0, 
	PCKLISTDET.PLD_SEC_IMP=0 
	FROM  PCKLISTDET INNER JOIN 
	  ARANCEL ON PCKLISTDET.AR_IMPMX = ARANCEL.AR_CODIGO 
	WHERE     (PCKLISTDET.PLD_DEF_TIP = 'R') AND PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%')
	AND PCKLISTDET.PLD_SALDO >0
	
	UPDATE PCKLISTDET  
	SET PCKLISTDET.PLD_POR_DEF= PAISARA.PAR_BEN, PCKLISTDET.PLD_SEC_IMP=0, PCKLISTDET.SPI_CODIGO=22 
	FROM PCKLISTDET INNER JOIN 
	PAISARA ON PCKLISTDET.AR_IMPMX = PAISARA.AR_CODIGO AND PCKLISTDET.PA_CODIGO = PAISARA.PA_CODIGO 
	WHERE (PCKLISTDET.PLD_DEF_TIP = 'P') AND PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%')
	AND PCKLISTDET.PA_CODIGO =233 	AND PCKLISTDET.PLD_SALDO >0

	UPDATE PCKLISTDET  
	SET PCKLISTDET.PLD_POR_DEF= PAISARA.PAR_BEN, PCKLISTDET.PLD_SEC_IMP=0
	FROM PCKLISTDET INNER JOIN 
	PAISARA ON PCKLISTDET.AR_IMPMX = PAISARA.AR_CODIGO AND PCKLISTDET.SPI_CODIGO = PAISARA.SPI_CODIGO 
	WHERE (PCKLISTDET.PLD_DEF_TIP = 'P') AND PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%')
	AND PCKLISTDET.PA_CODIGO <>233 	AND PCKLISTDET.PLD_SALDO >0



	UPDATE PCKLISTDET
	SET     PCKLISTDET.PLD_SEC_IMP= (SELECT SE_CODIGO FROM CONFIGURACION)
	FROM         PCKLISTDET
	WHERE     (PCKLISTDET.PLD_DEF_TIP = 'S') AND (PCKLISTDET.PLD_SEC_IMP = 0 OR
	                      PCKLISTDET.PLD_SEC_IMP IS NULL) AND (PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))
	AND PCKLISTDET.PLD_SALDO >0

	UPDATE PCKLISTDET
	SET     PCKLISTDET.PLD_SEC_IMP= MAESTRO.MA_SEC_IMP
	FROM         PCKLISTDET INNER JOIN
	                      MAESTRO ON PCKLISTDET.MA_CODIGO = MAESTRO.MA_CODIGO
	WHERE     (PCKLISTDET.PLD_DEF_TIP = 'S') AND (PCKLISTDET.PLD_SEC_IMP = 0 OR
	                      PCKLISTDET.PLD_SEC_IMP IS NULL) AND (MAESTRO.MA_SEC_IMP > 0) AND (PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))
	AND PCKLISTDET.PLD_SALDO >0
	
	UPDATE PCKLISTDET  
	SET   PCKLISTDET.PLD_POR_DEF= SECTORARA.SA_PORCENT, PCKLISTDET.SPI_CODIGO=0 
	FROM  PCKLISTDET INNER JOIN 
	 SECTORARA ON PCKLISTDET.AR_IMPMX = SECTORARA.AR_CODIGO AND 
	 PCKLISTDET.PLD_SEC_IMP = SECTORARA.SE_CODIGO 
	WHERE (PCKLISTDET.PLD_DEF_TIP = 'S') AND PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%') 
	AND PCKLISTDET.PLD_SALDO >0


	if (SELECT CF_SINGENERICOUM FROM CONFIGURACION)='S'
	and exists (SELECT MA_GENERICO FROM PCKLISTDET WHERE MA_GENERICO = 0 AND PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%') AND AR_IMPMX > 0)
	begin
		EXEC SP_ADDGENERICOS
	
		UPDATE PCKLISTDET
		SET     PCKLISTDET.MA_GENERICO= MAESTRO.MA_GENERICO, PCKLISTDET.EQ_GEN= MAESTRO.EQ_GEN, PCKLISTDET.ME_GEN= 
		                      MAESTRO_1.ME_COM
		FROM         MAESTRO INNER JOIN
		                      PCKLISTDET ON MAESTRO.MA_CODIGO = PCKLISTDET.MA_CODIGO AND 
		                      MAESTRO.MA_GENERICO <> PCKLISTDET.MA_GENERICO INNER JOIN
		                      MAESTRO MAESTRO_1 ON MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO
		WHERE     (PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))
		AND PCKLISTDET.PLD_SALDO >0
	end


	-- se actualizan factores de conversion
		UPDATE PCKLISTDET
		SET ME_ARIMPMX=isnull((SELECT ME_CODIGO FROM ARANCEL WHERE AR_CODIGO=PCKLISTDET.AR_IMPMX),0)
		WHERE PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%')

		if exists (SELECT     dbo.PCKLISTDET.EQ_IMPMX
			FROM         dbo.EQUIVALE INNER JOIN
			                      dbo.PCKLISTDET ON dbo.EQUIVALE.ME_CODIGO2 = dbo.PCKLISTDET.ME_ARIMPMX AND 
			                      dbo.EQUIVALE.ME_CODIGO1 = dbo.PCKLISTDET.ME_CODIGO INNER JOIN
			                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO
				WHERE     (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%')))

			UPDATE dbo.PCKLISTDET
			SET dbo.PCKLISTDET.EQ_IMPMX=dbo.EQUIVALE.EQ_CANT
			FROM         dbo.EQUIVALE INNER JOIN
			                      dbo.PCKLISTDET ON dbo.EQUIVALE.ME_CODIGO2 = dbo.PCKLISTDET.ME_ARIMPMX AND 
			                      dbo.EQUIVALE.ME_CODIGO1 = dbo.PCKLISTDET.ME_CODIGO INNER JOIN
			                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO
				WHERE     (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))



		-- ME_ARIMPMX igual a Kg
		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_IMPMX = dbo.PCKLISTDET.PLD_PES_UNI
		FROM  dbo.PCKLISTDET INNER JOIN
                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO
		WHERE (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))
			AND dbo.PCKLISTDET.PLD_PES_UNI>0 AND dbo.PCKLISTDET.ME_ARIMPMX in (select ME_KILOGRAMOS from configuracion) 

		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_IMPMX = 1
		FROM  dbo.PCKLISTDET INNER JOIN
                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO
		WHERE (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))
			AND (dbo.PCKLISTDET.PLD_PES_UNI is null or  dbo.PCKLISTDET.PLD_PES_UNI=0) 
			AND dbo.PCKLISTDET.ME_ARIMPMX in (select ME_KILOGRAMOS from configuracion) 
			AND dbo.PCKLISTDET.ME_CODIGO not in (SELECT ME_CODIGO1 FROM EQUIVALE
			WHERE     ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))


		-- en base a maestromedida
		UPDATE dbo.PCKLISTDET
		SET     dbo.PCKLISTDET.EQ_IMPMX= dbo.MAESTROMEDIDA.EQ_CANTIDAD
		FROM         dbo.MAESTRO MAESTRO_1 INNER JOIN
	                      dbo.MAESTRO ON MAESTRO_1.MA_CODIGO = dbo.MAESTRO.MA_GENERICO INNER JOIN
	                      dbo.PCKLISTDET INNER JOIN
	                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN
	                      dbo.MAESTROMEDIDA ON dbo.PCKLISTDET.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
	                      dbo.PCKLISTDET.ME_CODIGO = dbo.MAESTROMEDIDA.ME_CODIGO ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
	                      MAESTRO_1.ME_COM = dbo.PCKLISTDET.ME_ARIMPMX
		WHERE (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))

		-- sin factor de conversion
		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_IMPMX = 1
		WHERE (dbo.PCKLISTDET.EQ_IMPMX=0 OR dbo.PCKLISTDET.EQ_IMPMX IS NULL)
		AND (dbo.PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))

		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_IMPMX = 1
		WHERE (dbo.PCKLISTDET.EQ_IMPMX<>1 )
		AND dbo.PCKLISTDET.ME_ARIMPMX=dbo.PCKLISTDET.ME_CODIGO
		AND (dbo.PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))

/* =========================================================== EQ_EXPFO =====================================================*/
		-- existe en equivalencias
		if exists (SELECT     dbo.PCKLISTDET.EQ_EXPFO
				FROM         dbo.EQUIVALE INNER JOIN
				                      dbo.PCKLISTDET ON dbo.EQUIVALE.ME_CODIGO1 = dbo.PCKLISTDET.ME_CODIGO INNER JOIN
				                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN
				                      dbo.ARANCEL ON dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO AND dbo.EQUIVALE.ME_CODIGO2 = dbo.ARANCEL.ME_CODIGO
				WHERE     (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%')))


			UPDATE dbo.PCKLISTDET
			SET dbo.PCKLISTDET.EQ_EXPFO=dbo.EQUIVALE.EQ_CANT
				FROM         dbo.EQUIVALE INNER JOIN
				                      dbo.PCKLISTDET ON dbo.EQUIVALE.ME_CODIGO1 = dbo.PCKLISTDET.ME_CODIGO INNER JOIN
				                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN
				                      dbo.ARANCEL ON dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO AND dbo.EQUIVALE.ME_CODIGO2 = dbo.ARANCEL.ME_CODIGO
				WHERE     (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))



		-- ME_ARIMPMX igual a Kg
		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_EXPFO = dbo.PCKLISTDET.PLD_PES_UNI
		FROM  dbo.PCKLISTDET INNER JOIN
                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN ARANCEL ON
		      dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO 			
		WHERE (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))
			AND dbo.PCKLISTDET.PLD_PES_UNI>0 AND dbo.ARANCEL.ME_CODIGO in (select ME_KILOGRAMOS from configuracion) 

		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_EXPFO = 1
		FROM  dbo.PCKLISTDET INNER JOIN
                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN ARANCEL ON
		      dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO 			
		WHERE (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))
			AND (dbo.PCKLISTDET.PLD_PES_UNI is null or  dbo.PCKLISTDET.PLD_PES_UNI=0) 
			AND dbo.ARANCEL.ME_CODIGO in (select ME_KILOGRAMOS from configuracion) 
			AND dbo.PCKLISTDET.ME_CODIGO not in (SELECT ME_CODIGO1 FROM EQUIVALE
			WHERE     ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))


		-- en base a maestromedida
		UPDATE dbo.PCKLISTDET
		SET     dbo.PCKLISTDET.EQ_EXPFO= dbo.MAESTROMEDIDA.EQ_CANTIDAD
		FROM         dbo.MAESTRO MAESTRO_1 INNER JOIN
	                      dbo.MAESTRO ON MAESTRO_1.MA_CODIGO = dbo.MAESTRO.MA_GENERICO INNER JOIN
	                      dbo.PCKLISTDET INNER JOIN
	                      dbo.PCKLIST ON dbo.PCKLISTDET.PL_CODIGO = dbo.PCKLIST.PL_CODIGO INNER JOIN
	                      dbo.MAESTROMEDIDA ON dbo.PCKLISTDET.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO AND 
	                      dbo.PCKLISTDET.ME_CODIGO = dbo.MAESTROMEDIDA.ME_CODIGO ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTROMEDIDA.MA_CODIGO INNER JOIN
	                      dbo.ARANCEL ON dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO AND MAESTRO_1.ME_COM = dbo.ARANCEL.ME_CODIGO
		WHERE (dbo.PCKLIST.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))


	
		-- sin factor de conversion
		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_EXPFO = 1
		WHERE (dbo.PCKLISTDET.EQ_EXPFO=0 OR dbo.PCKLISTDET.EQ_EXPFO IS NULL)
		AND (dbo.PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))

		UPDATE dbo.PCKLISTDET
		SET dbo.PCKLISTDET.EQ_EXPFO = 1
		FROM dbo.PCKLISTDET INNER JOIN
	                      dbo.ARANCEL ON dbo.PCKLISTDET.AR_EXPFO = dbo.ARANCEL.AR_CODIGO 
		WHERE (dbo.PCKLISTDET.EQ_EXPFO<>1 )
		AND dbo.ARANCEL.ME_CODIGO=dbo.PCKLISTDET.ME_CODIGO
		AND (dbo.PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))



/*



	UPDATE MAESTRO
	SET     MAESTRO.AR_IMPMX=PCKLISTDET.AR_IMPMX, MAESTRO.AR_EXPMX=PCKLISTDET.AR_IMPMX,  
		         MAESTRO.MA_SEC_IMP=PCKLISTDET.PLD_SEC_IMP, 
	                      MAESTRO.MA_DEF_TIP=PCKLISTDET.PLD_DEF_TIP, 
	                      MAESTRO.SPI_CODIGO=PCKLISTDET.SPI_CODIGO, MAESTRO.EQ_IMPMX=PCKLISTDET.EQ_IMPMX
	FROM         PCKLISTDET INNER JOIN
	                      MAESTRO ON PCKLISTDET.MA_CODIGO = MAESTRO.MA_CODIGO
	WHERE     (PCKLISTDET.PL_CODIGO in (select fi_codigo from FolioFile1 where FileType like 'FIL1V%'))


*/
























GO
