SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE dbo.SP_DELREL_FACTIMPEMP     as

BEGIN
	DELETE  FROM FACTIMPRELEMPAQUE
	 WHERE FID_INDICED NOT IN
	 (SELECT FACTIMPRELEMPAQUE.FID_INDICED FROM FACTIMPRELEMPAQUE,FACTIMPDET 
	WHERE FACTIMPRELEMPAQUE.FID_INDICED = FACTIMPDET.FID_INDICED);

	DELETE FROM  FACTIMPRELEMPAQUE
	 WHERE FIE_INDICE NOT IN (SELECT FACTIMPRELEMPAQUE.FIE_INDICE
	 FROM FACTIMPRELEMPAQUE,FACTIMPEMPAQUE 
	WHERE FACTIMPRELEMPAQUE.FIE_INDICE = FACTIMPEMPAQUE.FIE_INDICE);
END



GO
