SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[CopiaCostos] (@BDOrigen varchar(50), @BDDestino varchar(50))    as


		EXEC('INSERT INTO MAESTROCOST (MA_CODIGO, TCO_CODIGO, MA_GRAV_MP, MA_GRAV_ADD, MA_GRAV_EMP, MA_GRAV_GI, MA_GRAV_GI_MX, MA_GRAV_MO, 
	                      MA_NG_MP, MA_NG_ADD, MA_NG_EMP, MA_COSTO, MA_GRAVA_VA, MA_NG_USA, TV_CODIGO, DV_CODIGO, 
	                      SPI_CODIGO, MA_PERINI, MA_PERFIN, MA_NG_MX)
	
		SELECT     MAESTRO_1.MA_CODIGO, MAESTROCOSTOrig.TCO_CODIGO, MAESTROCOSTOrig.MA_GRAV_MP, MAESTROCOSTOrig.MA_GRAV_ADD, 
		                      MAESTROCOSTOrig.MA_GRAV_EMP, MAESTROCOSTOrig.MA_GRAV_GI, MAESTROCOSTOrig.MA_GRAV_GI_MX, MAESTROCOSTOrig.MA_GRAV_MO, 
		                      MAESTROCOSTOrig.MA_NG_MP, MAESTROCOSTOrig.MA_NG_ADD, MAESTROCOSTOrig.MA_NG_EMP, MAESTROCOSTOrig.MA_COSTO, 
		                      MAESTROCOSTOrig.MA_GRAVA_VA, MAESTROCOSTOrig.MA_NG_USA, MAESTROCOSTOrig.TV_CODIGO, MAESTROCOSTOrig.DV_CODIGO, 
		                      MAESTROCOSTOrig.SPI_CODIGO, MAESTROCOSTOrig.MA_PERINI, MAESTROCOSTOrig.MA_PERFIN, MAESTROCOSTOrig.MA_NG_MX
		FROM         '+@BDOrigen+'.DBO.MAESTROCOST MAESTROCOSTOrig INNER JOIN
		                      '+@BDOrigen+'.DBO.MAESTRO MAESTROOrig ON MAESTROCOSTOrig.MA_CODIGO = MAESTROOrig.MA_CODIGO INNER JOIN
		                      MAESTRO MAESTRO_1 ON MAESTROOrig.MA_NOPARTE = MAESTRO_1.MA_NOPARTE AND MAESTROOrig.MA_INV_GEN = MAESTRO_1.MA_INV_GEN
		WHERE     (GETDATE() BETWEEN MAESTROCOSTOrig.MA_PERINI AND MAESTROCOSTOrig.MA_PERFIN)
		AND CONVERT(VARCHAR(50),MAESTRO_1.MA_CODIGO)+CONVERT(VARCHAR(10),MAESTROCOSTOrig.TCO_CODIGO) NOT IN
		(SELECT CONVERT(VARCHAR(50),M1.MA_CODIGO)+CONVERT(VARCHAR(10),M1.TCO_CODIGO) FROM MAESTROCOST M1 WHERE 
		(GETDATE() BETWEEN M1.MA_PERINI AND M1.MA_PERFIN))')
	


GO
