SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_PEDIMPANEXO](@PI_CODIGO INT)   as

SET NOCOUNT ON 
DELETE FROM PEDIMPANEXO WHERE PI_CODIGO=@PI_CODIGO

INSERT INTO PEDIMPANEXO(PIA_CODIGO_FACT, PIA_FACT_CONST, TQ_FACT_CONST, TF_FACT_CONST, PIA_TI_FACT_CONST, CL_DESTFIN,
PR_CODIGO, PIA_ESTATUS, PIA_FECHA, PIA_TOTALB,PIA_TIPO_CAMBIO, PI_CODIGO)
SELECT  FI_CODIGO, FI_FOLIO, TQ_CODIGO, TF_CODIGO,'F', CL_DESTFIN,  PR_CODIGO, FI_ESTATUS, FI_FECHA,  FI_TOTALB, FI_TIPOCAMBIO, PI_CODIGO
FROM VIMP_X_FACT WHERE PI_CODIGO=@PI_CODIGO AND FI_CODIGO IS NOT NULL

INSERT INTO PEDIMPANEXO(PIA_TI_FACT_CONST, PI_CODIGO)
SELECT 'P', PI_CODIGO
FROM VIMP_X_PED WHERE PI_CODIGO=@PI_CODIGO AND PI_CODIGO IS NOT NULL


GO
