SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE ActualizarClavePed as
declare @CP_CODIGO int, @CP_CLAVE varchar(8000), @CP_NOMBRE varchar(8000), @CP_DESC varchar(8000), 
@CP_TIPO varchar(8000), @CP_APLICACION varchar(8000), @CP_BASELEGAL varchar(8000), 
@CP_DESCARGABLE varchar(8000), @CP_CONSOLIDADO varchar(8000), @CP_ART303 varchar(8000), @CP_TPAGOIGI varchar(8000), @CP_TPAGOCC varchar(8000), 
@CP_TPAGODTA varchar(8000), @CP_TPAGODTI varchar(8000), @CP_TPAGOIEPS varchar(8000), @CP_TPAGOISAN varchar(8000), 
@CP_TPAGOIVA varchar(8000), @CP_TPAGOREC varchar(8000), @CP_TPAGOBBS varchar(8000), @CP_TPAGOIGE varchar(8000), @CP_TPAGOCCE varchar(8000), 
@CP_TPAGODTAE varchar(8000), @CP_TPAGODTIE varchar(8000), @CP_TPAGOIEPSE varchar(8000), @CP_TPAGOISANE varchar(8000), 
@CP_TPAGOIVAE varchar(8000), @CP_TPAGORECE varchar(8000), @CP_TPAGOBBSE varchar(8000), @CP_PAGODTA varchar(8000), @CP_DESCARGO varchar(8000), @CP_USANAFTADTA varchar(8000), @LDE_CODIGO int

declare cur_claveped cursor for
select CP_CODIGO, CP_CLAVE, CP_NOMBRE, CP_DESC, CP_TIPO, CP_APLICACION, CP_BASELEGAL, 
CP_DESCARGABLE, CP_CONSOLIDADO, CP_ART303, CP_TPAGOIGI, CP_TPAGOCC, CP_TPAGODTA, CP_TPAGODTI, CP_TPAGOIEPS, CP_TPAGOISAN, 
CP_TPAGOIVA, CP_TPAGOREC, CP_TPAGOBBS, CP_TPAGOIGE, CP_TPAGOCCE, CP_TPAGODTAE, CP_TPAGODTIE, CP_TPAGOIEPSE, CP_TPAGOISANE, 
CP_TPAGOIVAE, CP_TPAGORECE, CP_TPAGOBBSE, CP_PAGODTA, CP_DESCARGO, CP_USANAFTADTA, LDE_CODIGO
from original.dbo.claveped

open cur_claveped
fetch next from cur_claveped into @CP_CODIGO, @CP_CLAVE, @CP_NOMBRE, @CP_DESC, @CP_TIPO, @CP_APLICACION, @CP_BASELEGAL, 
@CP_DESCARGABLE, @CP_CONSOLIDADO, @CP_ART303, @CP_TPAGOIGI, @CP_TPAGOCC, @CP_TPAGODTA, @CP_TPAGODTI, @CP_TPAGOIEPS, @CP_TPAGOISAN, 
@CP_TPAGOIVA, @CP_TPAGOREC, @CP_TPAGOBBS, @CP_TPAGOIGE, @CP_TPAGOCCE, @CP_TPAGODTAE, @CP_TPAGODTIE, @CP_TPAGOIEPSE, @CP_TPAGOISANE, 
@CP_TPAGOIVAE, @CP_TPAGORECE, @CP_TPAGOBBSE, @CP_PAGODTA, @CP_DESCARGO, @CP_USANAFTADTA, @LDE_CODIGO
WHILE (@@FETCH_STATUS <> -1)
 BEGIN
	if exists(select cp_codigo from claveped where cp_clave = @cp_clave)
     	   begin
		update claveped set CP_NOMBRE=@CP_NOMBRE, CP_DESC=@CP_DESC, CP_TIPO=@CP_TIPO, CP_APLICACION=@CP_APLICACION, CP_BASELEGAL=@CP_BASELEGAL, 
				CP_DESCARGABLE=@CP_DESCARGABLE, CP_CONSOLIDADO=@CP_CONSOLIDADO, CP_ART303=@CP_ART303, CP_TPAGOIGI=@CP_TPAGOIGI, CP_TPAGOCC=@CP_TPAGOCC, 
				CP_TPAGODTA=@CP_TPAGODTA, CP_TPAGODTI=@CP_TPAGODTI, CP_TPAGOIEPS=@CP_TPAGOIEPS, CP_TPAGOISAN=@CP_TPAGOISAN, 
				CP_TPAGOIVA=@CP_TPAGOIVA, CP_TPAGOREC=@CP_TPAGOREC, CP_TPAGOBBS=@CP_TPAGOBBS, CP_TPAGOIGE=@CP_TPAGOIGE, CP_TPAGOCCE=@CP_TPAGOCCE, 
				CP_TPAGODTAE=@CP_TPAGODTAE, CP_TPAGODTIE=@CP_TPAGODTIE, CP_TPAGOIEPSE=@CP_TPAGOIEPSE, CP_TPAGOISANE=@CP_TPAGOISANE, 
				CP_TPAGOIVAE=@CP_TPAGOIVAE, CP_TPAGORECE=@CP_TPAGORECE, CP_TPAGOBBSE=@CP_TPAGOBBSE, CP_PAGODTA=@CP_PAGODTA, CP_DESCARGO=@CP_DESCARGO, 
				CP_USANAFTADTA=@CP_USANAFTADTA, LDE_CODIGO=@LDE_CODIGO
		where cp_clave=@cp_clave
	   end	 
	else
	  begin
		insert into clavePed(CP_CLAVE, CP_NOMBRE, CP_DESC, CP_TIPO, CP_APLICACION, CP_BASELEGAL, 
					CP_DESCARGABLE, CP_CONSOLIDADO, CP_ART303, CP_TPAGOIGI, CP_TPAGOCC, CP_TPAGODTA, CP_TPAGODTI, CP_TPAGOIEPS, CP_TPAGOISAN, 
					CP_TPAGOIVA, CP_TPAGOREC, CP_TPAGOBBS, CP_TPAGOIGE, CP_TPAGOCCE, CP_TPAGODTAE, CP_TPAGODTIE, CP_TPAGOIEPSE, CP_TPAGOISANE, 
					CP_TPAGOIVAE, CP_TPAGORECE, CP_TPAGOBBSE, CP_PAGODTA, CP_DESCARGO, CP_USANAFTADTA, LDE_CODIGO)
		values(@CP_CLAVE, @CP_NOMBRE, @CP_DESC, @CP_TIPO, @CP_APLICACION, @CP_BASELEGAL, 
					@CP_DESCARGABLE, @CP_CONSOLIDADO, @CP_ART303, @CP_TPAGOIGI, @CP_TPAGOCC, @CP_TPAGODTA, @CP_TPAGODTI, @CP_TPAGOIEPS, @CP_TPAGOISAN, 
					@CP_TPAGOIVA, @CP_TPAGOREC, @CP_TPAGOBBS, @CP_TPAGOIGE, @CP_TPAGOCCE, @CP_TPAGODTAE, @CP_TPAGODTIE, @CP_TPAGOIEPSE, @CP_TPAGOISANE, 
					@CP_TPAGOIVAE, @CP_TPAGORECE, @CP_TPAGOBBSE, @CP_PAGODTA, @CP_DESCARGO, @CP_USANAFTADTA, @LDE_CODIGO)
	  end
	fetch next from cur_claveped into @CP_CODIGO, @CP_CLAVE, @CP_NOMBRE, @CP_DESC, @CP_TIPO, @CP_APLICACION, @CP_BASELEGAL, 
	@CP_DESCARGABLE, @CP_CONSOLIDADO, @CP_ART303, @CP_TPAGOIGI, @CP_TPAGOCC, @CP_TPAGODTA, @CP_TPAGODTI, @CP_TPAGOIEPS, @CP_TPAGOISAN, 
	@CP_TPAGOIVA, @CP_TPAGOREC, @CP_TPAGOBBS, @CP_TPAGOIGE, @CP_TPAGOCCE, @CP_TPAGODTAE, @CP_TPAGODTIE, @CP_TPAGOIEPSE, @CP_TPAGOISANE, 
	@CP_TPAGOIVAE, @CP_TPAGORECE, @CP_TPAGOBBSE, @CP_PAGODTA, @CP_DESCARGO, @CP_USANAFTADTA, @LDE_CODIGO
 END
close cur_claveped
deallocate cur_claveped


GO
