SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_TEMPIMPORT141_7] AS
DECLARE @MAESTRO#MA_PESO_KG float,@MAESTRO#MA_TIP_ENS char,@MAESTRO#PA_PROCEDE int,@MAESTRO#MA_NOPARTEAUX varchar(8000),@MAESTRO#MA_INV_GEN char,@MAESTRO#MA_NOPARTE varchar(8000),@MAESTRO#TI_CODIGO smallint,@MAESTRO#MA_NOMBRE varchar(8000),@MAESTRO#MA_NAME varchar(8000),@MAESTRO#ME_COM int,@MAESTRO#PA_ORIGEN int,@MAESTRO#MA_GENERICO int,@MAESTRO#MA_PESO_LB float,@MAESTRO#AR_IMPFO int,@MAESTRO#AR_EXPFO int,@MAESTRO#AR_IMPMX int,@MAESTRO#AR_EXPMX int,@Cod_5 varchar(8000),@Cod_6 varchar(8000),@Cod_7 varchar(8000),@Cod_10 varchar(8000),@Cod_11 varchar(8000)
DECLARE @ACTUALIZA bit,@ANEXA bit,@CONSECUTIVO int,@CONSDET int,@CONSANEX int,@CONSCONT int
DECLARE @CAMPOSMASTER varchar(255),@temp_str varchar(20)
SELECT @ACTUALIZA=1
SELECT @ANEXA=1
DELETE FROM REGISTROSIMPORTADOS where RI_USERID = 7
-- Variables para campos de caratula
-- Variables para campos de detalle
DECLARE CUR_TEMPIMPORT141_7 CURSOR FOR
SELECT MAX(Cod_5),MAX(Cod_6),MAX(Cod_7),MAX(Cod_10),MAX(Cod_11),MAX(MAESTRO7#MA_PESO_KG),MAX(MAESTRO7#MA_TIP_ENS),MAX(MAESTRO7#PA_PROCEDE),MAESTRO7#MA_NOPARTEAUX,MAESTRO7#MA_INV_GEN,MAESTRO7#MA_NOPARTE,MAX(MAESTRO7#TI_CODIGO),MAX(MAESTRO7#MA_NOMBRE),MAX(MAESTRO7#MA_NAME),MAX(MAESTRO7#ME_COM),MAX(MAESTRO7#PA_ORIGEN),MAX(MAESTRO7#MA_GENERICO),MAX(MAESTRO7#MA_PESO_LB),MAESTRO7#AR_IMPFO,MAESTRO7#AR_EXPFO,MAESTRO7#AR_IMPMX,MAESTRO7#AR_EXPMX FROM TEMPIMPORT141_7 GROUP BY MAESTRO7#MA_NOPARTEAUX,MAESTRO7#MA_INV_GEN,MAESTRO7#MA_NOPARTE,MAESTRO7#AR_IMPFO,MAESTRO7#AR_EXPFO,MAESTRO7#AR_IMPMX,MAESTRO7#AR_EXPMX
OPEN CUR_TEMPIMPORT141_7
FETCH NEXT FROM CUR_TEMPIMPORT141_7 INTO @Cod_5 ,@Cod_6 ,@Cod_7 ,@Cod_10 ,@Cod_11 ,@MAESTRO#MA_PESO_KG ,@MAESTRO#MA_TIP_ENS ,@MAESTRO#PA_PROCEDE ,@MAESTRO#MA_NOPARTEAUX ,@MAESTRO#MA_INV_GEN ,@MAESTRO#MA_NOPARTE ,@MAESTRO#TI_CODIGO ,@MAESTRO#MA_NOMBRE ,@MAESTRO#MA_NAME ,@MAESTRO#ME_COM ,@MAESTRO#PA_ORIGEN ,@MAESTRO#MA_GENERICO ,@MAESTRO#MA_PESO_LB ,@MAESTRO#AR_IMPFO ,@MAESTRO#AR_EXPFO ,@MAESTRO#AR_IMPMX ,@MAESTRO#AR_EXPMX 
WHILE (@@FETCH_STATUS = 0)
BEGIN
   IF EXISTS(SELECT MA_CODIGO FROM MAESTRO WHERE MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX)
  BEGIN
          IF @ACTUALIZA=1
          BEGIN
              begin tran UPDATE MAESTRO SET MA_ULTIMAMODIF=GETDATE() WHERE MA_CODIGO=@CONSECUTIVO  commit tran 
                  SELECT @CONSECUTIVO=(SELECT MA_CODIGO FROM MAESTRO  WHERE MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX)
              begin tran UPDATE MAESTRO SET MA_PESO_KG=@MAESTRO#MA_PESO_KG, MA_TIP_ENS=@MAESTRO#MA_TIP_ENS, PA_PROCEDE=@MAESTRO#PA_PROCEDE, MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX, MA_INV_GEN=@MAESTRO#MA_INV_GEN, MA_NOPARTE=@MAESTRO#MA_NOPARTE, TI_CODIGO=@MAESTRO#TI_CODIGO, MA_NOMBRE=@MAESTRO#MA_NOMBRE, MA_NAME=@MAESTRO#MA_NAME, ME_COM=@MAESTRO#ME_COM, PA_ORIGEN=@MAESTRO#PA_ORIGEN, MA_GENERICO=@MAESTRO#MA_GENERICO, MA_PESO_LB=@MAESTRO#MA_PESO_LB, AR_IMPFO=@MAESTRO#AR_IMPFO, AR_EXPFO=@MAESTRO#AR_EXPFO, AR_IMPMX=@MAESTRO#AR_IMPMX, AR_EXPMX=@MAESTRO#AR_EXPMX WHERE MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX commit tran 
              update MAESTRO set MA_PESO_KG = ( MAESTRO.MA_PESO_LB * 0.4535922921968 )
              where MAESTRO.MA_CODIGO = @CONSECUTIVO
               INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO,RI_TIPO,RI_CBFORMA,RI_USERID) VALUES                                               ('MA_NOPARTE = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTE)+', '+'MA_INV_GEN = '+CONVERT(varchar(100),@MAESTRO#MA_INV_GEN)+', '+'MA_NOPARTEAUX = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTEAUX),'A',28,7) 
 if exists (select * from sysobjects where name='sysusrlog41')     insert into sysusrlog41 (user_id, mov_id, referencia, frmtag, fechahora) values                                                        (7, 2 ,'MA_NOPARTE = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTE)+', '+'MA_INV_GEN = '+CONVERT(varchar(100),@MAESTRO#MA_INV_GEN)+', '+'MA_NOPARTEAUX = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTEAUX),41, getdate()) 
          END
  END
  ELSE
  IF @ANEXA=1
  BEGIN
          EXEC SP_GETCONSECUTIVO @TIPO='MA',@VALUE=@CONSECUTIVO OUTPUT
          INSERT INTO MAESTRO (MA_CODIGO,MA_PESO_KG ,MA_TIP_ENS ,PA_PROCEDE ,MA_NOPARTEAUX ,MA_INV_GEN ,MA_NOPARTE ,TI_CODIGO ,MA_NOMBRE ,MA_NAME ,ME_COM ,PA_ORIGEN ,MA_GENERICO ,MA_PESO_LB ,AR_IMPFO ,AR_EXPFO ,AR_IMPMX ,AR_EXPMX ) VALUES (@CONSECUTIVO,@MAESTRO#MA_PESO_KG ,@MAESTRO#MA_TIP_ENS ,@MAESTRO#PA_PROCEDE ,@MAESTRO#MA_NOPARTEAUX ,@MAESTRO#MA_INV_GEN ,@MAESTRO#MA_NOPARTE ,@MAESTRO#TI_CODIGO ,@MAESTRO#MA_NOMBRE ,@MAESTRO#MA_NAME ,@MAESTRO#ME_COM ,@MAESTRO#PA_ORIGEN ,@MAESTRO#MA_GENERICO ,@MAESTRO#MA_PESO_LB ,@MAESTRO#AR_IMPFO ,@MAESTRO#AR_EXPFO ,@MAESTRO#AR_IMPMX ,@MAESTRO#AR_EXPMX )
               INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO,RI_TIPO,RI_CBFORMA, RI_USERID) VALUES                                               ('MA_NOPARTE = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTE)+', '+'MA_NOPARTEAUX = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTEAUX)+', '+'MA_INV_GEN = '+CONVERT(varchar(100),@MAESTRO#MA_INV_GEN),'I',28,7) 
 if exists (select * from sysobjects where name='sysusrlog41')                 insert into sysusrlog41 (user_id, mov_id, referencia, frmtag, fechahora) values                                                        (7, 1 ,'MA_NOPARTE = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTE)+', '+'MA_NOPARTEAUX = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTEAUX)+', '+'MA_INV_GEN = '+CONVERT(varchar(100),@MAESTRO#MA_INV_GEN),41, getdate()) 
       UPDATE MAESTRO SET MA_ULTIMAMODIF=GETDATE() WHERE MA_CODIGO=@CONSECUTIVO 
              update MAESTRO set MA_PESO_KG = ( MAESTRO.MA_PESO_LB * 0.4535922921968 )
              where MAESTRO.MA_CODIGO = @CONSECUTIVO
  END
  FETCH NEXT FROM CUR_TEMPIMPORT141_7 INTO @Cod_5 ,@Cod_6 ,@Cod_7 ,@Cod_10 ,@Cod_11 ,@MAESTRO#MA_PESO_KG ,@MAESTRO#MA_TIP_ENS ,@MAESTRO#PA_PROCEDE ,@MAESTRO#MA_NOPARTEAUX ,@MAESTRO#MA_INV_GEN ,@MAESTRO#MA_NOPARTE ,@MAESTRO#TI_CODIGO ,@MAESTRO#MA_NOMBRE ,@MAESTRO#MA_NAME ,@MAESTRO#ME_COM ,@MAESTRO#PA_ORIGEN ,@MAESTRO#MA_GENERICO ,@MAESTRO#MA_PESO_LB ,@MAESTRO#AR_IMPFO ,@MAESTRO#AR_EXPFO ,@MAESTRO#AR_IMPMX ,@MAESTRO#AR_EXPMX 
END
CLOSE CUR_TEMPIMPORT141_7
DEALLOCATE CUR_TEMPIMPORT141_7
GO
