SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




























CREATE PROCEDURE [dbo].[SP_ACTUALIZAEQUIVALE]  @GENERICO INT   as

SET NOCOUNT ON 
DECLARE @ME_CODIGO INT

	SELECT @ME_CODIGO=ME_COM FROM MAESTRO WHERE MA_CODIGO =@GENERICO

		if exists (SELECT dbo.MAESTRO.EQ_GEN FROM dbo.MAESTRO INNER JOIN
			                      dbo.MAESTRO MAESTRO_1 ON dbo.MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO INNER JOIN
			                      dbo.EQUIVALE ON dbo.MAESTRO.ME_COM = dbo.EQUIVALE.ME_CODIGO1 AND MAESTRO_1.ME_COM = dbo.EQUIVALE.ME_CODIGO2
			WHERE     (MAESTRO_1.MA_CODIGO = @GENERICO))

			update dbo.MAESTRO
			SET     dbo.MAESTRO.EQ_GEN= dbo.EQUIVALE.EQ_CANT
			FROM         dbo.MAESTRO INNER JOIN
			                      dbo.MAESTRO MAESTRO_1 ON dbo.MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO INNER JOIN
			                      dbo.EQUIVALE ON dbo.MAESTRO.ME_COM = dbo.EQUIVALE.ME_CODIGO1 AND MAESTRO_1.ME_COM = dbo.EQUIVALE.ME_CODIGO2
			WHERE     (MAESTRO_1.MA_CODIGO = @GENERICO)

		else
			UPDATE MAESTRO
			SET EQ_GEN = 1
			WHERE MA_GENERICO = @GENERICO




		if @ME_CODIGO in (select ME_KILOGRAMOS from configuracion) 
		begin
			UPDATE MAESTRO
			SET EQ_GEN = MA_PESO_KG
			WHERE MA_GENERICO = @GENERICO and MA_PESO_KG>0

			UPDATE MAESTRO
			SET EQ_GEN = 1
			WHERE MA_GENERICO = @GENERICO and MA_PESO_KG=0
		end



























GO
