SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO








/* inserta en la tabla [TempBOM_NIVELUso'+@USER+']  para calculo de costos de todos los productos*/
CREATE PROCEDURE [dbo].[SP_FILL_TempBOMNivelUso] (@BST_ENTRAVIGOR DATETIME, @USER varchar(50)='1')   as

--SET NOCOUNT ON 
declare @BSTENTRAVIGOR varchar(11)

	select @BSTENTRAVIGOR=convert(varchar(11),@BST_ENTRAVIGOR,101)


	exec('DECLARE @existe INT, @nivel INT

	set @nivel=1

	exec sp_droptable ''TempBOM_NIVELUso'+@USER+'''


	CREATE TABLE [dbo].[TempBOM_NIVELUso'+@USER+'] (
		[BST_PT] [int]  NOT NULL ,
		[BST_PERTENECE] [int] NOT NULL ,
		[BST_HIJO] [int] NULL ,
		[BST_NIVEL] [int] NULL ,
		[BST_PERINI] [datetime] NULL,
		[BST_INCORPOR] decimal(38,6) NULL,
		[BST_INCORPORUSO] decimal(38,6) NULL
	) ON [PRIMARY]


	--delete from bom_struct where bsu_subensamble = bst_hijo



	insert into [TempBOM_NIVELUso'+@USER+'](BST_PT,  BST_NIVEL, BST_PERTENECE, BST_HIJO, BST_PERINI, BST_INCORPOR, BST_INCORPORUSO)
	SELECT     dbo.BOM_STRUCT.BSU_SUBENSAMBLE, @nivel, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, dbo.BOM_STRUCT.BSU_SUBENSAMBLE,'''+@BSTENTRAVIGOR+''', 1, 1
	FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
	                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
	                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
	WHERE (dbo.CONFIGURATIPO.CFT_TIPO=''P'' OR dbo.CONFIGURATIPO.CFT_TIPO=''S'') 
		AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= '''+ @BSTENTRAVIGOR +''' and dbo.BOM_STRUCT.BST_PERFIN>= '''+@BST_ENTRAVIGOR+''')
		AND dbo.BOM_STRUCT.BST_INCORPOR >0
	GROUP BY dbo.BOM_STRUCT.BSU_SUBENSAMBLE
	ORDER BY dbo.BOM_STRUCT.BSU_SUBENSAMBLE

	SET @nivel=@nivel+1

	insert into [TempBOM_NIVELUso'+@USER+'](BST_PT,  BST_NIVEL, BST_PERTENECE, BST_HIJO, BST_PERINI, BST_INCORPOR, BST_INCORPORUSO)
	SELECT [TempBOM_NIVELUso'+@USER+'].BST_PT, @nivel, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, BOM_STRUCT.BST_HIJO, '''+@BSTENTRAVIGOR+''', SUM(dbo.BOM_STRUCT.BST_INCORPOR)*SUM([TempBOM_NIVELUso'+@USER+'].BST_INCORPOR), SUM([TempBOM_NIVELUso'+@USER+'].BST_INCORPOR) 
	FROM         BOM_STRUCT LEFT OUTER JOIN
	                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
	                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
	      INNER JOIN [TempBOM_NIVELUso'+@USER+'] ON [TempBOM_NIVELUso'+@USER+'].BST_PERTENECE=BOM_STRUCT.BSU_SUBENSAMBLE
	WHERE (CONFIGURATIPO.CFT_TIPO=''P'' OR CONFIGURATIPO.CFT_TIPO=''S'') AND BOM_STRUCT.BST_TIP_ENS<>''P'' AND BOM_STRUCT.BST_TIP_ENS<>''C''
		AND BOM_STRUCT.BST_HIJO IS NOT NULL AND (BOM_STRUCT.BST_PERINI <=  '''+@BSTENTRAVIGOR+''' and BOM_STRUCT.BST_PERFIN>=  '''+@BSTENTRAVIGOR+''')
		AND BOM_STRUCT.BST_INCORPOR >0
		AND [TempBOM_NIVELUso'+@USER+'].BST_NIVEL=@nivel-1
	GROUP BY BOM_STRUCT.BST_HIJO, [TempBOM_NIVELUso'+@USER+'].BST_PT, dbo.BOM_STRUCT.BSU_SUBENSAMBLE
	ORDER BY BOM_STRUCT.BST_HIJO


	SET @nivel=@nivel+1


	exec sp_droptable ''TempBOM_STRUCTUso'+@USER+'''


	SELECT     BSU_SUBENSAMBLE, BST_HIJO, '''+@BSTENTRAVIGOR+''' as BST_PERINI, SUM(BST_INCORPOR) AS BST_INCORPOR
	INTO dbo.[TempBOM_STRUCTUso'+@USER+']
	FROM         BOM_STRUCT LEFT OUTER JOIN
	                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
	                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
	WHERE    CFT_TIPO IN (''P'', ''S'') AND BOM_STRUCT.BST_INCORPOR >0
		AND BOM_STRUCT.BST_TIP_ENS<>''P'' AND BOM_STRUCT.BST_TIP_ENS<>''C'' and BOM_STRUCT.BST_HIJO IS NOT NULL 
		AND (BOM_STRUCT.BST_PERINI <=  '''+@BSTENTRAVIGOR+''' and BOM_STRUCT.BST_PERFIN>= '''+@BSTENTRAVIGOR+''')
	GROUP BY BSU_SUBENSAMBLE, BST_HIJO


inicio:

	--print @nivel
		insert into [TempBOM_NIVELUso'+@USER+'](BST_PT,  BST_NIVEL, BST_PERTENECE, BST_HIJO, BST_PERINI, BST_INCORPOR, BST_INCORPORUSO)
		SELECT [TempBOM_NIVELUso'+@USER+'].BST_PT, @nivel, [TempBOM_STRUCTUso'+@USER+'].BSU_SUBENSAMBLE, [TempBOM_STRUCTUso'+@USER+'].BST_HIJO, '''+@BSTENTRAVIGOR+''', SUM([TempBOM_STRUCTUso'+@USER+'].BST_INCORPOR), SUM([TempBOM_STRUCTUso'+@USER+'].BST_INCORPOR)
		FROM  [TempBOM_STRUCTUso'+@USER+'] INNER JOIN [TempBOM_NIVELUso'+@USER+'] 
		      ON [TempBOM_NIVELUso'+@USER+'].BST_HIJO=[TempBOM_STRUCTUso'+@USER+'].BSU_SUBENSAMBLE
		WHERE [TempBOM_NIVELUso'+@USER+'].BST_NIVEL=@nivel-1
		GROUP BY [TempBOM_STRUCTUso'+@USER+'].BST_HIJO, [TempBOM_NIVELUso'+@USER+'].BST_PT, [TempBOM_STRUCTUso'+@USER+'].BSU_SUBENSAMBLE
		ORDER BY [TempBOM_STRUCTUso'+@USER+'].BST_HIJO


		SET @nivel=@nivel+1

		if (SELECT COUNT([TempBOM_STRUCTUso'+@USER+'].BST_HIJO)
		FROM  [TempBOM_STRUCTUso'+@USER+'] 
		      INNER JOIN [TempBOM_NIVELUso'+@USER+'] ON [TempBOM_NIVELUso'+@USER+'].BST_HIJO=[TempBOM_STRUCTUso'+@USER+'].BSU_SUBENSAMBLE
		WHERE [TempBOM_NIVELUso'+@USER+'].BST_NIVEL=@nivel-1)>0

		set @existe=1
		else
		set @existe=0


	while (@existe>0)
	begin

		goto inicio


	end')

	exec('exec sp_droptable ''TempBOM_STRUCTUso'+@USER+'''')





GO
