SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



































CREATE PROCEDURE [dbo].[SP_ACTUALIZAFACTEXPAGRU] (@FEA_CODIGO INT)   as


		UPDATE FACTEXPAGRU
	SET FEA_NO_SEM = (SELECT MAX(FE_NO_SEM) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_DESTINO = (SELECT MAX(FE_DESTINO) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	AG_MX = (SELECT MAX(AG_MX) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	AG_US = (SELECT MAX(AG_US) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CL_PROD = (SELECT MAX(CL_PROD) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	DI_PROD = (SELECT MAX(DI_PROD) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CL_COMP = (SELECT MAX(CL_COMP) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	DI_COMP = (SELECT MAX(DI_COMP) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CO_COMP = (SELECT MAX(CO_COMP) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CL_COMPFIN = (SELECT MAX(CL_COMPFIN) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	DI_COMPFIN = (SELECT MAX(DI_COMPFIN) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CO_COMPFIN = (SELECT MAX(CO_COMPFIN) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CL_EXP = (SELECT MAX(CL_EXP) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	DI_EXP = (SELECT MAX(DI_EXP) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CL_EXPFIN = (SELECT MAX(CL_EXPFIN) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	DI_EXPFIN = (SELECT MAX(DI_EXPFIN) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CL_DESTINI = (SELECT MAX(CL_DESTINI) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	DI_DESTINI = (SELECT MAX(DI_DESTINI) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CO_DESTINI = (SELECT MAX(CO_DESTINI) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CL_DESTFIN = (SELECT MAX(CL_DESTFIN) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	DI_DESTFIN = (SELECT MAX(DI_DESTFIN) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CO_DESTFIN = (SELECT MAX(CO_DESTFIN) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CL_VEND = (SELECT MAX(CL_VEND) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	DI_VEND = (SELECT MAX(DI_VEND) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CL_IMP = (SELECT MAX(CL_IMP) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	DI_IMP = (SELECT MAX(DI_IMP) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	PU_CARGA = (SELECT MAX(PU_CARGA) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	PU_SALIDA = (SELECT MAX(PU_SALIDA) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	PU_ENTRADA = (SELECT MAX(PU_ENTRADA) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	PU_DESTINO = (SELECT MAX(PU_DESTINO) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_FEC_ENV = (SELECT MAX(FE_FEC_ENV) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_FEC_ARR = (SELECT MAX(FE_FEC_ARR) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_NUM_ENV = (SELECT MAX(FE_NUM_ENV) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_ENV_INST = (SELECT MAX(FE_ENV_INST) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_ORD_COMP = (SELECT MAX(FE_ORD_COMP) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_NUM_CTL = (SELECT MAX(FE_NUM_CTL) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_NUM_INBON = (SELECT MAX(FE_NUM_INBON) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_TIPO_INBON = (SELECT MAX(FE_TIPO_INBON) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_FEC_INBON = (SELECT MAX(FE_FEC_INBON) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_FIRMS = (SELECT MAX(FE_FIRMS) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_COMENTA = (SELECT MAX(FE_COMENTA) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_COMENTAUS = (SELECT MAX(FE_COMENTAUS) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CT_COMPANY1 = (SELECT MAX(CT_COMPANY1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CA_COMPANY1 = (SELECT MAX(CA_COMPANY1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CJ_COMPANY1 = (SELECT MAX(CJ_COMPANY1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CT_COMPANY2 = (SELECT MAX(CT_COMPANY2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CA_COMPANY2 = (SELECT MAX(CA_COMPANY2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	CJ_COMPANY2 = (SELECT MAX(CJ_COMPANY2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_TRAC_US1 = (SELECT MAX(FE_TRAC_US1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_TRAC_MX1 = (SELECT MAX(FE_TRAC_MX1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_CONT1_REG = (SELECT MAX(FE_CONT1_REG) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_CONT1_US = (SELECT MAX(FE_CONT1_US) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_CONT1_SELL = (SELECT MAX(FE_CONT1_SELL) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	PG_COMPANY1 = (SELECT MAX(PG_COMPANY1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_TRAC_CHO1 = (SELECT MAX(FE_TRAC_CHO1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_LIM1 = (SELECT MAX(FE_LIM1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	RU_COMPANY1 = (SELECT MAX(RU_COMPANY1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	--FEA_TRANSFER1 = (SELECT MAX(FE_TRANSFER1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	MT_COMPANY1 = (SELECT MAX(MT_COMPANY1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_GUIA1 = (SELECT MAX(FE_GUIA1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_TRAC_US2 = (SELECT MAX(FE_TRAC_US2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_TRAC_MX2 = (SELECT MAX(FE_TRAC_MX2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_CONT2_REG = (SELECT MAX(FE_CONT2_REG) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_CONT2_US = (SELECT MAX(FE_CONT2_US) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_CONT2_SELL = (SELECT MAX(FE_CONT2_SELL) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	PG_COMPANY2 = (SELECT MAX(PG_COMPANY2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_TRAC_CHO2 = (SELECT MAX(FE_TRAC_CHO2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_LIM2 = (SELECT MAX(FE_LIM2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	RU_COMPANY2 = (SELECT MAX(RU_COMPANY2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	MT_COMPANY2 = (SELECT MAX(MT_COMPANY2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_GUIA2 = (SELECT MAX(FE_GUIA2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_TOTALB = (SELECT MAX(FE_TOTALB) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_MANIF = (SELECT MAX(FE_MANIF) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_MANIF_DATE = (SELECT MAX(FE_MANIF_DATE) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_AWB = (SELECT MAX(FE_AWB) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_INCOTLUGAR1 = (SELECT MAX(FE_INCOTLUGAR1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_INCOTLUGAR2 = (SELECT MAX(FE_INCOTLUGAR2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_LAGNO = (SELECT MAX(FE_LAGNO) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_ESTATUS = (SELECT MAX(FE_ESTATUS) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	MO_CODIGO = (SELECT MAX(MO_CODIGO) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	SPI_CODIGO = (SELECT MAX(SPI_CODIGO) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_DESCRIPTION1 = (SELECT MAX(FE_DESCRIPTION1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_DESCRIPTION2 = (SELECT MAX(FE_DESCRIPTION2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_INVOICETYPE = (SELECT MAX(FE_INVOICETYPE) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_HEADER = (SELECT MAX(FE_HEADER) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	FEA_FOOTER = (SELECT MAX(FE_FOOTER) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	IT_COMPANY1 = (SELECT MAX(IT_COMPANY1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	IT_COMPANY2 = (SELECT MAX(IT_COMPANY2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	TCA_CONT1 = (SELECT MAX(TCA_CONT1) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO),
	TCA_CONT2 = (SELECT MAX(TCA_CONT2) FROM FACTEXP WHERE FE_FACTAGRU = FACTEXPAGRU.FEA_CODIGO)
	FROM  FACTEXPAGRU
	WHERE FEA_CODIGO=@FEA_CODIGO




































GO
