SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



































CREATE PROCEDURE [dbo].[SP_temp_13026]   as

		--Yolanda Avila
	--2010-09-20
	/*
	INSERT INTO ARANCELREGLAORIGEN(AR_CODIGO, ARR_CODIGO)
	SELECT     AR_CODIGO, ARR_CODIGO
	FROM         ARANCEL
	WHERE     (ARR_CODIGO IS NOT NULL)
	*/
	INSERT INTO ARANCELREGLAORIGEN(AR_CODIGO, ARR_CODIGO, arr_perini, arr_perfin)
	SELECT     AR_CODIGO, ARR_CODIGO, '1999-01-01', '9999-01-01'
	FROM         ARANCEL
	WHERE     (ARR_CODIGO IS NOT NULL)

	UPDATE NAFTA
	SET     NAFTA.PA_CLASE=PAIS.PA_CODIGO
	FROM         COMBOBOXES INNER JOIN
	                      PAIS ON COMBOBOXES.CB_LOOKUP = PAIS.PA_ISO INNER JOIN
	                      NAFTA ON COMBOBOXES.CB_KEYFIELD = NAFTA.NFT_CLASE
	WHERE     (COMBOBOXES.CB_FIELD = 'NFT_CLASE')


	UPDATE CERTORIGMPDET
	SET     CERTORIGMPDET.PA_CLASE=PAIS.PA_CODIGO
	FROM         COMBOBOXES INNER JOIN
	                      PAIS ON COMBOBOXES.CB_LOOKUP = PAIS.PA_ISO INNER JOIN
	                      CERTORIGMPDET ON COMBOBOXES.CB_KEYFIELD = CERTORIGMPDET.CMP_CLASE
	WHERE     (COMBOBOXES.CB_FIELD = 'CMP_CLASE')


	UPDATE CLASIFICATLC
	SET     CLASIFICATLC.NFT_CODIGO= NAFTA.NFT_CODIGO
	FROM         NAFTA INNER JOIN
	                      CLASIFICATLC ON NAFTA.MA_CODIGO = CLASIFICATLC.BST_PT


	UPDATE PERMISODET
	SET     PED_COSTOT= PED_CANT* isnull(PED_COSTO,0),
	PED_SALDOCOSTOT= (PED_CANT* isnull(PED_COSTO,0))-isnull((SELECT SUM(FACTIMPDET.FID_COS_TOT) 
			FROM FACTIMPPERM INNER JOIN
			      FACTIMPDET ON FACTIMPPERM.FID_INDICED = FACTIMPDET.FID_INDICED
			WHERE FACTIMPDET.FID_DEF_TIP = 'R' AND FACTIMPPERM.PED_INDICED = PERMISODET.PED_INDICED),0)
	FROM         PERMISODET
	WHERE     PED_CANT > 0


	UPDATE FACTEXPDET
	SET FACTEXPDET.FED_GRA_MP=ROUND((FACTEXPDET.FED_COS_UNI- (FACTEXPDET.FED_GRA_GI + FACTEXPDET.FED_NG_USA + FACTEXPDET.FED_NG_EMP + FACTEXPDET.FED_NG_ADD +
	                       FACTEXPDET.FED_GRA_MO + FACTEXPDET.FED_GRA_GI_MX + FACTEXPDET.FED_GRA_EMP + FACTEXPDET.FED_GRA_ADD)),6)
	FROM         FACTEXPDET INNER JOIN
	                      FACTEXP ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO INNER JOIN
	                      CONFIGURATEMBARQUE ON FACTEXP.TQ_CODIGO = CONFIGURATEMBARQUE.TQ_CODIGO INNER JOIN
	                      CONFIGURATIPO ON FACTEXPDET.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
	WHERE     (CONFIGURATEMBARQUE.CFQ_TIPO = 'N') AND (CONFIGURATIPO.CFT_TIPO = 'P' OR
	                      CONFIGURATIPO.CFT_TIPO = 'S') AND 
	                      ROUND((FACTEXPDET.FED_COS_UNI - (FACTEXPDET.FED_GRA_GI + FACTEXPDET.FED_NG_MP + FACTEXPDET.FED_NG_EMP + FACTEXPDET.FED_NG_ADD +
	                       FACTEXPDET.FED_GRA_MO + FACTEXPDET.FED_GRA_GI_MX + FACTEXPDET.FED_GRA_MP + FACTEXPDET.FED_GRA_EMP + FACTEXPDET.FED_GRA_ADD)),6)>1
	AND 
		FACTEXPDET.FED_COS_UNI- (FACTEXPDET.FED_GRA_GI + FACTEXPDET.FED_NG_USA + FACTEXPDET.FED_NG_EMP + FACTEXPDET.FED_NG_ADD +
	                       FACTEXPDET.FED_GRA_MO + FACTEXPDET.FED_GRA_GI_MX + FACTEXPDET.FED_GRA_EMP + FACTEXPDET.FED_GRA_ADD)>0
	
	
	UPDATE FACTEXPDET
	SET   FED_COS_TOT=ROUND(FED_COS_UNI*FED_CANT,6)
	WHERE ROUND((FED_COS_TOT-FED_COS_UNI*FED_CANT),6)>1 AND FED_COS_UNI>0 AND FED_CANT>0

	EXEC SP_ACTUALIZACONSECUTIVO


	UPDATE FACTEXPDET
	SET     FACTEXPDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         FACTEXPDET INNER JOIN
	                      MAESTRO ON FACTEXPDET.FED_NOPARTE = MAESTRO.MA_NOPARTE AND FACTEXPDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')

	UPDATE FACTIMPDET
	SET     FACTIMPDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         FACTIMPDET INNER JOIN
	                      MAESTRO ON FACTIMPDET.FID_NOPARTE = MAESTRO.MA_NOPARTE AND FACTIMPDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')

	UPDATE PEDIMPDET
	SET     PEDIMPDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         PEDIMPDET INNER JOIN
	                      MAESTRO ON PEDIMPDET.PID_NOPARTE = MAESTRO.MA_NOPARTE AND PEDIMPDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')

	UPDATE PIDescarga
	SET     PIDescarga.MA_CODIGO= PEDIMPDET.MA_CODIGO
	FROM         PEDIMPDET INNER JOIN
	                      PIDescarga ON PEDIMPDET.PID_INDICED = PIDescarga.PID_INDICED 
		AND PEDIMPDET.MA_CODIGO <> PIDescarga.MA_CODIGO

	UPDATE LISTAEXPDET
	SET     LISTAEXPDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         LISTAEXPDET INNER JOIN
	                      MAESTRO ON LISTAEXPDET.LED_NOPARTE = MAESTRO.MA_NOPARTE AND LISTAEXPDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')


	UPDATE PCKLISTDET
	SET     PCKLISTDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         PCKLISTDET INNER JOIN
	                      MAESTRO ON PCKLISTDET.PLD_NOPARTE = MAESTRO.MA_NOPARTE AND PCKLISTDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')































GO
