SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE dbo.SP_EXHIBITB_247 (@CS_CODIGO INT)   as

SET NOCOUNT ON 
BEGIN
	DELETE COSTSUBB_247 WHERE CS_CODIGO=@CS_CODIGO
	
	INSERT INTO COSTSUBB_247(NOCOLUMNA, VALOR, CS_CODIGO, ET_ENTRY_NO,FE_FOLIO, TITULO1COL, ET_FEC_ENTRYS)
	SELECT  'COLUMN (2)',  SUM(ETA_COS_TOT) AS COL2_VALOR,  CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO, 'Total Ent. Value', ET_FEC_ENTRYS
	FROM VEXHIBIT_B_BASE247  GROUP BY CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO, ET_FEC_ENTRYS 
	HAVING CS_CODIGO IS NOT NULL AND CS_CODIGO=@CS_CODIGO
	
	-- componentes originarios dentro del producto terminado
	INSERT INTO COSTSUBB_247(NOCOLUMNA, VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, TITULO1COL, TITULO2COL, ET_FEC_ENTRYS)
	/*SELECT  'COLUMN (3)',  COL2_VALOR,  CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO,'Value Entered Non-Dut.','9802.00.80', ET_FEC_ENTRYS
	FROM VEXHIBIT_B2_247 WHERE CS_CODIGO IS NOT NULL AND CS_CODIGO=@CS_CODIGO
	*/
	SELECT 'COLUMN (3)',  SUM(ETA_NG_MAT) AS COL2_VALOR, CS_CODIGO, ET_ENTRY_NO,  FE_FOLIO, 'Value Entered Non-Dut.','9802.00.80', ET_FEC_ENTRYS
	FROM VEXHIBIT_B_BASE247
	WHERE ((FRACCIONORIG LIKE '9802.00.80%') OR (FRACCIONORIG LIKE '98020080%'))
	AND CS_CODIGO=@CS_CODIGO
	GROUP BY CS_CODIGO, ET_CODIGO, FE_CODIGO, FRACCIONORIG, ET_ENTRY_NO, FE_FOLIO, ET_FEC_ENTRYS
	
	-- empaque originario
	INSERT INTO COSTSUBB_247(NOCOLUMNA, VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, TITULO1COL, TITULO2COL, ET_FEC_ENTRYS)
	/*SELECT  'COLUMN (3)',  COL2_VALOR,  CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO,'Value Entered Non-Dut.','9801.00.10', ET_FEC_ENTRYS
	FROM VEXHIBIT_B3_247 WHERE CS_CODIGO IS NOT NULL AND CS_CODIGO=@CS_CODIGO*/
	SELECT 'COLUMN (3)', SUM(ETA_NG_EMP) AS COL2_VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, 'Value Entered Non-Dut.','9801.00.10', 
	    ET_FEC_ENTRYS
	FROM VEXHIBIT_B_BASE247
	WHERE ((FRACCIONNGEMP LIKE '9801.00.10%') OR (FRACCIONNGEMP LIKE '98010010%'))
	AND CS_CODIGO=@CS_CODIGO
	GROUP BY CS_CODIGO, ET_CODIGO, FE_CODIGO, FRACCIONNGEMP, ET_ENTRY_NO, FE_FOLIO, ET_FEC_ENTRYS
	
	
	-- retrabajo
	INSERT INTO COSTSUBB_247(NOCOLUMNA, VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, TITULO1COL, TITULO2COL, ET_FEC_ENTRYS)
	/*SELECT  'COLUMN (3)',  COL2_VALOR,  CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO,'Value Entered Non-Dut.', '9802.00.40', ET_FEC_ENTRYS
	 FROM VEXHIBIT_B4_247 WHERE CS_CODIGO IS NOT NULL AND CS_CODIGO=@CS_CODIGO*/
	SELECT 'COLUMN (3)', SUM(ETA_NG_MAT) AS COL2_VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, 'Value Entered Non-Dut.', '9802.00.40',
	  ET_FEC_ENTRYS
	FROM VEXHIBIT_B_BASE247
	WHERE ((AR_FRACCION LIKE '9802.00.40%') OR (AR_FRACCION LIKE '9802.00.50%') OR (AR_FRACCION LIKE '98020040%') 
	   OR (AR_FRACCION LIKE '98020050%'))
	AND CS_CODIGO=@CS_CODIGO
	GROUP BY CS_CODIGO, ET_CODIGO, FE_CODIGO, AR_FRACCION, ET_ENTRY_NO, FE_FOLIO, ET_FEC_ENTRYS
	
	
	
	INSERT INTO COSTSUBB_247(NOCOLUMNA, VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, TITULO1COL, TITULO2COL, ET_FEC_ENTRYS)
	/*SELECT  'COLUMN (3)',  COL2_VALOR,  CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO,'Value Entered Non-Dut.', '9802.00.60', ET_FEC_ENTRYS
	 FROM VEXHIBIT_B5_247 WHERE CS_CODIGO IS NOT NULL AND CS_CODIGO=@CS_CODIGO*/
	SELECT 'COLUMN (3)',  SUM(ETA_NG_MAT) AS COL2_VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, 'Value Entered Non-Dut.', '9802.00.60', 
	   ET_FEC_ENTRYS
	FROM VEXHIBIT_B_BASE247
	WHERE ((AR_FRACCION LIKE '9802.00.60%') OR (AR_FRACCION LIKE '98020060%'))
	AND CS_CODIGO=@CS_CODIGO
	GROUP BY CS_CODIGO, ET_CODIGO, FE_CODIGO, AR_FRACCION, ET_ENTRY_NO, FE_FOLIO, ET_FEC_ENTRYS
	
	
	
	INSERT INTO COSTSUBB_247(NOCOLUMNA, VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, TITULO1COL, TITULO2COL, RATE, ET_FEC_ENTRYS)
	SELECT  'COLUMN (4)',  SUM(ETA_GRAV_MAT+ETA_GRAV_VA),  CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO,'Dut. Value Entered Under Each Rate',
	CONVERT(varchar(40), ETA_RATE) +' %', ETA_RATE, ET_FEC_ENTRYS 
	FROM  VEXHIBIT_B_BASE247 GROUP BY  CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO, ETA_RATE, ET_FEC_ENTRYS 
	HAVING CS_CODIGO IS NOT NULL AND CS_CODIGO=@CS_CODIGO
	AND SUM(ETA_GRAV_MAT+ETA_GRAV_VA)>0
	
	INSERT INTO COSTSUBB_247(NOCOLUMNA, VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, TITULO1COL, ET_FEC_ENTRYS)
	SELECT 'COLUMN (5)',  SUM(ETA_GRAV_MAT+ETA_GRAV_VA) AS ETA_COS_TOT, CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO, 'Total Dut. Value', ET_FEC_ENTRYS
	FROM VEXHIBIT_B_BASE247 GROUP BY CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO, ET_FEC_ENTRYS 
	HAVING CS_CODIGO IS NOT NULL AND CS_CODIGO=@CS_CODIGO
	
	INSERT INTO COSTSUBB_247(NOCOLUMNA, VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, TITULO1COL, ET_FEC_ENTRYS)
	SELECT 'COLUMN (8)', SUM(ETA_DUT_PAG) AS ETA_DUT_PAG,  CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO, 'Total Dut. Paid', ET_FEC_ENTRYS
	FROM VEXHIBIT_B_BASE247  GROUP BY CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO, ET_FEC_ENTRYS 
	HAVING CS_CODIGO IS NOT NULL AND CS_CODIGO=@CS_CODIGO
	
	INSERT INTO COSTSUBB_247(NOCOLUMNA, VALOR, CS_CODIGO, ET_ENTRY_NO, FE_FOLIO, TITULO1COL, ET_FEC_ENTRYS)
	SELECT 'COLUMN (8)', SUM(ETA_DLLS_MPF) AS ETA_DLLS_MPF,  CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO, 'M.P.F.', ET_FEC_ENTRYS
	FROM VEXHIBIT_B_BASE247 GROUP BY CS_CODIGO,  ET_ENTRY_NO,  FE_FOLIO, ET_FEC_ENTRYS 
	HAVING CS_CODIGO IS NOT NULL AND CS_CODIGO=@CS_CODIGO;
	
	
END





GO
