SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
























CREATE PROCEDURE [dbo].[SP_ACTUALIZAEQGEN] (@MA_CODIGO INT)   as

SET NOCOUNT ON 
DECLARE @ME_CODIGO INT, @ME_COM int, @ME_KILOGRAMOS int

	SELECT @ME_CODIGO=ME_COM FROM MAESTRO WHERE MA_CODIGO IN (SELECT MA_GENERICO FROM MAESTRO WHERE MA_CODIGO=@MA_CODIGO)
	SELECT @ME_COM=ME_COM FROM MAESTRO WHERE MA_CODIGO =@MA_CODIGO

	select @ME_KILOGRAMOS=ME_KILOGRAMOS from configuracion

		if exists (SELECT dbo.MAESTRO.EQ_GEN FROM dbo.MAESTRO INNER JOIN
			                      dbo.MAESTRO MAESTRO_1 ON dbo.MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO INNER JOIN
			                      dbo.EQUIVALE ON dbo.MAESTRO.ME_COM = dbo.EQUIVALE.ME_CODIGO1 AND MAESTRO_1.ME_COM = dbo.EQUIVALE.ME_CODIGO2
			WHERE     (dbo.MAESTRO.MA_CODIGO = @MA_CODIGO))

			update dbo.MAESTRO
			SET     dbo.MAESTRO.EQ_GEN= dbo.EQUIVALE.EQ_CANT
			FROM         dbo.MAESTRO INNER JOIN
			                      dbo.MAESTRO MAESTRO_1 ON dbo.MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO INNER JOIN
			                      dbo.EQUIVALE ON dbo.MAESTRO.ME_COM = dbo.EQUIVALE.ME_CODIGO1 AND MAESTRO_1.ME_COM = dbo.EQUIVALE.ME_CODIGO2
			WHERE     (dbo.MAESTRO.MA_CODIGO = @MA_CODIGO)

		else
			UPDATE MAESTRO
			SET EQ_GEN = 1
			WHERE MA_CODIGO = @MA_CODIGO


		if @ME_CODIGO =@ME_KILOGRAMOS
		begin
			UPDATE MAESTRO
			SET EQ_GEN = MA_PESO_KG
			WHERE MA_CODIGO = @MA_CODIGO and MA_PESO_KG>0


			UPDATE MAESTRO
			SET EQ_GEN = 1
			WHERE MA_CODIGO = @MA_CODIGO and MA_PESO_KG=0
			AND ME_COM not in (SELECT ME_CODIGO1 FROM EQUIVALE
			WHERE     ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))



			if @ME_COM =@ME_KILOGRAMOS
			UPDATE MAESTRO
			SET EQ_GEN = 1
			WHERE MA_CODIGO = @MA_CODIGO

		end





	SELECT @ME_CODIGO=ME_COM FROM MAESTRO WHERE MA_CODIGO IN (SELECT MA_GENERICOFIS FROM ANEXO24 WHERE MA_CODIGO=@MA_CODIGO)
	SELECT @ME_COM=ME_COM FROM MAESTRO WHERE MA_CODIGO =@MA_CODIGO

	select @ME_KILOGRAMOS=ME_KILOGRAMOS from configuracion

		if exists (SELECT     dbo.ANEXO24.EQ_GENERICOFIS
			FROM         dbo.MAESTRO INNER JOIN
			                      dbo.EQUIVALE ON dbo.MAESTRO.ME_COM = dbo.EQUIVALE.ME_CODIGO1 INNER JOIN
			                      dbo.MAESTRO MAESTRO_1 ON dbo.EQUIVALE.ME_CODIGO2 = MAESTRO_1.ME_COM INNER JOIN
			                      dbo.ANEXO24 ON dbo.MAESTRO.MA_CODIGO = dbo.ANEXO24.MA_CODIGO AND MAESTRO_1.MA_CODIGO = dbo.ANEXO24.MA_GENERICOFIS
			WHERE     (dbo.MAESTRO.MA_CODIGO = @MA_CODIGO))

			update dbo.ANEXO24
			SET     dbo.ANEXO24.EQ_GENERICOFIS= dbo.EQUIVALE.EQ_CANT
			FROM         dbo.MAESTRO INNER JOIN
			                      dbo.EQUIVALE ON dbo.MAESTRO.ME_COM = dbo.EQUIVALE.ME_CODIGO1 INNER JOIN
			                      dbo.MAESTRO MAESTRO_1 ON dbo.EQUIVALE.ME_CODIGO2 = MAESTRO_1.ME_COM INNER JOIN
			                      dbo.ANEXO24 ON dbo.MAESTRO.MA_CODIGO = dbo.ANEXO24.MA_CODIGO AND MAESTRO_1.MA_CODIGO = dbo.ANEXO24.MA_GENERICOFIS
			WHERE     (dbo.MAESTRO.MA_CODIGO = @MA_CODIGO)

		else
			UPDATE ANEXO24
			SET EQ_GENERICOFIS = 1
			WHERE MA_CODIGO = @MA_CODIGO


		if @ME_CODIGO =@ME_KILOGRAMOS
		begin
			UPDATE ANEXO24
			SET EQ_GENERICOFIS = MA_PESO_KG
			FROM MAESTRO INNER JOIN ANEXO24 ON MAESTRO.MA_CODIGO=ANEXO24.MA_CODIGO
			WHERE ANEXO24.MA_CODIGO = @MA_CODIGO and MA_PESO_KG>0


			UPDATE ANEXO24
			SET EQ_GENERICOFIS = 1
			FROM MAESTRO INNER JOIN ANEXO24 ON MAESTRO.MA_CODIGO=ANEXO24.MA_CODIGO
			WHERE ANEXO24.MA_CODIGO = @MA_CODIGO and MA_PESO_KG=0
			AND ME_COM not in (SELECT ME_CODIGO1 FROM EQUIVALE
			WHERE     ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))



			if @ME_COM =@ME_KILOGRAMOS
			UPDATE ANEXO24
			SET EQ_GENERICOFIS = 1
			WHERE ANEXO24.MA_CODIGO = @MA_CODIGO

		end


		begin tran
		UPDATE  BOM_STRUCT
		SET     BOM_STRUCT.ME_CODIGO= MAESTRO.ME_COM
		FROM         BOM_STRUCT INNER JOIN
		                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO
		WHERE     (BOM_STRUCT.ME_CODIGO = 0) AND MAESTRO.ME_COM<>0
		and bst_hijo= @MA_CODIGO
		commit tran

		begin tran
		UPDATE BOM_STRUCT
		SET     BOM_STRUCT.ME_GEN= MAESTRO_1.ME_COM
		FROM         BOM_STRUCT INNER JOIN
		                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO INNER JOIN
		                      MAESTRO MAESTRO_1 ON MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO AND BOM_STRUCT.ME_GEN <> MAESTRO_1.ME_COM
		and bst_hijo= @MA_CODIGO
		commit tran


		begin tran
		UPDATE BOM_STRUCT
		SET     BOM_STRUCT.FACTCONV= MAESTRO.EQ_GEN
		FROM         BOM_STRUCT INNER JOIN
		                     MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO AND BOM_STRUCT.ME_CODIGO = MAESTRO.ME_COM AND 
		                      BOM_STRUCT.FACTCONV <> MAESTRO.EQ_GEN
		and bst_hijo= @MA_CODIGO
		commit tran






















GO
