SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
































CREATE PROCEDURE [dbo].[SP_ACTUALIZATASAMAESTRO]   as

SET NOCOUNT ON 

	if not exists(select * from arancel where convert(varchar(11),AR_ULTMODIFTIGIE,101)= convert(varchar(11),getdate(),101))
	exec SP_ACTUALIZAARANCELBASETIGIE

	-- actualiza tasas
	UPDATE MAESTRO  
	SET MAESTRO.SPI_CODIGO=0, 
	MAESTRO.MA_SEC_IMP=0 
	FROM  MAESTRO INNER JOIN 
	  ARANCEL ON MAESTRO.AR_IMPMX = ARANCEL.AR_CODIGO 
	WHERE     (MAESTRO.MA_DEF_TIP = 'G') 

	
	UPDATE MAESTRO  
	SET /*MAESTRO.MA_POR_DEF= ARANCEL.AR_PORCENT_8VA,*/ MAESTRO.SPI_CODIGO=0, 
	MAESTRO.MA_SEC_IMP=0 
	FROM  MAESTRO INNER JOIN 
	  ARANCEL ON MAESTRO.AR_IMPMX = ARANCEL.AR_CODIGO 
	WHERE     (MAESTRO.MA_DEF_TIP = 'R') 


	UPDATE MAESTRO  
	SET /*MAESTRO.MA_POR_DEF= PAISARA.PAR_BEN,*/ MAESTRO.MA_SEC_IMP=0, MAESTRO.SPI_CODIGO=22 
	FROM MAESTRO INNER JOIN 
	PAISARA ON MAESTRO.AR_IMPMX = PAISARA.AR_CODIGO AND MAESTRO.PA_ORIGEN = PAISARA.PA_CODIGO 
	WHERE (MAESTRO.MA_DEF_TIP = 'P') 
	AND MAESTRO.PA_ORIGEN =233


	UPDATE MAESTRO  
	SET /*MAESTRO.MA_POR_DEF= PAISARA.PAR_BEN,*/ MAESTRO.MA_SEC_IMP=0
	FROM MAESTRO INNER JOIN 
	PAISARA ON MAESTRO.AR_IMPMX = PAISARA.AR_CODIGO AND MAESTRO.SPI_CODIGO = PAISARA.SPI_CODIGO 
	WHERE (MAESTRO.MA_DEF_TIP = 'P') 
	AND MAESTRO.PA_ORIGEN <>233



	UPDATE MAESTRO
	SET     MAESTRO.MA_SEC_IMP= (SELECT SE_CODIGO FROM CONFIGURACION)
	FROM         MAESTRO
	WHERE     (MAESTRO.MA_DEF_TIP = 'S') AND (MAESTRO.MA_SEC_IMP = 0 OR
	                      MAESTRO.MA_SEC_IMP IS NULL) 


	UPDATE MAESTRO  
	SET   MAESTRO.SPI_CODIGO=0 
	FROM  MAESTRO INNER JOIN 
	 SECTORARA ON MAESTRO.AR_IMPMX = SECTORARA.AR_CODIGO AND 
	 MAESTRO.MA_SEC_IMP = SECTORARA.SE_CODIGO 
	WHERE (MAESTRO.MA_DEF_TIP = 'S')
























GO
