SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO































CREATE PROCEDURE [dbo].[SP_FACTEXPAGRU]  (@FEA_CODIGO INT)   as


EXEC SP_DROPTABLE 'FACTEXPAGRUDET'

SELECT     FACTEXPDET.MA_CODIGO, MAX(FACTEXPDET.FED_NOMBRE) AS FED_NOMBRE, FACTEXPDET.FED_NOPARTE, MAX(FACTEXPDET.FED_NAME) 
                      AS FED_NAME, FACTEXPDET.ME_CODIGO, FACTEXPDET.FED_OBSERVA, SUM(FACTEXPDET.FED_CANT) AS FED_CANT, FACTEXPDET.FED_GRA_MP, 
                      FACTEXPDET.FED_GRA_MO, FACTEXPDET.FED_GRA_EMP, FACTEXPDET.FED_GRA_ADD, FACTEXPDET.FED_GRA_GI, 
                      FACTEXPDET.FED_GRA_GI_MX, FACTEXPDET.FED_NG_MP, FACTEXPDET.FED_NG_EMP, FACTEXPDET.FED_NG_ADD, FACTEXPDET.FED_NG_USA, 
                      FACTEXPDET.FED_COS_UNI, SUM(FACTEXPDET.FED_COS_TOT) AS FED_COS_TOT, FACTEXPDET.FED_PES_UNI, SUM(FACTEXPDET.FED_PES_NET) 
                      AS FED_PES_NET, SUM(FACTEXPDET.FED_PES_BRU) AS FED_PES_BRU, FACTEXPDET.FED_SEC_IMP, FACTEXPDET.FED_DEF_TIP, 
                      FACTEXPDET.FED_POR_DEF, FACTEXPDET.FED_LOTE, FACTEXPDET.AR_IMPMX, FACTEXPDET.AR_EXPMX, FACTEXPDET.AR_IMPFO, 
                      FACTEXPDET.FED_CON_PED, FACTEXPDET.MA_GENERICO, FACTEXPDET.PA_CODIGO, FACTEXPDET.LE_CODIGO, FACTEXPDET.LED_INDICED, 
                      FACTEXPDET.FED_ORD_COMP, FACTEXPDET.FED_NOORDEN, FACTEXPDET.EQ_GEN, FACTEXPDET.EQ_IMPFO, FACTEXPDET.EQ_EXPMX, 
                      FACTEXPDET.TI_CODIGO, FACTEXPDET.FED_TENVIO, FACTEXPDET.FED_INBOND, FACTEXPDET.FED_TIPOINBOND, FACTEXPDET.FED_RATEEXPMX, 
                      FACTEXPDET.FED_RATEIMPFO, FACTEXPDET.LE_FOLIO, FACTEXPDET.SPI_CODIGO, FACTEXPDET.FED_RETRABAJO, FACTEXPDET.MA_EMPAQUE, 
                      SUM(FACTEXPDET.FED_CANTEMP) AS FED_CANTEMP, FACTEXPDET.FED_FAC_NUM, FACTEXPDET.FED_FEC_ENV, FACTEXPDET.FED_PARTTYPE, 
                      FACTEXPDET.ME_GENERICO, FACTEXPDET.FED_TIP_ENS, FACTEXPDET.ME_AREXPMX, FACTEXPDET.FED_NAFTA, FACTEXPDET.TCO_CODIGO, 
                      FACTEXPDET.SE_CODIGO, FACTEXPDET.CL_CODIGO, FACTEXPDET.MA_STRUCT, FACTEXPDET.FED_DESTNAFTA, FACTEXPDET.AR_ORIG, 
                      FACTEXPDET.AR_NG_EMP, FACTEXPDET.FED_NOPARTEAUX, FACTEXP.FE_FACTAGRU, VNAFTAFACTEXP.PA_CLASE, (SELECT SUM(FACTEXP1.FE_TOTALB) FROM FACTEXP FACTEXP1 WHERE FACTEXP1.FE_FACTAGRU=FACTEXP.FE_FACTAGRU) AS FEA_TOTALB
INTO dbo.FACTEXPAGRUDET
FROM         FACTEXPDET INNER JOIN
                      FACTEXP ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO LEFT OUTER JOIN VNAFTAFACTEXP ON
		FACTEXPDET.FED_INDICED=VNAFTAFACTEXP.FED_INDICED
WHERE FACTEXP.FE_FACTAGRU=@FEA_CODIGO
GROUP BY FACTEXPDET.MA_CODIGO, FACTEXPDET.FED_NOPARTE, FACTEXPDET.ME_CODIGO, FACTEXPDET.FED_OBSERVA, FACTEXPDET.FED_GRA_MP, 
                      FACTEXPDET.FED_GRA_MO, FACTEXPDET.FED_GRA_EMP, FACTEXPDET.FED_GRA_ADD, FACTEXPDET.FED_GRA_GI, 
                      FACTEXPDET.FED_GRA_GI_MX, FACTEXPDET.FED_NG_MP, FACTEXPDET.FED_NG_EMP, FACTEXPDET.FED_NG_ADD, FACTEXPDET.FED_NG_USA, 
                      FACTEXPDET.FED_COS_UNI, FACTEXPDET.FED_PES_UNI, FACTEXPDET.FED_SEC_IMP, FACTEXPDET.FED_DEF_TIP, FACTEXPDET.FED_POR_DEF, 
                      FACTEXPDET.FED_LOTE, FACTEXPDET.AR_IMPMX, FACTEXPDET.AR_EXPMX, FACTEXPDET.AR_IMPFO, FACTEXPDET.FED_CON_PED, 
                      FACTEXPDET.MA_GENERICO, FACTEXPDET.PA_CODIGO, FACTEXPDET.LE_CODIGO, FACTEXPDET.LED_INDICED, FACTEXPDET.FED_ORD_COMP, 
                      FACTEXPDET.FED_NOORDEN, FACTEXPDET.EQ_GEN, FACTEXPDET.EQ_IMPFO, FACTEXPDET.EQ_EXPMX, FACTEXPDET.TI_CODIGO, 
                      FACTEXPDET.FED_TENVIO, FACTEXPDET.FED_INBOND, FACTEXPDET.FED_TIPOINBOND, FACTEXPDET.FED_RATEEXPMX, 
                      FACTEXPDET.FED_RATEIMPFO, FACTEXPDET.LE_FOLIO, FACTEXPDET.SPI_CODIGO, FACTEXPDET.FED_RETRABAJO, FACTEXPDET.MA_EMPAQUE, 
                      FACTEXPDET.FED_FAC_NUM, FACTEXPDET.FED_FEC_ENV, FACTEXPDET.FED_PARTTYPE, FACTEXPDET.ME_GENERICO, 
                      FACTEXPDET.FED_TIP_ENS, FACTEXPDET.ME_AREXPMX, FACTEXPDET.FED_NAFTA, FACTEXPDET.TCO_CODIGO, FACTEXPDET.SE_CODIGO, 
                      FACTEXPDET.CL_CODIGO, FACTEXPDET.MA_STRUCT, FACTEXPDET.FED_DESTNAFTA, FACTEXPDET.AR_ORIG, FACTEXPDET.AR_NG_EMP, 
                      FACTEXPDET.FED_NOPARTEAUX, FACTEXP.FE_FACTAGRU, VNAFTAFACTEXP.PA_CLASE






























GO
