SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO































CREATE PROCEDURE [dbo].[SP_INSERTPERMISODET] (@FI_CODIGO INT)   as

DECLARE @FI_FECHA DATETIME, @consecutivo int


SELECT @FI_FECHA=FI_FECHA FROM FACTIMP WHERE FI_CODIGO=@FI_CODIGO


	IF EXISTS (SELECT FACTIMPPERM.* FROM FACTIMPPERM LEFT OUTER JOIN VPERMISODETAR ON FACTIMPPERM.PED_INDICED=VPERMISODETAR.PED_INDICED
		LEFT OUTER JOIN PERMISO ON VPERMISODETAR.PE_CODIGO=PERMISO.PE_CODIGO LEFT OUTER JOIN IDENTIFICA ON PERMISO.IDE_CODIGO=IDENTIFICA.IDE_CODIGO
		WHERE     IDENTIFICA.IDE_CLAVE IN ('MQ', 'PX') AND FI_CODIGO=@FI_CODIGO)
	DELETE FACTIMPPERM 
	FROM FACTIMPPERM LEFT OUTER JOIN VPERMISODETAR ON FACTIMPPERM.PED_INDICED=VPERMISODETAR.PED_INDICED
		LEFT OUTER JOIN PERMISO ON VPERMISODETAR.PE_CODIGO=PERMISO.PE_CODIGO 
		LEFT OUTER JOIN IDENTIFICA ON PERMISO.IDE_CODIGO=IDENTIFICA.IDE_CODIGO
	WHERE     IDENTIFICA.IDE_CLAVE IN ('MQ','PX') AND FI_CODIGO=@FI_CODIGO



	exec sp_droptable 'FactImpPermTmp'
	CREATE TABLE [dbo].[FactImpPermTmp] (
		[FIR_CODIGO] [int] IDENTITY (1, 1) NOT NULL ,
		[FID_INDICED] [int] NOT NULL ,
		[FI_CODIGO] [int] NOT NULL ,
		[PE_CODIGO] [int] NOT NULL ,
		[PED_INDICED] [int] NOT NULL ,
		[CPE_CODIGO] [int] NULL ,
		[EQ_CANT] decimal(38,6) NULL ,
		[FIP_ESTATUSAFECTA] [smallint] NOT NULL CONSTRAINT [DF_FactImpPermTmp_FIP_ESTATUSAFECTA] DEFAULT (0)
	        ) ON [PRIMARY]
	
	set @consecutivo =(select isnull(max(FIR_CODIGO),0) from FACTIMPPERM)+1

	dbcc checkident (FactImpPermTmp, reseed, @consecutivo) WITH NO_INFOMSGS


	IF (SELECT CF_USADESCSICEX FROM CONFIGURACION)='S' 
	BEGIN
		INSERT INTO FactImpPermTmp(FID_INDICED, FI_CODIGO, PED_INDICED, PE_CODIGO, CPE_CODIGO)
		SELECT     dbo.FACTIMPDET.FID_INDICED, dbo.FACTIMPDET.FI_CODIGO, MIN(dbo.VPERMISODETAR.PED_INDICED) AS PED_INDICED,
			(SELECT PERMISODET2.PE_CODIGO FROM PERMISODET PERMISODET2 WHERE PERMISODET2.PED_INDICED=MIN(dbo.VPERMISODETAR.PED_INDICED)),
			(SELECT C1. MA_GENERICO FROM PERMISODET C1 WHERE C1.PED_INDICED=MIN(dbo.VPERMISODETAR.PED_INDICED))
		FROM         dbo.MAESTROCATEG INNER JOIN
		                      dbo.FACTIMPDET INNER JOIN
		                      dbo.VPERMISODETAR ON dbo.FACTIMPDET.MA_GENERICO = dbo.VPERMISODETAR.MA_GENERICO ON 
		                      dbo.MAESTROCATEG.MA_CODIGO = dbo.FACTIMPDET.MA_CODIGO AND 
		                      dbo.VPERMISODETAR.PED_NOMBRE = dbo.FACTIMPDET.FID_NOMBRE AND 				
		                      dbo.MAESTROCATEG.CPE_CODIGO = dbo.VPERMISODETAR.MA_GENERICO LEFT OUTER JOIN
		                      dbo.PERMISO LEFT OUTER JOIN
		                      dbo.IDENTIFICA ON dbo.PERMISO.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO ON dbo.VPERMISODETAR.PE_CODIGO = dbo.PERMISO.PE_CODIGO
		WHERE     (dbo.PERMISO.PE_APROBADO = 'S') AND (dbo.PERMISO.PE_FECHA <= @FI_FECHA) AND (dbo.IDENTIFICA.IDE_CLAVE IN ('MQ','PX'))
		GROUP BY dbo.FACTIMPDET.FID_INDICED, dbo.FACTIMPDET.FI_CODIGO
		HAVING      (dbo.FACTIMPDET.FI_CODIGO = @FI_CODIGO)

	END
	ELSE
	BEGIN
		INSERT INTO FactImpPermTmp(FID_INDICED, FI_CODIGO, PED_INDICED, PE_CODIGO, CPE_CODIGO)
		SELECT     dbo.FACTIMPDET.FID_INDICED, dbo.FACTIMPDET.FI_CODIGO, MIN(dbo.VPERMISODETAR.PED_INDICED) AS PED_INDICED,
			(SELECT PERMISODET2.PE_CODIGO FROM PERMISODET PERMISODET2 WHERE PERMISODET2.PED_INDICED=MIN(dbo.VPERMISODETAR.PED_INDICED)),
			(SELECT C1. MA_GENERICO FROM PERMISODET C1 WHERE C1.PED_INDICED=MIN(dbo.VPERMISODETAR.PED_INDICED))
		FROM         dbo.MAESTROCATEG INNER JOIN
		                      dbo.FACTIMPDET INNER JOIN
		                      dbo.VPERMISODETAR ON dbo.FACTIMPDET.MA_GENERICO = dbo.VPERMISODETAR.MA_GENERICO ON 
		                      dbo.MAESTROCATEG.MA_CODIGO = dbo.FACTIMPDET.MA_CODIGO AND 
		                      dbo.MAESTROCATEG.CPE_CODIGO = dbo.VPERMISODETAR.MA_GENERICO LEFT OUTER JOIN
		                      dbo.PERMISO LEFT OUTER JOIN
		                      dbo.IDENTIFICA ON dbo.PERMISO.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO ON dbo.VPERMISODETAR.PE_CODIGO = dbo.PERMISO.PE_CODIGO
		WHERE     (dbo.PERMISO.PE_APROBADO = 'S') AND (dbo.PERMISO.PE_FECHA <= @FI_FECHA) AND (dbo.IDENTIFICA.IDE_CLAVE IN ('MQ','PX'))
		GROUP BY dbo.FACTIMPDET.FID_INDICED, dbo.FACTIMPDET.FI_CODIGO
		HAVING      (dbo.FACTIMPDET.FI_CODIGO = @FI_CODIGO)
	END



	UPDATE FactImpPermTmp
	SET EQ_CANT = ISNULL((SELECT EQ_CANT FROM MAESTROCATEG WHERE MA_CODIGO  IN 
			  (SELECT MA_CODIGO FROM FACTIMPDET WHERE FID_INDICED=FactImpPermTmp.FID_INDICED) 
			AND CPE_CODIGO=FactImpPermTmp.CPE_CODIGO),1)


	INSERT INTO FACTIMPPERM(FIR_CODIGO, FID_INDICED, FI_CODIGO, PE_CODIGO, PED_INDICED, FIP_ESTATUSAFECTA, CPE_CODIGO, EQ_CANT)
	
	SELECT     FIR_CODIGO, FID_INDICED, FI_CODIGO, PE_CODIGO, PED_INDICED, FIP_ESTATUSAFECTA, CPE_CODIGO, EQ_CANT
	FROM         FactImpPermTmp



	

	update consecutivo
	set cv_codigo =  (select isnull(max(FIR_CODIGO),0) from FACTIMPPERM) + 1
	where cv_tipo = 'FIR'


	exec sp_droptable 'FactImpPermTmp'




























GO
