SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

















































-- actualiza la familia de las materias primas en base a su parent, esto significa que se debio haber asignado primero al padre la familia correspondiente
CREATE PROCEDURE [dbo].[SP_ACTUALIZAFAMILIAMP_12NIVELES]   as

SET NOCOUNT ON 

--NIVEL 1
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.BOM_STRUCT INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO INNER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)

-- NIVEL 2
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.MAESTRO MAESTRO_1 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_1.BST_HIJO = dbo.MAESTRO.MA_CODIGO INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO ON 
                      MAESTRO_1.MA_CODIGO = dbo.BOM_STRUCT.BSU_SUBENSAMBLE
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)

-- NIVEL 3
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_2.BST_HIJO = dbo.MAESTRO.MA_CODIGO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)

-- NIVEL 4
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.MAESTRO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_3 ON dbo.MAESTRO.MA_CODIGO = BOM_STRUCT_3.BST_HIJO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO ON BOM_STRUCT_3.BSU_SUBENSAMBLE = BOM_STRUCT_2.BST_HIJO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)

-- NIVEL 5
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_3 ON BOM_STRUCT_2.BST_HIJO = BOM_STRUCT_3.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_4 ON BOM_STRUCT_3.BST_HIJO = BOM_STRUCT_4.BSU_SUBENSAMBLE INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_4.BST_HIJO = dbo.MAESTRO.MA_CODIGO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)


-- NIVEL 6
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA 
FROM         dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_3 ON BOM_STRUCT_2.BST_HIJO = BOM_STRUCT_3.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_4 ON BOM_STRUCT_3.BST_HIJO = BOM_STRUCT_4.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_5 ON BOM_STRUCT_4.BST_HIJO = BOM_STRUCT_5.BSU_SUBENSAMBLE INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_5.BST_HIJO = dbo.MAESTRO.MA_CODIGO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)



-- NIVEL 7
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_3 ON BOM_STRUCT_2.BST_HIJO = BOM_STRUCT_3.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_4 ON BOM_STRUCT_3.BST_HIJO = BOM_STRUCT_4.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_5 ON BOM_STRUCT_4.BST_HIJO = BOM_STRUCT_5.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_6 ON BOM_STRUCT_5.BST_HIJO = BOM_STRUCT_6.BSU_SUBENSAMBLE INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_6.BST_HIJO = dbo.MAESTRO.MA_CODIGO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)


-- NIVEL 8
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_3 ON BOM_STRUCT_2.BST_HIJO = BOM_STRUCT_3.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_4 ON BOM_STRUCT_3.BST_HIJO = BOM_STRUCT_4.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_5 ON BOM_STRUCT_4.BST_HIJO = BOM_STRUCT_5.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_6 ON BOM_STRUCT_5.BST_HIJO = BOM_STRUCT_6.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_7 ON BOM_STRUCT_6.BST_HIJO = BOM_STRUCT_7.BSU_SUBENSAMBLE INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_7.BST_HIJO = dbo.MAESTRO.MA_CODIGO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)


-- NIVEL 9
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_3 ON BOM_STRUCT_2.BST_HIJO = BOM_STRUCT_3.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_4 ON BOM_STRUCT_3.BST_HIJO = BOM_STRUCT_4.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_5 ON BOM_STRUCT_4.BST_HIJO = BOM_STRUCT_5.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_6 ON BOM_STRUCT_5.BST_HIJO = BOM_STRUCT_6.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_7 ON BOM_STRUCT_6.BST_HIJO = BOM_STRUCT_7.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_8 ON BOM_STRUCT_7.BST_HIJO = BOM_STRUCT_8.BSU_SUBENSAMBLE INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_8.BST_HIJO = dbo.MAESTRO.MA_CODIGO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)


-- NIVEL 10
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_3 ON BOM_STRUCT_2.BST_HIJO = BOM_STRUCT_3.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_4 ON BOM_STRUCT_3.BST_HIJO = BOM_STRUCT_4.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_5 ON BOM_STRUCT_4.BST_HIJO = BOM_STRUCT_5.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_6 ON BOM_STRUCT_5.BST_HIJO = BOM_STRUCT_6.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_7 ON BOM_STRUCT_6.BST_HIJO = BOM_STRUCT_7.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_8 ON BOM_STRUCT_7.BST_HIJO = BOM_STRUCT_8.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_9 ON BOM_STRUCT_8.BST_HIJO = BOM_STRUCT_9.BSU_SUBENSAMBLE INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_9.BST_HIJO = dbo.MAESTRO.MA_CODIGO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)

-- NIVEL 11
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_3 ON BOM_STRUCT_2.BST_HIJO = BOM_STRUCT_3.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_4 ON BOM_STRUCT_3.BST_HIJO = BOM_STRUCT_4.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_5 ON BOM_STRUCT_4.BST_HIJO = BOM_STRUCT_5.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_6 ON BOM_STRUCT_5.BST_HIJO = BOM_STRUCT_6.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_7 ON BOM_STRUCT_6.BST_HIJO = BOM_STRUCT_7.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_8 ON BOM_STRUCT_7.BST_HIJO = BOM_STRUCT_8.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_9 ON BOM_STRUCT_8.BST_HIJO = BOM_STRUCT_9.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_10 ON BOM_STRUCT_9.BST_HIJO = BOM_STRUCT_10.BSU_SUBENSAMBLE INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_10.BST_HIJO = dbo.MAESTRO.MA_CODIGO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)


-- NIVEL 12
UPDATE dbo.MAESTRO
SET     dbo.MAESTRO.MA_FAMILIA= MAESTRO_1.MA_FAMILIA
FROM         dbo.BOM_STRUCT BOM_STRUCT_2 INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 INNER JOIN
                      dbo.BOM_STRUCT ON BOM_STRUCT_1.BSU_SUBENSAMBLE = dbo.BOM_STRUCT.BST_HIJO INNER JOIN
                      dbo.MAESTRO MAESTRO_1 ON dbo.BOM_STRUCT.BSU_SUBENSAMBLE = MAESTRO_1.MA_CODIGO ON 
                      BOM_STRUCT_2.BSU_SUBENSAMBLE = BOM_STRUCT_1.BST_HIJO INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_3 ON BOM_STRUCT_2.BST_HIJO = BOM_STRUCT_3.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_4 ON BOM_STRUCT_3.BST_HIJO = BOM_STRUCT_4.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_5 ON BOM_STRUCT_4.BST_HIJO = BOM_STRUCT_5.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_6 ON BOM_STRUCT_5.BST_HIJO = BOM_STRUCT_6.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_7 ON BOM_STRUCT_6.BST_HIJO = BOM_STRUCT_7.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_8 ON BOM_STRUCT_7.BST_HIJO = BOM_STRUCT_8.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_9 ON BOM_STRUCT_8.BST_HIJO = BOM_STRUCT_9.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_10 ON BOM_STRUCT_9.BST_HIJO = BOM_STRUCT_10.BSU_SUBENSAMBLE INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_11 ON BOM_STRUCT_10.BST_HIJO = BOM_STRUCT_11.BSU_SUBENSAMBLE INNER JOIN
                      dbo.MAESTRO ON BOM_STRUCT_11.BST_HIJO = dbo.MAESTRO.MA_CODIGO
WHERE     (MAESTRO_1.MA_FAMILIA <> 0) AND (dbo.MAESTRO.MA_FAMILIA = 0)
















































GO
