SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

















CREATE PROCEDURE [dbo].[SP_GENERATEMP_RETRABAJO]   as




exec sp_droptable 'TEMP_RETRABAJO'

CREATE TABLE [dbo].[TEMP_RETRABAJO] (
	[RE_INDICER] [int] IDENTITY (1, 1) NOT NULL ,
	[TIPO_FACTRANS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[FETR_CODIGO] [int] NOT NULL ,
	[FETR_INDICED] [int] NOT NULL ,
	[MA_HIJO] [int] NOT NULL ,
	[RE_NOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[RE_NOMBRE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[RE_NAME] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[RE_INCORPOR] decimal(38,6) NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO_RE_INCORPOR] DEFAULT (1),
	[TI_HIJO] [smallint] NOT NULL ,
	[ME_CODIGO] [int] NULL ,
	[MA_GENERICO] [int] NULL ,
	[ME_GEN] [int] NULL ,
	[RE_INCORPORGEN] decimal(38,6) NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO_RE_INCORPORGEN] DEFAULT (1),
	[FACTCONV] decimal(28,14) NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO_FACTCONV] DEFAULT (1),
	[FETR_RETRABAJODES] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO_FETR_RETRABAJODES] DEFAULT ('S'),
	[FETR_NAFTA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO_FETR_NAFTA] DEFAULT ('N'),
	[PA_ORIGEN] [int] NULL ,
	CONSTRAINT [IX_TEMP_RETRABAJO] UNIQUE  NONCLUSTERED 
	(
		[RE_INDICER]
	)  ON [PRIMARY] 
) ON [PRIMARY]



exec sp_droptable 'TEMP_RETRABAJO1'

CREATE TABLE [dbo].[TEMP_RETRABAJO1] (
	[RE_INDICER] [int] IDENTITY (1, 1) NOT NULL ,
	[TIPO_FACTRANS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[FETR_CODIGO] [int] NOT NULL ,
	[FETR_INDICED] [int] NOT NULL ,
	[MA_HIJO] [int] NOT NULL ,
	[RE_NOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[RE_NOMBRE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[RE_NAME] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[RE_INCORPOR] decimal(38,6) NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO1_RE_INCORPOR] DEFAULT (1),
	[TI_HIJO] [smallint] NOT NULL ,
	[ME_CODIGO] [int] NULL ,
	[MA_GENERICO] [int] NULL ,
	[ME_GEN] [int] NULL ,
	[RE_INCORPORGEN] decimal(38,6) NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO1_RE_INCORPORGEN] DEFAULT (1),
	[FACTCONV] decimal(28,14) NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO1_FACTCONV] DEFAULT (1),
	[FETR_RETRABAJODES] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO1_FETR_RETRABAJODES] DEFAULT ('S'),
	[FETR_NAFTA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_TEMP_RETRABAJO1_FETR_NAFTA] DEFAULT ('N'),
	[PA_ORIGEN] [int] NULL ,
	CONSTRAINT [IX_TEMP_RETRABAJO1] UNIQUE  NONCLUSTERED 
	(
		[RE_INDICER]
	)  ON [PRIMARY] 
) ON [PRIMARY]

	dbcc checkident (TEMP_RETRABAJO1, reseed, 1) WITH NO_INFOMSGS



























GO
