SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_COPIABOMSTRUCT]  @ORIGEN INT, @DESTINO INT    as

SET NOCOUNT ON 
DECLARE @Today DateTime, @BSU_SUBENSAMBLE INT,  @NOPARTEDESTINO VARCHAR(30), 
@Today2 DATETIME


SELECT @NOPARTEDESTINO = MA_NOPARTE FROM MAESTRO WHERE MA_CODIGO = @DESTINO


Set @Today = convert(datetime, convert(varchar(11), getdate(),101))


		if (select count(*) from bom_struct where (BST_PERINI <= @Today and  BST_PERFIN>=@Today)  and BSU_SUBENSAMBLE = @DESTINO)=0
		begin
			INSERT INTO BOM_STRUCT(BSU_SUBENSAMBLE, BSU_NOPARTE, BST_HIJO, BST_NOPARTE, BST_INCORPOR, BST_DISCH,
			ME_CODIGO, FACTCONV,  BST_PERINI, BST_PERFIN, ME_GEN, 
			BST_TRANS, BST_TIP_ENS)
	
			SELECT @DESTINO, @NOPARTEDESTINO, BST_HIJO, BST_NOPARTE, BST_INCORPOR, BST_DISCH,
			ME_CODIGO, FACTCONV,  BST_PERINI, BST_PERFIN, ME_GEN, 
			BST_TRANS, BST_TIP_ENS
			FROM BOM_STRUCT 
			WHERE     (BST_PERINI <= @Today and  BST_PERFIN>=@Today) AND (BSU_SUBENSAMBLE = @ORIGEN)
			ORDER BY BST_CODIGO
		end
GO
