SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_CREAVISTASPAGOCONTRIB] (@PICODIGO INT, @CrearTablas char(1)='N')   as

DECLARE @PI_CODIGO VARCHAR(50)

SELECT @PI_CODIGO=CONVERT(VARCHAR(50),@PICODIGO)

exec('exec sp_droptable ''VDATOSPEDEXPDESCxPedExp'', ''V''')


exec('CREATE VIEW dbo.VDATOSPEDEXPDESCxPedExp
with encryption as
SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED.KAP_INDICED_FACT, KARDESPED.KAP_INDICED_PED, 
                      KARDESPED.KAP_CANTDESC, 
	''PI_TIP_CAM''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'''')<>'''' then isnull(KARDESPEDPPS.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
	PEDEXPDET.PIB_INDICEB,
      factexp.pi_codigo AS  PI_CODIGOPEDEXP,
	''KAP_COS_UNI''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'''')<>'''' then round(isnull((KARDESPEDPPS.KAP_COSTOUNITACT / isnull(KARDESPEDPPS.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
	''PID_POR_DEF''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB=''N'' then 0 else PEDIMPDET.PID_POR_DEF end) end, 
	''KAP_DEF_TIP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
	KARDESPED.KAP_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         KARDESPEDPPS RIGHT OUTER JOIN
                      KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO LEFT OUTER JOIN
                      FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED LEFT OUTER JOIN
                      FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      PEDIMP RIGHT OUTER JOIN
                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO ON 
                      KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGA LEFT OUTER JOIN
                      PEDIMP PEDEXP ON FACTEXP.PI_CODIGO = PEDEXP.PI_CODIGO
WHERE     (KARDESPED.KAP_INDICED_PED IS NOT NULL) AND 
                ((case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB=''N'' then 0 else PEDIMPDET.PID_POR_DEF end) end) <> 0) AND (PEDEXP.PI_ESTATUS <> ''R'')
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
	AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
AND FACTEXP.PI_CODIGO=0'+@PI_CODIGO+' 
UNION
SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED.KAP_INDICED_FACT, KARDESPED.KAP_INDICED_PED, 
                      KARDESPED.KAP_CANTDESC, 
	''PI_TIP_CAM''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'''')<>'''' then isnull(KARDESPEDPPS.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
	PEDEXPDET.PIB_INDICEB, FACTEXP.PI_RECTIFICA AS PI_CODIGOPEDEXP,
	''KAP_COS_UNI''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'''')<>'''' then round(isnull((KARDESPEDPPS.KAP_COSTOUNITACT / isnull(KARDESPEDPPS.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
	''PID_POR_DEF''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB=''N'' then 0 else PEDIMPDET.PID_POR_DEF end) end,
	''KAP_DEF_TIP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
	KARDESPED.KAP_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         KARDESPEDPPS RIGHT OUTER JOIN
                      KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO LEFT OUTER JOIN
                      FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED LEFT OUTER JOIN
                      FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      PEDIMP RIGHT OUTER JOIN
                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO ON 
                      KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGAR1 LEFT OUTER JOIN
                      PEDIMP PEDEXP ON FACTEXP.PI_RECTIFICA = PEDEXP.PI_CODIGO                   
WHERE     (KARDESPED.KAP_INDICED_PED IS NOT NULL) AND 
                ((case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB=''N'' then 0 else PEDIMPDET.PID_POR_DEF end) end) <> 0) AND(FACTEXP.PI_RECTIFICA <> - 1)
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
	AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
AND FACTEXP.PI_RECTIFICA=0'+@PI_CODIGO) 


exec('exec sp_droptable ''VDATOSPEDEXPPAGOUSAxPedExp1'', ''V''')


EXEC('CREATE VIEW dbo.VDATOSPEDEXPPAGOUSAxPedExp1
with encryption as
SELECT     PEDIMPDET.PIB_INDICEB, FACTEXPDET.FED_INDICED, PEDIMPDET.AR_EXPFO, 
                      SUM(FACTEXPDET.FED_CANT * (FACTEXPDET.FED_GRA_MO + FACTEXPDET.FED_GRA_EMP + FACTEXPDET.FED_GRA_ADD + FACTEXPDET.FED_GRA_GI_MX
                       + FACTEXPDET.FED_GRA_MP + FACTEXPDET.FED_NG_MP + FACTEXPDET.FED_NG_ADD - FACTEXPDET.FED_NG_USA)) AS TOTALVALORUSA,
                      SUM(PEDIMP.PI_TIP_CAM *FACTEXPDET.FED_CANT * (FACTEXPDET.FED_GRA_MO + FACTEXPDET.FED_GRA_EMP + FACTEXPDET.FED_GRA_ADD + FACTEXPDET.FED_GRA_GI_MX
                       + FACTEXPDET.FED_GRA_MP + FACTEXPDET.FED_NG_MP + FACTEXPDET.FED_NG_ADD - FACTEXPDET.FED_NG_USA)) AS TOTALVALORUSAMN, 
		PEDIMPDETB.PIB_SECUENCIA, PEDIMPDET.PI_CODIGO, 
                      PEDIMPDETB.PIB_DESTNAFTA, FACTEXPDET.FED_RATEIMPFO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         FACTEXPDET INNER JOIN
                      PEDIMPDET ON FACTEXPDET.PID_INDICEDLIGA = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      PEDIMP ON PEDIMPDET.PI_CODIGO = PEDIMP.PI_CODIGO LEFT OUTER JOIN
                      PEDIMPDETB ON PEDIMPDET.PIB_INDICEB = PEDIMPDETB.PIB_INDICEB
WHERE PEDIMP.PI_ESTATUS <>''R''
AND PEDIMPDET.PI_CODIGO=0'+@PI_CODIGO+' 
GROUP BY PEDIMPDET.PIB_INDICEB, FACTEXPDET.FED_INDICED, PEDIMPDET.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, 
                      PEDIMPDET.PI_CODIGO, PEDIMPDETB.PIB_DESTNAFTA, FACTEXPDET.FED_RATEIMPFO, FACTEXPDET.MA_CODIGO
UNION
SELECT     PEDIMPDET.PIB_INDICEB, FACTEXPDET.FED_INDICED, PEDIMPDET.AR_EXPFO, 
                      SUM(FACTEXPDET.FED_CANT * (FACTEXPDET.FED_GRA_MO + FACTEXPDET.FED_GRA_EMP + FACTEXPDET.FED_GRA_ADD + FACTEXPDET.FED_GRA_GI_MX
                       + FACTEXPDET.FED_GRA_MP + FACTEXPDET.FED_NG_MP + FACTEXPDET.FED_NG_ADD - FACTEXPDET.FED_NG_USA)) AS TOTALVALORUSA, 
                      SUM(PEDIMP.PI_TIP_CAM *FACTEXPDET.FED_CANT * (FACTEXPDET.FED_GRA_MO + FACTEXPDET.FED_GRA_EMP + FACTEXPDET.FED_GRA_ADD + FACTEXPDET.FED_GRA_GI_MX
                       + FACTEXPDET.FED_GRA_MP + FACTEXPDET.FED_NG_MP + FACTEXPDET.FED_NG_ADD - FACTEXPDET.FED_NG_USA)) AS TOTALVALORUSAMN, 
		PEDIMPDETB.PIB_SECUENCIA, PEDIMPDET.PI_CODIGO, 
                      PEDIMPDETB.PIB_DESTNAFTA, FACTEXPDET.FED_RATEIMPFO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         FACTEXPDET INNER JOIN
                      PEDIMPDET ON FACTEXPDET.PID_INDICEDLIGAR1 = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      PEDIMP ON PEDIMPDET.PI_CODIGO = PEDIMP.PI_CODIGO LEFT OUTER JOIN
                      PEDIMPDETB ON PEDIMPDET.PIB_INDICEB = PEDIMPDETB.PIB_INDICEB
AND PEDIMPDET.PI_CODIGO=0'+@PI_CODIGO+' 
GROUP BY PEDIMPDET.PIB_INDICEB, FACTEXPDET.FED_INDICED, PEDIMPDET.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, 
                      PEDIMPDET.PI_CODIGO, PEDIMPDETB.PIB_DESTNAFTA, FACTEXPDET.FED_RATEIMPFO, FACTEXPDET.MA_CODIGO ')


exec('exec sp_droptable ''VDATOSPEDEXPPAGOMEXxPedExp'', ''V''')

EXEC('CREATE VIEW dbo.VDATOSPEDEXPPAGOMEXxPedExp
with encryption as
SELECT     PEDIMPDETB.PI_CODIGO, PEDIMPDETB.PIB_INDICEB, PEDIMPDETB.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, 
                      SUM(ISNULL(ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC, 0)) 
                      AS VALORMERCNOORIGUSD, SUM(ISNULL(ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC, 0)*VDATOSPEDEXPDESCxPedExp.PI_TIP_CAM) 
                      AS VALORMERCNOORIGMN, SUM((ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC) 
                      * (VDATOSPEDEXPDESCxPedExp.PID_POR_DEF / 100)) AS MONTOIGIMXUSD, 
	           SUM((ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC) 
                      * (VDATOSPEDEXPDESCxPedExp.PID_POR_DEF / 100)* VDATOSPEDEXPDESCxPedExp.PI_TIP_CAM) AS MONTOIGIMXMN,
		FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         FACTEXPDET INNER JOIN
                      FACTEXP ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO INNER JOIN
                      PEDIMPDETB ON FACTEXP.PI_CODIGO = PEDIMPDETB.PI_CODIGO INNER JOIN
                      PEDIMPDET PEDIMPDET_1 ON PEDIMPDETB.PIB_INDICEB = PEDIMPDET_1.PIB_INDICEB AND 
                      FACTEXPDET.PID_INDICEDLIGA = PEDIMPDET_1.PID_INDICED INNER JOIN
                      PEDIMP PEDIMP_2 ON PEDIMPDETB.PI_CODIGO = PEDIMP_2.PI_CODIGO INNER JOIN
                      VDATOSPEDEXPDESCxPedExp ON FACTEXPDET.FED_INDICED = VDATOSPEDEXPDESCxPedExp.KAP_INDICED_FACT
WHERE PEDIMP_2.PI_ESTATUS <>''R''
AND PEDIMPDETB.PI_CODIGO=0'+@PI_CODIGO+' 
GROUP BY PEDIMPDETB.PI_CODIGO, PEDIMPDETB.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, PEDIMPDETB.PIB_INDICEB, 
                      FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO
UNION
SELECT     PEDIMPDETB.PI_CODIGO, PEDIMPDETB.PIB_INDICEB, PEDIMPDETB.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, 
                      SUM(ISNULL(ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC, 0)) 
                      AS VALORMERCNOORIGUSD, SUM(ISNULL(ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC, 0)*VDATOSPEDEXPDESCxPedExp.PI_TIP_CAM) 
                      AS VALORMERCNOORIGMN, SUM((ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC) 
                      * (VDATOSPEDEXPDESCxPedExp.PID_POR_DEF / 100)) AS MONTOIGIMXUSD, 
	           SUM((ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC) 
                      * (VDATOSPEDEXPDESCxPedExp.PID_POR_DEF / 100)* VDATOSPEDEXPDESCxPedExp.PI_TIP_CAM) AS MONTOIGIMXMN,
		FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         FACTEXPDET INNER JOIN
                      FACTEXP ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO INNER JOIN
                      PEDIMPDETB ON FACTEXP.PI_RECTIFICA = PEDIMPDETB.PI_CODIGO INNER JOIN
                      PEDIMPDET PEDIMPDET_1 ON PEDIMPDETB.PIB_INDICEB = PEDIMPDET_1.PIB_INDICEB AND 
                      FACTEXPDET.PID_INDICEDLIGAR1 = PEDIMPDET_1.PID_INDICED INNER JOIN
                      PEDIMP PEDIMP_2 ON PEDIMPDETB.PI_CODIGO = PEDIMP_2.PI_CODIGO INNER JOIN
                      VDATOSPEDEXPDESCxPedExp ON FACTEXPDET.FED_INDICED = VDATOSPEDEXPDESCxPedExp.KAP_INDICED_FACT
WHERE PEDIMPDETB.PI_CODIGO=0'+@PI_CODIGO+' 
GROUP BY PEDIMPDETB.PI_CODIGO, PEDIMPDETB.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, PEDIMPDETB.PIB_INDICEB, 
                      FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO')


exec('exec sp_droptable ''VDATOSPEDEXPPAGOUSAxPedExp'', ''V''')

EXEC('CREATE VIEW dbo.VDATOSPEDEXPPAGOUSAxPedExp
with encryption as
SELECT     PIB_INDICEB, FED_INDICED, AR_EXPFO, TOTALVALORUSAMN * (case when (select cf_pagocontribucion from configuracion)=''J'' or PIB_DESTNAFTA=''N'' then 0 else FED_RATEIMPFO end)/100 as TOTALARANUSAMN, PIB_SECUENCIA, PI_CODIGO, PIB_DESTNAFTA, 
                    TOTALVALORUSA* (case when (select cf_pagocontribucion from configuracion)=''J'' or PIB_DESTNAFTA=''N'' then 0 else FED_RATEIMPFO end)/100 as TOTALARANUSA, TOTALVALORUSA AS TOTALVALORGRAVUSA, TOTALVALORUSAMN AS TOTALVALORGRAVMN,
	FED_RATEIMPFO=case when (select cf_pagocontribucion from configuracion)=''J'' or PIB_DESTNAFTA=''N'' then 0 else FED_RATEIMPFO end, MA_CODIGOFED
FROM         VDATOSPEDEXPPAGOUSAxPedExp1')





--Yolanda Avila
--2010-03-16
--Crear Nueva tabla temporal de KardespedPPS y Kardesped
/*exec('if exists (select * from dbo.sysobjects where id = object_id(N''[dbo].[InformacionBaseParaCalcularPagoArt303]'') and OBJECTPROPERTY(id, N''IsProcedure'') = 1)
drop procedure [dbo].[InformacionBaseParaCalcularPagoArt303]')

--aqui va

exec('create procedure [dbo].InformacionBaseParaCalcularPagoArt303 as
--Paso #1
if not exists (SELECT name FROM dbo.sysobjects WHERE dbo.sysobjects.name = N''KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303'')
begin
	--drop table KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303
	--select * from KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303
	select *
	into KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303
	from kardespedPPS
	where kap_codigo = (select max(kap_codigo) from kardespedPPS)
	
	print ''Parte 1''
	if not exists (SELECT dbo.syscolumns.name FROM dbo.syscolumns INNER JOIN dbo.sysobjects ON dbo.syscolumns.id = dbo.sysobjects.id
	WHERE (dbo.sysobjects.name = N''KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303'') AND (dbo.syscolumns.name = N''PedExp_codigo''))
	begin
        	ALTER TABLE [KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303] ADD [PedExp_codigo] [int] NULL 
	end 
	
	print ''Parte 2''
	truncate table KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303
	print ''Parte 3''
	
end 
else
begin
	delete from KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303 where PedExp_codigo =0'+@PI_CODIGO+' 
end

if not exists (SELECT name FROM dbo.sysobjects WHERE dbo.sysobjects.name = N''KARDESPED_InformacionBaseParaCalcularPagoArt303'')
begin
	--drop table KARDESPED_InformacionBaseParaCalcularPagoArt303
	--select * from KARDESPED_InformacionBaseParaCalcularPagoArt303
	select *
	into KARDESPED_InformacionBaseParaCalcularPagoArt303
	from kardesped
	where kap_codigo = (select max(kap_codigo) from kardesped)
	
	print ''Parte 1''
	if not exists (SELECT dbo.syscolumns.name FROM dbo.syscolumns INNER JOIN dbo.sysobjects ON dbo.syscolumns.id = dbo.sysobjects.id
	WHERE (dbo.sysobjects.name = N''KARDESPED_InformacionBaseParaCalcularPagoArt303'') AND (dbo.syscolumns.name = N''PedExp_codigo''))
	begin
	        ALTER TABLE [KARDESPED_InformacionBaseParaCalcularPagoArt303] ADD [PedExp_codigo] [int] NULL 
	end
	
	print ''Parte 2''
	truncate table KARDESPED_InformacionBaseParaCalcularPagoArt303
	print ''Parte 3''
end
else
begin
	delete from KARDESPED_InformacionBaseParaCalcularPagoArt303 where PedExp_codigo =0'+@PI_CODIGO+' 
end

 
if not exists (SELECT name FROM dbo.sysobjects WHERE dbo.sysobjects.name = N''PEDIMPDETB_InformacionBaseParaCalcularPagoArt303'')
begin
	--drop table PEDIMPDETB_InformacionBaseParaCalcularPagoArt303
	select *
	into PEDIMPDETB_InformacionBaseParaCalcularPagoArt303
	from PEDIMPDETB
	where pib_indiceb = (select max(pib_indiceb) from pedimpdetB)
	

	truncate table PEDIMPDETB_InformacionBaseParaCalcularPagoArt303
	
end
else
begin
	delete from PEDIMPDETB_InformacionBaseParaCalcularPagoArt303 where pi_codigo =0'+@PI_CODIGO+' 
end


 
--Paso #2
insert into KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303 (KAP_CODIGO,KAP_TASAFINAL,KAP_DEF_TIP,KAP_SECIMP,SPI_CODIGO,KAP_COSTOUNITACT,KAP_FT_ACT,KAP_PEDIMENTO,KAP_FECHAPED,KAP_TIP_CAM,KAP_SALDOAFECTADO, PedExp_codigo)
SELECT  KARDESPEDPPS.KAP_CODIGO,isnull(KARDESPEDPPS.KAP_TASAFINAL,-1),KARDESPEDPPS.KAP_DEF_TIP,KARDESPEDPPS.KAP_SECIMP,KARDESPEDPPS.SPI_CODIGO,KARDESPEDPPS.KAP_COSTOUNITACT,
	KARDESPEDPPS.KAP_FT_ACT,KARDESPEDPPS.KAP_PEDIMENTO,KARDESPEDPPS.KAP_FECHAPED,isnull(KARDESPEDPPS.KAP_TIP_CAM,1),isnull(KARDESPEDPPS.KAP_SALDOAFECTADO,''N''),0'+@PI_CODIGO+'
FROM KARDESPEDPPS 
RIGHT OUTER JOIN KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO 
LEFT OUTER JOIN FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED 
LEFT OUTER JOIN FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO 
LEFT OUTER JOIN PEDIMP 
RIGHT OUTER JOIN PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO 
	ON KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED 
LEFT OUTER JOIN PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGA 
LEFT OUTER JOIN PEDIMP PEDEXP ON FACTEXP.PI_CODIGO = PEDEXP.PI_CODIGO
WHERE (KARDESPED.KAP_INDICED_PED IS NOT NULL) AND (PEDEXP.PI_ESTATUS <> ''R'')
AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
and not(KARDESPEDPPS.kap_codigo is null)
AND FACTEXP.PI_CODIGO=0'+@PI_CODIGO+' 
UNION
SELECT  KARDESPEDPPS.KAP_CODIGO,isnull(KARDESPEDPPS.KAP_TASAFINAL,-1),KARDESPEDPPS.KAP_DEF_TIP,KARDESPEDPPS.KAP_SECIMP,KARDESPEDPPS.SPI_CODIGO,KARDESPEDPPS.KAP_COSTOUNITACT,
	KARDESPEDPPS.KAP_FT_ACT,KARDESPEDPPS.KAP_PEDIMENTO,KARDESPEDPPS.KAP_FECHAPED,isnull(KARDESPEDPPS.KAP_TIP_CAM,1),isnull(KARDESPEDPPS.KAP_SALDOAFECTADO,''N''),0'+@PI_CODIGO+'
FROM KARDESPEDPPS 
RIGHT OUTER JOIN KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO 
LEFT OUTER JOIN FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED 
LEFT OUTER JOIN FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO 
LEFT OUTER JOIN PEDIMP 
RIGHT OUTER JOIN PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO 
	ON KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED 
LEFT OUTER JOIN PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGAR1 
LEFT OUTER JOIN PEDIMP PEDEXP ON FACTEXP.PI_RECTIFICA = PEDEXP.PI_CODIGO                   
WHERE (KARDESPED.KAP_INDICED_PED IS NOT NULL) 
AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
and not(KARDESPEDPPS.kap_codigo is null)
AND FACTEXP.PI_RECTIFICA=0'+@PI_CODIGO+'



--Paso #3
insert into KARDESPED_InformacionBaseParaCalcularPagoArt303 (KAP_CODIGO,KAP_FACTRANS,KAP_INDICED_FACT,KAP_INDICED_PED,MA_HIJO,KAP_ESTATUS,KAP_CANTDESC,
		KAP_CantTotADescargar,KAP_Saldo_FED,KAP_PADRESUST,KAP_CONTESTATUS,KAP_Tipo_Desc,KAP_FisComp,KAP_PadreMain, PedExp_codigo)
SELECT KARDESPED.KAP_CODIGO, KARDESPED.KAP_FACTRANS, KARDESPED.KAP_INDICED_FACT, KARDESPED.KAP_INDICED_PED, KARDESPED.MA_HIJO, KARDESPED.KAP_ESTATUS, KARDESPED.KAP_CANTDESC,
		KARDESPED.KAP_CantTotADescargar, KARDESPED.KAP_Saldo_FED, KARDESPED.KAP_PADRESUST, KARDESPED.KAP_CONTESTATUS, KARDESPED.KAP_Tipo_Desc,
		KARDESPED.KAP_FisComp, KARDESPED.KAP_PadreMain,0'+@PI_CODIGO+' as PedExp_codigo
FROM KARDESPEDPPS 
RIGHT OUTER JOIN KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO 
LEFT OUTER JOIN FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED 
LEFT OUTER JOIN FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO 
LEFT OUTER JOIN PEDIMP 
RIGHT OUTER JOIN PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO 
	ON KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED 
LEFT OUTER JOIN PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGA 
LEFT OUTER JOIN PEDIMP PEDEXP ON FACTEXP.PI_CODIGO = PEDEXP.PI_CODIGO
WHERE (KARDESPED.KAP_INDICED_PED IS NOT NULL) AND (PEDEXP.PI_ESTATUS <> ''R'')
AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
and not(KARDESPED.kap_codigo is null)
AND FACTEXP.PI_CODIGO=0'+@PI_CODIGO+'

UNION
SELECT KARDESPED.KAP_CODIGO, KARDESPED.KAP_FACTRANS, KARDESPED.KAP_INDICED_FACT, KARDESPED.KAP_INDICED_PED, KARDESPED.MA_HIJO, KARDESPED.KAP_ESTATUS, KARDESPED.KAP_CANTDESC,
		KARDESPED.KAP_CantTotADescargar, KARDESPED.KAP_Saldo_FED, KARDESPED.KAP_PADRESUST, KARDESPED.KAP_CONTESTATUS, KARDESPED.KAP_Tipo_Desc,
		KARDESPED.KAP_FisComp, KARDESPED.KAP_PadreMain,0'+@PI_CODIGO+' as PedExp_codigo
FROM KARDESPEDPPS 
RIGHT OUTER JOIN KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO 
LEFT OUTER JOIN FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED 
LEFT OUTER JOIN FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO 
LEFT OUTER JOIN PEDIMP 
RIGHT OUTER JOIN PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO 
	ON KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED 
LEFT OUTER JOIN PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGAR1 
LEFT OUTER JOIN PEDIMP PEDEXP ON FACTEXP.PI_RECTIFICA = PEDEXP.PI_CODIGO                   
WHERE (KARDESPED.KAP_INDICED_PED IS NOT NULL) 
AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
and not(KARDESPED.kap_codigo is null)
AND FACTEXP.PI_RECTIFICA=0'+@PI_CODIGO+'


--Paso #4
set identity_insert PEDIMPDETB_InformacionBaseParaCalcularPagoArt303 on
insert into PEDIMPDETB_InformacionBaseParaCalcularPagoArt303 (PIB_INDICEB,PI_CODIGO,PIB_COS_UNIGEN,PIB_COS_UNIGRA,PIB_COS_UNIVA,
		PIB_CANT,PIB_CAN_AR,PIB_CAN_GEN,PIB_VAL_FAC,
		PIB_VAL_ADU,PIB_VAL_US,PIB_ESTADO,AR_IMPMX,PIB_POR_DEF,ME_ARIMPMX,MA_GENERICO,ME_GENERICO,PA_ORIGEN,PA_PROCEDE,
		ES_ORIGEN,ES_DESTINO,ES_COMPRADOR,ES_VENDEDOR,PIB_SECUENCIA,AR_EXPFO,PIB_RATEEXPFO,EQ_EXPFO,PIB_VALORMCIANOORIG,
		PIB_ADVMNIMPUSA,PIB_ADVMNIMPMEX,PIB_ADVUSDIMPMEX,PIB_EXCENCION,PIB_IMPORTECONTRSINRECARGOS,PIB_IMPORTECONTR,
		PIB_IMPORTECONTRUSD,PIB_IMPORTERECARGOS,PIB_DESTNAFTA,PIB_NOMBRE,PIB_PAGACONTRIB,PIB_DEF_TIP,PIB_SEC_IMP,
		SPI_CODIGO,PIB_CODIGOFACT,PIB_OBSERVA,PIB_VAL_RET,PIB_GENERA_EMPDET,PIB_SERVICIO)
select  PIB_INDICEB,PI_CODIGO,PIB_COS_UNIGEN,PIB_COS_UNIGRA,PIB_COS_UNIVA,PIB_CANT,PIB_CAN_AR,PIB_CAN_GEN,PIB_VAL_FAC,
	PIB_VAL_ADU,PIB_VAL_US,PIB_ESTADO,AR_IMPMX,PIB_POR_DEF,ME_ARIMPMX,MA_GENERICO,ME_GENERICO,PA_ORIGEN,PA_PROCEDE,
	ES_ORIGEN,ES_DESTINO,ES_COMPRADOR,ES_VENDEDOR,PIB_SECUENCIA,AR_EXPFO,PIB_RATEEXPFO,EQ_EXPFO,PIB_VALORMCIANOORIG,
	PIB_ADVMNIMPUSA,PIB_ADVMNIMPMEX,PIB_ADVUSDIMPMEX,PIB_EXCENCION,PIB_IMPORTECONTRSINRECARGOS,PIB_IMPORTECONTR,
	PIB_IMPORTECONTRUSD,PIB_IMPORTERECARGOS,PIB_DESTNAFTA,PIB_NOMBRE,PIB_PAGACONTRIB,PIB_DEF_TIP,PIB_SEC_IMP,
	SPI_CODIGO,PIB_CODIGOFACT,PIB_OBSERVA,PIB_VAL_RET,PIB_GENERA_EMPDET,PIB_SERVICIO
from pedimpdetb 
where pib_indiceb in (
	SELECT  PEDEXPDET.pib_indiceb
	FROM KARDESPEDPPS 
	RIGHT OUTER JOIN KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO 
	LEFT OUTER JOIN FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED 
	LEFT OUTER JOIN FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO 
	LEFT OUTER JOIN PEDIMP 
	RIGHT OUTER JOIN PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO 
		ON KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED 
	LEFT OUTER JOIN PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGA 
	LEFT OUTER JOIN PEDIMP PEDEXP ON FACTEXP.PI_CODIGO = PEDEXP.PI_CODIGO
	WHERE (KARDESPED.KAP_INDICED_PED IS NOT NULL) AND (PEDEXP.PI_ESTATUS <> ''R'')
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
	AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
	AND FACTEXP.PI_CODIGO=0'+@PI_CODIGO+'
	UNION
	SELECT PEDEXPDET.pib_indiceb
	FROM KARDESPEDPPS 
	RIGHT OUTER JOIN KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO 
	LEFT OUTER JOIN FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED 
	LEFT OUTER JOIN FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO 
	LEFT OUTER JOIN PEDIMP 
	RIGHT OUTER JOIN PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO 
		ON KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED 
	LEFT OUTER JOIN PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGAR1 
	LEFT OUTER JOIN PEDIMP PEDEXP ON FACTEXP.PI_RECTIFICA = PEDEXP.PI_CODIGO                   
	WHERE (KARDESPED.KAP_INDICED_PED IS NOT NULL) 
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
	AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
	AND FACTEXP.PI_RECTIFICA=0'+@PI_CODIGO+' )
set identity_insert PEDIMPDETB_InformacionBaseParaCalcularPagoArt303 off'
)
*/
--=================================
if @CrearTablas = 'S'
 exec InformacionBaseParaCalcularPagoArt303 @PICODIGO


--=================================


exec('exec sp_droptable ''VDATOSPEDEXPDESCxPedExpT'', ''V''')
/*Se Comento esta parte ya que si se modifica la información de KARDESPED no había forma de hacer referencia a los datos que respaldaban el cálculo del Art303*/

exec('CREATE VIEW dbo.VDATOSPEDEXPDESCxPedExpT
with encryption as
SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED.KAP_INDICED_FACT, KARDESPED.KAP_INDICED_PED, 
                      KARDESPED.KAP_CANTDESC, 
	''PI_TIP_CAM''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'''')<>'''' then isnull(KARDESPEDPPS.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
	PEDEXPDET.PIB_INDICEB,
      factexp.pi_codigo AS  PI_CODIGOPEDEXP,
	''KAP_COS_UNI''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'''')<>'''' then round(isnull((KARDESPEDPPS.KAP_COSTOUNITACT / isnull(KARDESPEDPPS.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
	''PID_POR_DEF''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB=''N'' then 0 else PEDIMPDET.PID_POR_DEF end) end, 
	''KAP_DEF_TIP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
	KARDESPED.KAP_CODIGO, ''KAP_SECIMP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.KAP_SECIMP else PEDIMPDET.PID_SEC_IMP end, 
	''SPI_CODIGO''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.SPI_CODIGO else PEDIMPDET.SPI_CODIGO end,
	PEDIMPDET.PA_ORIGEN, PEDIMPDET.AR_IMPMX, PEDIMPDET.PID_PAGACONTRIB, PEDIMPDET.PID_NOMBRE,
	PEDIMPDET.PID_NOPARTE, PEDIMPDET.MA_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         KARDESPEDPPS RIGHT OUTER JOIN
                      KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO LEFT OUTER JOIN
                      FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED LEFT OUTER JOIN
                      FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      PEDIMP RIGHT OUTER JOIN
                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO ON 
                      KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGA LEFT OUTER JOIN
                      PEDIMP PEDEXP ON FACTEXP.PI_CODIGO = PEDEXP.PI_CODIGO
WHERE     (KARDESPED.KAP_INDICED_PED IS NOT NULL) AND (PEDEXP.PI_ESTATUS <> ''R'')
AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
AND FACTEXP.PI_CODIGO=0'+@PI_CODIGO+' 
UNION
SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED.KAP_INDICED_FACT, KARDESPED.KAP_INDICED_PED, 
                      KARDESPED.KAP_CANTDESC, 
	''PI_TIP_CAM''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'''')<>'''' then isnull(KARDESPEDPPS.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
	PEDEXPDET.PIB_INDICEB, FACTEXP.PI_RECTIFICA AS PI_CODIGOPEDEXP,
	''KAP_COS_UNI''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'''')<>'''' then round(isnull((KARDESPEDPPS.KAP_COSTOUNITACT / isnull(KARDESPEDPPS.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
	''PID_POR_DEF''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB=''N'' then 0 else PEDIMPDET.PID_POR_DEF end) end,
	''KAP_DEF_TIP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
	KARDESPED.KAP_CODIGO, ''KAP_SECIMP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.KAP_SECIMP else PEDIMPDET.PID_SEC_IMP end, 
	''SPI_CODIGO''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.SPI_CODIGO else PEDIMPDET.SPI_CODIGO end,
	PEDIMPDET.PA_ORIGEN, PEDIMPDET.AR_IMPMX, PEDIMPDET.PID_PAGACONTRIB, PEDIMPDET.PID_NOMBRE,
	PEDIMPDET.PID_NOPARTE, PEDIMPDET.MA_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         KARDESPEDPPS RIGHT OUTER JOIN
                      KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO LEFT OUTER JOIN
                      FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED LEFT OUTER JOIN
                      FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      PEDIMP RIGHT OUTER JOIN
                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO ON 
                      KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGAR1 LEFT OUTER JOIN
                      PEDIMP PEDEXP ON FACTEXP.PI_RECTIFICA = PEDEXP.PI_CODIGO                   
WHERE     (KARDESPED.KAP_INDICED_PED IS NOT NULL) 
AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
AND FACTEXP.PI_RECTIFICA=0'+@PI_CODIGO)


if @CrearTablas = 'S' 
begin
	exec('exec sp_droptable ''VDATOSPEDEXPDESCxPedExpT_InfBaseCalculoPagoArt303'', ''V''')


	exec('
	CREATE VIEW dbo.VDATOSPEDEXPDESCxPedExpT_InfBaseCalculoPagoArt303
	with encryption as
	SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_FACT, KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED, 
	                      KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CANTDESC, 
		''PI_TIP_CAM''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_PEDIMENTO,'''')<>'''' then isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
		PEDEXPDET.PIB_INDICEB,
	      factexp.pi_codigo AS  PI_CODIGOPEDEXP,
		''KAP_COS_UNI''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_PEDIMENTO,'''')<>'''' then round(isnull((KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_COSTOUNITACT / isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
		''PID_POR_DEF''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL else
		(case when PEDIMPDET.PID_PAGACONTRIB=''N'' then 0 else PEDIMPDET.PID_POR_DEF end) end, 
		''KAP_DEF_TIP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
		KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO, ''KAP_SECIMP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_SECIMP else PEDIMPDET.PID_SEC_IMP end, 
		''SPI_CODIGO''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.SPI_CODIGO else PEDIMPDET.SPI_CODIGO end,
		PEDIMPDET.PA_ORIGEN, PEDIMPDET.AR_IMPMX, PEDIMPDET.PID_PAGACONTRIB, PEDIMPDET.PID_NOMBRE,
		PEDIMPDET.PID_NOPARTE, PEDIMPDET.MA_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
	FROM         KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303 RIGHT OUTER JOIN
	                      KARDESPED_InformacionBaseParaCalcularPagoArt303 ON KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO = KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO LEFT OUTER JOIN
	                      FACTEXPDET_InformacionBaseParaCalcularPagoArt303 factexpdet ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED LEFT OUTER JOIN
	                      FACTEXP ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_FACTRANS = FACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      PEDIMP RIGHT OUTER JOIN
	                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO ON 
	                      KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
	                      pedexpdet_InformacionBaseParaCalcularPagoArt303 /*PEDIMPDET*/ PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGA LEFT OUTER JOIN
	                      PEDIMP PEDEXP ON FACTEXP.PI_CODIGO = PEDEXP.PI_CODIGO
	WHERE     (KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED IS NOT NULL) AND (PEDEXP.PI_ESTATUS <> ''R'')
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
	AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
	AND FACTEXP.PI_CODIGO=0'+@PI_CODIGO+' 
	UNION
	SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_FACT, KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED, 
	                      KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CANTDESC, 
		''PI_TIP_CAM''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_PEDIMENTO,'''')<>'''' then isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
		PEDEXPDET.PIB_INDICEB, FACTEXP.PI_RECTIFICA AS PI_CODIGOPEDEXP,
		''KAP_COS_UNI''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_PEDIMENTO,'''')<>'''' then round(isnull((KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_COSTOUNITACT / isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
		''PID_POR_DEF''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL else
		(case when PEDIMPDET.PID_PAGACONTRIB=''N'' then 0 else PEDIMPDET.PID_POR_DEF end) end,
		''KAP_DEF_TIP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
		KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO, ''KAP_SECIMP''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_SECIMP else PEDIMPDET.PID_SEC_IMP end, 
		''SPI_CODIGO''=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)=''S''  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.SPI_CODIGO else PEDIMPDET.SPI_CODIGO end,
		PEDIMPDET.PA_ORIGEN, PEDIMPDET.AR_IMPMX, PEDIMPDET.PID_PAGACONTRIB, PEDIMPDET.PID_NOMBRE,
		PEDIMPDET.PID_NOPARTE, PEDIMPDET.MA_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
	FROM KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303 
	RIGHT OUTER JOIN KARDESPED_InformacionBaseParaCalcularPagoArt303 ON KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO = KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO 
	LEFT OUTER JOIN FACTEXPDET_InformacionBaseParaCalcularPagoArt303 FACTEXPDET ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED 
	LEFT OUTER JOIN FACTEXP ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_FACTRANS = FACTEXP.FE_CODIGO 
	LEFT OUTER JOIN PEDIMP 
	RIGHT OUTER JOIN PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO 
		ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED = PEDIMPDET.PID_INDICED 
	LEFT OUTER JOIN pedexpdet_InformacionBaseParaCalcularPagoArt303 /*PEDIMPDET*/ PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGAR1 
	LEFT OUTER JOIN PEDIMP PEDEXP ON FACTEXP.PI_RECTIFICA = PEDEXP.PI_CODIGO                   
	WHERE     (KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED IS NOT NULL) 
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN (''IT'', ''IM'', ''RE'', ''IV'', ''VT'', ''ED'', ''TS''))
	AND FACTEXPDET.FED_RETRABAJO<>''R'' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO=''D'')
	AND FACTEXP.PI_RECTIFICA=0'+@PI_CODIGO)
	
end



GO
