SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_DESCONGELASUB] (@FI_CODIGO INT, @USER INT)   as

DECLARE @FID_INDICED INT, @MA_CODIGO INT, @BST_ENTRAVIGOR DATETIME, @FID_CANT decimal(38,6), @CFT_TIPO VARCHAR(5)

UPDATE CONFIGURACION
SET CF_DESCARGANDO='S'


DELETE FROM IMPORTLOG WHERE IML_CBFORMA=-44

	/* =========== SE EXPLOSIONA LA FACTURA DE IMPORTACION ============*/
	DELETE FROM BOM_DESCTEMP WHERE FE_CODIGO=@FI_CODIGO

	select @BST_ENTRAVIGOR=convert(varchar(11),getdate(),101)


		insert into bom_desctemp (fe_codigo, bst_pt, bst_hijo, fed_cant, bst_disch, ti_codigo,
		me_codigo, factconv, me_gen, bst_incorpor, fed_indiced, bst_nivel, ma_tip_ens, bst_entravigor, bst_perini, bst_perfin,
		bst_tipodesc, bst_pertenece, bst_tipocosto)

		SELECT     @FI_CODIGO, dbo.FACTIMPDET.MA_CODIGO, dbo.FACTIMPDET.MA_CODIGO, SUM(dbo.FACTIMPDET.FID_CANT_ST) AS FID_CANT, 
			  'S', dbo.CONFIGURATIPO.CFT_TIPO, dbo.FACTIMPDET.ME_CODIGO, dbo.FACTIMPDET.EQ_GEN, 
			ISNULL(dbo.MAESTRO.ME_COM, 19), 1, dbo.FACTIMPDET.FID_INDICED, 'MP', 'C', dbo.FACTIMPDET.FID_FECHA_STRUCT,
			dbo.FACTIMPDET.FID_FECHA_STRUCT, dbo.FACTIMPDET.FID_FECHA_STRUCT, 'N', dbo.FACTIMPDET.MA_CODIGO, 'S'			
		FROM         dbo.FACTIMPDET LEFT OUTER JOIN
		                      dbo.MAESTRO MAESTRO_1 ON dbo.FACTIMPDET.MA_CODIGO = MAESTRO_1.MA_CODIGO LEFT OUTER JOIN
		                      dbo.MAESTRO ON dbo.FACTIMPDET.MA_GENERICO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
		                      dbo.CONFIGURATIPO ON dbo.FACTIMPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
		WHERE (dbo.FACTIMPDET.FI_CODIGO = @FI_CODIGO) AND dbo.CONFIGURATIPO.CFT_TIPO NOT IN ('P','S')
		GROUP BY dbo.CONFIGURATIPO.CFT_TIPO, dbo.FACTIMPDET.MA_CODIGO, dbo.FACTIMPDET.ME_CODIGO, dbo.FACTIMPDET.EQ_GEN, 
		                     dbo.MAESTRO.ME_COM, dbo.FACTIMPDET.FID_INDICED, dbo.FACTIMPDET.FID_FECHA_STRUCT
		HAVING      (SUM(dbo.FACTIMPDET.FID_CANT_ST) > 0) 


	DECLARE cur_Descongela CURSOR FOR
		SELECT   FID_INDICED, MA_CODIGO, FID_CANT_ST, @CFT_TIPO
		FROM FACTIMPDET LEFT OUTER JOIN CONFIGURATIPO ON
		FACTIMPDET.TI_CODIGO=CONFIGURATIPO.TI_CODIGO
		WHERE FI_CODIGO=@FI_CODIGO AND dbo.CONFIGURATIPO.CFT_TIPO IN ('P','S')
	open cur_Descongela
		FETCH NEXT FROM cur_Descongela INTO @FID_INDICED, @MA_CODIGO, @FID_CANT, @CFT_TIPO
		WHILE (@@FETCH_STATUS = 0) 
		BEGIN


		EXEC SP_FILL_BOM_DESCTEMP @FID_INDICED, @MA_CODIGO, @BST_ENTRAVIGOR, @FID_CANT, @FI_CODIGO	
		

		FETCH NEXT FROM cur_Descongela INTO @FID_INDICED, @MA_CODIGO, @FID_CANT, @CFT_TIPO
	
	END
	
	CLOSE cur_Descongela
	DEALLOCATE cur_Descongela



	exec SP_DESCONGELASUB1 @FI_CODIGO, @USER



























GO
