SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO







































CREATE PROCEDURE [dbo].[SP_FILLPAISARAUS] @arcodigo int    as

SET NOCOUNT ON 
--US se refiere al pais de origen del arancel

EXEC SP_DROPTABLE 'PAISARATEMP'
CREATE TABLE [dbo].[PAISARATEMP] (AR_CODIGO INT,
				PA_CODIGO INT,
				SPI_CODIGO SMALLINT)

INSERT INTO PAISARATEMP(AR_CODIGO, PA_CODIGO, SPI_CODIGO)
--pais de origen <> mexico
SELECT ARANCEL.AR_CODIGO, MAESTRO.PA_ORIGEN, PAIS.SPI_CODIGO
FROM CONFIGURACION INNER JOIN PAIS ON 
    CONFIGURACION.CF_PAIS_MX <> PAIS.PA_CODIGO RIGHT OUTER
     JOIN MAESTRO ON PAIS.PA_CODIGO = MAESTRO.PA_ORIGEN RIGHT OUTER JOIN
    ARANCEL ON MAESTRO.AR_IMPFO = ARANCEL.AR_CODIGO
WHERE PAIS.SPI_CODIGO IS NOT NULL
GROUP BY MAESTRO.PA_ORIGEN, ARANCEL.AR_CODIGO, 
   PAIS.SPI_CODIGO
HAVING (MAESTRO.PA_ORIGEN IS NOT NULL) AND PAIS.SPI_CODIGO IS NOT NULL AND
    (ARANCEL.AR_CODIGO = @arcodigo) 

UNION
--pais de origen mx
SELECT ARANCEL.AR_CODIGO, MAESTRO.PA_ORIGEN, SPI.SPI_CODIGO
FROM CONFIGURACION INNER JOIN PAIS ON 
    CONFIGURACION.CF_PAIS_MX = PAIS.PA_CODIGO LEFT OUTER
     JOIN SPI ON PAIS.PA_CORTO = SPI.SPI_TIPO RIGHT OUTER JOIN
    MAESTRO ON PAIS.PA_CODIGO = MAESTRO.PA_ORIGEN RIGHT OUTER JOIN
    ARANCEL ON MAESTRO.AR_IMPFO = ARANCEL.AR_CODIGO
GROUP BY MAESTRO.PA_ORIGEN, ARANCEL.AR_CODIGO, 
    SPI.SPI_CODIGO
HAVING (MAESTRO.PA_ORIGEN IS NOT NULL) AND SPI.SPI_CODIGO IS NOT NULL AND 
    (ARANCEL.AR_CODIGO = @arcodigo)


	INSERT INTO PAISARA(AR_CODIGO, PA_CODIGO, SPI_CODIGO, PAR_BEN)
	SELECT AR_CODIGO, PA_CODIGO, SPI_CODIGO, -1
	FROM PAISARATEMP
	GROUP BY AR_CODIGO, PA_CODIGO, SPI_CODIGO


EXEC SP_DROPTABLE 'PAISARATEMP'






































GO
