SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[ultima descarga]
AS
SELECT     TOP 100 PERCENT MA_HIJO, KAP_FACTRANS
FROM         dbo.KARDESPED
WHERE     (KAP_CANTDESC > 0)
ORDER BY MA_HIJO
GO
