SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[Saldo Por pedimento]
AS
SELECT     TOP 100 PERCENT dbo.PEDIMP.PI_FOLIO, dbo.PEDIMP.PI_FEC_ENT, dbo.PEDIMPDET.PID_NOPARTE, dbo.PEDIMPDET.PID_NOMBRE, 
                      SUM(dbo.PIDescarga.PID_SALDOGEN) AS SALDOGEN, dbo.PEDIMP.PI_TIPO, dbo.PEDIMPDET.PID_IMPRIMIR
FROM         dbo.PIDescarga INNER JOIN
                      dbo.PEDIMPDET ON dbo.PIDescarga.PID_INDICED = dbo.PEDIMPDET.PID_INDICED INNER JOIN
                      dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO
WHERE     (dbo.PEDIMPDET.TI_CODIGO IN (10, 16, 14, 5)) AND (dbo.PEDIMP.PI_MOVIMIENTO = 'E') AND (dbo.PIDescarga.PI_RECTIFICADO = 'N')
GROUP BY dbo.PEDIMP.PI_FEC_ENT, dbo.PEDIMPDET.PID_NOPARTE, dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMP.PI_FOLIO, dbo.PEDIMP.PI_TIPO, 
                      dbo.PEDIMPDET.PID_IMPRIMIR
HAVING      (SUM(dbo.PIDescarga.PID_SALDOGEN) > 0) AND (dbo.PEDIMPDET.PID_IMPRIMIR = 'S')
ORDER BY dbo.PEDIMP.PI_FEC_ENT, dbo.PEDIMPDET.PID_NOMBRE
GO
