SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VKARPENDIENTE8304 
as	
SELECT    KAP_CODIGO, KAP_FACTRANS, KAP_INDICED_FACT, KAP_INDICED_PED, MA_HIJO, KAP_ESTATUS, KAP_CANTDESC, 
                      KAP_CantTotADescargar, KAP_Saldo_FED, KAP_PADRESUST, KAP_CONTESTATUS
FROM         KARDESPED
WHERE KAP_FACTRANS=08304 AND
               KAP_SALDO_FED > 0 AND ((KAP_ESTATUS = 'N' OR KAP_ESTATUS = 'B') OR
(KAP_ESTATUS = 'P'
and KAP_CODIGO in (SELECT MAX(KARDESPED1.KAP_CODIGO) FROM KARDESPED KARDESPED1 WHERE KARDESPED1.KAP_INDICED_FACT = KARDESPED.KAP_INDICED_FACT
		    and KARDESPED1.KAP_CantTotADescargar=KARDESPED.KAP_CantTotADescargar
		   GROUP BY CASE WHEN KARDESPED1.KAP_PADRESUST=0 THEN KARDESPED1.MA_HIJO ELSE KARDESPED1.KAP_PADRESUST END)))
GO
