SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VPIDescargaSub
			AS SELECT  TOP 100 PERCENT PID_INDICED, round(ISNULL(PID_CONGELASUBMAQ,0),6) AS PID_SALDOGEN, PIDescarga.MA_CODIGO, pid_fechavence, PI_CODIGO
			FROM         dbo.PIDescarga 
			WHERE     (PI_ACTIVOFIJO = 'N') 
			AND round(PIDescarga.PID_CONGELASUBMAQ,6) > 0 AND PI_FEC_ENT<='07/27/2007' and PIDescarga.pid_fechavence>='07/27/2007'
GO
