SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[revisar saldos]
AS
SELECT     TOP 100 PERCENT dbo.KARDESPED.KAP_INDICED_PED, dbo.PIDescarga.PID_INDICED, dbo.KARDESPED.MA_HIJO, dbo.PIDescarga.pid_fechavence, 
                      dbo.PIDescarga.PID_SALDOGEN, dbo.KARDESPED.KAP_CANTDESC, dbo.KARDESPED.KAP_CantTotADescargar, dbo.PEDIMP.PI_FOLIO, 
                      dbo.PEDIMPDET.PID_CAN_GEN, dbo.PEDIMPDET.PID_NOPARTE, dbo.FACTEXP.FE_FOLIO, dbo.FACTEXP.FE_FECHA, 
                      dbo.KARDESPED.KAP_PADRESUST
FROM         dbo.FACTEXP RIGHT OUTER JOIN
                      dbo.KARDESPED ON dbo.FACTEXP.FE_CODIGO = dbo.KARDESPED.KAP_FACTRANS LEFT OUTER JOIN
                      dbo.PEDIMPDET INNER JOIN
                      dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO RIGHT OUTER JOIN
                      dbo.PIDescarga ON dbo.PEDIMPDET.PID_INDICED = dbo.PIDescarga.PID_INDICED AND dbo.PEDIMP.PI_CODIGO = dbo.PIDescarga.PI_CODIGO ON 
                      dbo.KARDESPED.KAP_INDICED_PED = dbo.PIDescarga.PID_INDICED
WHERE     (dbo.KARDESPED.MA_HIJO = 3327)
ORDER BY dbo.FACTEXP.FE_FECHA DESC, dbo.FACTEXP.FE_FOLIO DESC
GO
