SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VDUTIABLEKITS
AS
SELECT     TOP 100 PERCENT MA_CODIGO, AR_CODIGO, BA_TIPOCOSTO, BA_COSTO
FROM         dbo.BOM_ARANCEL
WHERE     (AR_CODIGO = 421)
GO
