SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO











CREATE VIEW dbo.VInvFisInTrade
	as
	SELECT PEDIMPDET.PID_NOPARTE, MAX(PEDIMPDET.PID_NOMBRE) PID_NOMBRE, ROUND(SUM(PIDescarga.PID_SALDOGEN / PEDIMPDET.EQ_GENERICO), 6) as CantidadSaldoInTrade, 
	      ROUND(SUM(PEDIMPDET.PID_CAN_GEN / PEDIMPDET.EQ_GENERICO), 6) as CantidadOrigInTrade, 
	      SUM(PEDIMPDET.PID_CTOT_DLS) as ValorOrigInTrade, 
	       MAX(MEDIDA.ME_CORTO) AS UMInTrade, SUM(PIDescarga.PID_SALDOGEN * PEDIMPDET.PID_COS_UNIGEN) as ValorSaldoInTrade, MAX(PIDescarga.PI_FEC_ENT) FechaEntradaInTrade,
	      MAX(ARANCEL.AR_FRACCION) AS FArancelariaInTrade
	FROM   PIDescarga INNER JOIN PEDIMP ON PIDescarga.PI_CODIGO = PEDIMP.PI_CODIGO INNER JOIN 
	       PEDIMPDET ON PIDescarga.PID_INDICED = PEDIMPDET.PID_INDICED INNER JOIN 
	       MEDIDA ON PEDIMPDET.ME_CODIGO = MEDIDA.ME_CODIGO LEFT OUTER JOIN ARANCEL
                    ON PEDIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO  
	WHERE (PEDIMP.PI_ESTATUS <> 'R') AND (PIDescarga.PI_ACTIVOFIJO = 'N') AND 
	      (PIDescarga.PI_FEC_ENT <='01/11/2007') AND (PIDescarga.PID_SALDOGEN > 0) 
	GROUP BY PEDIMPDET.PID_NOPARTE
GO
