SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[estructuras duplicadas en fechas]
AS
SELECT     TOP 100 PERCENT dbo.BOM_STRUCT.BSU_NOPARTE, dbo.BOM_STRUCT.BST_NOPARTE, dbo.BOM_STRUCT.FACTCONV, 
                      dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, BOM_STRUCT_1.BST_PERINI AS PERINI, 
                      BOM_STRUCT_1.BST_PERFIN AS PERFIN
FROM         dbo.BOM_STRUCT INNER JOIN
                      dbo.BOM_STRUCT BOM_STRUCT_1 ON dbo.BOM_STRUCT.BST_HIJO = BOM_STRUCT_1.BST_HIJO AND 
                      dbo.BOM_STRUCT.BST_PERINI > BOM_STRUCT_1.BST_PERINI AND dbo.BOM_STRUCT.BST_PERINI < BOM_STRUCT_1.BST_PERFIN AND 
                      dbo.BOM_STRUCT.BSU_SUBENSAMBLE = BOM_STRUCT_1.BSU_SUBENSAMBLE
GROUP BY dbo.BOM_STRUCT.BSU_NOPARTE, dbo.BOM_STRUCT.BST_NOPARTE, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
                      dbo.BOM_STRUCT.BST_PERFIN, BOM_STRUCT_1.BST_PERINI, BOM_STRUCT_1.BST_PERFIN
ORDER BY dbo.BOM_STRUCT.BST_NOPARTE, dbo.BOM_STRUCT.BSU_NOPARTE
GO
