SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[HARVARD BOM KARDESPED]
AS
SELECT     TOP 100 PERCENT dbo.FACTEXP.FE_FECHA, dbo.PEDIMPDET.PID_NOPARTE, dbo.KARDESPED.KAP_CANTDESC, 
                      dbo.FACTEXPDET.FED_NOPARTE
FROM         dbo.KARDESPED INNER JOIN
                      dbo.PEDIMPDET ON dbo.KARDESPED.KAP_INDICED_PED = dbo.PEDIMPDET.PID_INDICED INNER JOIN
                      dbo.FACTEXPDET ON dbo.KARDESPED.KAP_INDICED_FACT = dbo.FACTEXPDET.FED_INDICED INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
WHERE     (dbo.PEDIMPDET.PID_NOPARTE = '1X-6135V00')
ORDER BY dbo.FACTEXP.FE_FECHA, dbo.PEDIMPDET.PID_NOPARTE
GO
