SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[tipo de envio import]
AS
SELECT     TOP 100 PERCENT dbo.FACTIMP.FI_FOLIO, dbo.FACTIMP.FI_FECHA, dbo.FACTIMP.FI_TRAC_MX, dbo.TENVIO.TN_DESCRIP
FROM         dbo.FACTIMP INNER JOIN
                      dbo.TENVIO ON dbo.FACTIMP.TN_CODIGO = dbo.TENVIO.TN_CODIGO
WHERE     (dbo.FACTIMP.FI_FECHA >= CONVERT(DATETIME, '2004-09-01 00:00:00', 102) AND dbo.FACTIMP.FI_FECHA <= CONVERT(DATETIME, 
                      '2004-09-30 00:00:00', 102))
ORDER BY dbo.TENVIO.TN_DESCRIP, dbo.FACTIMP.FI_FECHA
GO
