SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[not nafta]
AS
SELECT     TOP 100 PERCENT dbo.FACTEXP.FE_FOLIO, dbo.FACTEXP.FE_FECHA, dbo.FACTEXP.FE_MANIF, dbo.FACTEXPDET.FED_NOPARTE, 
                      dbo.FACTEXPDET.FED_NOMBRE, dbo.FACTEXPDET.FED_CANT, dbo.FACTEXPDET.FED_GRA_MP, dbo.FACTEXPDET.FED_GRA_MO, 
                      dbo.FACTEXPDET.FED_GRA_EMP, dbo.FACTEXPDET.FED_NG_MP, dbo.FACTEXPDET.FED_NG_EMP, dbo.FACTEXPDET.FED_NG_USA, 
                      dbo.FACTEXPDET.FED_COS_UNI, dbo.FACTEXPDET.FED_COS_TOT, dbo.ARANCEL.AR_FRACCION, dbo.FACTEXPDET.FED_NAFTA
FROM         dbo.FACTEXP INNER JOIN
                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO INNER JOIN
                      dbo.ARANCEL ON dbo.FACTEXPDET.AR_IMPFO = dbo.ARANCEL.AR_CODIGO
WHERE     (dbo.ARANCEL.AR_FRACCION = '9506400000') AND (dbo.FACTEXP.FE_FECHA >= CONVERT(DATETIME, '2004-07-04 00:00:00', 102)) AND 
                      (dbo.FACTEXPDET.FED_NAFTA = 'N')
ORDER BY dbo.FACTEXP.FE_FECHA, dbo.FACTEXP.FE_FOLIO, dbo.FACTEXPDET.FED_NOPARTE
GO
