SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[PAGA 303]
AS
SELECT     TOP 100 PERCENT dbo.PEDIMPDET.PID_INDICED, dbo.PEDIMP.PI_FOLIO, dbo.PEDIMP.PI_FEC_ENT, dbo.PEDIMPDET.PID_NOPARTE, 
                      dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.PID_PAGACONTRIB, dbo.CLAVEPED.CP_CLAVE, dbo.PEDIMPDET.PID_POR_DEF, 
                      dbo.PEDIMPDET.PID_DEF_TIP, dbo.PEDIMPDET.PID_SEC_IMP, dbo.PAIS.PA_CORTO, dbo.FACTEXP.FE_FOLIO, dbo.FACTEXP.FE_FECHA, 
                      PEDIMP_1.PI_FOLIO AS Expr1, dbo.KARDESPED.KAP_CANTDESC, dbo.KARDESPED.KAP_CantTotADescargar
FROM         dbo.PEDIMP INNER JOIN
                      dbo.PEDIMPDET ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO INNER JOIN
                      dbo.CLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CLAVEPED.CP_CODIGO INNER JOIN
                      dbo.PAIS ON dbo.PEDIMPDET.PA_ORIGEN = dbo.PAIS.PA_CODIGO INNER JOIN
                      dbo.KARDESPED ON dbo.PEDIMPDET.PID_INDICED = dbo.KARDESPED.KAP_INDICED_PED INNER JOIN
                      dbo.FACTEXP ON dbo.KARDESPED.KAP_FACTRANS = dbo.FACTEXP.FE_CODIGO INNER JOIN
                      dbo.PEDIMP PEDIMP_1 ON dbo.FACTEXP.PI_CODIGO = PEDIMP_1.PI_CODIGO
WHERE     (dbo.PEDIMP.PI_MOVIMIENTO = 'E') AND (dbo.CLAVEPED.CP_CLAVE IN ('H2', 'R1')) AND (dbo.PEDIMP.PI_RECTESTATUS <> 'R') AND 
                      (dbo.PEDIMPDET.PID_PAGACONTRIB <> 'N') AND (dbo.PEDIMPDET.PID_NOPARTE = '6A-6414-009')
ORDER BY dbo.PEDIMPDET.PID_NOMBRE
GO
