SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VA16
with encryption as
SELECT     dbo.A16.A16_CODIGO, round(dbo.VPEDIMP.PI_TIP_CAM * ISNULL(dbo.PEDIMPDET.PID_CTOT_DLS, 0),0) AS valor, 
                      round(ISNULL(dbo.PEDIMPDET.PID_CTOT_DLS, 0),0) AS PID_CTOT_DLS, dbo.VPEDIMP.PI_CODIGO, dbo.VPEDIMP.PR_CODIGO, 
                      dbo.PEDIMPDET.PID_NOMBRE AS PID_NOMBRE, dbo.VPEDIMP.PI_TIP_CAM, dbo.VPEDIMP.CL_CODIGO, dbo.PEDIMPDET.MA_GENERICO, 
                      MAESTRO_1.MA_CODIGO, MAESTRO_1.MA_NOMBRE AS FAMILIAPT, dbo.VPEDIMP.CP_CODIGO, 'TRIMESTRE'=CASE WHEN Month(dbo.VPEDIMP.PI_FEC_PAG)<=3 THEN '1'  
		WHEN Month(dbo.VPEDIMP.PI_FEC_PAG)<=6 and Month(dbo.VPEDIMP.PI_FEC_PAG)>=4 THEN '2' WHEN Month(dbo.VPEDIMP.PI_FEC_PAG)<=9 and Month(dbo.VPEDIMP.PI_FEC_PAG)>=7 
		THEN '3' END, dbo.PEDIMPDET.MA_CODIGO AS MA_PEDIMP
FROM         dbo.CONFIGURATIPO RIGHT OUTER JOIN
                      dbo.MAESTRO MAESTRO_2 LEFT OUTER JOIN
                      dbo.MAESTRO MAESTRO_1 INNER JOIN
                      dbo.A16 INNER JOIN
                      dbo.VPEDIMP ON dbo.A16.A16_FECHAINI <= dbo.VPEDIMP.PI_FEC_ENT AND dbo.A16.A16_FECHAFIN >= dbo.VPEDIMP.PI_FEC_ENT ON 
                      MAESTRO_1.MA_CODIGO = dbo.A16.MA_FAMILIA ON MAESTRO_2.MA_FAMILIA = MAESTRO_1.MA_CODIGO FULL OUTER JOIN
                      dbo.PEDIMPDET ON MAESTRO_2.MA_CODIGO = dbo.PEDIMPDET.MA_CODIGO AND dbo.VPEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO ON 
                      dbo.CONFIGURATIPO.TI_CODIGO = dbo.PEDIMPDET.TI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
WHERE     (dbo.VPEDIMP.PI_TIPO = 'N') AND 
                      (dbo.VPEDIMP.PI_ESTATUS <> 'R') AND (dbo.CONFIGURATIPO.CFT_TIPO IN ('R', 'L', 'M', 'E')) OR 
                      (dbo.VPEDIMP.PI_ESTATUS <> 'R') AND (dbo.CONFIGURATIPO.CFT_TIPO IN ('R', 'L', 'M', 'E')) AND (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'IV') OR
                      (dbo.VPEDIMP.PI_ESTATUS <> 'R') AND (dbo.CONFIGURATIPO.CFT_TIPO IN ('R', 'L', 'M', 'E')) AND (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'VT') OR
                      (dbo.VPEDIMP.PI_ESTATUS <> 'R') AND (dbo.CONFIGURATIPO.CFT_TIPO IN ('R', 'L', 'M', 'E')) AND (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'RE') AND 
                      (dbo.VPEDIMP.CP_RECTIFICA IN
                          (SELECT     CP_CODIGO
                            FROM          CONFIGURACLAVEPED
                            WHERE      CCP_TIPO IN ('IV', 'VT')))

GO
