SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

	CREATE VIEW dbo.VDATOSPEDEXPDESCxPedExpT_InfBaseCalculoPagoArt303
	with encryption as
	SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_FACT, KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED, 
	                      KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CANTDESC, 
		'PI_TIP_CAM'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_PEDIMENTO,'')<>'' then isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
		PEDEXPDET.PIB_INDICEB,
	      factexp.pi_codigo AS  PI_CODIGOPEDEXP,
		'KAP_COS_UNI'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_PEDIMENTO,'')<>'' then round(isnull((KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_COSTOUNITACT / isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
		'PID_POR_DEF'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL else
		(case when PEDIMPDET.PID_PAGACONTRIB='N' then 0 else PEDIMPDET.PID_POR_DEF end) end, 
		'KAP_DEF_TIP'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
		KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO, 'KAP_SECIMP'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_SECIMP else PEDIMPDET.PID_SEC_IMP end, 
		'SPI_CODIGO'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.SPI_CODIGO else PEDIMPDET.SPI_CODIGO end,
		PEDIMPDET.PA_ORIGEN, PEDIMPDET.AR_IMPMX, PEDIMPDET.PID_PAGACONTRIB, PEDIMPDET.PID_NOMBRE,
		PEDIMPDET.PID_NOPARTE, PEDIMPDET.MA_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
	FROM         KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303 RIGHT OUTER JOIN
	                      KARDESPED_InformacionBaseParaCalcularPagoArt303 ON KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO = KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO LEFT OUTER JOIN
	                      FACTEXPDET_InformacionBaseParaCalcularPagoArt303 factexpdet ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED LEFT OUTER JOIN
	                      FACTEXP ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_FACTRANS = FACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      PEDIMP RIGHT OUTER JOIN
	                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO ON 
	                      KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
	                      pedexpdet_InformacionBaseParaCalcularPagoArt303 /*PEDIMPDET*/ PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGA LEFT OUTER JOIN
	                      PEDIMP PEDEXP ON FACTEXP.PI_CODIGO = PEDEXP.PI_CODIGO
	WHERE     (KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED IS NOT NULL) AND (PEDEXP.PI_ESTATUS <> 'R')
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IM', 'RE', 'IV', 'VT', 'ED', 'TS'))
	AND FACTEXPDET.FED_RETRABAJO<>'R' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO='D')
	AND FACTEXP.PI_CODIGO=07503 
	UNION
	SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_FACT, KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED, 
	                      KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CANTDESC, 
		'PI_TIP_CAM'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_PEDIMENTO,'')<>'' then isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
		PEDEXPDET.PIB_INDICEB, FACTEXP.PI_RECTIFICA AS PI_CODIGOPEDEXP,
		'KAP_COS_UNI'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_PEDIMENTO,'')<>'' then round(isnull((KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_COSTOUNITACT / isnull(KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
		'PID_POR_DEF'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL else
		(case when PEDIMPDET.PID_PAGACONTRIB='N' then 0 else PEDIMPDET.PID_POR_DEF end) end,
		'KAP_DEF_TIP'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
		KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO, 'KAP_SECIMP'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_SECIMP else PEDIMPDET.PID_SEC_IMP end, 
		'SPI_CODIGO'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
		KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_TASAFINAL<>-1 then KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.SPI_CODIGO else PEDIMPDET.SPI_CODIGO end,
		PEDIMPDET.PA_ORIGEN, PEDIMPDET.AR_IMPMX, PEDIMPDET.PID_PAGACONTRIB, PEDIMPDET.PID_NOMBRE,
		PEDIMPDET.PID_NOPARTE, PEDIMPDET.MA_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
	FROM KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303 
	RIGHT OUTER JOIN KARDESPED_InformacionBaseParaCalcularPagoArt303 ON KARDESPEDPPS_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO = KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_CODIGO 
	LEFT OUTER JOIN FACTEXPDET_InformacionBaseParaCalcularPagoArt303 FACTEXPDET ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED 
	LEFT OUTER JOIN FACTEXP ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_FACTRANS = FACTEXP.FE_CODIGO 
	LEFT OUTER JOIN PEDIMP 
	RIGHT OUTER JOIN PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO 
		ON KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED = PEDIMPDET.PID_INDICED 
	LEFT OUTER JOIN pedexpdet_InformacionBaseParaCalcularPagoArt303 /*PEDIMPDET*/ PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGAR1 
	LEFT OUTER JOIN PEDIMP PEDEXP ON FACTEXP.PI_RECTIFICA = PEDEXP.PI_CODIGO                   
	WHERE     (KARDESPED_InformacionBaseParaCalcularPagoArt303.KAP_INDICED_PED IS NOT NULL) 
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IM', 'RE', 'IV', 'VT', 'ED', 'TS'))
	AND FACTEXPDET.FED_RETRABAJO<>'R' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO='D')
	AND FACTEXP.PI_RECTIFICA=07503
GO
