SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW dbo.VPAGOCONTRIBUCION
with encryption as
SELECT     dbo.VDATOSPEDEXPCOMP.PI_CODIGO, dbo.FACTEXPDET.FE_CODIGO, 
  'TOTALPT' = CASE WHEN (TOTALARANUSA > MONTOIGIMXUSD or PIB_DESTNAFTA='N')
 THEN 0 else MONTOIGIMXUSD - isnull(TOTALARANUSA,0) END,
  'TOTALPTMN' = CASE WHEN (TOTALARANUSAMN > MONTOIGIMXMN or PIB_DESTNAFTA='N')
 THEN 0 else MONTOIGIMXMN - isnull(TOTALARANUSAMN,0) END
FROM         dbo.VDATOSPEDEXPCOMP LEFT OUTER JOIN
                      dbo.FACTEXPDET ON dbo.VDATOSPEDEXPCOMP.FED_INDICED = dbo.FACTEXPDET.FED_INDICED



GO
