SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VPRODUC
with encryption as
SELECT     PRO_CODIGO, PRO_FOLIO, PRO_FECHA, US_CODIGO, PRO_COMENTA, ARE_CODIGO, PRO_ESTATUS, 1 AS CL_CODIGO
FROM         dbo.PRODUC


GO
