SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.Reporte#parteConFraccion
AS
SELECT     TOP 100 PERCENT dbo.FACTIMPDET.FID_NOPARTE AS [Numero de Parte], dbo.FACTIMPDET.FID_NOMBRE AS [Descripcion en Espanol], 
                      dbo.ARANCEL.AR_FRACCION AS [Fraccion Arancelaria 
IMPMX]
FROM         dbo.ARANCEL RIGHT OUTER JOIN
                      dbo.FACTIMPDET ON dbo.ARANCEL.AR_CODIGO = dbo.FACTIMPDET.AR_IMPMX RIGHT OUTER JOIN
                      dbo.FACTIMP ON dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO
WHERE     (dbo.FACTIMP.FI_FECHA > CONVERT(DATETIME, '2003-01-01 00:00:00', 102)) AND (dbo.FACTIMP.FI_FECHA < CONVERT(DATETIME, 
                      '2004-03-24 00:00:00', 102))
GROUP BY dbo.FACTIMPDET.FID_NOPARTE, dbo.FACTIMPDET.FID_NOMBRE, dbo.ARANCEL.AR_FRACCION
ORDER BY dbo.ARANCEL.AR_FRACCION
GO
