SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW dbo.VPEDIMPVALORES
with encryption as
SELECT     dbo.PEDIMPDET.PI_CODIGO, max(round(dbo.PEDIMP.PI_PESO,6)) AS PI_PESO, round(SUM(dbo.PEDIMPDET.PID_CTOT_DLS) 
                      * dbo.PEDIMP.PI_FMON_EXT* isnull(dbo.PEDIMP.PI_FT_ADU,1),9) AS PI_VALOR_ME, 
	round(sum( isnull(dbo.PEDIMPDET.PID_CTOT_MN,1)),0) as PI_VALOR_FACT, 
                      round(sum( isnull(dbo.PEDIMPDET.PID_CTOT_MN,1)* isnull(dbo.PEDIMP.PI_FT_ADU,1)),0) as PI_VALOR_ADU, 
	ISNULL ((SELECT     SUM(dbo.VPEDIMPCONTRIBUCION1.PIT_CONTRIBTOTMN)
                              FROM         dbo.VPEDIMPCONTRIBUCION1 INNER JOIN
                                                    dbo.TPAGO ON dbo.VPEDIMPCONTRIBUCION1.PG_CODIGO = dbo.TPAGO.PG_CODIGO
                              WHERE     dbo.TPAGO.PG_CLAVE = '0' AND dbo.VPEDIMPCONTRIBUCION1.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO), 0) AS MONTOEFEC, ISNULL
                          ((SELECT     SUM(dbo.VPEDIMPCONTRIBUCION1.PIT_CONTRIBTOTMN)
                              FROM         dbo.VPEDIMPCONTRIBUCION1 INNER JOIN
                                                    dbo.TPAGO ON dbo.VPEDIMPCONTRIBUCION1.PG_CODIGO = dbo.TPAGO.PG_CODIGO
                              WHERE     dbo.TPAGO.PG_CLAVE <> '0' AND dbo.VPEDIMPCONTRIBUCION1.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO), 0) AS MONTODIFEFEC,
		sum(dbo.PEDIMPDET.PID_CAN_GEN) as PID_CAN_GEN, ISNULL((SELECT SUM(PEDIMPCONTRIBUCION.PIT_CONTRIBTOTMN)  FROM PEDIMPCONTRIBUCION INNER JOIN
                      CONTRIBUCION ON PEDIMPCONTRIBUCION.CON_CODIGO = CONTRIBUCION.CON_CODIGO WHERE CONTRIBUCION.CON_ABREVIA = 'DTA' AND PEDIMPCONTRIBUCION.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO),0) AS PAGODTAMN,
	isnull(max(PI_NUMVEHICULOS),0) as PI_NUMVEHICULOS
FROM         dbo.PEDIMP INNER JOIN
                      dbo.PEDIMPDET ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO
WHERE dbo.PEDIMPDET.PID_IMPRIMIR ='S'
GROUP BY dbo.PEDIMP.PI_TIP_CAM, dbo.PEDIMP.PI_FT_ADU, dbo.PEDIMP.PI_FMON_EXT, dbo.PEDIMPDET.PI_CODIGO, PI_USA_TIP_CAMFACT, dbo.PEDIMP.PI_FEC_PAG, dbo.PEDIMP.pi_movimiento








GO
