SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW dbo.VPAPSBARCODE
with encryption as
SELECT     dbo.FAST.FST_TIPO, dbo.FASTBARCODE.BFST_FOLIOFACT, dbo.FACTEXP.FE_CODIGO, 
                      dbo.FASTBARCODE.BFST_TEXTO, FAST.CT_CODIGO AS BFST_TRANSPOR
FROM         dbo.FASTBARCODE INNER JOIN
                      dbo.FAST ON dbo.FASTBARCODE.FST_CODIGO = dbo.FAST.FST_CODIGO INNER JOIN
                      dbo.FACTEXP ON dbo.FASTBARCODE.BFST_FOLIOFACT = dbo.FACTEXP.FE_FOLIO
WHERE     (dbo.FAST.FST_TIPO = 'P')


GO
