SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VEXHIBIT_C247W25
with encryption as
SELECT COSTSUBPER.CS_CODIGO, 
    COUNT(VEXHIBIT_B_BASE247.ET_CODIGO) 
    AS [NO.ENTRI/W25]
FROM VEXHIBIT_B_BASE247 FULL OUTER JOIN
    COSTSUBPER ON 
    VEXHIBIT_B_BASE247.ET_FEC_ENTRYS >= COSTSUBPER.CS_FECHAINI
     AND 
    VEXHIBIT_B_BASE247.ET_FEC_ENTRYS <= COSTSUBPER.CS_FECHAFIN
WHERE (VEXHIBIT_B_BASE247.ETA_DLLS_MPF = 25)
GROUP BY COSTSUBPER.CS_CODIGO












GO
