SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VPAIS
with encryption as
SELECT     TOP 100 PERCENT dbo.PAIS.PA_CODIGO, dbo.PAIS.PA_CORTO, dbo.PAIS.PA_NOMBRE, dbo.PAIS.PA_NAME, dbo.PAIS.PA_ISO, 
                      dbo.PAIS.PA_SAAIM3, dbo.PAIS.SPI_CODIGO, max(dbo.PAISMRP.PA_TEXTOMRP) as PA_TEXTOMRP, dbo.PAIS.PA_CLA_PED
FROM         dbo.PAIS LEFT OUTER JOIN
                      dbo.PAISMRP ON dbo.PAIS.PA_CODIGO = dbo.PAISMRP.PA_INTRADE
group by dbo.PAIS.PA_CODIGO, dbo.PAIS.PA_CORTO, dbo.PAIS.PA_NOMBRE, dbo.PAIS.PA_NAME, dbo.PAIS.PA_ISO, 
                      dbo.PAIS.PA_SAAIM3, dbo.PAIS.SPI_CODIGO, dbo.PAIS.PA_CLA_PED
ORDER BY dbo.PAIS.PA_CORTO







GO
