SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO























CREATE VIEW dbo.VFACTEXPDET9801
with encryption as
SELECT     FED_INDICED, FACTEXP.FE_CODIGO,
		'MA_9801' =CASE WHEN  TI_CODIGO not in (select ti_codigo from configuratipo where cft_tipo='P' or cft_tipo='S') 
		THEN ISNULL((SELECT  MAX(CERTORIGMP.CMP_FOLIO)
			FROM  CERTORIGMPDET INNER JOIN CERTORIGMP ON CERTORIGMPDET.CMP_CODIGO = CERTORIGMP.CMP_CODIGO
			--Yolanda Avila			
			--2010-04-06
			--WHERE  LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCION,'.',''),6)=LEFT(REPLACE(ARANCEL.AR_FRACCION,'.',''),6) 
			where (case when (LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCION,'.',''),6) = LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCIONAlt,'.',''),6))  or (CERTORIGMPDET.CMP_FRACCION <> '' and CERTORIGMPDET.CMP_FRACCIONAlt='') then 
				     LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCION,'.',''),6) 
			       else case when (LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCION,'.',''),6) <>  LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCIONAlt,'.',''),6) 
					     and (SELECT SPI_CLAVE FROM SPI WHERE spi.spi_codigo = CERTORIGMP.spi_codigo )='NAFTA' ) then 
						     LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCIONalt,'.',''),6) 
				     else
					     LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCION,'.',''),6) 
				     end end)
			        = LEFT(REPLACE(ARANCEL.AR_FRACCION,'.',''),6) 			


			AND CERTORIGMP.CMP_ESTATUS='V' AND CERTORIGMPDET.PA_CLASE IN (SELECT CF_PAIS_USA FROM CONFIGURACION)
			AND  CERTORIGMP.SPI_CODIGO IN (SELECT spi_codigo FROM spi  WHERE spi_clave = 'nafta')
			AND  CERTORIGMP.CMP_IFECHA<=FACTEXP.FE_FECHA AND CERTORIGMP.CMP_FECHATRANS>=FACTEXP.FE_FECHA AND CERTORIGMPDET.MA_CODIGO=FACTEXPDET.MA_CODIGO),'')
 		WHEN TI_CODIGO not in (select ti_codigo from configuratipo where cft_tipo='P' or cft_tipo='S') AND (select cf_usaaffidavit from configuracion)='S' 
		THEN ISNULL((SELECT     MAX(CERTORIGMP.CMP_FOLIO)
			FROM  CERTORIGMPDET INNER JOIN CERTORIGMP ON CERTORIGMPDET.CMP_CODIGO = CERTORIGMP.CMP_CODIGO
			WHERE  LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCION,'.',''),6)=LEFT(REPLACE(ARANCEL.AR_FRACCION,'.',''),6) 
			AND CERTORIGMP.CMP_ESTATUS='V' AND CERTORIGMPDET.PA_CLASE IN (SELECT CF_PAIS_USA FROM CONFIGURACION)
			AND  CERTORIGMP.SPI_CODIGO IN (SELECT spi_codigo FROM spi  WHERE spi_clave = 'nafta')
			AND  CERTORIGMP.CMP_IFECHA<=FACTEXP.FE_FECHA AND CERTORIGMP.CMP_FECHATRANS>=FACTEXP.FE_FECHA AND CERTORIGMPDET.MA_CODIGO=FACTEXPDET.MA_CODIGO and cmp_affidavit='S'),'')
		ELSE '' END
FROM         FACTEXPDET INNER JOIN
                      FACTEXP ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      ARANCEL ON FACTEXPDET.AR_IMPFO = ARANCEL.AR_CODIGO


GO
