SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE VIEW dbo.VDATOSPEDEXPPAGOMEX
with encryption as
SELECT     dbo.PEDIMPDETB.PI_CODIGO, dbo.PEDIMPDETB.PIB_INDICEB, dbo.PEDIMPDETB.AR_EXPFO, dbo.PEDIMPDETB.PIB_SECUENCIA, 
                      SUM(ISNULL(ROUND(dbo.VDATOSPEDEXPDESC.KAP_COS_UNI, 6) * dbo.VDATOSPEDEXPDESC.KAP_CANTDESC, 0)) 
                      AS VALORMERCNOORIGUSD, SUM(ISNULL(ROUND(dbo.VDATOSPEDEXPDESC.KAP_COS_UNI, 6) * dbo.VDATOSPEDEXPDESC.KAP_CANTDESC, 0)*dbo.VDATOSPEDEXPDESC.PI_TIP_CAM) 
                      AS VALORMERCNOORIGMN, SUM((ROUND(dbo.VDATOSPEDEXPDESC.KAP_COS_UNI, 6) * dbo.VDATOSPEDEXPDESC.KAP_CANTDESC) 
                      * (dbo.VDATOSPEDEXPDESC.PID_POR_DEF / 100)) AS MONTOIGIMXUSD, 
	           SUM((ROUND(dbo.VDATOSPEDEXPDESC.KAP_COS_UNI, 6) * dbo.VDATOSPEDEXPDESC.KAP_CANTDESC) 
                      * (dbo.VDATOSPEDEXPDESC.PID_POR_DEF / 100)* dbo.VDATOSPEDEXPDESC.PI_TIP_CAM) AS MONTOIGIMXMN,
		dbo.FACTEXPDET.FED_INDICED
FROM         dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO INNER JOIN
                      dbo.PEDIMPDETB ON dbo.FACTEXP.PI_CODIGO = dbo.PEDIMPDETB.PI_CODIGO INNER JOIN
                      dbo.PEDIMPDET PEDIMPDET_1 ON dbo.PEDIMPDETB.PIB_INDICEB = PEDIMPDET_1.PIB_INDICEB AND 
                      dbo.FACTEXPDET.PID_INDICEDLIGA = PEDIMPDET_1.PID_INDICED INNER JOIN
                      dbo.PEDIMP PEDIMP_2 ON dbo.PEDIMPDETB.PI_CODIGO = PEDIMP_2.PI_CODIGO INNER JOIN
                      dbo.VDATOSPEDEXPDESC ON dbo.FACTEXPDET.FED_INDICED = dbo.VDATOSPEDEXPDESC.KAP_INDICED_FACT
WHERE PEDIMP_2.PI_ESTATUS <>'R'
GROUP BY dbo.PEDIMPDETB.PI_CODIGO, dbo.PEDIMPDETB.AR_EXPFO, dbo.PEDIMPDETB.PIB_SECUENCIA, dbo.PEDIMPDETB.PIB_INDICEB, 
                      dbo.FACTEXPDET.FED_INDICED
UNION
SELECT     dbo.PEDIMPDETB.PI_CODIGO, dbo.PEDIMPDETB.PIB_INDICEB, dbo.PEDIMPDETB.AR_EXPFO, dbo.PEDIMPDETB.PIB_SECUENCIA, 
                      SUM(ISNULL(ROUND(dbo.VDATOSPEDEXPDESC.KAP_COS_UNI, 6) * dbo.VDATOSPEDEXPDESC.KAP_CANTDESC, 0)) 
                      AS VALORMERCNOORIGUSD, SUM(ISNULL(ROUND(dbo.VDATOSPEDEXPDESC.KAP_COS_UNI, 6) * dbo.VDATOSPEDEXPDESC.KAP_CANTDESC, 0)*dbo.VDATOSPEDEXPDESC.PI_TIP_CAM) 
                      AS VALORMERCNOORIGMN, SUM((ROUND(dbo.VDATOSPEDEXPDESC.KAP_COS_UNI, 6) * dbo.VDATOSPEDEXPDESC.KAP_CANTDESC) 
                      * (dbo.VDATOSPEDEXPDESC.PID_POR_DEF / 100)) AS MONTOIGIMXUSD, 
	           SUM((ROUND(dbo.VDATOSPEDEXPDESC.KAP_COS_UNI, 6) * dbo.VDATOSPEDEXPDESC.KAP_CANTDESC) 
                      * (dbo.VDATOSPEDEXPDESC.PID_POR_DEF / 100)* dbo.VDATOSPEDEXPDESC.PI_TIP_CAM) AS MONTOIGIMXMN,
		dbo.FACTEXPDET.FED_INDICED
FROM         dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO INNER JOIN
                      dbo.PEDIMPDETB ON dbo.FACTEXP.PI_RECTIFICA = dbo.PEDIMPDETB.PI_CODIGO INNER JOIN
                      dbo.PEDIMPDET PEDIMPDET_1 ON dbo.PEDIMPDETB.PIB_INDICEB = PEDIMPDET_1.PIB_INDICEB AND 
                      dbo.FACTEXPDET.PID_INDICEDLIGAR1 = PEDIMPDET_1.PID_INDICED INNER JOIN
                      dbo.PEDIMP PEDIMP_2 ON dbo.PEDIMPDETB.PI_CODIGO = PEDIMP_2.PI_CODIGO INNER JOIN
                      dbo.VDATOSPEDEXPDESC ON dbo.FACTEXPDET.FED_INDICED = dbo.VDATOSPEDEXPDESC.KAP_INDICED_FACT
GROUP BY dbo.PEDIMPDETB.PI_CODIGO, dbo.PEDIMPDETB.AR_EXPFO, dbo.PEDIMPDETB.PIB_SECUENCIA, dbo.PEDIMPDETB.PIB_INDICEB, 
                      dbo.FACTEXPDET.FED_INDICED



























GO
