SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[descarga por numero de parte]
AS
SELECT     TOP 100 PERCENT dbo.PEDIMPDET.MA_CODIGO, dbo.PEDIMPDET.PID_NOPARTE, dbo.KARDESPED.MA_HIJO, dbo.MAESTRO.MA_NOPARTE, 
                      dbo.KARDESPED.KAP_CANTDESC, dbo.KARDESPED.KAP_CantTotADescargar, dbo.FACTEXPDET.FED_NOPARTE, dbo.FACTEXP.FE_FECHA, 
                      dbo.KARDESPED.KAP_INDICED_PED, dbo.FACTEXP.FE_FOLIO, dbo.PIDescarga.PID_SALDOGEN, dbo.PEDIMP.PI_FOLIO, dbo.MAESTRO.MA_NOMBRE, 
                      dbo.KARDESPED.KAP_ESTATUS, dbo.KARDESPED.KAP_PADRESUST
FROM         dbo.PEDIMP INNER JOIN
                      dbo.PEDIMPDET ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO RIGHT OUTER JOIN
                      dbo.KARDESPED INNER JOIN
                      dbo.MAESTRO ON dbo.KARDESPED.MA_HIJO = dbo.MAESTRO.MA_CODIGO INNER JOIN
                      dbo.FACTEXPDET ON dbo.KARDESPED.KAP_INDICED_FACT = dbo.FACTEXPDET.FED_INDICED INNER JOIN
                      dbo.FACTEXP ON dbo.KARDESPED.KAP_FACTRANS = dbo.FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      dbo.PIDescarga ON dbo.KARDESPED.KAP_INDICED_PED = dbo.PIDescarga.PID_INDICED ON 
                      dbo.PEDIMPDET.PID_INDICED = dbo.KARDESPED.KAP_INDICED_PED
WHERE     (dbo.MAESTRO.MA_NOPARTE = '1X-6110-00') AND (dbo.PEDIMP.PI_FOLIO = '5013060')
ORDER BY dbo.PEDIMPDET.MA_CODIGO, dbo.FACTEXP.FE_FECHA, dbo.FACTEXPDET.FED_NOPARTE
GO
