SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VFACTIMPENT
with encryption as
SELECT     FI_CODIGO, FID_NUM_ENT, FID_FEC_ENT
FROM         dbo.FACTIMPDET
WHERE FID_NUM_ENT IS NOT NULL AND FID_NUM_ENT<>''
GROUP BY FI_CODIGO, FID_NUM_ENT, FID_FEC_ENT


GO
