SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VA16TOTAL
with encryption as
SELECT     dbo.A16.A16_CODIGO, SUM(dbo.VPEDEXP.PI_TIP_CAM * ISNULL(dbo.PEDIMPDET.PID_CTOT_DLS, 0)) AS valor, 
                      SUM(ISNULL(dbo.PEDIMPDET.PID_CTOT_DLS, 0)) AS PID_CTOT_DLS, dbo.CLAVEPED.CP_CLAVE, dbo.MAESTRO.MA_FAMILIA
FROM         dbo.CLAVEPED RIGHT OUTER JOIN
                      dbo.A16 INNER JOIN
                      dbo.VPEDEXP ON dbo.A16.A16_FECHAINI <= dbo.VPEDEXP.PI_FEC_PAG AND dbo.A16.A16_FECHAFIN >= dbo.VPEDEXP.PI_FEC_PAG ON 
                      dbo.CLAVEPED.CP_CODIGO = dbo.VPEDEXP.CP_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO RIGHT OUTER JOIN
                      dbo.PEDIMPDET ON dbo.MAESTRO.MA_CODIGO = dbo.PEDIMPDET.MA_CODIGO ON dbo.VPEDEXP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO
WHERE     (dbo.VPEDEXP.PI_ESTATUS <> 'R')
GROUP BY dbo.CLAVEPED.CP_CLAVE, dbo.A16.A16_CODIGO, dbo.MAESTRO.MA_FAMILIA
HAVING      (dbo.CLAVEPED.CP_CLAVE = 'J1') OR
                      (dbo.CLAVEPED.CP_CLAVE = 'F4')

GO
