SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.FacturasExportFraccion
AS
SELECT     TOP 100 PERCENT ARANCEL_1.AR_FRACCION AS [USA HTS], ARANCEL_2.AR_FRACCION AS [Mex HTS], dbo.FACTEXP.FE_FOLIO AS Invoice, 
                      dbo.FACTEXP.FE_FECHA AS [Date], dbo.FACTEXPDET.FED_NOPARTE AS [Part Number], dbo.FACTEXPDET.FED_NOMBRE AS SpanishDEsc, 
                      dbo.FACTEXPDET.FED_NAME AS EnglishDEsc, dbo.PAIS.PA_CORTO AS Origin, dbo.MEDIDA.ME_CORTO AS UM, 
                      dbo.FACTEXPDET.FED_CANT AS Quantity, dbo.FACTEXPDET.FED_GRA_MP AS UnitForeign, dbo.FACTEXPDET.FED_NG_MP AS [Unit USA], 
                      dbo.FACTEXPDET.FED_GRA_EMP AS UnitMX, dbo.FACTEXPDET.FED_NG_EMP AS UnitPackaging, dbo.FACTEXPDET.FED_GRA_ADD AS UnitKits, 
                      dbo.FACTEXPDET.FED_GRA_MO AS UnitAddedValue, dbo.FACTEXPDET.FED_GRA_GI, dbo.FACTEXPDET.FED_COS_UNI AS UnitCost, 
                      dbo.FACTEXPDET.FED_COS_TOT AS ExtendedValue
FROM         dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO INNER JOIN
                      dbo.PAIS ON dbo.FACTEXPDET.PA_CODIGO = dbo.PAIS.PA_CODIGO INNER JOIN
                      dbo.MEDIDA ON dbo.FACTEXPDET.ME_CODIGO = dbo.MEDIDA.ME_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ARANCEL_1 ON dbo.FACTEXPDET.AR_IMPFO = ARANCEL_1.AR_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ARANCEL_2 ON dbo.FACTEXPDET.AR_EXPMX = ARANCEL_2.AR_CODIGO
WHERE     (dbo.FACTEXP.FE_FECHA > CONVERT(DATETIME, '2004-01-01 00:00:00', 102)) AND (dbo.FACTEXP.FE_FECHA < CONVERT(DATETIME, 
                      '2004-02-22 00:00:00', 102)) AND (dbo.FACTEXPDET.TI_CODIGO IN (14, 16))
ORDER BY ARANCEL_1.AR_FRACCION, dbo.FACTEXP.FE_FECHA
GO
