SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VNOPARTE_RES
with encryption as
SELECT     dbo.MAESTRO.MA_CODIGO, dbo.MAESTRO.MA_NOPARTEAUX, dbo.MAESTRO.MA_NOPARTE, dbo.MAESTRO.MA_NOMBRE, dbo.MAESTRO.MA_NAME, 
                      dbo.MAESTRO.TI_CODIGO, dbo.MAESTRO.MA_GENERICO, MAESTRO1.ME_COM AS ME_GEN, dbo.MAESTRO.EQ_GEN, dbo.MAESTRO.ME_COM, dbo.MAESTRO.PA_ORIGEN
FROM         dbo.MAESTRO LEFT OUTER JOIN
                      dbo.MAESTRO MAESTRO1 ON dbo.MAESTRO.MA_GENERICO = MAESTRO1.MA_CODIGO
WHERE     (dbo.MAESTRO.MA_INV_GEN = 'I') AND (dbo.MAESTRO.MA_OCULTO = 'N')

GO
