SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VEXHIBIT_C247COUNTMAX
with encryption as
SELECT VEXHIBIT_B_BASE247.CS_CODIGO, 
    COUNT(VEXHIBIT_B_BASE247.ET_CODIGO) 
    AS COUNT_ET_CODIGO
FROM VEXHIBIT_C247MAXMPF INNER JOIN
    VEXHIBIT_B_BASE247 ON 
    VEXHIBIT_C247MAXMPF.CS_CODIGO = VEXHIBIT_B_BASE247.CS_CODIGO
     AND 
    VEXHIBIT_C247MAXMPF.MAX_MPF_PAG = VEXHIBIT_B_BASE247.ETA_DLLS_MPF
GROUP BY VEXHIBIT_B_BASE247.CS_CODIGO







GO
