SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


/* material no gravable*/
CREATE VIEW dbo.VEXHIBIT_A_1bDet
with encryption as
SELECT     SUM(CSA_NG_MAT) AS CSA_NG_MAT, CS_CODIGO, SUM(CSA_EMP_US) AS CSA_EMP_US, FE_CODIGO, FE_FOLIO, AR_FRACCION, FED_NOPARTE
FROM         (SELECT    SUM(dbo.FACTEXPDET.FED_NG_USA * dbo.FACTEXPDET.FED_CANT) AS CSA_NG_MAT, 
		dbo.VRELCSFACTEXP.CS_CODIGO, SUM(dbo.FACTEXPDET.FED_NG_EMP * dbo.FACTEXPDET.FED_CANT) AS CSA_EMP_US,
		     dbo.FACTEXP.FE_CODIGO, dbo.FACTEXP.FE_FOLIO, dbo.ARANCEL.AR_FRACCION, dbo.FACTEXPDET.FED_NOPARTE
	FROM         dbo.CONFIGURATIPO RIGHT OUTER JOIN
	                      dbo.ARANCEL RIGHT OUTER JOIN
	                      dbo.FACTEXPDET ON dbo.ARANCEL.AR_CODIGO = dbo.FACTEXPDET.AR_IMPFO ON 
	                      dbo.CONFIGURATIPO.TI_CODIGO = dbo.FACTEXPDET.TI_CODIGO RIGHT OUTER JOIN
	                      dbo.CONFIGURATEMBARQUE RIGHT OUTER JOIN
	                      dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.VRELCSFACTEXP ON dbo.FACTEXP.FE_CODIGO = dbo.VRELCSFACTEXP.FE_CODIGO ON 
	                      dbo.CONFIGURATEMBARQUE.TQ_CODIGO = dbo.FACTEXP.TQ_CODIGO ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
	WHERE     (dbo.CONFIGURATEMBARQUE.CFQ_TIPO <> 'D') AND (dbo.FACTEXP.TN_CODIGO = 2 OR
	                      dbo.FACTEXP.TN_CODIGO = 6 OR dbo.FACTEXP.TN_CODIGO = 8 OR dbo.FACTEXP.TN_CODIGO = 9 OR
	                      dbo.FACTEXP.TN_CODIGO = 7 OR
	                      dbo.FACTEXP.TN_CODIGO = 5)
	          AND dbo.FACTEXPDET.TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE CFT_TIPO IN ('P', 'S'))
	GROUP BY dbo.VRELCSFACTEXP.CS_CODIGO, dbo.FACTEXP.FE_CODIGO, dbo.FACTEXP.FE_FOLIO, dbo.ARANCEL.AR_FRACCION, dbo.FACTEXPDET.FED_NOPARTE
	UNION
	SELECT     SUM(dbo.FACTEXPDET.FED_COS_UNI * dbo.FACTEXPDET.FED_CANT) AS CSA_NG_MAT, dbo.VRELCSFACTEXP.CS_CODIGO, 
	                      0 AS CSA_EMP_US, dbo.FACTEXP.FE_CODIGO, dbo.FACTEXP.FE_FOLIO, dbo.ARANCEL.AR_FRACCION, dbo.FACTEXPDET.FED_NOPARTE
	FROM         dbo.CONFIGURATIPO RIGHT OUTER JOIN
	                      dbo.ARANCEL RIGHT OUTER JOIN
	                      dbo.FACTEXPDET ON dbo.ARANCEL.AR_CODIGO = dbo.FACTEXPDET.AR_IMPFO ON 
	                      dbo.CONFIGURATIPO.TI_CODIGO = dbo.FACTEXPDET.TI_CODIGO RIGHT OUTER JOIN
	                      dbo.CONFIGURATEMBARQUE RIGHT OUTER JOIN
	                      dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.VRELCSFACTEXP ON dbo.FACTEXP.FE_CODIGO = dbo.VRELCSFACTEXP.FE_CODIGO ON 
	                      dbo.CONFIGURATEMBARQUE.TQ_CODIGO = dbo.FACTEXP.TQ_CODIGO ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
	WHERE     (dbo.CONFIGURATEMBARQUE.CFQ_TIPO <> 'D') AND (dbo.FACTEXP.TN_CODIGO = 2 OR
	                      dbo.FACTEXP.TN_CODIGO = 6 OR dbo.FACTEXP.TN_CODIGO = 8 OR dbo.FACTEXP.TN_CODIGO = 9 OR
	                      dbo.FACTEXP.TN_CODIGO = 7 OR
	                      dbo.FACTEXP.TN_CODIGO = 5) AND (dbo.ARANCEL.AR_FRACCION LIKE '9802%' or dbo.ARANCEL.AR_FRACCION like '9801%')
		AND dbo.FACTEXPDET.TI_CODIGO NOT IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE CFT_TIPO IN ('P', 'S', 'E'))
	GROUP BY dbo.VRELCSFACTEXP.CS_CODIGO,dbo.FACTEXP.FE_CODIGO, dbo.FACTEXP.FE_FOLIO, dbo.ARANCEL.AR_FRACCION, dbo.FACTEXPDET.FED_NOPARTE
	UNION
	SELECT     0 AS CSA_NG_MAT, dbo.VRELCSFACTEXP.CS_CODIGO, 
	                      SUM(dbo.FACTEXPDET.FED_COS_UNI * dbo.FACTEXPDET.FED_CANT)  AS CSA_EMP_US, 
		     dbo.FACTEXP.FE_CODIGO, dbo.FACTEXP.FE_FOLIO, dbo.ARANCEL.AR_FRACCION, dbo.FACTEXPDET.FED_NOPARTE
	FROM         dbo.CONFIGURATIPO RIGHT OUTER JOIN
	                      dbo.ARANCEL RIGHT OUTER JOIN
	                      dbo.FACTEXPDET ON dbo.ARANCEL.AR_CODIGO = dbo.FACTEXPDET.AR_IMPFO ON 
	                      dbo.CONFIGURATIPO.TI_CODIGO = dbo.FACTEXPDET.TI_CODIGO RIGHT OUTER JOIN
	                      dbo.CONFIGURATEMBARQUE RIGHT OUTER JOIN
	                      dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.VRELCSFACTEXP ON dbo.FACTEXP.FE_CODIGO = dbo.VRELCSFACTEXP.FE_CODIGO ON 
	                      dbo.CONFIGURATEMBARQUE.TQ_CODIGO = dbo.FACTEXP.TQ_CODIGO ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
	WHERE     (dbo.CONFIGURATEMBARQUE.CFQ_TIPO <> 'D') AND (dbo.FACTEXP.TN_CODIGO = 2 OR
	                      dbo.FACTEXP.TN_CODIGO = 6 OR
	                      dbo.FACTEXP.TN_CODIGO = 7 OR
	                      dbo.FACTEXP.TN_CODIGO = 5 OR
			dbo.FACTEXP.TN_CODIGO = 8 OR
			dbo.FACTEXP.TN_CODIGO = 9) AND (dbo.ARANCEL.AR_FRACCION LIKE '9802%' or dbo.ARANCEL.AR_FRACCION like '9801%')
		AND dbo.FACTEXPDET.TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE CFT_TIPO IN ('E'))
	GROUP BY dbo.VRELCSFACTEXP.CS_CODIGO, dbo.FACTEXP.FE_CODIGO, dbo.FACTEXP.FE_FOLIO, dbo.ARANCEL.AR_FRACCION, dbo.FACTEXPDET.FED_NOPARTE) EXHIBIT_A_1ba
GROUP BY CS_CODIGO, FE_CODIGO, FE_FOLIO, AR_FRACCION, FED_NOPARTE



GO
