SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VPEDIMPPERMAR
with encryption as
SELECT     dbo.PEDIMPDET.AR_IMPMX, dbo.PEDIMPDETPERM.PI_CODIGO, dbo.PEDIMPDETPERM.IDE_CODIGO, dbo.PEDIMPDETPERM.PE_CODIGO, 
                      dbo.PEDIMPDETPERM.PIP_FOLIO, dbo.PEDIMPDETPERM.PIP_FIRMA, SUM(dbo.PEDIMPDETPERM.PIP_VALOR) AS PIP_VALOR, 
                      SUM(dbo.PEDIMPDETPERM.PIP_CANT) AS PIP_CANT
FROM         dbo.PEDIMPDET LEFT OUTER JOIN
                      dbo.PEDIMPDETPERM ON dbo.PEDIMPDET.PID_INDICED = dbo.PEDIMPDETPERM.PIB_INDICEB
GROUP BY dbo.PEDIMPDET.AR_IMPMX, dbo.PEDIMPDETPERM.PI_CODIGO, dbo.PEDIMPDETPERM.IDE_CODIGO, dbo.PEDIMPDETPERM.PE_CODIGO, 
                      dbo.PEDIMPDETPERM.PIP_FOLIO, dbo.PEDIMPDETPERM.PIP_FIRMA



GO
