SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.V_GETPTSUBBOM (
  MA_CODIGO,
  MA_NOMBRE,
  TI_CODIGO
) AS 
SELECT MA_CODIGO, MA_NOMBRE , TI_CODIGO
FROM MAESTRO
WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO 
			WHERE (CFT_TIPO = 'S') OR (CFT_TIPO = 'P'))



GO
