SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VA16PEDIMENTOS
with encryption as
SELECT     dbo.A16DET.A16_CODIGO, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT
FROM         dbo.A16DET LEFT OUTER JOIN
                      dbo.VPEDIMP ON dbo.A16DET.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO
WHERE     (dbo.VPEDIMP.PI_TIPO IN ('A', 'C'))
GROUP BY dbo.A16DET.A16_CODIGO, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT

GO
