SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




































CREATE VIEW dbo.VPREVIAPISINTCAMBIO
with encryption as
SELECT     TOP 100 PERCENT dbo.AGENCIAPATENTE.AGT_PATENTE collate database_default + '-' + dbo.PEDIMP.PI_FOLIO collate database_default AS PI_PATENTEFOLIO, dbo.PEDIMP.PI_FEC_ENT, 
                      dbo.PEDIMP.PI_FEC_PAG, dbo.PEDIMP.PI_TIP_CAM, dbo.CLAVEPED.CP_CLAVE, dbo.PEDIMPDET.MA_CODIGO, dbo.PEDIMPDET.PID_NOPARTE, 
                      dbo.PEDIMPDET.PID_COS_UNI, dbo.PEDIMPDET.PID_CANT, dbo.PEDIMPDET.PID_INDICED
FROM         dbo.CONFIGURATIPO RIGHT OUTER JOIN
                      dbo.PEDIMPDET ON dbo.CONFIGURATIPO.TI_CODIGO = dbo.PEDIMPDET.TI_CODIGO RIGHT OUTER JOIN
                      dbo.PEDIMP LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED CONFIGURACLAVEPED_1 ON dbo.PEDIMP.CP_RECTIFICA = CONFIGURACLAVEPED_1.CP_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED CONFIGURACLAVEPED_2 ON dbo.PEDIMP.CP_CODIGO = CONFIGURACLAVEPED_2.CP_CODIGO LEFT OUTER JOIN
                      dbo.CLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CLAVEPED.CP_CODIGO LEFT OUTER JOIN
                      dbo.AGENCIAPATENTE ON dbo.PEDIMP.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO
WHERE     (dbo.PEDIMP.PI_ESTATUS <> 'R') AND (dbo.PEDIMP.PI_MOVIMIENTO = 'E') AND (dbo.PEDIMP.PI_TIP_CAM = 0 OR
                      dbo.PEDIMP.PI_TIP_CAM IS NULL) AND (dbo.CLAVEPED.CP_DESCARGABLE = 'S') AND (dbo.PEDIMPDET.PID_NOPARTE IS NOT NULL) AND 
                      (CONFIGURACLAVEPED_2.CCP_TIPO <> 'IA') AND (CONFIGURACLAVEPED_2.CCP_TIPO <> 'IM') AND (CONFIGURACLAVEPED_2.CCP_TIPO <> 'IB') AND 
                      (CONFIGURACLAVEPED_2.CCP_TIPO <> 'IE') AND (NOT (dbo.CONFIGURATIPO.CFT_TIPO IN ('Q', 'H'))) AND (dbo.PEDIMPDET.PID_IMPRIMIR = 'S')
ORDER BY dbo.PEDIMP.PI_FEC_ENT, dbo.AGENCIAPATENTE.AGT_PATENTE collate database_default + '-' + dbo.PEDIMP.PI_FOLIO collate database_default




























































GO
