SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO








CREATE VIEW dbo.VFACTEXPFLETE
with encryption as
SELECT PI_CODIGO, PI_RECTIFICA, FE_CODIGO, FE_FACTAGRU, FE_TOTALB, FE_TRAC_MX1, ISNULL((SELECT SUM(FACTEXPDET.FED_PES_BRU) FROM FACTEXPDET WHERE FACTEXPDET.FE_CODIGO=dbo.FACTEXP.FE_CODIGO),0) AS FE_PESOKG,
isnull((SELECT SUM(FACTEXPINCREMENTA1.FEI_VALOR)
FROM         dbo.FACTEXPINCREMENTA FACTEXPINCREMENTA1 INNER JOIN
                      dbo.INCREMENTABLE ON FACTEXPINCREMENTA1.IC_CODIGO = dbo.INCREMENTABLE.IC_CODIGO
WHERE     dbo.INCREMENTABLE.IC_PEDIMENTO = 'F' AND FACTEXPINCREMENTA1.FE_CODIGO=dbo.FACTEXP.FE_CODIGO),0) AS FE_FLETE,
isnull((SELECT SUM(FACTEXPINCREMENTA1.FEI_VALOR)
FROM         dbo.FACTEXPINCREMENTA FACTEXPINCREMENTA1 INNER JOIN
                      dbo.INCREMENTABLE ON FACTEXPINCREMENTA1.IC_CODIGO = dbo.INCREMENTABLE.IC_CODIGO
WHERE     dbo.INCREMENTABLE.IC_PEDIMENTO = 'S' AND FACTEXPINCREMENTA1.FE_CODIGO=dbo.FACTEXP.FE_CODIGO),0) AS FE_SEGURO,
isnull((SELECT SUM(FACTEXPINCREMENTA1.FEI_VALOR)
FROM         dbo.FACTEXPINCREMENTA FACTEXPINCREMENTA1 INNER JOIN
                      dbo.INCREMENTABLE ON FACTEXPINCREMENTA1.IC_CODIGO = dbo.INCREMENTABLE.IC_CODIGO
WHERE     dbo.INCREMENTABLE.IC_PEDIMENTO = 'E' AND FACTEXPINCREMENTA1.FE_CODIGO=dbo.FACTEXP.FE_CODIGO),0) AS FE_EMBALAJE,
isnull((SELECT SUM(FACTEXPINCREMENTA1.FEI_VALOR)
FROM         dbo.FACTEXPINCREMENTA FACTEXPINCREMENTA1 INNER JOIN
                      dbo.INCREMENTABLE ON FACTEXPINCREMENTA1.IC_CODIGO = dbo.INCREMENTABLE.IC_CODIGO
WHERE     dbo.INCREMENTABLE.IC_PEDIMENTO = 'O' AND FACTEXPINCREMENTA1.FE_CODIGO=dbo.FACTEXP.FE_CODIGO),0) AS FE_OTROS
FROM dbo.FACTEXP








GO
