SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VTLCCOSTOTOTAL
with encryption as
SELECT     BST_PT, SUM(COSTOTOTAL) AS COSTOTOTAL, NFT_CODIGO
FROM         (SELECT     NAFTA.MA_CODIGO AS BST_PT, SUM(ISNULL(BST_MATNOORIG, 0) + ISNULL(BST_MATORIG, 0) + ISNULL(BST_EMPAQUE,0)) AS COSTOTOTAL, dbo.NAFTA.NFT_CODIGO
	       FROM         dbo.CLASIFICATLC INNER JOIN NAFTA ON CLASIFICATLC.NFT_CODIGO=NAFTA.NFT_CODIGO
	       GROUP BY NAFTA.MA_CODIGO, dbo.NAFTA.NFT_CODIGO
	       union
	       SELECT     NAFTA.MA_CODIGO AS BST_PT, CASE WHEN CF_ANALISISCOSTOMA='S' THEN MAESTRO.MA_COSTOVATLC ELSE VMAESTROCOST.MA_GRAV_GI + VMAESTROCOST.MA_GRAV_GI_MX + VMAESTROCOST.MA_GRAV_MO END AS COSTOTOTAL, NAFTA.NFT_CODIGO
	        FROM         CLASIFICATLC LEFT OUTER JOIN NAFTA
			 ON CLASIFICATLC.NFT_CODIGO=NAFTA.NFT_CODIGO  LEFT OUTER JOIN
		                      VMAESTROCOST ON NAFTA.MA_CODIGO = VMAESTROCOST.MA_CODIGO LEFT OUTER JOIN
		                      MAESTRO ON NAFTA.MA_CODIGO = MAESTRO.MA_CODIGO CROSS JOIN CONFIGURACION
	        GROUP BY NAFTA.MA_CODIGO, NAFTA.NFT_CODIGO, CASE WHEN CF_ANALISISCOSTOMA='S' THEN MAESTRO.MA_COSTOVATLC ELSE VMAESTROCOST.MA_GRAV_GI + VMAESTROCOST.MA_GRAV_GI_MX + VMAESTROCOST.MA_GRAV_MO END)  AS VTLCCOSTO
GROUP BY BST_PT, NFT_CODIGO

GO
