SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





























CREATE VIEW dbo.VFACTIMPREVISION
with encryption as
SELECT     dbo.FACTIMP.FI_FOLIO, dbo.TFACTURA.TF_NOMBRE, dbo.FACTIMP.FI_FECHA, dbo.FACTIMPDET.ME_CODIGO, 
                      dbo.FACTIMPDET.FID_INDICED, dbo.FACTIMPDET.MA_CODIGO, dbo.FACTIMPDET.FID_NOPARTE, dbo.FACTIMPDET.PA_CODIGO, dbo.PAIS.PA_CORTO, 
                      dbo.FACTIMPDET.MA_GENERICO, dbo.FACTIMPDET.ME_GEN, dbo.MAESTRO.MA_NOPARTE, dbo.FACTIMPDET.EQ_GEN, dbo.FACTIMPDET.AR_IMPMX, 
                      dbo.FACTIMPDET.ME_ARIMPMX, ARANCEL_1.AR_FRACCION, dbo.FACTIMPDET.EQ_IMPMX, dbo.FACTIMPDET.FID_DEF_TIP, 
                      dbo.FACTIMPDET.FID_POR_DEF, dbo.FACTIMPDET.FID_SEC_IMP, SECTOR_1.SE_CLAVE, dbo.FACTIMPDET.SPI_CODIGO, dbo.SPI.SPI_CLAVE, 
                      dbo.FACTIMPDET.AR_EXPFO, ARANCEL_1.AR_FRACCION AS AR_FRACCIONEXPFO, dbo.FACTIMPDET.FID_RATEEXPFO, 
                      dbo.FACTIMPDET.FID_COS_UNI, dbo.FACTIMPDET.FID_CANT_ST, dbo.FACTIMPDET.FID_COS_TOT, dbo.MEDIDA.ME_CORTO, dbo.FACTIMP.TF_CODIGO, 
                      dbo.FACTIMPDET.FID_NOMBRE, dbo.FACTIMP.FI_ESTATUS, dbo.FACTIMP.FI_CODIGO
FROM         dbo.MAESTRO RIGHT OUTER JOIN
                      dbo.FACTIMPDET LEFT OUTER JOIN
                      dbo.SECTOR SECTOR_1 ON dbo.FACTIMPDET.FID_SEC_IMP = SECTOR_1.SE_CODIGO LEFT OUTER JOIN
                      dbo.PAIS ON dbo.FACTIMPDET.PA_CODIGO = dbo.PAIS.PA_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.FACTIMPDET.ME_CODIGO = dbo.MEDIDA.ME_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ARANCEL_1 ON dbo.FACTIMPDET.AR_EXPFO = ARANCEL_1.AR_CODIGO LEFT OUTER JOIN
                      dbo.SPI ON dbo.FACTIMPDET.SPI_CODIGO = dbo.SPI.SPI_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ARANCEL_2 ON dbo.FACTIMPDET.AR_IMPMX = ARANCEL_2.AR_CODIGO ON 
                      dbo.MAESTRO.MA_CODIGO = dbo.FACTIMPDET.MA_GENERICO RIGHT OUTER JOIN
                      dbo.TFACTURA RIGHT OUTER JOIN
                      dbo.FACTIMP ON dbo.TFACTURA.TF_CODIGO = dbo.FACTIMP.TF_CODIGO ON 
                      dbo.FACTIMPDET.FI_CODIGO = dbo.FACTIMP.FI_CODIGO LEFT OUTER JOIN
                      dbo.AGENCIAPATENTE ON dbo.FACTIMP.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO
WHERE     (dbo.FACTIMP.FI_ESTATUS = 'S')
































GO
