SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VA16DETFINAL
with encryption as
SELECT     A16_CODIGO, MIN(MA_GENERICO) AS MA_GENERICO, CL_CODIGO, SUM(A16D_VALORTRANS) AS A16D_VALORTRANS, 
                      SUM(A16D_VALORADQ0) AS A16D_VALORADQ0, SUM(A16D_PROPORCION) AS A16D_PROPORCION
FROM         dbo.A16DET
GROUP BY A16_CODIGO, CL_CODIGO

GO
