SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VPEDEXPPAGAN
with encryption as
SELECT     TOP 100 PERCENT dbo.VPEDEXP.[PATENTE-FOLIO], dbo.VPEDEXP.PI_FEC_ENT, dbo.CLAVEPED.CP_CLAVE
FROM         dbo.VPEDEXP INNER JOIN
                      dbo.PEDIMPDET INNER JOIN
                      dbo.KARDESPED ON dbo.PEDIMPDET.PID_INDICED = dbo.KARDESPED.KAP_INDICED_PED INNER JOIN
                      dbo.FACTEXP ON dbo.KARDESPED.KAP_FACTRANS = dbo.FACTEXP.FE_CODIGO ON dbo.VPEDEXP.PI_CODIGO = dbo.FACTEXP.PI_CODIGO INNER JOIN
                      dbo.CLAVEPED ON dbo.VPEDEXP.CP_CODIGO = dbo.CLAVEPED.CP_CODIGO
WHERE     (dbo.PEDIMPDET.PID_POR_DEF > 0) AND (dbo.PEDIMPDET.PID_PAGACONTRIB = 'S')
GROUP BY dbo.VPEDEXP.[PATENTE-FOLIO], dbo.VPEDEXP.PI_FEC_ENT, dbo.CLAVEPED.CP_CLAVE
HAVING      (dbo.CLAVEPED.CP_CLAVE <> 'H1')
ORDER BY dbo.VPEDEXP.PI_FEC_ENT, dbo.VPEDEXP.[PATENTE-FOLIO]





GO
