SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





























































CREATE VIEW dbo.VDETDESCARGARI
with encryption as
SELECT     dbo.FACTEXP.FE_CODIGO, dbo.FACTEXP.FE_TIPO, dbo.BOM_DESCTEMP.FED_INDICED, dbo.FACTEXPDET.FED_RATEIMPFO, 
                      dbo.FACTEXPDET.AR_IMPFO, dbo.BOM_DESCTEMP.BST_ENTRAVIGOR, dbo.FACTEXPDET.MA_CODIGO, dbo.FACTEXPDET.FED_COS_UNI, 
                      dbo.FACTEXPDET.FED_CANT, dbo.FACTEXPDET.TI_CODIGO, MAESTRO_1.MA_TIP_ENS, dbo.BOM_DESCTEMP.BST_HIJO, 
                      dbo.BOM_DESCTEMP.BST_PT, SUM(dbo.BOM_DESCTEMP.BST_INCORPOR) AS BST_INCORPOR, dbo.BOM_DESCTEMP.FACTCONV, 
                      dbo.BOM_DESCTEMP.BST_DISCH, MAESTRO_1.PA_ORIGEN, MAESTRO_1.PA_PROCEDE, MAESTRO_1.MA_CONSTA, 
                      MAX(dbo.BOM_DESCTEMP.ME_GEN) AS ME_GEN, MAESTRO_1.SE_CODIGO, MAESTRO_2.MA_DEF_TIP, MAESTRO_2.TI_CODIGO AS TI_HIJO, 
                      dbo.FACTEXPDET.MA_GENERICO
FROM         dbo.MAESTRO MAESTRO_1 RIGHT OUTER JOIN
                      dbo.FACTEXPDET ON MAESTRO_1.MA_CODIGO = dbo.FACTEXPDET.MA_CODIGO RIGHT OUTER JOIN
                      dbo.BOM_DESCTEMP LEFT OUTER JOIN
                      dbo.MAESTRO MAESTRO_2 ON dbo.BOM_DESCTEMP.BST_HIJO = MAESTRO_2.MA_CODIGO ON 
                      dbo.FACTEXPDET.FED_INDICED = dbo.BOM_DESCTEMP.FED_INDICED RIGHT OUTER JOIN
                      dbo.FACTEXP ON dbo.BOM_DESCTEMP.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
GROUP BY dbo.FACTEXP.FE_CODIGO, dbo.BOM_DESCTEMP.FED_INDICED, dbo.FACTEXPDET.FED_RATEIMPFO, dbo.FACTEXPDET.AR_IMPFO, 
                      dbo.BOM_DESCTEMP.BST_ENTRAVIGOR, dbo.FACTEXPDET.MA_CODIGO, dbo.FACTEXPDET.FED_COS_UNI, dbo.FACTEXPDET.TI_CODIGO, 
                      MAESTRO_1.MA_TIP_ENS, dbo.BOM_DESCTEMP.BST_HIJO, dbo.BOM_DESCTEMP.BST_PT, dbo.BOM_DESCTEMP.FACTCONV, 
                      dbo.BOM_DESCTEMP.BST_DISCH, MAESTRO_1.PA_ORIGEN, MAESTRO_1.PA_PROCEDE, MAESTRO_1.MA_CONSTA, dbo.FACTEXP.FE_TIPO, 
                      dbo.FACTEXPDET.FED_CANT, MAESTRO_1.SE_CODIGO, MAESTRO_2.MA_DEF_TIP, MAESTRO_2.TI_CODIGO, 
                      dbo.FACTEXPDET.MA_GENERICO
HAVING      (dbo.BOM_DESCTEMP.BST_DISCH = 'S') AND (dbo.FACTEXPDET.FED_CANT > 0)


































































GO
