SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW dbo.v1
AS
SELECT     dbo.KARDESALMACEN.KAA_FECHADESC, dbo.ENTSALALM.EN_FOLIO, dbo.ENTSALALMDET.END_LOTE, dbo.ENTSALALMDET.OT_FOLIO, 
                      dbo.ENTSALALM.EN_FECHA
FROM         dbo.KARDESALMACEN INNER JOIN
                      dbo.ENTSALALMDET ON dbo.KARDESALMACEN.KAA_INDICED_PED = dbo.ENTSALALMDET.END_INDICED LEFT OUTER JOIN
                      dbo.ENTSALALM ON dbo.ENTSALALMDET.EN_CODIGO = dbo.ENTSALALM.EN_CODIGO
WHERE     (dbo.KARDESALMACEN.KAA_INDICED_FACT = 347)



GO
