SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VEXHIBIT_B_BASECOM
with encryption as
SELECT COSTSUBPER.CS_CODIGO, ENTRYSUM.ET_ENTRY_NO, 
    FACTEXP.FE_CODIGO, FACTEXP.FE_FECHA, 
    ENTRYSUM.ET_FEC_ENTRYS, ENTRYSUM.ET_CODIGO, 
    VENTRYSUMDET.AR_CODIGO, COMMINVDET.PA_CODIGO, 
    ENTRYSUMARA.ETA_DLLS_MPF, 
    VENTRYSUMDET.ETD_COS_TOT, VENTRYSUMDET.ETD_CANT, 
    VENTRYSUMDET.FED_INDICED, 
    COMMINVDET.IVD_NOPARTE AS FED_NOPARTE, 
    COMMINVDET.MA_CODIGO, 
    SUM(VENTRYSUMDET.ETD_GRAV_MAT) AS ETD_GRAV_MAT, 
    SUM(VENTRYSUMDET.ETD_NG_MAT) AS ETD_NG_MAT, 
    SUM(VENTRYSUMDET.ETD_GRAV_VA) AS ETD_GRAV_VA, 
    SUM(VENTRYSUMDET.ETD_NG_VA) AS ETD_NG_VA, 
    SUM(VENTRYSUMDET.ETD_GRAV_VA + VENTRYSUMDET.ETD_GRAV_MAT)
     AS ETD_TOT_GRAV, 
    SUM(VENTRYSUMDET.ETD_NG_VA + VENTRYSUMDET.ETD_NG_MAT)
     AS ETD_TOT_NG, 
    SUM(VENTRYSUMDET.ETD_GRAV_VA + VENTRYSUMDET.ETD_GRAV_MAT
     * ENTRYSUMARA.ETA_RATE) AS ETD_DUT_PAG, 
    ENTRYSUMARA.MA_NAFTA, 
    SUM((VENTRYSUMDET.ETD_GRAV_VA + VENTRYSUMDET.ETD_GRAV_MAT)
     * VENTRYSUMDET.ETD_CANT) AS TotGrav, 
    SUM(VENTRYSUMDET.ETD_NG_MAT * VENTRYSUMDET.ETD_CANT)
     AS TotNoGrav, MAESTRO.TI_CODIGO, 
    SUM(VENTRYSUMDET.ETD_GRAV_VA + VENTRYSUMDET.ETD_GRAV_MAT
     + VENTRYSUMDET.ETD_NG_MAT) AS ETD_COS_UNI, 
    FACTEXP.TN_CODIGO, 
    ENTRYSUMARA.ETA_RATE AS ETD_RATE, 
    ENTRYSUMARA.SPI_CODIGO, MAX(FACTEXP.PU_ENTRADA) 
    AS PU_ENTRADA
FROM FACTEXP RIGHT OUTER JOIN
    COMMINV ON 
    FACTEXP.FE_CODIGO = COMMINV.FE_CODIGO RIGHT OUTER JOIN
    ENTRYSUM RIGHT OUTER JOIN
    COSTSUBPER ON 
    ENTRYSUM.ET_FEC_ENTRYS >= COSTSUBPER.CS_FECHAINI AND
     ENTRYSUM.ET_FEC_ENTRYS <= COSTSUBPER.CS_FECHAFIN LEFT
     OUTER JOIN
    VENTRYSUMDET LEFT OUTER JOIN
    ENTRYSUMARA ON 
    VENTRYSUMDET.ETA_CODIGO = ENTRYSUMARA.ETA_CODIGO ON
     ENTRYSUM.ET_CODIGO = VENTRYSUMDET.ET_CODIGO LEFT OUTER
     JOIN
    COMMINVDET LEFT OUTER JOIN
    MAESTRO ON 
    COMMINVDET.MA_CODIGO = MAESTRO.MA_CODIGO ON 
    VENTRYSUMDET.FED_INDICED = COMMINVDET.FED_INDICED ON
     COMMINV.IV_CODIGO = COMMINVDET.IV_CODIGO
GROUP BY ENTRYSUM.ET_ENTRY_NO, 
    ENTRYSUM.ET_FEC_ENTRYS, ENTRYSUM.ET_CODIGO, 
    COSTSUBPER.CS_CODIGO, VENTRYSUMDET.AR_CODIGO, 
    COMMINVDET.PA_CODIGO, ENTRYSUMARA.ETA_DLLS_MPF, 
    VENTRYSUMDET.ETD_COS_TOT, VENTRYSUMDET.ETD_CANT, 
    FACTEXP.FE_CODIGO, FACTEXP.FE_FECHA, 
    VENTRYSUMDET.FED_INDICED, COMMINVDET.IVD_NOPARTE, 
    COMMINVDET.MA_CODIGO, MAESTRO.TI_CODIGO, 
    FACTEXP.TN_CODIGO, ENTRYSUMARA.SPI_CODIGO, 
    ENTRYSUMARA.MA_NAFTA, ENTRYSUMARA.ETA_RATE
HAVING (ENTRYSUM.ET_CODIGO IS NOT NULL) AND 
    (FACTEXP.FE_CODIGO IS NOT NULL) AND 
    (FACTEXP.TN_CODIGO = 2 OR (FACTEXP.TN_CODIGO = 6) OR  (FACTEXP.TN_CODIGO = 7) OR
    FACTEXP.TN_CODIGO = 5) AND 
    (VENTRYSUMDET.FED_INDICED IS NOT NULL) AND 
    (COMMINVDET.PA_CODIGO IN (SELECT CF_PAIS_MX FROM CONFIGURACION)) OR
    (COMMINVDET.PA_CODIGO IN (SELECT CF_PAIS_USA FROM CONFIGURACION))



GO
