SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






















CREATE VIEW dbo.VDECANUALIMPUESTOXPAGAR
with encryption as
SELECT     dbo.DECANUALNVA.DAN_CODIGO, SUM((dbo.PEDIMPDET.PID_CAN_GEN * dbo.PEDIMPDET.PID_COS_UNIGEN * dbo.VPEDIMP.PI_TIP_CAM) 
                      * (dbo.PEDIMPDET.PID_POR_DEF / 100)) AS IMPUESTOXPAGAR, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO
FROM         dbo.VPEDIMP INNER JOIN
                      dbo.DECANUALNVA ON dbo.VPEDIMP.PI_FEC_ENT >= dbo.DECANUALNVA.DAN_INICIO AND 
                      dbo.VPEDIMP.PI_FEC_ENT <= dbo.DECANUALNVA.DAN_FINAL LEFT OUTER JOIN
                      dbo.PEDIMPDET ON dbo.VPEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.PEDIMPDET.MA_CODIGO = dbo.MAESTRO.MA_CODIGO
WHERE   (dbo.PEDIMPDET.PID_IMPRIMIR='S') AND (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'IT' AND dbo.VPEDIMP.PI_ESTATUS <> 'R') 
		AND (dbo.PEDIMPDET.PID_PAGACONTRIB ='S') AND (dbo.PEDIMPDET.PID_POR_DEF > 0) 
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO
UNION
SELECT     dbo.DECANUALNVA.DAN_CODIGO, SUM((dbo.PEDIMPDET.PID_CAN_GEN * dbo.PEDIMPDET.PID_COS_UNIGEN * dbo.VPEDIMP.PI_TIP_CAM) 
                      * (dbo.PEDIMPDET.PID_POR_DEF / 100)) AS IMPUESTOXPAGAR, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO
FROM         dbo.VPEDIMP INNER JOIN
                      dbo.DECANUALNVA ON dbo.VPEDIMP.PI_FEC_ENT >= dbo.DECANUALNVA.DAN_INICIO AND 
                      dbo.VPEDIMP.PI_FEC_ENT <= dbo.DECANUALNVA.DAN_FINAL LEFT OUTER JOIN
                      dbo.PEDIMPDET ON dbo.VPEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.PEDIMPDET.MA_CODIGO = dbo.MAESTRO.MA_CODIGO
WHERE   (dbo.PEDIMPDET.PID_IMPRIMIR='S') AND  (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'RE' AND dbo.VPEDIMP.CP_RECTIFICA
		 IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO = 'IT'))
		AND (dbo.PEDIMPDET.PID_PAGACONTRIB ='S') AND (dbo.PEDIMPDET.PID_POR_DEF > 0) 
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO
UNION
SELECT     dbo.DECANUALNVA.DAN_CODIGO, SUM((dbo.PEDIMPDET.PID_CAN_GEN * dbo.PEDIMPDET.PID_COS_UNIGEN * dbo.VPEDIMP.PI_TIP_CAM) 
                      * (dbo.PEDIMPDET.PID_POR_DEF / 100)) AS IMPUESTOXPAGAR, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO
FROM         dbo.VPEDIMP INNER JOIN
                      dbo.DECANUALNVA ON dbo.VPEDIMP.PI_FEC_ENT >= dbo.DECANUALNVA.DAN_INICIO AND 
                      dbo.VPEDIMP.PI_FEC_ENT <= dbo.DECANUALNVA.DAN_FINAL LEFT OUTER JOIN
                      dbo.PEDIMPDET ON dbo.VPEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.PEDIMPDET.MA_CODIGO = dbo.MAESTRO.MA_CODIGO
WHERE   (dbo.PEDIMPDET.PID_IMPRIMIR='S') AND (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'IV' and dbo.MAESTRO.MA_SERVICIO='S')
		AND (dbo.PEDIMPDET.PID_PAGACONTRIB ='S') AND (dbo.PEDIMPDET.PID_POR_DEF > 0) 
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO
UNION
SELECT     dbo.DECANUALNVA.DAN_CODIGO, SUM((dbo.PEDIMPDET.PID_CAN_GEN * dbo.PEDIMPDET.PID_COS_UNIGEN * dbo.VPEDIMP.PI_TIP_CAM) 
                      * (dbo.PEDIMPDET.PID_POR_DEF / 100)) AS IMPUESTOXPAGAR, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO
FROM         dbo.VPEDIMP INNER JOIN
                      dbo.DECANUALNVA ON dbo.VPEDIMP.PI_FEC_ENT >= dbo.DECANUALNVA.DAN_INICIO AND 
                      dbo.VPEDIMP.PI_FEC_ENT <= dbo.DECANUALNVA.DAN_FINAL LEFT OUTER JOIN
                      dbo.PEDIMPDET ON dbo.VPEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.PEDIMPDET.MA_CODIGO = dbo.MAESTRO.MA_CODIGO
WHERE   (dbo.PEDIMPDET.PID_IMPRIMIR='S') AND dbo.CONFIGURACLAVEPED.CCP_TIPO = 'RE' AND dbo.VPEDIMP.CP_RECTIFICA
		 IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO = 'IV') AND  dbo.MAESTRO.MA_SERVICIO='S' 
		AND (dbo.PEDIMPDET.PID_PAGACONTRIB ='S') AND (dbo.PEDIMPDET.PID_POR_DEF > 0) 
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO





















GO
