SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO































CREATE VIEW dbo.vdetalles_facturaexpagru
with encryption as
SELECT     dbo.CONFIGURACION.CF_PAIS_USA, dbo.CONFIGURATIPO.CFT_TIPO, dbo.CONFIGURATEMBARQUE.CFQ_TIPO, dbo.FACTEXPDET.EQ_GEN, 
                      dbo.FACTEXPDET.FED_COS_UNI, dbo.FACTEXPDET.FED_NAFTA, dbo.FACTEXPDET.FED_NG_EMP, dbo.FACTEXPDET.PA_CODIGO
FROM         dbo.FACTEXPAGRU LEFT OUTER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPAGRU.FEA_CODIGO = dbo.FACTEXP.FE_FACTAGRU LEFT OUTER JOIN
                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACION ON dbo.FACTEXP.CL_EXP = dbo.CONFIGURACION.EM_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.FACTEXPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATEMBARQUE ON dbo.FACTEXPAGRU.TQ_CODIGO = dbo.CONFIGURATEMBARQUE.TQ_CODIGO
WHERE     (dbo.FACTEXPAGRU.FEA_CODIGO = '63')































GO
