SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO








CREATE VIEW dbo.VKARDESPED2
with encryption as
SELECT     dbo.KARDESPED.KAP_CODIGO, dbo.KARDESPED.KAP_FACTRANS, dbo.PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, 
                      dbo.KARDESPED.KAP_INDICED_FACT, dbo.KARDESPED.KAP_INDICED_PED, dbo.PEDIMP.PI_TIPO AS KAP_TIPO_PED, 
                      dbo.FACTEXP.FE_FECHADESCARGA AS KAP_FECHADESC, dbo.PEDIMP.PI_FEC_ENT AS KAP_FECHAPED, dbo.KARDESPED.MA_HIJO, 
                      dbo.PEDIMPDET.TI_CODIGO AS TI_HIJO, dbo.PEDIMPDET.ME_GENERICO AS ME_HIJO, 
                      dbo.KARDESPED.KAP_ESTATUS, dbo.PEDIMPDET.EQ_GENERICO AS EQ_GENHIJO, dbo.KARDESPED.KAP_CANTDESC,
                       VKAP_SALDO_PED.KAP_SALDO_PED, dbo.KARDESPED.KAP_CantTotADescargar, dbo.KARDESPED.KAP_Saldo_FED, 
                      dbo.KARDESPED.KAP_PADRESUST, dbo.PEDIMPDET.PA_ORIGEN, dbo.PEDIMPDET.PA_PROCEDE, 
                      dbo.PEDIMPDET.PID_POR_DEF AS KAP_POR_DEF, dbo.PEDIMPDET.PID_DEF_TIP AS KAP_DEF_TIP, 
                      dbo.PEDIMPDET.PID_SEC_IMP AS KAP_SEC_IMP, dbo.PEDIMPDET.SPI_CODIGO, dbo.PEDIMPDET.AR_IMPMX,
		'KAP_COS_UNI' =case when dbo.PEDIMP.PI_TIP_CAM is null or dbo.PEDIMP.PI_TIP_CAM = 0 then 0 else
	     isnull((isnull(dbo.PEDIMPDET.PID_COS_UNIADU,0)/ISNULL(dbo.PEDIMP.PI_TIP_CAM,1)),0) end
FROM         dbo.PEDIMP RIGHT OUTER JOIN
                      dbo.PEDIMPDET ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO RIGHT OUTER JOIN
                      dbo.KARDESPED ON dbo.PEDIMPDET.PID_INDICED = dbo.KARDESPED.KAP_INDICED_PED LEFT OUTER JOIN
	   dbo.FACTEXP ON FACTEXP.FE_CODIGO=dbo.KARDESPED.KAP_FACTRANS
	LEFT OUTER JOIN VKAP_SALDO_PED ON dbo.KARDESPED.KAP_CODIGO=VKAP_SALDO_PED.KAP_CODIGO
WHERE     (PEDIMPDET.PA_ORIGEN <>
                          (SELECT     CF_PAIS_MX
                            FROM          CONFIGURACION)) AND (PEDIMPDET.PID_DEF_TIP <> 'P') AND (PEDIMP.PI_FEC_PAG >= CONVERT(DATETIME, 
                      '2000-11-20 00:00:00', 102)) OR
                      (PEDIMPDET.PA_ORIGEN <>
                          (SELECT     CF_PAIS_CA
                            FROM          CONFIGURACION)) AND (PEDIMPDET.PID_DEF_TIP <> 'P') AND (PEDIMP.PI_FEC_PAG >= CONVERT(DATETIME, 
                      '2000-11-20 00:00:00', 102)) OR
                      (PEDIMPDET.PA_ORIGEN <>
                          (SELECT     CF_PAIS_USA
                            FROM          CONFIGURACION)) AND (PEDIMPDET.PID_DEF_TIP <> 'P') AND (PEDIMP.PI_FEC_PAG >= CONVERT(DATETIME, 
                      '2000-11-20 00:00:00', 102))









GO
