SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO














CREATE VIEW dbo.VPEDIMPVENCIMIENTO
with encryption as
SELECT    PEDIMP.PI_CODIGO,  AGENCIAPATENTE.AGT_PATENTE collate database_default + '-' + PEDIMP.PI_FOLIO collate database_default AS PI_FOLIO, MIN(PEDIMP.PI_FEC_PAG) 'PI_FEC_PAG', MIN(CLAVEPED.CP_CLAVE) 'CP_CLAVE',  
                     MIN(PIDescarga.PID_FECHAVENCE) AS FECHAVENCIMIENTO, PEDIMPDET.PID_NOPARTE,
	'BUSQUEDA'=CASE WHEN PEDIMPDET.MA_CODIGO IN (SELECT BST_HIJO FROM BOM_STRUCT WHERE BST_DISCH='S' GROUP BY BST_HIJO) 
	THEN 'No. Parte Incluido en BOM' ELSE (CASE WHEN PEDIMPDET.MA_GENERICO IN (SELECT MAESTRO.MA_GENERICO FROM BOM_STRUCT INNER JOIN MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO
									GROUP BY MAESTRO.MA_GENERICO HAVING MAESTRO.MA_GENERICO <> 0) THEN 'G.Generico No incluido en BOM' ELSE 'Ni Grupo ni No. Parte incluidos en BOM' END) END
FROM         CLAVEPED RIGHT OUTER JOIN
                      PEDIMP ON CLAVEPED.CP_CODIGO = PEDIMP.CP_CODIGO LEFT OUTER JOIN
                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO LEFT OUTER JOIN
                      AGENCIAPATENTE ON PEDIMP.AGT_CODIGO = AGENCIAPATENTE.AGT_CODIGO LEFT OUTER JOIN PIDescarga
	ON PIDescarga.PID_INDICED= PEDIMPDET.PID_INDICED
WHERE PIDescarga.PID_FECHAVENCE IS NOT NULL AND (PEDIMP.PI_MOVIMIENTO = 'E') AND PIDescarga.PID_SALDOGEN >0
AND PEDIMP.PI_ESTATUS<>'R'
GROUP BY AGENCIAPATENTE.AGT_PATENTE collate database_default + '-' + PEDIMP.PI_FOLIO collate database_default, PEDIMPDET.PID_NOPARTE, PEDIMPDET.MA_CODIGO, PEDIMPDET.MA_GENERICO, PEDIMP.PI_CODIGO
HAVING  (MIN(PIDescarga.PID_FECHAVENCE) <= CONVERT(datetime, FLOOR(CONVERT(decimal(38,6), GETDATE()-isnull((select CF_DIAS_AVISO from configuracion),0)))))






















GO
