SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






















CREATE VIEW dbo.VREPANUALMDONACACTFIJ
with encryption as
SELECT     dbo.DECANUALNVA.DAN_CODIGO, dbo.PEDIMP.PI_CODIGO, ISNULL(dbo.PEDIMPDET.PID_CTOT_DLS, 0) * dbo.PEDIMP.PI_TIP_CAM AS VALOR, 
                      ISNULL(dbo.PEDIMPDET.PID_CTOT_DLS, 0) AS PID_CTOT_DLS, dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.MA_GENERICO, 
                      dbo.PEDIMPDET.AR_IMPMX
FROM         dbo.PEDIMP INNER JOIN
                      dbo.DECANUALNVA ON dbo.PEDIMP.PI_FEC_ENT >= dbo.DECANUALNVA.DAN_INICIO AND 
                      dbo.PEDIMP.PI_FEC_ENT <= dbo.DECANUALNVA.DAN_FINAL INNER JOIN
                      dbo.PEDIMPDET ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO INNER JOIN
                      dbo.CONFIGURATIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.TIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.TIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
WHERE    (dbo.PEDIMPDET.PID_IMPRIMIR='S') and  (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'CN') AND (dbo.PEDIMP.PI_MOVIMIENTO = 'E') 
		AND (dbo.TIPO.TI_CATEGM = '3' OR dbo.TIPO.TI_CATEGM = '4')





















GO
