SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE VIEW dbo.VPERMISODETAR
with encryption as
SELECT     PED_INDICED, PE_CODIGO, PED_REGISTROTIPO, MA_GENERICO, MA_NOPARTE, PED_OBSERVA, PED_NOMBRE, TI_CODIGO, ME_COM, 
                      PED_ID_SUBORD, PED_CONSECUTIVO, PED_CANT, SE_CODIGO, PED_COSTO, PED_COSTOT, PED_ENUSO, PED_SALDO, 
                      PED_ENUSOCOSTOT, PED_SALDOCOSTOT, PED_CAS_NUM, PA_CODIGO,
	AR_IMPMX=CASE WHEN TI_CODIGO in (select ti_codigo from configuratipo where cft_tipo in ('P','S')) THEN AR_EXPMX ELSE AR_IMPMX END
FROM         dbo.PERMISODET





GO
