SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VFACTEXPPEDBase
with encryption as
SELECT     dbo.KARDESPED.KAP_FACTRANS, dbo.KARDESPED.KAP_INDICED_FACT, dbo.VPEDIMP.PI_FEC_ENT AS KAP_FECHAPED, dbo.VPEDIMP.AGT_CODIGO, 
                      dbo.PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, dbo.VPEDIMP.AD_DES, dbo.KARDESPED.MA_HIJO, dbo.PEDIMPDET.ME_GENERICO AS ME_HIJO, 
                      SUM(dbo.KARDESPED.KAP_CANTDESC) AS KAP_CANTDESC, dbo.VKARDESPED1.CL_RFC, MIN(dbo.KARDESPED.KAP_CODIGO) AS FEP_INDICEP, 
                      dbo.FACTEXPDET.MA_CODIGO AS MA_FACT_TRANS, dbo.FACTEXP.FE_TIPO AS KAP_TIPO_FACTRANS, dbo.VPEDIMP.PI_TIPO AS KAP_TIPO_PED, 
                      dbo.PEDIMPDET.PA_ORIGEN, dbo.VPI_TIPO.CB_LOOKUP AS FEP_TIPO, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.PEDIMPDET.PID_DEF_TIP, dbo.PEDIMPDET.PID_POR_DEF, 
                      dbo.PEDIMPDET.PID_COS_UNI AS PID_COS_UNI, SUM(dbo.KARDESPED.KAP_CANTDESC / dbo.PEDIMPDET.EQ_GENERICO) AS KAP_CANTDESCHIJO, 
                      dbo.PEDIMPDET.ME_CODIGO, dbo.PEDIMPDET.SPI_CODIGO, 
                      'FED_TIP_PED' = CASE CONFIGURACLAVEPED.CCP_TIPO WHEN 'IT' THEN 'Temporal' WHEN 'IA' THEN 'Temporal' WHEN 'RE' THEN 'Temporal' WHEN 'IV'
                       THEN 'Temporal' WHEN 'IR' THEN 'Temporal' WHEN 'CS' THEN 'Temporal' WHEN 'ID' THEN 'Definitivo' END,
	        'CODIGOPEDEXP'=CASE WHEN dbo.FACTEXP.PI_RECTIFICA=-1 THEN dbo.FACTEXP.PI_CODIGO ELSE dbo.FACTEXP.PI_RECTIFICA END,
	        'PEDEXPFOLIO'=CASE WHEN dbo.FACTEXP.PI_RECTIFICA=-1 THEN dbo.VPEDEXP.[PATENTE-FOLIO] ELSE VPEDEXPR1.[PATENTE-FOLIO] END
FROM         dbo.VPI_TIPO RIGHT OUTER JOIN
                      dbo.VPEDIMP ON dbo.VPI_TIPO.CB_KEYFIELD = dbo.VPEDIMP.PI_TIPO RIGHT OUTER JOIN
                      dbo.PEDIMPDET ON dbo.VPEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO RIGHT OUTER JOIN
                      dbo.FACTEXPDET RIGHT OUTER JOIN
                      dbo.KARDESPED ON dbo.FACTEXPDET.FED_INDICED = dbo.KARDESPED.KAP_INDICED_FACT INNER JOIN
                      dbo.FACTEXP ON dbo.KARDESPED.KAP_FACTRANS = dbo.FACTEXP.FE_CODIGO ON 
                      dbo.PEDIMPDET.PID_INDICED = dbo.KARDESPED.KAP_INDICED_PED LEFT OUTER JOIN
                      dbo.VKARDESPED1 ON dbo.KARDESPED.KAP_CODIGO = dbo.VKARDESPED1.KAP_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO LEFT OUTER JOIN
 	         dbo.VPEDEXP ON dbo.FACTEXP.PI_CODIGO = dbo.VPEDEXP.PI_CODIGO LEFT OUTER JOIN
	         dbo.VPEDEXP VPEDEXPR1 ON dbo.FACTEXP.PI_RECTIFICA = VPEDEXPR1.PI_CODIGO 
GROUP BY dbo.KARDESPED.KAP_FACTRANS, dbo.KARDESPED.KAP_INDICED_FACT, dbo.FACTEXP.FE_TIPO, dbo.VPEDIMP.PI_FEC_ENT, 
                      dbo.VPEDIMP.AGT_CODIGO, dbo.PEDIMPDET.PI_CODIGO, dbo.VPEDIMP.AD_DES, dbo.CONFIGURACLAVEPED.CCP_TIPO, dbo.VPEDIMP.PI_TIPO, 
                      dbo.KARDESPED.MA_HIJO, dbo.PEDIMPDET.ME_GENERICO, dbo.VKARDESPED1.CL_RFC, dbo.FACTEXPDET.MA_CODIGO, dbo.VPI_TIPO.CB_LOOKUP, 
                      dbo.PEDIMPDET.PA_ORIGEN, dbo.VPEDIMP.[PATENTE-FOLIO], dbo.PEDIMPDET.PID_COS_UNI, dbo.PEDIMPDET.EQ_GENERICO, dbo.PEDIMPDET.PID_POR_DEF,
                      dbo.PEDIMPDET.ME_CODIGO, dbo.PEDIMPDET.PID_DEF_TIP, dbo.PEDIMPDET.SPI_CODIGO, dbo.FACTEXP.PI_CODIGO, dbo.FACTEXP.PI_RECTIFICA,
	        dbo.VPEDEXP.[PATENTE-FOLIO], VPEDEXPR1.[PATENTE-FOLIO]
HAVING      (dbo.PEDIMPDET.PI_CODIGO IS NOT NULL)



GO
