SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VTLCCOSTOTOTAL_COSTOMA
with encryption as
SELECT     BST_PT, SUM(COSTOTOTAL) AS COSTOTOTAL, NFT_CODIGO
FROM         (SELECT     NAFTA.MA_CODIGO AS BST_PT, SUM(ISNULL(BST_MATNOORIG, 0) + ISNULL(BST_MATORIG, 0) + ISNULL(BST_EMPAQUE,0)) AS COSTOTOTAL, dbo.NAFTA.NFT_CODIGO
	       FROM         dbo.CLASIFICATLC INNER JOIN NAFTA ON CLASIFICATLC.NFT_CODIGO=NAFTA.NFT_CODIGO
	       GROUP BY NAFTA.MA_CODIGO, dbo.NAFTA.NFT_CODIGO
	       union
	       SELECT     NAFTA.MA_CODIGO AS BST_PT, ISNULL((SELECT MA_COSTOVATLC FROM MAESTRO WHERE MA_CODIGO=NAFTA.MA_CODIGO),0) AS COSTOTOTAL, NAFTA.NFT_CODIGO
	        FROM         CLASIFICATLC LEFT OUTER JOIN NAFTA
			 ON CLASIFICATLC.NFT_CODIGO=NAFTA.NFT_CODIGO  INNER JOIN
		                      VMAESTROCOST ON NAFTA.MA_CODIGO = VMAESTROCOST.MA_CODIGO
	        GROUP BY NAFTA.MA_CODIGO, NAFTA.NFT_CODIGO, VMAESTROCOST.MA_GRAV_GI + VMAESTROCOST.MA_GRAV_GI_MX + VMAESTROCOST.MA_GRAV_MO)  AS VTLCCOSTO
GROUP BY BST_PT, NFT_CODIGO

GO
