SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO







CREATE VIEW dbo.VR1ANTERIOR1
with encryption as
SELECT     AGENCIAPATENTE.AGT_PATENTE, PEDIMPR1HIST.R1H_PEDIMENTOR1ANT ,
                          (SELECT     CP_CODIGO
                            FROM          CLAVEPED
                            WHERE      CP_CLAVE = 'R1') AS CP_CODIGO, PEDIMPR1HIST.R1H_FECHAPAGO,
PEDIMPR1HIST.PI_CODIGO
FROM         PEDIMPR1HIST LEFT OUTER JOIN
                      AGENCIAPATENTE ON PEDIMPR1HIST.AGT_R1ANT = AGENCIAPATENTE.AGT_CODIGO
WHERE PEDIMPR1HIST.R1H_FECHAPAGO IN
                          (SELECT     MAX(PEDIMPR1HIST_1.R1H_FECHAPAGO)
                            FROM          PEDIMPR1HIST PEDIMPR1HIST_1
                            WHERE      PEDIMPR1HIST_1.PI_CODIGO = PEDIMPR1HIST.PI_CODIGO AND
				PEDIMPR1HIST_1.R1H_FECHAPAGO NOT IN (SELECT MAX(PEDIMPR1HIST_2.R1H_FECHAPAGO)
                            FROM          PEDIMPR1HIST PEDIMPR1HIST_2
                            WHERE      PEDIMPR1HIST_2.PI_CODIGO = PEDIMPR1HIST.PI_CODIGO)) 
UNION
SELECT     AGENCIAPATENTE.AGT_PATENTE, PEDIMP.PI_FOLIO, PEDIMP.CP_CODIGO,  PEDIMP.PI_FEC_PAG, PEDIMPRECT.PI_NO_RECT
FROM         AGENCIAPATENTE INNER JOIN
                      PEDIMP ON AGENCIAPATENTE.AGT_CODIGO = PEDIMP.AGT_CODIGO INNER JOIN
                      PEDIMPRECT ON PEDIMP.PI_CODIGO = PEDIMPRECT.PI_CODIGO







GO
