SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE VIEW dbo.VENTRYSUMARA
with encryption as

SELECT     VENTRYSUMDET.ET_CODIGO, VENTRYSUMDET.FE_CODIGO, VENTRYSUMDET.AR_CODIGO, 'A' AS ETA_TIPOIMPUESTO, VENTRYSUMDET.ETD_RATE, VENTRYSUMDET.ETD_NAFTA,
	(Select ARE_ADACVD_CASE from ARANCELENTRY where AR_CODIGO = VENTRYSUMDET.AR_CODIGO AND ARANCELENTRY.PA_CODIGO=VENTRYSUMDET.PA_CODIGO) AS ETA_ADV_CDVCASE, 0 AS ETA_CHGS,
	(Select ARE_ADACVD_RATE from ARANCELENTRY where AR_CODIGO = VENTRYSUMDET.AR_CODIGO AND ARANCELENTRY.PA_CODIGO=VENTRYSUMDET.PA_CODIGO) AS ETA_ADV_CDVRATE, 'N' AS ETA_RELATIONSHIP,
	VENTRYSUMDET.ETD_CANT AS ETA_CANT, VENTRYSUMDET.ETD_CANT * VENTRYSUMDET.EQ_IMPFO AS ETA_CANTAR, VENTRYSUMDET.ETD_GRAV_VA AS ETA_GRAV_VA,
	VENTRYSUMDET.ETD_GRAV_MAT AS ETA_GRAV_MAT, VENTRYSUMDET.ETD_NG_MAT AS ETA_NG_MAT, VENTRYSUMDET.ETD_NG_EMP AS ETA_NG_EMP,
	VENTRYSUMDET.ETD_NG_VA AS ETA_NG_VA, VENTRYSUMDET.ETD_COS_TOT AS ETA_COS_TOT,
	(Select ARE_IRC_RATE from ARANCELENTRY where AR_CODIGO = VENTRYSUMDET.AR_CODIGO AND ARANCELENTRY.PA_CODIGO=VENTRYSUMDET.PA_CODIGO) AS ETA_IRC, 
	(Select ARE_VISA from ARANCELENTRY where AR_CODIGO = VENTRYSUMDET.AR_CODIGO AND ARANCELENTRY.PA_CODIGO=VENTRYSUMDET.PA_CODIGO) AS ETA_VISA,
        (Select ARE_IRC_RATE from ARANCELENTRY where AR_CODIGO = VENTRYSUMDET.AR_CODIGO AND ARANCELENTRY.PA_CODIGO=VENTRYSUMDET.PA_CODIGO)/100 * VENTRYSUMDET.ETD_COS_TOT AS ETA_DLLS_IRC,
        (Select ARE_VISA from ARANCELENTRY where AR_CODIGO = VENTRYSUMDET.AR_CODIGO AND ARANCELENTRY.PA_CODIGO=VENTRYSUMDET.PA_CODIGO)/100 * VENTRYSUMDET.ETD_COS_TOT AS ETA_DLLS_VISA,
	(VENTRYSUMDET.ETD_GRAV_MAT + VENTRYSUMDET.ETD_GRAV_VA)*VENTRYSUMDET.ETD_RATE/100 AS ETA_DLLS_RATE,
	(SELECT ME_CODIGO FROM ARANCEL WHERE AR_CODIGO =VENTRYSUMDET.AR_CODIGO) AS ME_CODIGO,
	VENTRYSUMDET.PA_CODIGO, VENTRYSUMDET.AR_ORIG,
	VENTRYSUMDET.FED_INDICED, VENTRYSUMDET.MA_CODIGO, VENTRYSUMDET.ETD_NAME,
                      VENTRYSUMDET.AR_NG_EMP, VENTRYSUMDET.ETD_RETRABAJO, CONFIGURATIPO.CFT_TIPO, ARANCEL.AR_FRACCION,
                      ARANCEL_1.AR_FRACCION AS AR_FRACCIONORIG, ARANCEL_2.AR_FRACCION AS AR_FRACCIONEMP
FROM         dbo.VENTRYSUMDET LEFT OUTER JOIN
                      dbo.ARANCEL ARANCEL_2 ON dbo.VENTRYSUMDET.AR_NG_EMP = ARANCEL_2.AR_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ARANCEL_1 ON dbo.VENTRYSUMDET.AR_ORIG = ARANCEL_1.AR_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ON dbo.VENTRYSUMDET.AR_CODIGO = dbo.ARANCEL.AR_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.VENTRYSUMDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO


GO
