SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO









CREATE VIEW dbo.VDATOSPEDEXPCOMP
with encryption as
SELECT dbo.VDATOSPEDEXPPAGOUSA.PIB_INDICEB, dbo.VDATOSPEDEXPPAGOUSA.FED_INDICED, dbo.VDATOSPEDEXPPAGOUSA.AR_EXPFO, 
               dbo.VDATOSPEDEXPPAGOUSA.TOTALARANUSA, dbo.VDATOSPEDEXPPAGOUSA.TOTALARANUSAMN, dbo.VDATOSPEDEXPPAGOUSA.PIB_SECUENCIA, dbo.VDATOSPEDEXPPAGOUSA.PI_CODIGO, 
               dbo.VDATOSPEDEXPPAGOMEX.MONTOIGIMXUSD, dbo.VDATOSPEDEXPPAGOMEX.VALORMERCNOORIGUSD, 
               dbo.VDATOSPEDEXPPAGOUSA.PIB_DESTNAFTA, dbo.VDATOSPEDEXPPAGOMEX.MONTOIGIMXMN
FROM  dbo.VDATOSPEDEXPPAGOMEX RIGHT OUTER JOIN
               dbo.VDATOSPEDEXPPAGOUSA ON dbo.VDATOSPEDEXPPAGOMEX.FED_INDICED = dbo.VDATOSPEDEXPPAGOUSA.FED_INDICED




GO
