SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW dbo.entries
with encryption as
SELECT     dbo.ENTRYSUM.ET_ENTRY_NO, dbo.ENTRYSUM.ET_FEC_ENTRYS, dbo.ENTRADA_A.EA_CLAVE, dbo.ENTRADA_B.EB_CLAVE, 
                      dbo.ENTRYSUM.ET_MANIFEST
FROM         dbo.ENTRYSUM LEFT OUTER JOIN
                      dbo.ENTRADA_B ON dbo.ENTRYSUM.EB_ENTRADA = dbo.ENTRADA_B.EB_CODIGO LEFT OUTER JOIN
                      dbo.ENTRADA_A ON dbo.ENTRYSUM.EA_ENTRADA = dbo.ENTRADA_A.EA_CODIGO


GO
