SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW dbo.VPEDIMPVENCIMIENTODET
with encryption as
SELECT     dbo.PEDIMP.PI_CODIGO, MIN(dbo.PIDescarga.pid_fechavence) AS FECHAVENCIMIENTO, dbo.PEDIMPDET.PID_NOPARTE, 
                      MAX(dbo.PEDIMPDET.PID_NOMBRE) AS PID_NOMBRE, SUM(dbo.PIDescarga.PID_SALDOGEN) AS PID_SALDOGEN, 
                      dbo.PEDIMPDET.PID_COS_UNIGEN, dbo.MEDIDA.ME_CORTO, dbo.PEDIMPDET.EQ_GENERICO, dbo.MAESTRO.MA_NOPARTE AS MA_NOPARTEGEN,
	'BUSQUEDA'=CASE WHEN PEDIMPDET.MA_CODIGO IN (SELECT BST_HIJO FROM BOM_STRUCT WHERE BST_DISCH='S' GROUP BY BST_HIJO) 
	THEN 'No. Parte Incluido en BOM' ELSE (CASE WHEN PEDIMPDET.MA_GENERICO IN (SELECT MAESTRO.MA_GENERICO FROM BOM_STRUCT INNER JOIN MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO
									GROUP BY MAESTRO.MA_GENERICO HAVING MAESTRO.MA_GENERICO <> 0) THEN 'G.Generico No incluido en BOM' ELSE 'Ni Grupo ni No. Parte incluidos en BOM' END) END
FROM         dbo.MAESTRO RIGHT OUTER JOIN
                      dbo.PEDIMPDET ON dbo.MAESTRO.MA_CODIGO = dbo.PEDIMPDET.MA_GENERICO LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.PEDIMPDET.ME_GENERICO = dbo.MEDIDA.ME_CODIGO RIGHT OUTER JOIN
                      dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.PIDescarga ON dbo.PIDescarga.PID_INDICED = dbo.PEDIMPDET.PID_INDICED
WHERE     (dbo.PIDescarga.pid_fechavence IS NOT NULL) AND (dbo.PEDIMP.PI_MOVIMIENTO = 'E') AND (dbo.PIDescarga.PID_SALDOGEN > 0)
AND PEDIMP.PI_ESTATUS<>'R'
GROUP BY dbo.PEDIMPDET.PID_NOPARTE, dbo.PEDIMPDET.MA_CODIGO, dbo.PEDIMPDET.MA_GENERICO, dbo.PEDIMP.PI_CODIGO, 
                      dbo.PEDIMPDET.PID_COS_UNIGEN, dbo.MEDIDA.ME_CORTO, dbo.PEDIMPDET.EQ_GENERICO, dbo.MAESTRO.MA_NOPARTE
HAVING      (MIN(dbo.PIDescarga.pid_fechavence) <= CONVERT(datetime, FLOOR(CONVERT(decimal(38,6), GETDATE() - ISNULL
                          ((SELECT     CF_DIAS_AVISO
                              FROM         configuracion), 0)))))



GO
