SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VEXP_DICTAMEN
with encryption as
SELECT     dbo.DICTAMENFISCAL.DF_CODIGO, dbo.FACTEXP.FE_CODIGO, dbo.FACTEXP.CL_EXP, dbo.FACTEXP.CL_COMP, dbo.FACTEXP.FE_ESTATUS, 
                      dbo.PEDIMP.PI_FEC_PAG, dbo.FACTEXP.FE_TOTALB, dbo.FACTEXP.FE_TIPOCAMBIO, dbo.PEDIMP.CP_CODIGO, 
                      dbo.AGENCIAPATENTE.AG_CODIGO AS AG_MX, dbo.PEDIMP.AD_DES, dbo.FACTEXPDET.FED_INDICED, dbo.FACTEXPDET.MA_CODIGO, 
                      dbo.FACTEXPDET.FED_NOPARTE, dbo.FACTEXPDET.FED_NOMBRE, dbo.FACTEXPDET.FED_NAME, dbo.FACTEXPDET.ME_CODIGO, 
                      dbo.FACTEXPDET.FED_CANT, dbo.FACTEXPDET.FED_PES_NET, dbo.FACTEXPDET.FED_PES_BRU, dbo.FACTEXPDET.FED_COS_UNI, 
                      dbo.FACTEXPDET.TI_CODIGO, dbo.FACTEXPDET.PA_CODIGO, dbo.MAESTRO.PA_PROCEDE, dbo.FACTEXPDET.AR_IMPMX, dbo.FACTEXPDET.EQ_GEN, 
                      dbo.FACTEXPDET.MA_GENERICO, dbo.FACTEXP.FE_TIPO, dbo.DIR_CLIENTE.PA_CODIGO AS PA_DESTINO, dbo.AGENCIAPATENTE.AGT_CODIGO
FROM         dbo.PEDIMP INNER JOIN
                      dbo.AGENCIAPATENTE ON dbo.PEDIMP.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO RIGHT OUTER JOIN
                      dbo.FACTEXP ON dbo.PEDIMP.PI_CODIGO = dbo.FACTEXP.PI_CODIGO LEFT OUTER JOIN
                      dbo.DIR_CLIENTE ON dbo.FACTEXP.DI_DESTINI = dbo.DIR_CLIENTE.DI_INDICE RIGHT OUTER JOIN
                      dbo.DICTAMENFISCAL ON dbo.PEDIMP.PI_FEC_PAG >= dbo.DICTAMENFISCAL.DF_FECHAINI AND 
                      dbo.PEDIMP.PI_FEC_PAG <= dbo.DICTAMENFISCAL.DF_FECHAFIN LEFT OUTER JOIN
                      dbo.FACTEXPDET LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.FACTEXPDET.MA_CODIGO = dbo.MAESTRO.MA_CODIGO ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO
WHERE dbo.FACTEXP.FE_CANCELADO='N'



































GO
