SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VMAESTROCOSTtlc
with encryption as
SELECT     TCO_CODIGO, VMAESTROCOST1tlc.MA_CODIGO, MA_GRAV_MP, MA_GRAV_ADD, MA_GRAV_EMP, MA_GRAV_GI, MA_GRAV_GI_MX, MA_GRAV_MO, MA_NG_MP, 
                      MA_NG_ADD, MA_NG_EMP, MA_COSTO, MA_GRAVA_VA, MA_NG_USA, MA_NG_MX, TV_CODIGO, MA_NOPARTE, MA_NOPARTEAUX, 
                      SPI_CODIGO, EQ_GEN
FROM         dbo.VMAESTROCOST1tlc INNER JOIN (SELECT     MAX(MC2.MAC_CODIGO) AS MAC_CODIGO, MC2.MA_CODIGO
                            FROM          VMAESTROCOST1tlc MC2 GROUP BY MC2.MA_CODIGO) MC2 
ON MC2.MA_CODIGO=VMAESTROCOST1tlc.MA_CODIGO AND MC2.MAC_CODIGO=VMAESTROCOST1tlc.MAC_CODIGO



GO
