SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE VIEW dbo.VPEDIMPCONTRIBCOMPLE
with encryption as
SELECT     dbo.CONTRIBUCION.CON_ABREVIA, dbo.TPAGO.PG_DESC, dbo.VPEDIMPCONTRIBUCIONCOMPL.PIT_CONTRIBTOTMN, 
                      dbo.VPEDIMPCONTRIBUCIONCOMPL.PI_CODIGO
FROM         dbo.VPEDIMPCONTRIBUCIONCOMPL INNER JOIN
                      dbo.CONTRIBUCION ON dbo.VPEDIMPCONTRIBUCIONCOMPL.CON_CODIGO = dbo.CONTRIBUCION.CON_CODIGO INNER JOIN
                      dbo.TPAGO ON dbo.VPEDIMPCONTRIBUCIONCOMPL.PG_CODIGO = dbo.TPAGO.PG_CODIGO



GO
