SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VA17
with encryption as
SELECT     dbo.A17.A17_CODIGO, round(dbo.VPEDEXP.PI_TIP_CAM * dbo.PEDIMPDET.PID_CTOT_DLS,0) AS valor, round(dbo.PEDIMPDET.PID_CTOT_DLS,0) 
                      AS PID_CTOT_DLS, dbo.VPEDEXP.PI_CODIGO, dbo.VPEDEXP.PI_FEC_PAG, dbo.VPEDEXP.PR_CODIGO, dbo.PEDIMPDET.PID_NOMBRE 
                      AS PID_NOMBRE, dbo.VPEDEXP.PI_TIP_CAM, dbo.VPEDEXP.CL_CODIGO, dbo.PEDIMPDET.MA_GENERICO, MAESTRO_1.MA_CODIGO, 
                      MAESTRO_1.MA_NOMBRE AS FAMILIAPT, dbo.VPEDEXP.CP_CODIGO, dbo.PEDIMPDET.MA_CODIGO AS MA_PEDIMP, 
	'TRIMESTRE'=CASE WHEN Month(dbo.VPEDEXP.PI_FEC_PAG)<=3 THEN '1'  
		WHEN Month(dbo.VPEDEXP.PI_FEC_PAG)<=6 and Month(dbo.VPEDEXP.PI_FEC_PAG)>=4 THEN '2' WHEN Month(dbo.VPEDEXP.PI_FEC_PAG)<=9 and Month(dbo.VPEDEXP.PI_FEC_PAG)>=7 
		THEN '3' END
FROM         dbo.CONFIGURATIPO RIGHT OUTER JOIN
                      dbo.MAESTRO MAESTRO_2 INNER JOIN
                      dbo.A17 INNER JOIN
                      dbo.VPEDEXP ON dbo.A17.A17_FECHAINI <= dbo.VPEDEXP.PI_FEC_PAG AND dbo.A17.A17_FECHAFIN >= dbo.VPEDEXP.PI_FEC_PAG ON 
                      MAESTRO_2.MA_FAMILIA = dbo.A17.MA_FAMILIA LEFT OUTER JOIN
                      dbo.MAESTRO MAESTRO_1 ON MAESTRO_2.MA_FAMILIA = MAESTRO_1.MA_CODIGO FULL OUTER JOIN
                      dbo.PEDIMPDET ON MAESTRO_2.MA_CODIGO = dbo.PEDIMPDET.MA_CODIGO AND dbo.VPEDEXP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO ON 
                      dbo.CONFIGURATIPO.TI_CODIGO = dbo.PEDIMPDET.TI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDEXP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
WHERE     (dbo.CONFIGURACLAVEPED.CCP_TIPO IN ('VT', 'IV', 'CN')) AND (dbo.CONFIGURATIPO.CFT_TIPO IN ('T', 'R', 'E', 'L', 'M', 'O', 'P', 'S'))

GO
