SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VR1ACTUAL3
with encryption as
SELECT     MAX(dbo.VR1ACTUAL1.R1H_PEDIMENTOR1ANT) AS R1H_PEDIMENTOR1ANT, MAX(dbo.VR1ACTUAL1.R1H_FECHAPAGO) AS R1H_FECHAPAGO, 
                      dbo.VR1ACTUAL1.PI_CODIGO
FROM         dbo.VR1ACTUAL2 INNER JOIN
                      dbo.VR1ACTUAL1 ON dbo.VR1ACTUAL2.PI_CODIGO = dbo.VR1ACTUAL1.PI_CODIGO AND 
                      dbo.VR1ACTUAL2.R1H_FECHAPAGO = dbo.VR1ACTUAL1.R1H_FECHAPAGO
GROUP BY dbo.VR1ACTUAL1.PI_CODIGO


GO
