SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VPEDIMPERROR
with encryption as
SELECT     dbo.FACTIMP.PI_CODIGO
FROM         dbo.FACTIMP INNER JOIN
                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO INNER JOIN
                      dbo.PEDIMP ON dbo.FACTIMP.PI_CODIGO = dbo.PEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.CLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CLAVEPED.CP_CODIGO
WHERE     (dbo.PEDIMP.PI_ESTATUS IN ('S', 'B')) AND (dbo.FACTIMPDET.PID_INDICEDLIGA = - 1 OR
                      dbo.FACTIMPDET.PID_INDICEDLIGA IS NULL) AND (dbo.CLAVEPED.CP_DESCARGABLE = 'S')
GROUP BY dbo.FACTIMP.PI_CODIGO
UNION
SELECT     dbo.FACTIMP.PI_RECTIFICA
FROM         dbo.FACTIMP INNER JOIN
                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO INNER JOIN
                      dbo.PEDIMP ON dbo.FACTIMP.PI_RECTIFICA = dbo.PEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.CLAVEPED ON dbo.PEDIMP.CP_RECTIFICA = dbo.CLAVEPED.CP_CODIGO
WHERE     (dbo.FACTIMPDET.PID_INDICEDLIGAR1 = - 1 OR
             dbo.FACTIMPDET.PID_INDICEDLIGAR1 IS NULL) AND (dbo.PEDIMP.PI_ESTATUS IN ('N', 'T')) 
	AND (dbo.FACTIMP.PI_CODIGO IS NOT NULL) AND (dbo.FACTIMP.PI_CODIGO <> - 1) AND
	 (dbo.CLAVEPED.CP_DESCARGABLE = 'S' OR dbo.CLAVEPED.CP_DESCARGABLE IS NULL)
GROUP BY dbo.FACTIMP.PI_RECTIFICA, dbo.CLAVEPED.CP_DESCARGABLE








GO
