SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VPEDIMPTEMPIMP
with encryption as
SELECT     dbo.PEDIMP.PI_CODIGO, dbo.PEDIMP.PI_FOLIO, dbo.PEDIMP.FC_CODIGO, dbo.PEDIMP.PI_MOVIMIENTO, dbo.PEDIMP.PI_TIPO, 
                      dbo.PEDIMP.CP_CODIGO, dbo.PEDIMP.CP_RECTIFICA, dbo.PEDIMP.REG_CODIGO, dbo.PEDIMP.PI_TIP_CAM, dbo.PEDIMP.PI_FMON_EXT, 
                      dbo.PEDIMP.MT_CODIGO, VPEDIMPVALORES.PI_PESO, dbo.PEDIMP.PI_FRAN_INT, 
                      dbo.PEDIMP.PI_FEC_PAG, dbo.PEDIMP.AD_DES, dbo.PEDIMP.AD_ORI, 
                      dbo.PEDIMP.PI_FEC_ENT, dbo.PEDIMP.PI_REEXPED, dbo.PEDIMP.PI_TRANSIT, dbo.PEDIMP.PI_IN_DIR, dbo.PEDIMP.CL_CODIGO, 
                      dbo.PEDIMP.DI_CL, dbo.PEDIMP.PR_CODIGO, dbo.PEDIMP.DI_PR, 
                      dbo.PEDIMP.PI_BULTO, VPEDIMPVALORES.PI_VALOR_ME, VPEDIMPVALORES.PI_VALOR_FACT, VPEDIMPVALORES.PI_VALOR_ADU, 
                      dbo.PEDIMP.PI_FT_ADU, dbo.PEDIMP.PI_TOTAL, dbo.PEDIMP.PI_FIRMA, dbo.AGENCIAPATENTE.AG_CODIGO, dbo.PEDIMP.AGT_CODIGO, dbo.PEDIMP.PI_OBSERVA, 
                      dbo.PEDIMP.PI_RECTIFICA, dbo.PEDIMP.PI_SEM, 0 AS PI_TRANSP, dbo.PEDIMP.PI_ANEXOL, dbo.PEDIMP.US_CODIGO, 
                      dbo.PEDIMP.PI_ESTATUS, dbo.PEDIMP.PI_ACTIVO_DESCARGA, dbo.PEDIMP.PI_AFECTADO, dbo.PEDIMP.PI_FECHAINI, dbo.PEDIMP.PI_FECHAFIN, 
                      dbo.PEDIMP.PI_OBSERVA_RECTIFICA, dbo.PEDIMP.PI_CONSOLIDA, dbo.PEDIMP.PI_FEC_CAMREG, dbo.PEDIMP.ZO_CODIGO, 
                      dbo.PEDIMP.MT_SALIDA, dbo.PEDIMP.MT_ARRIBO, dbo.PEDIMP.MT_ABANDONA, dbo.PEDIMP.TTA_CODIGO, dbo.PEDIMP.PI_FOLIOPAGO, 
                      dbo.PEDIMP.PI_CHEQUEPAGO, dbo.PEDIMP.PI_COMPLEMEN, dbo.PEDIMP.PI_FECHAPAGO, dbo.PEDIMP.PI_TIP_CAMPAGO, 
                      dbo.PEDIMP.PI_IMPORTECONTR, dbo.PEDIMP.PI_IMPORTERECARGOS, dbo.PEDIMP.PI_PORCENNAFTA, dbo.PEDIMP.PI_FEC_ACT_TIEMPO, 
                      dbo.AGENCIAPATENTE.AGT_PATENTE collate database_default + '-' + dbo.PEDIMP.PI_FOLIO collate database_default AS [PATENTE-FOLIO]
FROM         dbo.PEDIMP LEFT OUTER JOIN
                      dbo.AGENCIAPATENTE ON dbo.PEDIMP.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO LEFT OUTER JOIN
	        VPEDIMPVALORES ON dbo.PEDIMP.PI_CODIGO = VPEDIMPVALORES.PI_CODIGO
WHERE     (dbo.PEDIMP.PI_MOVIMIENTO = 'E')
AND ((CP_CODIGO IN (SELECT CP_CODIGO FROM CLAVEPED WHERE CP_DESCARGABLE='S') AND
PI_ESTATUS<>'R')
OR CP_RECTIFICA IN (SELECT CP_CODIGO FROM CLAVEPED WHERE CP_DESCARGABLE='S'))


GO
