SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
































CREATE VIEW dbo.VFACTIMPR8VA
with encryption as
SELECT     dbo.FACTIMPDET.FI_CODIGO, dbo.FACTIMPDET.FID_INDICED, dbo.FACTIMPDET.FID_NOPARTE, dbo.FACTIMPDET.AR_IMPMX, 
                      dbo.ARANCEL.AR_FRACCION, round(SUM(dbo.FACTIMPDET.FID_CANT_ST * dbo.FACTIMPPERM.EQ_CANT),6) AS FID_CANT, 
                      round(SUM(dbo.FACTIMPDET.FID_COS_TOT),6) AS FID_COS_TOT, dbo.ANEXO24.ANX_CAS_NUM, dbo.MEDIDA.ME_CORTO, dbo.CATEGPERMISO.CPE_CORTO, 
                      MEDIDA_1.ME_CORTO AS ME_CORTOCATEG, dbo.FACTIMPPERM.FIR_CODIGO
FROM         dbo.PERMISO LEFT OUTER JOIN
                      dbo.CONFIGURAPERMISOREL ON dbo.PERMISO.IDE_CODIGO = dbo.CONFIGURAPERMISOREL.IDE_CODIGO RIGHT OUTER JOIN
                      dbo.FACTIMPPERM ON dbo.PERMISO.PE_CODIGO = dbo.FACTIMPPERM.PE_CODIGO LEFT OUTER JOIN
                      dbo.CATEGPERMISO LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_1 ON dbo.CATEGPERMISO.ME_CODIGO = MEDIDA_1.ME_CODIGO ON 
                      dbo.FACTIMPPERM.CPE_CODIGO = dbo.CATEGPERMISO.CPE_CODIGO RIGHT OUTER JOIN
                      dbo.FACTIMPDET ON dbo.FACTIMPPERM.FID_INDICED = dbo.FACTIMPDET.FID_INDICED LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.FACTIMPDET.ME_CODIGO = dbo.MEDIDA.ME_CODIGO LEFT OUTER JOIN
                      dbo.ANEXO24 ON dbo.FACTIMPDET.MA_CODIGO = dbo.ANEXO24.MA_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ON dbo.FACTIMPDET.AR_IMPMX = dbo.ARANCEL.AR_CODIGO
WHERE     (dbo.FACTIMPDET.FID_DEF_TIP = 'R') AND (dbo.CONFIGURAPERMISOREL.CFR_SALDO = 'S' OR dbo.CONFIGURAPERMISOREL.CFR_SALDOCARATULA = 'S' OR
                     dbo.ANEXO24.ANX_CAS_NUM IS NOT NULL)
GROUP BY dbo.ARANCEL.AR_FRACCION, dbo.FACTIMPDET.FI_CODIGO, dbo.FACTIMPDET.AR_IMPMX, dbo.ANEXO24.ANX_CAS_NUM, dbo.MEDIDA.ME_CORTO, 
                      dbo.FACTIMPPERM.EQ_CANT, dbo.CATEGPERMISO.CPE_CORTO, MEDIDA_1.ME_CORTO, dbo.FACTIMPPERM.FIR_CODIGO, 
                      dbo.FACTIMPDET.FID_INDICED, dbo.FACTIMPDET.FID_NOPARTE



































GO
