SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VPEDIMPPAIS
with encryption as
SELECT     TOP 100 PERCENT PI_CODIGO, MA_GENERICO, PA_ORIGEN, COUNT(*) AS COUNTPAIS
FROM         dbo.PEDIMPDET
GROUP BY PI_CODIGO, MA_GENERICO, PA_ORIGEN



GO
