SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






































-- el total del pago se calcula de esa manera por que no es directamente en base a el valor en aduana, ej IVA
CREATE VIEW dbo.VPEDIMPDETCONTRIBUCION
with encryption as
SELECT     dbo.PEDIMPDET.PID_INDICED, dbo.PEDIMPDETBCONTRIBUCION.PI_CODIGO, dbo.PEDIMPDETBCONTRIBUCION.PIB_CONTRIBPOR, 
--round(dbo.PEDIMPDETBCONTRIBUCION.PIB_CONTRIBTOTMN * (dbo.PEDIMPDET.PID_CAN_GEN / dbo.PEDIMPDETB.PIB_CAN_GEN),0) AS PIB_CONTRIBTOTMN,
(CASE WHEN dbo.PEDIMPDETBCONTRIBUCION.PIB_CONTRIBTOTMN<>0 and dbo.PEDIMPDET.PID_CAN_GEN<>0 and dbo.PEDIMPDETB.PIB_CAN_GEN<>0 THEN round(dbo.PEDIMPDETBCONTRIBUCION.PIB_CONTRIBTOTMN *  (  dbo.PEDIMPDET.PID_CAN_GEN /  dbo.PEDIMPDETB.PIB_CAN_GEN),0)  ELSE 0.0 END) AS PIB_CONTRIBTOTMN,
--                      ROUND(dbo.PEDIMPDETBCONTRIBUCION.PIB_CONTRIBPOR / 100 * dbo.PEDIMPDET.PID_VAL_ADU, 0) AS PIB_CONTRIBTOTMN, 
                      dbo.PEDIMPDETBCONTRIBUCION.PG_CODIGO, dbo.PEDIMPDETBCONTRIBUCION.TTA_CODIGO, dbo.PEDIMPDETBCONTRIBUCION.CON_CODIGO
FROM         dbo.PEDIMPDETBCONTRIBUCION INNER JOIN
                      dbo.PEDIMPDET ON dbo.PEDIMPDETBCONTRIBUCION.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB INNER JOIN 
dbo.PEDIMPDETB ON dbo.PEDIMPDET.PIB_INDICEB =dbo.PEDIMPDETB.PIB_INDICEB












































GO
