SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VPERMISODET_MP
with encryption as
SELECT PERMISODET.*
FROM PERMISODET
WHERE (PED_REGISTROTIPO = 1) AND (PED_ID_SUBORD <> 0)



GO
