SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO









CREATE VIEW dbo.VINPCMAX
with encryption as
SELECT     INPCMAX1.PI_CODIGO, INPCMAX1.IN_FECINI, MAX(dbo.INPC.IN_CANT) AS IN_CANT, dbo.INPC.IN_MES
FROM         (SELECT dbo.VPAGOCONTRIBPERIODO.PI_CODIGO, MAX(dbo.INPC.IN_FECINI) AS IN_FECINI
	       FROM  dbo.INPC INNER JOIN
 	               dbo.VPAGOCONTRIBPERIODO ON dbo.INPC.IN_FECINI <= DATEADD(mm, -1, dbo.VPAGOCONTRIBPERIODO.KAP_FECHAPEDmax) 
  	      GROUP BY dbo.VPAGOCONTRIBPERIODO.PI_CODIGO) INPCMAX1 INNER JOIN
                           dbo.INPC ON INPCMAX1.IN_FECINI = dbo.INPC.IN_FECINI
GROUP BY INPCMAX1.PI_CODIGO, INPCMAX1.IN_FECINI, dbo.INPC.IN_MES












GO
