SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VTCAMBIOMIN
with encryption as
SELECT     INPCMIN1.IN_FECINI, INPCMIN1.PI_CODIGO, dbo.TCAMBIO.TC_CANTDOF
FROM         (SELECT dbo.VPAGOCONTRIBPERIODO.PI_CODIGO, MAX(dbo.INPC.IN_FECINI) AS IN_FECINI
	FROM  dbo.INPC INNER JOIN
	               dbo.VPAGOCONTRIBPERIODO ON dbo.INPC.IN_FECINI <= DATEADD(mm, -1, dbo.VPAGOCONTRIBPERIODO.KAP_FECHAPEDmin)  
	GROUP BY dbo.VPAGOCONTRIBPERIODO.PI_CODIGO
	) INPCMIN1 INNER JOIN
                      dbo.TCAMBIO ON INPCMIN1.IN_FECINI = dbo.TCAMBIO.TC_FECHA




GO
