SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






























CREATE VIEW dbo.VDESCARGAGR
with encryption as
SELECT     dbo.FACTEXPDET.FE_CODIGO, dbo.BOM_DESCTEMP.FED_INDICED, dbo.BOM_DESCTEMP.FED_CANT, dbo.MAESTRO.MA_GENERICO, 
                      SUM(dbo.BOM_DESCTEMP.BST_INCORPOR) AS BST_INCORPOR, ISNULL(dbo.BOM_DESCTEMP.FACTCONV, 1) AS FACTCONV, 
                      dbo.MAESTRO.SE_CODIGO, dbo.BOM_DESCTEMP.BST_TIPODESC, dbo.BOM_DESCTEMP.BST_TIPOCOSTO, 
                      'MA_DEF_TIP' = CASE WHEN dbo.MAESTRO.MA_DEF_TIP = 'S' THEN 'S' ELSE 'N' END
FROM         dbo.MAESTRO LEFT OUTER JOIN
                      dbo.VMAESTROCOST ON dbo.MAESTRO.MA_GENERICO = dbo.VMAESTROCOST.MA_CODIGO RIGHT OUTER JOIN
                      dbo.BOM_DESCTEMP ON dbo.MAESTRO.MA_CODIGO = dbo.BOM_DESCTEMP.BST_HIJO LEFT OUTER JOIN
                      dbo.FACTEXPDET ON dbo.BOM_DESCTEMP.FED_INDICED = dbo.FACTEXPDET.FED_INDICED RIGHT OUTER JOIN
                      dbo.FACTEXP ON dbo.BOM_DESCTEMP.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
WHERE     (dbo.BOM_DESCTEMP.BST_DISCH = 'S')
GROUP BY dbo.FACTEXPDET.FE_CODIGO, dbo.BOM_DESCTEMP.FED_INDICED, dbo.BOM_DESCTEMP.FACTCONV, dbo.BOM_DESCTEMP.FED_CANT, 
                      dbo.BOM_DESCTEMP.BST_TIPODESC, dbo.BOM_DESCTEMP.BST_TIPOCOSTO, dbo.MAESTRO.MA_GENERICO, dbo.MAESTRO.SE_CODIGO, 
                      dbo.MAESTRO.MA_DEF_TIP
HAVING      (SUM(dbo.BOM_DESCTEMP.BST_INCORPOR) > 0) AND (dbo.BOM_DESCTEMP.FED_CANT > 0) AND (dbo.MAESTRO.MA_GENERICO IS NOT NULL)
AND (dbo.MAESTRO.MA_GENERICO >0)





















































GO
