SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
























CREATE VIEW dbo.VPEDIMPTTASA
with encryption as
SELECT     dbo.PEDIMPCONTRIBUCION.PI_CODIGO, 
                      round(SUM(dbo.PEDIMPCONTRIBUCION.PIT_CONTRIBTOTMN - (dbo.PEDIMPCONTRIBUCION.PIT_CONTRIBTOTMN * dbo.CONTRIBUCION.CON_PORMENOSTASA) 
                     ),0) AS PIT_CONTRIBTOTMN, dbo.TTASA.TTA_CLA_PED, dbo.CONTRIBUCION.CON_ABREVIA, max(dbo.PEDIMPCONTRIBUCION.PIT_CONTRIBPOR) as PIT_CONTRIBPOR
FROM         dbo.PEDIMPCONTRIBUCION LEFT OUTER JOIN
                      dbo.CONTRIBUCION ON dbo.PEDIMPCONTRIBUCION.CON_CODIGO = dbo.CONTRIBUCION.CON_CODIGO LEFT OUTER JOIN
                      dbo.TTASA ON dbo.PEDIMPCONTRIBUCION.TTA_CODIGO = dbo.TTASA.TTA_CODIGO
WHERE     (dbo.PEDIMPCONTRIBUCION.TTA_CODIGO IS NOT NULL) AND (dbo.PEDIMPCONTRIBUCION.TTA_CODIGO <> 0)
GROUP BY dbo.PEDIMPCONTRIBUCION.PI_CODIGO, dbo.TTASA.TTA_CLA_PED, dbo.CONTRIBUCION.CON_ABREVIA



GO
