SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO









CREATE VIEW dbo.VDATOSPEDEXPDESC
with encryption as
SELECT     KAP_CODIGO, KAP_PED_CONST, KAP_INDICED_PED, KAP_INDICED_FACT, PI_CODIGOPEDEXP, PIB_INDICEB, ISNULL(KAP_CANTDESC, 0) 
                      AS KAP_CANTDESC, PI_TIP_CAM, KAP_COS_UNI, ISNULL(PID_POR_DEF, - 1) AS PID_POR_DEF, KAP_DEF_TIP, PID_PAGACONTRIB, PID_NOMBRE, 
                      AR_IMPMX, KAP_SECIMP, SPI_CODIGO, PA_ORIGEN, MA_CODIGO, PID_NOPARTE
FROM         dbo.KARDATOSPEDEXPDESC
WHERE     (PID_POR_DEF > 0) AND (KAP_CANTDESC > 0)












GO
