SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

































CREATE VIEW dbo.VFACTIMPDETLiga
with encryption as
SELECT     FID_INDICED, FI_CODIGO, FID_NOPARTE, FID_NOMBRE, FID_NAME, FID_CANT_ST, FID_COS_UNI, FID_COS_TOT, FID_PES_UNI, FID_PES_NET, 
                      FID_PES_BRU, FID_PES_UNILB, FID_PES_NETLB, FID_PES_BRULB, OR_CODIGO, FID_ORD_COMP, ORD_INDICED, FID_NOORDEN, FID_OBSERVA, 
                      FID_FEC_ENT, FID_NUM_ENT, FID_SEC_IMP, FID_POR_DEF, FID_DEF_TIP, FID_ENVIO, AR_IMPMX, AR_EXPFO, MA_CODIGO, MV_CODIGO, 
                      ME_CODIGO, MA_GENERICO, ME_ARIMPMX, PA_CODIGO, PR_CODIGO, PL_FOLIO, PL_CODIGO, PLD_INDICED, CS_CODIGO, PE_CODIGO, EQ_GEN, 
                      EQ_IMPMX, EQ_EXPFO, TI_CODIGO, FID_RATEEXPFO, FID_RELEMP, SPI_CODIGO, MA_EMPAQUE, FID_CANTEMP, FID_LOTE, FID_FAC_NUM, 
                      FID_FEC_ENV, FID_LISTA, FID_CON_CERTORIG, ME_GEN, FID_GENERA_EMP, FID_CANT_DESP, FID_DEFTXT1, FID_DEFTXT2, FID_DEFNO3, 
                      FID_DEFNO4, FID_FECHA_STRUCT, FID_PADREKITINSERT, 'PID_INDICEDLIGA'=CASE WHEN PID_INDICEDLIGAR1=-1 OR PID_INDICEDLIGAR1
	          IS NULL THEN PID_INDICEDLIGA ELSE PID_INDICEDLIGAR1 END,
	         TCO_CODIGO, FID_RELCAJAS, FID_SALDO, FID_ENUSO, FID_NOPARTEAUX,
                       'CONIDENTIFICA'=CASE WHEN (SELECT COUNT(*) FROM FACTIMPDETIDENTIFICA WHERE FACTIMPDETIDENTIFICA.FID_INDICED=dbo.FACTIMPDET.FID_INDICED)>0 THEN 'S' ELSE 'N' END,
	         'CONCONTENIDO'=CASE WHEN (SELECT COUNT(*) FROM FACTIMPCONT WHERE FACTIMPCONT.FID_INDICED=dbo.FACTIMPDET.FID_INDICED)>0 THEN 'S' ELSE 'N' END
FROM         dbo.FACTIMPDET


















































GO
