SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

































CREATE VIEW dbo.VPREVIADEFACTCONV
with encryption as
-- um diferente pero factor igual a uno.
SELECT     TOP 100 PERCENT dbo.FACTIMP.FI_FOLIO, dbo.FACTIMP.FI_FECHA, dbo.TFACTURA.TF_NOMBRE, dbo.FACTIMPDET.MA_CODIGO, 
                      dbo.FACTIMPDET.FID_NOPARTE, dbo.FACTIMPDET.FID_NOMBRE, dbo.FACTIMPDET.FID_CANT_ST, dbo.TIPO.TI_NOMBRE, dbo.CLIENTE.CL_RAZON, 
                      dbo.FACTIMPDET.EQ_GEN, MEDIDA_2.ME_CORTO, MEDIDA_1.ME_CORTO AS ME_GEN
FROM         dbo.CLIENTE RIGHT OUTER JOIN
                      dbo.FACTIMP LEFT OUTER JOIN
                      dbo.CONFIGURATFACT ON dbo.FACTIMP.TF_CODIGO = dbo.CONFIGURATFACT.TF_CODIGO ON 
                      dbo.CLIENTE.CL_CODIGO = dbo.FACTIMP.PR_CODIGO LEFT OUTER JOIN
                      dbo.TFACTURA ON dbo.FACTIMP.TF_CODIGO = dbo.TFACTURA.TF_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_1 RIGHT OUTER JOIN
                      dbo.FACTIMPDET ON MEDIDA_1.ME_CODIGO = dbo.FACTIMPDET.ME_GEN LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_2 ON dbo.FACTIMPDET.ME_CODIGO = MEDIDA_2.ME_CODIGO LEFT OUTER JOIN
                      dbo.TIPO ON dbo.FACTIMPDET.TI_CODIGO = dbo.TIPO.TI_CODIGO ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
WHERE     (dbo.FACTIMPDET.FID_NOPARTE IS NOT NULL) AND (dbo.FACTIMP.FI_CANCELADO = 'N') AND 
                      (dbo.FACTIMPDET.ME_CODIGO <> dbo.FACTIMPDET.ME_GEN) AND (dbo.FACTIMPDET.EQ_GEN = 1)
	AND (dbo.CONFIGURATFACT.CFF_TIPO <> 'ID' AND 
                      dbo.CONFIGURATFACT.CFF_TIPO <> 'TA' AND dbo.CONFIGURATFACT.CFF_TIPO <> 'IA' AND dbo.CONFIGURATFACT.CFF_TIPO <> 'RS')
	and convert(varchar(10),dbo.FACTIMPDET.ME_CODIGO)+convert(varchar(10),dbo.FACTIMPDET.ME_GEN) not in 
	(SELECT convert(varchar(10),dbo.EQUIVALE.ME_CODIGO1)+convert(varchar(10),dbo.EQUIVALE.ME_CODIGO2) FROM dbo.EQUIVALE WHERE dbo.EQUIVALE.EQ_CANT=1)
ORDER BY dbo.FACTIMP.FI_FECHA, dbo.FACTIMP.FI_FOLIO
UNION
-- um igual pero factor diferente de uno.
SELECT     TOP 100 PERCENT dbo.FACTIMP.FI_FOLIO, dbo.FACTIMP.FI_FECHA, dbo.TFACTURA.TF_NOMBRE, dbo.FACTIMPDET.MA_CODIGO, 
                      dbo.FACTIMPDET.FID_NOPARTE, dbo.FACTIMPDET.FID_NOMBRE, dbo.FACTIMPDET.FID_CANT_ST, dbo.TIPO.TI_NOMBRE, dbo.CLIENTE.CL_RAZON, 
                      dbo.FACTIMPDET.EQ_GEN, MEDIDA_2.ME_CORTO, MEDIDA_1.ME_CORTO AS ME_GEN
FROM         dbo.CLIENTE RIGHT OUTER JOIN
                      dbo.FACTIMP LEFT OUTER JOIN
                      dbo.CONFIGURATFACT ON dbo.FACTIMP.TF_CODIGO = dbo.CONFIGURATFACT.TF_CODIGO ON 
                      dbo.CLIENTE.CL_CODIGO = dbo.FACTIMP.PR_CODIGO LEFT OUTER JOIN
                      dbo.TFACTURA ON dbo.FACTIMP.TF_CODIGO = dbo.TFACTURA.TF_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_1 RIGHT OUTER JOIN
                      dbo.FACTIMPDET ON MEDIDA_1.ME_CODIGO = dbo.FACTIMPDET.ME_GEN LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_2 ON dbo.FACTIMPDET.ME_CODIGO = MEDIDA_2.ME_CODIGO LEFT OUTER JOIN
                      dbo.TIPO ON dbo.FACTIMPDET.TI_CODIGO = dbo.TIPO.TI_CODIGO ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
WHERE     (dbo.FACTIMPDET.FID_NOPARTE IS NOT NULL) AND (dbo.FACTIMP.FI_CANCELADO = 'N') AND 
                      (dbo.FACTIMPDET.ME_CODIGO = dbo.FACTIMPDET.ME_GEN) AND (dbo.FACTIMPDET.EQ_GEN <> 1) AND (dbo.CONFIGURATFACT.CFF_TIPO <> 'ID') 
                      AND (dbo.CONFIGURATFACT.CFF_TIPO <> 'TA') AND (dbo.CONFIGURATFACT.CFF_TIPO <> 'IA') AND (dbo.CONFIGURATFACT.CFF_TIPO <> 'RS')
	and convert(varchar(10),dbo.FACTIMPDET.ME_CODIGO)+convert(varchar(10),dbo.FACTIMPDET.ME_GEN) not in 
	(SELECT convert(varchar(10),dbo.EQUIVALE.ME_CODIGO1)+convert(varchar(10),dbo.EQUIVALE.ME_CODIGO2) FROM dbo.EQUIVALE WHERE dbo.EQUIVALE.EQ_CANT=1)
ORDER BY dbo.FACTIMP.FI_FECHA, dbo.FACTIMP.FI_FOLIO


































































GO
