SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.vINVENTARIO_GENERICO
with encryption as
SELECT     TOP 100 PERCENT maestro_gen.MA_NOPARTE AS Generico, dbo.TEMP_INVENTARIOS.PI_FOLIO, dbo.TEMP_INVENTARIOS.PI_FECHA, 
                      dbo.TEMP_INVENTARIOS.NOPARTE, dbo.TEMP_INVENTARIOS.END_SALDOGEN
FROM         dbo.TEMP_INVENTARIOS LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.MAESTRO.MA_CODIGO = dbo.TEMP_INVENTARIOS.MA_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO maestro_gen ON dbo.MAESTRO.MA_GENERICO = maestro_gen.MA_CODIGO
GROUP BY maestro_gen.MA_NOPARTE, dbo.TEMP_INVENTARIOS.PI_FOLIO, dbo.TEMP_INVENTARIOS.PI_FECHA, dbo.TEMP_INVENTARIOS.NOPARTE, 
                      dbo.TEMP_INVENTARIOS.END_SALDOGEN
ORDER BY maestro_gen.MA_NOPARTE, dbo.TEMP_INVENTARIOS.PI_FECHA

GO
