SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VPCKLISTPEDIMP
with encryption as
SELECT     dbo.PCKLIST.PL_FOLIO, dbo.VFACTIMP.FI_FOLIO, dbo.PCKLIST.PL_FECHA, dbo.PCKLIST.PL_CTRLADD, dbo.PCKLISTDET.PLD_NOPARTE, 
                      dbo.PCKLISTDET.PLD_CANT_ST, dbo.PCKLISTDET.PLD_CANT_ORIG, dbo.PCKLISTDET.PLD_ORD_COMP, dbo.MEDIDA.ME_CORTO, dbo.PCKLISTDET.PLD_CANTEMP, 
                      dbo.MAESTRO.MA_NOPARTE, dbo.PCKLISTDET.PLD_PES_NETLB, dbo.PCKLISTDET.PLD_PES_BRULB, dbo.VPEDIMP.PATENTE_FOLIO, 
                      dbo.VFACTIMP.FI_FEC_ENV, dbo.CLIENTE.CL_RAZON, dbo.VFACTIMP.FI_FECHA, dbo.PCKLIST.PL_COMENTA, dbo.VPEDIMP.PI_FEC_ENT,
	         dbo.VFACTIMP.FI_TRAC_MX, dbo.VFACTIMP.CT_CODIGO
FROM         dbo.CLIENTE RIGHT OUTER JOIN
                      dbo.PCKLIST INNER JOIN
                      dbo.PCKLISTDET ON dbo.PCKLIST.PL_CODIGO = dbo.PCKLISTDET.PL_CODIGO ON 
                      dbo.CLIENTE.CL_CODIGO = dbo.PCKLIST.PR_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.PCKLISTDET.ME_CODIGO = dbo.MEDIDA.ME_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.PCKLISTDET.MA_EMPAQUE = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.VFACTIMP LEFT OUTER JOIN
                      dbo.VPEDIMP ON dbo.VFACTIMP.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO RIGHT OUTER JOIN
                      dbo.VFACTIMPDETLiga ON dbo.VFACTIMP.FI_CODIGO = dbo.VFACTIMPDETLiga.FI_CODIGO ON 
                      dbo.PCKLISTDET.PLD_INDICED = dbo.VFACTIMPDETLiga.PLD_INDICED
WHERE     (dbo.PCKLIST.PL_RECIBIDO = 'S') and (dbo.PCKLIST.PL_PDOCUMEN <> 'S')



GO
