SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






































CREATE VIEW dbo.[VPREVIAESSINFACTCONV]
with encryption as
SELECT     TOP 100 PERCENT dbo.BOM_STRUCT.BSU_NOPARTE, dbo.BOM_STRUCT.BST_NOPARTE, dbo.BOM_STRUCT.ME_CODIGO, dbo.MEDIDA.ME_CORTO, 
                      MEDIDA_1.ME_CORTO AS ME_GEN, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, 
                      dbo.BOM_STRUCT.BSU_SUBENSAMBLE, dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_CODIGO
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_1 ON dbo.BOM_STRUCT.ME_GEN = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.BOM_STRUCT.ME_CODIGO = dbo.MEDIDA.ME_CODIGO
WHERE     (dbo.BOM_STRUCT.ME_CODIGO <> dbo.BOM_STRUCT.ME_GEN) AND (dbo.BOM_STRUCT.FACTCONV = 1) and (dbo.BOM_STRUCT.BST_DISCH='S')
	and convert(varchar(10),dbo.BOM_STRUCT.ME_CODIGO)+convert(varchar(10),dbo.BOM_STRUCT.ME_GEN) not in 
	(SELECT convert(varchar(10),dbo.EQUIVALE.ME_CODIGO1)+convert(varchar(10),dbo.EQUIVALE.ME_CODIGO2) FROM dbo.EQUIVALE WHERE dbo.EQUIVALE.EQ_CANT=1)
ORDER BY dbo.BOM_STRUCT.BSU_SUBENSAMBLE, dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_PERINI
UNION
SELECT     TOP 100 PERCENT dbo.BOM_STRUCT.BSU_NOPARTE, dbo.BOM_STRUCT.BST_NOPARTE, dbo.BOM_STRUCT.ME_CODIGO, dbo.MEDIDA.ME_CORTO, 
                      MEDIDA_1.ME_CORTO AS ME_GEN, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, 
                      dbo.BOM_STRUCT.BSU_SUBENSAMBLE, dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_CODIGO
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_1 ON dbo.BOM_STRUCT.ME_GEN = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.BOM_STRUCT.ME_CODIGO = dbo.MEDIDA.ME_CODIGO
WHERE     (dbo.BOM_STRUCT.ME_CODIGO = dbo.BOM_STRUCT.ME_GEN) AND (dbo.BOM_STRUCT.FACTCONV <> 1) and (dbo.BOM_STRUCT.BST_DISCH='S')
	and convert(varchar(10),dbo.BOM_STRUCT.ME_CODIGO)+convert(varchar(10),dbo.BOM_STRUCT.ME_GEN) not in 
	(SELECT convert(varchar(10),dbo.EQUIVALE.ME_CODIGO1)+convert(varchar(10),dbo.EQUIVALE.ME_CODIGO2) FROM dbo.EQUIVALE WHERE dbo.EQUIVALE.EQ_CANT=1)
ORDER BY dbo.BOM_STRUCT.BSU_SUBENSAMBLE, dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_PERINI







































































GO
