SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW dbo.VPEDIMPDETIDENTIFICACOMPL
with encryption as
SELECT     PIID_CODIGO, PIB_INDICEB, IDE_CODIGO, IDED_CODIGO, PIID_DESC
FROM         dbo.PEDIMPDETIDENTIFICA
WHERE     (PIID_TIPO = 'C')


GO
