SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




























CREATE VIEW dbo.VAUDTASAS
with encryption as
SELECT     TOP 100 PERCENT FACTIMP.FI_CODIGO, FACTIMP.FI_FOLIO, FACTIMP.FI_FECHA, FACTIMPDET.FID_NOPARTE, FACTIMPDET.FID_POR_DEF, 
                      FACTIMPDET.AR_IMPMX, FACTIMPDET.PA_CODIGO, CONFIGURATIPO.CFT_TIPO, FACTIMPDET.SPI_CODIGO, FACTIMPDET.FID_DEF_TIP, 
                      FACTIMPDET.FID_SEC_IMP, FACTIMPDET.MA_CODIGO
FROM         dbo.FACTIMP FACTIMP LEFT OUTER JOIN
                      dbo.FACTIMPDET FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO CONFIGURATIPO ON FACTIMPDET.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
WHERE     (CONFIGURATIPO.CFT_TIPO NOT IN ('X', 'S', 'Q', 'P', 'H', 'C')) AND (FACTIMPDET.FID_POR_DEF = - 1) OR
                      (CONFIGURATIPO.CFT_TIPO NOT IN ('X', 'S', 'Q', 'P', 'H', 'C')) AND (FACTIMPDET.PA_CODIGO = 0) OR
                      (CONFIGURATIPO.CFT_TIPO NOT IN ('X', 'S', 'Q', 'P', 'H', 'C')) AND (FACTIMPDET.AR_IMPMX = 0) OR
                      (CONFIGURATIPO.CFT_TIPO NOT IN ('X', 'S', 'Q', 'P', 'H', 'C')) AND (FACTIMPDET.AR_IMPMX IS NULL)
ORDER BY FACTIMP.FI_CODIGO

























GO
