SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VDATOSPEDEXPPAGOMEXxPedExp
with encryption as
SELECT     PEDIMPDETB.PI_CODIGO, PEDIMPDETB.PIB_INDICEB, PEDIMPDETB.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, 
                      SUM(ISNULL(ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC, 0)) 
                      AS VALORMERCNOORIGUSD, SUM(ISNULL(ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC, 0)*VDATOSPEDEXPDESCxPedExp.PI_TIP_CAM) 
                      AS VALORMERCNOORIGMN, SUM((ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC) 
                      * (VDATOSPEDEXPDESCxPedExp.PID_POR_DEF / 100)) AS MONTOIGIMXUSD, 
	           SUM((ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC) 
                      * (VDATOSPEDEXPDESCxPedExp.PID_POR_DEF / 100)* VDATOSPEDEXPDESCxPedExp.PI_TIP_CAM) AS MONTOIGIMXMN,
		FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         FACTEXPDET INNER JOIN
                      FACTEXP ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO INNER JOIN
                      PEDIMPDETB ON FACTEXP.PI_CODIGO = PEDIMPDETB.PI_CODIGO INNER JOIN
                      PEDIMPDET PEDIMPDET_1 ON PEDIMPDETB.PIB_INDICEB = PEDIMPDET_1.PIB_INDICEB AND 
                      FACTEXPDET.PID_INDICEDLIGA = PEDIMPDET_1.PID_INDICED INNER JOIN
                      PEDIMP PEDIMP_2 ON PEDIMPDETB.PI_CODIGO = PEDIMP_2.PI_CODIGO INNER JOIN
                      VDATOSPEDEXPDESCxPedExp ON FACTEXPDET.FED_INDICED = VDATOSPEDEXPDESCxPedExp.KAP_INDICED_FACT
WHERE PEDIMP_2.PI_ESTATUS <>'R'
AND PEDIMPDETB.PI_CODIGO=07503 
GROUP BY PEDIMPDETB.PI_CODIGO, PEDIMPDETB.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, PEDIMPDETB.PIB_INDICEB, 
                      FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO
UNION
SELECT     PEDIMPDETB.PI_CODIGO, PEDIMPDETB.PIB_INDICEB, PEDIMPDETB.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, 
                      SUM(ISNULL(ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC, 0)) 
                      AS VALORMERCNOORIGUSD, SUM(ISNULL(ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC, 0)*VDATOSPEDEXPDESCxPedExp.PI_TIP_CAM) 
                      AS VALORMERCNOORIGMN, SUM((ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC) 
                      * (VDATOSPEDEXPDESCxPedExp.PID_POR_DEF / 100)) AS MONTOIGIMXUSD, 
	           SUM((ROUND(VDATOSPEDEXPDESCxPedExp.KAP_COS_UNI, 6) * VDATOSPEDEXPDESCxPedExp.KAP_CANTDESC) 
                      * (VDATOSPEDEXPDESCxPedExp.PID_POR_DEF / 100)* VDATOSPEDEXPDESCxPedExp.PI_TIP_CAM) AS MONTOIGIMXMN,
		FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         FACTEXPDET INNER JOIN
                      FACTEXP ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO INNER JOIN
                      PEDIMPDETB ON FACTEXP.PI_RECTIFICA = PEDIMPDETB.PI_CODIGO INNER JOIN
                      PEDIMPDET PEDIMPDET_1 ON PEDIMPDETB.PIB_INDICEB = PEDIMPDET_1.PIB_INDICEB AND 
                      FACTEXPDET.PID_INDICEDLIGAR1 = PEDIMPDET_1.PID_INDICED INNER JOIN
                      PEDIMP PEDIMP_2 ON PEDIMPDETB.PI_CODIGO = PEDIMP_2.PI_CODIGO INNER JOIN
                      VDATOSPEDEXPDESCxPedExp ON FACTEXPDET.FED_INDICED = VDATOSPEDEXPDESCxPedExp.KAP_INDICED_FACT
WHERE PEDIMPDETB.PI_CODIGO=07503 
GROUP BY PEDIMPDETB.PI_CODIGO, PEDIMPDETB.AR_EXPFO, PEDIMPDETB.PIB_SECUENCIA, PEDIMPDETB.PIB_INDICEB, 
                      FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO
GO
