SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW dbo.VBOM_STRUCT
with encryption as
SELECT     BST_CODIGO, BSU_SUBENSAMBLE, BST_HIJO, BST_INCORPOR, BST_DISCH, dbo.MAESTRO.TI_CODIGO, ME_CODIGO, FACTCONV
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO 






GO
