SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO







CREATE VIEW dbo.VPEDIMPDETIDENTIFICA
with encryption as
SELECT     PIID_CODIGO, PIB_INDICEB, IDE_CODIGO, IDED_CODIGO, PIID_DESC, PIID_DESC2, IDED_CODIGO2, IDED_CODIGO3, PIID_DESC3
FROM         dbo.PEDIMPDETIDENTIFICA
WHERE     (PIID_TIPO = 'N')



GO
