SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






















CREATE VIEW dbo.VREPANUALIMPTEMPACTFIJ
with encryption as
-- h3 que no estan recificados
SELECT     dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_CODIGO, SUM(dbo.VPEDIMP.PI_TIP_CAM * dbo.PEDIMPDET.PID_CTOT_DLS) AS valor, 
                      SUM(dbo.PEDIMPDET.PID_CTOT_DLS) AS PID_CTOT_DLS, dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.MA_GENERICO, dbo.PEDIMPDET.AR_IMPMX
FROM         dbo.PEDIMPDET LEFT OUTER JOIN
                      dbo.TIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.TIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO RIGHT OUTER JOIN
                      dbo.DECANUALNVA INNER JOIN
                      dbo.VPEDIMP ON dbo.DECANUALNVA.DAN_INICIO <= dbo.VPEDIMP.PI_FEC_ENT AND dbo.DECANUALNVA.DAN_FINAL >= dbo.VPEDIMP.PI_FEC_ENT ON
                       dbo.PEDIMPDET.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
WHERE     (dbo.PEDIMPDET.PID_IMPRIMIR='S') and  (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'IM' AND dbo.VPEDIMP.PI_ESTATUS <> 'R')  
AND  (dbo.TIPO.TI_CATEGM = '3' OR dbo.TIPO.TI_CATEGM = '4' )  
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_CODIGO,  dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.MA_GENERICO, dbo.PEDIMPDET.AR_IMPMX
UNION
-- rectificaciones que son h3
SELECT     dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_CODIGO, SUM(dbo.VPEDIMP.PI_TIP_CAM * dbo.PEDIMPDET.PID_CTOT_DLS) AS valor, 
                      SUM(dbo.PEDIMPDET.PID_CTOT_DLS), dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.MA_GENERICO, dbo.PEDIMPDET.AR_IMPMX
FROM         dbo.PEDIMPDET LEFT OUTER JOIN
                      dbo.TIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.TIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO RIGHT OUTER JOIN
                      dbo.DECANUALNVA INNER JOIN
                      dbo.VPEDIMP ON dbo.DECANUALNVA.DAN_INICIO <= dbo.VPEDIMP.PI_FEC_ENT AND dbo.DECANUALNVA.DAN_FINAL >= dbo.VPEDIMP.PI_FEC_ENT ON
                       dbo.PEDIMPDET.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
WHERE     (dbo.PEDIMPDET.PID_IMPRIMIR='S') and  dbo.CONFIGURACLAVEPED.CCP_TIPO = 'RE' AND dbo.VPEDIMP.CP_RECTIFICA IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED
                            WHERE      CCP_TIPO = 'IM') AND  (dbo.TIPO.TI_CATEGM = '3' OR dbo.TIPO.TI_CATEGM = '4' )   
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_CODIGO,  dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.MA_GENERICO, dbo.PEDIMPDET.AR_IMPMX
UNION
-- virtuales que no estas rectificados
SELECT     dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_CODIGO, SUM(dbo.VPEDIMP.PI_TIP_CAM * dbo.PEDIMPDET.PID_CTOT_DLS) AS valor, 
                      SUM(dbo.PEDIMPDET.PID_CTOT_DLS), dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.MA_GENERICO, dbo.PEDIMPDET.AR_IMPMX
FROM         dbo.PEDIMPDET LEFT OUTER JOIN
                      dbo.TIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.TIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO RIGHT OUTER JOIN
                      dbo.DECANUALNVA INNER JOIN
                      dbo.VPEDIMP ON dbo.DECANUALNVA.DAN_INICIO <= dbo.VPEDIMP.PI_FEC_ENT AND dbo.DECANUALNVA.DAN_FINAL >= dbo.VPEDIMP.PI_FEC_ENT ON
                       dbo.PEDIMPDET.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
WHERE     (dbo.TIPO.TI_CATEGM = '3' OR dbo.TIPO.TI_CATEGM = '4' ) AND (dbo.PEDIMPDET.PID_IMPRIMIR='S') and 
	(dbo.CONFIGURACLAVEPED.CCP_TIPO IN ('IV', 'VT') AND dbo.VPEDIMP.PI_ESTATUS <> 'R') 
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_CODIGO,  dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.MA_GENERICO, dbo.PEDIMPDET.AR_IMPMX                    
UNION
--r1 virtuales
SELECT     dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_CODIGO, SUM(dbo.VPEDIMP.PI_TIP_CAM * dbo.PEDIMPDET.PID_CTOT_DLS) AS valor, 
                      SUM(dbo.PEDIMPDET.PID_CTOT_DLS), dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.MA_GENERICO, dbo.PEDIMPDET.AR_IMPMX
FROM         dbo.PEDIMPDET LEFT OUTER JOIN
                      dbo.TIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.TIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO RIGHT OUTER JOIN
                      dbo.DECANUALNVA INNER JOIN
                      dbo.VPEDIMP ON dbo.DECANUALNVA.DAN_INICIO <= dbo.VPEDIMP.PI_FEC_ENT AND dbo.DECANUALNVA.DAN_FINAL >= dbo.VPEDIMP.PI_FEC_ENT ON
                       dbo.PEDIMPDET.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
WHERE     (dbo.TIPO.TI_CATEGM = '3' OR dbo.TIPO.TI_CATEGM = '4' ) AND (dbo.PEDIMPDET.PID_IMPRIMIR='S') and 
                    dbo.CONFIGURACLAVEPED.CCP_TIPO = 'RE' AND dbo.VPEDIMP.CP_RECTIFICA IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED
                            WHERE      CCP_TIPO IN ('IV', 'VT'))
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_CODIGO,  dbo.PEDIMPDET.PID_NOMBRE, dbo.PEDIMPDET.MA_GENERICO, dbo.PEDIMPDET.AR_IMPMX





















GO
