SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






/*union de todas las vistas*/
CREATE VIEW dbo.VEXHIBIT_A
with encryption as
SELECT     dbo.COSTSUBPER.CS_CODIGO, dbo.COSTSUBPER.CL_CODIGO, ISNULL(dbo.VEXHIBIT_A_11.CSA_98020040, 0) AS CSA_98020040, ISNULL(dbo.VEXHIBIT_A_9.CSA_98020080, 0) 
                      AS CSA_98020080, ISNULL(dbo.VEXHIBIT_A_10.CSA_98010010, 0) AS CSA_98010010, ISNULL(dbo.VEXHIBIT_A_12.CSA_98020060, 0) 
                      AS CSA_98020060, ISNULL(dbo.VEXHIBIT_A_1.CSA_NG_MAT, 0) AS CSA_NG_MAT, ISNULL(dbo.VEXHIBIT_A_1.CSA_GRAV_MAT, 0) AS CSA_GRAV_MAT, 
                      ISNULL(dbo.VEXHIBIT_A_1.CSA_EMP_US, 0) AS CSA_EMP_US, ISNULL(dbo.VEXHIBIT_A_1.CSA_EMP_FO, 0) AS CSA_EMP_FO, 
                      ISNULL(dbo.VEXHIBIT_A_2.CSA_NG_DESP, 0) AS CSA_NG_DESP, ISNULL(dbo.VEXHIBIT_A_2.CSA_GRAV_DESP, 0) AS CSA_GRAV_DESP, 
                      ISNULL(dbo.VEXHIBIT_A_3.CSA_VA_GRAV, 0) AS CSA_VA_GRAV, ISNULL(dbo.VEXHIBIT_A_3.CSA_MO_DIR_FO, 0) AS CSA_MO_DIR_FO
FROM         dbo.VEXHIBIT_A_10 RIGHT OUTER JOIN
                      dbo.VEXHIBIT_A_2 RIGHT OUTER JOIN
                      dbo.VEXHIBIT_A_3 RIGHT OUTER JOIN
                      dbo.COSTSUBPER ON dbo.VEXHIBIT_A_3.CS_CODIGO = dbo.COSTSUBPER.CS_CODIGO ON 
                      dbo.VEXHIBIT_A_2.CS_CODIGO = dbo.COSTSUBPER.CS_CODIGO LEFT OUTER JOIN
                      dbo.VEXHIBIT_A_9 ON dbo.COSTSUBPER.CS_CODIGO = dbo.VEXHIBIT_A_9.CS_CODIGO ON 
                      dbo.VEXHIBIT_A_10.CS_CODIGO = dbo.COSTSUBPER.CS_CODIGO LEFT OUTER JOIN
                      dbo.VEXHIBIT_A_12 ON dbo.COSTSUBPER.CS_CODIGO = dbo.VEXHIBIT_A_12.CS_CODIGO LEFT OUTER JOIN
                      dbo.VEXHIBIT_A_11 ON dbo.COSTSUBPER.CS_CODIGO = dbo.VEXHIBIT_A_11.CS_CODIGO LEFT OUTER JOIN
                      dbo.VEXHIBIT_A_1 ON dbo.COSTSUBPER.CS_CODIGO = dbo.VEXHIBIT_A_1.CS_CODIGO





GO
