SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW dbo.VFillPedImpDet
with encryption as
SELECT     ISNULL(MA_CODIGO, 0) AS MA_CODIGO, ISNULL(FID_NOPARTE, '') AS FID_NOPARTE, FID_NOMBRE, FID_NAME, ISNULL(FID_COS_TOT, 0) 
                      AS FID_COS_TOT, ME_CODIGO, ISNULL(MA_GENERICO, 0) AS MA_GENERICO, ISNULL(AR_IMPMX, 0) AS AR_IMPMX, ISNULL(AR_EXPFO, 0) 
                      AS AR_EXPFO, FID_SEC_IMP, ISNULL(FID_DEF_TIP, 'G') AS FID_DEF_TIP, ISNULL(FID_POR_DEF, - 1) AS FID_POR_DEF, ISNULL(TI_CODIGO, 10) 
                      AS TI_CODIGO, PA_CODIGO, SPI_CODIGO, ME_GEN, PR_CODIGO, ISNULL(FID_ORD_COMP, 0) AS FID_ORD_COMP, FID_PADREKITINSERT, 
                      ISNULL(CS_CODIGO, 8) AS CS_CODIGO, ISNULL(FID_NOPARTEAUX, '') AS FID_NOPARTEAUX, FID_INDICED, ISNULL(FID_CANT_ST, 0) 
                      AS FID_CANT_ST, ISNULL(EQ_GEN, 1) AS EQ_GEN, ISNULL(EQ_IMPMX, 1) AS EQ_IMPMX, FID_GENERA_EMPDET, ROUND(FID_PES_NET,6) AS FID_PES_NET, 
                      ROUND(FID_PES_BRU,6) AS FID_PES_BRU, ISNULL(ME_ARIMPMX,0) AS ME_ARIMPMX, FI_CODIGO, isnull(FID_PIDSECUENCIA,0) FID_PIDSECUENCIA, 
	       	 'PID_PES_UNIKG'=case when isnull(FID_CANT_ST,0)>0 then(case when FID_PES_NET= 0 then  ROUND(FID_PES_BRU/isnull(FID_CANT_ST,0),6) else ROUND(FID_PES_NET/isnull(FID_CANT_ST,0),10) end) else 0 end
FROM         dbo.FACTIMPDET

GO
