SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VEXHIBIT_C247MAXMPF
with encryption as
SELECT COSTSUBPER.CS_CODIGO, 
    MAX(VEXHIBIT_B_BASE247.ETA_DLLS_MPF) 
    AS MAX_MPF_PAG
FROM VEXHIBIT_B_BASE247 FULL OUTER JOIN
    COSTSUBPER ON 
    VEXHIBIT_B_BASE247.ET_FEC_ENTRYS >= COSTSUBPER.CS_FECHAINI
     AND 
    VEXHIBIT_B_BASE247.ET_FEC_ENTRYS <= COSTSUBPER.CS_FECHAFIN
GROUP BY COSTSUBPER.CS_CODIGO





GO
