SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO











CREATE VIEW dbo.VFACTFLETE
with encryption as
SELECT     PI_CODIGO, FI_CODIGO, FI_FACTAGRU, FI_FLETE, FI_SEGURO, FI_EMBALAJE, FI_OTROS, FI_TOTALB, FI_PESOKG, FI_TRAC_MX
FROM         VFACTIMPFLETE
WHERE PI_RECTIFICA=-1
UNION
SELECT     PI_RECTIFICA, FI_CODIGO, FI_FACTAGRU, FI_FLETE, FI_SEGURO, FI_EMBALAJE, FI_OTROS, FI_TOTALB, FI_PESOKG, FI_TRAC_MX
FROM         VFACTIMPFLETE
WHERE PI_RECTIFICA<>-1
UNION
SELECT     PI_CODIGO, FE_CODIGO, FE_FACTAGRU, FE_FLETE, FE_SEGURO, FE_EMBALAJE, FE_OTROS, FE_TOTALB, FE_PESOKG, FE_TRAC_MX1
FROM         VFACTEXPFLETE
WHERE PI_RECTIFICA=-1
UNION
SELECT     PI_RECTIFICA, FE_CODIGO, FE_FACTAGRU, FE_FLETE, FE_SEGURO, FE_EMBALAJE, FE_OTROS, FE_TOTALB, FE_PESOKG, FE_TRAC_MX1
FROM         VFACTEXPFLETE
WHERE PI_RECTIFICA<>-1































GO
