SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE VIEW dbo.VR1ACTUAL
with encryption as
SELECT     dbo.VR1ACTUAL1.AGT_PATENTE, dbo.VR1ACTUAL1.R1H_PEDIMENTOR1ANT, dbo.VR1ACTUAL1.CP_CODIGO, dbo.VR1ACTUAL1.R1H_FECHAPAGO, 
                      dbo.VR1ACTUAL1.AD_CODIGOANT, dbo.VR1ACTUAL1.PI_CODIGO
FROM         dbo.VR1ACTUAL3 INNER JOIN
                      dbo.VR1ACTUAL1 ON dbo.VR1ACTUAL3.R1H_PEDIMENTOR1ANT = dbo.VR1ACTUAL1.R1H_PEDIMENTOR1ANT AND 
                      dbo.VR1ACTUAL3.R1H_FECHAPAGO = dbo.VR1ACTUAL1.R1H_FECHAPAGO AND dbo.VR1ACTUAL3.PI_CODIGO = dbo.VR1ACTUAL1.PI_CODIGO





GO
