SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VENTRYSUMDET
with encryption as
SELECT     FACTEXP.ET_CODIGO, FACTEXPDET.FE_CODIGO, FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO, FACTEXPDET.FED_NOPARTE, FACTEXPDET.FED_CANT AS ETD_CANT, 
AR_IMPFO AS AR_CODIGO, AR_NG_EMP, FED_NAME AS ETD_NAME, PA_CODIGO, EQ_IMPFO, AR_ORIG, FED_RATEIMPFO AS ETD_RATE,FED_NAFTA AS ETD_NAFTA, 
case WHEN CFQ_TIPO <> 'D' and CFQ_TIPO <> 'T' and
         (CFT_TIPO = 'P' or CFT_TIPO = 'S') then (CASE when (select CF_PEDEXPVAUSA from configuracion)= 'S' then
           (FACTEXPDET.FED_CANT * (FACTEXPDET.FED_GRA_GI_MX + FACTEXPDET.FED_GRA_GI + FACTEXPDET.FED_GRA_MO)) * FE_TIPOCAMBIOUSD
           else
           (FACTEXPDET.FED_CANT * (FACTEXPDET.FED_GRA_GI_MX + FACTEXPDET.FED_GRA_MO))* FE_TIPOCAMBIOUSD end)
	else 0 end as ETD_GRAV_VA,
CASE WHEN CFQ_TIPO <> 'D' and CFQ_TIPO <> 'T' and (CFT_TIPO = 'P' or CFT_TIPO = 'S') then   
          FACTEXPDET.FED_CANT * ((FACTEXPDET.FED_GRA_MP + FACTEXPDET.FED_GRA_ADD + FACTEXPDET.FED_GRA_EMP + FACTEXPDET.FED_NG_MP +
                                               FACTEXPDET.FED_NG_ADD) - FACTEXPDET.FED_NG_USA) * FE_TIPOCAMBIOUSD
	ELSE (CASE WHEN FED_NAFTA =  'N' then  FED_CANT * FED_COS_UNI*FE_TIPOCAMBIOUSD ELSE 0 END) END AS ETD_GRAV_MAT,
case WHEN CFQ_TIPO <> 'D' and CFQ_TIPO <> 'T' and
         (CFT_TIPO = 'P' or CFT_TIPO = 'S') then (CASE when (select CF_PEDEXPVAUSA from configuracion)= 'S' then
           FACTEXPDET.FED_CANT * (FACTEXPDET.FED_NG_USA) * FE_TIPOCAMBIOUSD
           else
           FACTEXPDET.FED_CANT * (FACTEXPDET.FED_NG_USA + FACTEXPDET.FED_GRA_GI) * FE_TIPOCAMBIOUSD end)
	else (CASE WHEN FED_NAFTA =  'S' AND CFQ_TIPO <> 'E' then  FED_CANT * FED_COS_UNI * FE_TIPOCAMBIOUSD ELSE 0 END) end as ETD_NG_MAT,
case WHEN CFQ_TIPO <> 'D' and CFQ_TIPO <> 'T' and
         (CFT_TIPO = 'P' or CFT_TIPO = 'S') then FACTEXPDET.FED_CANT * FACTEXPDET.FED_NG_EMP * FE_TIPOCAMBIOUSD
	else (CASE WHEN FED_NAFTA =  'S' AND CFQ_TIPO = 'E' then  FED_CANT * FED_COS_UNI * FE_TIPOCAMBIOUSD ELSE 0 END) end as ETD_NG_EMP,
0 AS ETD_NG_VA, FED_COS_TOT* FE_TIPOCAMBIOUSD AS ETD_COS_TOT, 
FACTEXPDET.TI_CODIGO, CASE  WHEN FED_RETRABAJO='R' THEN 'S' ELSE 'N' END AS ETD_RETRABAJO, ETA_CODIGO
FROM         FACTEXPDET INNER JOIN
                      FACTEXP ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO INNER JOIN
                      CONFIGURATEMBARQUE ON FACTEXP.TQ_CODIGO = CONFIGURATEMBARQUE.TQ_CODIGO INNER JOIN
                      CONFIGURATIPO ON FACTEXPDET.TI_CODIGO = CONFIGURATIPO.TI_CODIGO









GO
