SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VNAFTAFACTEXP
with encryption as
SELECT     dbo.FACTEXPDET.FED_INDICED, dbo.NAFTA.NFT_CODIGO, dbo.NAFTA.MA_CODIGO, dbo.NAFTA.SPI_CODIGO, dbo.NAFTA.NFT_FABRICA, 
                      dbo.NAFTA.NFT_CRITERIO, dbo.NAFTA.NFT_NETCOST, dbo.NAFTA.NFT_OTRASINST, dbo.NAFTA.PA_CLASE, dbo.CONFIGURATIPO.CFT_TIPO
FROM         dbo.NAFTA INNER JOIN
                      dbo.FACTEXPDET ON dbo.NAFTA.MA_CODIGO = dbo.FACTEXPDET.MA_CODIGO INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO AND dbo.NAFTA.NFT_PERINI <= dbo.FACTEXP.FE_FECHA AND 
                      dbo.NAFTA.NFT_PERFIN >= dbo.FACTEXP.FE_FECHA LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.FACTEXPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
WHERE     (dbo.NAFTA.SPI_CODIGO IN
                          (SELECT     spi_codigo
                            FROM          spi
                            WHERE      spi_clave = 'nafta')) AND (dbo.CONFIGURATIPO.CFT_TIPO = 'P' OR
                      dbo.CONFIGURATIPO.CFT_TIPO = 'S')
AND dbo.NAFTA.NFT_CODIGO IN 
(SELECT MAX(N1.NFT_CODIGO) FROM NAFTA N1 WHERE N1.MA_CODIGO=dbo.NAFTA.MA_CODIGO AND N1.NFT_PERINI <= dbo.FACTEXP.FE_FECHA AND 
                      N1.NFT_PERFIN >= dbo.FACTEXP.FE_FECHA AND N1.SPI_CODIGO= dbo.NAFTA.SPI_CODIGO and NFT_CALIFICO='S')


GO
