SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW dbo.VHISTORICOR1
with encryption as
SELECT  TOP 100 PERCENT PEDIMENTOANT, FECHAPAGO, PI_CODIGO, CP_CLAVE
FROM (SELECT     CONVERT(varchar(2), RIGHT(YEAR(dbo.PEDIMPR1HIST.R1H_FECHAPAGO), 2)) +' '+
                      + dbo.ADUANA.AD_CLAVE collate database_default +' '+ AGENCIAPATENTE_1.AGT_PATENTE collate database_default +' '+ dbo.PEDIMPR1HIST.R1H_PEDIMENTOR1ANT collate database_default AS PEDIMENTOANT, 
                      dbo.PEDIMPR1HIST.R1H_FECHAPAGO AS FECHAPAGO, dbo.PEDIMPR1HIST.PI_CODIGO, 'R1'  AS CP_CLAVE
FROM         dbo.AGENCIAPATENTE AGENCIAPATENTE_1 INNER JOIN
                      dbo.PEDIMPR1HIST ON AGENCIAPATENTE_1.AGT_CODIGO = dbo.PEDIMPR1HIST.AGT_R1ANT INNER JOIN
                      dbo.ADUANA ON dbo.PEDIMPR1HIST.AD_CODIGOANT = dbo.ADUANA.AD_CODIGO
UNION
SELECT     CONVERT(varchar(2), RIGHT(YEAR(PEDIMP_1.PI_FEC_PAG), 2)) 
                      + ' ' + + dbo.ADUANA.AD_CLAVE + ' ' + dbo.AGENCIAPATENTE.AGT_PATENTE + ' ' + PEDIMP_1.PI_FOLIO AS PEDIMENTOANT, 
		PEDIMP_1.PI_FEC_PAG AS FECHAPAGO, 
                      dbo.PEDIMP.PI_CODIGO, dbo.CLAVEPED.CP_CLAVE
FROM         dbo.PEDIMP INNER JOIN
                      dbo.PEDIMP PEDIMP_1 ON dbo.PEDIMP.PI_RECTIFICA = PEDIMP_1.PI_CODIGO LEFT OUTER JOIN
                      dbo.CLAVEPED ON PEDIMP_1.CP_CODIGO = dbo.CLAVEPED.CP_CODIGO LEFT OUTER JOIN
                      dbo.AGENCIAPATENTE ON PEDIMP_1.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO LEFT OUTER JOIN
                      dbo.ADUANA ON PEDIMP_1.AD_DES = dbo.ADUANA.AD_CODIGO) HISTORICOR1
ORDER BY FECHAPAGO DESC









GO
