SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW dbo.VEXHIBIT_A_9Det
with encryption as
SELECT     SUM(CSA_98020080) AS CSA_98020080, CS_CODIGO, FE_CODIGO, AR_FRACCION
FROM        (SELECT     SUM((dbo.FACTEXPDET.FED_NG_USA) * dbo.FACTEXPDET.FED_CANT) AS CSA_98020080, 
	                      dbo.VRELCSFACTEXP.CS_CODIGO, dbo.FACTEXP.FE_CODIGO, ARANCEL_1.AR_FRACCION
	FROM         dbo.ARANCEL RIGHT OUTER JOIN
	                      dbo.ARANCEL ARANCEL_1 RIGHT OUTER JOIN
	                      dbo.CONFIGURACION INNER JOIN
	                      dbo.FACTEXPDET ON dbo.CONFIGURACION.CF_PAIS_USA <> dbo.FACTEXPDET.PA_CODIGO ON 
	                      ARANCEL_1.AR_CODIGO = dbo.FACTEXPDET.AR_ORIG LEFT OUTER JOIN
	                      dbo.CONFIGURATIPO ON dbo.FACTEXPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO ON 
	                      dbo.ARANCEL.AR_CODIGO = dbo.FACTEXPDET.AR_IMPFO RIGHT OUTER JOIN
	                      dbo.CONFIGURATEMBARQUE RIGHT OUTER JOIN
	                      dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.VRELCSFACTEXP ON dbo.FACTEXP.FE_CODIGO = dbo.VRELCSFACTEXP.FE_CODIGO ON 
	                      dbo.CONFIGURATEMBARQUE.TQ_CODIGO = dbo.FACTEXP.TQ_CODIGO ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
	WHERE     (dbo.CONFIGURATEMBARQUE.CFQ_TIPO <> 'D') AND (dbo.FACTEXP.TN_CODIGO = 2 OR
	                      dbo.FACTEXP.TN_CODIGO = 6 OR dbo.FACTEXP.TN_CODIGO = 8 OR dbo.FACTEXP.TN_CODIGO = 9 OR
	                      dbo.FACTEXP.TN_CODIGO = 7 OR
	                      dbo.FACTEXP.TN_CODIGO = 5) AND (REPLACE(dbo.ARANCEL.AR_FRACCION, '.', '') LIKE '98020080%' OR 
	                      REPLACE(ARANCEL_1.AR_FRACCION, '.', '') LIKE '98020080%')
		AND dbo.FACTEXPDET.TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE CFT_TIPO IN ('P', 'S'))
	GROUP BY dbo.VRELCSFACTEXP.CS_CODIGO, dbo.FACTEXP.FE_CODIGO, ARANCEL_1.AR_FRACCION
	UNION
	SELECT     SUM((dbo.FACTEXPDET.FED_COS_UNI) * dbo.FACTEXPDET.FED_CANT) AS CSA_98020080, 
	                      dbo.VRELCSFACTEXP.CS_CODIGO, dbo.FACTEXP.FE_CODIGO, ARANCEL.AR_FRACCION
	FROM         dbo.ARANCEL RIGHT OUTER JOIN
	                      dbo.ARANCEL ARANCEL_1 RIGHT OUTER JOIN
	                      dbo.CONFIGURACION INNER JOIN
	                      dbo.FACTEXPDET ON dbo.CONFIGURACION.CF_PAIS_USA <> dbo.FACTEXPDET.PA_CODIGO ON 
	                      ARANCEL_1.AR_CODIGO = dbo.FACTEXPDET.AR_ORIG LEFT OUTER JOIN
	                      dbo.CONFIGURATIPO ON dbo.FACTEXPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO ON 
	                      dbo.ARANCEL.AR_CODIGO = dbo.FACTEXPDET.AR_IMPFO RIGHT OUTER JOIN
	                      dbo.CONFIGURATEMBARQUE RIGHT OUTER JOIN
	                      dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.VRELCSFACTEXP ON dbo.FACTEXP.FE_CODIGO = dbo.VRELCSFACTEXP.FE_CODIGO ON 
	                      dbo.CONFIGURATEMBARQUE.TQ_CODIGO = dbo.FACTEXP.TQ_CODIGO ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
	WHERE     (dbo.CONFIGURATEMBARQUE.CFQ_TIPO <> 'D') AND (dbo.FACTEXP.TN_CODIGO = 2 OR
	                      dbo.FACTEXP.TN_CODIGO = 6 OR dbo.FACTEXP.TN_CODIGO = 8 OR dbo.FACTEXP.TN_CODIGO = 9 OR
	                      dbo.FACTEXP.TN_CODIGO = 7 OR
	                      dbo.FACTEXP.TN_CODIGO = 5) AND (REPLACE(dbo.ARANCEL.AR_FRACCION, '.', '') LIKE '98020080%' OR 
	                      REPLACE(ARANCEL_1.AR_FRACCION, '.', '') LIKE '98020080%')
		AND dbo.FACTEXPDET.TI_CODIGO NOT IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE CFT_TIPO IN ('P', 'S'))
	GROUP BY dbo.VRELCSFACTEXP.CS_CODIGO, dbo.FACTEXP.FE_CODIGO, ARANCEL.AR_FRACCION) EXHIBIT_A_9a
GROUP BY CS_CODIGO, FE_CODIGO, AR_FRACCION


GO
