SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.numerossinbom
AS
SELECT     TOP 100 PERCENT dbo.PEDIMP.PI_FOLIO AS Pedimento, dbo.PEDIMP.PI_FEC_ENT AS Fecha, dbo.CLAVEPED.CP_CLAVE AS Clave, 
                      dbo.PEDIMPDET.PID_NOPARTE AS NoParte, dbo.PEDIMPDET.PID_NOMBRE AS Descripcion, dbo.PEDIMPDET.PID_CTOT_DLS AS Valor, 
                      dbo.PEDIMPDET.TI_CODIGO AS Tipo, dbo.PEDIMPDET.PID_CANT AS CantImportada, dbo.FACTEXPDET.FED_CANT AS CantExportada, 
                      dbo.FACTEXP.FE_FOLIO AS FactExp, dbo.FACTEXPDET.FED_INDICED AS Indice, dbo.PEDIMPDET.PID_INDICED, dbo.MAESTRO.MA_NOPARTE
FROM         dbo.PIDescarga RIGHT OUTER JOIN
                      dbo.CLAVEPED INNER JOIN
                      dbo.PEDIMP ON dbo.CLAVEPED.CP_CODIGO = dbo.PEDIMP.CP_CODIGO INNER JOIN
                      dbo.PEDIMPDET ON dbo.PEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO ON 
                      dbo.PIDescarga.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO LEFT OUTER JOIN
                      dbo.MAESTROSUST INNER JOIN
                      dbo.MAESTRO ON dbo.MAESTROSUST.MA_CODIGO = dbo.MAESTRO.MA_CODIGO ON 
                      dbo.PEDIMPDET.MA_CODIGO = dbo.MAESTROSUST.MA_CODIGOSUST LEFT OUTER JOIN
                      dbo.FACTEXPDET INNER JOIN
                      dbo.FACTEXP ON dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO ON 
                      dbo.PEDIMPDET.MA_CODIGO = dbo.FACTEXPDET.MA_CODIGO LEFT OUTER JOIN
                      dbo.BOM_STRUCT ON dbo.PEDIMPDET.PID_NOPARTE = dbo.BOM_STRUCT.BST_NOPARTE
WHERE     (dbo.PEDIMPDET.PID_IMPRIMIR = 's') AND (dbo.BOM_STRUCT.BST_NOPARTE IS NULL) AND (dbo.CLAVEPED.CP_CLAVE IN ('h2', 'v1')) AND 
                      (NOT (dbo.PEDIMPDET.TI_CODIGO IN (14, 9))) AND (dbo.PIDescarga.PID_SALDOGEN > 0)
ORDER BY dbo.PEDIMPDET.PID_NOPARTE, dbo.PEDIMP.PI_FEC_ENT, dbo.FACTEXPDET.FED_INDICED
GO
