SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO































CREATE VIEW dbo.VCOSTORETRA
with encryption as
SELECT     dbo.RETRABAJO.FETR_INDICED, SUM(dbo.VMAESTROCOST.MA_COSTO * dbo.RETRABAJO.RE_INCORPOR) AS MA_COSTO, dbo.RETRABAJO.MA_HIJO, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.MAESTRO.MA_DEF_TIP, dbo.MAESTRO.MA_SERVICIO, dbo.RETRABAJO.PA_ORIGEN, dbo.RETRABAJO.FETR_NAFTA
FROM         dbo.RETRABAJO LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.RETRABAJO.MA_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.RETRABAJO.TI_HIJO = dbo.CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.VMAESTROCOST ON dbo.RETRABAJO.MA_HIJO = dbo.VMAESTROCOST.MA_CODIGO
GROUP BY dbo.RETRABAJO.FETR_INDICED, dbo.RETRABAJO.MA_HIJO, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.MAESTRO.MA_DEF_TIP, dbo.MAESTRO.MA_SERVICIO, dbo.RETRABAJO.PA_ORIGEN, dbo.RETRABAJO.FETR_NAFTA
union
SELECT     dbo.FACTEXPDET.FED_INDICED, SUM(dbo.VMAESTROCOST.MA_COSTO * dbo.FACTEXPDET.FED_CANT) AS MA_COSTO, dbo.FACTEXPDET.MA_CODIGO, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.MAESTRO.MA_DEF_TIP, dbo.MAESTRO.MA_SERVICIO, dbo.MAESTRO.PA_ORIGEN, 'S'
FROM         dbo.FACTEXPDET LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.FACTEXPDET.MA_CODIGO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.FACTEXPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.VMAESTROCOST ON dbo.FACTEXPDET.MA_CODIGO = dbo.VMAESTROCOST.MA_CODIGO
WHERE dbo.FACTEXPDET.FED_RETRABAJO='R'
GROUP BY dbo.FACTEXPDET.FED_INDICED, dbo.FACTEXPDET.MA_CODIGO, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.MAESTRO.MA_DEF_TIP, dbo.MAESTRO.MA_SERVICIO, dbo.MAESTRO.PA_ORIGEN

























GO
