SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


/*INVENTARIO PERPETUO
*/
CREATE VIEW dbo.VINVENTARIOEXISTE
with encryption as
SELECT     TOP 100 PERCENT dbo.ENTSALALMDET.END_NOPARTE, MAX(dbo.ENTSALALMDET.END_NOMBRE) AS END_NOMBRE, 
                      MAX(dbo.ENTSALALMDET.END_NAME) AS END_NAME, SUM(dbo.ENTSALALMSALDO.END_SALDOALM) AS END_SALDOALM, 
                      MEDIDA_2.ME_CORTO AS ME_ALM, dbo.ENTSALALMDET.EQ_ALM, dbo.TIPO.TI_NOMBRE, 
                      SUM(dbo.ENTSALALMSALDO.END_SALDOALM / ISNULL(dbo.ENTSALALMDET.EQ_ALM, 1)) AS END_SALDOCANT, MEDIDA_1.ME_CORTO, 
                      dbo.ENTSALALMSALDO.ALM_DESTINO, dbo.ENTSALALMDET.MA_CODIGO, dbo.ALMACEN.ALM_NOMBRE, dbo.ENTSALALMDET.TI_CODIGO, 
                      dbo.ENTSALALMDET.END_TIPOENTSAL
FROM         dbo.ENTSALALM LEFT OUTER JOIN
                      dbo.ALMACEN ON dbo.ENTSALALM.ALM_DESTINO = dbo.ALMACEN.ALM_CODIGO LEFT OUTER JOIN
                      dbo.ENTSALALMSALDO RIGHT OUTER JOIN
                      dbo.ENTSALALMDET ON dbo.ENTSALALMSALDO.END_INDICED = dbo.ENTSALALMDET.END_INDICED ON 
                      dbo.ENTSALALM.EN_CODIGO = dbo.ENTSALALMDET.EN_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_2 ON dbo.ENTSALALMDET.ME_ALM = MEDIDA_2.ME_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_1 ON dbo.ENTSALALMDET.ME_CODIGO = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
                      dbo.TIPO ON dbo.ENTSALALMDET.TI_CODIGO = dbo.TIPO.TI_CODIGO
WHERE     (dbo.ENTSALALM.ALM_DESTINO <> 0)
GROUP BY dbo.ENTSALALMDET.END_NOPARTE, dbo.ENTSALALMDET.END_NOMBRE, dbo.ENTSALALMDET.END_NAME, MEDIDA_2.ME_CORTO, 
                      MEDIDA_1.ME_CORTO, dbo.TIPO.TI_NOMBRE, dbo.ENTSALALMDET.EQ_ALM, MEDIDA_1.ME_CORTO, dbo.ENTSALALMSALDO.ALM_DESTINO, 
                      dbo.ENTSALALMDET.MA_CODIGO, dbo.ALMACEN.ALM_NOMBRE, dbo.ENTSALALMDET.TI_CODIGO, dbo.ENTSALALMDET.END_TIPOENTSAL
HAVING      (SUM(dbo.ENTSALALMSALDO.END_SALDOALM) > 0)
ORDER BY dbo.ENTSALALMDET.END_NOPARTE, dbo.ENTSALALMDET.END_NOMBRE

GO
