SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VPEDIMPDETDIDENTIFICA3
with encryption as
SELECT     PID_INDICED, PIID_CODIGO, PIID_CODIGO2, PI_CODIGO,
	(SELECT     dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO
			FROM         dbo.PEDIMPDETIDENTIFICA INNER JOIN
			                      dbo.PEDIMPDET ON dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB
			WHERE (dbo.PEDIMPDETIDENTIFICA.PIID_TIPO = 'N') AND dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE IN ('PS','TL','NE'))
	                            GROUP BY dbo.PEDIMPDET.PID_INDICED, dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO
	                            HAVING      (dbo.PEDIMPDET.PID_INDICED = dbo.VPEDIMPDETDIDENTIFICA2.PID_INDICED) AND 
	                                                   MIN(dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO) <> dbo.VPEDIMPDETDIDENTIFICA2.PIID_CODIGO AND 
	                                                   VPEDIMPDETDIDENTIFICA2.PIID_CODIGO <> dbo.VPEDIMPDETDIDENTIFICA2.PIID_CODIGO) AS PIID_CODIGO3
FROM         dbo.VPEDIMPDETDIDENTIFICA2
GROUP BY PIID_CODIGO, PID_INDICED, PIID_CODIGO2, PI_CODIGO












GO
