SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[tipo de envios export]
AS
SELECT     TOP 100 PERCENT dbo.FACTEXP.FE_FOLIO, dbo.FACTEXP.FE_FECHA, dbo.FACTEXP.FE_TRAC_MX1, dbo.TENVIO.TN_DESCRIP
FROM         dbo.FACTEXP INNER JOIN
                      dbo.TENVIO ON dbo.FACTEXP.TN_CODIGO = dbo.TENVIO.TN_CODIGO
WHERE     (dbo.FACTEXP.FE_FECHA >= CONVERT(DATETIME, '2004-09-01 00:00:00', 102) AND dbo.FACTEXP.FE_FECHA <= CONVERT(DATETIME, 
                      '2004-09-30 00:00:00', 102))
ORDER BY dbo.TENVIO.TN_DESCRIP, dbo.FACTEXP.FE_TRAC_MX1
GO
