SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VInvCantDescGen
with encryption as
SELECT     round(SUM(dbo.FACTEXPDET.FED_CANT * dbo.RETRABAJO.RE_INCORPOR * dbo.RETRABAJO.FACTCONV),6) AS CANT, MAESTRO.MA_GENERICO
FROM         dbo.RETRABAJO INNER JOIN
                      dbo.FACTEXPDET ON dbo.RETRABAJO.FETR_INDICED = dbo.FACTEXPDET.FED_INDICED LEFT OUTER JOIN
	dbo.FACTEXP ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	dbo.CONFIGURATFACT ON dbo.CONFIGURATFACT.TF_CODIGO = dbo.FACTEXP.TF_CODIGO LEFT OUTER JOIN MAESTRO ON dbo.RETRABAJO.MA_HIJO = MAESTRO.MA_CODIGO
	
WHERE     (dbo.FACTEXPDET.FED_RETRABAJO = 'E' OR
             dbo.FACTEXPDET.FED_RETRABAJO = 'D') AND (dbo.FACTEXP.FE_CANCELADO = 'N') 
	AND (dbo.CONFIGURATFACT.CFF_TIPODESCARGA = 'A') and (dbo.FACTEXP.FE_FECHA >= '07/01/2002') AND (dbo.FACTEXP.FE_FECHA <= '02/28/2003')
GROUP BY MAESTRO.MA_GENERICO









































GO
