SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VRETRABAJO
with encryption as
SELECT     RETRABAJO.RE_INDICER, RETRABAJO.TIPO_FACTRANS, RETRABAJO.FETR_CODIGO, RETRABAJO.FETR_INDICED, 
                      RETRABAJO.MA_HIJO, RETRABAJO.RE_NOPARTE, RETRABAJO.RE_INCORPOR, RETRABAJO.TI_HIJO, RETRABAJO.ME_CODIGO,
'MA_NAFTA'=CASE WHEN RETRABAJO.MA_HIJO in
	         (SELECT NAFTA.MA_CODIGO FROM NAFTA INNER JOIN SPI ON NAFTA.SPI_CODIGO = SPI.SPI_CODIGO	WHERE SPI.SPI_CLAVE = 'NAFTA'
		and NFT_CALIFICO='S'  AND NFT_PERINI<=GETDATE() AND NFT_PERFIN>=GETDATE()) 
	         and TI_HIJO IN (select ti_codigo from configuratipo where cft_tipo='P' or cft_tipo='S')
	         then 'S' else 
		(CASE WHEN RETRABAJO.MA_HIJO in (SELECT     CERTORIGMPDET.MA_CODIGO
		FROM         CERTORIGMPDET INNER JOIN
		                      CERTORIGMP ON CERTORIGMPDET.CMP_CODIGO = CERTORIGMP.CMP_CODIGO
		WHERE     CERTORIGMP.SPI_CODIGO IN (SELECT spi_codigo FROM spi  WHERE spi_clave = 'nafta')
		AND CERTORIGMP.CMP_ESTATUS='V' AND  CERTORIGMP.CMP_IFECHA<=GETDATE() AND CERTORIGMP.CMP_FECHATRANS>=GETDATE())
		THEN 'S' ELSE 'N' END 
		) end, VMAESTROCOST.MA_COSTO, MAESTRO.AR_IMPFO, MAESTRO.PA_ORIGEN
FROM         FACTEXP LEFT OUTER JOIN
                      RETRABAJO ON FACTEXP.FE_CODIGO = RETRABAJO.FETR_CODIGO LEFT OUTER JOIN MAESTRO
	ON RETRABAJO.MA_HIJO=MAESTRO.MA_CODIGO LEFT OUTER JOIN VMAESTROCOST ON
	RETRABAJO.MA_HIJO=VMAESTROCOST.MA_CODIGO




































GO
