SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

































CREATE VIEW dbo.VMAESTROPBOM
with encryption as
SELECT     dbo.MAESTRO.MA_CODIGO, dbo.MAESTRO.MA_NOPARTE, dbo.MAESTRO.MA_NAME, dbo.MAESTRO.MA_NOMBRE, dbo.MAESTRO.MA_TIP_ENS, 
                      dbo.MEDIDA.ME_CORTO, dbo.MAESTRO.MA_MODELO, --dbo.MAESTRO.MA_NAFTA,
		 'MA_NAFTA'=CASE WHEN dbo.MAESTRO.MA_CODIGO in
	         (SELECT NAFTA.MA_CODIGO FROM NAFTA INNER JOIN SPI ON NAFTA.SPI_CODIGO = SPI.SPI_CODIGO	WHERE SPI.SPI_CLAVE = 'NAFTA' and NFT_CALIFICO='S'
	         AND NFT_PERINI<=GETDATE() AND NFT_PERFIN>=GETDATE()) 
	         and TI_CODIGO IN (select ti_codigo from configuratipo where cft_tipo='P' or cft_tipo='S')
	         then 'S' else 
		(CASE WHEN dbo.MAESTRO.MA_CODIGO in (SELECT     CERTORIGMPDET.MA_CODIGO
		FROM         CERTORIGMPDET INNER JOIN
		                      CERTORIGMP ON CERTORIGMPDET.CMP_CODIGO = CERTORIGMP.CMP_CODIGO
		WHERE     CERTORIGMP.SPI_CODIGO IN (SELECT spi_codigo FROM spi  WHERE spi_clave = 'nafta')
		AND CERTORIGMP.CMP_ESTATUS='V' AND  CERTORIGMP.CMP_IFECHA<=GETDATE() AND CERTORIGMP.CMP_VFECHA>=GETDATE())
		THEN 'S' ELSE 'N' END 
		) end,
 	         ARANCEL1.AR_FRACCION AS AR_IMPFO, 
                      ARANCEL1.AR_FRACCION AS AR_IMPMX, dbo.PAIS.PA_CORTO, dbo.MAESTRO.PA_ORIGEN, dbo.MAESTRO.MA_NOPARTEAUX, 
                      VMAESTROCOST.MA_COSTO, VMAESTROCOST.MA_GRAV_MP, VMAESTROCOST.MA_GRAV_ADD, VMAESTROCOST.MA_GRAV_EMP, VMAESTROCOST.MA_GRAV_GI,
                      VMAESTROCOST.MA_GRAV_GI_MX, VMAESTROCOST.MA_GRAV_MO, VMAESTROCOST.MA_NG_MP, VMAESTROCOST.MA_NG_ADD, 
                      VMAESTROCOST.MA_NG_EMP, dbo.MAESTRO.MA_NOPARTE collate database_default + ' ' + dbo.MAESTRO.MA_NOPARTEAUX collate database_default AS MAPARTEAUX
FROM         dbo.PAIS RIGHT OUTER JOIN
                      dbo.MAESTRO ON dbo.PAIS.PA_CODIGO = dbo.MAESTRO.PA_ORIGEN LEFT OUTER JOIN
                      dbo.ARANCEL ON dbo.MAESTRO.AR_IMPFO = dbo.ARANCEL.AR_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ARANCEL1 ON dbo.MAESTRO.AR_IMPMX = ARANCEL1.AR_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.MAESTRO.ME_COM = dbo.MEDIDA.ME_CODIGO LEFT OUTER JOIN 
	        VMAESTROCOST ON dbo.MAESTRO.MA_CODIGO=VMAESTROCOST.MA_CODIGO
WHERE dbo.MAESTRO.MA_OCULTO='N'









































































GO
