SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO







CREATE VIEW dbo.VCONSULTA_FACTEXP
with encryption as
SELECT     dbo.FACTEXPDET.MA_CODIGO, dbo.FACTEXP.FE_FOLIO, dbo.FACTEXP.FE_FECHA, dbo.TFACTURA.TF_NOMBRE, dbo.TEMBARQUE.TQ_NOMBRE, 
                      SUM(ISNULL(dbo.FACTEXPDET.FED_CANT, 0)) AS cantidad, dbo.MEDIDA.ME_CORTO, dbo.PAIS.PA_CORTO, dbo.ARANCEL.AR_FRACCION, 
                      dbo.FACTEXPDET.FED_DEF_TIP, dbo.FACTEXPDET.FED_POR_DEF, dbo.MAESTRO.MA_NOPARTE, dbo.SPI.SPI_CLAVE, dbo.SECTOR.SE_CLAVE, 
                      dbo.FACTEXPDET.EQ_GEN
FROM         dbo.PAIS RIGHT OUTER JOIN
                      dbo.FACTEXPDET LEFT OUTER JOIN
                      dbo.SECTOR ON dbo.FACTEXPDET.FED_SEC_IMP = dbo.SECTOR.SE_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.FACTEXPDET.MA_GENERICO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ON dbo.FACTEXPDET.AR_IMPMX = dbo.ARANCEL.AR_CODIGO ON 
                      dbo.PAIS.PA_CODIGO = dbo.FACTEXPDET.PA_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.FACTEXPDET.ME_CODIGO = dbo.MEDIDA.ME_CODIGO RIGHT OUTER JOIN
                      dbo.TEMBARQUE RIGHT OUTER JOIN
                      dbo.FACTEXP ON dbo.TEMBARQUE.TQ_CODIGO = dbo.FACTEXP.TQ_CODIGO LEFT OUTER JOIN
                      dbo.TFACTURA ON dbo.FACTEXP.TF_CODIGO = dbo.TFACTURA.TF_CODIGO ON 
                      dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      dbo.SPI ON dbo.FACTEXPDET.SPI_CODIGO = dbo.SPI.SPI_CODIGO
GROUP BY dbo.FACTEXP.FE_FOLIO, dbo.FACTEXP.FE_FECHA, dbo.TFACTURA.TF_NOMBRE, dbo.TEMBARQUE.TQ_NOMBRE, dbo.PAIS.PA_CORTO, 
                      dbo.MEDIDA.ME_CORTO, dbo.ARANCEL.AR_FRACCION, dbo.FACTEXPDET.FED_POR_DEF, dbo.FACTEXPDET.FED_DEF_TIP, 
                      dbo.FACTEXPDET.MA_CODIGO, dbo.MAESTRO.MA_NOPARTE, dbo.SPI.SPI_CLAVE, dbo.SECTOR.SE_CLAVE, dbo.FACTEXPDET.EQ_GEN










GO
