SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO















CREATE VIEW dbo.VKARDES_X_PED
with encryption as
SELECT     dbo.VPEDIMP.PI_FEC_PAG AS KAP_FECHAPED, dbo.PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, 
                      dbo.VPEDIMP.PI_FOLIO AS KPN_PED_CONST_FOL, dbo.AGENCIA.AG_PATENTE AS KPN_PED_CONST_PATENTE, 
                      dbo.VPEDIMP.PI_TIPO AS KAP_TIPO_PED, dbo.VPEDIMP.PI_FEC_PAG AS KPN_PED_CONST_FECHA, 
                      dbo.VPEDIMP.PI_TIP_CAM AS KPN_PED_CONST_TC, dbo.KARDESPED.KAP_FACTRANS, dbo.FACTEXP.FE_TIPO AS KAP_TIPO_FACTRANS, 
                      dbo.FACTEXPDET.MA_CODIGO AS MA_FACT_TRANS, dbo.FACTEXPDET.TI_CODIGO AS TI_FACT_TRANS, SUM(dbo.FACTEXPDET.FED_CANT) 
                      AS KAP_CANT_FACT_TRANS, dbo.KARDESPED.MA_HIJO, dbo.FACTEXPDET.TI_CODIGO AS TI_HIJO, 
                      dbo.FACTEXPDET.ME_GENERICO AS ME_HIJO, SUM(dbo.KARDESPED.KAP_CANTDESC) AS KAP_CANTDESC, VKAP_SALDO_PED.KAP_SALDO_PED, 
                      dbo.PEDIMPDET.PA_ORIGEN, dbo.PEDIMPDET.PA_PROCEDE, dbo.MAESTRO.MA_CONSTA AS KAP_CONSTA
FROM         dbo.FACTEXP RIGHT OUTER JOIN
                      dbo.KARDESPED ON dbo.FACTEXP.FE_CODIGO = dbo.KARDESPED.KAP_FACTRANS LEFT OUTER JOIN
                      dbo.VPEDIMP RIGHT OUTER JOIN
                      dbo.PEDIMPDET LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.PEDIMPDET.MA_CODIGO = dbo.MAESTRO.MA_CODIGO ON dbo.VPEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO ON 
                      dbo.KARDESPED.KAP_INDICED_PED = dbo.PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      dbo.FACTEXPDET ON dbo.KARDESPED.KAP_INDICED_FACT = dbo.FACTEXPDET.FED_INDICED LEFT OUTER JOIN
                      dbo.AGENCIA ON dbo.VPEDIMP.AG_CODIGO = dbo.AGENCIA.AG_CODIGO
	LEFT OUTER JOIN VKAP_SALDO_PED ON dbo.KARDESPED.KAP_CODIGO=VKAP_SALDO_PED.KAP_CODIGO
GROUP BY dbo.PEDIMPDET.PI_CODIGO, dbo.KARDESPED.MA_HIJO, dbo.VPEDIMP.PI_TIPO, 
                      dbo.FACTEXPDET.ME_GENERICO, dbo.PEDIMPDET.PA_ORIGEN, dbo.PEDIMPDET.PA_PROCEDE, VKAP_SALDO_PED.KAP_SALDO_PED, 
                      dbo.MAESTRO.MA_CONSTA, dbo.FACTEXPDET.MA_CODIGO, dbo.FACTEXPDET.TI_CODIGO, dbo.KARDESPED.KAP_FACTRANS, dbo.FACTEXP.FE_TIPO, 
                      dbo.VPEDIMP.PI_FOLIO, dbo.AGENCIA.AG_PATENTE, dbo.VPEDIMP.PI_FEC_PAG, dbo.VPEDIMP.PI_TIP_CAM
HAVING      (SUM(dbo.KARDESPED.KAP_CANTDESC) > 0) AND (dbo.VPEDIMP.PI_TIPO = 'P')


GO
