SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VEXHIBIT_A_2
with encryption as
SELECT     SUM(CSA_NG_DESP) AS CSA_NG_DESP, SUM(CSA_GRAV_DESP) AS CSA_GRAV_DESP, CS_CODIGO
FROM         (SELECT SUM(FACTEXPDET.FED_NG_USA) AS CSA_NG_DESP, 
	    SUM((FACTEXPDET.FED_GRA_MP + FACTEXPDET.FED_GRA_ADD)+(FACTEXPDET.FED_NG_MP -FACTEXPDET.FED_NG_USA) * FACTEXPDET.FED_CANT)
	     AS CSA_GRAV_DESP, VRELCSFACTEXP.CS_CODIGO,  FACTEXP.FE_CODIGO, dbo.ARANCEL.AR_FRACCION
	FROM FACTEXP RIGHT OUTER JOIN
	    VRELCSFACTEXP ON 
	    FACTEXP.FE_CODIGO = VRELCSFACTEXP.FE_CODIGO LEFT OUTER
	     JOIN
	    CONFIGURATEMBARQUE ON 
	    FACTEXP.TQ_CODIGO = CONFIGURATEMBARQUE.TQ_CODIGO LEFT
	     OUTER JOIN
	    CONFIGURATIPO RIGHT OUTER JOIN
	    FACTEXPDET ON 
	    CONFIGURATIPO.TI_CODIGO = FACTEXPDET.TI_CODIGO ON 
	    FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO left outer JOIN ARANCEL ON
		dbo.ARANCEL.AR_CODIGO = dbo.FACTEXPDET.AR_IMPFO 
	WHERE (CONFIGURATEMBARQUE.CFQ_TIPO = 'D') AND (dbo.CONFIGURATIPO.CFT_TIPO = 'P' OR
	                      dbo.CONFIGURATIPO.CFT_TIPO = 'S') AND
		       (FACTEXP.TN_CODIGO = 2 OR FACTEXP.TN_CODIGO = 6 OR FACTEXP.TN_CODIGO = 7 OR
		    FACTEXP.TN_CODIGO = 5 OR dbo.FACTEXP.TN_CODIGO = 8 OR dbo.FACTEXP.TN_CODIGO = 9)
	GROUP BY VRELCSFACTEXP.CS_CODIGO,  FACTEXP.FE_CODIGO, dbo.ARANCEL.AR_FRACCION
	UNION
	SELECT     0 AS CSA_NG_DESP, SUM(dbo.FACTEXPDET.FED_COS_UNI*FACTEXPDET.FED_CANT) AS CSA_GRAV_DESP, dbo.VRELCSFACTEXP.CS_CODIGO,  FACTEXP.FE_CODIGO, dbo.ARANCEL.AR_FRACCION
	FROM         dbo.CONFIGURATIPO RIGHT OUTER JOIN
	                      dbo.ARANCEL RIGHT OUTER JOIN
	                      dbo.FACTEXPDET ON dbo.ARANCEL.AR_CODIGO = dbo.FACTEXPDET.AR_IMPFO ON 
	                      dbo.CONFIGURATIPO.TI_CODIGO = dbo.FACTEXPDET.TI_CODIGO RIGHT OUTER JOIN
	                      dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.VRELCSFACTEXP ON dbo.FACTEXP.FE_CODIGO = dbo.VRELCSFACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      dbo.CONFIGURATEMBARQUE ON dbo.FACTEXP.TQ_CODIGO = dbo.CONFIGURATEMBARQUE.TQ_CODIGO ON 
	                      dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
	WHERE     (dbo.CONFIGURATEMBARQUE.CFQ_TIPO = 'D') AND (dbo.CONFIGURATIPO.CFT_TIPO <> 'P') AND (dbo.CONFIGURATIPO.CFT_TIPO <> 'S') AND 
	                      (dbo.ARANCEL.AR_FRACCION NOT LIKE '9801%' OR dbo.ARANCEL.AR_FRACCION NOT LIKE '9802%') AND
		       (FACTEXP.TN_CODIGO = 2 OR FACTEXP.TN_CODIGO = 6 OR FACTEXP.TN_CODIGO = 7 OR
		    FACTEXP.TN_CODIGO = 5 OR dbo.FACTEXP.TN_CODIGO = 8 OR dbo.FACTEXP.TN_CODIGO = 9)
	GROUP BY dbo.VRELCSFACTEXP.CS_CODIGO,  FACTEXP.FE_CODIGO, dbo.ARANCEL.AR_FRACCION
	UNION
	SELECT     SUM(dbo.FACTEXPDET.FED_COS_UNI*FACTEXPDET.FED_CANT) AS CSA_NG_DESP, 0 AS CSA_GRAV_DESP, dbo.VRELCSFACTEXP.CS_CODIGO,  FACTEXP.FE_CODIGO, dbo.ARANCEL.AR_FRACCION
	FROM         dbo.CONFIGURATIPO RIGHT OUTER JOIN
	                      dbo.ARANCEL RIGHT OUTER JOIN
	                      dbo.FACTEXPDET ON dbo.ARANCEL.AR_CODIGO = dbo.FACTEXPDET.AR_IMPFO ON 
	                      dbo.CONFIGURATIPO.TI_CODIGO = dbo.FACTEXPDET.TI_CODIGO RIGHT OUTER JOIN
	                      dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.VRELCSFACTEXP ON dbo.FACTEXP.FE_CODIGO = dbo.VRELCSFACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      dbo.CONFIGURATEMBARQUE ON dbo.FACTEXP.TQ_CODIGO = dbo.CONFIGURATEMBARQUE.TQ_CODIGO ON 
	                      dbo.FACTEXPDET.FE_CODIGO = dbo.FACTEXP.FE_CODIGO
	WHERE     (dbo.CONFIGURATEMBARQUE.CFQ_TIPO = 'D') AND (dbo.CONFIGURATIPO.CFT_TIPO <> 'P') AND (dbo.CONFIGURATIPO.CFT_TIPO <> 'S') AND 
	                      (dbo.ARANCEL.AR_FRACCION LIKE '9801%' AND dbo.ARANCEL.AR_FRACCION LIKE '9802%') AND
		       (FACTEXP.TN_CODIGO = 2 OR FACTEXP.TN_CODIGO = 6 OR FACTEXP.TN_CODIGO = 7 OR
		    FACTEXP.TN_CODIGO = 5 OR dbo.FACTEXP.TN_CODIGO = 8 OR dbo.FACTEXP.TN_CODIGO = 9)
	GROUP BY dbo.VRELCSFACTEXP.CS_CODIGO,  FACTEXP.FE_CODIGO, dbo.ARANCEL.AR_FRACCION
	) EXHIBIT_A_2A
GROUP BY CS_CODIGO



GO
