SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VTIPOMOV
with encryption as
SELECT     dbo.TMOVIMIENTO.TM_CODIGO, dbo.TMOVIMIENTO.TM_NOMBRE, dbo.TMOVIMIENTO.TM_NAME,dbo.TMOVIMIENTO.TM_TIPO, dbo.TMOVIMIENTO.TM_ALMACENES, 
                      dbo.CONFIGURATMOVIMIENTO.CFM_TIPO, dbo.TMOVIMIENTO.ALM_ORIGEN, dbo.TMOVIMIENTO.ALM_DESTINO
FROM         dbo.TMOVIMIENTO LEFT OUTER JOIN
                      dbo.CONFIGURATMOVIMIENTO ON dbo.TMOVIMIENTO.TM_CODIGO = dbo.CONFIGURATMOVIMIENTO.TM_CODIGO
WHERE  dbo.TMOVIMIENTO.TM_ACTIVO='S'

GO
