SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO









CREATE VIEW dbo.VFACTIMPFLETE
with encryption as
SELECT PI_CODIGO, PI_RECTIFICA, FI_CODIGO, FI_FACTAGRU, FI_TOTALB, FI_TRAC_MX, ISNULL((SELECT SUM(FACTIMPDET.FID_PES_BRU) FROM FACTIMPDET WHERE FACTIMPDET.FI_CODIGO=dbo.FACTIMP.FI_CODIGO),0) AS FI_PESOKG,
isnull((SELECT SUM(FACTIMPINCREMENTA1.FII_VALOR)
FROM         dbo.FACTIMPINCREMENTA FACTIMPINCREMENTA1 INNER JOIN
                      dbo.INCREMENTABLE ON FACTIMPINCREMENTA1.IC_CODIGO = dbo.INCREMENTABLE.IC_CODIGO
WHERE     dbo.INCREMENTABLE.IC_PEDIMENTO = 'F' AND FACTIMPINCREMENTA1.FI_CODIGO=dbo.FACTIMP.FI_CODIGO),0) AS FI_FLETE,
isnull((SELECT SUM(FACTIMPINCREMENTA1.FII_VALOR)
FROM         dbo.FACTIMPINCREMENTA FACTIMPINCREMENTA1 INNER JOIN
                      dbo.INCREMENTABLE ON FACTIMPINCREMENTA1.IC_CODIGO = dbo.INCREMENTABLE.IC_CODIGO
WHERE     dbo.INCREMENTABLE.IC_PEDIMENTO = 'S' AND FACTIMPINCREMENTA1.FI_CODIGO=dbo.FACTIMP.FI_CODIGO),0) AS FI_SEGURO,
isnull((SELECT SUM(FACTIMPINCREMENTA1.FII_VALOR)
FROM         dbo.FACTIMPINCREMENTA FACTIMPINCREMENTA1 INNER JOIN
                      dbo.INCREMENTABLE ON FACTIMPINCREMENTA1.IC_CODIGO = dbo.INCREMENTABLE.IC_CODIGO
WHERE     dbo.INCREMENTABLE.IC_PEDIMENTO = 'E' AND FACTIMPINCREMENTA1.FI_CODIGO=dbo.FACTIMP.FI_CODIGO),0) AS FI_EMBALAJE,
isnull((SELECT SUM(FACTIMPINCREMENTA1.FII_VALOR)
FROM         dbo.FACTIMPINCREMENTA FACTIMPINCREMENTA1 INNER JOIN
                      dbo.INCREMENTABLE ON FACTIMPINCREMENTA1.IC_CODIGO = dbo.INCREMENTABLE.IC_CODIGO
WHERE     dbo.INCREMENTABLE.IC_PEDIMENTO = 'O' AND FACTIMPINCREMENTA1.FI_CODIGO=dbo.FACTIMP.FI_CODIGO),0) AS FI_OTROS
FROM dbo.FACTIMP




GO
