SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW dbo.VDECANUALIMPUESTOPAGYEAR
with encryption as
SELECT     dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDEXP.PI_IMPORTECONTRSINRECARGOS AS PI_IMPORTECONTR, dbo.VPEDEXP.PI_COMPLEMEN, 
                      dbo.VPEDEXP.PI_FECHAPAGO
FROM         dbo.DECANUALNVA INNER JOIN
                      dbo.VPEDEXP ON dbo.DECANUALNVA.DAN_INICIO <= dbo.VPEDEXP.PI_FECHAPAGO AND 
                      dbo.DECANUALNVA.DAN_FINAL >= dbo.VPEDEXP.PI_FECHAPAGO AND dbo.DECANUALNVA.DAN_INICIO <= dbo.VPEDEXP.PI_FEC_PAG AND 
                      dbo.DECANUALNVA.DAN_FINAL >= dbo.VPEDEXP.PI_FEC_PAG
WHERE     (dbo.VPEDEXP.PI_IMPORTECONTRSINRECARGOS > 0) AND (dbo.VPEDEXP.PI_COMPLEMEN <> '') AND (dbo.VPEDEXP.PI_COMPLEMEN IS NOT NULL)





GO
