SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VistaUltimoMovTransmisionDet
with encryption as
SELECT     MAX(TRMD_INDICED) AS TRMD_INDICED, TRM_CODIGO, MAX(TRMD_FECHAHORA) AS TRMD_UFECHAHORA
FROM         dbo.TRANSMISIONDET
GROUP BY TRM_CODIGO




GO
