SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE VIEW dbo.VPERMISO
with encryption as
SELECT PERMISO.PE_CODIGO, 'PE_PERMISO'=CASE WHEN  dbo.PERMISO.PE_ANIO IS NULL OR dbo.PERMISO.PE_ANIO='' THEN dbo.PERMISO.PE_PERMISO
ELSE CONVERT(VARCHAR(5),dbo.PERMISO.PE_ANIO)+'-'+dbo.PERMISO.PE_PERMISO collate database_default END, PERMISO.PE_FOLIO, IDENTIFICA.IDE_CLAVE,PERMISO.IDE_CODIGO
FROM PERMISO
LEFT OUTER JOIN
IDENTIFICA ON
PERMISO.IDE_CODIGO = IDENTIFICA.IDE_CODIGO
WHERE PE_APROBADO = 'S'



GO
