SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO















CREATE VIEW dbo.VPEDIMPIMAGEN
with encryption as
SELECT TOP 100 PERCENT VPEDEXP.PI_CODIGO, IMAGEN.IM_IMAGEN, IMAGEN.IM_NOMBREARCHIVO, IMAGEN.IM_ORDEN, PEDIMPDET.PI_CODIGO AS PI_CODIGOIMP
FROM  dbo.VPEDEXP VPEDEXP LEFT OUTER JOIN
      dbo.FACTEXP FACTEXP ON VPEDEXP.PI_CODIGO = FACTEXP.PI_CODIGO LEFT OUTER JOIN
      dbo.KARDESPED KARDESPED ON FACTEXP.FE_CODIGO = KARDESPED.KAP_FACTRANS LEFT OUTER JOIN
      dbo.PEDIMPDET PEDIMPDET ON KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
      dbo.PEDIMPIMAGEN IMAGEN ON PEDIMPDET.PI_CODIGO = IMAGEN.PI_CODIGO
WHERE  (IMAGEN.IM_IMAGEN IS NOT NULL OR IMAGEN.IM_NOMBREARCHIVO IS NOT NULL)
ORDER BY VPEDEXP.PI_CODIGO
















GO
