SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VPEDIMPINCREMENTASEGURO
with encryption as
SELECT     dbo.INCREMENTABLE.IC_PEDIMENTO, SUM(ISNULL(dbo.PEDIMPINCREMENTA.PII_VALOR, 0)) AS PII_VALOR, dbo.PEDIMP.PI_CODIGO
FROM         dbo.PEDIMPINCREMENTA RIGHT OUTER JOIN
                      dbo.PEDIMP ON dbo.PEDIMPINCREMENTA.PI_CODIGO = dbo.PEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.INCREMENTABLE ON dbo.PEDIMPINCREMENTA.IC_CODIGO = dbo.INCREMENTABLE.IC_CODIGO
GROUP BY dbo.INCREMENTABLE.IC_PEDIMENTO, dbo.PEDIMP.PI_CODIGO
HAVING      (dbo.INCREMENTABLE.IC_PEDIMENTO = 'S')




GO
