SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

































CREATE VIEW dbo.VCOSTSUBBASC247
with encryption as
SELECT     CS_CODIGO, CSBD_RATE AS CSBC_RATE, MA_NAFTA AS CSBC_NAFTA, SUM(CSBD_DUTVALWOMPF) AS CSBC_DUTVALWOMPF, 
                      SUM(CSBD_DUTVALWMPF) AS CSBC_DUTVALWMPF, SUM(CSBD_DUTVAL) AS CSBC_DUTVAL, SUM(CSBD_3PORCENTW) AS CSBC_3PORCENTW, 
                      SUM(CSBD_3PORCENTO) AS CSBC_3PORCENTO, SUM(CSBD_3TOT) AS CSBC_3TOT, SUM(CSBD_4ACTUAL) AS CSBC_4ACTUAL, 
                      SUM(CSBD_5PRORATIO) AS CSBC_5PRORATIO, SUM(CSBD_5PRORATIW) AS CSBC_5PRORATIW, SUM(CSBD_5TOT) AS CSBC_5TOT, 
                      SUM(CSBD_6DUTYACTUALO) AS CSBC_6DUTYACTUALO, SUM(CSBD_6DUTYACTUALW) AS CSBC_6DUTYACTUALW, SUM(CSBD_6TOT) 
                      AS CSBC_6TOT, SUM(CSBD_7DUTYPAIDO) AS CSBC_7DUTYPAIDO, SUM(CSBD_7DUTYPAIDW) AS CSBC_7DUTYPAIDW, SUM(CSBD_7TOT) 
                      AS CSBC_7TOT
FROM         dbo.COSTSUBBASC247DET
GROUP BY CS_CODIGO, CSBD_RATE, MA_NAFTA

GO
