SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO







CREATE VIEW dbo.VKARDESPEDGR
with encryption as
SELECT     dbo.KARDESPED.KAP_CODIGO, dbo.FACTEXP.FE_FOLIO, dbo.FACTEXP.FE_FECHA, dbo.TFACTURA.TF_NOMBRE, dbo.TEMBARQUE.TQ_NOMBRE, 
                      dbo.AGENCIAPATENTE.AGT_PATENTE collate database_default + '-' + dbo.PEDIMP.PI_FOLIO collate database_default AS [PATENTE-FOLIO], 
                      dbo.ADUANA.AD_CLAVE collate database_default + '-' + dbo.ADUANA.AD_SECCION collate database_default AS [ADUANA-SECCION], dbo.PEDIMP.PI_FEC_PAG, dbo.PEDIMP.PI_TIP_CAM, 
                      dbo.CLIENTE.CL_RFC, dbo.VBASEKARDESPEDGR.FED_NOPARTE, dbo.VBASEKARDESPEDGR.FED_NOMBRE, dbo.VBASEKARDESPEDGR.FED_NAME, 
                      dbo.MAESTRO.MA_NOPARTE, dbo.MAESTRO.MA_NOMBRE, dbo.MAESTRO.MA_NAME, dbo.FACTEXP.FE_TIPOCAMBIO, 
                      dbo.VBASEKARDESPEDGR.FED_COS_GRAVUNI, dbo.VBASEKARDESPEDGR.FED_CANT
FROM         dbo.AGENCIAPATENTE RIGHT OUTER JOIN
                      dbo.TEMBARQUE RIGHT OUTER JOIN
                      dbo.FACTEXP ON dbo.TEMBARQUE.TQ_CODIGO = dbo.FACTEXP.TQ_CODIGO LEFT OUTER JOIN
                      dbo.TFACTURA ON dbo.FACTEXP.TF_CODIGO = dbo.TFACTURA.TF_CODIGO RIGHT OUTER JOIN
                      dbo.MAESTRO RIGHT OUTER JOIN
                      dbo.VBASEKARDESPEDGR RIGHT OUTER JOIN
                      dbo.PEDIMPDET RIGHT OUTER JOIN
                      dbo.KARDESPED ON dbo.PEDIMPDET.PID_INDICED = dbo.KARDESPED.KAP_INDICED_PED ON 
                      dbo.VBASEKARDESPEDGR.MA_GENERICO = dbo.KARDESPED.KAP_INDICED_FACT AND 
                      dbo.VBASEKARDESPEDGR.FE_CODIGO = dbo.KARDESPED.KAP_FACTRANS ON dbo.MAESTRO.MA_CODIGO = dbo.KARDESPED.MA_HIJO ON 
                      dbo.FACTEXP.FE_CODIGO = dbo.KARDESPED.KAP_FACTRANS LEFT OUTER JOIN
                      dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.CLIENTE ON dbo.PEDIMP.PR_CODIGO = dbo.CLIENTE.CL_CODIGO LEFT OUTER JOIN
                      dbo.ADUANA ON dbo.PEDIMP.AD_DES = dbo.ADUANA.AD_CODIGO ON dbo.AGENCIAPATENTE.AGT_CODIGO = dbo.PEDIMP.AGT_CODIGO







GO
