SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VPEDIMPFACT
with encryption as
SELECT     VPEDIMPFACT1.PI_CODIGO, VPEDIMPFACT1.FI_CODIGO, VPEDIMPFACT1.FI_FOLIO, VPEDIMPFACT1.FI_FECHA, 
                      VPEDIMPFACT1.IT_CODIGO, VPEDIMPFACT1.MO_CODIGO, VPEDIMPFACT1.PIF_VALMONEXT, VPEDIMPFACT1.PIF_FACTORMONEXT, 
                      VPEDIMPFACT1.PIF_VALDLLS, VPEDIMPFACT1.PR_CODIGO, VPEDIMPFACT1.DI_CODIGO, VFACTFLETE.FI_FLETE, 
                      VFACTFLETE.FI_SEGURO, VFACTFLETE.FI_EMBALAJE, VFACTFLETE.FI_OTROS, VFACTFLETE.FI_TOTALB, 
                      VFACTFLETE.FI_TRAC_MX, VPEDIMPFACT1.FI_CONSECUTIVOPED, VPEDIMPFACT1.FI_CONT_REG
FROM         (SELECT FACTEXP.PI_RECTIFICA AS PI_CODIGO, FACTEXP.FE_CODIGO AS FI_CODIGO, FACTEXP.FE_FOLIO AS FI_FOLIO, FACTEXP.FE_FECHA AS FI_FECHA, 
			FACTEXP.IT_COMPANY1 AS IT_CODIGO, FACTEXP.MO_CODIGO, round(SUM(FACTEXPDET.FED_COS_TOT),2) AS PIF_VALMONEXT, 
			 CASE WHEN (CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = FACTEXP.PI_RECTIFICA),1)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTEXPDET.FED_COS_TOT) ELSE SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = FACTEXP.PI_RECTIFICA),1),1) END)> 0 THEN 
			
			 ROUND(SUM(FACTEXPDET.FED_COS_TOT)/(CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = FACTEXP.PI_RECTIFICA),1)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTEXPDET.FED_COS_TOT) ELSE SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = FACTEXP.PI_RECTIFICA),1),1) END),4) ELSE 1 END AS PIF_FACTORMONEXT, 
			
			'PIF_VALDLLS'=CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN round(SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = FACTEXP.PI_RECTIFICA),1),2)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 round(SUM(FACTEXPDET.FED_COS_TOT),2) ELSE round(SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = FACTEXP.PI_RECTIFICA),1),1),2) END, 
			 FACTEXP.CL_DESTINI AS PR_CODIGO, FACTEXP.DI_DESTINI AS DI_CODIGO, 
			FACTEXP.FE_CONSECUTIVOPED AS FI_CONSECUTIVOPED, FACTEXP.FE_CONT1_REG AS FI_CONT_REG
		FROM         FACTEXP LEFT OUTER JOIN 
		      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO 
		WHERE     (dbo.FACTEXP.PI_RECTIFICA <> - 1) AND FE_FACTAGRU NOT IN (SELECT PI_FACTAGRU FROM PEDIMP WHERE PI_MOVIMIENTO='S' AND PI_USAFACTAGRU = 'S' AND PI_FACTAGRU<>-1)
		GROUP BY FACTEXP.PI_RECTIFICA, FACTEXP.FE_CODIGO, FACTEXP.FE_FOLIO, FACTEXP.FE_FECHA, FACTEXP.IT_COMPANY1, 
		      FACTEXP.MO_CODIGO, FACTEXP.CL_DESTINI, FACTEXP.DI_DESTINI, FACTEXP.FE_CONSECUTIVOPED, FACTEXP.FE_CONT1_REG
            UNION
		SELECT FACTIMP.PI_RECTIFICA AS PI_CODIGO, FACTIMP.FI_CODIGO, FACTIMP.FI_FOLIO, FACTIMP.FI_FECHA, FACTIMP.IT_CODIGO, 
			     FACTIMP.MO_CODIGO, round(SUM(FACTIMPDET.FID_COS_TOT),2) AS PIF_VALMONEXT, 
	
			 CASE WHEN (CASE WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTIMPDET.FID_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_RECTIFICA),1)
			 WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTIMPDET.FID_COS_TOT) ELSE SUM(isnull(FACTIMPDET.FID_COS_TOT,0)*FACTIMP.FI_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_RECTIFICA),1),1) END) > 0 THEN 
			
			 ROUND(SUM(FACTIMPDET.FID_COS_TOT)/(CASE WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTIMPDET.FID_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_RECTIFICA),1)
			 WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTIMPDET.FID_COS_TOT) ELSE SUM(isnull(FACTIMPDET.FID_COS_TOT,0)*FACTIMP.FI_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_RECTIFICA),1),1) END),4) ELSE 1 END AS PIF_FACTORMONEXT, 
			
			     'PIF_VALDLLS'=CASE WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN round(SUM(FACTIMPDET.FID_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_RECTIFICA),1),2)
			 WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 round(SUM(FACTIMPDET.FID_COS_TOT),2) ELSE round(SUM(isnull(FACTIMPDET.FID_COS_TOT,0)*FACTIMP.FI_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_RECTIFICA),1),1),2) END, 
			 FACTIMP.PR_CODIGO, FACTIMP.DI_PROVEE AS DI_CODIGO, FACTIMP.FI_CONSECUTIVOPED, FACTIMP.FI_CONT_REG
		FROM FACTIMP LEFT OUTER JOIN 
		     FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO 
		WHERE     (dbo.FACTIMP.PI_RECTIFICA <> - 1) AND FI_FACTAGRU NOT IN (SELECT PI_FACTAGRU FROM PEDIMP WHERE PI_MOVIMIENTO='E' AND PI_USAFACTAGRU = 'S' AND PI_FACTAGRU<>-1)
		GROUP BY FACTIMP.PI_RECTIFICA, FACTIMP.FI_CODIGO, FACTIMP.FI_FOLIO, FACTIMP.FI_FECHA, FACTIMP.IT_CODIGO, 
		FACTIMP.MO_CODIGO, FACTIMP.PR_CODIGO, FACTIMP.DI_PROVEE, FACTIMP.FI_CONSECUTIVOPED, FACTIMP.FI_CONT_REG 
	UNION
	-- agrupadora
		SELECT PEDIMP.PI_CODIGO, FACTIMPAGRU.FIA_CODIGO, FACTIMPAGRU.FIA_FOLIO, 
		    FACTIMPAGRU.FIA_FECHA, FACTIMPAGRU.IT_CODIGO, 
		    FACTIMPAGRU.MO_CODIGO, PIF_VALMONEXT, PIF_FACTORMONEXT, PIF_VALDLLS, FACTIMPAGRU.PR_CODIGO, 
		    FACTIMPAGRU.DI_PROVEE,  0, ''	    
		FROM FACTIMPAGRU INNER JOIN PEDIMP
		ON PEDIMP.PI_FACTAGRU = FACTIMPAGRU.FIA_CODIGO INNER JOIN 
		 (SELECT FACTIMP.PI_CODIGO, round(SUM(FACTIMPDET.FID_COS_TOT),2) AS PIF_VALMONEXT, 
		    CASE WHEN (CASE WHEN MAX(FACTIMP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
		    THEN SUM(FACTIMPDET.FID_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTIMP.PI_CODIGO)),1)
		    WHEN MAX(FACTIMP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
		    SUM(FACTIMPDET.FID_COS_TOT) ELSE SUM(isnull(FACTIMPDET.FID_COS_TOT,0)*FACTIMP.FI_TIPOCAMBIO)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTIMP.PI_CODIGO)),1) END) > 0 THEN 
		    ROUND(SUM(FACTIMPDET.FID_COS_TOT) / (CASE WHEN MAX(FACTIMP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
		    THEN SUM(FACTIMPDET.FID_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTIMP.PI_CODIGO)),1)
		    WHEN MAX(FACTIMP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
		    SUM(FACTIMPDET.FID_COS_TOT) ELSE SUM(isnull(FACTIMPDET.FID_COS_TOT,0)*FACTIMP.FI_TIPOCAMBIO)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTIMP.PI_CODIGO)),1) END),4) ELSE 1 END AS PIF_FACTORMONEXT, 
		      'PIF_VALDLLS'=CASE WHEN MAX(FACTIMP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
		    THEN round(SUM(FACTIMPDET.FID_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTIMP.PI_CODIGO)),1),2) 
		    WHEN MAX(FACTIMP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
		    round(SUM(FACTIMPDET.FID_COS_TOT),2) ELSE round(SUM(isnull(FACTIMPDET.FID_COS_TOT,0)*FACTIMP.FI_TIPOCAMBIO)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTIMP.PI_CODIGO)),1),2) END 
		  FROM FACTIMP LEFT OUTER JOIN 
		      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO
		  WHERE FACTIMP.PI_CODIGO <> -1 AND FACTIMP.PI_CODIGO<>0
		 GROUP BY FACTIMP.PI_CODIGO) FACTURAIMP ON FACTURAIMP.PI_CODIGO=PEDIMP.PI_CODIGO 
		WHERE  PEDIMP.PI_USAFACTAGRU = 'S'
	UNION
		SELECT FACTEXP.PI_CODIGO, FACTEXP.FE_CODIGO AS FI_CODIGO, FACTEXP.FE_FOLIO AS FI_FOLIO, FACTEXP.FE_FECHA AS FI_FECHA, 
			FACTEXP.IT_COMPANY1 AS IT_CODIGO, FACTEXP.MO_CODIGO, round(SUM(FACTEXPDET.FED_COS_TOT),2) AS PIF_VALMONEXT, 
	
			CASE WHEN (CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTEXPDET.FED_COS_TOT) ELSE SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),1) END)> 0 THEN 
			
			ROUND(SUM(FACTEXPDET.FED_COS_TOT) / (CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTEXPDET.FED_COS_TOT) ELSE SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),1) END),4) ELSE 1 END AS PIF_FACTORMONEXT, 
			
			 'PIF_VALDLLS'=CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN round(SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),2)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 round(SUM(FACTEXPDET.FED_COS_TOT),2) ELSE round(SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),1),2) END, 
			FACTEXP.CL_DESTINI AS PR_CODIGO, FACTEXP.DI_DESTINI AS DI_CODIGO, 
			FACTEXP.FE_CONSECUTIVOPED AS FI_CONSECUTIVOPED, FACTEXP.FE_CONT1_REG
		FROM         FACTEXP LEFT OUTER JOIN 
		      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO 
		WHERE FACTEXP.PI_CODIGO<>-1 AND FE_FACTAGRU NOT IN (SELECT PI_FACTAGRU FROM PEDIMP WHERE PI_MOVIMIENTO='S' AND PI_USAFACTAGRU = 'S' AND PI_FACTAGRU<>-1)
		GROUP BY FACTEXP.PI_CODIGO, FACTEXP.FE_CODIGO, FACTEXP.FE_FOLIO, FACTEXP.FE_FECHA, FACTEXP.IT_COMPANY1, 
		      FACTEXP.MO_CODIGO, FACTEXP.CL_DESTINI, FACTEXP.DI_DESTINI, FACTEXP.FE_CONSECUTIVOPED, FACTEXP.FE_CONT1_REG 
	UNION
		SELECT FACTIMP.PI_CODIGO, FACTIMP.FI_CODIGO, FACTIMP.FI_FOLIO, FACTIMP.FI_FECHA, FACTIMP.IT_CODIGO, 
			     FACTIMP.MO_CODIGO, round(SUM(FACTIMPDET.FID_COS_TOT),2) AS PIF_VALMONEXT, 
			
			CASE WHEN (CASE WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTIMPDET.FID_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_CODIGO),1)
			 WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTIMPDET.FID_COS_TOT) ELSE SUM(isnull(FACTIMPDET.FID_COS_TOT,0)*FACTIMP.FI_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_CODIGO),1),1) END) > 0 THEN 
			
			ROUND(SUM(FACTIMPDET.FID_COS_TOT) / (CASE WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTIMPDET.FID_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_CODIGO),1)
			 WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTIMPDET.FID_COS_TOT) ELSE SUM(isnull(FACTIMPDET.FID_COS_TOT,0)*FACTIMP.FI_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_CODIGO),1),1) END),4) ELSE 1 END AS PIF_FACTORMONEXT, 
			
			     'PIF_VALDLLS'=CASE WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN round(SUM(FACTIMPDET.FID_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_CODIGO),1),2)
			 WHEN FACTIMP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 round(SUM(FACTIMPDET.FID_COS_TOT),2) ELSE round(SUM(isnull(FACTIMPDET.FID_COS_TOT,0)*FACTIMP.FI_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTIMP.PI_CODIGO),1),1),2) END, 
			     FACTIMP.PR_CODIGO, FACTIMP.DI_PROVEE AS DI_CODIGO, FACTIMP.FI_CONSECUTIVOPED, FACTIMP.FI_CONT_REG 
		FROM FACTIMP LEFT OUTER JOIN 
		     FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO 
		WHERE FACTIMP.PI_CODIGO<>-1 AND FI_FACTAGRU NOT IN (SELECT PI_FACTAGRU FROM PEDIMP WHERE PI_MOVIMIENTO='E' AND PI_USAFACTAGRU = 'S' AND PI_FACTAGRU<>-1)
		GROUP BY FACTIMP.PI_CODIGO, FACTIMP.FI_CODIGO, FACTIMP.FI_FOLIO, FACTIMP.FI_FECHA, FACTIMP.IT_CODIGO, 
		FACTIMP.MO_CODIGO, FACTIMP.PR_CODIGO, FACTIMP.DI_PROVEE, FACTIMP.FI_CONSECUTIVOPED, FACTIMP.FI_CONT_REG 
	UNION
	-- agrupadora
		SELECT PEDIMP.PI_CODIGO, FACTEXPAGRU.FEA_CODIGO, FACTEXPAGRU.FEA_FOLIO, 
		    FACTEXPAGRU.FEA_FECHA, FACTEXPAGRU.IT_COMPANY1, 
		    FACTEXPAGRU.MO_CODIGO, PIF_VALMONEXT, PIF_FACTORMONEXT, PIF_VALDLLS, 
		FACTEXPAGRU.CL_DESTINI, FACTEXPAGRU.DI_DESTINI,  0 AS FEA_CONSECUTIVOPED, ''
		FROM FACTEXPAGRU INNER JOIN PEDIMP
		ON PEDIMP.PI_FACTAGRU = FACTEXPAGRU.FEA_CODIGO INNER JOIN 
		 (SELECT FACTEXP.PI_CODIGO, round(SUM(FACTEXPDET.FED_COS_TOT),2) AS PIF_VALMONEXT, 
		    CASE WHEN (CASE WHEN MAX(FACTEXP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
		    THEN SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTEXP.PI_CODIGO)),1)
		    WHEN MAX(FACTEXP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
		    SUM(FACTEXPDET.FED_COS_TOT) ELSE SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTEXP.PI_CODIGO)),1) END) > 0 THEN 
		    ROUND(SUM(FACTEXPDET.FED_COS_TOT) / (CASE WHEN MAX(FACTEXP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
		    THEN SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTEXP.PI_CODIGO)),1)
		    WHEN MAX(FACTEXP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
		    SUM(FACTEXPDET.FED_COS_TOT) ELSE SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTEXP.PI_CODIGO)),1) END),4) ELSE 1 END AS PIF_FACTORMONEXT, 
		      'PIF_VALDLLS'=CASE WHEN MAX(FACTEXP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
		    THEN round(SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTEXP.PI_CODIGO)),1),2) 
		    WHEN MAX(FACTEXP.MO_CODIGO) IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
		    round(SUM(FACTEXPDET.FED_COS_TOT),2) ELSE round(SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = MAX(FACTEXP.PI_CODIGO)),1),2) END 
		  FROM FACTEXP LEFT OUTER JOIN 
		      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO
		  WHERE FACTEXP.PI_CODIGO <> -1 AND FACTEXP.PI_CODIGO<>0
		 GROUP BY FACTEXP.PI_CODIGO) FACTURAIMP ON FACTURAIMP.PI_CODIGO=PEDIMP.PI_CODIGO 
		WHERE  PEDIMP.PI_USAFACTAGRU = 'S'
	--complementario
	UNION
		SELECT PEDIMP.PI_COMPLEMENTA AS PI_CODIGO, FACTEXP.FE_CODIGO AS FI_CODIGO, FACTEXP.FE_FOLIO AS FI_FOLIO, FACTEXP.FE_FECHA AS FI_FECHA, 
			       FACTEXP.IT_COMPANY1 AS IT_CODIGO, FACTEXP.MO_CODIGO, round(SUM(FACTEXPDET.FED_COS_TOT),2) AS PIF_VALMONEXT, 1 AS PIF_FACTORMONEXT, 
			     'PIF_VALDLLS'=CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN round(SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),2)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 round(SUM(FACTEXPDET.FED_COS_TOT),2) ELSE round(SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),1),2) END, 
			       FACTEXP.CL_DESTINI AS PR_CODIGO, FACTEXP.DI_DESTINI AS DI_CODIGO, 
			       FACTEXP.FE_CONSECUTIVOPED AS FI_CONSECUTIVOPED, FACTEXP.FE_CONT1_REG 
		FROM   FACTEXP LEFT OUTER JOIN 
		       FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO  LEFT OUTER JOIN 
		       PEDIMP ON PEDIMP.PI_CODIGO = FACTEXP.PI_CODIGO 
		WHERE     (dbo.PEDIMP.PI_COMPLEMENTA <> - 1)
		 GROUP BY PEDIMP.PI_COMPLEMENTA, FACTEXP.FE_CODIGO, FACTEXP.FE_FOLIO, FACTEXP.FE_FECHA, FACTEXP.IT_COMPANY1, 
		          FACTEXP.MO_CODIGO, FACTEXP.CL_DESTINI, FACTEXP.DI_DESTINI, FACTEXP.FE_CONSECUTIVOPED, dbo.FACTEXP.PI_CODIGO, FACTEXP.FE_CONT1_REG
	UNION 
		SELECT PEDIMP.PI_COMPLEMENTA AS PI_CODIGO, FACTEXP.FE_CODIGO AS FI_CODIGO, FACTEXP.FE_FOLIO AS FI_FOLIO, FACTEXP.FE_FECHA AS FI_FECHA, 
			       FACTEXP.IT_COMPANY1 AS IT_CODIGO, FACTEXP.MO_CODIGO, round(SUM(FACTEXPDET.FED_COS_TOT),2) AS PIF_VALMONEXT, 1 AS PIF_FACTORMONEXT, 
			     'PIF_VALDLLS'=CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN round(SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_RECTIFICA),1),2)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 round(SUM(FACTEXPDET.FED_COS_TOT),2) ELSE round(SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_RECTIFICA),1),1),2) END, 
			       FACTEXP.CL_DESTINI AS PR_CODIGO, FACTEXP.DI_DESTINI AS DI_CODIGO, 
			       FACTEXP.FE_CONSECUTIVOPED AS FI_CONSECUTIVOPED , FACTEXP.FE_CONT1_REG
		FROM   FACTEXP LEFT OUTER JOIN 
		       FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO  LEFT OUTER JOIN 
		       PEDIMP ON PEDIMP.PI_CODIGO = FACTEXP.PI_RECTIFICA 
		WHERE     (dbo.PEDIMP.PI_COMPLEMENTA <> - 1)
		 GROUP BY PEDIMP.PI_COMPLEMENTA, FACTEXP.FE_CODIGO, FACTEXP.FE_FOLIO, FACTEXP.FE_FECHA, FACTEXP.IT_COMPANY1, 
		          FACTEXP.MO_CODIGO, FACTEXP.CL_DESTINI, FACTEXP.DI_DESTINI, FACTEXP.FE_CONSECUTIVOPED, dbo.FACTEXP.PI_RECTIFICA, FACTEXP.FE_CONT1_REG
	union
	-- transferencias (faturas de exportacion relacionadas a la transferencia)
		SELECT FACTEXP.PI_CODIGO, FACTEXP.FE_CODIGO AS FI_CODIGO, FACTEXP.FE_FOLIO AS FI_FOLIO, FACTEXP.FE_FECHA AS FI_FECHA, 
			       FACTEXP.IT_COMPANY1 AS IT_CODIGO, FACTEXP.MO_CODIGO, round(SUM(FACTEXPDET.FED_COS_TOT),2) AS PIF_VALMONEXT, 
			
			 CASE WHEN (CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTEXPDET.FED_COS_TOT) ELSE SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),1) END) > 0 THEN 
			
			 ROUND(SUM(FACTEXPDET.FED_COS_TOT)/(CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 SUM(FACTEXPDET.FED_COS_TOT) ELSE SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),1) END),4) ELSE 1 END AS PIF_FACTORMONEXT, 
			
			     'PIF_VALDLLS'=CASE WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 154) 
			 THEN round(SUM(FACTEXPDET.FED_COS_TOT)/isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),2)
			 WHEN FACTEXP.MO_CODIGO IN (SELECT MO_CODIGO FROM MONEDA WHERE MONEDA.PA_CODIGO = 233) THEN 
			 round(SUM(FACTEXPDET.FED_COS_TOT),2) ELSE round(SUM(isnull(FACTEXPDET.FED_COS_TOT,0)*FACTEXP.FE_TIPOCAMBIO)/ISNULL(isnull((SELECT PI_TIP_CAM FROM PEDIMP WHERE PI_CODIGO = dbo.FACTEXP.PI_CODIGO),1),1),2) END, 
			 FACTEXP.CL_DESTINI AS PR_CODIGO, FACTEXP.DI_DESTINI AS DI_CODIGO, FACTEXP.FE_CONSECUTIVOPED AS FI_CONSECUTIVOPED, FACTEXP.FE_CONT1_REG 
		FROM         PEDIMPRELTRANS INNER JOIN 
		       FACTEXPDET ON PEDIMPRELTRANS.FED_INDICED = FACTEXPDET.FED_INDICED INNER JOIN 
		       PEDIMPDET ON PEDIMPRELTRANS.PID_INDICED = PEDIMPDET.PID_INDICED INNER JOIN 
		       FACTEXP ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO 
		 GROUP BY FACTEXP.PI_CODIGO, FACTEXP.FE_CODIGO, FACTEXP.FE_FOLIO, FACTEXP.FE_FECHA, FACTEXP.IT_COMPANY1, 
		        FACTEXP.MO_CODIGO, FACTEXP.CL_DESTINI, FACTEXP.DI_DESTINI, FACTEXP.FE_CONSECUTIVOPED, FACTEXP.FE_CONT1_REG) 
as VPEDIMPFACT1 LEFT OUTER JOIN
   VFACTFLETE ON VPEDIMPFACT1.PI_CODIGO = VFACTFLETE.PI_CODIGO AND 
   VPEDIMPFACT1.FI_CODIGO = VFACTFLETE.FI_CODIGO





GO
