SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VPEDIMPPERIODO
with encryption as
SELECT     'mes'=case when MONTH(FI_FECHA)=1 then 'ENERO' when MONTH(FI_FECHA)=2 then 'FEBRERO'
when MONTH(FI_FECHA)=3 then 'MARZO' when MONTH(FI_FECHA)=4 then 'ABRIL' when MONTH(FI_FECHA)=5 then 'MAYO'
when MONTH(FI_FECHA)=6 then 'JUNIO' when MONTH(FI_FECHA)=7 then 'JULIO' when MONTH(FI_FECHA)=8 then 'AGOSTO'
when MONTH(FI_FECHA)=9 then 'SEPTIEMBRE' when MONTH(FI_FECHA)=10 then 'OCTUBRE' when MONTH(FI_FECHA)=11 then 'NOVIEMBRE'
when MONTH(FI_FECHA)=12 then 'DICIEMBRE' end, YEAR(FI_FECHA) AS 'year', MONTH(FI_FECHA) as mesnum, FI_FECHA, PI_CODIGO
FROM         dbo.FACTIMP
WHERE PI_CODIGO<>-1
UNION
SELECT     'mes'=case when MONTH(FI_FECHA)=1 then 'ENERO' when MONTH(FI_FECHA)=2 then 'FEBRERO'
when MONTH(FI_FECHA)=3 then 'MARZO' when MONTH(FI_FECHA)=4 then 'ABRIL' when MONTH(FI_FECHA)=5 then 'MAYO'
when MONTH(FI_FECHA)=6 then 'JUNIO' when MONTH(FI_FECHA)=7 then 'JULIO' when MONTH(FI_FECHA)=8 then 'AGOSTO'
when MONTH(FI_FECHA)=9 then 'SEPTIEMBRE' when MONTH(FI_FECHA)=10 then 'OCTUBRE' when MONTH(FI_FECHA)=11 then 'NOVIEMBRE'
when MONTH(FI_FECHA)=12 then 'DICIEMBRE' end, YEAR(FI_FECHA) AS 'year', MONTH(FI_FECHA) as mesnum, FI_FECHA, PI_RECTIFICA
FROM         dbo.FACTIMP
WHERE PI_RECTIFICA<>-1






GO
