SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VPRODUCLIGA
with encryption as
SELECT     dbo.ORDTRABAJO.OT_FOLIO, dbo.PRODUCLIGA.PROD_INDICED, dbo.PRODUCLIGA.LIP_CANTDESC, dbo.ORDTRABAJODET.OTD_FECHAENTREGA, 
                      dbo.ORDTRABAJO.OT_FECHA, dbo.CLIENTE.CL_RAZON
FROM         dbo.ORDTRABAJO LEFT OUTER JOIN
                      dbo.CLIENTE ON dbo.ORDTRABAJO.CL_CODIGO = dbo.CLIENTE.CL_CODIGO RIGHT OUTER JOIN
                      dbo.ORDTRABAJODET ON dbo.ORDTRABAJO.OT_CODIGO = dbo.ORDTRABAJODET.OT_CODIGO RIGHT OUTER JOIN
                      dbo.PRODUCLIGA ON dbo.ORDTRABAJODET.OTD_INDICED = dbo.PRODUCLIGA.OTD_INDICED
WHERE     (dbo.ORDTRABAJO.OT_FOLIO IS NOT NULL)


GO
