SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO








































CREATE VIEW dbo.VFACTEXP
with encryption as
SELECT     FE_CODIGO, FE_FOLIO, FE_FECHA, TF_CODIGO, TQ_CODIGO, FE_TIPO, FE_PINICIAL, FE_PFINAL, FC_CODIGO, TN_CODIGO, FE_NO_SEM, 
                      FE_DOCUMENTO, FE_DESTINO, AG_MX, AG_US, CL_PROD, DI_PROD, CL_COMP, DI_COMP, CO_COMP, CL_COMPFIN, DI_COMPFIN, CO_COMPFIN, 
                      CL_EXP, DI_EXP, CL_EXPFIN, DI_EXPFIN, CL_DESTINI, DI_DESTINI, CO_DESTINI, CL_DESTFIN, DI_DESTFIN, CO_DESTFIN, CL_VEND, DI_VEND, 
                      CL_IMP, DI_IMP, CO_IMP, PU_CARGA, PU_SALIDA, PU_ENTRADA, PU_DESTINO, FE_FEC_ENV, FE_FEC_ARR, FE_NUM_ENV, FE_ENV_INST, 
                      FE_ORD_COMP, FE_NUM_CTL, FE_NUM_INBON, FE_TIPO_INBON, FE_FEC_INBON, FE_FIRMS, FE_COMENTA, FE_COMENTAUS, US_CODIGO, 
                      CT_COMPANY1, CA_COMPANY1, CJ_COMPANY1, CT_COMPANY2, CA_COMPANY2, CJ_COMPANY2, FE_TRAC_US1, FE_TRAC_MX1, FE_CONT1_REG, 
                      FE_CONT1_US, FE_CONT1_SELL, TCA_CONT1, PG_COMPANY1, FE_TRAC_CHO1, FE_LIM1, 
                      RU_COMPANY1, 'N' AS FE_FAIRE_MART1, FE_TPAGO_FLETE1, FE_TPAGO_FLETE2, 'N' AS FE_F_TERRT1,
                      IT_COMPANY1, 0 AS FE_TOTAL_TRANS1, MT_COMPANY1, FE_GUIA1, FE_TRAC_US2, FE_CONSECUTIVOPED,
                      FE_TRAC_MX2, FE_CONT2_REG, FE_CONT2_US, FE_CONT2_SELL, TCA_CONT2, 
                      PG_COMPANY2, FE_TRAC_CHO2, FE_LIM2, RU_COMPANY2, 'N' AS FE_FAIRE_MART2, 'N' AS FE_F_TERRT2,
                      IT_COMPANY2, 0 AS FE_TOTAL_TRANS2, MT_COMPANY2, FE_GUIA2, FE_TOTALB, FE_NUMVEHICULOS,
                      FE_TIPOCAMBIO, FE_MANIF, FE_MANIF_DATE, FE_AWB, FE_INCOTLUGAR1, FE_INCOTLUGAR2, FE_LAGNO, FE_DESCARGADA, 
                      FE_FACTAGRU, FE_ESTATUS, FE_CANCELADO, FE_MOSTRARDIV, MO_CODIGO, SPI_CODIGO, FE_CON_PEDCR, FE_DESCRIPTION1, 
                      FE_DESCRIPTION2, FE_INVOICETYPE, FE_HEADER, FE_FOOTER, FE_COMENTACO, ALM_CODIGO, FE_DISCHCONTENEDOR1, 
	         'PI_CODIGO'=CASE WHEN PI_RECTIFICA=-1 THEN PI_CODIGO ELSE PI_RECTIFICA END, FE_CUENTADET,
	         FE_DESCARGABLE, FE_USACONSOLIDADO, FE_SEL, FE_AUXDESC, FE_BARCODE, FE_PREVIADESC, FE_DESCSUST, BC_CODIGO, 
                      FE_DESCITALICA, FE_FECHADESCARGA, ETC_CODIGO, ET_CODIGO, FE_GAFETECHOFER
FROM         dbo.FACTEXP
WHERE FE_CANCELADO<>'S'




















































GO
