SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



































CREATE VIEW dbo.vwKARDESPED_FE
with encryption as
SELECT     dbo.VKARDESPED.KAP_CODIGO, dbo.VKARDESPED.KAP_TIPO_FACTRANS, dbo.FACTEXP.FE_FOLIO, dbo.FACTEXP.FE_FECHA, 
                      dbo.TFACTURA.TF_NOMBRE, dbo.FACTEXP.FE_TIPOCAMBIO, dbo.TEMBARQUE.TQ_NOMBRE, dbo.PEDIMP.PI_FOLIO, dbo.AGENCIAPATENTE.AGT_PATENTE, 
                      dbo.PEDIMP.PI_FEC_PAG, dbo.PEDIMP.PI_TIP_CAM, dbo.CLIENTE.CL_RFC, dbo.ADUANA.AD_CLAVE collate database_default + dbo.ADUANA.AD_SECCION collate database_default AS AD_SECC_CONST,
                       dbo.FACTEXPDET.FED_NOPARTE AS KPN_FNOPARTE, dbo.FACTEXPDET.FED_NOMBRE AS KPN_FNOMBRE, 
                      dbo.FACTEXPDET.FED_NAME AS KPN_FNAME, dbo.MEDIDA.ME_CORTO AS ME_FCORTO, dbo.PAIS.PA_CORTO AS PA_FCORTO, 
                      PAIS1.PA_CORTO AS PA_FPROCEDE, TIPO1.TI_NOMBRE AS TI_FNOMBRE, dbo.FACTEXPDET.EQ_GEN AS EQ_FGENERICO, 
                      MAESTRO1.MA_NOPARTE AS KPN_DNOPARTE, MAESTRO1.MA_NOMBRE AS KPN_DNOMBRE, MAESTRO1.MA_NAME AS KPN_DNAME, 
                      MEDIDA1.ME_CORTO AS ME_DCORTO, PAIS2.PA_CORTO AS PA_DCORTO, PAIS3.PA_CORTO AS PA_DPROCEDE, TIPO1.TI_NOMBRE AS TI_DNOMBRE,
                       dbo.ARANCEL.AR_FRACCION, dbo.SECTOR.SE_DESC
FROM         dbo.FACTEXPDET LEFT OUTER JOIN
                      dbo.TIPO ON dbo.FACTEXPDET.TI_CODIGO = dbo.TIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRO MAESTRO2 ON dbo.FACTEXPDET.MA_CODIGO = MAESTRO2.MA_CODIGO LEFT OUTER JOIN
                      dbo.PAIS ON dbo.FACTEXPDET.PA_CODIGO = dbo.PAIS.PA_CODIGO LEFT OUTER JOIN
                      dbo.MEDIDA ON dbo.FACTEXPDET.ME_CODIGO = dbo.MEDIDA.ME_CODIGO LEFT OUTER JOIN
                      dbo.PAIS PAIS1 ON MAESTRO2.PA_PROCEDE = PAIS1.PA_CODIGO RIGHT OUTER JOIN
                      dbo.MEDIDA MEDIDA1 RIGHT OUTER JOIN
                      dbo.PAIS PAIS3 RIGHT OUTER JOIN
                      dbo.MAESTRO MAESTRO1 RIGHT OUTER JOIN
                      dbo.VKARDESPED LEFT OUTER JOIN
                      dbo.ARANCEL ON dbo.VKARDESPED.AR_IMPMX = dbo.ARANCEL.AR_CODIGO ON MAESTRO1.MA_CODIGO = dbo.VKARDESPED.MA_HIJO ON 
                      PAIS3.PA_CODIGO = dbo.VKARDESPED.PA_PROCEDE LEFT OUTER JOIN
                      dbo.PAIS PAIS2 ON dbo.VKARDESPED.PA_ORIGEN = PAIS2.PA_CODIGO ON MEDIDA1.ME_CODIGO = dbo.VKARDESPED.ME_HIJO LEFT OUTER JOIN
                      dbo.TEMBARQUE RIGHT OUTER JOIN
                      dbo.FACTEXP ON dbo.TEMBARQUE.TQ_CODIGO = dbo.FACTEXP.TQ_CODIGO LEFT OUTER JOIN
                      dbo.TFACTURA ON dbo.FACTEXP.TF_CODIGO = dbo.TFACTURA.TF_CODIGO ON 
                      dbo.VKARDESPED.KAP_FACTRANS = dbo.FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      dbo.ADUANA RIGHT OUTER JOIN
                      dbo.PEDIMP LEFT OUTER JOIN
                      dbo.CLIENTE ON dbo.PEDIMP.CL_CODIGO = dbo.CLIENTE.CL_CODIGO ON dbo.ADUANA.AD_CODIGO = dbo.PEDIMP.AD_ORI LEFT OUTER JOIN
                      dbo.AGENCIAPATENTE ON dbo.PEDIMP.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO ON dbo.VKARDESPED.KAP_PED_CONST = dbo.PEDIMP.PI_CODIGO ON 
                      dbo.FACTEXPDET.FED_INDICED = dbo.VKARDESPED.KAP_INDICED_FACT LEFT OUTER JOIN
                      dbo.TIPO TIPO1 ON dbo.VKARDESPED.TI_HIJO = TIPO1.TI_CODIGO LEFT OUTER JOIN
                      dbo.SECTOR ON dbo.VKARDESPED.SE_CODIGO = dbo.SECTOR.SE_CODIGO
WHERE     (dbo.VKARDESPED.KAP_TIPO_FACTRANS = 'F')


































































GO
