SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






































CREATE VIEW dbo.VTABLASMAESTRO
with encryption as
SELECT     dbo.MAESTRO.MA_CODIGO, dbo.ANEXO24.ANX_MATERIAL, dbo.ANEXO24.FUN_CODIGO, dbo.ANEXO24.ANX_LARGO, dbo.ANEXO24.ANX_ANCHO, 
                      dbo.ANEXO24.ANX_DIAME, dbo.ANEXO24.ANX_ALTURA, dbo.ANEXO24.ANX_VID_YEAR, dbo.ANEXO24.ANX_VID_MES, dbo.ANEXO24.ANX_VID_DIA, 
                      dbo.ANEXO24.ANX_STA_FIS, dbo.ANEXO24.ANX_CAS_NUM, dbo.ANEXO24.ANX_BASE_SECA, dbo.ANEXO24.ANX_CAP_EMP, 
                      dbo.ANEXO24.TCA_CODIGO, dbo.ANEXO24.ANX_CONT_REG, dbo.MAESTROAUX.FCC_CODIGO, dbo.MAESTROAUX.MAX_FCCQTYAPPROVAL, 
                      dbo.MAESTROAUX.MAX_FCCIDENTIFIER, dbo.MAESTROAUX.MAX_FCCTRADENAME, dbo.MAESTROAUX.MAX_FCCPUBLICINSPECTION, 
                      dbo.MAESTROAUX.FDA_CODIGO, dbo.MAESTROAUX.FDA_PRODCODE, dbo.MAESTROAUX.MAX_FDASTORAGE, 
                      dbo.MAESTROAUX.PA_FDACOUNTRYCODE, dbo.MAESTROAUX.MAX_FDAMARKER, dbo.MAESTRODEF.MA_DEFTXT1, dbo.MAESTRODEF.MA_DEFTXT2,
                       dbo.MAESTRODEF.MA_DEFTXT3, dbo.MAESTRODEF.MA_DEFNO1, dbo.MAESTRODEF.MA_DEFNO2, dbo.MAESTRODEF.MA_DEFNO3, 
                      dbo.NAFTA.NFT_CLASE, dbo.NAFTA.NFT_FABRICA, dbo.NAFTA.NFT_CRITERIO, dbo.NAFTA.NFT_NETCOST, dbo.NAFTA.NFT_OTRASINST, 
                      dbo.NAFTA.NFT_COSTOSRESTAR, dbo.NAFTA.NFT_RESOLUCION, dbo.NAFTA.NFT_VERBIENFUNG, dbo.NAFTA.NFT_CONTROLINV, 
                      dbo.NAFTA.NFT_ORIGBIENFUNG, dbo.NAFTA.NFT_CONTROLINV2, dbo.NAFTA.NFT_PERSONAREL, dbo.NAFTA.CL_EMPRESA, dbo.NAFTA.NFT_FECHA, 
                      dbo.NAFTA.NFT_TIPOEXP, dbo.NAFTA.NFT_FECHACERT, dbo.NAFTA.US_CERTIFICADO, dbo.NAFTA.NFT_VCR, dbo.NAFTA.US_CODIGO, 
                      dbo.NAFTA.NFT_PROCESO, dbo.VMAESTROCOST.MA_GRAV_MP, dbo.VMAESTROCOST.MA_GRAV_ADD, dbo.VMAESTROCOST.MA_GRAV_EMP, 
                      dbo.VMAESTROCOST.MA_GRAV_GI, dbo.VMAESTROCOST.MA_GRAV_GI_MX, dbo.VMAESTROCOST.MA_GRAV_MO, dbo.VMAESTROCOST.MA_NG_MP, 
                      dbo.VMAESTROCOST.MA_NG_ADD, dbo.VMAESTROCOST.MA_NG_EMP, dbo.VMAESTROCOST.MA_COSTO, dbo.VMAESTROCOST.MA_NG_USA, 
                      dbo.VMAESTROCOST.TV_CODIGO, dbo.VMAESTROCOST.MA_NOPARTE, dbo.VMAESTROCOST.MA_NOPARTEAUX, dbo.VMAESTROCOST.TCO_CODIGO, 
                      dbo.MAESTROAUXDET.MAXD_AFFCODE, dbo.MAESTROAUXDET.MAXD_AFFQUAL
FROM         dbo.MAESTRO LEFT OUTER JOIN
                      dbo.MAESTROAUXDET ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTROAUXDET.MA_CODIGO LEFT OUTER JOIN
                      dbo.VMAESTROCOST ON dbo.MAESTRO.MA_CODIGO = dbo.VMAESTROCOST.MA_CODIGO LEFT OUTER JOIN
                      dbo.NAFTA ON dbo.MAESTRO.MA_CODIGO = dbo.NAFTA.MA_CODIGO LEFT OUTER JOIN
                      dbo.MAESTRODEF ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTRODEF.MA_CODIGO LEFT OUTER JOIN
                      dbo.MAESTROAUX ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTROAUX.MA_CODIGO LEFT OUTER JOIN
                      dbo.ANEXO24 ON dbo.MAESTRO.MA_CODIGO = dbo.ANEXO24.MA_CODIGO






































GO
