SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW dbo.VPEDIMPDTA
with encryption as
SELECT     dbo.PEDIMPCONTRIBUCION.PI_CODIGO, SUM(ROUND(dbo.PEDIMPCONTRIBUCION.PIT_CONTRIBTOTMN, 0)) AS PIT_CONTRIBTOTMN
FROM         dbo.PEDIMPCONTRIBUCION LEFT OUTER JOIN
                      dbo.CONTRIBUCION ON dbo.PEDIMPCONTRIBUCION.CON_CODIGO = dbo.CONTRIBUCION.CON_CODIGO
GROUP BY dbo.PEDIMPCONTRIBUCION.PI_CODIGO, dbo.CONTRIBUCION.CON_CLAVE
HAVING      (dbo.CONTRIBUCION.CON_CLAVE = '1')


GO
