SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VMAXIMOCOTIZACION
with encryption as
SELECT     MAX(COTA_INDICED) AS COTA_INDICED, COT_CODIGO
FROM         dbo.COTIZACIONAVISO
GROUP BY COT_CODIGO

GO
