SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO








CREATE VIEW dbo.VKARDESPED1
with encryption as
SELECT     dbo.KARDESPED.KAP_CODIGO, dbo.FACTEXP.FE_FOLIO, dbo.FACTEXP.FE_FECHA, dbo.TFACTURA.TF_NOMBRE, dbo.TEMBARQUE.TQ_NOMBRE, 
                      dbo.AGENCIAPATENTE.AGT_PATENTE collate database_default + '-' + dbo.PEDIMP.PI_FOLIO collate database_default AS [PATENTE-FOLIO], 
                      dbo.ADUANA.AD_CLAVE + '-' + dbo.ADUANA.AD_SECCION AS [ADUANA-SECCION], dbo.PEDIMP.PI_FEC_ENT AS PI_FEC_PAG, dbo.PEDIMP.PI_TIP_CAM, 
                      dbo.CLIENTE.CL_RFC, dbo.FACTEXPDET.FED_NOPARTE, dbo.FACTEXPDET.FED_NOMBRE, dbo.FACTEXPDET.FED_NAME, 
                      dbo.FACTEXPDET.FED_FECHA_STRUCT, dbo.FACTEXPDET.EQ_GEN, dbo.MAESTRO.MA_NOPARTE, dbo.MAESTRO.MA_NOMBRE, 
                      dbo.MAESTRO.MA_NAME, dbo.FACTEXP.FE_TIPOCAMBIO, dbo.FACTEXPDET.FED_CANT, dbo.PEDIMP.PI_CODIGO AS KAP_PED_CONST
FROM         dbo.AGENCIAPATENTE RIGHT OUTER JOIN
                      dbo.ADUANA RIGHT OUTER JOIN
                      dbo.FACTEXPDET RIGHT OUTER JOIN
                      dbo.TEMBARQUE RIGHT OUTER JOIN
                      dbo.FACTEXP ON dbo.TEMBARQUE.TQ_CODIGO = dbo.FACTEXP.TQ_CODIGO LEFT OUTER JOIN
                      dbo.TFACTURA ON dbo.FACTEXP.TF_CODIGO = dbo.TFACTURA.TF_CODIGO RIGHT OUTER JOIN
                      dbo.MAESTRO RIGHT OUTER JOIN
                      dbo.KARDESPED ON dbo.MAESTRO.MA_CODIGO = dbo.KARDESPED.MA_HIJO ON dbo.FACTEXP.FE_CODIGO = dbo.KARDESPED.KAP_FACTRANS ON 
                      dbo.FACTEXPDET.FED_INDICED = dbo.KARDESPED.KAP_INDICED_FACT LEFT OUTER JOIN
                      dbo.PEDIMPDET LEFT OUTER JOIN
                      dbo.PEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.PEDIMP.PI_CODIGO ON 
                      dbo.KARDESPED.KAP_INDICED_PED = dbo.PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      dbo.CLIENTE ON dbo.PEDIMP.PR_CODIGO = dbo.CLIENTE.CL_CODIGO ON dbo.ADUANA.AD_CODIGO = dbo.PEDIMP.AD_DES ON 
                      dbo.AGENCIAPATENTE.AGT_CODIGO = dbo.PEDIMP.AGT_CODIGO






GO
