SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VA17PEDIMENTOS
with encryption as
SELECT     dbo.A17DET.A17_CODIGO, dbo.VPEDEXP.[PATENTE-FOLIO], dbo.VPEDEXP.PI_FEC_ENT
FROM         dbo.A17DET LEFT OUTER JOIN
                      dbo.VPEDEXP ON dbo.A17DET.PI_CODIGO = dbo.VPEDEXP.PI_CODIGO
WHERE     (dbo.VPEDEXP.PI_TIPO IN ('A', 'C'))
GROUP BY dbo.A17DET.A17_CODIGO, dbo.VPEDEXP.[PATENTE-FOLIO], dbo.VPEDEXP.PI_FEC_ENT

GO
