SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO











CREATE VIEW dbo.VPEDIMPFACTDET
with encryption as
SELECT     dbo.PEDIMPDET.PI_CODIGO, dbo.PEDIMPDET.PID_INDICED, dbo.VPEDIMPFACT.FI_FOLIO, dbo.VPEDIMPFACT.FI_CODIGO, 
                      dbo.VPEDIMPFACT.FI_FECHA, dbo.VPEDIMPFACT.IT_CODIGO, dbo.VPEDIMPFACT.MO_CODIGO, dbo.VPEDIMPFACT.PR_CODIGO, 
                      dbo.VPEDIMPFACT.DI_CODIGO, dbo.PEDIMPDET.PID_CTOT_DLS * dbo.VPEDIMPFACT.PIF_FACTORMONEXT AS PIF_VALMONEXT, 
                      dbo.VPEDIMPFACT.PIF_FACTORMONEXT, dbo.PEDIMPDET.PID_CTOT_DLS AS PIF_VALDLLS
FROM         dbo.VPEDIMPFACT INNER JOIN
                      dbo.PEDIMPDET ON dbo.VPEDIMPFACT.FI_CODIGO = dbo.PEDIMPDET.PID_CODIGOFACT AND 
                      dbo.VPEDIMPFACT.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO
WHERE dbo.PEDIMPDET.PID_IMPRIMIR='S'





GO
