SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.[HARVARD BOMSTRUCT]
AS
SELECT     TOP 100 PERCENT BSU_NOPARTE, BST_NOPARTE, BST_TIP_ENS, BST_PERINI, BST_PERFIN
FROM         dbo.BOM_STRUCT
WHERE     (BST_TIP_ENS = 'a')
ORDER BY BST_NOPARTE, BSU_NOPARTE, BST_PERINI, BST_PERFIN
GO
