SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO








CREATE VIEW dbo.VMAESTROCOST1
with encryption as
SELECT     dbo.MAESTROCOST.MAC_CODIGO, dbo.MAESTROCOST.TCO_CODIGO, dbo.MAESTROCOST.MA_CODIGO, dbo.MAESTROCOST.MA_GRAV_MP, dbo.MAESTROCOST.MA_GRAV_ADD, 
                      dbo.MAESTROCOST.MA_GRAV_EMP, dbo.MAESTROCOST.MA_GRAV_GI, dbo.MAESTROCOST.MA_GRAV_GI_MX, dbo.MAESTROCOST.MA_GRAV_MO, 
                      dbo.MAESTROCOST.MA_NG_MP, dbo.MAESTROCOST.MA_NG_ADD, dbo.MAESTROCOST.MA_NG_EMP, dbo.MAESTROCOST.MA_COSTO, 
                      dbo.MAESTROCOST.MA_GRAVA_VA, dbo.MAESTROCOST.MA_NG_USA, dbo.MAESTROCOST.MA_NG_MX, dbo.MAESTROCOST.TV_CODIGO, 
                      isnull(dbo.MAESTRO.MA_NOPARTE, dbo.MAESTROREFER.MA_NOPARTE) as MA_NOPARTE, isnull(dbo.MAESTRO.MA_NOPARTEAUX,dbo.MAESTROREFER.MA_NOPARTEAUX) as MA_NOPARTEAUX, dbo.MAESTROCOST.SPI_CODIGO
FROM         dbo.MAESTROREFER LEFT OUTER JOIN
                      dbo.CONFIGURATIPO CONFIGURATIPO_1 ON dbo.MAESTROREFER.TI_CODIGO = CONFIGURATIPO_1.TI_CODIGO RIGHT OUTER JOIN
                      dbo.MAESTROCOST ON dbo.MAESTROREFER.MA_CODIGO = dbo.MAESTROCOST.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO RIGHT OUTER JOIN
                      dbo.MAESTRO ON dbo.CONFIGURATIPO.TI_CODIGO = dbo.MAESTRO.TI_CODIGO ON 
                      dbo.MAESTROCOST.MA_CODIGO = dbo.MAESTRO.MA_CODIGO
WHERE     ((((isnull(dbo.CONFIGURATIPO.CFT_TIPO,CONFIGURATIPO_1.CFT_TIPO) <> 'P' AND isnull(dbo.CONFIGURATIPO.CFT_TIPO,CONFIGURATIPO_1.CFT_TIPO) <> 'S') OR dbo.MAESTRO.MA_TIP_ENS = 'C') AND
dbo.MAESTROCOST.TCO_CODIGO IN (SELECT TCO_COMPRA FROM CONFIGURACION)) OR
(((isnull(dbo.CONFIGURATIPO.CFT_TIPO,CONFIGURATIPO_1.CFT_TIPO) = 'P' OR isnull(dbo.CONFIGURATIPO.CFT_TIPO,CONFIGURATIPO_1.CFT_TIPO) = 'S') AND dbo.MAESTRO.MA_TIP_ENS<>'C' )) AND
dbo.MAESTROCOST.TCO_CODIGO IN (SELECT TCO_MANUFACTURA FROM CONFIGURACION))
AND (isnull(dbo.MAESTRO.MA_INV_GEN,'I') = 'I') AND (dbo.MAESTROCOST.MA_PERINI <= convert(varchar(11), getdate(),101))
 AND (dbo.MAESTROCOST.MA_PERFIN >= convert(varchar(11), getdate(),101)) 


GO
