SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



















































CREATE VIEW dbo.VBOM_STRUCTDESC
with encryption as

SELECT    dbo.BOM_STRUCT.BSU_SUBENSAMBLE, dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_INCORPOR) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
                      dbo.BOM_STRUCT.BST_TIP_ENS, 'N' AS BST_TIPODESC,
		dbo.MAESTRO.MA_PESO_KG BST_PESO_KG, isnull((SELECT MA_COSTO FROM VMAESTROCOST
	WHERE MA_CODIGO=dbo.BOM_STRUCT.BST_HIJO),0) as MA_COSTO
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
WHERE dbo.CONFIGURATIPO.CFT_TIPO='P' OR dbo.CONFIGURATIPO.CFT_TIPO='S'
GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.MAESTRO.MA_PESO_KG, dbo.BOM_STRUCT.BST_PERFIN
HAVING dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND SUM(dbo.BOM_STRUCT.BST_INCORPOR) >0















































GO
