SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






































CREATE VIEW dbo.VIMP_DICTAMEN
with encryption as
SELECT     dbo.DICTAMENFISCAL.DF_CODIGO, dbo.VPEDIMP.PI_CODIGO, dbo.VPEDIMP.CL_CODIGO, dbo.VPEDIMP.PR_CODIGO, dbo.VPEDIMP.CP_CODIGO, 
                      dbo.VPEDIMP.AG_CODIGO, dbo.VPEDIMP.AD_DES, SUM(dbo.PEDIMPDET.PID_VAL_ADU) AS PID_VAL_ADU, 
                      dbo.PEDIMPDET.PA_ORIGEN, dbo.PEDIMPDET.PA_PROCEDE, (SELECT MAX(dbo.FACTIMP.FI_TIPO) FROM dbo.FACTIMP WHERE dbo.FACTIMP.PI_CODIGO=dbo.VPEDIMP.PI_CODIGO OR dbo.FACTIMP.PI_RECTIFICA=dbo.VPEDIMP.PI_CODIGO) AS PI_TIPO_VCFP, dbo.TIPO.TI_DICTAMEN
FROM         dbo.MAESTRO RIGHT OUTER JOIN
                      dbo.PEDIMPDET LEFT OUTER JOIN
                      dbo.TIPO ON dbo.PEDIMPDET.TI_CODIGO = dbo.TIPO.TI_CODIGO ON dbo.MAESTRO.MA_CODIGO = dbo.PEDIMPDET.MA_CODIGO RIGHT OUTER JOIN
                      dbo.DICTAMENFISCAL LEFT OUTER JOIN
                      dbo.VPEDIMP ON dbo.DICTAMENFISCAL.DF_FECHAINI <= dbo.VPEDIMP.PI_FEC_ENT AND 
                      dbo.DICTAMENFISCAL.DF_FECHAFIN >= dbo.VPEDIMP.PI_FEC_ENT ON dbo.PEDIMPDET.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO LEFT OUTER JOIN
                      dbo.PIDescarga ON dbo.PEDIMPDET.PID_INDICED = dbo.PIDescarga.PID_INDICED
GROUP BY dbo.DICTAMENFISCAL.DF_CODIGO, dbo.VPEDIMP.PI_CODIGO, dbo.VPEDIMP.CL_CODIGO, dbo.VPEDIMP.PR_CODIGO, dbo.VPEDIMP.CP_CODIGO, 
                      dbo.VPEDIMP.AG_CODIGO, dbo.VPEDIMP.AD_DES, dbo.PEDIMPDET.PA_ORIGEN, dbo.PEDIMPDET.PA_PROCEDE, dbo.TIPO.TI_DICTAMEN
















































GO
