SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO







CREATE VIEW dbo.VPEDIMPDETDIDENTIFICA2
with encryption as
SELECT     PID_INDICED, PI_CODIGO, PIID_CODIGO,
	(SELECT     dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO
		FROM         dbo.PEDIMPDETIDENTIFICA INNER JOIN
		                      dbo.PEDIMPDET ON dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB
		WHERE (dbo.PEDIMPDETIDENTIFICA.PIID_TIPO = 'N') AND dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE IN ('PS','TL','NE'))
                            GROUP BY dbo.PEDIMPDET.PID_INDICED, dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO
                            HAVING      (dbo.PEDIMPDET.PID_INDICED = PEDIMPDETDIDENTIFICA1.PID_INDICED) AND 
                                                   MIN(dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO) <> PEDIMPDETDIDENTIFICA1.PIID_CODIGO) AS PIID_CODIGO2
FROM	(SELECT     MIN(PIID_CODIGO) AS PIID_CODIGO, PID_INDICED, PI_CODIGO
	FROM        (SELECT     dbo.PEDIMPDET.PI_CODIGO, dbo.PEDIMPDET.PID_INDICED, dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO, dbo.PEDIMPDETIDENTIFICA.PIID_DESC, 
		                      dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO
		FROM         dbo.PEDIMPDETIDENTIFICA INNER JOIN
		                      dbo.PEDIMPDET ON dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB
		 WHERE     (dbo.PEDIMPDETIDENTIFICA.PIID_TIPO = 'N') AND dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO
	               IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE IN ('PS','TL','NE'))) PEDIMPDETDIDENTIFICA0
	GROUP BY PID_INDICED, PI_CODIGO) PEDIMPDETDIDENTIFICA1
GROUP BY PIID_CODIGO, PI_CODIGO, PID_INDICED






























































GO
