SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




CREATE VIEW dbo.VCONSTEXPSAL1ERCONST
with encryption as
SELECT     dbo.FACTEXP.FE_CODIGO, MIN(dbo.VFACTEXPPED.FEP_INDICEP) AS FEP_INDICEP
FROM         dbo.FACTEXP LEFT OUTER JOIN
                      dbo.VFACTEXPPED ON dbo.FACTEXP.FE_CODIGO = dbo.VFACTEXPPED.KAP_FACTRANS
GROUP BY dbo.FACTEXP.FE_CODIGO, dbo.VFACTEXPPED.FEP_TIPO
HAVING      (dbo.VFACTEXPPED.FEP_TIPO = 'Constancia')
AND MIN(dbo.VFACTEXPPED.FEP_INDICEP) IS NOT NULL






GO
