SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






-- material no gravable
CREATE VIEW dbo.VEXHIBIT_B_BASE247
with encryption as
SELECT     TOP 100 PERCENT dbo.COSTSUBPER.CS_CODIGO, dbo.ENTRYSUM.ET_CODIGO, dbo.ENTRYSUM.ET_ENTRY_NO, dbo.FACTEXP.FE_CODIGO, 
                      dbo.ENTRYSUM.ET_FEC_ENTRYS, dbo.ENTRYSUMARA.AR_CODIGO, dbo.ENTRYSUMARA.AR_NG_EMP, 
                      ISNULL(ROUND(dbo.ENTRYSUMARA.ETA_RATE, 2), 0) AS ETA_RATE, ISNULL(dbo.ENTRYSUMARA.ETA_DLLS_MPF, 0) AS ETA_DLLS_MPF, 
                      ISNULL(dbo.ENTRYSUMARA.ETA_COS_TOT, 0) AS ETA_COS_TOT, ISNULL(dbo.ENTRYSUMARA.ETA_DLLS_RATE, 0) AS ETA_DUT_PAG, 
                      ISNULL(dbo.ENTRYSUMARA.ETA_WMPF, 0) AS ETA_WMPF, ISNULL(dbo.ENTRYSUMARA.ETA_WOMPF, 0) AS ETA_WOMPF, dbo.FACTEXP.FE_FOLIO, 
                      ARANCEL_3.AR_FRACCION, dbo.ENTRYSUMARA.ETA_CODIGO, dbo.ENTRYSUMARA.SPI_CODIGO, dbo.ENTRYSUMARA.MA_NAFTA, 
                      ISNULL(dbo.ENTRYSUMARA.ETA_CANT, 0) AS ETA_CANT, dbo.ENTRYSUM.PU_ENTRADA, dbo.ENTRYSUMARA.PA_CODIGO, 
                      ISNULL(dbo.ENTRYSUMARA.ETA_GRAV_VA, 0) AS ETA_GRAV_VA, ISNULL(dbo.ENTRYSUMARA.ETA_GRAV_MAT, 0) AS ETA_GRAV_MAT, 
                      ISNULL(dbo.ENTRYSUMARA.ETA_NG_MAT, 0) AS ETA_NG_MAT, ISNULL(dbo.ENTRYSUMARA.ETA_NG_EMP, 0) AS ETA_NG_EMP, 
                      ARANCEL_2.AR_FRACCION AS FRACCIONNGEMP, ARANCEL_1.AR_FRACCION AS FRACCIONORIG
FROM         dbo.FACTEXP INNER JOIN
                      dbo.COSTSUBPER ON dbo.FACTEXP.CL_DESTINI = dbo.COSTSUBPER.CL_CODIGO FULL OUTER JOIN
                      dbo.ARANCEL ARANCEL_2 RIGHT OUTER JOIN
                      dbo.ARANCEL ARANCEL_3 RIGHT OUTER JOIN
                      dbo.ENTRYSUMARA ON ARANCEL_3.AR_CODIGO = dbo.ENTRYSUMARA.AR_CODIGO ON 
                      ARANCEL_2.AR_CODIGO = dbo.ENTRYSUMARA.AR_NG_EMP RIGHT OUTER JOIN
                      dbo.ENTRYSUM ON dbo.ENTRYSUMARA.ET_CODIGO = dbo.ENTRYSUM.ET_CODIGO ON 
                      dbo.COSTSUBPER.CS_FECHAINI <= dbo.ENTRYSUM.ET_FEC_ENTRYS AND 
                      dbo.COSTSUBPER.CS_FECHAFIN >= dbo.ENTRYSUM.ET_FEC_ENTRYS AND 
                      dbo.FACTEXP.FE_CODIGO = dbo.ENTRYSUMARA.FE_CODIGO LEFT OUTER JOIN
                      dbo.ARANCEL ARANCEL_1 ON dbo.ENTRYSUMARA.AR_ORIG = ARANCEL_1.AR_CODIGO
WHERE     (dbo.FACTEXP.TN_CODIGO = 2 OR
                      dbo.FACTEXP.TN_CODIGO = 5 OR
                      dbo.FACTEXP.TN_CODIGO = 6 OR
                      dbo.FACTEXP.TN_CODIGO = 7 OR dbo.FACTEXP.TN_CODIGO = 8 OR dbo.FACTEXP.TN_CODIGO = 9) and dbo.ENTRYSUM.ET_ENTRY_NO is not null
ORDER BY dbo.FACTEXP.FE_FOLIO



GO
