SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE VIEW dbo.VBOMSUBCOSTO1
with encryption as
SELECT BSU_SUBENSAMBLE, BST_HIJO,
'FORANEO'=CASE WHEN (MAESTRO.TI_CODIGO=14 or MAESTRO.TI_CODIGO=16) then
(round(isnull(MA_GRAV_MP,0),6)+round(isnull(MA_GRAV_EMP,0),6)+round(isnull(MA_GRAV_ADD,0),6))*BOM_STRUCT.BST_INCORPOR
else
(case when MAESTRO.BST_TIPOCOSTO='E' or MAESTRO.BST_TIPOCOSTO='A' or MAESTRO.BST_TIPOCOSTO='B'
then round(isnull(MA_COSTO,0),6)*BOM_STRUCT.BST_INCORPOR else  0 end)
end,
'ORIGINARIO'=CASE WHEN (MAESTRO.TI_CODIGO=14 or MAESTRO.TI_CODIGO=16)
then (round(isnull(MA_NG_MP,0),6)+round(isnull(MA_NG_EMP,0),6)+round(isnull(MA_NG_ADD,0),6))*BOM_STRUCT.BST_INCORPOR
else
(case when MAESTRO.BST_TIPOCOSTO='C' or MAESTRO.BST_TIPOCOSTO='D' or MAESTRO.BST_TIPOCOSTO='F'or MAESTRO.BST_TIPOCOSTO='P' or MAESTRO.BST_TIPOCOSTO='N'
then round(isnull(MA_COSTO,0),6)*BOM_STRUCT.BST_INCORPOR else  0 end)
end
FROM  BOM_STRUCT INNER JOIN MAESTRO ON BOM_STRUCT.BST_HIJO=MAESTRO.MA_CODIGO INNER JOIN
		      VMAESTROCOST ON BOM_STRUCT.BST_HIJO = VMAESTROCOST.MA_CODIGO
WHERE     VMAESTROCOST.SPI_CODIGO = 22 AND (GETDATE() between BST_PERINI AND BST_PERFIN)








GO
