SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO










CREATE VIEW dbo.VBASEINVENTARIO
with encryption as
SELECT     TOP 100 PERCENT CASE WHEN PEDIMP.PI_TIPO IN ('C', 'A') THEN isnull(AGENCIAPATENTE.AGT_PATENTE, '') collate database_default
                      + '-' + PEDIMP.PI_FOLIO collate database_default ELSE PEDIMP.PI_FOLIO END AS NoPedimento, CLAVEPED.CP_CLAVE,
	        PEDIMPDET.PI_CODIGO, PEDIMPDET.PID_INDICED,PEDIMP.PI_FEC_ENT AS FechaPedimento, 
                      PEDIMP.PI_FEC_PAG AS FechaPagoPedimento, round(PIDESCARGA.PID_SALDOGEN / ISNULL(PEDIMPDET.EQ_GENERICO, 1) ,6)
                      AS PID_saldoCANT, MEDIDA_1.ME_CORTO, round(PIDESCARGA.PID_SALDOGEN,6) AS PID_SALDOGEN, isnull(MEDIDA_2.ME_CORTO, 'SIN UM') 
                      AS ME_GEN, PEDIMPDET.PID_COS_UNI, ARANCEL.AR_FRACCION, PEDIMPDET.PID_POR_DEF, PEDIMPDET.MA_CODIGO, 
                      SECTOR.SE_CLAVE, SPI.SPI_CLAVE, PEDIMPDET.TI_CODIGO, PEDIMPDET.PID_NOPARTE, 
                      'CFT_TIPO' = CASE WHEN CONFIGURATIPO.CFT_TIPO = 'C' OR (CONFIGURATIPO.CFT_TIPO = 'H' AND CLAVEPED.CP_CLAVE <> 'H3') OR
                      CONFIGURATIPO.CFT_TIPO = 'Q' OR CONFIGURATIPO.CFT_TIPO = 'X' THEN 'Q' ELSE 'R' END, 
                      'PID_DEF_TIP' = CASE PEDIMPDET.PID_DEF_TIP WHEN 'G' THEN 'General' WHEN 'S' THEN 'PPS' WHEN 'P' THEN 'Bajo Tratado' WHEN 'R' THEN
                       'Regla Octava' END, PEDIMPDET.PID_NOMBRE, PID_COS_UNIGEN
FROM         SECTOR RIGHT OUTER JOIN
                      CONFIGURATIPO RIGHT OUTER JOIN
                      PEDIMPDET ON CONFIGURATIPO.TI_CODIGO = PEDIMPDET.TI_CODIGO LEFT OUTER JOIN
                      SPI ON PEDIMPDET.SPI_CODIGO = SPI.SPI_CODIGO ON SECTOR.SE_CODIGO = PEDIMPDET.PID_SEC_IMP LEFT OUTER JOIN
                      AGENCIAPATENTE RIGHT OUTER JOIN
                      PEDIMP ON AGENCIAPATENTE.AGT_CODIGO = PEDIMP.AGT_CODIGO ON 
                      PEDIMPDET.PI_CODIGO = PEDIMP.PI_CODIGO LEFT OUTER JOIN
                      ARANCEL ON PEDIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO LEFT OUTER JOIN
                      MAESTRO ON PEDIMPDET.MA_GENERICO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      MEDIDA MEDIDA_1 ON PEDIMPDET.ME_CODIGO = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
                      MEDIDA MEDIDA_2 ON PEDIMPDET.ME_GENERICO = MEDIDA_2.ME_CODIGO LEFT OUTER JOIN
                      CLAVEPED ON CLAVEPED.CP_CODIGO = PEDIMP.CP_CODIGO LEFT OUTER JOIN PIDESCARGA ON
	         PEDIMPDET.PID_INDICED=PIDESCARGA.PID_INDICED
WHERE     (PEDIMP.PI_MOVIMIENTO = 'E') AND (PEDIMP.PI_ESTATUS <> 'R') AND round((PIDESCARGA.PID_SALDOGEN),6) > 0 
        AND ((CASE WHEN PEDIMP.PI_TIPO IN ('C', 'A') THEN isnull(AGENCIAPATENTE.AGT_PATENTE, '') 
        + '-' + PEDIMP.PI_FOLIO ELSE PEDIMP.PI_FOLIO END) IS NOT NULL) AND 
        CLAVEPED.CP_DESCARGABLE = 'S' 















GO
