SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VMONEDA
with encryption as
SELECT     TOP 100 PERCENT dbo.MONEDA.MO_CODIGO, dbo.MONEDA.MO_NOMBRE, dbo.MONEDA.MO_NAME, dbo.PAIS.PA_NOMBRE, dbo.PAIS.PA_NAME, 
                      dbo.MONEDA.MO_CLAVEPED
FROM         dbo.MONEDA INNER JOIN
                      dbo.PAIS ON dbo.MONEDA.PA_CODIGO = dbo.PAIS.PA_CODIGO
ORDER BY dbo.MONEDA.MO_NOMBRE



GO
