SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






CREATE VIEW dbo.VINVENTARIO
with encryption as
SELECT     NoPedimento, PI_CODIGO, PID_INDICED,FechaPedimento, FechaPagoPedimento, SUM(PID_saldoCANT) AS PID_saldoCANT, ME_CORTO, SUM(PID_SALDOGEN) 
                      AS PID_SALDOGEN, ME_GEN, round(PID_COS_UNI,6) as PID_COS_UNI, AR_FRACCION, PID_POR_DEF, MA_CODIGO, SE_CLAVE, SPI_CLAVE, TI_CODIGO, PID_NOPARTE, 
                      CFT_TIPO, PID_DEF_TIP
FROM         dbo.VBASEINVENTARIO
GROUP BY NoPedimento, PI_CODIGO, PID_INDICED,FechaPedimento, FechaPagoPedimento, ME_CORTO, ME_GEN, AR_FRACCION, PID_POR_DEF, MA_CODIGO, SE_CLAVE, 
                      SPI_CLAVE, TI_CODIGO, PID_NOPARTE, CFT_TIPO, PID_DEF_TIP, PID_COS_UNI







GO
