SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW dbo.VINVENTARIOEXISTE_X_FECHA
with encryption as
SELECT     TOP 100 PERCENT dbo.ENTSALALM.EN_FECHA, dbo.ENTSALALMDET.END_NOPARTE, MAX(dbo.ENTSALALMDET.END_NOMBRE) AS END_NOMBRE, 
                      MAX(dbo.ENTSALALMDET.END_NAME) AS END_NAME, SUM(dbo.ENTSALALMSALDO.END_SALDOALM) AS END_SALDOALM, 
                      MEDIDA_2.ME_CORTO AS ME_ALM, dbo.ENTSALALMDET.EQ_ALM, dbo.TIPO.TI_NOMBRE, 
                      SUM(dbo.ENTSALALMSALDO.END_SALDOALM / ISNULL(dbo.ENTSALALMDET.EQ_ALM, 1)) AS END_SALDOCANT, MEDIDA_1.ME_CORTO, 
                      dbo.ENTSALALMSALDO.ALM_DESTINO, dbo.ENTSALALMDET.MA_CODIGO, dbo.ALMACEN.ALM_NOMBRE, dbo.ENTSALALMDET.TI_CODIGO, 
                      dbo.ENTSALALMDET.END_TIPOENTSAL
FROM         dbo.MEDIDA MEDIDA_2 RIGHT OUTER JOIN
                      dbo.ENTSALALMSALDO INNER JOIN
                      dbo.ENTSALALMDET ON dbo.ENTSALALMSALDO.END_INDICED = dbo.ENTSALALMDET.END_INDICED ON 
                      MEDIDA_2.ME_CODIGO = dbo.ENTSALALMDET.ME_ALM LEFT OUTER JOIN
                      dbo.MEDIDA MEDIDA_1 ON dbo.ENTSALALMDET.ME_CODIGO = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
                      dbo.TIPO ON dbo.ENTSALALMDET.TI_CODIGO = dbo.TIPO.TI_CODIGO FULL OUTER JOIN
                      dbo.ENTSALALM LEFT OUTER JOIN
                      dbo.ALMACEN ON dbo.ENTSALALM.ALM_DESTINO = dbo.ALMACEN.ALM_CODIGO ON 
                      dbo.ENTSALALMDET.EN_CODIGO = dbo.ENTSALALM.EN_CODIGO
WHERE     (dbo.ENTSALALM.ALM_DESTINO <> 0)
GROUP BY dbo.ENTSALALM.EN_FECHA, dbo.ENTSALALMDET.END_NOPARTE, dbo.ENTSALALMDET.END_NOMBRE, dbo.ENTSALALMDET.END_NAME, 
                      MEDIDA_2.ME_CORTO, MEDIDA_1.ME_CORTO, dbo.TIPO.TI_NOMBRE, dbo.ENTSALALMDET.EQ_ALM, MEDIDA_1.ME_CORTO, 
                      dbo.ENTSALALMSALDO.ALM_DESTINO, dbo.ENTSALALMDET.MA_CODIGO, dbo.ALMACEN.ALM_NOMBRE, dbo.ENTSALALMDET.TI_CODIGO, 
                      dbo.ENTSALALMDET.END_TIPOENTSAL
ORDER BY dbo.ENTSALALMDET.END_NOPARTE, dbo.ENTSALALMDET.END_NOMBRE

GO
