SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VLISTACOPIABOM
with encryption as
SELECT     dbo.ENTSALALMDET.EN_CODIGO, dbo.ENTSALALMDET.END_INDICED, dbo.ENTSALALMDET.MA_CODIGO, dbo.TempBOM_DESCALM.BST_HIJO, 
                      dbo.MAESTRO.MA_NOPARTE, dbo.MAESTRO.MA_NOMBRE, dbo.MAESTRO.MA_NAME, SUM(dbo.TempBOM_DESCALM.BST_INCORPOR) 
                      AS BST_INCORPOR, dbo.MAESTRO.TI_CODIGO, dbo.TempBOM_DESCALM.ME_CODIGO, dbo.MAESTRO.MA_GENERICO, 
                      MAX(dbo.TempBOM_DESCALM.ME_ALM) AS ME_ALM, dbo.TempBOM_DESCALM.FACTCONVALM, 
                      dbo.TempBOM_DESCALM.BST_INCORPOR * dbo.TempBOM_DESCALM.FACTCONVALM AS ENT_INCORPORGEN
FROM         dbo.MAESTRO RIGHT OUTER JOIN
                      dbo.TempBOM_DESCALM RIGHT OUTER JOIN
                      dbo.ENTSALALMDET ON dbo.TempBOM_DESCALM.END_INDICED = dbo.ENTSALALMDET.END_INDICED ON 
                      dbo.MAESTRO.MA_CODIGO = dbo.TempBOM_DESCALM.BST_HIJO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.ENTSALALMDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
WHERE     (dbo.TempBOM_DESCALM.BST_DISCH = 'S') AND (dbo.CONFIGURATIPO.CFT_TIPO = 'S' OR
                      dbo.CONFIGURATIPO.CFT_TIPO = 'P')
GROUP BY dbo.ENTSALALMDET.MA_CODIGO, dbo.TempBOM_DESCALM.BST_HIJO, dbo.TempBOM_DESCALM.FACTCONVALM, dbo.ENTSALALMDET.END_INDICED, 
                      dbo.ENTSALALMDET.EN_CODIGO, dbo.MAESTRO.MA_NOPARTE, dbo.MAESTRO.MA_NOMBRE, dbo.MAESTRO.MA_NAME, dbo.MAESTRO.TI_CODIGO, 
                      dbo.TempBOM_DESCALM.ME_CODIGO, dbo.MAESTRO.MA_GENERICO, dbo.TempBOM_DESCALM.BST_INCORPOR * dbo.TempBOM_DESCALM.FACTCONVALM
HAVING      (dbo.ENTSALALMDET.MA_CODIGO IS NOT NULL)

GO
