SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW dbo.VDATOSPEDEXPDESCxPedExp
with encryption as
SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED.KAP_INDICED_FACT, KARDESPED.KAP_INDICED_PED, 
                      KARDESPED.KAP_CANTDESC, 
	'PI_TIP_CAM'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'')<>'' then isnull(KARDESPEDPPS.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
	PEDEXPDET.PIB_INDICEB,
      factexp.pi_codigo AS  PI_CODIGOPEDEXP,
	'KAP_COS_UNI'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'')<>'' then round(isnull((KARDESPEDPPS.KAP_COSTOUNITACT / isnull(KARDESPEDPPS.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
	'PID_POR_DEF'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB='N' then 0 else PEDIMPDET.PID_POR_DEF end) end, 
	'KAP_DEF_TIP'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
	KARDESPED.KAP_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         KARDESPEDPPS RIGHT OUTER JOIN
                      KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO LEFT OUTER JOIN
                      FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED LEFT OUTER JOIN
                      FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      PEDIMP RIGHT OUTER JOIN
                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO ON 
                      KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGA LEFT OUTER JOIN
                      PEDIMP PEDEXP ON FACTEXP.PI_CODIGO = PEDEXP.PI_CODIGO
WHERE     (KARDESPED.KAP_INDICED_PED IS NOT NULL) AND 
                ((case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB='N' then 0 else PEDIMPDET.PID_POR_DEF end) end) <> 0) AND (PEDEXP.PI_ESTATUS <> 'R')
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IM', 'RE', 'IV', 'VT', 'ED', 'TS'))
	AND FACTEXPDET.FED_RETRABAJO<>'R' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO='D')
AND FACTEXP.PI_CODIGO=07503 
UNION
SELECT     PEDIMPDET.PI_CODIGO AS KAP_PED_CONST, KARDESPED.KAP_INDICED_FACT, KARDESPED.KAP_INDICED_PED, 
                      KARDESPED.KAP_CANTDESC, 
	'PI_TIP_CAM'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'')<>'' then isnull(KARDESPEDPPS.KAP_TIP_CAM,1) else isnull(PEDIMP.PI_TIP_CAM,1) end, 
	PEDEXPDET.PIB_INDICEB, FACTEXP.PI_RECTIFICA AS PI_CODIGOPEDEXP,
	'KAP_COS_UNI'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	isnull(KARDESPEDPPS.KAP_PEDIMENTO,'')<>'' then round(isnull((KARDESPEDPPS.KAP_COSTOUNITACT / isnull(KARDESPEDPPS.KAP_TIP_CAM,1)), 0),6) else round(isnull((PEDIMPDET.PID_COS_UNIADU / isnull(PEDIMP.PI_TIP_CAM,1)), 0),6) end, 
	'PID_POR_DEF'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB='N' then 0 else PEDIMPDET.PID_POR_DEF end) end,
	'KAP_DEF_TIP'=case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then KARDESPEDPPS.KAP_DEF_TIP else PEDIMPDET.PID_DEF_TIP end, 
	KARDESPED.KAP_CODIGO, FACTEXPDET.MA_CODIGO AS MA_CODIGOFED
FROM         KARDESPEDPPS RIGHT OUTER JOIN
                      KARDESPED ON KARDESPEDPPS.KAP_CODIGO = KARDESPED.KAP_CODIGO LEFT OUTER JOIN
                      FACTEXPDET ON KARDESPED.KAP_INDICED_FACT = FACTEXPDET.FED_INDICED LEFT OUTER JOIN
                      FACTEXP ON KARDESPED.KAP_FACTRANS = FACTEXP.FE_CODIGO LEFT OUTER JOIN
                      PEDIMP RIGHT OUTER JOIN
                      PEDIMPDET ON PEDIMP.PI_CODIGO = PEDIMPDET.PI_CODIGO ON 
                      KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED LEFT OUTER JOIN
                      PEDIMPDET PEDEXPDET ON PEDEXPDET.PID_INDICED = FACTEXPDET.PID_INDICEDLIGAR1 LEFT OUTER JOIN
                      PEDIMP PEDEXP ON FACTEXP.PI_RECTIFICA = PEDEXP.PI_CODIGO                   
WHERE     (KARDESPED.KAP_INDICED_PED IS NOT NULL) AND 
                ((case when (SELECT CF_CAMBIOTASASEC FROM CONFIGURACION)='S'  and
	KARDESPEDPPS.KAP_TASAFINAL<>-1 then
	KARDESPEDPPS.KAP_TASAFINAL else
	(case when PEDIMPDET.PID_PAGACONTRIB='N' then 0 else PEDIMPDET.PID_POR_DEF end) end) <> 0) AND(FACTEXP.PI_RECTIFICA <> - 1)
	AND PEDIMP.CP_CODIGO IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IM', 'RE', 'IV', 'VT', 'ED', 'TS'))
	AND FACTEXPDET.FED_RETRABAJO<>'R' AND FACTEXP.TQ_CODIGO NOT IN (SELECT TQ_CODIGO FROM CONFIGURATEMBARQUE WHERE CFQ_TIPO='D')
AND FACTEXP.PI_RECTIFICA=07503
GO
