SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW dbo.VBOM_DESCTEMP1
with encryption as
SELECT     dbo.BOM_DESCTEMP.FE_CODIGO, dbo.BOM_DESCTEMP.FED_INDICED, dbo.BOM_DESCTEMP.BST_HIJO, 
                      dbo.BOM_DESCTEMP.FED_CANT * dbo.BOM_DESCTEMP.BST_INCORPOR * ISNULL(dbo.BOM_DESCTEMP.FACTCONV, 1) AS CANTDESC, 
                      dbo.BOM_DESCTEMP.BST_TIPODESC, dbo.BOM_DESCTEMP.MA_TIP_ENS, dbo.BOM_DESCTEMP.BST_TIPOCOSTO, dbo.BOM_DESCTEMP.BST_PT, 
                      MAESTRO_2.MA_GENERICO, MAESTRO_2.MA_FAMILIAMP
FROM         dbo.BOM_DESCTEMP LEFT OUTER JOIN
                      dbo.MAESTRO MAESTRO_2 ON dbo.BOM_DESCTEMP.BST_HIJO = MAESTRO_2.MA_CODIGO
WHERE     (dbo.BOM_DESCTEMP.BST_DISCH = 'S')











GO
