SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW dbo.VPEDIMPPAGO
with encryption as
SELECT     PEDIMP.PI_CODIGO, AGENCIAPATENTE.AGT_PATENTE collate database_default + '-' + PEDIMP.PI_FOLIO collate database_default AS PEDIMENTO, CLAVEPED.CP_CLAVE, AGENCIAPATENTE.AG_CODIGO, PEDIMP.AGT_CODIGO, 'N' AS AGPD_PEDTIPO
FROM         PEDIMP LEFT OUTER JOIN
                      AGENCIAPATENTE ON PEDIMP.AGT_CODIGO = AGENCIAPATENTE.AGT_CODIGO LEFT OUTER JOIN
                      CLAVEPED ON PEDIMP.CP_CODIGO = CLAVEPED.CP_CODIGO
UNION
SELECT     PEDIMP.PI_CODIGO, AGENCIAPATENTE.AGT_PATENTE collate database_default + '-' + PEDIMP.PI_COMPLEMEN collate database_default AS PEDIMENTO, 'CT' AS CP_CLAVE, AGENCIAPATENTE.AG_CODIGO, PEDIMP.AGT_CODIGO, 'C' AS AGPD_PEDTIPO
FROM         PEDIMP LEFT OUTER JOIN
                      AGENCIAPATENTE ON PEDIMP.AGT_CODIGO = AGENCIAPATENTE.AGT_CODIGO LEFT OUTER JOIN
                      CLAVEPED ON PEDIMP.CP_CODIGO = CLAVEPED.CP_CODIGO
WHERE     (CLAVEPED.CP_CLAVE = 'J1') AND (PEDIMP.PI_COMPLEMEN IS NOT NULL AND PEDIMP.PI_COMPLEMEN <> '')




GO
