SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






















CREATE VIEW dbo.VDECANUALIMPUESTOENT
with encryption as
SELECT     SUM(dbo.VPEDIMPCONTRIBUCION.PIT_CONTRIBTOTMN) AS PIT_CONTRIBTOTMN, dbo.DECANUALNVA.DAN_CODIGO,  dbo.VPEDIMP.PI_FEC_ENT as PI_FEC_PAG, 
                      dbo.VPEDIMP.PI_CODIGO
FROM         dbo.VPEDIMPCONTRIBUCION INNER JOIN
                      dbo.VPEDIMP ON dbo.VPEDIMPCONTRIBUCION.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO INNER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO INNER JOIN
                      dbo.DECANUALNVA ON dbo.VPEDIMP.PI_FEC_ENT >= dbo.DECANUALNVA.DAN_INICIO AND 
                      dbo.VPEDIMP.PI_FEC_ENT <= dbo.DECANUALNVA.DAN_FINAL
WHERE      (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'IT' AND dbo.VPEDIMP.PI_ESTATUS <> 'R') 
                   and (dbo.VPEDIMPCONTRIBUCION.CON_CODIGO  in(select CON_CODIGO  from contribucion where con_clave='6')) 
and (dbo.VPEDIMPCONTRIBUCION.PG_CODIGO  in (SELECT PG_CODIGO  FROM TPAGO WHERE PG_CLAVEM3='0'))
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO
UNION
SELECT     SUM(dbo.VPEDIMPCONTRIBUCION.PIT_CONTRIBTOTMN) AS PIT_CONTRIBTOTMN, dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_FEC_ENT as PI_FEC_PAG, 
                      dbo.VPEDIMP.PI_CODIGO
FROM         dbo.VPEDIMPCONTRIBUCION INNER JOIN
                      dbo.VPEDIMP ON dbo.VPEDIMPCONTRIBUCION.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO INNER JOIN
                      dbo.CONFIGURACLAVEPED ON dbo.VPEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO INNER JOIN
                      dbo.DECANUALNVA ON dbo.VPEDIMP.PI_FEC_ENT >= dbo.DECANUALNVA.DAN_INICIO AND 
                      dbo.VPEDIMP.PI_FEC_ENT <= dbo.DECANUALNVA.DAN_FINAL
WHERE       (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'RE' AND dbo.VPEDIMP.CP_RECTIFICA IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED
                            WHERE      CCP_TIPO = 'IT'))  and (dbo.VPEDIMPCONTRIBUCION.CON_CODIGO  in(select CON_CODIGO  from contribucion where con_clave='6')) 
and (dbo.VPEDIMPCONTRIBUCION.PG_CODIGO  in (SELECT PG_CODIGO  FROM TPAGO WHERE PG_CLAVEM3='0'))
GROUP BY dbo.DECANUALNVA.DAN_CODIGO, dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO


























GO
