SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TREPORTEFRMS] (
		[TRE_FRMTAG]        [int] NOT NULL,
		[TRE_DESCFORMA]     [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TRE_CATALOGO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TREPORTEFRMS]
	ADD
	CONSTRAINT [PK_TReporteFrms]
	PRIMARY KEY
	NONCLUSTERED
	([TRE_FRMTAG])
	ON [PRIMARY]
GO
