SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXPORTSPECPRM] (
		[EMS_CODIGO]             [int] NOT NULL,
		[PXM_CODIGO]             [int] NOT NULL,
		[PXM_ORDEN]              [int] NOT NULL,
		[IMF_CODIGO]             [int] NOT NULL,
		[PXM_LABELPARAMETRO]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXM_OPERADOR]           [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXM_DISPLAYFIELDS]      [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PXM_TIPOPARAM]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PXCM_VALOR]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXPORTSPECPRM]
	ADD
	CONSTRAINT [PK_PlntExpCnxPrm]
	PRIMARY KEY
	CLUSTERED
	([EMS_CODIGO], [PXM_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXPORTSPECPRM]
	ADD
	CONSTRAINT [DF_EXPORTSPECPRM_IMF_CODIGO]
	DEFAULT (0) FOR [IMF_CODIGO]
GO
ALTER TABLE [dbo].[EXPORTSPECPRM]
	ADD
	CONSTRAINT [DF_EXPORTSPECPRM_PXM_OPERADOR]
	DEFAULT ('=') FOR [PXM_OPERADOR]
GO
ALTER TABLE [dbo].[EXPORTSPECPRM]
	ADD
	CONSTRAINT [DF_EXPORTSPECPRM_PXM_ORDEN]
	DEFAULT (0) FOR [PXM_ORDEN]
GO
ALTER TABLE [dbo].[EXPORTSPECPRM]
	ADD
	CONSTRAINT [DF_EXPORTSPECPRM_PXM_TIPOPARAM]
	DEFAULT ('U') FOR [PXM_TIPOPARAM]
GO
