SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROGTARPROC] (
		[PRO_CODIGO]            [int] NOT NULL,
		[PTA_CODIGO]            [int] NOT NULL,
		[PRO_NOMBRE]            [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRO_COMANDO]           [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRO_PARAMS]            [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PRO_ARCHIVO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRO_NOMBREARCHIVO]     [varchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMG_CODIGO]            [int] NOT NULL,
		CONSTRAINT [IX_PROGTARPROC]
		UNIQUE
		NONCLUSTERED
		([PRO_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROGTARPROC]
	ADD
	CONSTRAINT [PK_PROGTARPROC]
	PRIMARY KEY
	CLUSTERED
	([PTA_CODIGO], [PRO_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROGTARPROC]
	ADD
	CONSTRAINT [DF_PROGTARPROC_IMG_CODIGO]
	DEFAULT (0) FOR [IMG_CODIGO]
GO
ALTER TABLE [dbo].[PROGTARPROC]
	ADD
	CONSTRAINT [DF_PROGTARPROC_PRO_ARCHIVO]
	DEFAULT ('N') FOR [PRO_ARCHIVO]
GO
ALTER TABLE [dbo].[PROGTARPROC]
	ADD
	CONSTRAINT [DF_PROGTARPROC_PRO_COMANDO]
	DEFAULT ('') FOR [PRO_COMANDO]
GO
