SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[RELTCOMPRATIPO] (
		[TR_CODIGO]     [int] NOT NULL,
		[TI_CODIGO]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RELTCOMPRATIPO]
	ADD
	CONSTRAINT [PK_RELTCOMPRATIPO]
	PRIMARY KEY
	NONCLUSTERED
	([TR_CODIGO], [TI_CODIGO])
	ON [PRIMARY]
GO
