SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COTIZACIONAVISO] (
		[COT_CODIGO]            [int] NOT NULL,
		[COTA_INDICED]          [int] NOT NULL,
		[COTA_FECHALLAMADA]     [datetime] NULL,
		[COTA_CONTACTO]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[COTA_VOLVERLLAMAR]     [datetime] NULL,
		[COTA_COMENTARIOS]      [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COTIZACIONAVISO]
	ADD
	CONSTRAINT [PK_COTIZACIONAVISO]
	PRIMARY KEY
	NONCLUSTERED
	([COTA_INDICED])
	ON [PRIMARY]
GO
