SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONTROLCAMION] (
		[RC_CODIGO]      [int] NOT NULL,
		[CJ_CODIGO]      [int] NOT NULL,
		[CT_CODIGO]      [int] NOT NULL,
		[EC_ENTRADA]     [int] NOT NULL,
		[RC_FECHA_E]     [datetime] NULL,
		[SC_SALIDA]      [int] NOT NULL,
		[RC_FECHA_S]     [datetime] NULL,
		[RC_ESTATUS]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RC_COMENTA]     [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
