SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FCC] (
		[FCC_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[FCC_CLAVE]      [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FCC_NAME]       [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FCC_DESC]       [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_FCC]
		UNIQUE
		NONCLUSTERED
		([FCC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FCC]
	ADD
	CONSTRAINT [PK_FCC]
	PRIMARY KEY
	NONCLUSTERED
	([FCC_CLAVE])
	ON [PRIMARY]
GO
