SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COMMINVDET] (
		[FED_INDICED]       [int] NOT NULL,
		[IV_CODIGO]         [int] NOT NULL,
		[IVD_GRAV_UNI]      [decimal](38, 6) NULL,
		[IVD_NG_UNI]        [decimal](38, 6) NULL,
		[IVD_PRECIO]        [decimal](38, 6) NOT NULL,
		[IVD_OBSERVA]       [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IVD_COS_TOT]       [decimal](38, 6) NOT NULL,
		[IVD_CANT]          [decimal](38, 6) NOT NULL,
		[PA_CODIGO]         [int] NULL,
		[AR_IMPFO]          [int] NULL,
		[IVD_RATEIMPFO]     [decimal](38, 6) NOT NULL,
		[TI_CODIGO]         [int] NULL,
		[MA_CODIGO]         [int] NULL,
		[IVD_NOPARTE]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[EQ_IMPFO]          [decimal](28, 14) NULL,
		[IVD_NOPARTECL]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMMINVDET]
	ADD
	CONSTRAINT [PK_COMMINVDET_IND]
	PRIMARY KEY
	NONCLUSTERED
	([FED_INDICED], [IV_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMMINVDET]
	ADD
	CONSTRAINT [DF_COMMINVDET_EQ_IMPFO]
	DEFAULT (0) FOR [EQ_IMPFO]
GO
ALTER TABLE [dbo].[COMMINVDET]
	ADD
	CONSTRAINT [DF_COMMINVDET_IVD_CANT]
	DEFAULT (0) FOR [IVD_CANT]
GO
ALTER TABLE [dbo].[COMMINVDET]
	ADD
	CONSTRAINT [DF_COMMINVDET_IVD_COS_TOT]
	DEFAULT (0) FOR [IVD_COS_TOT]
GO
ALTER TABLE [dbo].[COMMINVDET]
	ADD
	CONSTRAINT [DF_COMMINVDET_IVD_PRECIO]
	DEFAULT (0) FOR [IVD_PRECIO]
GO
ALTER TABLE [dbo].[COMMINVDET]
	ADD
	CONSTRAINT [DF_COMMINVDET_IVD_RATEIMPFO]
	DEFAULT (0) FOR [IVD_RATEIMPFO]
GO
