SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IDENTIFICADET] (
		[IDED_CODIGO]       [int] NOT NULL,
		[IDE_CODIGO]        [int] NOT NULL,
		[IDED_COMPL]        [smallint] NOT NULL,
		[IDED_DESC]         [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDED_VALOR]        [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_APLICA]       [varchar](2100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_OBSOLETO]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IDENTIFICADET]
	ADD
	CONSTRAINT [PK_IDENTIFICADET]
	PRIMARY KEY
	NONCLUSTERED
	([IDED_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[IDENTIFICADET]
	ADD
	CONSTRAINT [DF_IDENTIFICADET_IDED_COMPL]
	DEFAULT (1) FOR [IDED_COMPL]
GO
ALTER TABLE [dbo].[IDENTIFICADET]
	ADD
	CONSTRAINT [DF_IDENTIFICADET_IDED_DESC]
	DEFAULT ('') FOR [IDED_DESC]
GO
ALTER TABLE [dbo].[IDENTIFICADET]
	ADD
	CONSTRAINT [DF_IDENTIFICADET_IDED_OBSOLETO]
	DEFAULT ('N') FOR [IDED_OBSOLETO]
GO
