SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REGLAORIGENMP] (
		[ARG_CODIGO]         [int] NOT NULL,
		[ARM_PARTIDAMP]      [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ARM_PARTIDAMPF]     [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REGLAORIGENMP]
	ADD
	CONSTRAINT [PK_REGLAORIGENMP]
	PRIMARY KEY
	NONCLUSTERED
	([ARG_CODIGO], [ARM_PARTIDAMP])
	ON [PRIMARY]
GO
