SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPEXCELENTRY] (
		[ET_ENTRY_NO]      [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ET_FEC_ENTRY]     [datetime] NULL,
		[FOLIOFACT]        [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
