SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPORTLOG] (
		[IML_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[IML_MENSAJE]        [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IML_CBFORMA]        [int] NULL,
		[IML_REFERENCIA]     [int] NULL,
		CONSTRAINT [IX_IMPORTLOG]
		UNIQUE
		NONCLUSTERED
		([IML_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTLOG]
	ADD
	CONSTRAINT [DF_IMPORTLOG_IML_CBFORMA]
	DEFAULT (0) FOR [IML_CBFORMA]
GO
