SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TPAGO] (
		[PG_CODIGO]      [smallint] IDENTITY(1, 1) NOT NULL,
		[PG_CLAVE]       [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PG_DESC]        [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PG_NAME]        [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PG_LIMITE]      [decimal](38, 6) NULL,
		[MO_CODIGO]      [int] NULL,
		[PG_CLAVEM3]     [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_TPAGO]
		UNIQUE
		NONCLUSTERED
		([PG_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPAGO]
	ADD
	CONSTRAINT [PK_TPAGO]
	PRIMARY KEY
	NONCLUSTERED
	([PG_CLAVE], [PG_CLAVEM3])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TPAGO]
	ADD
	CONSTRAINT [DF_TPAGO_PG_NAME]
	DEFAULT ('') FOR [PG_NAME]
GO
