SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BARCODE] (
		[BC_CODIGO]         [int] NOT NULL,
		[BC_NOMBRE]         [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BC_TEXTO]          [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BC_DOCTO]          [int] NOT NULL,
		[BC_TIPO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BC_BARCODE]        [image] NULL,
		[BC_TIPOMOV]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BC_AGRUPACION]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[BARCODE]
	ADD
	CONSTRAINT [PK_BARCODE]
	PRIMARY KEY
	CLUSTERED
	([BC_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[BARCODE]
	ADD
	CONSTRAINT [DF_BARCODE_BC_AGRUPACION]
	DEFAULT ('I') FOR [BC_AGRUPACION]
GO
ALTER TABLE [dbo].[BARCODE]
	ADD
	CONSTRAINT [DF_BARCODE_BC_DOCTO]
	DEFAULT (0) FOR [BC_DOCTO]
GO
ALTER TABLE [dbo].[BARCODE]
	ADD
	CONSTRAINT [DF_BARCODE_BC_TIPO]
	DEFAULT ('F') FOR [BC_TIPO]
GO
