SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TERMINO] (
		[TE_CODIGO]       [smallint] IDENTITY(1, 1) NOT NULL,
		[TE_CORTO]        [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TE_NOMBRE]       [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TE_NAME]         [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TE_DESC]         [decimal](38, 6) NULL,
		[TE_DIASNETO]     [int] NULL,
		CONSTRAINT [IX_TERMINO]
		UNIQUE
		NONCLUSTERED
		([TE_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TERMINO]
	ADD
	CONSTRAINT [PK_TERMINO]
	PRIMARY KEY
	NONCLUSTERED
	([TE_CORTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TERMINO]
	ADD
	CONSTRAINT [DF_TERMINO_TE_NAME]
	DEFAULT ('') FOR [TE_NAME]
GO
