SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TENVIO] (
		[TN_CODIGO]      [smallint] IDENTITY(1, 1) NOT NULL,
		[TN_DESCRIP]     [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TN_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_TENVIO]
		UNIQUE
		NONCLUSTERED
		([TN_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TENVIO]
	ADD
	CONSTRAINT [PK_TENVIO]
	PRIMARY KEY
	NONCLUSTERED
	([TN_DESCRIP])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TENVIO]
	ADD
	CONSTRAINT [DF_TENVIO_TN_DESCRIP]
	DEFAULT ('') FOR [TN_DESCRIP]
GO
ALTER TABLE [dbo].[TENVIO]
	ADD
	CONSTRAINT [DF_TENVIO_TN_TIPO]
	DEFAULT ('A') FOR [TN_TIPO]
GO
