SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MEDIDAMRP] (
		[ME_INTRADE]       [int] NOT NULL,
		[ME_TEXTOMRP]      [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_NOMBRESYS]     [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDIDAMRP]
	ADD
	CONSTRAINT [PK_MEDIDAMRP]
	PRIMARY KEY
	CLUSTERED
	([ME_TEXTOMRP])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDIDAMRP]
	ADD
	CONSTRAINT [DF_MEDIDAMRP_ME_NOMBRESYS]
	DEFAULT ('') FOR [ME_NOMBRESYS]
GO
