SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[CONFIGURATIEMPO] (
		[CP_CODIGO]            [smallint] NOT NULL,
		[TI_CODIGO]            [smallint] NOT NULL,
		[COT_TIEMPO]           [int] NOT NULL,
		[COT_FECHAINICIAL]     [datetime] NOT NULL,
		[COT_FECHAFINAL]       [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURATIEMPO]
	ADD
	CONSTRAINT [PK_CONFIGURATIEMPO]
	PRIMARY KEY
	NONCLUSTERED
	([CP_CODIGO], [TI_CODIGO], [COT_FECHAINICIAL])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURATIEMPO]
	ADD
	CONSTRAINT [DF_CONFIGURATIEMPO_COT_FECHAFINAL]
	DEFAULT ('9999-01-01') FOR [COT_FECHAFINAL]
GO
ALTER TABLE [dbo].[CONFIGURATIEMPO]
	ADD
	CONSTRAINT [DF_CONFIGURATIEMPO_COT_FECHAINICIAL]
	DEFAULT ('1999-01-01') FOR [COT_FECHAINICIAL]
GO
