SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ALMACENDESP] (
		[AM_CODIGO]           [int] NOT NULL,
		[ADE_CODIGO]          [int] IDENTITY(1, 1) NOT NULL,
		[FETR_CODIGO]         [int] NOT NULL,
		[FETR_INDICED]        [int] NOT NULL,
		[FETR_TIPO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TIPO_ENT_SAL]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PI_CODIGO]           [int] NOT NULL,
		[PID_INDICED]         [int] NOT NULL,
		[MA_PADRE]            [int] NULL,
		[MA_PERTENECE]        [int] NULL,
		[MA_HIJO]             [int] NOT NULL,
		[TI_CODIGO]           [smallint] NOT NULL,
		[ADE_CANT]            [decimal](38, 6) NOT NULL,
		[ME_CODIGO]           [int] NULL,
		[ADE_CANTKG]          [decimal](38, 6) NULL,
		[ADE_PESO_UNIKG]      [decimal](38, 6) NOT NULL,
		[ADE_SALDO]           [decimal](38, 6) NOT NULL,
		[ADE_ENUSO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ADE_GENERADOPOR]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_GENERA_EMP]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EQ_GENERICO]         [decimal](28, 14) NOT NULL,
		[MA_GENERICO]         [int] NULL,
		[ADE_FECHA]           [datetime] NULL,
		CONSTRAINT [IX_ALMACENDESP]
		UNIQUE
		NONCLUSTERED
		([ADE_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [PK_ALMACENDESP]
	PRIMARY KEY
	NONCLUSTERED
	([AM_CODIGO], [FETR_INDICED], [TIPO_ENT_SAL], [PID_INDICED], [MA_HIJO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_ADE_CANT]
	DEFAULT (0) FOR [ADE_CANT]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_ADE_ENUSO]
	DEFAULT ('N') FOR [ADE_ENUSO]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_ADE_GENERADOPOR]
	DEFAULT ('C') FOR [ADE_GENERADOPOR]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_ADE_PESO_UNIKG]
	DEFAULT (0) FOR [ADE_PESO_UNIKG]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_ADE_SALDO]
	DEFAULT (0) FOR [ADE_SALDO]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_AM_CODIGO]
	DEFAULT (0) FOR [AM_CODIGO]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_EQ_GENERICO]
	DEFAULT (1) FOR [EQ_GENERICO]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_FETR_CODIGO]
	DEFAULT (0) FOR [FETR_CODIGO]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_FETR_INDICED]
	DEFAULT (0) FOR [FETR_INDICED]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_FETR_TIPO]
	DEFAULT ('F') FOR [FETR_TIPO]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_MA_GENERA_EMP]
	DEFAULT ('D') FOR [MA_GENERA_EMP]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_PI_CODIGO]
	DEFAULT (0) FOR [PI_CODIGO]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_PID_INDICED]
	DEFAULT (0) FOR [PID_INDICED]
GO
ALTER TABLE [dbo].[ALMACENDESP]
	ADD
	CONSTRAINT [DF_ALMACENDESP_TIPO_ENT_SAL]
	DEFAULT ('S') FOR [TIPO_ENT_SAL]
GO
