SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROCESO] (
		[PRC_CODIGO]     [int] IDENTITY(1, 1) NOT NULL,
		[PRC_CORTO]      [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRC_NOMBRE]     [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_PROCESO]
		UNIQUE
		NONCLUSTERED
		([PRC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROCESO]
	ADD
	CONSTRAINT [PK_PROCESO]
	PRIMARY KEY
	NONCLUSTERED
	([PRC_CORTO])
	ON [PRIMARY]
GO
