SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTROCOST] (
		[MAC_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[TCO_CODIGO]        [smallint] NOT NULL,
		[MA_CODIGO]         [int] NOT NULL,
		[MA_GRAV_MP]        [decimal](38, 6) NOT NULL,
		[MA_GRAV_ADD]       [decimal](38, 6) NOT NULL,
		[MA_GRAV_EMP]       [decimal](38, 6) NOT NULL,
		[MA_GRAV_GI]        [decimal](38, 6) NOT NULL,
		[MA_GRAV_GI_MX]     [decimal](38, 6) NOT NULL,
		[MA_GRAV_MO]        [decimal](38, 6) NOT NULL,
		[MA_NG_MP]          [decimal](38, 6) NOT NULL,
		[MA_NG_ADD]         [decimal](38, 6) NOT NULL,
		[MA_NG_EMP]         [decimal](38, 6) NOT NULL,
		[MA_COSTO]          [decimal](38, 6) NOT NULL,
		[MA_GRAVA_VA]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_NG_USA]         [decimal](38, 6) NOT NULL,
		[TV_CODIGO]         [int] NOT NULL,
		[DV_CODIGO]         [smallint] NULL,
		[SPI_CODIGO]        [int] NOT NULL,
		[MA_PERINI]         [datetime] NOT NULL,
		[MA_PERFIN]         [datetime] NOT NULL,
		[MA_NG_MX]          [decimal](38, 6) NOT NULL,
		CONSTRAINT [IX_MAESTROCOST]
		UNIQUE
		NONCLUSTERED
		([MAC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [PK_MAESTROCOST]
	PRIMARY KEY
	NONCLUSTERED
	([TCO_CODIGO], [MA_CODIGO], [SPI_CODIGO], [MA_PERINI])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_COSTO]
	DEFAULT (0) FOR [MA_COSTO]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_GRAV_ADD]
	DEFAULT (0) FOR [MA_GRAV_ADD]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_GRAV_EMP]
	DEFAULT (0) FOR [MA_GRAV_EMP]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_GRAV_GI]
	DEFAULT (0) FOR [MA_GRAV_GI]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_GRAV_GI_MX]
	DEFAULT (0) FOR [MA_GRAV_GI_MX]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_GRAV_MO]
	DEFAULT (0) FOR [MA_GRAV_MO]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_GRAV_MP]
	DEFAULT (0) FOR [MA_GRAV_MP]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_GRAVA_VA]
	DEFAULT ('S') FOR [MA_GRAVA_VA]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_NG_ADD]
	DEFAULT (0) FOR [MA_NG_ADD]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_NG_EMP]
	DEFAULT (0) FOR [MA_NG_EMP]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_NG_MP]
	DEFAULT (0) FOR [MA_NG_MP]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_NG_MX]
	DEFAULT (0) FOR [MA_NG_MX]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_NG_USA]
	DEFAULT (0) FOR [MA_NG_USA]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_PERFIN]
	DEFAULT ('01/01/9999') FOR [MA_PERFIN]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_MA_PERINI]
	DEFAULT ('01/01/1999') FOR [MA_PERINI]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_SPI_CODIGO]
	DEFAULT (22) FOR [SPI_CODIGO]
GO
ALTER TABLE [dbo].[MAESTROCOST]
	ADD
	CONSTRAINT [DF_MAESTROCOST_TV_CODIGO]
	DEFAULT (2) FOR [TV_CODIGO]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTROCOST_1]
	ON [dbo].[MAESTROCOST] ([MA_PERINI], [MA_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTROCOST_2]
	ON [dbo].[MAESTROCOST] ([TCO_CODIGO], [SPI_CODIGO], [MA_PERINI], [MAC_CODIGO], [MA_CODIGO])
	ON [PRIMARY]
GO
