SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[FACTIMPINCREMENTA] (
		[FI_CODIGO]     [int] NOT NULL,
		[IC_CODIGO]     [smallint] NOT NULL,
		[FII_VALOR]     [decimal](38, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPINCREMENTA]
	ADD
	CONSTRAINT [PK_FACTIMPINCREMENTA]
	PRIMARY KEY
	CLUSTERED
	([FI_CODIGO], [IC_CODIGO])
	ON [PRIMARY]
GO
