SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[VERSIONINFO] (
		[VERSIONNO]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA]         [datetime] NOT NULL,
		[FECHAACT]      [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VERSIONINFO]
	ADD
	CONSTRAINT [PK_VERSIONINFO]
	PRIMARY KEY
	NONCLUSTERED
	([VERSIONNO], [FECHA])
	ON [PRIMARY]
GO
