SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTURAPDF417] (
		[FACB_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[FACB_CODIGOFACT]     [int] NOT NULL,
		[FACB_MOVIMIENTO]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FACB_BARCODE]        [image] NULL,
		[FACB_TEXTO]          [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_FACTURAPDF417]
		UNIQUE
		NONCLUSTERED
		([FACB_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTURAPDF417]
	ADD
	CONSTRAINT [PK_FACTURAPDF417]
	PRIMARY KEY
	CLUSTERED
	([FACB_CODIGOFACT], [FACB_MOVIMIENTO], [FACB_TEXTO])
	ON [PRIMARY]
GO
