SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPORTTEMPBOM] (
		[CONSECUTIVO]        [int] IDENTITY(1, 1) NOT NULL,
		[BST_INCORPOR]       [decimal](38, 6) NOT NULL,
		[BST_DISCH]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_CODIGO]          [int] NULL,
		[FACTCONV]           [decimal](28, 14) NULL,
		[BST_PERINI]         [datetime] NULL,
		[BST_PERFIN]         [datetime] NULL,
		[ME_GEN]             [int] NULL,
		[BST_TRANS]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BSU_NOPARTE]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BST_NOPARTE]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BST_PERCAMBIO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BSU_NOPARTEAUX]     [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BST_NOPARTEAUX]     [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BST_TIP_ENS]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BST_SEC]            [smallint] NOT NULL,
		CONSTRAINT [IX_IMPORTTEMPBOM_1]
		UNIQUE
		NONCLUSTERED
		([CONSECUTIVO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_ImportTempBOM_BST_DISCH]
	DEFAULT ('S') FOR [BST_DISCH]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_ImportTempBOM_BST_INCORPOR]
	DEFAULT ((1)) FOR [BST_INCORPOR]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_ImportTempBOM_BST_NOPARTEAUX]
	DEFAULT ('') FOR [BST_NOPARTEAUX]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_ImportTempBOM_BST_PERCAMBIOS]
	DEFAULT ('N') FOR [BST_PERCAMBIO]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_IMPORTTEMPBOM_BST_PERFIN]
	DEFAULT ('1/1/9999') FOR [BST_PERFIN]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_IMPORTTEMPBOM_BST_PERINI]
	DEFAULT ('1/1/1999') FOR [BST_PERINI]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_ImportTempBOM_BST_SEC]
	DEFAULT ((-1)) FOR [BST_SEC]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_ImportTempBOM_BST_TRANS]
	DEFAULT ('N') FOR [BST_TRANS]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_ImportTempBOM_BSU_NOPARTEAUX]
	DEFAULT ('') FOR [BSU_NOPARTEAUX]
GO
ALTER TABLE [dbo].[IMPORTTEMPBOM]
	ADD
	CONSTRAINT [DF_ImportTempBOM_FACTCONV]
	DEFAULT ((1)) FOR [FACTCONV]
GO
CREATE CLUSTERED INDEX [IX_IMPORTTEMPBOM]
	ON [dbo].[IMPORTTEMPBOM] ([BSU_NOPARTE], [BST_NOPARTE], [BST_PERINI], [BST_PERFIN], [BST_SEC])
	ON [PRIMARY]
GO
