SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIDODETENTPARCIAL] (
		[PDDP_INDICEP]     [int] NOT NULL,
		[PDD_INDICED]      [int] NOT NULL,
		[PDDP_FECHA]       [datetime] NOT NULL,
		[PDDP_CANT]        [decimal](38, 6) NOT NULL,
		[PDDP_OBSERVA]     [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
