SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[REPEXPUSACA] (
		[RUC_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[RUC_FOLIO]          [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RUC_LUGAREXP]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RUC_FECHA]          [datetime] NOT NULL,
		[CL_EMISOR]          [int] NULL,
		[DIR_EMISOR]         [int] NULL,
		[RUC_SEMESTRE]       [smallint] NOT NULL,
		[CL_TRANSFIERE]      [int] NULL,
		[DIR_TRANSFIERE]     [int] NULL,
		[RUC_PERINI]         [datetime] NOT NULL,
		[RUC_PERFIN]         [datetime] NOT NULL,
		CONSTRAINT [IX_REPEXPUSACA]
		UNIQUE
		NONCLUSTERED
		([RUC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[REPEXPUSACA]
	ADD
	CONSTRAINT [PK_REPEXPUSACA]
	PRIMARY KEY
	NONCLUSTERED
	([RUC_FOLIO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[REPEXPUSACA]
	ADD
	CONSTRAINT [DF_REPEXPUSACA_RUC_SEMESTRE]
	DEFAULT (1) FOR [RUC_SEMESTRE]
GO
