SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PUESTO] (
		[PO_CODIGO]     [int] IDENTITY(1, 1) NOT NULL,
		[PO_NOMBRE]     [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PO_NAME]       [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_PUESTO]
		UNIQUE
		NONCLUSTERED
		([PO_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PUESTO]
	ADD
	CONSTRAINT [PK_PUESTO]
	PRIMARY KEY
	NONCLUSTERED
	([PO_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PUESTO]
	ADD
	CONSTRAINT [DF_PUESTO_PO_NAME]
	DEFAULT ('') FOR [PO_NAME]
GO
