SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BUSQUEDAFILTRO] (
		[BFI_CODIGO]       [int] NOT NULL,
		[BUS_CODIGO]       [int] NOT NULL,
		[BFI_CAMPO1]       [int] NOT NULL,
		[BFI_CAMPO2]       [int] NOT NULL,
		[BFI_OPERADOR]     [int] NOT NULL,
		[BFI_IGUAL]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BFI_MIN]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BFI_MAX]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BFI_NULL]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_BUSQUEDAFILTRO]
		UNIQUE
		NONCLUSTERED
		([BFI_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUSQUEDAFILTRO]
	ADD
	CONSTRAINT [PK_BUSQUEDAFILTRO]
	PRIMARY KEY
	NONCLUSTERED
	([BFI_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUSQUEDAFILTRO]
	ADD
	CONSTRAINT [DF_BUSQUEDAFILTRO_BFI_CAMPO2]
	DEFAULT (0) FOR [BFI_CAMPO2]
GO
ALTER TABLE [dbo].[BUSQUEDAFILTRO]
	ADD
	CONSTRAINT [DF_BUSQUEDAFILTRO_BFI_NULL]
	DEFAULT ('N') FOR [BFI_NULL]
GO
