SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENCIAPATENTE] (
		[AGT_CODIGO]             [int] NOT NULL,
		[AG_CODIGO]              [smallint] NOT NULL,
		[AGT_PATENTE]            [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AGT_NOMBRE]             [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AGT_RFC]                [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGT_CURP]               [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGT_DEFAULT]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AGT_ARCHIVOKEY]         [varchar](1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGT_ARCHIVOCER]         [varchar](1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGT_PASSWORDKEY]        [varchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGT_TIPO]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AGT_NOSERIECERTFEA]     [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_AGENCIAPATENTE]
		UNIQUE
		NONCLUSTERED
		([AGT_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIAPATENTE]
	ADD
	CONSTRAINT [PK_AGENCIAPATENTE]
	PRIMARY KEY
	NONCLUSTERED
	([AG_CODIGO], [AGT_PATENTE], [AGT_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIAPATENTE]
	ADD
	CONSTRAINT [DF_AGENCIAPATENTE_AGT_DEFAULT]
	DEFAULT ('N') FOR [AGT_DEFAULT]
GO
ALTER TABLE [dbo].[AGENCIAPATENTE]
	ADD
	CONSTRAINT [DF_AGENCIAPATENTE_AGT_RFC]
	DEFAULT ('') FOR [AGT_RFC]
GO
ALTER TABLE [dbo].[AGENCIAPATENTE]
	ADD
	CONSTRAINT [DF_AGENCIAPATENTE_AGT_TIPO]
	DEFAULT ('A') FOR [AGT_TIPO]
GO
