SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ERRORREGDESC] (
		[ERR_TIPOREGISTRO]     [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERR_REGDESC]          [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ERRORREGDESC]
	ADD
	CONSTRAINT [PK_ERRORREGDESC]
	PRIMARY KEY
	NONCLUSTERED
	([ERR_TIPOREGISTRO])
	ON [PRIMARY]
GO
