SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURATIPO] (
		[TI_CODIGO]       [smallint] NOT NULL,
		[CFT_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFT_COSTSUB]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURATIPO]
	ADD
	CONSTRAINT [PK_CONFIGURATIPO]
	PRIMARY KEY
	NONCLUSTERED
	([TI_CODIGO])
	ON [PRIMARY]
GO
