SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DTS] (
		[DTS_TAG]             [int] NOT NULL,
		[DTS_NOMBREDTS]       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DTS_PROCEDPOST]      [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DTS_PROCEDANT]       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DTS_FILENAME]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DTS_DESCRIPCION]     [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DTS_ENUSO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DTS_ESEXE]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DTS_TITULOS]         [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DTS_TAGIMPLOG]       [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DTS]
	ADD
	CONSTRAINT [PK_DTS]
	PRIMARY KEY
	CLUSTERED
	([DTS_TAG], [DTS_NOMBREDTS], [DTS_PROCEDPOST])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[DTS]
	ADD
	CONSTRAINT [DF_DTS_DTS_ENUSO]
	DEFAULT ('N') FOR [DTS_ENUSO]
GO
ALTER TABLE [dbo].[DTS]
	ADD
	CONSTRAINT [DF_DTS_DTS_ESEXE]
	DEFAULT ('N') FOR [DTS_ESEXE]
GO
ALTER TABLE [dbo].[DTS]
	ADD
	CONSTRAINT [DF_DTS_DTS_PROCEDPOST]
	DEFAULT ('') FOR [DTS_PROCEDPOST]
GO
ALTER TABLE [dbo].[DTS]
	ADD
	CONSTRAINT [DF_DTS_DTS_TAGIMPLOG]
	DEFAULT (0) FOR [DTS_TAGIMPLOG]
GO
