SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[A16] (
		[A16_CODIGO]          [int] NOT NULL,
		[A16_FOLIO]           [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[A16_FECHAINI]        [datetime] NOT NULL,
		[A16_FECHAFIN]        [datetime] NOT NULL,
		[MA_FAMILIA]          [int] NOT NULL,
		[A16_TOTALEXP]        [decimal](38, 6) NULL,
		[A16_TOTALVENTAS]     [decimal](38, 6) NULL,
		[A16_PROPORCION]      [decimal](38, 6) NULL,
		[CL_EMPRESA]          [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[A16]
	ADD
	CONSTRAINT [PK_A16]
	PRIMARY KEY
	NONCLUSTERED
	([A16_FECHAINI], [A16_FECHAFIN], [MA_FAMILIA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[A16]
	ADD
	CONSTRAINT [DF_A16_CL_EMPRESA]
	DEFAULT (1) FOR [CL_EMPRESA]
GO
