SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPIDENTIFICA] (
		[FEI_CODIGO]       [int] NOT NULL,
		[FE_CODIGO]        [int] NOT NULL,
		[IDE_CODIGO]       [int] NOT NULL,
		[IDED_CODIGO]      [int] NULL,
		[FEI_DESC]         [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FEI_DESC2]        [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_CODIGO2]     [int] NULL,
		[FEI_DESC3]        [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_CODIGO3]     [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPIDENTIFICA]
	ADD
	CONSTRAINT [PK_FACTEXPIDENTIFICA]
	PRIMARY KEY
	CLUSTERED
	([FE_CODIGO], [IDE_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPIDENTIFICA]
	ADD
	CONSTRAINT [DF_FACTEXPIDENTIFICA_FEI_DESC]
	DEFAULT ('') FOR [FEI_DESC]
GO
