SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[A17DET] (
		[A17D_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[A17_CODIGO]          [int] NOT NULL,
		[MA_GENERICO]         [int] NOT NULL,
		[CL_CODIGO]           [int] NOT NULL,
		[PI_CODIGO]           [int] NOT NULL,
		[A17D_VALORTRANS]     [decimal](38, 6) NOT NULL,
		[A17D_VALORADQ0]      [decimal](38, 6) NOT NULL,
		[A17D_PROPORCION]     [decimal](38, 6) NULL,
		CONSTRAINT [IX_A17DET]
		UNIQUE
		NONCLUSTERED
		([A17D_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
