SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPEXCELRELFACTAGRU] (
		[FOLIOFACTAGRU]     [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FOLIOFACT]         [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
