SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[MAESTROGENPT] (
		[MA_GENHIJO]     [int] NOT NULL,
		[MA_FAMPT]       [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROGENPT]
	ADD
	CONSTRAINT [PK_MAESTROGENPT]
	PRIMARY KEY
	NONCLUSTERED
	([MA_GENHIJO], [MA_FAMPT])
	ON [PRIMARY]
GO
