SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[KARDESDESV] (
		[KAD_CODIGO]       [int] IDENTITY(1, 1) NOT NULL,
		[FE_CODIGO]        [int] NOT NULL,
		[DEV_CODIGO]       [int] NOT NULL,
		[KAD_CANTIDAD]     [decimal](38, 20) NOT NULL,
		CONSTRAINT [IX_KARDESDESV]
		UNIQUE
		CLUSTERED
		([KAD_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
