SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PREVALIDADOR] (
		[PRE_CODIGO]                [int] IDENTITY(1, 1) NOT NULL,
		[PRE_CLAVE]                 [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRE_NOMBRE]                [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRE_CLAVECONTRIBUCION]     [smallint] NULL,
		[PRE_CUOTAFIJA]             [decimal](38, 6) NULL,
		CONSTRAINT [IX_PREVALIDADOR]
		UNIQUE
		NONCLUSTERED
		([PRE_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PREVALIDADOR]
	ADD
	CONSTRAINT [PK_PREVALIDADOR]
	PRIMARY KEY
	NONCLUSTERED
	([PRE_CLAVE])
	ON [PRIMARY]
GO
