SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TIPS] (
		[TIP_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[TIP_TEMA]           [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TIP_INFO]           [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TIP_FECHA]          [datetime] NULL,
		[TIP_VERSIONEXE]     [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_TIPS]
		UNIQUE
		NONCLUSTERED
		([TIP_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
