SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[OMISIONRELFACTPED] (
		[CP_CODIGO]      [smallint] NULL,
		[TQ_CODIGO]      [smallint] NULL,
		[TF_CODIGO]      [smallint] NULL,
		[OFP_TIPOFC]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
