SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TFACTURA] (
		[TF_CODIGO]      [smallint] IDENTITY(1, 1) NOT NULL,
		[TF_NOMBRE]      [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TF_NAME]        [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TF_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LDE_CODIGO]     [smallint] NULL,
		CONSTRAINT [IX_TFACTURA]
		UNIQUE
		NONCLUSTERED
		([TF_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TFACTURA]
	ADD
	CONSTRAINT [PK_TFACTURA]
	PRIMARY KEY
	NONCLUSTERED
	([TF_NOMBRE])
	ON [PRIMARY]
GO
