SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PlntUsedTbls] (
,
		CONSTRAINT [IX_PlntUsedTbls]
		UNIQUE
		NONCLUSTERED
		()
		ON [PRIMARY]
) ON [PRIMARY]
GO
