SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURACION] (
		[EM_CODIGO]                           [int] NOT NULL,
		[CF_DESCARGAS]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCARGASBUS]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_VAL_PED]                          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AUMENTA_VA]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_MAN_EMPAQUE]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_VEHICULOS]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CONTENEDOR]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AVISO_PAIS]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DIAS_AVISO]                       [smallint] NOT NULL,
		[CF_DIAS_AVISOTLC]                    [smallint] NOT NULL,
		[CF_AVISO_CERTTLC]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CONS_IMP]                         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CONS_EXP]                         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PESOS_IMP]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PESOS_EXP]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ARANC_PAIS]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_MPFIM_TLC]                        [decimal](38, 6) NOT NULL,
		[CF_MPFIM_NTLC]                       [decimal](38, 6) NOT NULL,
		[CF_MPFIM_MINTLC]                     [decimal](38, 6) NOT NULL,
		[CF_MPFIM_MINNTLC]                    [decimal](38, 6) NOT NULL,
		[CF_MPFIM_MAXNTLC]                    [decimal](38, 6) NOT NULL,
		[ME_DIMENSION]                        [int] NULL,
		[CF_OMISIO]                           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CTRANSP]                          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PAIS_MX]                          [int] NOT NULL,
		[CF_PAIS_USA]                         [int] NOT NULL,
		[CF_PAIS_CA]                          [int] NOT NULL,
		[CF_NO_PROVEE]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ME_PROVEE]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_KILOGRAMOS]                       [int] NOT NULL,
		[CF_EMPAQUE_BOM]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PRECIOCLIENTE]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PRECIOFACTEXP]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_GENERAENTRY]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AGRUPAENTRY]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESPERDICIO_BOM]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_VANOGRAVABLE]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAPCKLIST]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USALISTAEXP]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USACERTORIGMP]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAEQUIVALENTE]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USATIPOADQUISICION]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TIPODESCCAMBIOREG]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CLASIFICATLC]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SECTOR]                           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PERMISOAVISO]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ARGENAVISO]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DECANUALBASEPED]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCARGANDO]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DIMENSIONESMP]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AR_EMPAQUEUSA]                       [int] NULL,
		[CF_DESCEMPUSA]                       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AR_RETORNOUSA]                       [int] NULL,
		[CF_DESCRETORNOUSA]                   [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AR_RETRABAJO]                        [int] NULL,
		[CF_DESCRETRABAJO]                    [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AR_INSERTO]                          [int] NULL,
		[CF_DESCINSERTO]                      [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CF_UPDATEARCAMBIO]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AGRSENCILLA]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_NIVELES]                          [int] NOT NULL,
		[CP_ORDENCOMPRA]                      [int] NOT NULL,
		[CP_CONSTANCIAEXP]                    [int] NOT NULL,
		[CF_DESCDESPERDICIO]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_REVISATIPOTASA]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_EMPDESPIMP]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_FOLIOENT]                         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_FOLIOSAL]                         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DIGITOFOLIO]                      [smallint] NOT NULL,
		[CF_CAMBIOUM]                         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AVISODESCARGA]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_EXPLOSIONAUX]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TIPOCOSTO]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TCO_MANUFACTURA]                     [smallint] NOT NULL,
		[TCO_COMPRA]                          [smallint] NOT NULL,
		[TCO_DESPERDICIO]                     [smallint] NOT NULL,
		[TCO_RETRABAJO]                       [smallint] NOT NULL,
		[CF_ACTUALIZATIEMPO]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCARGAVENCIDOS]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CANCELADESCPEPS]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USACLASSCOSTO]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SINGENERICO]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCUPDATECOSTFE]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PAGOCONTRIBUCION]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PEDIMPDETB]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PEDIMPFACT]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_MANEJOKITS]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PAGADTAFIII]                      [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CF_PAGADTAFIV]                       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CF_SAAIDIVPA]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SAAIDIVCOSGEN]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USACONFGRID]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AVISONUMPARTE]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USADISCREPANCIA]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCMOVALM]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CONTROLDESP]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CUSTOMCLASS]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AVISOMAXMIN]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_FILTRARPARTECLI]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USACATALOGOMA]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USANOPARTECONSULTA]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SAAI_CONS]                        [int] NOT NULL,
		[CF_VALIDADOR]                        [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CF_MULTAEXCPLAZO]                    [decimal](38, 6) NOT NULL,
		[CF_PEDEXPVAUSA]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_FACTORACT]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CTRLLOCPRODUC]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TIPODESCALM]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[US_DESCARGANDO]                      [int] NULL,
		[CF_FECHATIP]                         [datetime] NULL,
		[TIP_CODIGO]                          [int] NULL,
		[CF_TURNOHRS]                         [decimal](38, 6) NULL,
		[CF_PAGOCONTRIBDET]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_REPARA]                           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SERVICIOS]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TEXTIL]                           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ORDENDETDOC]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ACTTASA]                          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ACTTASAPER8VA]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ACTTASAPERPPS]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ACTTASACERTO]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCGRCOSTO]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_EXPLOSDESCADD]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_COSTO_PROVEE]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ESTRUCTALT]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_NO_PROVEECL]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAKITS]                          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PENDGR]                           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DISABLEGEN]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PERMITESINCON]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAGENERICO]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AUTOMOTRIZ]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USACATCHOFER]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TIEMPOUSO]                        [decimal](38, 6) NOT NULL,
		[CF_USACOSTOBOM]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SAAIDETDIVFACT]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USASUBDECANUAL]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SINGENERICOUM]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SE_CODIGO]                           [int] NULL,
		[CF_SAAIDIVDESC]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PEDDESPKG]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_IVAPROPORCIONAL]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CONFERIRORIGEN]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_VALIDAPERMISOS]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AGRUPASAAISEC]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_COSTOCLIVIRT]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CF_FOLIOPED]                         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_RANGOINI]                         [int] NULL,
		[CF_RANGOFIN]                         [int] NULL,
		[CF_PEDCONSEC]                        [int] NULL,
		[CF_IMGONDB]                          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PEDSALDOINC]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USARELCAJAS]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USACARGOCOSTO]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TRANSPCONSEC]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SAAIRANGOINI]                     [int] NOT NULL,
		[CF_SAAIRANGOFIN]                     [int] NOT NULL,
		[CF_DESCARGATASA]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCARGAPAIS]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CONSECSHIPPER]                    [int] NOT NULL,
		[CFR_VERCORETORNO]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCDESPFAM]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DECANUALGEN]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CAMBIOTASASEC]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CORIGXFACT]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SICEXEXP]                         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USACONTPT]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAFIRMADIGITAL]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TIPOFIRMA]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_APLICANOMS]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USACOSTNODUTNAFTA]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TIGIESECTORPERM]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_EXPSINBOM]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SELPAISIMP]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAPEDCT]                         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_AVISOMODIFFOLIO]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TCOCOMPRAIMP]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_IMPDATUSAPERMFIINSERT]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_IMPDATUSAEQFIINSERT]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_IMPDATUSAEQFEINSERT]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_BOMBORRANOINCLUIDO]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USALOCALIDADALM]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USADESCSICEX]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_IMPDATUSAINFOINSERT]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_GRABAAUTOMAIN]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USASALDOPEDIMPDEFINITO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCPORGENERICO]                  [decimal](38, 6) NOT NULL,
		[CF_IMPDATUSAHISTCOSTMA]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USABORRADOTOTALBOM]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SALDODESPSEPARADO]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_BARCODEPDF417]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PENDDESC]                         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_FECHAENTDECANUAL]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_LISTACANTPEDIDA]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAAFFIDAVIT]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_FISCOMP_EXPDESC]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USATODOSPAISDEF]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ACTTASAVERR8]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EM_DIASMANTLOG]                      [smallint] NOT NULL,
		[CF_USABOMSEC]                        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_EDITPEDCORR]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_BOMFECHAINIMAYOR]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_BARCODEAUTCONS]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PASAINFOGENERICO]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAPROVEECERTORIG]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USASETRANSFORMA]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TODOGRAVABLE]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCARGAH1DEF]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TASABAJAFIIMPORTA]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DTAMASUNOALCERRAR]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PEDIMPSINAGRUP]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_REVISIONDOCIMPRIMIR]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SAAIDETDIVPO]                     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CP_AVISOTRASLADO]                    [int] NULL,
		[CF_USATRASLADOPEDIMP]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_VERIFICABOMDESPERDICIO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_DESCARGADEFINITIVOFECHAFACT]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAAVISOTRASLADO]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ANALISISCOSTOMA]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAPRECIOVENTA]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CONCILIASAAISEC]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USAEQUIVALENTEGR]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_GENAUTFACTEXPPO]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_PEDIMPSECFACT]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ANAVT]                            [smallint] NOT NULL,
		[CF_ANAMINIMIS]                       [smallint] NOT NULL,
		[CF_ANACN]                            [smallint] NOT NULL,
		[CF_ANASALTOARA]                      [smallint] NOT NULL,
		[CF_USADESENSAMBLE]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SAAIERANGOINI]                    [int] NOT NULL,
		[CF_SAAIERANGOFIN]                    [int] NOT NULL,
		[CF_SAAIE_CONS]                       [int] NOT NULL,
		[CF_PENDTR]                           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USADESVIACION]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_SALDOPENDPEPS]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_UMSALDO]                          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_VERUMSALDO]                       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_USALIGACORRECTA]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_EXPLOSIONBOMANALISISNAFTA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_CREATABLASCALCULOPAGOCONTRIB]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_VALIDATIPODESCARGAPT]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_VALIDAMATERIALPELIGROSO]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_VALIDAHOJASEGURIDAD]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_FRACCIONFACTURASEMPAQUE]          [int] NOT NULL,
		[CF_VERIFICARPEDINICIOSISTEMA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_FRACCIONCATETER]                  [int] NOT NULL,
		[CF_ACTTASAREGLA16]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ACTTASAGENERAL]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_ACTTASACOMPARATIVO]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_APLICACONTROLRETRABAJO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_APLICACONTROLRESINAS]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_APLICATASABAJAPPSCATMAESTRO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CF_TIPOFRACCIONCATETER]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [PK_CONFIGURACION]
	PRIMARY KEY
	NONCLUSTERED
	([EM_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ACTTASA]
	DEFAULT ('N') FOR [CF_ACTTASA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ACTTASACERTO]
	DEFAULT ('S') FOR [CF_ACTTASACERTO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ACTTASACOMPARATIVO]
	DEFAULT ('N') FOR [CF_ACTTASACOMPARATIVO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ACTTASAGENERAL]
	DEFAULT ('0') FOR [CF_ACTTASAGENERAL]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ACTTASAPER8VA]
	DEFAULT ('S') FOR [CF_ACTTASAPER8VA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ACTTASAPERPPS]
	DEFAULT ('S') FOR [CF_ACTTASAPERPPS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ACTTASAREGLA16]
	DEFAULT ('0') FOR [CF_ACTTASAREGLA16]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ACTTASAVERR8]
	DEFAULT ('N') FOR [CF_ACTTASAVERR8]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ACTUALIZATIEMPO]
	DEFAULT ('S') FOR [CF_ACTUALIZATIEMPO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AGRSENCILLA]
	DEFAULT ('N') FOR [CF_AGRSENCILLA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AGRUPAENTRY]
	DEFAULT ('A') FOR [CF_AGRUPAENTRY]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AGRUPASAAISEC]
	DEFAULT ('N') FOR [CF_AGRUPASAAISEC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ANACN]
	DEFAULT (2) FOR [CF_ANACN]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ANALISISCOSTOMA]
	DEFAULT ('N') FOR [CF_ANALISISCOSTOMA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ANAMINIMIS]
	DEFAULT (3) FOR [CF_ANAMINIMIS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ANASALTOARA]
	DEFAULT (1) FOR [CF_ANASALTOARA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ANAVT]
	DEFAULT (4) FOR [CF_ANAVT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_APLICACONTROLRESINAS]
	DEFAULT ('N') FOR [CF_APLICACONTROLRESINAS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_APLICACONTROLRETRABAJO]
	DEFAULT ('N') FOR [CF_APLICACONTROLRETRABAJO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_APLICANOMS]
	DEFAULT ('S') FOR [CF_APLICANOMS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_APLICATASABAJAPPSCATMAESTRO]
	DEFAULT ('N') FOR [CF_APLICATASABAJAPPSCATMAESTRO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ARANC_PAIS]
	DEFAULT ('P') FOR [CF_ARANC_PAIS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ARGENAVISO]
	DEFAULT ('N') FOR [CF_ARGENAVISO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AUMENTA_VA]
	DEFAULT (1) FOR [CF_AUMENTA_VA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AUTOMOTRIZ]
	DEFAULT ('N') FOR [CF_AUTOMOTRIZ]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AVISO_CERTTLC]
	DEFAULT ('N') FOR [CF_AVISO_CERTTLC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AVISO_PAIS]
	DEFAULT ('N') FOR [CF_AVISO_PAIS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AVISODESCARGA]
	DEFAULT ('S') FOR [CF_AVISODESCARGA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AVISOMAXMIN]
	DEFAULT ('N') FOR [CF_AVISOMAXMIN]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AVISOMODIFFOLIO]
	DEFAULT ('N') FOR [CF_AVISOMODIFFOLIO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_AVISONUMPARTE]
	DEFAULT ('N') FOR [CF_AVISONUMPARTE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_BARCODEAUTCONS]
	DEFAULT ('N') FOR [CF_BARCODEAUTCONS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_BARCODEPDF417]
	DEFAULT ('N') FOR [CF_BARCODEPDF417]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_BOMBORRANOINCLUIDO]
	DEFAULT ('N') FOR [CF_BOMBORRANOINCLUIDO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_BOMFECHAINIMAYOR]
	DEFAULT ('N') FOR [CF_BOMFECHAINIMAYOR]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CAMBIOTASASEC]
	DEFAULT ('N') FOR [CF_CAMBIOTASASEC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CAMBIOUM]
	DEFAULT ('S') FOR [CF_CAMBIOUM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CANCELADESCPEPS]
	DEFAULT ('S') FOR [CF_CANCELADESCPEPS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CLASIFICATLC]
	DEFAULT ('N') FOR [CF_CLASIFICATLC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CONCILIASAAISEC]
	DEFAULT ('N') FOR [CF_CONCILIASAAISEC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CONFERIRORIGEN]
	DEFAULT ('T') FOR [CF_CONFERIRORIGEN]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CONS_EXP]
	DEFAULT ('N') FOR [CF_CONS_EXP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CONS_IMP]
	DEFAULT ('N') FOR [CF_CONS_IMP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CONSECSHIPPER]
	DEFAULT (1) FOR [CF_CONSECSHIPPER]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CONTENEDOR]
	DEFAULT ('S') FOR [CF_CONTENEDOR]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CONTROLDESP]
	DEFAULT ('P') FOR [CF_CONTROLDESP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CORIGXFACT]
	DEFAULT ('N') FOR [CF_CORIGXFACT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_COSTO_PROVEE]
	DEFAULT ('N') FOR [CF_COSTO_PROVEE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CREATABLASCALCULOPAGOCONTRIB]
	DEFAULT ('N') FOR [CF_CREATABLASCALCULOPAGOCONTRIB]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CTRANSP]
	DEFAULT ('P') FOR [CF_CTRANSP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CTRLLOCPRODUC]
	DEFAULT ('N') FOR [CF_CTRLLOCPRODUC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_CUSTOMCLASS]
	DEFAULT ('N') FOR [CF_CUSTOMCLASS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DECANUALBASEPED]
	DEFAULT ('N') FOR [CF_DECANUALBASEPED]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DECANUALGEN]
	DEFAULT ('N') FOR [CF_DECANUALGEN]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCARGADEFINITIVOFECHAFACT]
	DEFAULT ('N') FOR [CF_DESCARGADEFINITIVOFECHAFACT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCARGAH1DEF]
	DEFAULT ('N') FOR [CF_DESCARGAH1DEF]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCARGANDO]
	DEFAULT (0) FOR [CF_DESCARGANDO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCARGAPAIS]
	DEFAULT ('N') FOR [CF_DESCARGAPAIS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCARGAS]
	DEFAULT ('S') FOR [CF_DESCARGAS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCARGASBUS]
	DEFAULT ('I') FOR [CF_DESCARGASBUS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCARGATASA]
	DEFAULT ('N') FOR [CF_DESCARGATASA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCARGAVENCIDOS]
	DEFAULT ('S') FOR [CF_DESCARGAVENCIDOS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCDESPERDICIO]
	DEFAULT ('R') FOR [CF_DESCDESPERDICIO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCDESPFAM]
	DEFAULT ('N') FOR [CF_DESCDESPFAM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCGRCOSTO]
	DEFAULT ('N') FOR [CF_DESCGRCOSTO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCMOVALM]
	DEFAULT ('N') FOR [CF_DESCMOVALM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCPORGENERICO]
	DEFAULT (0) FOR [CF_DESCPORGENERICO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESCUPDATECOSTFE]
	DEFAULT ('N') FOR [CF_DESCUPDATECOSTFE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DESPERDICIO_BOM]
	DEFAULT ('N') FOR [CF_DESPERDICIO_BOM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DIAS_AVISO]
	DEFAULT (15) FOR [CF_DIAS_AVISO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DIAS_AVISOTLC]
	DEFAULT (15) FOR [CF_DIAS_AVISOTLC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DIGITOFOLIO]
	DEFAULT (5) FOR [CF_DIGITOFOLIO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DIMENSIONESMP]
	DEFAULT ('N') FOR [CF_DIMENSIONESMP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DISABLEGEN]
	DEFAULT ('N') FOR [CF_DISABLEGEN]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_DTAMASUNOALCERRAR]
	DEFAULT ('N') FOR [CF_DTAMASUNOALCERRAR]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_EDITPEDCORR]
	DEFAULT ('N') FOR [CF_EDITPEDCORR]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_EMPAQUE_BOM]
	DEFAULT ('N') FOR [CF_EMPAQUE_BOM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_EMPDESPIMP]
	DEFAULT ('N') FOR [CF_EMPDESPIMP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ESTRUCTALT]
	DEFAULT ('N') FOR [CF_ESTRUCTALT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_EXPLOSDESCADD]
	DEFAULT ('N') FOR [CF_EXPLOSDESCADD]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_EXPLOSIONAUX]
	DEFAULT ('S') FOR [CF_EXPLOSIONAUX]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_EXPLOSIONBOMANALISISNAFTA]
	DEFAULT ('S') FOR [CF_EXPLOSIONBOMANALISISNAFTA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_EXPSINBOM]
	DEFAULT ('S') FOR [CF_EXPSINBOM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_FACTORACT]
	DEFAULT ('I') FOR [CF_FACTORACT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_FECHAENTDECANUAL]
	DEFAULT ('S') FOR [CF_FECHAENTDECANUAL]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_FILTRARPARTECLI]
	DEFAULT ('N') FOR [CF_FILTRARPARTECLI]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_FISCOMP_EXPDESC]
	DEFAULT ('N') FOR [CF_FISCOMP_EXPDESC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_FOLIOENT]
	DEFAULT ('N') FOR [CF_FOLIOENT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_FOLIOPED]
	DEFAULT ('N') FOR [CF_FOLIOPED]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_FOLIOSAL]
	DEFAULT ('N') FOR [CF_FOLIOSAL]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_FRACCIONCATETER]
	DEFAULT (0) FOR [CF_FRACCIONCATETER]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_FRACCIONFACTURASEMPAQUE]
	DEFAULT (0) FOR [CF_FRACCIONFACTURASEMPAQUE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_GENAUTFACTEXPPO]
	DEFAULT ('N') FOR [CF_GENAUTFACTEXPPO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_GENERAENTRY]
	DEFAULT ('X') FOR [CF_GENERAENTRY]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_GRABAAUTOMAIN]
	DEFAULT ('S') FOR [CF_GRABAAUTOMAIN]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_IMGONDB]
	DEFAULT ('N') FOR [CF_IMGONDB]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_IMPDATUSAEQFEINSERT]
	DEFAULT ('N') FOR [CF_IMPDATUSAEQFEINSERT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_IMPDATUSAEQFIINSERT]
	DEFAULT ('N') FOR [CF_IMPDATUSAEQFIINSERT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_IMPDATUSAHISTCOSTMA]
	DEFAULT ('S') FOR [CF_IMPDATUSAHISTCOSTMA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_IMPDATUSAINFOINSERT]
	DEFAULT ('N') FOR [CF_IMPDATUSAINFOINSERT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_IMPDATUSAPERMFIINSERT]
	DEFAULT ('N') FOR [CF_IMPDATUSAPERMFIINSERT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_IVAPROPORCIONAL]
	DEFAULT ('S') FOR [CF_IVAPROPORCIONAL]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_LISTACANTPEDIDA]
	DEFAULT ('S') FOR [CF_LISTACANTPEDIDA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_MAN_EMPAQUE]
	DEFAULT ('I') FOR [CF_MAN_EMPAQUE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_MANEJOKITS]
	DEFAULT ('N') FOR [CF_MANEJOKITS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ME_PROVEE]
	DEFAULT ('N') FOR [CF_ME_PROVEE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_MPFIM_MAXNTLC]
	DEFAULT (485) FOR [CF_MPFIM_MAXNTLC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_MPFIM_MINNTLC]
	DEFAULT (25) FOR [CF_MPFIM_MINNTLC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_MPFIM_MINTLC]
	DEFAULT (21) FOR [CF_MPFIM_MINTLC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_MPFIM_NTLC]
	DEFAULT (0.21) FOR [CF_MPFIM_NTLC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_MPFIM_TLC]
	DEFAULT (0) FOR [CF_MPFIM_TLC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_MULTAEXCPLAZO]
	DEFAULT (0) FOR [CF_MULTAEXCPLAZO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_NIVELES]
	DEFAULT (8) FOR [CF_NIVELES]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_NO_PROVEE]
	DEFAULT ('N') FOR [CF_NO_PROVEE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_NO_PROVEECL]
	DEFAULT ('N') FOR [CF_NO_PROVEECL]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_OMISIO]
	DEFAULT (1) FOR [CF_OMISIO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_ORDENDETDOC]
	DEFAULT ('C') FOR [CF_ORDENDETDOC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PAGOCONTRIBDET]
	DEFAULT ('S') FOR [CF_PAGOCONTRIBDET]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PAGOCONTRIBUCION]
	DEFAULT ('S') FOR [CF_PAGOCONTRIBUCION]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PAIS_CA]
	DEFAULT (35) FOR [CF_PAIS_CA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PAIS_MX]
	DEFAULT (154) FOR [CF_PAIS_MX]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PAIS_USA]
	DEFAULT (233) FOR [CF_PAIS_USA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PASAINFOGENERICO]
	DEFAULT ('S') FOR [CF_PASAINFOGENERICO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PEDDESPKG]
	DEFAULT ('N') FOR [CF_PEDDESPKG]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PEDEXPVAUSA]
	DEFAULT ('S') FOR [CF_PEDEXPVAUSA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PEDIMPDETB]
	DEFAULT ('S') FOR [CF_PEDIMPDETB]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PEDIMPFACT]
	DEFAULT ('S') FOR [CF_PEDIMPFACT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PEDIMPSECFACT]
	DEFAULT ('N') FOR [CF_PEDIMPSECFACT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PEDIMPSINAGRUP]
	DEFAULT ('N') FOR [CF_PEDIMPSINAGRUP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PEDSALDOINC]
	DEFAULT ('S') FOR [CF_PEDSALDOINC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PENDDESC]
	DEFAULT ('N') FOR [CF_PENDDESC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PENDGR]
	DEFAULT ('N') FOR [CF_PENDGR]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PENDTR]
	DEFAULT ('N') FOR [CF_PENDTR]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PERMISOAVISO]
	DEFAULT ('S') FOR [CF_PERMISOAVISO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PERMITESINCON]
	DEFAULT ('N') FOR [CF_PERMITESINCON]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PESOS_EXP]
	DEFAULT ('K') FOR [CF_PESOS_EXP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PESOS_IMP]
	DEFAULT ('K') FOR [CF_PESOS_IMP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PRECIOCLIENTE]
	DEFAULT ('N') FOR [CF_PRECIOCLIENTE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_PRECIOFACTEXP]
	DEFAULT (1) FOR [CF_PRECIOFACTEXP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_REPARA]
	DEFAULT ('N') FOR [CF_REPARA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_REVISATIPOTASA]
	DEFAULT ('N') FOR [CF_REVISATIPOTASA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_REVISIONDOCIMPRIMIR]
	DEFAULT ('N') FOR [CF_REVISIONDOCIMPRIMIR]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAI_CONS]
	DEFAULT (1) FOR [CF_SAAI_CONS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIDETDIVFACT]
	DEFAULT ('N') FOR [CF_SAAIDETDIVFACT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIDETDIVPO]
	DEFAULT ('N') FOR [CF_SAAIDETDIVPO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIDIVCOSGEN]
	DEFAULT ('N') FOR [CF_SAAIDIVCOSGEN]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIDIVDESC]
	DEFAULT ('N') FOR [CF_SAAIDIVDESC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIDIVPA]
	DEFAULT ('N') FOR [CF_SAAIDIVPA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIE_CONS]
	DEFAULT (1) FOR [CF_SAAIE_CONS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIERANGOFIN]
	DEFAULT (9999) FOR [CF_SAAIERANGOFIN]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIERANGOINI]
	DEFAULT (1) FOR [CF_SAAIERANGOINI]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIRANGOFIN]
	DEFAULT (999) FOR [CF_SAAIRANGOFIN]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SAAIRANGOINI]
	DEFAULT (1) FOR [CF_SAAIRANGOINI]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SALDODESPSEPARADO]
	DEFAULT ('N') FOR [CF_SALDODESPSEPARADO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SALDOPENDPEPS]
	DEFAULT ('N') FOR [CF_SALDOPENDPEPS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SECTOR]
	DEFAULT ('N') FOR [CF_SECTOR]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SELPAISIMP]
	DEFAULT ('N') FOR [CF_SELPAISIMP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SERVICIOS]
	DEFAULT ('N') FOR [CF_SERVICIOS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SICEXEXP]
	DEFAULT ('N') FOR [CF_SICEXEXP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SINGENERICO]
	DEFAULT ('N') FOR [CF_SINGENERICO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_SINGENERICOUM]
	DEFAULT ('N') FOR [CF_SINGENERICOUM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TASABAJAFIIMPORTA]
	DEFAULT ('N') FOR [CF_TASABAJAFIIMPORTA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TCOCOMPRAIMP]
	DEFAULT ('N') FOR [CF_TCOCOMPRAIMP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TEXTIL]
	DEFAULT ('N') FOR [CF_TEXTIL]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TIEMPOUSO]
	DEFAULT (6) FOR [CF_TIEMPOUSO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TIGIESECTORPERM]
	DEFAULT ('N') FOR [CF_TIGIESECTORPERM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TIPOCOSTO]
	DEFAULT ('N') FOR [CF_TIPOCOSTO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TIPODESCALM]
	DEFAULT ('P') FOR [CF_TIPODESCALM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TIPODESCCAMBIOREG]
	DEFAULT ('P') FOR [CF_TIPODESCCAMBIOREG]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TIPOFIRMA]
	DEFAULT ('A') FOR [CF_TIPOFIRMA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TIPOFRACCIONCATETER]
	DEFAULT ('M') FOR [CF_TIPOFRACCIONCATETER]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TODOGRAVABLE]
	DEFAULT ('N') FOR [CF_TODOGRAVABLE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_TRANSPCONSEC]
	DEFAULT ('N') FOR [CF_TRANSPCONSEC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_UMSALDO]
	DEFAULT ('G') FOR [CF_UMSALDO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_UPDATEARCAMBIO]
	DEFAULT ('N') FOR [CF_UPDATEARCAMBIO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAAFFIDAVIT]
	DEFAULT ('N') FOR [CF_USAAFFIDAVIT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAAVISOTRASLADO]
	DEFAULT ('N') FOR [CF_USAAVISOTRASLADO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USABOMSEC]
	DEFAULT ('N') FOR [CF_USABOMSEC]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USABORRADOTOTALBOM]
	DEFAULT ('N') FOR [CF_USABORRADOTOTALBOM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USACARGOCOSTO]
	DEFAULT ('N') FOR [CF_USACARGOCOSTO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USACATALOGOMA]
	DEFAULT ('N') FOR [CF_USACATALOGOMA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USACATCHOFER]
	DEFAULT ('N') FOR [CF_USACATCHOFER]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USACERTORIGMP]
	DEFAULT ('N') FOR [CF_USACERTORIGMP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USACLASSCOSTO]
	DEFAULT ('N') FOR [CF_USACLASSCOSTO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USACONFGRID]
	DEFAULT ('N') FOR [CF_USACONFGRID]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USACONTPT]
	DEFAULT ('N') FOR [CF_USACONTPT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USACOSTNODUTNAFTA]
	DEFAULT ('N') FOR [CF_USACOSTNODUTNAFTA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USACOSTOBOM]
	DEFAULT ('N') FOR [CF_USACOSTOBOM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USADESCSICEX]
	DEFAULT ('N') FOR [CF_USADESCSICEX]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USADESENSAMBLE]
	DEFAULT ('N') FOR [CF_USADESENSAMBLE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USADESVIACION]
	DEFAULT ('S') FOR [CF_USADESVIACION]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USADISCREPANCIA]
	DEFAULT ('S') FOR [CF_USADISCREPANCIA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAEQUIVALENTE]
	DEFAULT ('N') FOR [CF_USAEQUIVALENTE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAEQUIVALENTEGR]
	DEFAULT ('N') FOR [CF_USAEQUIVALENTEGR]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAFIRMADIGITAL]
	DEFAULT ('N') FOR [CF_USAFIRMADIGITAL]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAGENERICO]
	DEFAULT ('S') FOR [CF_USAGENERICO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAKITS]
	DEFAULT ('N') FOR [CF_USAKITS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USALIGACORRECTA]
	DEFAULT ('S') FOR [CF_USALIGACORRECTA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USALISTAEXP]
	DEFAULT ('N') FOR [CF_USALISTAEXP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USALOCALIDADALM]
	DEFAULT ('N') FOR [CF_USALOCALIDADALM]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USANOPARTECONSULTA]
	DEFAULT ('N') FOR [CF_USANOPARTECONSULTA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAPCKLIST]
	DEFAULT ('N') FOR [CF_USAPCKLIST]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAPEDCT]
	DEFAULT ('N') FOR [CF_USAPEDCT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAPRECIOVENTA]
	DEFAULT ('N') FOR [CF_USAPRECIOVENTA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USAPROVEECERTORIG]
	DEFAULT ('N') FOR [CF_USAPROVEECERTORIG]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USARELCAJAS]
	DEFAULT ('N') FOR [CF_USARELCAJAS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USASALDOPEDIMPDEFINITO]
	DEFAULT ('N') FOR [CF_USASALDOPEDIMPDEFINITO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USASETRANSFORMA]
	DEFAULT ('S') FOR [CF_USASETRANSFORMA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USASUBDECANUAL]
	DEFAULT ('S') FOR [CF_USASUBDECANUAL]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USATIPOADQUISICION]
	DEFAULT ('N') FOR [CF_USATIPOADQUISICION]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USATODOSPAISDEF]
	DEFAULT ('N') FOR [CF_USATODOSPAISDEF]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_USATRASLADOPEDIMP]
	DEFAULT ('N') FOR [CF_USATRASLADOPEDIMP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VAL_PED]
	DEFAULT ('N') FOR [CF_VAL_PED]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VALIDAHOJASEGURIDAD]
	DEFAULT ('N') FOR [CF_VALIDAHOJASEGURIDAD]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VALIDAMATERIALPELIGROSO]
	DEFAULT ('N') FOR [CF_VALIDAMATERIALPELIGROSO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VALIDAPERMISOS]
	DEFAULT ('I') FOR [CF_VALIDAPERMISOS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VALIDATIPODESCARGAPT]
	DEFAULT ('N') FOR [CF_VALIDATIPODESCARGAPT]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VANOGRAVABLE]
	DEFAULT ('S') FOR [CF_VANOGRAVABLE]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VEHICULOS]
	DEFAULT ('S') FOR [CF_VEHICULOS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VERIFICABOMDESPERDICIO]
	DEFAULT ('S') FOR [CF_VERIFICABOMDESPERDICIO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VERIFICARPEDINICIOSISTEMA]
	DEFAULT ('S') FOR [CF_VERIFICARPEDINICIOSISTEMA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CF_VERUMSALDO]
	DEFAULT ('N') FOR [CF_VERUMSALDO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CFR_VERCORETORNO]
	DEFAULT ('N') FOR [CFR_VERCORETORNO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CP_CONSTANCIAEXP]
	DEFAULT (99) FOR [CP_CONSTANCIAEXP]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_CP_ORDENCOMPRA]
	DEFAULT (58) FOR [CP_ORDENCOMPRA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_EM_DIASMANTLOG]
	DEFAULT (7) FOR [EM_DIASMANTLOG]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_ME_KILOGRAMOS]
	DEFAULT (36) FOR [ME_KILOGRAMOS]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_TCO_COMPRA]
	DEFAULT (3) FOR [TCO_COMPRA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_TCO_DESPERDICIO]
	DEFAULT (4) FOR [TCO_DESPERDICIO]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_TCO_MANUFACTURA]
	DEFAULT (1) FOR [TCO_MANUFACTURA]
GO
ALTER TABLE [dbo].[CONFIGURACION]
	ADD
	CONSTRAINT [DF_CONFIGURACION_TCO_RETRABAJO]
	DEFAULT (2) FOR [TCO_RETRABAJO]
GO
