SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[RELMEDIDASAAI] (
		[REL_CODIGO]       [int] IDENTITY(1, 1) NOT NULL,
		[ME_CODIGO]        [int] NOT NULL,
		[ME_COMERCIAL]     [int] NOT NULL,
		CONSTRAINT [IX_RELMEDIDASAAI]
		UNIQUE
		NONCLUSTERED
		([REL_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RELMEDIDASAAI]
	ADD
	CONSTRAINT [PK_RELMEDIDASAAI]
	PRIMARY KEY
	CLUSTERED
	([ME_CODIGO], [ME_COMERCIAL])
	ON [PRIMARY]
GO
