SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPLEMENTA] (
		[BST_HIJO]        [int] NOT NULL,
		[PID_CANT_ST]     [decimal](38, 6) NOT NULL,
		[FE_FECHA]        [datetime] NOT NULL,
		[ME_CODIGO]       [int] NULL,
		[FACTCONV]        [decimal](28, 14) NULL,
		[MA_COSTO]        [decimal](38, 6) NULL,
		[ORIGENREG]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPLEMENTA]
	ADD
	CONSTRAINT [PK_IMPLEMENTA_1]
	PRIMARY KEY
	NONCLUSTERED
	([BST_HIJO], [FE_FECHA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPLEMENTA]
	ADD
	CONSTRAINT [DF_IMPLEMENTA_ORIGENREG]
	DEFAULT ('E') FOR [ORIGENREG]
GO
