SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BUSQUEDAMASCARA] (
		[BUM_CODIGO]           [int] IDENTITY(1, 1) NOT NULL,
		[BUM_TEXTOMOSTRAR]     [varchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_TIPO]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_DECIMAL]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_REDONDEO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_SEPARAMIL]        [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_SIMADICIONA]      [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BUM_SIMPOSICION]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BUM_NEGATIVO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_DATEORDER]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_MESFORMAT]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_DIAFORMAT]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_ANIOFORMAT]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_DATESEPARA]       [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_MASCARATEXT]      [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_BUSQUEDAMASCARA]
		UNIQUE
		NONCLUSTERED
		([BUM_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [PK_BUSQUEDAMASCARA]
	PRIMARY KEY
	NONCLUSTERED
	([BUM_TEXTOMOSTRAR])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [DF_BUSQUEDAMASCARA_BUM_ANIOFORMAT]
	DEFAULT (2) FOR [BUM_ANIOFORMAT]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [DF_BUSQUEDAMASCARA_BUM_DATEORDER]
	DEFAULT (2) FOR [BUM_DATEORDER]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [DF_BUSQUEDAMASCARA_BUM_DATESEPARA]
	DEFAULT ('/') FOR [BUM_DATESEPARA]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [DF_BUSQUEDAMASCARA_BUM_DECIMAL]
	DEFAULT ('C') FOR [BUM_DECIMAL]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [DF_BUSQUEDAMASCARA_BUM_DIAFORMAT]
	DEFAULT (2) FOR [BUM_DIAFORMAT]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [DF_BUSQUEDAMASCARA_BUM_MESFORMAT]
	DEFAULT (3) FOR [BUM_MESFORMAT]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [DF_BUSQUEDAMASCARA_BUM_NEGATIVO]
	DEFAULT (1) FOR [BUM_NEGATIVO]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [DF_BUSQUEDAMASCARA_BUM_REDONDEO]
	DEFAULT ('C') FOR [BUM_REDONDEO]
GO
ALTER TABLE [dbo].[BUSQUEDAMASCARA]
	ADD
	CONSTRAINT [DF_BUSQUEDAMASCARA_BUM_SEPARAMIL]
	DEFAULT ('N') FOR [BUM_SEPARAMIL]
GO
