SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURACARA] (
		[CFC_CODIGO]             [int] IDENTITY(1, 1) NOT NULL,
		[CFC_CARACTERISTICA]     [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFC_TIPO]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_CONFIGURACARA]
		UNIQUE
		NONCLUSTERED
		([CFC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURACARA]
	ADD
	CONSTRAINT [PK_CONFIGURACARA]
	PRIMARY KEY
	NONCLUSTERED
	([CFC_CARACTERISTICA], [CFC_TIPO])
	ON [PRIMARY]
GO
