SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ZONA] (
		[ZO_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[ZO_DESC]       [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PA_CODIGO]     [int] NOT NULL,
		[ZO_IVA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_ZONA]
		UNIQUE
		NONCLUSTERED
		([ZO_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ZONA]
	ADD
	CONSTRAINT [PK_ZONA]
	PRIMARY KEY
	NONCLUSTERED
	([ZO_DESC])
	ON [PRIMARY]
GO
