SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NAFTA] (
		[NFT_CODIGO]           [int] NOT NULL,
		[MA_CODIGO]            [int] NOT NULL,
		[SPI_CODIGO]           [int] NOT NULL,
		[NFT_CLASE]            [int] NOT NULL,
		[NFT_FABRICA]          [int] NOT NULL,
		[NFT_CRITERIO]         [int] NOT NULL,
		[NFT_NETCOST]          [int] NOT NULL,
		[NFT_OTRASINST]        [int] NULL,
		[NFT_COSTOSRESTAR]     [decimal](38, 6) NULL,
		[NFT_RESOLUCION]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_VERBIENFUNG]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_CONTROLINV]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_ORIGBIENFUNG]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_CONTROLINV2]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_PERSONAREL]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CL_EMPRESA]           [int] NOT NULL,
		[NFT_FECHA]            [datetime] NULL,
		[NFT_TIPOEXP]          [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_FECHACERT]        [datetime] NULL,
		[US_CERTIFICADO]       [smallint] NULL,
		[NFT_VCR]              [decimal](38, 6) NULL,
		[US_CODIGO]            [smallint] NULL,
		[NFT_PROCESO]          [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_PERINI]           [datetime] NOT NULL,
		[NFT_PERFIN]           [datetime] NOT NULL,
		[NFT_REFERENCIA]       [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PA_CLASE]             [int] NOT NULL,
		[NFT_BASIS]            [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_COSTO]            [decimal](38, 6) NULL,
		[NFT_PRECIO]           [decimal](38, 6) NULL,
		[NFT_VCRXCN]           [decimal](38, 6) NULL,
		[NFT_VCRXVT]           [decimal](38, 6) NULL,
		[NFT_COSTOTOTALPT]     [decimal](38, 6) NULL,
		[NFT_MINIMIS]          [decimal](38, 6) NULL,
		[NFT_CALIFICO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NFT_NOPARTE]          [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_REGLA]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AR_CODIGO]            [int] NULL,
		[NFT_NOPARTEAUX]       [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NFT_TRACEVALUE]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_NAFTA]
		UNIQUE
		NONCLUSTERED
		([NFT_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [PK_NAFTA]
	PRIMARY KEY
	CLUSTERED
	([MA_CODIGO], [NFT_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_CL_EMPRESA]
	DEFAULT (1) FOR [CL_EMPRESA]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_NFT_CALIFICO]
	DEFAULT ('S') FOR [NFT_CALIFICO]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_NFT_CLASE]
	DEFAULT (1) FOR [NFT_CLASE]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_NFT_COSTOSRESTAR]
	DEFAULT (0) FOR [NFT_COSTOSRESTAR]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_NFT_CRITERIO]
	DEFAULT (1) FOR [NFT_CRITERIO]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_NFT_FABRICA]
	DEFAULT (0) FOR [NFT_FABRICA]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_NFT_NETCOST]
	DEFAULT (0) FOR [NFT_NETCOST]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_NFT_PERFIN]
	DEFAULT ('01/01/9999') FOR [NFT_PERFIN]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_NFT_PERINI]
	DEFAULT ('01/01/1999') FOR [NFT_PERINI]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_NFT_TRACEVALUE]
	DEFAULT ('N') FOR [NFT_TRACEVALUE]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_PA_CLASE]
	DEFAULT (154) FOR [PA_CLASE]
GO
ALTER TABLE [dbo].[NAFTA]
	ADD
	CONSTRAINT [DF_NAFTA_SPI_CODIGO]
	DEFAULT (22) FOR [SPI_CODIGO]
GO
