SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXPORTSPEC] (
		[EMS_CODIGO]          [int] NOT NULL,
		[EMS_FOLIO]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXP_CODIGO]          [int] NOT NULL,
		[EMS_FORMA]           [int] NOT NULL,
		[EMS_TIPOEMPRESA]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EMS_EMPRESA]         [int] NOT NULL,
		[EMS_FECHA]           [datetime] NOT NULL,
		[EMS_TIPOTRANS]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EMS_FILENUMBER]      [int] NOT NULL,
		[PXC_CODIGO]          [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXPORTSPEC]
	ADD
	CONSTRAINT [PK_EXPORTSPEC]
	PRIMARY KEY
	CLUSTERED
	([EMS_FOLIO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXPORTSPEC]
	ADD
	CONSTRAINT [DF_EXPORTSPEC_EMS_FILENUMBER]
	DEFAULT (0) FOR [EMS_FILENUMBER]
GO
ALTER TABLE [dbo].[EXPORTSPEC]
	ADD
	CONSTRAINT [DF_EXPORTSPEC_EMS_FORMA]
	DEFAULT (0) FOR [EMS_FORMA]
GO
ALTER TABLE [dbo].[EXPORTSPEC]
	ADD
	CONSTRAINT [DF_EXPORTSPEC_EMS_TIPOEMPRESA]
	DEFAULT ('A') FOR [EMS_TIPOEMPRESA]
GO
ALTER TABLE [dbo].[EXPORTSPEC]
	ADD
	CONSTRAINT [DF_EXPORTSPEC_EMS_TIPOTRANS]
	DEFAULT ('N') FOR [EMS_TIPOTRANS]
GO
