SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EXPORTSPECFIXVAL] (
		[EMS_CODIGO]     [int] NOT NULL,
		[PXD_CODIGO]     [int] NOT NULL,
		[EMS_VALOR]      [varchar](5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EXPORTSPECFIXVAL]
	ADD
	CONSTRAINT [PK_EXPORTSPECFIXVAL]
	PRIMARY KEY
	CLUSTERED
	([EMS_CODIGO], [PXD_CODIGO])
	ON [PRIMARY]
GO
