SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[MAESTROALMDET] (
		[MA_CODIGO]         [int] NOT NULL,
		[ALM_CODIGO]        [int] NOT NULL,
		[MAM_MAXIMOGEN]     [decimal](38, 6) NOT NULL,
		[MAM_MINIMOGEN]     [decimal](38, 6) NOT NULL,
		[MAM_MAXIMOALM]     [decimal](38, 6) NOT NULL,
		[MAM_MINIMOALM]     [decimal](38, 6) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROALMDET]
	ADD
	CONSTRAINT [PK_MAESTROALMDET]
	PRIMARY KEY
	NONCLUSTERED
	([MA_CODIGO], [ALM_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROALMDET]
	ADD
	CONSTRAINT [DF_MAESTROALMDET_MAM_MAXIMOALM]
	DEFAULT (0) FOR [MAM_MAXIMOALM]
GO
ALTER TABLE [dbo].[MAESTROALMDET]
	ADD
	CONSTRAINT [DF_MAESTROALMDET_MAM_MAXIMOGEN]
	DEFAULT (0) FOR [MAM_MAXIMOGEN]
GO
ALTER TABLE [dbo].[MAESTROALMDET]
	ADD
	CONSTRAINT [DF_MAESTROALMDET_MAM_MINIMOALM]
	DEFAULT (0) FOR [MAM_MINIMOALM]
GO
ALTER TABLE [dbo].[MAESTROALMDET]
	ADD
	CONSTRAINT [DF_MAESTROALMDET_MAM_MINIMOGEN]
	DEFAULT (0) FOR [MAM_MINIMOGEN]
GO
