SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURAEDICIONDESC] (
		[CED_FARANCELARIA]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CED_GRUPOGEN]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CED_ORIGEN]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CED_DESCRIPCION]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CED_TIPO]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAEDICIONDESC]
	ADD
	CONSTRAINT [PK_CONFIGURAEDICIONDESC]
	PRIMARY KEY
	NONCLUSTERED
	([CED_TIPO])
	ON [PRIMARY]
GO
