SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPADVERTENCIA] (
		[FEN_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[FE_CODIGO]         [int] NOT NULL,
		[FE_COMENTARIO]     [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_FACTEXPADVERTENCIA]
		UNIQUE
		NONCLUSTERED
		([FEN_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
