SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[DTA] (
		[DTA_CODIGO]      [int] IDENTITY(1, 1) NOT NULL,
		[DTA_INICIAL]     [datetime] NOT NULL,
		[DTA_FINAL]       [datetime] NOT NULL,
		[DTA_CUOTA]       [decimal](38, 6) NOT NULL,
		CONSTRAINT [IX_DTA]
		UNIQUE
		NONCLUSTERED
		([DTA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DTA]
	ADD
	CONSTRAINT [PK_DTA]
	PRIMARY KEY
	NONCLUSTERED
	([DTA_INICIAL], [DTA_FINAL])
	ON [PRIMARY]
GO
