SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTIMP] (
		[FI_CODIGO]              [int] NOT NULL,
		[FI_FOLIO]               [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_FECHA]               [datetime] NOT NULL,
		[TF_CODIGO]              [smallint] NOT NULL,
		[TQ_CODIGO]              [smallint] NOT NULL,
		[FI_TIPO]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_PINICIAL]            [datetime] NOT NULL,
		[FI_PFINAL]              [datetime] NOT NULL,
		[FC_CODIGO]              [int] NOT NULL,
		[FI_NO_SEM]              [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AG_MEX]                 [int] NOT NULL,
		[AG_USA]                 [int] NOT NULL,
		[PR_CODIGO]              [int] NOT NULL,
		[DI_PROVEE]              [int] NULL,
		[CL_PROD]                [int] NULL,
		[DI_PROD]                [int] NULL,
		[CL_DESTINT]             [int] NULL,
		[DI_DESTINT]             [int] NULL,
		[CL_DESTFIN]             [int] NOT NULL,
		[DI_DESTFIN]             [int] NULL,
		[CL_COMP]                [int] NULL,
		[DI_COMP]                [int] NULL,
		[CL_VEND]                [int] NULL,
		[DI_VEND]                [int] NULL,
		[CL_EXP]                 [int] NULL,
		[DI_EXP]                 [int] NULL,
		[CL_IMP]                 [int] NOT NULL,
		[DI_IMP]                 [int] NULL,
		[ZO_CODIGO]              [smallint] NULL,
		[PU_CARGA]               [int] NULL,
		[PU_SALIDA]              [int] NULL,
		[PU_ENTRADA]             [int] NULL,
		[PU_DESTINO]             [int] NULL,
		[FI_FEC_ENV]             [smalldatetime] NULL,
		[FI_FEC_ARR]             [smalldatetime] NULL,
		[MT_CODIGO]              [smallint] NULL,
		[CT_CODIGO]              [int] NULL,
		[CA_CODIGO]              [int] NULL,
		[FI_TRAC_MX]             [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_TRAC_US]             [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TCA_CODIGO]             [smallint] NULL,
		[CJ_CODIGO]              [int] NULL,
		[FI_CONT_REG]            [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_SELLO]               [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_TRANS_CHO]           [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_COMENTA]             [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_COMENTAUS]           [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[US_CODIGO]              [smallint] NULL,
		[RU_CODIGO]              [smallint] NULL,
		[YA_CODIGO]              [int] NULL,
		[FI_NOINB]               [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_TOTALB]              [decimal](38, 6) NOT NULL,
		[FI_TIPOCAMBIO]          [decimal](38, 6) NULL,
		[FI_NUM_EMB]             [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_DOCUMENTO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_INBOND]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_FACTAGRU]            [int] NOT NULL,
		[FI_ESTATUS]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PI_CODIGO]              [int] NOT NULL,
		[PI_RECTIFICA]           [int] NOT NULL,
		[FI_PI_ENUSO]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_CANCELADO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MO_CODIGO]              [int] NULL,
		[IT_CODIGO]              [smallint] NULL,
		[FI_MANIFIESTO]          [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_GUIA]                [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SPI_CODIGO]             [smallint] NULL,
		[CP_CODIGO]              [smallint] NULL,
		[ALM_CODIGO]             [smallint] NULL,
		[FI_FECFIANZA]           [datetime] NULL,
		[FI_PASARCONTENEDOR]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_DESCRIPTION1]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_DESCRIPTION2]        [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_INVOICETYPE]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_HEADER]              [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_FOOTER]              [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_USACONSOLIDADO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TN_CODIGO]              [smallint] NOT NULL,
		[FI_NUM_INBON]           [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_TIPO_INBON]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_FEC_INBON]           [datetime] NULL,
		[FI_BARCODE]             [image] NULL,
		[FI_NUMVEHICULOS]        [int] NOT NULL,
		[BC_CODIGO]              [int] NOT NULL,
		[MT_ORIGEN]              [int] NULL,
		[FI_GUIAORIGEN]          [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_CUENTADET]           [int] NOT NULL,
		[FI_MANIF]               [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_CONSECUTIVOPED]      [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_TRANSNOORIG]         [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_TRANSNO]             [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGT_CODIGO]             [int] NULL,
		[SI_CODIGO]              [int] NOT NULL,
		[FI_PRIORIDAD]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_ITN]                 [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FIG_CODIGO]             [int] NOT NULL,
		[FI_INICIOCRUCE]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FI_FIRMAAVISO]          [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_FIRMAELECTAVANZ]     [varchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_BARCODEREMESA]       [image] NULL,
		[BC_REMESA]              [int] NOT NULL,
		[FI_TIPOCAMBIOUSD]       [decimal](38, 6) NOT NULL,
		[FI_FOLIOPROVEE]         [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_FEACODBARRAS]        [varchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FI_EDOCUMENT]           [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_FACTIMP]
		UNIQUE
		NONCLUSTERED
		([FI_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [PK_FACTIMP]
	PRIMARY KEY
	NONCLUSTERED
	([FI_FOLIO], [FI_TIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_BC_CODIGO]
	DEFAULT (0) FOR [BC_CODIGO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_BC_REMESA]
	DEFAULT (0) FOR [BC_REMESA]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FC_CODIGO]
	DEFAULT (0) FOR [FC_CODIGO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_CANCELADO]
	DEFAULT ('N') FOR [FI_CANCELADO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_CONT_REG]
	DEFAULT ('') FOR [FI_CONT_REG]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_CUENTADET]
	DEFAULT (0) FOR [FI_CUENTADET]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_DESCRIPTION1]
	DEFAULT ('') FOR [FI_DESCRIPTION1]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_DESCRIPTION2]
	DEFAULT ('') FOR [FI_DESCRIPTION2]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_ESTATUS]
	DEFAULT ('S') FOR [FI_ESTATUS]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_FACTAGRU]
	DEFAULT ((-1)) FOR [FI_FACTAGRU]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_FOOTER]
	DEFAULT ('') FOR [FI_FOOTER]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_GUIA]
	DEFAULT ('') FOR [FI_GUIA]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_HEADER]
	DEFAULT ('') FOR [FI_HEADER]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_INICIOCRUCE]
	DEFAULT ('N') FOR [FI_INICIOCRUCE]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_MANIFIESTO]
	DEFAULT ('') FOR [FI_MANIFIESTO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_NO_SEM]
	DEFAULT ('') FOR [FI_NO_SEM]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_NOINB]
	DEFAULT ('') FOR [FI_NOINB]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_NUM_EMB]
	DEFAULT (' ') FOR [FI_NUM_EMB]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_NUMVEHICULOS]
	DEFAULT (1) FOR [FI_NUMVEHICULOS]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_PASARCONTENEDOR]
	DEFAULT ('N') FOR [FI_PASARCONTENEDOR]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_PI_ENUSO]
	DEFAULT ('X') FOR [FI_PI_ENUSO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_PRIORIDAD]
	DEFAULT ('N') FOR [FI_PRIORIDAD]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_SELLO]
	DEFAULT ('') FOR [FI_SELLO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_TIPO]
	DEFAULT ('F') FOR [FI_TIPO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_TIPOCAMBIOUSD]
	DEFAULT (1) FOR [FI_TIPOCAMBIOUSD]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_TOTALB]
	DEFAULT (0) FOR [FI_TOTALB]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_TRAC_MX]
	DEFAULT ('') FOR [FI_TRAC_MX]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_TRAC_US]
	DEFAULT ('') FOR [FI_TRAC_US]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_TRANS_CHO]
	DEFAULT ('') FOR [FI_TRANS_CHO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FI_USACONSOLIDADO]
	DEFAULT ('N') FOR [FI_USACONSOLIDADO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_FIG_CODIGO]
	DEFAULT ((-1)) FOR [FIG_CODIGO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_PI_CODIGO]
	DEFAULT ((-1)) FOR [PI_CODIGO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_PI_RECTIFICA]
	DEFAULT ((-1)) FOR [PI_RECTIFICA]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_SI_CODIGO]
	DEFAULT ((-1)) FOR [SI_CODIGO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_TF_CODIGO]
	DEFAULT (0) FOR [TF_CODIGO]
GO
ALTER TABLE [dbo].[FACTIMP]
	ADD
	CONSTRAINT [DF_FACTIMP_TN_CODIGO]
	DEFAULT (4) FOR [TN_CODIGO]
GO
CREATE CLUSTERED INDEX [IX_FACTIMP_1]
	ON [dbo].[FACTIMP] ([FI_CODIGO], [FI_FOLIO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FACTIMP_2]
	ON [dbo].[FACTIMP] ([PI_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FACTIMP_3]
	ON [dbo].[FACTIMP] ([PI_RECTIFICA])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FACTIMP_4]
	ON [dbo].[FACTIMP] ([TF_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FACTIMP_5]
	ON [dbo].[FACTIMP] ([TQ_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FACTIMP_6]
	ON [dbo].[FACTIMP] ([FI_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FACTIMP_7]
	ON [dbo].[FACTIMP] ([FI_CODIGO], [FI_FACTAGRU], [PI_CODIGO], [MO_CODIGO], [FI_FOLIO], [FI_FECHA], [PR_CODIGO], [DI_PROVEE], [FI_CONT_REG], [FI_TIPOCAMBIO], [IT_CODIGO], [FI_CONSECUTIVOPED])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FACTIMP_8]
	ON [dbo].[FACTIMP] ([PI_RECTIFICA], [PI_CODIGO])
	ON [PRIMARY]
GO
