SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGVERIFICAENTSAL] (
		[VET_PATENTE]         [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MT_CODIGO]           [smallint] NOT NULL,
		[VET_TIPOMOV]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VET_TIPODESFASE]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGVERIFICAENTSAL]
	ADD
	CONSTRAINT [PK_CONFIGVERIFICAENTSAL]
	PRIMARY KEY
	CLUSTERED
	([VET_PATENTE], [MT_CODIGO], [VET_TIPOMOV])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGVERIFICAENTSAL]
	ADD
	CONSTRAINT [DF_CONFIGVERIFICAENTSAL_MT_CODIGO]
	DEFAULT (0) FOR [MT_CODIGO]
GO
