SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PERMISOCONTROL] (
		[PE_CODIGO]        [int] NOT NULL,
		[CL_CODIGO]        [int] NOT NULL,
		[PET_MONTOEXP]     [decimal](38, 6) NOT NULL,
		[PET_ANIOPROG]     [int] NULL,
		[PET_NUMPROG]      [int] NULL,
		[PET_PORCONT]      [decimal](38, 6) NULL,
		[PET_PORCEXT]      [decimal](38, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERMISOCONTROL]
	ADD
	CONSTRAINT [PK_PERMISOCONTROL]
	PRIMARY KEY
	CLUSTERED
	([PE_CODIGO], [CL_CODIGO])
	ON [PRIMARY]
GO
