SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MISING] (
		[MI_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[MI_CLAVE]      [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MI_NOMBRE]     [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MI_NAME]       [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_MISING]
		UNIQUE
		NONCLUSTERED
		([MI_CODIGO])
		ON [PRIMARY],
		CONSTRAINT [IX_MISING_1]
		UNIQUE
		NONCLUSTERED
		([MI_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MISING]
	ADD
	CONSTRAINT [PK_MISING]
	PRIMARY KEY
	NONCLUSTERED
	([MI_CLAVE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MISING]
	ADD
	CONSTRAINT [DF_MISING_MI_NOMBRE]
	DEFAULT ('') FOR [MI_NOMBRE]
GO
