SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPIMAGEN] (
		[PI_CODIGO]            [int] NOT NULL,
		[IM_IMAGEN]            [image] NULL,
		[IM_ORDEN]             [int] NOT NULL,
		[IM_NOMBREARCHIVO]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PI_FOLIO]             [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PI_TIPO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPIMAGEN]
	ADD
	CONSTRAINT [PK_PEDIMPIMAGEN]
	PRIMARY KEY
	NONCLUSTERED
	([PI_CODIGO], [IM_ORDEN], [PI_TIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPIMAGEN]
	ADD
	CONSTRAINT [DF_PEDIMPIMAGEN_PI_TIPO]
	DEFAULT ('N') FOR [PI_TIPO]
GO
