SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRODUCCIONEMPAQUEADICIONAL] (
		[PRO_CODIGO]         [int] NOT NULL,
		[MA_CODIGO]          [int] NOT NULL,
		[MA_NOPARTE]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PROAD_CANTIDAD]     [decimal](38, 6) NULL,
		[MA_GENERICO]        [int] NULL,
		[EQ_GEN]             [decimal](28, 14) NULL,
		[ME_CODIGO]          [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCCIONEMPAQUEADICIONAL]
	ADD
	CONSTRAINT [PK_PRODUCCIONEMPAQUEADICIONAL]
	PRIMARY KEY
	NONCLUSTERED
	([PRO_CODIGO], [MA_CODIGO])
	ON [PRIMARY]
GO
