SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPCTRANSPOR] (
		[PIR_CODIGO]           [int] IDENTITY(1, 1) NOT NULL,
		[PI_CODIGO]            [int] NOT NULL,
		[CT_CODIGO]            [int] NOT NULL,
		[PA_CTRANPOR]          [int] NULL,
		[PI_IDENTMTRANSP]      [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PI_NUMEROCANDADO]     [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_PEDIMPCTRANSPOR]
		UNIQUE
		NONCLUSTERED
		([PIR_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCTRANSPOR]
	ADD
	CONSTRAINT [PK_PEDIMPCTRANSPOR]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO], [CT_CODIGO], [PI_IDENTMTRANSP])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCTRANSPOR]
	ADD
	CONSTRAINT [DF_PEDIMPCTRANSPOR_PI_IDENTMTRANSP]
	DEFAULT ('') FOR [PI_IDENTMTRANSP]
GO
