SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[LISTAEXPINCREMENTA] (
		[LE_CODIGO]     [int] NOT NULL,
		[IC_CODIGO]     [smallint] NOT NULL,
		[LEI_VALOR]     [decimal](38, 6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LISTAEXPINCREMENTA]
	ADD
	CONSTRAINT [PK_LISTAEXPINCREMENTA]
	PRIMARY KEY
	CLUSTERED
	([LE_CODIGO], [IC_CODIGO])
	ON [PRIMARY]
GO
