SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[CTRANSPORADIC] (
		[CTA_CODIGO]      [int] IDENTITY(1, 1) NOT NULL,
		[CT_CODIGO]       [int] NOT NULL,
		[CTA_CANTINI]     [decimal](38, 6) NOT NULL,
		[CTA_CANTFIN]     [decimal](38, 6) NOT NULL,
		[CTA_PRECIO]      [decimal](38, 6) NULL,
		CONSTRAINT [IX_CTRANSPORADIC]
		UNIQUE
		NONCLUSTERED
		([CTA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTRANSPORADIC]
	ADD
	CONSTRAINT [PK_CTRANSPORADIC]
	PRIMARY KEY
	CLUSTERED
	([CT_CODIGO], [CTA_CANTINI], [CTA_CANTFIN])
	ON [PRIMARY]
GO
