SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COMBOBOXES] (
		[CB_CODIGO]          [int] IDENTITY(1, 1) NOT NULL,
		[CB_TABLA]           [smallint] NOT NULL,
		[CB_FIELD]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CB_KEYFIELD]        [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CB_LOOKUP]          [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CB_LOOKUPENG]       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CB_NOMBRETABLA]     [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_COMBOBOXES]
		UNIQUE
		NONCLUSTERED
		([CB_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMBOBOXES]
	ADD
	CONSTRAINT [PK_COMBOBOXES]
	PRIMARY KEY
	CLUSTERED
	([CB_TABLA], [CB_FIELD], [CB_KEYFIELD])
	ON [PRIMARY]
GO
