SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TCOSTO] (
		[TCO_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[TCO_NOMBRE]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TCO_NAME]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TCO_TIPO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_TCOSTO]
		UNIQUE
		NONCLUSTERED
		([TCO_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TCOSTO]
	ADD
	CONSTRAINT [PK_TCOSTO]
	PRIMARY KEY
	NONCLUSTERED
	([TCO_NOMBRE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TCOSTO]
	ADD
	CONSTRAINT [DF_TCOSTO_TCO_TIPO]
	DEFAULT ('A') FOR [TCO_TIPO]
GO
