SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPITN] (
		[PI_CODIGO]       [int] NOT NULL,
		[ITN_BARCODE]     [image] NULL,
		[ITN_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ITN_TEXTO]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPITN]
	ADD
	CONSTRAINT [PK_PEDIMPITN]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO], [ITN_TEXTO])
	ON [PRIMARY]
GO
