SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPCONCILIALOG] (
		[IML_CODIGO]      [int] IDENTITY(1, 1) NOT NULL,
		[IML_MENSAJE]     [varchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_IMPCONCILIALOG]
		UNIQUE
		NONCLUSTERED
		([IML_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
