SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[ELECTRODO] (
		[EL_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[EL_ELECTRODO]     [decimal](38, 6) NOT NULL,
		[EL_FECHA]         [datetime] NOT NULL,
		CONSTRAINT [IX_ELECTRODO]
		UNIQUE
		NONCLUSTERED
		([EL_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELECTRODO]
	ADD
	CONSTRAINT [PK_ELECTRODO]
	PRIMARY KEY
	NONCLUSTERED
	([EL_ELECTRODO], [EL_FECHA])
	ON [PRIMARY]
GO
