SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BUSQUEDAFORMULA] (
		[BUF_CODIGO]            [int] NOT NULL,
		[BUS_CODIGO]            [int] NOT NULL,
		[BUS_FORMULANAME]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUS_FORMULASTRING]     [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BUS_MOSTRAR]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_CODIGO]            [int] NOT NULL,
		[BUF_TIPO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BUF_FORMULATITLE]      [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BUF_DATATYPE]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUF_AGRUPACION]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUF_SECCION]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUF_VERIFICADA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUF_LONGITUD]          [int] NOT NULL,
		[BUF_ORDENCOL]          [int] NULL,
		CONSTRAINT [IX_BUSQUEDAFORMULA]
		UNIQUE
		NONCLUSTERED
		([BUF_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [PK_BUSQUEDAFORMULA]
	PRIMARY KEY
	NONCLUSTERED
	([BUS_CODIGO], [BUS_FORMULANAME])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [DF_BUSQUEDAFORMULA_BUF_AGRUPACION]
	DEFAULT ('A') FOR [BUF_AGRUPACION]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [DF_BUSQUEDAFORMULA_BUF_CODIGO]
	DEFAULT (0) FOR [BUF_CODIGO]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [DF_BUSQUEDAFORMULA_BUF_DATATYPE]
	DEFAULT ('0') FOR [BUF_DATATYPE]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [DF_BUSQUEDAFORMULA_BUF_LONGITUD]
	DEFAULT (20) FOR [BUF_LONGITUD]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [DF_BUSQUEDAFORMULA_BUF_SECCION]
	DEFAULT ('D') FOR [BUF_SECCION]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [DF_BUSQUEDAFORMULA_BUF_TIPO]
	DEFAULT ('C') FOR [BUF_TIPO]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [DF_BUSQUEDAFORMULA_BUF_VERIFICADA]
	DEFAULT ('N') FOR [BUF_VERIFICADA]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [DF_BUSQUEDAFORMULA_BUM_CODIGO]
	DEFAULT (0) FOR [BUM_CODIGO]
GO
ALTER TABLE [dbo].[BUSQUEDAFORMULA]
	ADD
	CONSTRAINT [DF_BUSQUEDAFORMULA_BUS_MOSTRAR]
	DEFAULT ('N') FOR [BUS_MOSTRAR]
GO
