SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BOMESPECIALDESCTEMP] (
		[CONSECUTIVO]         [int] IDENTITY(1, 1) NOT NULL,
		[FE_CODIGO]           [int] NULL,
		[FED_INDICED]         [int] NULL,
		[BST_PT]              [int] NOT NULL,
		[BST_ENTRAVIGOR]      [datetime] NULL,
		[BST_HIJO]            [int] NOT NULL,
		[BST_INCORPOR]        [decimal](38, 20) NOT NULL,
		[BST_DISCH]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TI_CODIGO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ME_CODIGO]           [int] NULL,
		[FACTCONV]            [decimal](28, 14) NOT NULL,
		[BST_PERINI]          [datetime] NULL,
		[BST_PERFIN]          [datetime] NULL,
		[ME_GEN]              [int] NULL,
		[BST_TRANS]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BST_TIPOCOSTO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BST_COSTO]           [decimal](38, 6) NULL,
		[MA_TIP_ENS]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FED_CANT]            [decimal](38, 6) NULL,
		[BST_NIVEL]           [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BST_TIPODESC]        [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BST_PERTENECE]       [int] NULL,
		[BST_CONTESTATUS]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FACT_INV]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BST_DESCARGADO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BST_PESO_KG]         [decimal](38, 6) NULL,
		[BST_ORIGEN]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_BOMESPECIALDESCTEMP]
		UNIQUE
		NONCLUSTERED
		([CONSECUTIVO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOMESPECIALDESCTEMP]
	ADD
	CONSTRAINT [DF_BOMESPECIALDESCTEMP_BST_CONTESTATUS]
	DEFAULT ('E') FOR [BST_CONTESTATUS]
GO
ALTER TABLE [dbo].[BOMESPECIALDESCTEMP]
	ADD
	CONSTRAINT [DF_BOMESPECIALDESCTEMP_BST_DESCARGADO]
	DEFAULT ('N') FOR [BST_DESCARGADO]
GO
ALTER TABLE [dbo].[BOMESPECIALDESCTEMP]
	ADD
	CONSTRAINT [DF_BOMESPECIALDESCTEMP_BST_DISCH]
	DEFAULT ('S') FOR [BST_DISCH]
GO
ALTER TABLE [dbo].[BOMESPECIALDESCTEMP]
	ADD
	CONSTRAINT [DF_BOMESPECIALDESCTEMP_BST_INCORPOR]
	DEFAULT (1) FOR [BST_INCORPOR]
GO
ALTER TABLE [dbo].[BOMESPECIALDESCTEMP]
	ADD
	CONSTRAINT [DF_BOMESPECIALDESCTEMP_BST_PERFIN]
	DEFAULT ('01/01/9999') FOR [BST_PERFIN]
GO
ALTER TABLE [dbo].[BOMESPECIALDESCTEMP]
	ADD
	CONSTRAINT [DF_BOMESPECIALDESCTEMP_BST_PESO_KG]
	DEFAULT (0) FOR [BST_PESO_KG]
GO
ALTER TABLE [dbo].[BOMESPECIALDESCTEMP]
	ADD
	CONSTRAINT [DF_BOMESPECIALDESCTEMP_BST_TRANS]
	DEFAULT ('N') FOR [BST_TRANS]
GO
ALTER TABLE [dbo].[BOMESPECIALDESCTEMP]
	ADD
	CONSTRAINT [DF_BOMESPECIALDESCTEMP_FACT_INV]
	DEFAULT ('F') FOR [FACT_INV]
GO
ALTER TABLE [dbo].[BOMESPECIALDESCTEMP]
	ADD
	CONSTRAINT [DF_BOMESPECIALDESCTEMP_FACTCONV]
	DEFAULT (1) FOR [FACTCONV]
GO
CREATE NONCLUSTERED INDEX [IX_BOMESPECIALDESCTEMP_1]
	ON [dbo].[BOMESPECIALDESCTEMP] ([FE_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BOMESPECIALDESCTEMP_2]
	ON [dbo].[BOMESPECIALDESCTEMP] ([FED_INDICED])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BOMESPECIALDESCTEMP_3]
	ON [dbo].[BOMESPECIALDESCTEMP] ([BST_HIJO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_BOMESPECIALDESCTEMP_4]
	ON [dbo].[BOMESPECIALDESCTEMP] ([BST_PT])
	ON [PRIMARY]
GO
