SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[RELTEMBTIPO] (
		[TQ_CODIGO]     [smallint] NOT NULL,
		[TI_CODIGO]     [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RELTEMBTIPO]
	ADD
	CONSTRAINT [PK_RELTEMBTIPO]
	PRIMARY KEY
	NONCLUSTERED
	([TQ_CODIGO], [TI_CODIGO])
	ON [PRIMARY]
GO
