SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPCAJA] (
		[PIN_CODIGO]           [int] IDENTITY(1, 1) NOT NULL,
		[PI_CODIGO]            [int] NOT NULL,
		[PI_CONTENEDOR_NO]     [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TCA_CODIGO]           [smallint] NOT NULL,
		CONSTRAINT [IX_PEDIMPCAJA]
		UNIQUE
		NONCLUSTERED
		([PIN_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCAJA]
	ADD
	CONSTRAINT [PK_PEDIMPCAJA]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO], [PI_CONTENEDOR_NO])
	ON [PRIMARY]
GO
