SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TTASA] (
		[TTA_CODIGO]      [smallint] IDENTITY(1, 1) NOT NULL,
		[TTA_CLA_PED]     [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TTA_DESC]        [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TTA_NIVEL]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_TTASA]
		UNIQUE
		NONCLUSTERED
		([TTA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TTASA]
	ADD
	CONSTRAINT [PK_TTASA]
	PRIMARY KEY
	NONCLUSTERED
	([TTA_CLA_PED])
	ON [PRIMARY]
GO
