SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPORTSPEC] (
		[IMS_CODIGO]               [int] NOT NULL,
		[IMS_ESPECIFICACION]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_FORMATO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_ORDENFECHA]           [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_SEPARADORFECHA]       [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_SEPARADORHORA]        [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_CUATROCIFRAS]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_MESCONLETRAS]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_SIMBOLODECIMAL]       [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_CBFORMA]              [int] NOT NULL,
		[IMS_CBQUAL]               [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_DELIMCOLUMNA]         [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_PRIMERAFILA]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_TIPOIMPORTACION]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_COLUMNASFIJAS]        [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMS_COLUMNASVISIBLES]     [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMS_CBDETALLE]            [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMS_HEADERS]              [varchar](800) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMS_BORRARBOM]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_HISTORIAL]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_FILTRAR]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_FILTRO]               [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMS_USAFOLIADOR]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMS_TIPOSPEC]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CNX_CODIGO]               [int] NOT NULL,
		[IMF_ARIMPMX]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_ARIMPFO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_UPDATEMAESTRO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_MAESTRO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_RUTAS]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_FACTURA]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_SINAGRUPA]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [PK_IMPORTSPEC]
	PRIMARY KEY
	NONCLUSTERED
	([IMS_CODIGO], [IMS_CBFORMA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_CNX_CODIGO]
	DEFAULT (0) FOR [CNX_CODIGO]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMF_ARIMPFO]
	DEFAULT ('N') FOR [IMF_ARIMPFO]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMF_ARIMPMX]
	DEFAULT ('N') FOR [IMF_ARIMPMX]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMF_FACTURA]
	DEFAULT ('N') FOR [IMF_FACTURA]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMF_MAESTRO]
	DEFAULT ('N') FOR [IMF_MAESTRO]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMF_RUTAS]
	DEFAULT ('N') FOR [IMF_RUTAS]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMF_SINAGRUPA]
	DEFAULT ('N') FOR [IMF_SINAGRUPA]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMF_UPDATEMAESTRO]
	DEFAULT ('N') FOR [IMF_UPDATEMAESTRO]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMS_BORRARBOM]
	DEFAULT ('N') FOR [IMS_BORRARBOM]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMS_FILTRAR]
	DEFAULT ('N') FOR [IMS_FILTRAR]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMS_HISTORIAL]
	DEFAULT ('N') FOR [IMS_HISTORIAL]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMS_TIPOSPEC]
	DEFAULT ('F') FOR [IMS_TIPOSPEC]
GO
ALTER TABLE [dbo].[IMPORTSPEC]
	ADD
	CONSTRAINT [DF_IMPORTSPEC_IMS_USAFOLIADOR]
	DEFAULT ('N') FOR [IMS_USAFOLIADOR]
GO
