SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPPEDIMPTMP] (
		[PI_CODIGO]       [int] NOT NULL,
		[RPT_CODIGO]      [int] NOT NULL,
		[RPT_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RPT_ESTATUS]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPPEDIMPTMP]
	ADD
	CONSTRAINT [PK_IMPPEDIMENT]
	PRIMARY KEY
	NONCLUSTERED
	([PI_CODIGO], [RPT_CODIGO], [RPT_TIPO])
	ON [PRIMARY]
GO
