SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COTIZACIONCONTRIBUCION] (
		[COT_CODIGO]            [int] NOT NULL,
		[CON_CODIGO]            [int] NOT NULL,
		[COTC_CONTRIBPOR]       [decimal](38, 6) NOT NULL,
		[COTC_CONTRIBTOTUS]     [decimal](38, 6) NOT NULL,
		[COTC_TIPOVALOR]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COTIZACIONCONTRIBUCION]
	ADD
	CONSTRAINT [PK_COTIZACIONCONTRIBUCION]
	PRIMARY KEY
	NONCLUSTERED
	([COT_CODIGO], [CON_CODIGO], [COTC_CONTRIBPOR])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[COTIZACIONCONTRIBUCION]
	ADD
	CONSTRAINT [DF_COTIZACIONCONTRIBUCION_COTC_CONTRIBPOR]
	DEFAULT ((-1)) FOR [COTC_CONTRIBPOR]
GO
ALTER TABLE [dbo].[COTIZACIONCONTRIBUCION]
	ADD
	CONSTRAINT [DF_COTIZACIONCONTRIBUCION_COTC_CONTRIBTOTUS]
	DEFAULT (0) FOR [COTC_CONTRIBTOTUS]
GO
