SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPGUIA] (
		[PIG_CODIGO]     [int] IDENTITY(1, 1) NOT NULL,
		[PI_CODIGO]      [int] NOT NULL,
		[PI_GUIA]        [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PI_TGUIA]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_PEDIMPGUIA]
		UNIQUE
		NONCLUSTERED
		([PIG_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPGUIA]
	ADD
	CONSTRAINT [PK_PEDIMPGUIA]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO], [PI_GUIA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPGUIA]
	ADD
	CONSTRAINT [DF_PEDIMPGUIA_PI_GUIA]
	DEFAULT ('') FOR [PI_GUIA]
GO
ALTER TABLE [dbo].[PEDIMPGUIA]
	ADD
	CONSTRAINT [DF_PEDIMPGUIA_PI_TGUIA]
	DEFAULT ('') FOR [PI_TGUIA]
GO
