SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPCUENTA] (
		[PIU_CODIGO]               [int] IDENTITY(1, 1) NOT NULL,
		[PI_CODIGO]                [int] NOT NULL,
		[BAN_CODIGO]               [smallint] NOT NULL,
		[PIU_NOCUENTA]             [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PIU_FOLIOCONSTANCIA]      [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PIU_FECHACONSTANCIA]      [datetime] NULL,
		[PIU_TIPOCUENTA]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PIU_CLAVEGARANTIA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PIU_VALORUNIT_TITULO]     [decimal](38, 6) NULL,
		[PIU_IMPORTETOTAL]         [decimal](38, 6) NULL,
		[PIU_CANTIDAD]             [decimal](38, 6) NULL,
		[PIU_CANTTITULOS]          [decimal](38, 6) NULL,
		CONSTRAINT [IX_PEDIMPCUENTA]
		UNIQUE
		NONCLUSTERED
		([PIU_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCUENTA]
	ADD
	CONSTRAINT [PK_PEDIMPCUENTA]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO], [BAN_CODIGO], [PIU_NOCUENTA])
	ON [PRIMARY]
GO
