SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPDETCARGO] (
		[FE_CODIGO]       [int] NOT NULL,
		[FED_INDICED]     [int] NOT NULL,
		[CAR_CODIGO]      [int] NOT NULL,
		[FEG_VALOR]       [decimal](38, 6) NOT NULL,
		[FEG_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDETCARGO]
	ADD
	CONSTRAINT [PK_FACTEXPDETCARGO]
	PRIMARY KEY
	CLUSTERED
	([FED_INDICED], [CAR_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDETCARGO]
	ADD
	CONSTRAINT [DF_FACTEXPDETCARGO_FEG_TIPO]
	DEFAULT ('T') FOR [FEG_TIPO]
GO
ALTER TABLE [dbo].[FACTEXPDETCARGO]
	ADD
	CONSTRAINT [DF_FACTEXPDETCARGO_FEG_VALOR]
	DEFAULT (0) FOR [FEG_VALOR]
GO
