SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[ARANCELREGLAORIGEN] (
		[AR_CODIGO]      [int] NOT NULL,
		[ARR_CODIGO]     [int] NOT NULL,
		[ARR_PERINI]     [datetime] NOT NULL,
		[ARR_PERFIN]     [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARANCELREGLAORIGEN]
	ADD
	CONSTRAINT [PK_ARANCELREGLAORIGEN]
	PRIMARY KEY
	CLUSTERED
	([AR_CODIGO], [ARR_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARANCELREGLAORIGEN]
	ADD
	CONSTRAINT [DF_ARANCELREGLAORIGEN_ARR_PERFIN]
	DEFAULT ('9999-01-01') FOR [ARR_PERFIN]
GO
ALTER TABLE [dbo].[ARANCELREGLAORIGEN]
	ADD
	CONSTRAINT [DF_ARANCELREGLAORIGEN_ARR_PERINI]
	DEFAULT ('1999-01-01') FOR [ARR_PERINI]
GO
