SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPEXCELRELFACTENTRY] (
		[FACTURA]       [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NOENTRY]       [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA]         [datetime] NULL,
		[TIPOENTRY]     [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPEXCELRELFACTENTRY]
	ADD
	CONSTRAINT [PK_IMPEXCELRELFACTENTRY]
	PRIMARY KEY
	CLUSTERED
	([FACTURA], [NOENTRY])
	ON [PRIMARY]
GO
