SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORDTRABAJODETENTPARCIAL] (
		[OTDP_INDICEP]     [int] NOT NULL,
		[OTD_INDICED]      [int] NOT NULL,
		[OTDP_FECHA]       [datetime] NOT NULL,
		[OTDP_CANT]        [decimal](38, 6) NOT NULL,
		[OTDP_OBSERVA]     [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[OTDP_SALDO]       [decimal](38, 6) NULL,
		[OTDP_ENUSO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDTRABAJODETENTPARCIAL]
	ADD
	CONSTRAINT [PK_ORDTRABAJODETENTPARCIAL]
	PRIMARY KEY
	NONCLUSTERED
	([OTD_INDICED], [OTDP_FECHA])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDTRABAJODETENTPARCIAL]
	ADD
	CONSTRAINT [DF_ORDTRABAJODETENTPARCIAL_OTDP_ENUSO]
	DEFAULT ('N') FOR [OTDP_ENUSO]
GO
