SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTROCOSTHIST] (
		[MAH_CODIGO]        [int] IDENTITY(1, 1) NOT NULL,
		[TCO_CODIGO]        [smallint] NOT NULL,
		[MA_CODIGO]         [int] NOT NULL,
		[MA_GRAV_MP]        [float] NOT NULL,
		[MA_GRAV_ADD]       [float] NOT NULL,
		[MA_GRAV_EMP]       [float] NOT NULL,
		[MA_GRAV_GI]        [float] NOT NULL,
		[MA_GRAV_GI_MX]     [float] NOT NULL,
		[MA_GRAV_MO]        [float] NOT NULL,
		[MA_NG_MP]          [float] NOT NULL,
		[MA_NG_ADD]         [float] NOT NULL,
		[MA_NG_EMP]         [float] NOT NULL,
		[MA_COSTO]          [float] NOT NULL,
		[MA_GRAVA_VA]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_NG_USA]         [float] NOT NULL,
		[TV_CODIGO]         [int] NOT NULL,
		[MAH_FECHACAMB]     [datetime] NOT NULL,
		[EQ_GEN]            [float] NULL,
		CONSTRAINT [IX_MAESTROCOSTHIST]
		UNIQUE
		NONCLUSTERED
		([MAH_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [PK_MAESTROCOSTHIST]
	PRIMARY KEY
	NONCLUSTERED
	([TCO_CODIGO], [MA_CODIGO], [MAH_FECHACAMB])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_COSTO]
	DEFAULT (0) FOR [MA_COSTO]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_GRAV_ADD]
	DEFAULT (0) FOR [MA_GRAV_ADD]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_GRAV_EMP]
	DEFAULT (0) FOR [MA_GRAV_EMP]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_GRAV_GI]
	DEFAULT (0) FOR [MA_GRAV_GI]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_GRAV_GI_MX]
	DEFAULT (0) FOR [MA_GRAV_GI_MX]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_GRAV_MO]
	DEFAULT (0) FOR [MA_GRAV_MO]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_GRAV_MP]
	DEFAULT (0) FOR [MA_GRAV_MP]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_GRAVA_VA]
	DEFAULT ('S') FOR [MA_GRAVA_VA]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_NG_ADD]
	DEFAULT (0) FOR [MA_NG_ADD]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_NG_EMP]
	DEFAULT (0) FOR [MA_NG_EMP]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_NG_MP]
	DEFAULT (0) FOR [MA_NG_MP]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MA_NG_USA]
	DEFAULT (0) FOR [MA_NG_USA]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_MAH_FECHACAMB]
	DEFAULT ('01/01/1990') FOR [MAH_FECHACAMB]
GO
ALTER TABLE [dbo].[MAESTROCOSTHIST]
	ADD
	CONSTRAINT [DF_MAESTROCOSTHIST_TV_CODIGO]
	DEFAULT (2) FOR [TV_CODIGO]
GO
