SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IDENTIFICAMAESTRO] (
		[IDEM_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[MA_CODIGO]           [int] NOT NULL,
		[IDE_CODIGO]          [int] NOT NULL,
		[IDEM_NIVEL]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDEM_MOVIMIENTO]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_CODIGO]         [int] NULL,
		[IDEM_DESC]           [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IDEM_DESC2]          [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_CODIGO2]        [int] NULL,
		[IDEM_DESC3]          [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IDED_CODIGO3]        [int] NULL,
		CONSTRAINT [IX_IDENTIFICAMAESTRO]
		UNIQUE
		NONCLUSTERED
		([IDEM_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IDENTIFICAMAESTRO]
	ADD
	CONSTRAINT [PK_IDENTIFICAMAESTRO]
	PRIMARY KEY
	CLUSTERED
	([MA_CODIGO], [IDE_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[IDENTIFICAMAESTRO]
	ADD
	CONSTRAINT [DF_IDENTIFICAMAESTRO_IDEM_DESC]
	DEFAULT ('') FOR [IDEM_DESC]
GO
ALTER TABLE [dbo].[IDENTIFICAMAESTRO]
	ADD
	CONSTRAINT [DF_IDENTIFICAMAESTRO_IDEM_NIVEL]
	DEFAULT ('G') FOR [IDEM_NIVEL]
GO
