SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[QUERY] (
		[QU_DESCRIPCION]     [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[QU_SQL]             [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[QU_READONLY]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[QUERY]
	ADD
	CONSTRAINT [PK_QUERY]
	PRIMARY KEY
	CLUSTERED
	([QU_DESCRIPCION])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[QUERY]
	ADD
	CONSTRAINT [DF_QUERY_QU_READONLY]
	DEFAULT ('N') FOR [QU_READONLY]
GO
