SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SECTOR] (
		[SE_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[SE_CLAVE]      [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SE_DESC]       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_SECTOR]
		UNIQUE
		NONCLUSTERED
		([SE_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SECTOR]
	ADD
	CONSTRAINT [PK_sector]
	PRIMARY KEY
	NONCLUSTERED
	([SE_CLAVE])
	ON [PRIMARY]
GO
