SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PlntExpFormula] (
		[PXF_CODIGO]            [int] NOT NULL,
		[PXS_CODIGO]            [int] NOT NULL,
		[PXF_FORMULANAME]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXF_FORMULASTRING]     [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PXF_DATATYPE]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXF_VERIFICADA]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUM_CODIGO]            [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PlntExpFormula]
	ADD
	CONSTRAINT [PK_PlntExpFormula]
	PRIMARY KEY
	CLUSTERED
	([PXS_CODIGO], [PXF_FORMULANAME])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PlntExpFormula]
	ADD
	CONSTRAINT [DF_PlntExpFormula_BUM_CODIGO]
	DEFAULT (0) FOR [BUM_CODIGO]
GO
ALTER TABLE [dbo].[PlntExpFormula]
	ADD
	CONSTRAINT [DF_PlntExpFormula_PXF_DATATYPE]
	DEFAULT ('0') FOR [PXF_DATATYPE]
GO
ALTER TABLE [dbo].[PlntExpFormula]
	ADD
	CONSTRAINT [DF_PlntExpFormula_PXF_VERIFICADA]
	DEFAULT ('N') FOR [PXF_VERIFICADA]
GO
ALTER TABLE [dbo].[PlntExpFormula]
	ADD
	CONSTRAINT [DF_PlntExpFormula_PXS_CODIGO]
	DEFAULT (0) FOR [PXS_CODIGO]
GO
