SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SUSTITUTO] (
		[TIPO_FACTRANS]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FETR_CODIGO]         [int] NOT NULL,
		[FETR_INDICED]        [int] NOT NULL,
		[FES_SUBENSAMBLE]     [int] NOT NULL,
		[FES_HIJO]            [int] NOT NULL,
		[FES_MAT]             [int] NULL,
		[FES_NOPARTE]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FES_NOMBRE]          [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FES_NAME]            [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FES_INCORPOR]        [decimal](38, 6) NOT NULL,
		[ME_CODIGO]           [int] NULL,
		[FACTCONV]            [decimal](28, 14) NOT NULL,
		[MA_GENERICO]         [int] NULL,
		[ME_GEN]              [int] NULL,
		[TI_CODIGO]           [smallint] NULL,
		[FES_INCORPORGEN]     [decimal](38, 6) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUSTITUTO]
	ADD
	CONSTRAINT [PK_SUSTITUTO]
	PRIMARY KEY
	NONCLUSTERED
	([TIPO_FACTRANS], [FETR_CODIGO], [FETR_INDICED], [FES_SUBENSAMBLE], [FES_HIJO], [FES_NOPARTE])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUSTITUTO]
	ADD
	CONSTRAINT [DF_SUSTITUTO_FACTCONV]
	DEFAULT (1) FOR [FACTCONV]
GO
ALTER TABLE [dbo].[SUSTITUTO]
	ADD
	CONSTRAINT [DF_SUSTITUTO_FES_INCORPOR]
	DEFAULT (1) FOR [FES_INCORPOR]
GO
ALTER TABLE [dbo].[SUSTITUTO]
	ADD
	CONSTRAINT [DF_SUSTITUTO_FES_INCORPORGEN]
	DEFAULT (1) FOR [FES_INCORPORGEN]
GO
