SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPCONTRIBUCION] (
		[PI_CODIGO]             [int] NOT NULL,
		[CON_CODIGO]            [smallint] NOT NULL,
		[PIT_CONTRIBPOR]        [decimal](38, 6) NOT NULL,
		[PIT_CONTRIBAPLICA]     [decimal](38, 6) NOT NULL,
		[PIT_CONTRIBTOTMN]      [decimal](38, 6) NOT NULL,
		[PG_CODIGO]             [smallint] NOT NULL,
		[TTA_CODIGO]            [smallint] NULL,
		[PIT_TIPO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCONTRIBUCION]
	ADD
	CONSTRAINT [PK_PEDIMPCONTRIBUCION]
	PRIMARY KEY
	NONCLUSTERED
	([PI_CODIGO], [CON_CODIGO], [PIT_CONTRIBPOR], [PG_CODIGO], [PIT_TIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPCONTRIBUCION]
	ADD
	CONSTRAINT [DF_PEDIMPCONTRIBUCION_PG_CODIGO]
	DEFAULT (1) FOR [PG_CODIGO]
GO
ALTER TABLE [dbo].[PEDIMPCONTRIBUCION]
	ADD
	CONSTRAINT [DF_PEDIMPCONTRIBUCION_PIT_CONTRIBAPLICA]
	DEFAULT (100) FOR [PIT_CONTRIBAPLICA]
GO
ALTER TABLE [dbo].[PEDIMPCONTRIBUCION]
	ADD
	CONSTRAINT [DF_PEDIMPCONTRIBUCION_PIT_CONTRIBPOR]
	DEFAULT ((-1)) FOR [PIT_CONTRIBPOR]
GO
ALTER TABLE [dbo].[PEDIMPCONTRIBUCION]
	ADD
	CONSTRAINT [DF_PEDIMPCONTRIBUCION_PIT_TIPO]
	DEFAULT ('N') FOR [PIT_TIPO]
GO
