SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURAPERMISO] (
		[IDE_CODIGO]                [int] NOT NULL,
		[CFM_DETALLEPT]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_DETALLEHIJO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_DETALLEIND]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_DETALLEPTFILTRO]       [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_DETALLEHIJOFILTRO]     [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_DETALLEINDFILTRO]      [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_CANTIDAD]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_NOREPETIR]             [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_TITULOPT]              [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFM_SECTOR]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFM_PAISHIJO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFM_CASNO]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFM_FRACCION]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISO]
	ADD
	CONSTRAINT [PK_CONFIGURAPERMISO]
	PRIMARY KEY
	NONCLUSTERED
	([IDE_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISO]
	ADD
	CONSTRAINT [DF_CONFIGURAPERMISO_CFM_CASNO]
	DEFAULT ('N') FOR [CFM_CASNO]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISO]
	ADD
	CONSTRAINT [DF_CONFIGURAPERMISO_CFM_FRACCION]
	DEFAULT ('S') FOR [CFM_FRACCION]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISO]
	ADD
	CONSTRAINT [DF_CONFIGURAPERMISO_CFM_PAISHIJO]
	DEFAULT ('N') FOR [CFM_PAISHIJO]
GO
ALTER TABLE [dbo].[CONFIGURAPERMISO]
	ADD
	CONSTRAINT [DF_CONFIGURAPERMISO_CFM_SECTOR]
	DEFAULT ('N') FOR [CFM_SECTOR]
GO
