SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[LOGO] (
		[CL_CODIGO]     [int] NOT NULL,
		[CL_LOGO]       [image] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOGO]
	ADD
	CONSTRAINT [PK_LOGO]
	PRIMARY KEY
	NONCLUSTERED
	([CL_CODIGO])
	ON [PRIMARY]
GO
