SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[CARGODET] (
		[CARD_INDICED]      [int] IDENTITY(1, 1) NOT NULL,
		[CAR_CODIGO]        [int] NOT NULL,
		[CARD_FECHAINI]     [datetime] NOT NULL,
		[CARD_FECHAFIN]     [datetime] NOT NULL,
		[CARD_VALOR]        [decimal](38, 6) NULL,
		CONSTRAINT [IX_CARGODET]
		UNIQUE
		NONCLUSTERED
		([CARD_INDICED])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARGODET]
	ADD
	CONSTRAINT [PK_CARGODET]
	PRIMARY KEY
	CLUSTERED
	([CAR_CODIGO], [CARD_FECHAINI], [CARD_FECHAFIN])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARGODET]
	ADD
	CONSTRAINT [DF_CARGODET_CARD_FECHAFIN]
	DEFAULT ('01/01/9999') FOR [CARD_FECHAFIN]
GO
