SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PAISARA] (
		[PAR_CODIGO]          [int] IDENTITY(1, 1) NOT NULL,
		[AR_CODIGO]           [int] NOT NULL,
		[PA_CODIGO]           [int] NOT NULL,
		[PAR_BEN]             [decimal](38, 6) NULL,
		[SPI_CODIGO]          [smallint] NOT NULL,
		[PAR_CUOTA]           [smallint] NULL,
		[PAR_IVA]             [decimal](38, 6) NULL,
		[PAR_TLC]             [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PAR_IEPS]            [decimal](38, 6) NULL,
		[PAR_ISAN]            [decimal](38, 6) NULL,
		[AR_TIPOIMPUESTO]     [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PAR_PERINI]          [datetime] NOT NULL,
		[PAR_PERFIN]          [datetime] NOT NULL,
		CONSTRAINT [IX_PAISARA]
		UNIQUE
		NONCLUSTERED
		([PAR_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAISARA]
	ADD
	CONSTRAINT [PK_PAISARA]
	PRIMARY KEY
	NONCLUSTERED
	([AR_CODIGO], [PA_CODIGO], [SPI_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAISARA]
	ADD
	CONSTRAINT [DF_PAISARA_PAR_PERFIN]
	DEFAULT ('1/1/9999') FOR [PAR_PERFIN]
GO
ALTER TABLE [dbo].[PAISARA]
	ADD
	CONSTRAINT [DF_PAISARA_PAR_PERINI]
	DEFAULT ('1/1/1999') FOR [PAR_PERINI]
GO
CREATE CLUSTERED INDEX [IX_PAISARA_1]
	ON [dbo].[PAISARA] ([AR_CODIGO], [PAR_CODIGO])
	ON [PRIMARY]
GO
