SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DEPTOS] (
		[DP_CODIGO]     [smallint] IDENTITY(1, 1) NOT NULL,
		[DP_CORTO]      [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DP_DESC]       [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[US_CODIGO]     [smallint] NULL,
		CONSTRAINT [IX_DEPTOS]
		UNIQUE
		NONCLUSTERED
		([DP_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPTOS]
	ADD
	CONSTRAINT [PK_DEPTOS]
	PRIMARY KEY
	NONCLUSTERED
	([DP_CORTO])
	ON [PRIMARY]
GO
