SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPPAGOVIRT] (
		[PIV_CODIGO]           [int] IDENTITY(1, 1) NOT NULL,
		[PI_CODIGO]            [int] NOT NULL,
		[PG_CODIGO]            [smallint] NOT NULL,
		[BAN_CODIGO]           [smallint] NOT NULL,
		[PIV_DOCUMENTO]        [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PIV_FECHADOC]         [datetime] NULL,
		[PIV_IMPORTEDOC]       [decimal](38, 6) NULL,
		[PIV_SALDODISP]        [decimal](38, 6) NULL,
		[PIV_IMPORTEPAGAR]     [decimal](38, 6) NULL,
		CONSTRAINT [IX_PEDIMPPAGOVIRT]
		UNIQUE
		NONCLUSTERED
		([PIV_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPPAGOVIRT]
	ADD
	CONSTRAINT [PK_PEDIMPPAGOVIRT]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO], [PG_CODIGO], [BAN_CODIGO])
	ON [PRIMARY]
GO
