SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COSTSUBB_247] (
		[CONSECUTIVO]       [int] IDENTITY(1, 1) NOT NULL,
		[CS_CODIGO]         [int] NOT NULL,
		[NOCOLUMNA]         [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TITULO1COL]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TITULO2COL]        [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ET_ENTRY_NO]       [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ET_FEC_ENTRYS]     [datetime] NULL,
		[FE_FOLIO]          [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RATE]              [decimal](38, 6) NOT NULL,
		[VALOR]             [decimal](38, 6) NULL,
		CONSTRAINT [IX_COSTSUBB_247]
		UNIQUE
		NONCLUSTERED
		([CONSECUTIVO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COSTSUBB_247]
	ADD
	CONSTRAINT [DF_COSTSUBB_247_RATE]
	DEFAULT (0) FOR [RATE]
GO
ALTER TABLE [dbo].[COSTSUBB_247]
	ADD
	CONSTRAINT [DF_COSTSUBB_247_TITULO1COL]
	DEFAULT ('') FOR [TITULO1COL]
GO
ALTER TABLE [dbo].[COSTSUBB_247]
	ADD
	CONSTRAINT [DF_COSTSUBB_247_VALOR]
	DEFAULT (0) FOR [VALOR]
GO
