SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TREPORTEDEL] (
		[TRE_NOMBRE_RTM]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TREPORTEDEL]
	ADD
	CONSTRAINT [PK_TREPORTEDEL]
	PRIMARY KEY
	NONCLUSTERED
	([TRE_NOMBRE_RTM])
	ON [PRIMARY]
GO
