SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PlntExpSeccDet] (
		[PXD_CODIGO]             [int] NOT NULL,
		[PXS_CODIGO]             [int] NOT NULL,
		[PXD_MOSTRAR]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXD_TIPOCOL]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXD_TABLA]              [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMF_CODIGO]             [int] NOT NULL,
		[PXF_CODIGO]             [int] NOT NULL,
		[PXD_DETALLE]            [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PXD_OBLIGATORIO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXD_SIZE]               [int] NOT NULL,
		[PXD_AGRUPACION]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXD_CASONULO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PXD_VALOROMISION]       [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PXD_ORDENCOL]           [int] NOT NULL,
		[PXD_PROCSOLO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXD_IDENTSECCION]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXD_ININEWROW]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXD_ACUMULATOTALES]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXD_QUERY]              [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [PK_PlntExpSeccDet]
	PRIMARY KEY
	CLUSTERED
	([PXD_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_IMF_CODIGO]
	DEFAULT (0) FOR [IMF_CODIGO]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_ACUMULATOTALES]
	DEFAULT ('N') FOR [PXD_ACUMULATOTALES]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_AGRUPACION]
	DEFAULT ('A') FOR [PXD_AGRUPACION]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_IDENTSECCION]
	DEFAULT ('N') FOR [PXD_IDENTSECCION]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_ININEWROW]
	DEFAULT ('N') FOR [PXD_ININEWROW]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_MOSTRAR]
	DEFAULT ('S') FOR [PXD_MOSTRAR]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_OBLIGATORIO]
	DEFAULT ('N') FOR [PXD_OBLIGATORIO]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_ORDENCOL]
	DEFAULT (0) FOR [PXD_ORDENCOL]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_PROCSOLO]
	DEFAULT ('N') FOR [PXD_PROCSOLO]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_QUERY]
	DEFAULT ('') FOR [PXD_QUERY]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_SIZE]
	DEFAULT (20) FOR [PXD_SIZE]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_TABLA]
	DEFAULT ('') FOR [PXD_TABLA]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXD_TIPOCOL]
	DEFAULT ('C') FOR [PXD_TIPOCOL]
GO
ALTER TABLE [dbo].[PlntExpSeccDet]
	ADD
	CONSTRAINT [DF_PlntExpSeccDet_PXF_CODIGO]
	DEFAULT (0) FOR [PXF_CODIGO]
GO
