SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[KARDESORDTRABAJO] (
		[KAO_CODIGO]       [int] IDENTITY(1, 1) NOT NULL,
		[ORD_INDICED]      [int] NULL,
		[OTD_INDICED]      [int] NULL,
		[ORD_CANTDESC]     [decimal](38, 6) NULL,
		CONSTRAINT [IX_KARDESORDTRABAJO]
		UNIQUE
		NONCLUSTERED
		([KAO_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
