SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORDTRABAJOEXPLO] (
		[OTE_INDICED]       [int] IDENTITY(1, 1) NOT NULL,
		[OT_CODIGO]         [int] NOT NULL,
		[OTD_INDICED]       [int] NOT NULL,
		[MA_CODIGO]         [int] NOT NULL,
		[OTE_NOPARTE]       [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[OTE_CANT]          [decimal](38, 6) NOT NULL,
		[ME_CODIGO]         [int] NULL,
		[OTE_CANTFALTA]     [decimal](38, 6) NOT NULL,
		[OTE_CANTPO]        [decimal](38, 6) NULL,
		CONSTRAINT [IX_ORDTRABAJOEXPLO]
		UNIQUE
		NONCLUSTERED
		([OTE_INDICED])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDTRABAJOEXPLO]
	ADD
	CONSTRAINT [DF_ORDTRABAJOEXPLO_OTE_CANT]
	DEFAULT (0) FOR [OTE_CANT]
GO
ALTER TABLE [dbo].[ORDTRABAJOEXPLO]
	ADD
	CONSTRAINT [DF_ORDTRABAJOEXPLO_OTE_CANTFALTA]
	DEFAULT (0) FOR [OTE_CANTFALTA]
GO
