SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAESTRO] (
		[MA_CODIGO]                [int] NOT NULL,
		[MA_NOPARTE]               [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_INV_GEN]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TI_CODIGO]                [smallint] NOT NULL,
		[CS_CODIGO]                [smallint] NOT NULL,
		[MA_NOMBRE]                [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_NAME]                  [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_TIP_ENS]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_COM]                   [int] NOT NULL,
		[ME_ALM]                   [int] NULL,
		[EQ_GEN]                   [decimal](28, 14) NOT NULL,
		[EQ_IMPMX]                 [decimal](28, 14) NOT NULL,
		[EQ_ALM]                   [decimal](28, 14) NOT NULL,
		[EQ_EXPMX]                 [decimal](28, 14) NOT NULL,
		[EQ_IMPFO]                 [decimal](28, 14) NOT NULL,
		[EQ_RETRA]                 [decimal](28, 14) NOT NULL,
		[EQ_DESP]                  [decimal](28, 14) NOT NULL,
		[EQ_EXPFO]                 [decimal](28, 14) NOT NULL,
		[PA_ORIGEN]                [int] NOT NULL,
		[PA_PROCEDE]               [int] NOT NULL,
		[MA_CONSTA]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_GENERICO]              [int] NOT NULL,
		[MA_FAMILIA]               [int] NOT NULL,
		[MA_FAMILIAMP]             [int] NOT NULL,
		[MA_EXPENS]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_DEF_TIP]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_PESO_KG]               [decimal](38, 6) NOT NULL,
		[MA_PESO_LB]               [decimal](38, 6) NOT NULL,
		[MA_EST_MAT]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_MARCA]                 [varchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_COLOR]                 [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_MODELO]                [varchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MP_CODIGO]                [smallint] NULL,
		[MA_EMP_PEL]               [int] NOT NULL,
		[MA_IDENTI]                [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AR_IMPMX]                 [int] NULL,
		[AR_EXPMX]                 [int] NULL,
		[AR_IMPFO]                 [int] NULL,
		[AR_RETRA]                 [int] NULL,
		[AR_DESP]                  [int] NULL,
		[AR_EXPFO]                 [int] NULL,
		[CX_CODIGO]                [smallint] NULL,
		[MA_TALLA]                 [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_ESTILO]                [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_DISCHARGE]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SE_CODIGO]                [smallint] NULL,
		[MA_SEC_IMP]               [smallint] NULL,
		[SPI_CODIGO]               [smallint] NULL,
		[MA_REPARA]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_GENERA_EMP]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_EMPAQUE]               [int] NULL,
		[MA_CANTEMP]               [decimal](38, 6) NOT NULL,
		[MA_NOPARTEAUX]            [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CC_CODIGO]                [int] NULL,
		[MA_PELIGROSO]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AR_IMPFOUSA]              [int] NULL,
		[EQ_IMPFOUSA]              [decimal](38, 6) NOT NULL,
		[AR_IMPEMPFOUSA]           [int] NULL,
		[EQ_IMPEMPFOUSA]           [decimal](38, 6) NULL,
		[MA_SEL]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_EMPFACT]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_TIEMPOENSMIN]          [decimal](38, 6) NOT NULL,
		[TEM_CODIGO]               [int] NULL,
		[MA_SERVICIO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_OCULTO]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_TONMAQUINAS]           [decimal](38, 6) NULL,
		[PA_CORTE]                 [int] NULL,
		[MA_TRANS]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_SOLOBOM]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_ESTRUCTURA]            [int] NULL,
		[MA_DESCOSTOARR]           [smallint] NOT NULL,
		[MA_DESCOSTOABA]           [smallint] NOT NULL,
		[MA_ENUSO]                 [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_YEAR]                  [int] NULL,
		[EQ_EXPFO2]                [decimal](28, 14) NOT NULL,
		[LIN_CODIGO]               [int] NULL,
		[MA_ULTIMAMODIF]           [datetime] NULL,
		[MA_MULTIPAIS]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_NAFTATEMP]             [smallint] NOT NULL,
		[AR_DESPMX]                [int] NULL,
		[EQ_DESPMX]                [decimal](38, 6) NOT NULL,
		[AR_IMPMXR8]               [int] NULL,
		[EQ_IMPMXR8]               [decimal](38, 6) NOT NULL,
		[MA_SEC_IMPCERTDEF]        [int] NOT NULL,
		[MA_NOMBREDESP]            [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MA_NAMEDESP]              [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MA_RETRABAJO]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_COSTOUNITLC]           [decimal](38, 6) NOT NULL,
		[MA_COSTOVATLC]            [decimal](38, 6) NOT NULL,
		[BST_TIPOCOSTO]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MA_POR_DESP]              [decimal](38, 6) NOT NULL,
		[MA_POR_MERMA]             [decimal](38, 6) NOT NULL,
		[MA_USO_ENANALISIS]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MA_NOPARTEDEFINITIVO]     [smallint] NOT NULL,
		[MA_HOJASEGURIDAD]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_MAESTRO]
		UNIQUE
		NONCLUSTERED
		([MA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [PK_MAESTRO]
	PRIMARY KEY
	NONCLUSTERED
	([MA_NOPARTE], [MA_INV_GEN], [MA_NOPARTEAUX])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_CS_CODIGO]
	DEFAULT (8) FOR [CS_CODIGO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_ALM]
	DEFAULT (1) FOR [EQ_ALM]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_DESP]
	DEFAULT (1) FOR [EQ_DESP]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_DESPMX]
	DEFAULT (1) FOR [EQ_DESPMX]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_EXPFO]
	DEFAULT (1) FOR [EQ_EXPFO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_EXPFO2]
	DEFAULT (1) FOR [EQ_EXPFO2]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_EXPMX]
	DEFAULT (1) FOR [EQ_EXPMX]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_GEN]
	DEFAULT (1) FOR [EQ_GEN]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_IMPFO]
	DEFAULT (1) FOR [EQ_IMPFO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_IMPFOUSA]
	DEFAULT (1) FOR [EQ_IMPFOUSA]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_IMPMX]
	DEFAULT (1) FOR [EQ_IMPMX]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_IMPMXR8]
	DEFAULT (1) FOR [EQ_IMPMXR8]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_EQ_RETRA]
	DEFAULT (1) FOR [EQ_RETRA]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_CANTEMP]
	DEFAULT (0) FOR [MA_CANTEMP]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_COLOR]
	DEFAULT ('') FOR [MA_COLOR]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_CONSTA]
	DEFAULT ('N') FOR [MA_CONSTA]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_COSTOUNITLC]
	DEFAULT (0) FOR [MA_COSTOUNITLC]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_COSTOVATLC]
	DEFAULT (0) FOR [MA_COSTOVATLC]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_DEF_TIP]
	DEFAULT ('G') FOR [MA_DEF_TIP]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_DESCOSTOABA]
	DEFAULT (10) FOR [MA_DESCOSTOABA]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_DESCOSTOARR]
	DEFAULT (10) FOR [MA_DESCOSTOARR]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_DISCHARGE]
	DEFAULT ('S') FOR [MA_DISCHARGE]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_EMP_PEL]
	DEFAULT (0) FOR [MA_EMP_PEL]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_EMPFACT]
	DEFAULT ('S') FOR [MA_EMPFACT]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_ENUSO]
	DEFAULT ('S') FOR [MA_ENUSO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_EST_MAT]
	DEFAULT ('A') FOR [MA_EST_MAT]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_ESTILO]
	DEFAULT ('') FOR [MA_ESTILO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_EXPENS]
	DEFAULT ('N') FOR [MA_EXPENS]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_FAMILIA]
	DEFAULT (0) FOR [MA_FAMILIA]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_FAMILIAMP]
	DEFAULT (0) FOR [MA_FAMILIAMP]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_GENERA_EMP]
	DEFAULT ('D') FOR [MA_GENERA_EMP]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_GENERICO]
	DEFAULT (0) FOR [MA_GENERICO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_HOJASEGURIDAD]
	DEFAULT ('N') FOR [MA_HOJASEGURIDAD]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_IDENTI]
	DEFAULT ('') FOR [MA_IDENTI]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_INV_GEN]
	DEFAULT ('I') FOR [MA_INV_GEN]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_MARCA]
	DEFAULT ('') FOR [MA_MARCA]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_MODELO]
	DEFAULT ('') FOR [MA_MODELO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_MULTIPAIS]
	DEFAULT ('N') FOR [MA_MULTIPAIS]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_NAFTATEMP]
	DEFAULT (0) FOR [MA_NAFTATEMP]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_NOPARTEAUX]
	DEFAULT ('') FOR [MA_NOPARTEAUX]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_NOPARTEDEFINITIVO]
	DEFAULT (0) FOR [MA_NOPARTEDEFINITIVO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_OCULTO]
	DEFAULT ('N') FOR [MA_OCULTO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_PELIGROSO]
	DEFAULT ('N') FOR [MA_PELIGROSO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_PESO_KG]
	DEFAULT (0) FOR [MA_PESO_KG]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_PESO_LB]
	DEFAULT (0) FOR [MA_PESO_LB]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_POR_DESP]
	DEFAULT (0) FOR [MA_POR_DESP]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_POR_MERMA]
	DEFAULT (0) FOR [MA_POR_MERMA]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_REPARA]
	DEFAULT ('N') FOR [MA_REPARA]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_RETRABAJO]
	DEFAULT ('N') FOR [MA_RETRABAJO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_SEC_IMPCERTDEF]
	DEFAULT (0) FOR [MA_SEC_IMPCERTDEF]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_SEL]
	DEFAULT ('N') FOR [MA_SEL]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_SERVICIO]
	DEFAULT ('N') FOR [MA_SERVICIO]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_SOLOBOM]
	DEFAULT ('N') FOR [MA_SOLOBOM]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_TALLA]
	DEFAULT ('') FOR [MA_TALLA]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_TIEMPOENSMIN]
	DEFAULT (0) FOR [MA_TIEMPOENSMIN]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_TIP_ENS]
	DEFAULT ('C') FOR [MA_TIP_ENS]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_TRANS]
	DEFAULT ('N') FOR [MA_TRANS]
GO
ALTER TABLE [dbo].[MAESTRO]
	ADD
	CONSTRAINT [DF_MAESTRO_MA_USO_ENANALISIS]
	DEFAULT ('S') FOR [MA_USO_ENANALISIS]
GO
CREATE CLUSTERED INDEX [IX_MAESTRO_1]
	ON [dbo].[MAESTRO] ([MA_CODIGO], [MA_NOPARTE])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_10]
	ON [dbo].[MAESTRO] ([ME_COM])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_11]
	ON [dbo].[MAESTRO] ([MA_INV_GEN], [MA_OCULTO], [MA_ENUSO], [MA_NOPARTE], [MA_CODIGO], [TI_CODIGO], [MA_NOMBRE], [MA_NAME], [MA_NOPARTEAUX])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_12]
	ON [dbo].[MAESTRO] ([MA_CODIGO], [MA_FAMILIAMP])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_13]
	ON [dbo].[MAESTRO] ([MA_CODIGO], [MA_GENERICO], [MA_FAMILIAMP])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_14]
	ON [dbo].[MAESTRO] ([MA_INV_GEN], [TI_CODIGO], [MA_EST_MAT], [MA_EMPFACT], [MA_OCULTO], [MA_CODIGO], [MA_NOPARTE], [MA_NOMBRE], [MA_PESO_KG], [MA_CANTEMP], [MA_NOPARTEAUX], [TEM_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_15]
	ON [dbo].[MAESTRO] ([MA_CODIGO], [TI_CODIGO], [MA_NOPARTE], [MA_NOPARTEAUX])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_16]
	ON [dbo].[MAESTRO] ([MA_INV_GEN], [TI_CODIGO], [MA_CODIGO], [MA_NOPARTE], [MA_NOMBRE], [MA_GENERA_EMP], [MA_NOPARTEAUX])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_17]
	ON [dbo].[MAESTRO] ([MA_EST_MAT], [MA_INV_GEN], [MA_EMPFACT], [MA_OCULTO], [TI_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_2]
	ON [dbo].[MAESTRO] ([MA_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_3]
	ON [dbo].[MAESTRO] ([TI_CODIGO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_4]
	ON [dbo].[MAESTRO] ([MA_GENERICO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_5]
	ON [dbo].[MAESTRO] ([PA_ORIGEN])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_6]
	ON [dbo].[MAESTRO] ([AR_IMPMX])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_7]
	ON [dbo].[MAESTRO] ([AR_EXPMX])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_8]
	ON [dbo].[MAESTRO] ([AR_IMPFO])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_9]
	ON [dbo].[MAESTRO] ([AR_DESP])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MAESTRO_BOM]
	ON [dbo].[MAESTRO] ([MA_NOPARTE], [MA_NOPARTEAUX], [MA_NOMBRE], [TI_CODIGO], [MA_CODIGO], [MA_INV_GEN], [CS_CODIGO])
	ON [PRIMARY]
GO
