SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[IMPLEMENTACONTRIB] (
		[PI_CODIGOIMP]          [int] NOT NULL,
		[CON_CODIGO]            [smallint] NOT NULL,
		[PIT_CONTRIBPOR]        [decimal](38, 6) NULL,
		[PIT_CONTRIBAPLICA]     [decimal](38, 6) NULL,
		[PIT_CONTRIBTOTMN]      [decimal](38, 6) NOT NULL,
		[PG_CODIGO]             [smallint] NOT NULL,
		[TTA_CODIGO]            [smallint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPLEMENTACONTRIB]
	ADD
	CONSTRAINT [PK_IMPLEMENTACONTRIB]
	PRIMARY KEY
	NONCLUSTERED
	([PI_CODIGOIMP], [CON_CODIGO], [PIT_CONTRIBTOTMN])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPLEMENTACONTRIB]
	ADD
	CONSTRAINT [DF_IMPLEMENTACONTRIB_PG_CODIGO]
	DEFAULT (1) FOR [PG_CODIGO]
GO
ALTER TABLE [dbo].[IMPLEMENTACONTRIB]
	ADD
	CONSTRAINT [DF_IMPLEMENTACONTRIB_PIT_CONTRIBAPLICA]
	DEFAULT (100) FOR [PIT_CONTRIBAPLICA]
GO
