SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MEDIDA] (
		[ME_CODIGO]         [int] IDENTITY(1, 1) NOT NULL,
		[ME_CORTO]          [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_CORTOE]         [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ME_CLA_PED]        [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_CLA_ISO]        [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_CLA_SCHEDB]     [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_NOMBRE]         [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_NAME]           [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ME_IDSICEX]        [int] NULL,
		[ME_DESCSICEX]      [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_MEDIDA]
		UNIQUE
		NONCLUSTERED
		([ME_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDIDA]
	ADD
	CONSTRAINT [PK_MEDIDA]
	PRIMARY KEY
	NONCLUSTERED
	([ME_CORTO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDIDA]
	ADD
	CONSTRAINT [DF_MEDIDA_ME_CLA_ISO]
	DEFAULT ('') FOR [ME_CLA_ISO]
GO
ALTER TABLE [dbo].[MEDIDA]
	ADD
	CONSTRAINT [DF_MEDIDA_ME_CLA_PED]
	DEFAULT ('') FOR [ME_CLA_PED]
GO
ALTER TABLE [dbo].[MEDIDA]
	ADD
	CONSTRAINT [DF_MEDIDA_ME_CLA_SCHEDB]
	DEFAULT ('') FOR [ME_CLA_SCHEDB]
GO
CREATE CLUSTERED INDEX [IX_MEDIDA_1]
	ON [dbo].[MEDIDA] ([ME_CODIGO], [ME_CORTO])
	ON [PRIMARY]
GO
