SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGFOLIOARAN] (
		[PA_CODIGO]       [int] NOT NULL,
		[CFA_TIPO]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFA_MASK]        [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CFA_USRMASK]     [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CFA_SIZE]        [smallint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGFOLIOARAN]
	ADD
	CONSTRAINT [PK_CONFIGFOLIOARAN]
	PRIMARY KEY
	NONCLUSTERED
	([PA_CODIGO], [CFA_TIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGFOLIOARAN]
	ADD
	CONSTRAINT [DF_CONFIGFOLIOARAN_CFA_SIZE]
	DEFAULT (20) FOR [CFA_SIZE]
GO
