SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PEDIMPSAAICONFIG] (
		[PI_CODIGO]                   [int] NOT NULL,
		[PICF_APLICANOMS]             [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_SAAIDETDIVFACT]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_SAAIDIVCOSGEN]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_SAAIDIVPA]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_SAAIDIVDESC]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_AGRUPASAAISEC]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_IVAPROPORCIONAL]        [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_PEDIMPSINAGRUP]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_SAAIDETDIVPO]           [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_PEDIMPSAAISINAGRUP]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICF_PEDIMPSECFACT]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [PK_PEDIMPSAAICONFIG]
	PRIMARY KEY
	CLUSTERED
	([PI_CODIGO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPCOFIGSAAI_PICF_AGRUPASAAISEC]
	DEFAULT ('N') FOR [PICF_AGRUPASAAISEC]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPCOFIGSAAI_PICF_APLICANOMS]
	DEFAULT ('S') FOR [PICF_APLICANOMS]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPCOFIGSAAI_PICF_IVAPROPORCIONAL]
	DEFAULT ('S') FOR [PICF_IVAPROPORCIONAL]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPCOFIGSAAI_PICF_SAAIDETDIVFACT]
	DEFAULT ('N') FOR [PICF_SAAIDETDIVFACT]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPCOFIGSAAI_PICF_SAAIDIVCOSGEN]
	DEFAULT ('N') FOR [PICF_SAAIDIVCOSGEN]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPCOFIGSAAI_PICF_SAAIDIVDESC]
	DEFAULT ('N') FOR [PICF_SAAIDIVDESC]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPCOFIGSAAI_PICF_SAAIDIVPA]
	DEFAULT ('N') FOR [PICF_SAAIDIVPA]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPSAAICONFIG_PIC_PEDIMPSAAISINAGRUP]
	DEFAULT ('N') FOR [PICF_PEDIMPSAAISINAGRUP]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPSAAICONFIG_PICF_PEDIMPSECFACT]
	DEFAULT ('N') FOR [PICF_PEDIMPSECFACT]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPSAAICONFIG_PICF_PEDIMPSINAGRUP]
	DEFAULT ('N') FOR [PICF_PEDIMPSINAGRUP]
GO
ALTER TABLE [dbo].[PEDIMPSAAICONFIG]
	ADD
	CONSTRAINT [DF_PEDIMPSAAICONFIG_PICF_SAAIDETDIVPO]
	DEFAULT ('N') FOR [PICF_SAAIDETDIVPO]
GO
