SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[APROBACION] (
		[AP_CODIGO]       [int] IDENTITY(1, 1) NOT NULL,
		[REQ_CODIGO]      [int] NOT NULL,
		[DP_CODIGO]       [int] NULL,
		[AP_APROBADA]     [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[US_CODIGO]       [int] NULL,
		CONSTRAINT [IX_APROBACION]
		UNIQUE
		NONCLUSTERED
		([AP_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APROBACION]
	ADD
	CONSTRAINT [DF_APROBACION_AP_APROBADA]
	DEFAULT ('N') FOR [AP_APROBADA]
GO
