SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TSERVICIO] (
		[SER_CODIGO]      [smallint] IDENTITY(1, 1) NOT NULL,
		[SER_DESCRIP]     [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_TSERVICIO]
		UNIQUE
		NONCLUSTERED
		([SER_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TSERVICIO]
	ADD
	CONSTRAINT [PK_TSERVICIO]
	PRIMARY KEY
	CLUSTERED
	([SER_DESCRIP])
	ON [PRIMARY]
GO
