SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[IMPORTTABLESDETCONT] (
		[IMR_CODIGO]            [int] IDENTITY(1, 1) NOT NULL,
		[IMR_TABLA]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMR_DESCTABLA]         [varchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMR_TABLEDESC]         [varchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMR_TIPO]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMR_TMASTER]           [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMR_FIELDCONSEC]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMR_IDENTITY]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMR_PREFIJO]           [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMR_PRIMKEYFIELDS]     [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMR_OBLIGATORIO]       [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMR_LINKQUERY]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_IMPORTTABLESDETCONT]
		UNIQUE
		NONCLUSTERED
		([IMR_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTTABLESDETCONT]
	ADD
	CONSTRAINT [PK_IMPORTTABLESDETCONT]
	PRIMARY KEY
	CLUSTERED
	([IMR_TABLA], [IMR_TMASTER])
	ON [PRIMARY]
GO
