SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURATEMBARQUE] (
		[TQ_CODIGO]     [smallint] NOT NULL,
		[CFQ_TIPO]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURATEMBARQUE]
	ADD
	CONSTRAINT [PK_CONFIGURATEMBARQUE]
	PRIMARY KEY
	NONCLUSTERED
	([TQ_CODIGO])
	ON [PRIMARY]
GO
