SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[FACTCONSTQ] (
		[FC_CODIGO]     [int] NOT NULL,
		[TQ_EMBIMP]     [smallint] NOT NULL
) ON [PRIMARY]
GO
