SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TACTIVIDAD] (
		[TA_CODIGO]          [int] IDENTITY(1, 1) NOT NULL,
		[TA_CORTO]           [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TA_NOMBRE]          [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TA_NAME]            [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TA_RANGOMOVMES]     [varchar](53) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_TACTIVIDAD]
		UNIQUE
		NONCLUSTERED
		([TA_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TACTIVIDAD]
	ADD
	CONSTRAINT [PK_TACTIVIDAD]
	PRIMARY KEY
	NONCLUSTERED
	([TA_CORTO])
	ON [PRIMARY]
GO
