SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTEXPDETDEF] (
		[FED_INDICED]      [int] NOT NULL,
		[FE_CODIGO]        [int] NOT NULL,
		[FED_DEFTXT1]      [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_DEFTXT2]      [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_DEFTXT3]      [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_DEFBOL1]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_DEFBOL2]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_DEFBOL3]      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FED_DEFNO1]       [int] NOT NULL,
		[FED_DEFNO2]       [int] NOT NULL,
		[FED_DEFNO3]       [int] NOT NULL,
		[FED_DEFDATE1]     [datetime] NULL,
		[FED_DEFDATE2]     [datetime] NULL,
		[FED_DEFDATE3]     [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [PK_FACTEXPDETDEF]
	PRIMARY KEY
	CLUSTERED
	([FED_INDICED])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDETDEF_FED_DEFBOL1]
	DEFAULT ('N') FOR [FED_DEFBOL1]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDETDEF_FED_DEFBOL2]
	DEFAULT ('N') FOR [FED_DEFBOL2]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDETDEF_FED_DEFBOL3]
	DEFAULT ('N') FOR [FED_DEFBOL3]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDETDEF_FED_DEFNO1]
	DEFAULT (0) FOR [FED_DEFNO1]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDETDEF_FED_DEFNO2]
	DEFAULT (0) FOR [FED_DEFNO2]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDETDEF_FED_DEFNO3]
	DEFAULT (0) FOR [FED_DEFNO3]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDETDEF_FED_DEFTXT1]
	DEFAULT ('') FOR [FED_DEFTXT1]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDETDEF_FED_DEFTXT2]
	DEFAULT ('') FOR [FED_DEFTXT2]
GO
ALTER TABLE [dbo].[FACTEXPDETDEF]
	ADD
	CONSTRAINT [DF_FACTEXPDETDEF_FED_DEFTXT3]
	DEFAULT ('') FOR [FED_DEFTXT3]
GO
