SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FACTIMPDOCREVISA] (
		[FIR_CODIGO]            [int] IDENTITY(1, 1) NOT NULL,
		[FI_CODIGO]             [int] NOT NULL,
		[FIR_DOCUMENTO]         [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIR_OBSERVACIONES]     [varchar](1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FIR_REQUERIDO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FIR_FECHA]             [datetime] NULL,
		[US_CODIGO]             [smallint] NULL,
		CONSTRAINT [IX_FACTIMPDOCREVISA]
		UNIQUE
		NONCLUSTERED
		([FIR_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FACTIMPDOCREVISA]
	ADD
	CONSTRAINT [PK_FACTIMPDOCREVISA]
	PRIMARY KEY
	CLUSTERED
	([FI_CODIGO], [FIR_DOCUMENTO])
	ON [PRIMARY]
GO
