SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENCIACONEXION] (
		[AGC_CODIGO]           [int] NOT NULL,
		[AG_CODIGO]            [int] NOT NULL,
		[AGC_NOMBRE]           [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGC_FTP]              [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGC_ARCHIVO]          [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGC_ORDENDEFAULT]     [smallint] NULL,
		[AGC_RUTALOCAL]        [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGC_RUTAREMOTA]       [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGC_LAYOUT]           [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGC_USERNAME]         [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AGC_PASSWORD]         [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [IX_AGENCIACONEXION]
		UNIQUE
		NONCLUSTERED
		([AGC_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIACONEXION]
	ADD
	CONSTRAINT [PK_AGENCIACONEXION]
	PRIMARY KEY
	NONCLUSTERED
	([AG_CODIGO])
	ON [PRIMARY]
GO
