SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FAST] (
		[FST_CODIGO]              [int] IDENTITY(1, 1) NOT NULL,
		[FST_FOLIO]               [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FST_FECHA]               [datetime] NULL,
		[US_CODIGO]               [int] NULL,
		[FST_TIPO]                [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FST_NUMENVIO]            [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FST_CHECKDIGIT]          [int] NULL,
		[CT_CODIGO]               [int] NULL,
		[FST_PREVIOENTRY]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ETI_REPETICIONES]        [int] NOT NULL,
		[ETI_POSICIONINICIAL]     [int] NOT NULL,
		[FST_LEYENDA]             [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [IX_FAST]
		UNIQUE
		NONCLUSTERED
		([FST_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAST]
	ADD
	CONSTRAINT [PK_FAST]
	PRIMARY KEY
	CLUSTERED
	([FST_FOLIO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAST]
	ADD
	CONSTRAINT [DF_FAST_ETI_POSICIONINICIAL]
	DEFAULT (1) FOR [ETI_POSICIONINICIAL]
GO
ALTER TABLE [dbo].[FAST]
	ADD
	CONSTRAINT [DF_FAST_ETI_REPETICIONES]
	DEFAULT (1) FOR [ETI_REPETICIONES]
GO
ALTER TABLE [dbo].[FAST]
	ADD
	CONSTRAINT [DF_FAST_FST_PREVIOENTRY]
	DEFAULT ('N') FOR [FST_PREVIOENTRY]
GO
ALTER TABLE [dbo].[FAST]
	ADD
	CONSTRAINT [DF_FAST_FST_TIPO]
	DEFAULT ('F') FOR [FST_TIPO]
GO
