SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TURNO] (
		[TUR_CODIGO]         [smallint] IDENTITY(1, 1) NOT NULL,
		[TUR_DESCRIP]        [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TUR_HORAS]          [decimal](38, 6) NOT NULL,
		[TUR_NOPERSONAS]     [int] NULL,
		CONSTRAINT [IX_TURNO]
		UNIQUE
		NONCLUSTERED
		([TUR_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TURNO]
	ADD
	CONSTRAINT [PK_TURNO]
	PRIMARY KEY
	NONCLUSTERED
	([TUR_DESCRIP])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[TURNO]
	ADD
	CONSTRAINT [DF_TURNO_TUR_HORAS]
	DEFAULT (8) FOR [TUR_HORAS]
GO
