SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FORMULASAGREGADAS] (
		[PXS_CODIGO]            [int] NOT NULL,
		[PXF_FORMULA]           [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PXF_FORMULASTRING]     [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FORMULASAGREGADAS]
	ADD
	CONSTRAINT [PK_FORMULASAGREGRADAS]
	PRIMARY KEY
	CLUSTERED
	([PXF_FORMULA])
	ON [PRIMARY]
GO
