SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[CONTRIBUCIONRANGO] (
		[COR_CODIGO]          [int] IDENTITY(1, 1) NOT NULL,
		[CON_CODIGO]          [int] NOT NULL,
		[COR_LIMINFERIOR]     [decimal](38, 6) NOT NULL,
		[COR_LIMSUPERIOR]     [decimal](38, 6) NOT NULL,
		[COR_CUOTAFIJA]       [decimal](38, 6) NULL,
		[COR_PORCENT]         [decimal](38, 6) NULL,
		[COR_PERINI]          [datetime] NOT NULL,
		[COR_PERFIN]          [datetime] NOT NULL,
		CONSTRAINT [IX_CONTRIBUCIONRANGO]
		UNIQUE
		NONCLUSTERED
		([COR_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRIBUCIONRANGO]
	ADD
	CONSTRAINT [PK_CONTRIBUCIONRANGO]
	PRIMARY KEY
	CLUSTERED
	([CON_CODIGO], [COR_LIMINFERIOR], [COR_LIMSUPERIOR], [COR_PERINI], [COR_PERFIN])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONTRIBUCIONRANGO]
	ADD
	CONSTRAINT [DF_CONTRIBUCIONRANGO_COR_PERFIN]
	DEFAULT ('01/01/9999') FOR [COR_PERFIN]
GO
ALTER TABLE [dbo].[CONTRIBUCIONRANGO]
	ADD
	CONSTRAINT [DF_CONTRIBUCIONRANGO_COR_PERINI]
	DEFAULT ('01/01/1990') FOR [COR_PERINI]
GO
