SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AGENCIACONCEPTO] (
		[COP_CODIGO]       [smallint] IDENTITY(1, 1) NOT NULL,
		[COP_NOMBRE]       [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[COP_NAME]         [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[COP_TIPO]         [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[COP_PAGOFIJO]     [decimal](38, 6) NULL,
		[MO_CODIGO]        [int] NULL,
		CONSTRAINT [IX_AGENCIACONCEPTO]
		UNIQUE
		NONCLUSTERED
		([COP_CODIGO])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AGENCIACONCEPTO]
	ADD
	CONSTRAINT [PK_AGENCIACONCEPTO]
	PRIMARY KEY
	CLUSTERED
	([COP_NOMBRE])
	ON [PRIMARY]
GO
