SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CTRANSPORPAGDET] (
		[CTP_CODIGO]          [int] NOT NULL,
		[CTPD_INDICED]        [int] NOT NULL,
		[FI_CODIGO]           [int] NOT NULL,
		[FI_FOLIO]            [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CTPD_FACTTIPO]       [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CTPD_CHOFER]         [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CTPD_KILOGRAMOS]     [decimal](38, 6) NOT NULL,
		[CTPD_PRECIOTOT]      [decimal](38, 6) NULL,
		[CTPD_ANTICIPO]       [decimal](38, 6) NULL,
		CONSTRAINT [IX_CTRANSPORPAGDET]
		UNIQUE
		NONCLUSTERED
		([CTPD_INDICED])
		ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTRANSPORPAGDET]
	ADD
	CONSTRAINT [PK_CTRANSPORPAGDET]
	PRIMARY KEY
	CLUSTERED
	([FI_CODIGO], [CTPD_FACTTIPO])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[CTRANSPORPAGDET]
	ADD
	CONSTRAINT [DF_CTRANSPORPAGDET_CTPD_ANTICIPO]
	DEFAULT (0) FOR [CTPD_ANTICIPO]
GO
ALTER TABLE [dbo].[CTRANSPORPAGDET]
	ADD
	CONSTRAINT [DF_CTRANSPORPAGDET_CTPD_FACTTIPO]
	DEFAULT ('N') FOR [CTPD_FACTTIPO]
GO
ALTER TABLE [dbo].[CTRANSPORPAGDET]
	ADD
	CONSTRAINT [DF_CTRANSPORPAGDET_CTPD_KILOGRAMOS]
	DEFAULT (1) FOR [CTPD_KILOGRAMOS]
GO
