SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONFIGURACLAVEPED] (
		[CP_CODIGO]     [smallint] NOT NULL,
		[CCP_TIPO]      [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONFIGURACLAVEPED]
	ADD
	CONSTRAINT [PK_CONFIGURACLAVEPED]
	PRIMARY KEY
	NONCLUSTERED
	([CP_CODIGO])
	ON [PRIMARY]
GO
