SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO































CREATE PROCEDURE [dbo].[SP_ACTUALIZAMA_NAFTATEMP]   as



ALTER TABLE MAESTRO DISABLE trigger Update_Maestro 

	
	UPDATE MAESTRO
	SET MA_NAFTATEMP=0
	FROM         MAESTRO 
	WHERE MA_NAFTATEMP<>0 OR MA_NAFTATEMP IS NULL
	
	
	UPDATE MAESTRO
	SET MA_NAFTATEMP=1 
	FROM         MAESTRO 
	WHERE  maestro.MA_OCULTO = 'N' AND MA_INV_GEN='I'
	AND MAESTRO.TI_CODIGO IN (select ti_codigo from configuratipo where cft_tipo='P' or cft_tipo='S')
	AND MAESTRO.MA_CODIGO in (SELECT NAFTA.MA_CODIGO FROM NAFTA INNER JOIN SPI ON NAFTA.SPI_CODIGO = SPI.SPI_CODIGO	WHERE SPI.SPI_CLAVE = 'NAFTA' and NFT_CALIFICO='S'
		         AND NAFTA.MA_CODIGO=MAESTRO.MA_CODIGO AND NFT_PERINI<=GETDATE() AND NFT_PERFIN>=GETDATE()) 
	AND (MA_NAFTATEMP<>1 OR MA_NAFTATEMP IS NULL)
	
	UPDATE MAESTRO
	SET MA_NAFTATEMP=1
	FROM MAESTRO LEFT OUTER JOIN ARANCEL ON MAESTRO.AR_EXPMX = ARANCEL.AR_CODIGO
	WHERE  MAESTRO.MA_OCULTO = 'N' AND MA_INV_GEN='I'
	and MAESTRO.TI_CODIGO NOT IN (select ti_codigo from configuratipo where cft_tipo='P' or cft_tipo='S')
	AND MAESTRO.MA_CODIGO in (SELECT CERTORIGMPDET.MA_CODIGO
			FROM  CERTORIGMPDET INNER JOIN CERTORIGMP ON CERTORIGMPDET.CMP_CODIGO = CERTORIGMP.CMP_CODIGO 
			WHERE LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCION,'.',''),6)=LEFT(REPLACE(ARANCEL.AR_FRACCION,'.',''),6) AND  CERTORIGMP.SPI_CODIGO IN (SELECT spi_codigo FROM spi  WHERE spi_clave = 'nafta')
			AND CERTORIGMPDET.MA_CODIGO=MAESTRO.MA_CODIGO AND CERTORIGMP.CMP_ESTATUS='V' AND  CERTORIGMP.CMP_IFECHA<=GETDATE() AND CERTORIGMP.CMP_FECHATRANS>=GETDATE())
	AND (MA_NAFTATEMP<>1 OR MA_NAFTATEMP IS NULL)
	
	UPDATE MAESTRO
	SET MA_NAFTATEMP=1
	FROM         MAESTRO 
	WHERE  maestro.MA_OCULTO = 'N' AND MA_INV_GEN='I'
	and MAESTRO.TI_CODIGO NOT IN (select ti_codigo from configuratipo where cft_tipo='P' or cft_tipo='S')
	AND MAESTRO.PA_ORIGEN IN (SELECT CF_PAIS_USA FROM CONFIGURACION) AND MAESTRO.MA_DEF_TIP='P' 
	AND (MA_NAFTATEMP<>1 OR MA_NAFTATEMP IS NULL)



ALTER TABLE MAESTRO ENABLE trigger Update_Maestro






























GO
