SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO































CREATE PROCEDURE [dbo].[SP_temp_13031]   as

DECLARE  @tco_manufactura INT, @SPI_CODIGO INT

select  @tco_manufactura=TCO_MANUFACTURA from configuracion
SELECT @spi_codigo=SPI_CODIGO FROM SPI WHERE SPI_CLAVE='NAFTA'


	UPDATE IMPORTSPECDET
	SET     IMPORTSPECDET.IMS_CBFORMA= IMPORTSPEC.IMS_CBFORMA
	FROM         IMPORTSPEC INNER JOIN
	                      IMPORTSPECDET ON IMPORTSPEC.IMS_CODIGO = IMPORTSPECDET.IMS_CODIGO
	
	
	UPDATE IMPORTSPECSELECT
	SET     IMPORTSPECSELECT.IMS_CBFORMA= IMPORTSPEC.IMS_CBFORMA
	FROM         IMPORTSPEC INNER JOIN
	                      IMPORTSPECSELECT ON IMPORTSPEC.IMS_CODIGO = IMPORTSPECSELECT.IMS_CODIGO


	UPDATE    NAFTA
	SET              NFT_CALIFICO = 'S'
	WHERE     (NFT_CALIFICO IS NULL)

	/* CALCULOS NAFTA */

	UPDATE NAFTA
	SET NFT_COSTO =(SELECT MA_COSTO FROM MAESTROCOST 
			WHERE SPI_CODIGO = @spi_codigo AND TCO_CODIGO = @tco_manufactura AND MA_PERINI <= CONVERT(varchar(11), GETDATE(), 101)
			AND MA_PERFIN >= CONVERT(varchar(11), GETDATE(), 101) AND MAESTROCOST.MA_CODIGO=NAFTA.MA_CODIGO),
	NFT_PRECIO = isnull((select mc_precio from maestrocliente where mc_vtr='S' and maestrocliente.ma_codigo=NAFTA.MA_CODIGO),0)


	UPDATE NAFTA
	SET NFT_VCRXVT=round(((NFT_PRECIO -  (SELECT SUM(CLASIFICATLC.BST_MATNOORIG) FROM CLASIFICATLC 
		WHERE CLASIFICATLC.BST_DISCH = 'S' AND CLASIFICATLC.NFT_CODIGO = NAFTA.NFT_CODIGO)) / NFT_PRECIO)* 100,2)
	WHERE NFT_PRECIO>0


	UPDATE NAFTA
	SET NFT_VCRXCN=round(((NFT_COSTO - isnull(NFT_COSTOSRESTAR,0)) - (SELECT SUM(CLASIFICATLC.BST_MATNOORIG) FROM CLASIFICATLC 
	WHERE CLASIFICATLC.BST_DISCH = 'S' AND CLASIFICATLC.NFT_CODIGO = NAFTA.NFT_CODIGO)) / ((NFT_COSTO - isnull(NFT_COSTOSRESTAR,0)) * 100),2)
	WHERE NFT_COSTO - isnull(NFT_COSTOSRESTAR,0)>0


	UPDATE NAFTA
	SET NFT_COSTOTOTALPT = round((select VTLCCOSTOTOTAL.COSTOTOTAL FROM VTLCCOSTOTOTAL where VTLCCOSTOTOTAL.nft_codigo = NAFTA.NFT_CODIGO),6)
	
	
	UPDATE NAFTA
	SET NFT_MINIMIS = round(100-((select vtlcanalisisfrac.COSTO FROM vtlcanalisisfrac where vtlcanalisisfrac.nft_codigo = NAFTA.NFT_CODIGO)*100)
	/NFT_COSTOTOTALPT,2)


	UPDATE NAFTA
	SET NFT_MINIMIS = 0
	WHERE NFT_MINIMIS < 0






























GO
