SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_COPIA_REG_FACTEXP] (@FUENTE INT,@DESTINO INT)  as

SET NOCOUNT ON 
declare @FED_INDICED INT, @MA_CODIGO INT, @FED_NOMBRE VARCHAR(150), @FED_NOPARTE VARCHAR(30), @FED_NAME VARCHAR(150), @ME_CODIGO INT, @FED_CANT decimal(38,6), @FED_GRA_MP decimal(38,6), 
                      @FED_GRA_MO decimal(38,6), @FED_GRA_EMP decimal(38,6), @FED_GRA_ADD decimal(38,6), @FED_GRA_GI decimal(38,6), @FED_GRA_GI_MX decimal(38,6), @FED_NG_MP decimal(38,6), @FED_NG_EMP decimal(38,6), @FED_NG_ADD decimal(38,6), 
                      @FED_COS_UNI decimal(38,6), @FED_COS_TOT decimal(38,6), @FED_PES_UNI decimal(38,6), @FED_PES_NET decimal(38,6), @FED_PES_BRU decimal(38,6), @FED_PES_UNILB decimal(38,6), @FED_PES_NETLB decimal(38,6), @FED_PES_BRULB decimal(38,6), 
                      @FED_SEC_IMP INT, @FED_DEF_TIP CHAR(1), @FED_POR_DEF decimal(38,6), @FED_LOTE VARCHAR(15), @AR_IMPMX INT, @AR_EXPMX INT, @AR_IMPFO INT, 
                      @FED_CON_PED CHAR(1), @MA_GENERICO INT, @PA_CODIGO INT, @EX_CODIGO INT, @FED_ORD_COMP VARCHAR(20), @FED_NOORDEN VARCHAR(20), 
                      @FED_USO_COMMINV CHAR(1), @EQ_GEN decimal(28,14), @EQ_IMPFO decimal(28,14), @EQ_EXPMX decimal(28,14), @TI_CODIGO INT, @FED_TENVIO CHAR(1), @FED_INBOND CHAR(1), @FED_TIPOINBOND varchar(20), @FED_RATEEXPMX decimal(38,6), 
                      @FED_RATEIMPFO decimal(38,6), @FED_RELEMP CHAR(1), @FED_FECHA_STRUCT DATETIME, @FED_DISCHARGE CHAR(1), @LE_FOLIO VARCHAR(20), @SPI_CODIGO SMALLINT, @FED_SALDO decimal(38,6), @FED_RETRABAJO CHAR(1), 
                      @ADE_CODIGO INT, @MA_EMPAQUE INT, @FED_CANTEMP decimal(38,6), @FED_FAC_NUM VARCHAR(15), @FED_FEC_ENV DATETIME, @FED_CON_CERTORIG CHAR(1), @FED_COS_UNI_CO decimal(38,6), @FED_GRA_MAT_CO decimal(38,6), 
                      @FED_EMP_CO decimal(38,6), @FED_NG_MAT_CO decimal(38,6), @FED_VA_CO decimal(38,6), @FED_CANTGEN decimal(38,6), @MO_CODIGO INT, @FED_DESCARGADO CHAR(1), @FED_PARTTYPE CHAR(1), @ME_GENERICO INT, @FED_TIP_ENS CHAR(1),
	@CONSECUTIVO INT


	-- crea la tabla FactExpDetTemp
	exec sp_CreaFactExpDetTemp

-- insercion a tabla temporal
	INSERT INTO FactExpDetTemp(FED_INDICEDANT, FE_CODIGO, MA_CODIGO, FED_NOMBRE, FED_NOPARTE, FED_NAME, ME_CODIGO, FED_CANT, FED_GRA_MP, 
	                      FED_GRA_MO, FED_GRA_EMP, FED_GRA_ADD, FED_GRA_GI, FED_GRA_GI_MX, FED_NG_MP, FED_NG_EMP, FED_NG_ADD, 
	                      FED_COS_UNI, FED_COS_TOT, FED_PES_UNI, FED_PES_NET, FED_PES_BRU, FED_PES_UNILB, FED_PES_NETLB, FED_PES_BRULB, 
	                      FED_SEC_IMP, FED_DEF_TIP, FED_POR_DEF, FED_LOTE, AR_IMPMX, AR_EXPMX, AR_IMPFO, 
	                      FED_CON_PED, MA_GENERICO, PA_CODIGO, EX_CODIGO, FED_ORD_COMP, FED_NOORDEN, 
	                      FED_USO_COMMINV, EQ_GEN, EQ_IMPFO, EQ_EXPMX, TI_CODIGO, FED_TENVIO, FED_INBOND, FED_TIPOINBOND, FED_RATEEXPMX, 
	                      FED_RATEIMPFO, FED_RELEMP, FED_FECHA_STRUCT, FED_DISCHARGE, LE_FOLIO, SPI_CODIGO, FED_SALDO, FED_RETRABAJO, 
	                      ADE_CODIGO, MA_EMPAQUE, FED_CANTEMP, FED_FAC_NUM, FED_FEC_ENV, FED_CON_CERTORIG, FED_COS_UNI_CO, FED_GRA_MAT_CO, 
	                      FED_EMP_CO, FED_NG_MAT_CO, FED_VA_CO, FED_CANTGEN, MO_CODIGO, FED_DESCARGADO, FED_PARTTYPE, ME_GENERICO, FED_TIP_ENS, TCO_CODIGO, FED_NAFTA, AR_ORIG, AR_NG_EMP)

	SELECT     FED_INDICED, @DESTINO, MA_CODIGO, FED_NOMBRE, FED_NOPARTE, FED_NAME, ME_CODIGO, FED_CANT, FED_GRA_MP, 
	                      FED_GRA_MO, FED_GRA_EMP, FED_GRA_ADD, FED_GRA_GI, FED_GRA_GI_MX, FED_NG_MP, FED_NG_EMP, FED_NG_ADD, 
	                      FED_COS_UNI, FED_COS_TOT, FED_PES_UNI, FED_PES_NET, FED_PES_BRU, FED_PES_UNILB, FED_PES_NETLB, FED_PES_BRULB, 
	                      FED_SEC_IMP, FED_DEF_TIP, FED_POR_DEF, FED_LOTE, AR_IMPMX, AR_EXPMX, AR_IMPFO, 
	                      FED_CON_PED, MA_GENERICO, PA_CODIGO, EX_CODIGO, FED_ORD_COMP, FED_NOORDEN, 
	                      FED_USO_COMMINV, EQ_GEN, EQ_IMPFO, EQ_EXPMX, TI_CODIGO, FED_TENVIO, FED_INBOND, FED_TIPOINBOND, FED_RATEEXPMX, 
	                      FED_RATEIMPFO, FED_RELEMP, FED_FECHA_STRUCT, FED_DISCHARGE, LE_FOLIO, SPI_CODIGO, FED_SALDO, FED_RETRABAJO, 
	                      ADE_CODIGO, MA_EMPAQUE, FED_CANTEMP, FED_FAC_NUM, FED_FEC_ENV, FED_CON_CERTORIG, FED_COS_UNI_CO, FED_GRA_MAT_CO, 
	                      FED_EMP_CO, FED_NG_MAT_CO, FED_VA_CO, FED_CANTGEN, MO_CODIGO, 'N', FED_PARTTYPE, ME_GENERICO, FED_TIP_ENS, TCO_CODIGO, FED_NAFTA, AR_ORIG, AR_NG_EMP
	FROM         FACTEXPDET WHERE FE_CODIGO=@FUENTE


	-- insercion en detalle
	INSERT INTO FactExpDet (FED_INDICED, FE_CODIGO, MA_CODIGO, FED_NOMBRE, FED_NOPARTE, FED_NAME, ME_CODIGO, FED_CANT, FED_GRA_MP, 
	                      FED_GRA_MO, FED_GRA_EMP, FED_GRA_ADD, FED_GRA_GI, FED_GRA_GI_MX, FED_NG_MP, FED_NG_EMP, FED_NG_ADD, 
	                      FED_COS_UNI, FED_COS_TOT, FED_PES_UNI, FED_PES_NET, FED_PES_BRU, FED_PES_UNILB, FED_PES_NETLB, FED_PES_BRULB, 
	                      FED_SEC_IMP, FED_DEF_TIP, FED_POR_DEF, FED_LOTE, AR_IMPMX, AR_EXPMX, AR_IMPFO, 
	                      FED_CON_PED, MA_GENERICO, PA_CODIGO, EX_CODIGO, FED_ORD_COMP, FED_NOORDEN, 
	                      FED_USO_COMMINV, EQ_GEN, EQ_IMPFO, EQ_EXPMX, TI_CODIGO, FED_TENVIO, FED_INBOND, FED_TIPOINBOND, FED_RATEEXPMX, 
	                      FED_RATEIMPFO, FED_RELEMP, FED_FECHA_STRUCT, FED_DISCHARGE, LE_FOLIO, SPI_CODIGO, FED_SALDO, FED_RETRABAJO, 
	                      ADE_CODIGO, MA_EMPAQUE, FED_CANTEMP, FED_FAC_NUM, FED_FEC_ENV, FED_CON_CERTORIG, FED_COS_UNI_CO, FED_GRA_MAT_CO, 
	                      FED_EMP_CO, FED_NG_MAT_CO, FED_VA_CO, FED_CANTGEN, MO_CODIGO, FED_DESCARGADO, FED_PARTTYPE, ME_GENERICO, FED_TIP_ENS, TCO_CODIGO, FED_NAFTA, AR_ORIG, AR_NG_EMP)


	SELECT     FED_INDICED, FE_CODIGO, MA_CODIGO, FED_NOMBRE, FED_NOPARTE, FED_NAME, ME_CODIGO, FED_CANT, FED_GRA_MP, 
	                      FED_GRA_MO, FED_GRA_EMP, FED_GRA_ADD, FED_GRA_GI, FED_GRA_GI_MX, FED_NG_MP, FED_NG_EMP, FED_NG_ADD, 
	                      FED_COS_UNI, FED_COS_TOT, FED_PES_UNI, FED_PES_NET, FED_PES_BRU, FED_PES_UNILB, FED_PES_NETLB, FED_PES_BRULB, 
	                      FED_SEC_IMP, FED_DEF_TIP, FED_POR_DEF, FED_LOTE, AR_IMPMX, AR_EXPMX, AR_IMPFO, 
	                      FED_CON_PED, MA_GENERICO, PA_CODIGO, EX_CODIGO, FED_ORD_COMP, FED_NOORDEN, 
	                      FED_USO_COMMINV, EQ_GEN, EQ_IMPFO, EQ_EXPMX, TI_CODIGO, FED_TENVIO, FED_INBOND, FED_TIPOINBOND, FED_RATEEXPMX, 
	                      FED_RATEIMPFO, FED_RELEMP, FED_FECHA_STRUCT, FED_DISCHARGE, LE_FOLIO, SPI_CODIGO, FED_SALDO, FED_RETRABAJO, 
	                      ADE_CODIGO, MA_EMPAQUE, FED_CANTEMP, FED_FAC_NUM, FED_FEC_ENV, FED_CON_CERTORIG, FED_COS_UNI_CO, FED_GRA_MAT_CO, 
	                      FED_EMP_CO, FED_NG_MAT_CO, FED_VA_CO, FED_CANTGEN, MO_CODIGO, FED_DESCARGADO, FED_PARTTYPE, ME_GENERICO, FED_TIP_ENS, TCO_CODIGO, FED_NAFTA, AR_ORIG, AR_NG_EMP
	FROM         FactExpDetTemp


		update factexp
		set fe_cuentadet=(select isnull(count(factexpdet.fe_codigo),0) from factexpdet where factexpdet.fe_codigo =factexp.fe_codigo),
                            FE_TOTALB = (select FE_TOTALB from factexp where fe_codigo=@fuente)
		where fe_codigo =@DESTINO

		select @FED_INDICED= max(fed_indiced) from factexpdet

		update consecutivo
		set cv_codigo =  isnull(@fed_indiced,0) + 1
		where cv_tipo = 'FED'


	exec sp_droptable 'FactExpDetTemp'

GO
