SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO













CREATE PROCEDURE [dbo].[SP_FACTEXPREVSIONIMPRESION] (@FE_CODIGO INT)   as

declare @sinGrupo char(1), @CFV_PEDCONSOLIDA CHAR(1), @CFV_NOREMESA CHAR(1), @CFV_NOGUIA CHAR(1), @CFV_CTRANSPOR CHAR(1), 
      @CFV_MEDIOTRANS CHAR(1), @CFV_PLACASMX CHAR(1), @CFV_PLACASUSA CHAR(1), @CFV_REGISTRO CHAR(1), 
      @CFV_BULTOS CHAR(1), @CFV_NOMBRE CHAR(1), @CFV_COSTOUNI CHAR(1), @CFV_CANTIDAD CHAR(1), @CFV_TARIFAUSA CHAR(1), 
      @CFV_TARIFAMX CHAR(1), @CFV_TASAMX CHAR(1), @CFV_GRUPOGEN CHAR(1), @CFV_PESONETO CHAR(1), 
      @CFV_PESOBRUTO CHAR(1), @CFV_ORDCOMPRA CHAR(1), @CFV_ORDTRABAJO CHAR(1), @CFV_NOENTRADA CHAR(1)

	delete from FACTEXPADVERTENCIA where FE_codigo=@FE_CODIGO

	
	SELECT  @CFV_PEDCONSOLIDA=CFV_PEDCONSOLIDA, 
		@CFV_NOREMESA=CFV_NOREMESA, 
		@CFV_NOGUIA=CFV_NOGUIA, 
		@CFV_CTRANSPOR=CFV_CTRANSPOR, 
		@CFV_MEDIOTRANS=CFV_MEDIOTRANS, 
		@CFV_PLACASMX=CFV_PLACASMX, 
		@CFV_PLACASUSA=CFV_PLACASUSA, 
		@CFV_REGISTRO=CFV_REGISTRO, 
	        @CFV_BULTOS=CFV_BULTOS, 
		-- detalle
		@CFV_NOMBRE=CFV_NOMBRE,  -- ya
		@CFV_COSTOUNI=CFV_COSTOUNI, -- ya
		@CFV_CANTIDAD=CFV_CANTIDAD, -- ya
		@CFV_TARIFAUSA=CFV_TARIFAUSA, -- ya
		@CFV_TARIFAMX=CFV_TARIFAMX, -- ya
		@CFV_TASAMX=CFV_TASAMX, -- ya
		@CFV_GRUPOGEN=CFV_GRUPOGEN,  -- ya
		@CFV_PESONETO=CFV_PESONETO, 
		@CFV_PESOBRUTO=CFV_PESOBRUTO, 
		@CFV_ORDCOMPRA=CFV_ORDCOMPRA, 
		@CFV_ORDTRABAJO=CFV_ORDTRABAJO, 
		@CFV_NOENTRADA=CFV_NOENTRADA
	FROM         CONFIGURAREVISAVAL
	WHERE     (CFV_FORMATAG = 62)




	if @CFV_PEDCONSOLIDA = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* No. Pedimento Consolidado Vacio' 
	FROM       FACTEXP
	WHERE   (FC_CODIGO = 0 OR FC_CODIGO IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO) 
	AND CP_CODIGO IN (SELECT CP_CODIGO FROM CLAVEPED WHERE CP_CONSOLIDADO='S')


	if @CFV_NOREMESA = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* No. Remesa Vacia' 
	FROM       FACTEXP
	WHERE   (FE_CONSECUTIVOPED = '' OR FE_CONSECUTIVOPED IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO) 
	AND CP_CODIGO IN (SELECT CP_CODIGO FROM CLAVEPED WHERE CP_CONSOLIDADO='S')


	if @CFV_NOGUIA = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* No. Guia Vacia' 
	FROM       FACTEXP
	WHERE   (FE_GUIA1 = '' OR FE_GUIA1 IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO) 


	if @CFV_CTRANSPOR = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Comp. Transportista Vacia' 
	FROM       FACTEXP
	WHERE   (CT_COMPANY1 = 0 OR CT_COMPANY1 IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO) 


	if @CFV_MEDIOTRANS = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Medio de Transporte Vacio' 
	FROM       FACTEXP
	WHERE   (MT_COMPANY1 = 0 OR MT_COMPANY1 IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO)

	if @CFV_PLACASMX = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Placas Mx. Vacias' 
	FROM       FACTEXP
	WHERE   (FE_TRAC_MX1 = '' OR FE_TRAC_MX1 IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO)


	if @CFV_PLACASUSA = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Placas US. Vacias' 
	FROM       FACTEXP
	WHERE   (FE_TRAC_US1 = '' OR FE_TRAC_US1 IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO)

	if @CFV_REGISTRO = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Registro del Contenedor Vacio' 
	FROM       FACTEXP
	WHERE   (FE_CONT1_REG = '' OR FE_CONT1_REG IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO)

	if @CFV_BULTOS = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Total de Bultos Vacio' 
	FROM       FACTEXP
	WHERE   (FE_TOTALB = 0 OR FE_TOTALB IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO)

	/*  Factores de conversion */
/*
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)

	SELECT     dbo.FACTEXP.FE_CODIGO, 
	                      '* Posible Factor de Conversion erroneo, No. Parte: ' + dbo.FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTEXPDET.FED_CANT) + ', UM No. Parte:' + MEDIDA_2.ME_CORTO + ', UM Generico:' + isnull(MEDIDA_1.ME_CORTO,'')
	FROM         dbo.FACTEXP INNER JOIN
	                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTEXPDET.ME_GENERICO = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_2 ON dbo.FACTEXPDET.ME_CODIGO = MEDIDA_2.ME_CODIGO
	WHERE     (dbo.FACTEXPDET.ME_CODIGO <> dbo.FACTEXPDET.ME_GENERICO) AND (dbo.FACTEXPDET.EQ_GEN = 1)
	and (FACTEXP.FE_CODIGO = @FE_CODIGO) AND isnull(MEDIDA_1.ME_CORTO,'')<>'SET' AND  isnull(MEDIDA_2.ME_CORTO,'')<>'RLL' AND isnull(MEDIDA_1.ME_CORTO,'')<>''
*/

	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)

	SELECT     dbo.FACTEXP.FE_CODIGO, 
	                      '* Registro en Detalle con posible Factor de Conversion erroneo, No. Parte: ' + dbo.FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTEXPDET.FED_CANT) + ', UM No. Parte:' + MEDIDA_2.ME_CORTO + ', UM Generico:' + isnull(MEDIDA_1.ME_CORTO,'')
	FROM         dbo.FACTEXP INNER JOIN
	                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTEXPDET.ME_GENERICO = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_2 ON dbo.FACTEXPDET.ME_CODIGO = MEDIDA_2.ME_CODIGO
	WHERE     (dbo.FACTEXPDET.ME_CODIGO = dbo.FACTEXPDET.ME_GENERICO) AND (dbo.FACTEXPDET.EQ_GEN <> 1)
	and (FACTEXP.FE_CODIGO = @FE_CODIGO)



	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)

	SELECT     dbo.FACTEXP.FE_CODIGO, 
	                      '* Registro en Detalle con Factor de Conversion erroneo Grupo Gen en KG, No. Parte: ' + dbo.FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTEXPDET.FED_CANT) + ', UM Generico: KG, Peso Unitario Kg:'+CONVERT(varchar(50),dbo.FACTEXPDET.FED_PES_UNI)+' <> Factor de Conversion: '+CONVERT(varchar(50),dbo.FACTEXPDET.EQ_GEN)
	FROM         dbo.FACTEXP INNER JOIN
	                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO
	WHERE     dbo.FACTEXPDET.ME_GENERICO=(SELECT ME_KILOGRAMOS FROM CONFIGURACION) AND (round(dbo.FACTEXPDET.EQ_GEN,6) <> ROUND(dbo.FACTEXPDET.FED_PES_UNI,6))
	and (FACTEXP.FE_CODIGO = @FE_CODIGO)



	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)

	SELECT     dbo.FACTEXP.FE_CODIGO, 
	                      '* Registro en Detalle con Factor de Conversion erroneo F. Arancelaria Exp. Mx en KG, No. Parte: ' + dbo.FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTEXPDET.FED_CANT) + ', UM F. Arancelaria: KG, Peso Unitario Kg:'+CONVERT(varchar(50),dbo.FACTEXPDET.FED_PES_UNI)+' <> Factor de Conversion: '+CONVERT(varchar(50),dbo.FACTEXPDET.EQ_EXPMX)
	FROM         dbo.FACTEXP INNER JOIN
	                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO
	WHERE     dbo.FACTEXPDET.ME_AREXPMX=(SELECT ME_KILOGRAMOS FROM CONFIGURACION) AND (round(dbo.FACTEXPDET.EQ_EXPMX,6) <> ROUND(dbo.FACTEXPDET.FED_PES_UNI,6))
	and (FACTEXP.FE_CODIGO = @FE_CODIGO)



	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)

	SELECT     dbo.FACTEXP.FE_CODIGO, 
	                      '* Registro en Detalle con Factor de Conversion erroneo Grupo VS F. Arancelaria, No. Parte: ' + dbo.FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTEXPDET.FED_CANT) + ', UM F. Arancelaria:' + MEDIDA_2.ME_CORTO + ', UM Generico:' + isnull(MEDIDA_1.ME_CORTO,'')
	FROM         dbo.FACTEXP INNER JOIN
	                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTEXPDET.ME_GENERICO = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_2 ON dbo.FACTEXPDET.ME_AREXPMX = MEDIDA_2.ME_CODIGO
	WHERE     (dbo.FACTEXPDET.ME_AREXPMX = dbo.FACTEXPDET.ME_GENERICO) AND (round(dbo.FACTEXPDET.EQ_GEN,6) <> round(dbo.FACTEXPDET.EQ_EXPMX,6))
	and (FACTEXP.FE_CODIGO = @FE_CODIGO)


	if @CFV_CANTIDAD='S'
	begin
		INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	
		SELECT     dbo.FACTEXP.FE_CODIGO, 
		                      '* Registro en Detalle con Cantidad Erronea, Con la UM Seleccionada no se permite la Cantidad con punto decimal, No. Parte: ' + dbo.FACTEXPDET.FED_NOPARTE +', UM : ' + MEDIDA_1.ME_CORTO 
		FROM         dbo.FACTEXP INNER JOIN
		                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
		                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTEXPDET.ME_CODIGO = MEDIDA_1.ME_CODIGO 
		WHERE     (ME_CLA_PED in ('15', '6', '12', '9')) AND ROUND(FED_CANT, 6) - dbo.Trunc(ROUND(FED_CANT, 6), 0)>0
		--AND (CHARINDEX('.', CONVERT(varchar(50), FED_CANT)) <> 0) 
		and (FACTEXP.FE_CODIGO = @FE_CODIGO)


		INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	
		SELECT     dbo.FACTEXP.FE_CODIGO, 
		                      '* Registro en Detalle Sin Cantidad, No. Parte: ' + dbo.FACTEXPDET.FED_NOPARTE +', UM : ' + MEDIDA_1.ME_CORTO 
		FROM         dbo.FACTEXP INNER JOIN
		                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
		                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTEXPDET.ME_CODIGO = MEDIDA_1.ME_CODIGO 
		WHERE   (FACTEXPDET.FED_CANT =0 OR FACTEXPDET.FED_CANT IS NULL) 
		and (FACTEXP.FE_CODIGO = @FE_CODIGO)


	
	end




	if @CFV_NOMBRE='S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FACTEXP.FE_CODIGO, '* Registro en Detalle Sin Descripcion en espa¤ol, No. Parte: ' + FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTEXPDET.FED_CANT) + ' ' + MEDIDA.ME_CORTO 
	FROM         FACTEXP INNER JOIN
	                      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTEXPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTEXPDET.FED_NOMBRE IS NULL OR FACTEXPDET.FED_NOMBRE='' OR FACTEXPDET.FED_NOMBRE='TEMP' OR FACTEXPDET.FED_NOMBRE='.') 
	and (FACTEXP.FE_CODIGO = @FE_CODIGO)


	/* Costos */
	if @CFV_COSTOUNI='S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FACTEXP.FE_CODIGO, '* Registro en Detalle Sin Costo Unitario, No. Parte: ' + FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTEXPDET.FED_CANT) + ' ' + MEDIDA.ME_CORTO 
	FROM         FACTEXP INNER JOIN
	                      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTEXPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTEXPDET.FED_COS_UNI IS NULL OR FACTEXPDET.FED_COS_UNI=0) 
	and (FACTEXP.FE_CODIGO = @FE_CODIGO)


	
	if @CFV_TASAMX='S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FACTEXP.FE_CODIGO, '* Registro en Detalle Sin Tasa de Importacion Mx, No. Parte: ' + FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTEXPDET.FED_CANT) + ' ' + MEDIDA.ME_CORTO AS Expr1
	FROM         FACTEXP INNER JOIN
	                      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTEXPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTEXP.FE_CODIGO = @FE_CODIGO) AND (FACTEXPDET.FED_POR_DEF= -1)



	if (SELECT     Count(*)
	FROM         FACTEXP INNER JOIN
	                      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTEXPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTEXPDET.MA_GENERICO = 0 OR
	                      FACTEXPDET.MA_GENERICO IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO))>0
	set @sinGrupo='S'



	IF @CFV_GRUPOGEN = 'S' -- grupo generico
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FACTEXP.FE_CODIGO, '* Registro en Detalle Sin Grupo Generico, No. Parte: ' + FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTEXPDET.FED_CANT) + ' ' + MEDIDA.ME_CORTO 
	FROM         FACTEXP INNER JOIN
	                      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTEXPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTEXPDET.MA_GENERICO = 0 OR
	                      FACTEXPDET.MA_GENERICO IS NULL) AND (FACTEXP.FE_CODIGO = @FE_CODIGO)


	if @CFV_TARIFAUSA = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Registro en Detalle con Fraccion Exp. USA Incorrecta, No. Parte: ' + FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), FED_CANT)
	FROM       FACTEXPDET
	WHERE   (AR_IMPFO = 0 OR AR_IMPFO IS NULL) AND (FACTEXPDET.FE_CODIGO = @FE_CODIGO) 


	if @CFV_TARIFAMX = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Registro en Detalle con Fraccion Exp. Mx Incorrecta, No. Parte: ' + FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), FED_CANT)
	FROM       FACTEXPDET left outer join ARANCEL on FACTEXPDET.AR_EXPMX = ARANCEL.AR_CODIGO
	WHERE   (AR_EXPMX = 0 OR AR_EXPMX IS NULL OR ARANCEL.AR_FRACCION='SINFRACCION' OR ARANCEL.AR_FRACCION='SIN FRACCION' OR ARANCEL.AR_FRACCION='00000000'
		OR ARANCEL.AR_FRACCION='99999999') AND (FACTEXPDET.FE_CODIGO = @FE_CODIGO) 


	IF(SELECT CF_PESOS_EXP FROM CONFIGURACION)='K'
	begin
		if @CFV_PESONETO='S'
		INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
		SELECT     FACTEXPDET.FE_CODIGO, '* Registro en Detalle con Peso Neto en cero (Kg) en No. Parte: '+ FACTEXPDET.FED_NOPARTE +' Peso Bruto: ' +convert(varchar(50),FED_PES_BRU)
		FROM         FACTEXPDET
		WHERE     (FED_PES_NET=0) AND (FED_CANTEMP = 0)
		AND (FACTEXPDET.FE_CODIGO = @FE_CODIGO) 

		if @CFV_PESOBRUTO='S'
		INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
		SELECT     FACTEXPDET.FE_CODIGO, '* Registro en Detalle con Peso Bruto en cero (Kg) en No. Parte: '+ FACTEXPDET.FED_NOPARTE +' Peso Neto: ' +convert(varchar(50),FED_PES_NET)
		FROM         FACTEXPDET
		WHERE     (FED_PES_BRU=0) AND (FED_CANTEMP = 0)
		AND (FACTEXPDET.FE_CODIGO = @FE_CODIGO) 
	end
	else
	begin
		if @CFV_PESONETO='S'
		INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
		SELECT     FACTEXPDET.FE_CODIGO, '* Registro en Detalle con Peso Neto en cero (Lb) en No. Parte: '+ FACTEXPDET.FED_NOPARTE +' Peso Bruto: ' +convert(varchar(50),FED_PES_BRULB)
		FROM         FACTEXPDET
		WHERE     (FED_PES_NETLB=0) AND (FED_CANTEMP = 0)
		AND (FACTEXPDET.FE_CODIGO = @FE_CODIGO) 

		if @CFV_PESOBRUTO='S'
		INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
		SELECT     FACTEXPDET.FE_CODIGO, '* Registro en Detalle con Peso Bruto en cero (Lb) en No. Parte: '+ FACTEXPDET.FED_NOPARTE +' Peso Neto: ' +convert(varchar(50),FED_PES_NETLB)
		FROM         FACTEXPDET
		WHERE     (FED_PES_BRULB=0) AND (FED_CANTEMP = 0)
		AND (FACTEXPDET.FE_CODIGO = @FE_CODIGO) 
	end



	if @CFV_ORDCOMPRA = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Registro en Detalle con Orden de Compra Vacia, No. Parte: ' + FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), FED_CANT)
	FROM       FACTEXPDET
	WHERE   (FED_ORD_COMP = '' OR FED_ORD_COMP IS NULL) AND (FACTEXPDET.FE_CODIGO = @FE_CODIGO) 


	if @CFV_ORDTRABAJO = 'S'
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FE_CODIGO, '* Registro en Detalle con Orden de Trabajo Vacia, No. Parte: ' + FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), FED_CANT)
	FROM       FACTEXPDET
	WHERE   (FED_NOORDEN = '' OR FED_NOORDEN IS NULL) AND (FACTEXPDET.FE_CODIGO = @FE_CODIGO) 


/*	
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FACTEXP.FE_CODIGO, '* Sin Sector (Tipo de tasa PPS), No. Parte: ' + FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTEXPDET.FED_CANT) + ' ' + MEDIDA.ME_CORTO 
	FROM         FACTEXP INNER JOIN
	                      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTEXPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTEXPDET.FED_SEC_IMP = 0 OR
	                      FACTEXPDET.FED_SEC_IMP IS NULL) AND (FACTEXPDET.FED_DEF_TIP = 'S') AND (FACTEXP.FE_CODIGO = @FE_CODIGO)

	
	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FACTEXP.FE_CODIGO, '* Sin Tratado (Tipo de tasa Bajo Tratado), No. Parte: ' + FACTEXPDET.FED_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTEXPDET.FED_CANT) + ' ' + MEDIDA.ME_CORTO
	FROM         FACTEXP INNER JOIN
	                      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTEXPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTEXPDET.FED_DEF_TIP = 'P') AND (FACTEXP.FE_CODIGO = @FE_CODIGO) AND (FACTEXPDET.SPI_CODIGO = 0 OR
	                      FACTEXPDET.SPI_CODIGO IS NULL)

	INSERT INTO FACTEXPADVERTENCIA(FE_CODIGO, FE_COMENTARIO)
	SELECT     FACTEXPDET.FE_CODIGO, '* Peso Bruto (Kg) Incorrecto en No. Parte: '+ FACTEXPDET.FED_NOPARTE +' PB: ' +convert(varchar(50),FED_PES_BRU)+' mayor que PN: '+ convert(varchar(50),FED_PES_NET)+' y sin Cantidad de Empaque' 
	FROM         FACTEXPDET
	WHERE     (FED_PES_BRU > FED_PES_NET) AND (FED_CANTEMP = 0)
	AND (FACTEXPDET.FE_CODIGO = @FE_CODIGO) 
*/

GO
