SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_ACTUALIZACODIGO]   as


		ALTER TABLE FACTEXPDET DISABLE TRIGGER Update_FactExpDet

	UPDATE FACTEXPDET
	SET     FACTEXPDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         FACTEXPDET INNER JOIN
	                      MAESTRO ON FACTEXPDET.FED_NOPARTE = MAESTRO.MA_NOPARTE AND FACTEXPDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')

	ALTER TABLE FACTEXPDET ENABLE TRIGGER Update_FactExpDet

	ALTER TABLE FACTIMPDET DISABLE TRIGGER Update_FactImpDet

	UPDATE FACTIMPDET
	SET     FACTIMPDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         FACTIMPDET INNER JOIN
	                      MAESTRO ON FACTIMPDET.FID_NOPARTE = MAESTRO.MA_NOPARTE AND FACTIMPDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')

	ALTER TABLE FACTIMPDET ENABLE TRIGGER Update_FactImpDet


	ALTER TABLE PEDIMPDET DISABLE TRIGGER insert_pedimpdet


	UPDATE PEDIMPDET
	SET     PEDIMPDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         PEDIMPDET INNER JOIN
	                      MAESTRO ON PEDIMPDET.PID_NOPARTE = MAESTRO.MA_NOPARTE AND PEDIMPDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')

	ALTER TABLE PEDIMPDET ENABLE TRIGGER insert_pedimpdet



	ALTER TABLE PIDescarga DISABLE TRIGGER INSERT_PIDESCARGA


	UPDATE PIDescarga
	SET     PIDescarga.MA_CODIGO= PEDIMPDET.MA_CODIGO
	FROM         PEDIMPDET INNER JOIN
	                      PIDescarga ON PEDIMPDET.PID_INDICED = PIDescarga.PID_INDICED 
		AND PEDIMPDET.MA_CODIGO <> PIDescarga.MA_CODIGO

	ALTER TABLE PIDescarga ENABLE TRIGGER INSERT_PIDESCARGA


	ALTER TABLE LISTAEXPDET DISABLE TRIGGER Update_listaexpDet

	UPDATE LISTAEXPDET
	SET     LISTAEXPDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         LISTAEXPDET INNER JOIN
	                      MAESTRO ON LISTAEXPDET.LED_NOPARTE = MAESTRO.MA_NOPARTE AND LISTAEXPDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')


	ALTER TABLE LISTAEXPDET ENABLE TRIGGER Update_listaexpDet

	ALTER TABLE PCKLISTDET DISABLE TRIGGER Update_PcklistDet

	UPDATE PCKLISTDET
	SET     PCKLISTDET.MA_CODIGO= MAESTRO.MA_CODIGO
	FROM         PCKLISTDET INNER JOIN
	                      MAESTRO ON PCKLISTDET.PLD_NOPARTE = MAESTRO.MA_NOPARTE AND PCKLISTDET.MA_CODIGO <> MAESTRO.MA_CODIGO
	WHERE     (MAESTRO.MA_INV_GEN = 'I')

	ALTER TABLE PCKLISTDET ENABLE TRIGGER Update_PcklistDet










GO
