SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




























CREATE PROCEDURE [dbo].[SP_CreaFactImpDetTemp]   as

declare @FID_INDICED int


	exec sp_droptable 'FactImpDetTemp'

	CREATE TABLE [dbo].[FactImpDetTemp] (
		[FID_INDICED] [int] IDENTITY (1, 1) NOT NULL ,
		[FI_CODIGO] [int] NOT NULL ,
		[FID_INDICEDANT] [int] NOT NULL ,
		[FID_NOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
		[FID_NOMBRE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
		[FID_NAME] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
		[FID_CANT_ST] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_CANT_ST] DEFAULT (0),
		[FID_COS_UNI] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_COS_UNI] DEFAULT (0),
		[FID_COS_TOT] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_COS_TOT] DEFAULT (0),
		[FID_PES_UNI] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_PES_UNI] DEFAULT (0),
		[FID_PES_NET] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_PES_NET] DEFAULT (0),
		[FID_PES_BRU] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_PES_BRU] DEFAULT (0),
		[FID_PES_UNILB] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_PES_UNILB] DEFAULT (0),
		[FID_PES_NETLB] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_PES_NETLB] DEFAULT (0),
		[FID_PES_BRULB] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_PES_BRULB] DEFAULT (0),
		[OR_CODIGO] [int] NULL ,
		[FID_ORD_COMP] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[ORD_INDICED] [int] NULL ,
		[FID_NOORDEN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FID_OBSERVA] [varchar] (1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FID_FEC_ENT] [datetime] NULL ,
		[FID_NUM_ENT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FID_SEC_IMP] [smallint] NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_SEC_IMP] DEFAULT (0),
		[FID_POR_DEF] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_POR_DEF] DEFAULT ((-1)),
		[FID_DEF_TIP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_DEF_TIP] DEFAULT ('G'),
		[FID_ENVIO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[AR_IMPMX] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_AR_IMPMX] DEFAULT (0),
		[AR_EXPFO] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_AR_EXPFO] DEFAULT (0),
		[MA_CODIGO] [int] NOT NULL ,
		[MV_CODIGO] [int] NULL ,
		[ME_CODIGO] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_ME_CODIGO] DEFAULT (0),
		[MA_GENERICO] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_MA_GENERICO] DEFAULT (0),
		[ME_ARIMPMX] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_ME_ARIMPMX] DEFAULT (0),
		[PA_CODIGO] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_PA_CODIGO] DEFAULT (0),
		[PR_CODIGO] [int] NULL ,
		[PL_FOLIO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[PL_CODIGO] [int] NULL ,
		[PLD_INDICED] [int] NULL ,
		[CS_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_FactImpDetTemp_CS_CODIGO] DEFAULT (8),
		[PE_CODIGO] [int] NULL ,
		[EQ_GEN] decimal(28,14) NOT NULL CONSTRAINT [DF_FactImpDetTemp_EQ_GEN] DEFAULT (1),
		[EQ_IMPMX] decimal(28,14) NOT NULL CONSTRAINT [DF_FactImpDetTemp_EQ_IMPMX] DEFAULT (1),
		[EQ_EXPFO] decimal(28,14) NOT NULL CONSTRAINT [DF_FactImpDetTemp_EQ_EXPFO] DEFAULT (1),
		[EQ_EXPFO2] decimal(28,14) NOT NULL CONSTRAINT [DF_FactImpDetTemp_EQ_EXPFO2] DEFAULT (1),
		[TI_CODIGO] [int] NOT NULL ,
		[FID_RATEEXPFO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_RATEEXPFO] DEFAULT (0),
		[FID_RELEMP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_RELEMP] DEFAULT ('N'),
		[SPI_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_FactImpDetTemp_SPI_CODIGO] DEFAULT (0),
		[MA_EMPAQUE] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_MA_EMPAQUE] DEFAULT (0),
		[FID_CANTEMP] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_CANTEMP] DEFAULT (0),
		[FID_LOTE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FID_FAC_NUM] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FID_FEC_ENV] [datetime] NULL ,
		[FID_LISTA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FID_CON_CERTORIG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[ME_GEN] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_ME_GEN] DEFAULT (0),
		[FID_GENERA_EMP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_GENERA_EMP] DEFAULT ('D'),
		[FID_CANT_DESP] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_CANT_DESP] DEFAULT (0),
		[FID_DEFTXT1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_DEFTXT1] DEFAULT (''),
		[FID_DEFTXT2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_DEFTXT2] DEFAULT (''),
		[FID_DEFNO3] decimal(38,6) NULL ,
		[FID_DEFNO4] decimal(38,6) NULL ,
		[FID_FECHA_STRUCT] [datetime] NULL ,
		[FID_PADREKITINSERT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_PADREKITINSERT] DEFAULT ('S'),
		[PID_INDICEDLIGA] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_PID_INDICEDLIGA] DEFAULT ((-1)),
		[PID_INDICEDLIGAR1] [int] NOT NULL CONSTRAINT [DF_FactImpDetTemp_PID_INDICEDLIGAR1] DEFAULT ((-1)),
		[TCO_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_FactImpDetTemp_TCO_CODIGO] DEFAULT (0),
		[FID_RELCAJAS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FID_SALDO] decimal(38,6) NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_SALDO] DEFAULT (0),
		[FID_ENUSO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_FactImpDetTemp_FID_ENUSO] DEFAULT ('N'),
		[FID_NOPARTEAUX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		CONSTRAINT [PK_FactImpDetTemp] PRIMARY KEY  NONCLUSTERED 
		(
			[FID_INDICED]
		)  ON [PRIMARY] 
	) ON [PRIMARY]

		select @FID_INDICED= max(isnull(fid_indiced,0))+1 from factimpdet

		DBCC CHECKIDENT (FACTIMPDETTEMP, RESEED, @FID_INDICED) WITH NO_INFOMSGS






GO
