SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE procedure dbo.SP_CALCULAR_EMPAQUE_ADICIONAL_FACTEXP (@FE_CODIGO INT)   as

SET NOCOUNT ON 
INSERT INTO FACTEXPEMPAQUEADICIONAL (FE_CODIGO, MA_CODIGO, MA_NOPARTE, FEAD_CANTIDAD, MA_GENERICO, EQ_GEN, ME_CODIGO)
SELECT     dbo.FACTEXPDET.FE_CODIGO, dbo.MAESTROEMPAQUEADICIONAL.MA_EMPAQUE, (SELECT MA_NOPARTE FROM MAESTRO WHERE MA_CODIGO=dbo.MAESTROEMPAQUEADICIONAL.MA_EMPAQUE), SUM(ISNULL(dbo.FACTEXPDET.FED_CANT, 0) 
                      * ISNULL(dbo.MAESTROEMPAQUEADICIONAL.FEAD_CANTIDAD, 0)) AS Cantidad, dbo.FACTEXPDET.MA_GENERICO, dbo.FACTEXPDET.EQ_GEN, 
                      dbo.FACTEXPDET.ME_CODIGO
FROM         dbo.FACTEXPDET LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.FACTEXPDET.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
                      dbo.MAESTROEMPAQUEADICIONAL ON dbo.FACTEXPDET.MA_CODIGO = dbo.MAESTROEMPAQUEADICIONAL.MA_CODIGO
WHERE     (dbo.CONFIGURATIPO.CFT_TIPO = 'S' OR dbo.CONFIGURATIPO.CFT_TIPO = 'P') AND
	     dbo.MAESTROEMPAQUEADICIONAL.MA_EMPAQUE NOT IN (SELECT MA_CODIGO FROM FACTEXPEMPAQUEADICIONAL WHERE FE_CODIGO=@FE_CODIGO)
GROUP BY dbo.FACTEXPDET.FE_CODIGO, dbo.MAESTROEMPAQUEADICIONAL.MA_EMPAQUE, dbo.FACTEXPDET.MA_GENERICO, 
                      dbo.FACTEXPDET.EQ_GEN, dbo.FACTEXPDET.ME_CODIGO
HAVING      (dbo.FACTEXPDET.FE_CODIGO = @FE_CODIGO) AND (SUM(ISNULL(dbo.FACTEXPDET.FED_CANT, 0) 
                      * ISNULL(dbo.MAESTROEMPAQUEADICIONAL.FEAD_CANTIDAD, 0)) > 0)

GO
