SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[sp_CreaVDescRetrabajo] (@FECodigo int)    as

declare @FE_Codigo varchar(50)

if exists (select *
           from   dbo.sysobjects
           where  id = object_id(N'[dbo].[VDESCRETRABAJO]')
                 and OBJECTPROPERTY(id, N'IsView') = 1)
   drop view [dbo].[VDESCRETRABAJO]

	

	select @FE_Codigo = convert(varchar(50),@FECodigo)

	-- (glr 21-sep-2010)
	-- para componentes de estructuras dinámicas, el tipo de adquisición se toma
	-- de la tabla de Retrabajo
	exec ('CREATE VIEW dbo.VDESCRETRABAJO
		as
		-- COMPONENTES CUANDO ES DINAMICA/RETRABAJO
		SELECT
           FACTEXPDET.MA_CODIGO, RETRABAJO.MA_HIJO
           , case when (FACTEXPDET.FED_RETRABAJO in (''D'',''E''))
                then SUM(FACTEXPDET.FED_CANT)
                else 1
             end AS FED_CANT
           , ''S'' AS MA_DISCHARGE
           , CONFIGURATIPO.CFT_TIPO, MAESTRO.ME_COM, RETRABAJO.FACTCONV
           , RETRABAJO.ME_GEN AS ME_GEN, SUM(RETRABAJO.RE_INCORPOR) AS RE_INCORPOR
           , FACTEXPDET.FED_INDICED
           , case when (FACTEXPDET.FED_RETRABAJO in (''D'',''E''))
                then RETRABAJO.MA_TIP_ENS
                else MAESTRO.MA_TIP_ENS
             end as MA_TIP_ENS
           , FACTEXPDET.FED_RETRABAJO, FACTEXPDET.FE_CODIGO
		FROM
           RETRABAJO LEFT OUTER JOIN FACTEXPDET
              ON RETRABAJO.FETR_INDICED = FACTEXPDET.FED_INDICED
                 and RETRABAJO.TIPO_FACTRANS = ''F''
           LEFT OUTER JOIN MAESTRO
              ON RETRABAJO.MA_HIJO = MAESTRO.MA_CODIGO
           LEFT OUTER JOIN CONFIGURATIPO
              ON RETRABAJO.TI_HIJO = CONFIGURATIPO.TI_CODIGO
           --LEFT OUTER JOIN FACTEXP
           --   ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO
		WHERE
           FACTEXPDET.PID_IndiceD = -1
           AND RETRABAJO.MA_HIJO <> FACTEXPDET.MA_CODIGO
           AND FACTEXPDET.FE_CODIGO = 0' + @FE_Codigo + '
        GROUP BY
           FACTEXPDET.FE_CODIGO, FACTEXPDET.FED_INDICED, FACTEXPDET.FED_RATEIMPFO
           , FACTEXPDET.AR_IMPFO, FACTEXPDET.FED_FECHA_STRUCT, FACTEXPDET.MA_CODIGO
           , FACTEXPDET.FED_COS_UNI, CONFIGURATIPO.TI_CODIGO
           , case when (FACTEXPDET.FED_RETRABAJO in (''D'',''E''))
                then RETRABAJO.MA_TIP_ENS
                else MAESTRO.MA_TIP_ENS
             end
           , RETRABAJO.MA_HIJO, RETRABAJO.FACTCONV, FACTEXPDET.FED_RETRABAJO
           , CONFIGURATIPO.CFT_TIPO, RETRABAJO.ME_GEN, MAESTRO.ME_COM
           , MAESTRO.MA_DISCHARGE, FACTEXPDET.pid_indiced
        HAVING   SUM(FACTEXPDET.FED_CANT) > 0

		UNION
		-- PT DEL RETRABAJO
		SELECT
           FACTEXPDET.MA_CODIGO, MAESTRO_1.MA_CODIGO AS BST_HIJO, 1 AS FED_CANT
           , ''S'' AS FED_DISCHARGE, CONFIGURATIPO.CFT_TIPO, FACTEXPDET.ME_CODIGO
           , MAESTRO_1.EQ_GEN, MAESTRO.ME_COM AS ME_GEN
           , SUM(FACTEXPDET.FED_CANT) AS RE_INCORPOR, FACTEXPDET.FED_INDICED
           , MAESTRO_1.MA_TIP_ENS, FACTEXPDET.FED_RETRABAJO, FACTEXPDET.FE_CODIGO
		FROM
           MAESTRO MAESTRO_1 RIGHT OUTER JOIN FACTEXPDET
              ON MAESTRO_1.MA_CODIGO = FACTEXPDET.MA_CODIGO
           LEFT OUTER JOIN MAESTRO
              ON FACTEXPDET.MA_GENERICO = MAESTRO.MA_CODIGO
           LEFT OUTER JOIN CONFIGURATIPO
              ON FACTEXPDET.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
		WHERE
           (ADE_CODIGO NOT IN (SELECT ADE_CODIGO
                               FROM   ALMACENDESP
                               WHERE  ADE_GENERADOPOR = ''R''
                                      AND FETR_CODIGO = FACTEXPDET.FE_CODIGO
                                      AND FETR_TIPO = ''F''))
           AND (FACTEXPDET.FED_RETRABAJO = ''R'')
           and FACTEXPDET.PID_IndiceD = -1
           AND FACTEXPDET.FE_CODIGO = 0' + @FE_Codigo + ' 
		GROUP BY
           FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO, MAESTRO_1.MA_TIP_ENS
           , MAESTRO_1.MA_CODIGO, MAESTRO_1.EQ_GEN, CONFIGURATIPO.CFT_TIPO
           , FACTEXPDET.ME_CODIGO, MAESTRO.ME_COM, FACTEXPDET.FED_RETRABAJO
           , FACTEXPDET.FE_CODIGO, FACTEXPDET.pid_indiced
		UNION
		--PT INCLUIDO EN LA LISTA(CUANDO SE EXPLOSIONA EL SUBENSAMBLE)
		SELECT
           FACTEXPDET.MA_CODIGO, RETRABAJO.MA_HIJO, 1 AS FED_CANT, ''S'' AS MA_DISCHARGE
           , CONFIGURATIPO.CFT_TIPO, MAESTRO.ME_COM, RETRABAJO.FACTCONV
           , RETRABAJO.ME_GEN AS ME_GEN
           , SUM(FED_CANT)-SUM(RETRABAJO.RE_INCORPOR) AS RE_INCORPOR
           , FACTEXPDET.FED_INDICED, MAESTRO.MA_TIP_ENS, FACTEXPDET.FED_RETRABAJO
           , FACTEXPDET.FE_CODIGO
		FROM
           MAESTRO RIGHT OUTER JOIN FACTEXPDET
           INNER JOIN RETRABAJO
              ON FACTEXPDET.FED_INDICED = RETRABAJO.FETR_INDICED
                 AND RETRABAJO.TIPO_FACTRANS = ''F''
           LEFT OUTER JOIN CONFIGURATIPO
              ON RETRABAJO.TI_HIJO = CONFIGURATIPO.TI_CODIGO
              ON MAESTRO.MA_CODIGO = RETRABAJO.MA_HIJO
           LEFT OUTER JOIN FACTEXP
              ON FACTEXPDET.FE_CODIGO = FACTEXP.FE_CODIGO
		WHERE
           (FACTEXP.CL_PROD IN (SELECT EM_CODIGO
                                FROM   CONFIGURACION
                                WHERE  CF_EXPLOSDESCADD = ''S'')
            AND (FACTEXPDET.FED_RETRABAJO = ''A'')
            AND (FACTEXPDET.PID_INDICED = -1)
            AND RETRABAJO.MA_HIJO = FACTEXPDET.MA_CODIGO)
           AND FACTEXPDET.FE_CODIGO = 0' + @FE_Codigo + '
		GROUP BY
           FACTEXPDET.MA_CODIGO, RETRABAJO.MA_HIJO, CONFIGURATIPO.CFT_TIPO
           , MAESTRO.ME_COM, RETRABAJO.FACTCONV, RETRABAJO.ME_GEN
           , RETRABAJO.RE_INCORPOR, FACTEXPDET.FED_INDICED, MAESTRO.MA_TIP_ENS
           , FACTEXPDET.FED_RETRABAJO, FACTEXPDET.FE_CODIGO, FACTEXPDET.PID_INDICED
		HAVING
           (SUM(FED_CANT) - SUM(RETRABAJO.RE_INCORPOR) > 0)')

/*	exec ('CREATE VIEW dbo.VDESCRETRABAJO
		as
		-- COMPONENTES CUANDO ES DINAMICA
		SELECT     FACTEXPDET.MA_CODIGO, RETRABAJO.MA_HIJO, SUM(FACTEXPDET.FED_CANT) AS FED_CANT,  ''S'' AS MA_DISCHARGE, 
		                      CONFIGURATIPO.CFT_TIPO, MAESTRO.ME_COM, RETRABAJO.FACTCONV, RETRABAJO.ME_GEN AS ME_GEN, 
		                      SUM(RETRABAJO.RE_INCORPOR) AS RE_INCORPOR, FACTEXPDET.FED_INDICED, MAESTRO.MA_TIP_ENS,
			FACTEXPDET.FED_RETRABAJO, FACTEXPDET.FE_CODIGO
		FROM         RETRABAJO LEFT OUTER JOIN
		                      FACTEXPDET ON RETRABAJO.FETR_INDICED = FACTEXPDET.FED_INDICED and RETRABAJO.TIPO_FACTRANS=''F'' LEFT OUTER JOIN
		                      MAESTRO ON RETRABAJO.MA_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
		                      CONFIGURATIPO ON FACTEXPDET.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
				LEFT OUTER JOIN FACTEXP ON FACTEXPDET.FE_CODIGO=FACTEXP.FE_CODIGO
		WHERE (RETRABAJO.MA_HIJO <> FACTEXPDET.MA_CODIGO AND
		 (((FACTEXPDET.FED_RETRABAJO = ''A'') AND FACTEXP.CL_PROD IN(SELECT EM_CODIGO FROM CONFIGURACION WHERE CF_EXPLOSDESCADD=''N''))
		OR ((FACTEXPDET.FED_RETRABAJO <> ''N'') AND (FACTEXPDET.FED_RETRABAJO <> ''E''))) and (FACTEXPDET.pid_indiced =-1))
		AND FACTEXPDET.FE_CODIGO=0'+@FE_CODIGO+' 

		GROUP BY FACTEXPDET.FE_CODIGO, FACTEXPDET.FED_INDICED, FACTEXPDET.FED_RATEIMPFO, FACTEXPDET.AR_IMPFO, 
		                      FACTEXPDET.FED_FECHA_STRUCT, FACTEXPDET.MA_CODIGO, FACTEXPDET.FED_COS_UNI, CONFIGURATIPO.TI_CODIGO, 
		                      MAESTRO.MA_TIP_ENS, RETRABAJO.MA_HIJO, RETRABAJO.FACTCONV, FACTEXPDET.FED_RETRABAJO, 
		                      CONFIGURATIPO.CFT_TIPO, RETRABAJO.ME_GEN, MAESTRO.ME_COM, MAESTRO.MA_DISCHARGE,
			FACTEXPDET.pid_indiced
		HAVING   SUM(FACTEXPDET.FED_CANT) >0
		UNION
		SELECT     FACTEXPDET.MA_CODIGO, RETRABAJO.MA_HIJO, SUM(FACTEXPDET.FED_CANT) AS FED_CANT,  ''S'' AS MA_DISCHARGE, 
		                      CONFIGURATIPO.CFT_TIPO, MAESTRO.ME_COM, RETRABAJO.FACTCONV, RETRABAJO.ME_GEN AS ME_GEN, 
		                      SUM(RETRABAJO.RE_INCORPOR) AS RE_INCORPOR, FACTEXPDET.FED_INDICED, MAESTRO.MA_TIP_ENS,
			FACTEXPDET.FED_RETRABAJO, FACTEXPDET.FE_CODIGO
		FROM         RETRABAJO LEFT OUTER JOIN
		                      FACTEXPDET ON RETRABAJO.FETR_INDICED = FACTEXPDET.FED_INDICED and RETRABAJO.TIPO_FACTRANS=''F'' LEFT OUTER JOIN
		                      MAESTRO ON RETRABAJO.MA_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
		                      CONFIGURATIPO ON FACTEXPDET.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
		WHERE FACTEXPDET.FE_CODIGO=0'+@FE_CODIGO+' 
		GROUP BY FACTEXPDET.FE_CODIGO, FACTEXPDET.FED_INDICED, FACTEXPDET.FED_RATEIMPFO, FACTEXPDET.AR_IMPFO, 
		                      FACTEXPDET.FED_FECHA_STRUCT, FACTEXPDET.MA_CODIGO, FACTEXPDET.FED_COS_UNI, CONFIGURATIPO.TI_CODIGO, 
		                      MAESTRO.MA_TIP_ENS, RETRABAJO.MA_HIJO, RETRABAJO.FACTCONV, FACTEXPDET.FED_RETRABAJO, 
		                      CONFIGURATIPO.CFT_TIPO, RETRABAJO.ME_GEN, MAESTRO.ME_COM, MAESTRO.MA_DISCHARGE,
			FACTEXPDET.pid_indiced
		HAVING      (FACTEXPDET.FED_RETRABAJO = ''E'') 
			         and (FACTEXPDET.pid_indiced =-1) and SUM(FACTEXPDET.FED_CANT) >0
		UNION
		-- PT
		SELECT     FACTEXPDET.MA_CODIGO, MAESTRO_1.MA_CODIGO AS BST_HIJO, 1 AS FED_CANT, ''S'' AS FED_DISCHARGE, 
		                      CONFIGURATIPO.CFT_TIPO, FACTEXPDET.ME_CODIGO, MAESTRO_1.EQ_GEN, MAESTRO.ME_COM AS ME_GEN, SUM(FACTEXPDET.FED_CANT) AS RE_INCORPOR, 
		                      FACTEXPDET.FED_INDICED, MAESTRO_1.MA_TIP_ENS, 	FACTEXPDET.FED_RETRABAJO, FACTEXPDET.FE_CODIGO
		FROM         MAESTRO MAESTRO_1 RIGHT OUTER JOIN
		                      FACTEXPDET ON MAESTRO_1.MA_CODIGO = FACTEXPDET.MA_CODIGO LEFT OUTER JOIN
		                      MAESTRO ON FACTEXPDET.MA_GENERICO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
		                      CONFIGURATIPO ON FACTEXPDET.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
		WHERE (ADE_CODIGO NOT IN (SELECT ADE_CODIGO FROM ALMACENDESP WHERE  ADE_GENERADOPOR=''R'' AND FETR_CODIGO=FACTEXPDET.FE_CODIGO AND FETR_TIPO=''F''))
		AND FACTEXPDET.FE_CODIGO=0'+@FE_CODIGO+' 
		GROUP BY FACTEXPDET.FED_INDICED, FACTEXPDET.MA_CODIGO, MAESTRO_1.MA_TIP_ENS, MAESTRO_1.MA_CODIGO, MAESTRO_1.EQ_GEN, 
		                      CONFIGURATIPO.CFT_TIPO, FACTEXPDET.ME_CODIGO, MAESTRO.ME_COM, FACTEXPDET.FED_RETRABAJO, 
		                      FACTEXPDET.FE_CODIGO, FACTEXPDET.pid_indiced
		HAVING      (FACTEXPDET.FED_RETRABAJO = ''R'') 
				and FACTEXPDET.pid_indiced=-1
		UNION
		--COMPONENTES PT (CUANDO SE EXPLOSIONA EL SUBENSAMBLE)
		SELECT     FACTEXPDET.MA_CODIGO, RETRABAJO.MA_HIJO, 1 AS FED_CANT, ''S'' AS MA_DISCHARGE, CONFIGURATIPO.CFT_TIPO, 
		                      MAESTRO.ME_COM, RETRABAJO.FACTCONV, RETRABAJO.ME_GEN AS ME_GEN, SUM(RETRABAJO.RE_INCORPOR) 
		                      AS RE_INCORPOR, FACTEXPDET.FED_INDICED, MAESTRO.MA_TIP_ENS, FACTEXPDET.FED_RETRABAJO, 
		                      FACTEXPDET.FE_CODIGO
		FROM         MAESTRO RIGHT OUTER JOIN
		                      FACTEXPDET INNER JOIN
		                      RETRABAJO ON FACTEXPDET.FED_INDICED = RETRABAJO.FETR_INDICED AND RETRABAJO.TIPO_FACTRANS = ''F'' LEFT OUTER JOIN
		                      CONFIGURATIPO ON RETRABAJO.TI_HIJO = CONFIGURATIPO.TI_CODIGO ON 
		                      MAESTRO.MA_CODIGO = RETRABAJO.MA_HIJO LEFT OUTER JOIN FACTEXP ON FACTEXPDET.FE_CODIGO=FACTEXP.FE_CODIGO
		WHERE (FACTEXP.CL_PROD IN(SELECT EM_CODIGO FROM CONFIGURACION WHERE CF_EXPLOSDESCADD=''S'')
		AND RETRABAJO.MA_HIJO <> FACTEXPDET.MA_CODIGO)
		AND FACTEXPDET.FE_CODIGO=0'+@FE_CODIGO+' 
		GROUP BY FACTEXPDET.MA_CODIGO, RETRABAJO.MA_HIJO, CONFIGURATIPO.CFT_TIPO, MAESTRO.ME_COM, RETRABAJO.FACTCONV, 
		                      RETRABAJO.ME_GEN, RETRABAJO.RE_INCORPOR, FACTEXPDET.FED_INDICED, MAESTRO.MA_TIP_ENS, 
		                      FACTEXPDET.FED_RETRABAJO, FACTEXPDET.FE_CODIGO, FACTEXPDET.PID_INDICED
		HAVING      (FACTEXPDET.FED_RETRABAJO = ''A'') AND (FACTEXPDET.PID_INDICED = - 1) AND (SUM(RETRABAJO.RE_INCORPOR) > 0)
		UNION
		--PT INCLUIDO EN LA LISTA(CUANDO SE EXPLOSIONA EL SUBENSAMBLE)
		SELECT     FACTEXPDET.MA_CODIGO, RETRABAJO.MA_HIJO, 1 AS FED_CANT, ''S'' AS MA_DISCHARGE, CONFIGURATIPO.CFT_TIPO, 
		                      MAESTRO.ME_COM, RETRABAJO.FACTCONV, RETRABAJO.ME_GEN AS ME_GEN, SUM(FED_CANT)-SUM(RETRABAJO.RE_INCORPOR) 
		                      AS RE_INCORPOR, FACTEXPDET.FED_INDICED, MAESTRO.MA_TIP_ENS, FACTEXPDET.FED_RETRABAJO, 
		                      FACTEXPDET.FE_CODIGO
		FROM         MAESTRO RIGHT OUTER JOIN
		                      FACTEXPDET INNER JOIN
		                      RETRABAJO ON FACTEXPDET.FED_INDICED = RETRABAJO.FETR_INDICED AND RETRABAJO.TIPO_FACTRANS = ''F'' LEFT OUTER JOIN
		                      CONFIGURATIPO ON RETRABAJO.TI_HIJO = CONFIGURATIPO.TI_CODIGO ON 
		                      MAESTRO.MA_CODIGO = RETRABAJO.MA_HIJO LEFT OUTER JOIN FACTEXP ON FACTEXPDET.FE_CODIGO=FACTEXP.FE_CODIGO
		WHERE (FACTEXP.CL_PROD IN(SELECT EM_CODIGO FROM CONFIGURACION WHERE CF_EXPLOSDESCADD=''S'')
		AND RETRABAJO.MA_HIJO = FACTEXPDET.MA_CODIGO)
		AND FACTEXPDET.FE_CODIGO=0'+@FE_CODIGO+' 
		GROUP BY FACTEXPDET.MA_CODIGO, RETRABAJO.MA_HIJO, CONFIGURATIPO.CFT_TIPO, MAESTRO.ME_COM, RETRABAJO.FACTCONV, 
		                      RETRABAJO.ME_GEN, RETRABAJO.RE_INCORPOR, FACTEXPDET.FED_INDICED, MAESTRO.MA_TIP_ENS, 
		                      FACTEXPDET.FED_RETRABAJO, FACTEXPDET.FE_CODIGO, FACTEXPDET.PID_INDICED
		HAVING      (FACTEXPDET.FED_RETRABAJO = ''A'') AND (FACTEXPDET.PID_INDICED = - 1) AND 
				(SUM(FED_CANT)-SUM(RETRABAJO.RE_INCORPOR) > 0)')
*/


GO
