SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_ACTUALIZATASAFACTIMP]  (@fi_codigo int)   as

SET NOCOUNT ON 

declare @fid_indiced int

--	if not exists(select * from arancel where convert(varchar(11),AR_ULTMODIFTIGIE,101)= convert(varchar(11),getdate(),101))
--	exec SP_ACTUALIZAARANCELBASETIGIE



	-- actualiza tasas
	/*UPDATE FACTIMPDET  
	SET FACTIMPDET.FID_POR_DEF= ARANCEL.AR_ADVDEF, FACTIMPDET.SPI_CODIGO=0, 
	FACTIMPDET.FID_SEC_IMP=0 
	FROM  FACTIMPDET INNER JOIN 
	  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO 
	WHERE     (FACTIMPDET.FID_DEF_TIP = 'G') AND FACTIMPDET.FI_CODIGO =@fi_codigo
	
	UPDATE FACTIMPDET  
	SET FACTIMPDET.FID_POR_DEF= ARANCEL.AR_PORCENT_8VA, FACTIMPDET.SPI_CODIGO=0, 
	FACTIMPDET.FID_SEC_IMP=0 
	FROM  FACTIMPDET INNER JOIN 
	  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO 
	WHERE     (FACTIMPDET.FID_DEF_TIP = 'R') AND FACTIMPDET.FI_CODIGO =@fi_codigo
	
	UPDATE FACTIMPDET  
	SET FACTIMPDET.FID_POR_DEF= PAISARA.PAR_BEN, FACTIMPDET.FID_SEC_IMP=0, FACTIMPDET.SPI_CODIGO=22 
	FROM FACTIMPDET INNER JOIN 
	PAISARA ON FACTIMPDET.AR_IMPMX = PAISARA.AR_CODIGO AND FACTIMPDET.PA_CODIGO = PAISARA.PA_CODIGO 
	WHERE (FACTIMPDET.FID_DEF_TIP = 'P') AND FACTIMPDET.FI_CODIGO = @fi_codigo
	AND FACTIMPDET.PA_CODIGO =233

	UPDATE FACTIMPDET  
	SET FACTIMPDET.FID_POR_DEF= PAISARA.PAR_BEN, FACTIMPDET.FID_SEC_IMP=0
	FROM FACTIMPDET INNER JOIN 
	PAISARA ON FACTIMPDET.AR_IMPMX = PAISARA.AR_CODIGO AND FACTIMPDET.SPI_CODIGO = PAISARA.SPI_CODIGO 
	WHERE (FACTIMPDET.FID_DEF_TIP = 'P') AND FACTIMPDET.FI_CODIGO = @fi_codigo
	AND FACTIMPDET.PA_CODIGO <>233

*/
	UPDATE FACTIMPDET
	SET     FACTIMPDET.FID_SEC_IMP= (SELECT SE_CODIGO FROM CONFIGURACION)
	FROM         FACTIMPDET
	WHERE     (FACTIMPDET.FID_DEF_TIP = 'S') AND (FACTIMPDET.FID_SEC_IMP = 0 OR
	                      FACTIMPDET.FID_SEC_IMP IS NULL) AND (FACTIMPDET.FI_CODIGO = @fi_codigo)

	UPDATE FACTIMPDET
	SET     FACTIMPDET.FID_SEC_IMP= MAESTRO.MA_SEC_IMP
	FROM         FACTIMPDET INNER JOIN
	                      MAESTRO ON FACTIMPDET.MA_CODIGO = MAESTRO.MA_CODIGO
	WHERE     (FACTIMPDET.FID_DEF_TIP = 'S') AND (FACTIMPDET.FID_SEC_IMP = 0 OR
	                      FACTIMPDET.FID_SEC_IMP IS NULL) AND (MAESTRO.MA_SEC_IMP > 0) AND (FACTIMPDET.FI_CODIGO = @fi_codigo)
	
/*	UPDATE FACTIMPDET  
	SET   FACTIMPDET.FID_POR_DEF= SECTORARA.SA_PORCENT, FACTIMPDET.SPI_CODIGO=0 
	FROM  FACTIMPDET INNER JOIN 
	 SECTORARA ON FACTIMPDET.AR_IMPMX = SECTORARA.AR_CODIGO AND 
	 FACTIMPDET.FID_SEC_IMP = SECTORARA.SE_CODIGO 
	WHERE (FACTIMPDET.FID_DEF_TIP = 'S') AND FACTIMPDET.FI_CODIGO = @fi_codigo */

	UPDATE FACTIMPDET
	SET FID_POR_DEF=dbo.GetAdvalorem(FACTIMPDET.AR_IMPMX, FACTIMPDET.PA_CODIGO, FACTIMPDET.FID_DEF_TIP, FACTIMPDET.FID_SEC_IMP, FACTIMPDET.SPI_CODIGO)
	WHERE FACTIMPDET.FI_CODIGO = @fi_codigo	

	if (SELECT CF_SINGENERICOUM FROM CONFIGURACION)='S'
	and exists (SELECT MA_GENERICO FROM FACTIMPDET WHERE MA_GENERICO = 0 AND FI_CODIGO = @fi_codigo AND AR_IMPMX > 0)
	begin
		EXEC SP_ADDGENERICOS
	
		UPDATE FACTIMPDET
		SET     FACTIMPDET.MA_GENERICO= MAESTRO.MA_GENERICO, FACTIMPDET.EQ_GEN= MAESTRO.EQ_GEN, FACTIMPDET.ME_GEN= 
		                      MAESTRO_1.ME_COM
		FROM         MAESTRO INNER JOIN
		                      FACTIMPDET ON MAESTRO.MA_CODIGO = FACTIMPDET.MA_CODIGO AND 
		                      MAESTRO.MA_GENERICO <> FACTIMPDET.MA_GENERICO INNER JOIN
		                      MAESTRO MAESTRO_1 ON MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO
		WHERE     (FACTIMPDET.FI_CODIGO = @fi_codigo)
	end

--	IF EXISTS (SELECT EQ_IMPMX FROM FACTIMPDET WHERE (ME_CODIGO <> ME_ARIMPMX) AND (EQ_IMPMX = 1))
	EXEC SP_ACTUALIZAEQARAFACTIMP @fi_codigo


	EXEC SP_ACTUALIZAEQGENFI @fi_codigo 

/*
	UPDATE MAESTRO
	SET     MAESTRO.AR_IMPMX=FACTIMPDET.AR_IMPMX, MAESTRO.AR_EXPMX=FACTIMPDET.AR_IMPMX,
		         MAESTRO.MA_SEC_IMP=FACTIMPDET.FID_SEC_IMP, 
	                       MAESTRO.MA_DEF_TIP=FACTIMPDET.FID_DEF_TIP, 
	                      MAESTRO.SPI_CODIGO=FACTIMPDET.SPI_CODIGO, MAESTRO.EQ_IMPMX=FACTIMPDET.EQ_IMPMX,
		MAESTRO.EQ_GEN=FACTIMPDET.EQ_GEN
	FROM         FACTIMPDET INNER JOIN
	                      MAESTRO ON FACTIMPDET.MA_CODIGO = MAESTRO.MA_CODIGO
	WHERE     (FACTIMPDET.FI_CODIGO =@fi_codigo)*/


GO
