SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_INVENTARIOSAFEHARBOR] (@fechaini datetime, @fechafin datetime)   as

SET NOCOUNT ON 
declare @owner varchar(150)

if @fechafin=''
set @fechafin='01/01/9999'


TRUNCATE TABLE INVENTARIOTEMP 


if not exists (select * from dbo.sysobjects where name='SafeHarborTemp')
CREATE TABLE [dbo].[SafeHarborTemp]
		(PI_CODIGO int,
		NoPedimento varchar(50), 
		FechaPedimento datetime, 
		FechaPagoPedimento datetime, 
		PID_saldoCANT decimal(38,6), 
		ME_CORTO varchar(5), 
		PID_SALDOGEN decimal(38,6), 
		ME_GEN varchar(5), 
		PID_COS_UNI decimal(38,6), 
		MA_CODIGO int, 
		TI_CODIGO int, 
		PID_NOPARTE varchar(50),
		PID_INPUTSCANT	decimal(38,6),
		PID_INPUTSGEN	decimal(38,6),
		PID_OUTPUTSCANT	decimal(38,6),
		PID_OUTPUTSGEN	decimal(38,6))


	TRUNCATE TABLE SafeHarborTemp



			insert into SafeHarborTemp (NoPedimento,  FechaPedimento, FechaPagoPedimento,  PID_saldoCANT, 
		PID_SALDOGEN, PID_COS_UNI, MA_CODIGO, PI_CODIGO, PID_INPUTSCANT, PID_INPUTSGEN, PID_OUTPUTSCANT, PID_OUTPUTSGEN,
		ME_CORTO, ME_GEN)

	-- balance inicial en el periodo en los pedimentos 
		SELECT     dbo.VPEDIMP.[PATENTE-FOLIO] AS NoPedimento, dbo.VPEDIMP.PI_FEC_ENT AS FechaPedimento, 
		                      dbo.VPEDIMP.PI_FEC_PAG AS FechaPagoPedimento, SUM(dbo.PIDESCARGA.PID_SALDOGEN / ISNULL(dbo.PEDIMPDET.EQ_GENERICO, 1)), SUM(dbo.PIDESCARGA.PID_SALDOGEN) AS PID_SALDOGEN, MAX(dbo.PEDIMPDET.PID_COS_UNIGEN) AS PID_COS_UNI, 
		                      dbo.PEDIMPDET.MA_CODIGO, dbo.VPEDIMP.PI_CODIGO, SUM(dbo.PIDESCARGA.PID_SALDOGEN / ISNULL(dbo.PEDIMPDET.EQ_GENERICO, 1)), SUM(dbo.PIDESCARGA.PID_SALDOGEN), 0, 0,
			max(MEDIDA.ME_CORTO), max(MEDIDA_1.ME_CORTO)
		FROM         dbo.VPEDIMP RIGHT OUTER JOIN
		                      dbo.PEDIMPDET ON dbo.VPEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO LEFT OUTER JOIN
			     dbo.PIDESCARGA ON dbo.PEDIMPDET.PID_INDICED=dbo.PIDESCARGA.PID_INDICED LEFT OUTER JOIN 
			      MEDIDA ON dbo.PEDIMPDET.ME_CODIGO=MEDIDA.ME_CODIGO LEFT OUTER JOIN 
			      MEDIDA MEDIDA_1 ON dbo.PEDIMPDET.ME_GENERICO=MEDIDA_1.ME_CODIGO
		WHERE     (dbo.VPEDIMP.PI_ESTATUS <> 'R') AND dbo.VPEDIMP.PI_FEC_ENT<=@fechafin
			and ISNULL(dbo.PEDIMPDET.EQ_GENERICO, 1) <>0 AND (dbo.VPEDIMP.CP_CODIGO IN
			(SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IV', 'VT'))
			OR CP_RECTIFICA IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IV', 'VT'))	)	
			and dbo.PEDIMPDET.PID_IMPRIMIR='S' 
		GROUP BY dbo.VPEDIMP.[PATENTE-FOLIO], dbo.VPEDIMP.PI_FEC_PAG, 
		                       dbo.PEDIMPDET.MA_CODIGO, dbo.VPEDIMP.PI_FEC_ENT, dbo.VPEDIMP.PI_CODIGO, ISNULL(dbo.PEDIMPDET.EQ_GENERICO, 1)
		HAVING      (SUM(dbo.PEDIMPDET.PID_CAN_GEN) > 0) AND (dbo.VPEDIMP.[PATENTE-FOLIO] IS NOT NULL)
	union	
		-- para que sea balance inicial se suman las descargas que se hicieron despues de la fecha inicial.
		-- se suma la cantidad que ha sido descargada y se debe tomar en cuenta en base a la fecha de la factura de exportacion 
		SELECT     dbo.VPEDIMP.[PATENTE-FOLIO] AS NoPedimento, MAX(dbo.VINVENTARIOKARSUM.FE_FECHA), 
		                      MAX(dbo.VPEDIMP.PI_FEC_PAG) AS FechaPagoPedimento, SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC / ISNULL(dbo.PEDIMPDET.EQ_GENERICO, 1)) 
		                      AS PID_saldoCANT, SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC) AS PID_SALDOGEN, MAX(dbo.PEDIMPDET.PID_COS_UNIGEN) AS PID_COS_UNI,
		                       dbo.PEDIMPDET.MA_CODIGO, dbo.VPEDIMP.PI_CODIGO, SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC / ISNULL(dbo.MAESTRO.EQ_GEN, 1)),
			SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC), 0, 0, max(MEDIDA.ME_CORTO), max(MEDIDA_1.ME_CORTO)
		FROM         dbo.VINVENTARIOKARSUM RIGHT OUTER JOIN
		                      dbo.PEDIMPDET ON dbo.VINVENTARIOKARSUM.KAP_INDICED_PED = dbo.PEDIMPDET.PID_INDICED LEFT OUTER JOIN
		                      dbo.VPEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO LEFT OUTER JOIN
		                      dbo.MAESTRO ON dbo.PEDIMPDET.MA_GENERICO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN 
			      MEDIDA ON dbo.PEDIMPDET.ME_CODIGO=MEDIDA.ME_CODIGO LEFT OUTER JOIN 
			      MEDIDA MEDIDA_1 ON dbo.PEDIMPDET.ME_GENERICO=MEDIDA_1.ME_CODIGO
		WHERE     (dbo.VPEDIMP.PI_ESTATUS <> 'R')  AND dbo.VINVENTARIOKARSUM.FE_FECHA>=@fechaini
			and dbo.VPEDIMP.PI_FEC_ENT<=@fechafin AND (dbo.VPEDIMP.CP_CODIGO IN
			(SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IV', 'VT') 
			OR CP_RECTIFICA IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IV', 'VT'))	))
			and dbo.PEDIMPDET.PID_IMPRIMIR='S'
		GROUP BY dbo.VPEDIMP.[PATENTE-FOLIO], dbo.PEDIMPDET.MA_CODIGO, dbo.VPEDIMP.PI_CODIGO
		HAVING      (dbo.VPEDIMP.[PATENTE-FOLIO] IS NOT NULL) AND (SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC) > 0)
	union
	-- salidas en el periodo de los pedimentos de acuerdo a descargas
		SELECT dbo.VPEDIMP.[PATENTE-FOLIO] AS NoPedimento, MAX(dbo.VINVENTARIOKARSUM.FE_FECHA), 
		                      MAX(dbo.VPEDIMP.PI_FEC_PAG) AS FechaPagoPedimento, 0, 0, MAX(dbo.PEDIMPDET.PID_COS_UNIGEN),
		                       dbo.PEDIMPDET.MA_CODIGO, dbo.VPEDIMP.PI_CODIGO, 0, 0, SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC / ISNULL(dbo.MAESTRO.EQ_GEN, 1)),
			SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC), max(MEDIDA.ME_CORTO), max(MEDIDA_1.ME_CORTO)
		FROM         dbo.VINVENTARIOKARSUM RIGHT OUTER JOIN
		                      dbo.PEDIMPDET ON dbo.VINVENTARIOKARSUM.KAP_INDICED_PED = dbo.PEDIMPDET.PID_INDICED LEFT OUTER JOIN
		                      dbo.VPEDIMP ON dbo.PEDIMPDET.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO LEFT OUTER JOIN
		                      dbo.MAESTRO ON dbo.PEDIMPDET.MA_GENERICO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN 
			      MEDIDA ON dbo.PEDIMPDET.ME_CODIGO=MEDIDA.ME_CODIGO LEFT OUTER JOIN 
			      MEDIDA MEDIDA_1 ON dbo.PEDIMPDET.ME_GENERICO=MEDIDA_1.ME_CODIGO
		WHERE     (dbo.VPEDIMP.PI_ESTATUS <> 'R')  and dbo.VINVENTARIOKARSUM.FE_FECHA>=@fechaini
			and dbo.VINVENTARIOKARSUM.FE_FECHA<=@fechafin
			and dbo.VPEDIMP.PI_FEC_ENT<=@fechafin and (dbo.VPEDIMP.CP_CODIGO IN
			(SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IV', 'VT')) 
			OR dbo.VPEDIMP.CP_RECTIFICA IN (SELECT CP_CODIGO FROM CONFIGURACLAVEPED WHERE CCP_TIPO IN ('IT', 'IV', 'VT'))	)
			and dbo.PEDIMPDET.PID_IMPRIMIR='S'
		GROUP BY dbo.VPEDIMP.[PATENTE-FOLIO], dbo.PEDIMPDET.MA_CODIGO, dbo.VPEDIMP.PI_CODIGO
		HAVING      (SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC) > 0)



-- se hace la sumatoria
		insert into INVENTARIOTEMP (NoPedimento,  FechaPedimento, FechaPagoPedimento,  PID_saldoCANT, ME_CORTO, 
			PID_SALDOGEN, ME_GEN, PID_COS_UNI, MA_CODIGO, TI_CODIGO, PID_NOPARTE, PI_CODIGO, 
			PID_INPUTSCANT, PID_INPUTSGEN, PID_OUTPUTSCANT, PID_OUTPUTSGEN)

		select NoPedimento,  FechaPedimento, max(FechaPagoPedimento),  round(sum(PID_saldoCANT),6), ME_CORTO, 
		round(sum(PID_SALDOGEN),6), ME_GEN, max(PID_COS_UNI), MA_CODIGO, TI_CODIGO, 
		PID_NOPARTE,  PI_CODIGO, round(sum(PID_INPUTSCANT),6), round(sum(PID_INPUTSGEN),6), round(sum(PID_OUTPUTSCANT),6), round(sum(PID_OUTPUTSGEN),6)
		from SafeHarborTemp
		group by NoPedimento,  FechaPedimento, ME_CORTO, ME_GEN, MA_CODIGO, TI_CODIGO, PID_NOPARTE, PI_CODIGO
		order by MA_CODIGO, FechaPedimento


		UPDATE dbo.INVENTARIOTEMP
		SET     dbo.INVENTARIOTEMP.PID_NOPARTE= dbo.MAESTRO.MA_NOPARTE
		FROM         dbo.INVENTARIOTEMP LEFT OUTER JOIN
		                      dbo.MAESTRO ON dbo.INVENTARIOTEMP.MA_CODIGO = dbo.MAESTRO.MA_CODIGO
		UPDATE dbo.INVENTARIOTEMP
		SET FECHAINI=@fechaini,
		FECHAFIN=@fechafin


	exec sp_droptable 'SafeHarborTemp'

GO
