SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SP_regresaNumParteBorradosUsados]   as



INSERT INTO MAESTRO(MA_NOPARTE, MA_CODIGO, MA_NOMBRE, MA_NAME, ME_COM, MA_GENERICO, EQ_GEN, EQ_IMPMX, AR_IMPMX, 
                      AR_EXPFO, MA_SEC_IMP, MA_DEF_TIP, CS_CODIGO, TI_CODIGO, PA_ORIGEN, PA_PROCEDE, SPI_CODIGO, EQ_EXPFO, 
                      SE_CODIGO)
SELECT     PID_NOPARTE, MAX(MA_CODIGO), MAX(PID_NOMBRE), MAX(PID_NAME), MAX(ME_CODIGO), MAX(MA_GENERICO), MAX(EQ_GENERICO), MAX(EQ_IMPMX), MAX(AR_IMPMX), 
                      MAX(AR_EXPFO), MAX(ISNULL(PID_SEC_IMP,0)), MAX(ISNULL(PID_DEF_TIP,'G')), MAX(ISNULL(CS_CODIGO,8)), MAX(TI_CODIGO), MAX(ISNULL(PA_ORIGEN,233)), MAX(ISNULL(PA_PROCEDE,233)), MAX(SPI_CODIGO), MAX(EQ_EXPFO), 
                      MAX(SE_CODIGO)
FROM         PEDIMPDET
GROUP BY PID_NOPARTE
HAVING    MAX(MA_CODIGO) NOT IN (SELECT MA_CODIGO FROM MAESTRO) AND PID_NOPARTE NOT IN (SELECT MA_NOPARTE FROM MAESTRO)



























GO
