SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[SP_arreglaLigaAll]   as



-- se hace la liga con detalles de facturas 

	exec sp_droptable 'pi_codigo_temp'
	
	create table [dbo].[pi_codigo_temp] (codigo integer)

	  insert into pi_codigo_temp 
	             SELECT     FACTIMP.PI_CODIGO
		FROM         FACTIMP INNER JOIN
		                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO INNER JOIN
		                      PEDIMP ON FACTIMP.PI_CODIGO = PEDIMP.PI_CODIGO
		WHERE     (FACTIMPDET.PID_INDICEDLIGA = - 1 OR
		                      FACTIMPDET.PID_INDICEDLIGA IS NULL) AND (PEDIMP.PI_ESTATUS IN ('S', 'B')) 
		GROUP BY FACTIMP.PI_CODIGO
		UNION
		SELECT     FACTIMP.PI_RECTIFICA
		FROM         FACTIMP INNER JOIN
		                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO INNER JOIN
		                      PEDIMP ON FACTIMP.PI_RECTIFICA = PEDIMP.PI_CODIGO
		WHERE     (FACTIMPDET.PID_INDICEDLIGAR1 = - 1 OR
		                      FACTIMPDET.PID_INDICEDLIGAR1 IS NULL) AND (PEDIMP.PI_ESTATUS IN ('N', 'T')) 
			AND (FACTIMP.PI_CODIGO is not null and FACTIMP.PI_CODIGO<>-1)
		GROUP BY FACTIMP.PI_RECTIFICA
		UNION

			SELECT     FACTEXP.PI_CODIGO
			FROM         FACTEXP INNER JOIN
			                      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO INNER JOIN
			                      PEDIMP ON FACTEXP.PI_CODIGO = PEDIMP.PI_CODIGO
			WHERE     (FACTEXPDET.PID_INDICEDLIGA = - 1 OR
			                      FACTEXPDET.PID_INDICEDLIGA IS NULL) AND (PEDIMP.PI_ESTATUS IN ('L')) 
	
				AND FACTEXP.PI_CODIGO NOT IN 
					(SELECT     PEDIMP.PI_CODIGO
					FROM         CONFIGURACLAVEPED INNER JOIN
					                      PEDIMP ON CONFIGURACLAVEPED.CP_CODIGO = PEDIMP.CP_CODIGO
					WHERE     (CONFIGURACLAVEPED.CCP_TIPO = 'CN'))
			GROUP BY FACTEXP.PI_CODIGO
	
			UNION
	
			SELECT     FACTEXP.PI_RECTIFICA
			FROM         FACTEXP INNER JOIN
			                      FACTEXPDET ON FACTEXP.FE_CODIGO = FACTEXPDET.FE_CODIGO INNER JOIN
			                      PEDIMP ON FACTEXP.PI_RECTIFICA = PEDIMP.PI_CODIGO
			WHERE     (FACTEXPDET.PID_INDICEDLIGAR1 = - 1 OR
			                      FACTEXPDET.PID_INDICEDLIGAR1 IS NULL) AND (PEDIMP.PI_ESTATUS IN ('O', 'N')) 
			AND (FACTEXP.PI_CODIGO is not null and FACTEXP.PI_CODIGO<>-1) AND
	
				FACTEXP.PI_RECTIFICA NOT IN (SELECT     PEDIMP.PI_CODIGO
				FROM         CONFIGURACLAVEPED INNER JOIN
				                      PEDIMP ON CONFIGURACLAVEPED.CP_CODIGO = PEDIMP.CP_CODIGO
				WHERE     (CONFIGURACLAVEPED.CCP_TIPO = 'CN'))
			GROUP BY FACTEXP.PI_RECTIFICA
		union
			select pi_codigo from pedimp where pi_codigo not in (select pi_codigo from pedimpdet) 
			and pi_codigo NOT IN (SELECT     PEDIMP.PI_CODIGO
					FROM         CONFIGURACLAVEPED INNER JOIN
					                      PEDIMP ON CONFIGURACLAVEPED.CP_CODIGO = PEDIMP.CP_CODIGO
					WHERE     (CONFIGURACLAVEPED.CCP_TIPO = 'CN'))
		union
			select pedimpdet.pi_codigo from pedimpdet inner join pedimp on pedimpdet.pi_codigo=pedimp.pi_codigo
			where pi_movimiento='E' and pid_indiced not in (select pid_indicedliga from factimpdet inner join factimp on factimpdet.fi_codigo=factimp.fi_codigo where factimp.pi_codigo=pedimpdet.pi_codigo) 
			and pedimp.pi_estatus<>'R'
			and pedimpdet.pi_codigo NOT IN (SELECT     PEDIMP.PI_CODIGO
					FROM         CONFIGURACLAVEPED INNER JOIN
					                      PEDIMP ON CONFIGURACLAVEPED.CP_CODIGO = PEDIMP.CP_CODIGO
					WHERE     (CONFIGURACLAVEPED.CCP_TIPO = 'RE'))
			group by pedimpdet.pi_codigo
		union
			select pedimpdet.pi_codigo from pedimpdet inner join pedimp on pedimpdet.pi_codigo=pedimp.pi_codigo
			where pi_movimiento='E' and pid_indiced not in (select pid_indicedligar1 from factimpdet inner join factimp on factimpdet.fi_codigo=factimp.fi_codigo where factimp.pi_rectifica=pedimpdet.pi_codigo) 
			and pedimpdet.pi_codigo IN (SELECT     PEDIMP.PI_CODIGO
					FROM         CONFIGURACLAVEPED INNER JOIN
					                      PEDIMP ON CONFIGURACLAVEPED.CP_CODIGO = PEDIMP.CP_CODIGO
					WHERE     (CONFIGURACLAVEPED.CCP_TIPO = 'RE'))
			group by pedimpdet.pi_codigo
		
	
	

		-- ACTIVO FIJO
			UPDATE FACTIMPDET
			SET     FACTIMPDET.PID_INDICEDLIGA =PEDIMPDET.PID_INDICED
			FROM         FACTIMPDET INNER JOIN
	                      PEDIMPDET ON FACTIMPDET.MA_CODIGO = PEDIMPDET.MA_CODIGO 			
			AND FACTIMPDET.FID_NOPARTE = PEDIMPDET.PID_NOPARTE 
			AND FACTIMPDET.FID_NOMBRE = PEDIMPDET.PID_NOMBRE
			AND  ISNULL(FACTIMPDET.ME_CODIGO, 0) = ISNULL(PEDIMPDET.ME_CODIGO, 0) 
			AND ISNULL(FACTIMPDET.MA_GENERICO, 0) = ISNULL(PEDIMPDET.MA_GENERICO, 0) 
			AND ISNULL(FACTIMPDET.FID_ORD_COMP, 0) = ISNULL(PEDIMPDET.PID_ORD_COMP, 0) 
			AND ISNULL(FACTIMPDET.AR_IMPMX, 0) = ISNULL(PEDIMPDET.AR_IMPMX, 0) 
			AND ISNULL(FACTIMPDET.FID_RATEEXPFO, - 1) = ISNULL(PEDIMPDET.PID_RATEEXPFO, - 1) 
			AND ISNULL(FACTIMPDET.FID_SEC_IMP, 0) = ISNULL(PEDIMPDET.PID_SEC_IMP, 0) 
			AND round(ISNULL(FACTIMPDET.FID_COS_UNI, 0),6) = round(ISNULL(PEDIMPDET.PID_COS_UNI, 0) ,6)
			AND ISNULL(FACTIMPDET.FID_DEF_TIP, 'G') = ISNULL(PEDIMPDET.PID_DEF_TIP, 'G') 
			AND ISNULL(FACTIMPDET.FID_POR_DEF, - 1) = ISNULL(PEDIMPDET.PID_POR_DEF, - 1) 
			AND ISNULL(FACTIMPDET.PA_CODIGO, 0) = ISNULL(PEDIMPDET.PA_ORIGEN, 0) 
			AND ISNULL(FACTIMPDET.SPI_CODIGO, 0) = ISNULL(PEDIMPDET.SPI_CODIGO, 0) 
			AND ISNULL(FACTIMPDET.CS_CODIGO, 8) = isnull(PEDIMPDET.CS_CODIGO ,8)			
			AND isnull(PEDIMPDET.PID_CODIGOFACT, 0) = isnull(FACTIMPDET.FI_CODIGO, 0)
			INNER JOIN FACTIMP ON PEDIMPDET.PI_CODIGO = FACTIMP.PI_CODIGO AND FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
			LEFT OUTER JOIN  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO
			LEFT OUTER JOIN  ARANCEL ARANCEL_1 ON PEDIMPDET.AR_IMPMX = ARANCEL_1.AR_CODIGO			
			INNER JOIN PEDIMP ON PEDIMPDET.PI_CODIGO= PEDIMP.PI_CODIGO
			LEFT OUTER JOIN CONFIGURACLAVEPED ON PEDIMP.CP_CODIGO=CONFIGURACLAVEPED.CP_CODIGO
			WHERE ccp_tipo in ('IA', 'IM')
			and PEDIMPDET.pi_codigo in (select codigo from pi_codigo_temp group by codigo)
			and PEDIMPDET.pi_codigo in (SELECT PI_CODIGO FROM PEDIMPSAAICONFIG WHERE PICF_SAAIDETDIVFACT='S')


			UPDATE FACTIMPDET
			SET     FACTIMPDET.PID_INDICEDLIGA =PEDIMPDET.PID_INDICED
			FROM         FACTIMPDET INNER JOIN
	                      PEDIMPDET ON FACTIMPDET.MA_CODIGO = PEDIMPDET.MA_CODIGO 			
			AND FACTIMPDET.FID_NOPARTE = PEDIMPDET.PID_NOPARTE 
			AND FACTIMPDET.FID_NOMBRE = PEDIMPDET.PID_NOMBRE 
			AND  ISNULL(FACTIMPDET.ME_CODIGO, 0) = ISNULL(PEDIMPDET.ME_CODIGO, 0) 
			AND ISNULL(FACTIMPDET.MA_GENERICO, 0) = ISNULL(PEDIMPDET.MA_GENERICO, 0) 
			AND ISNULL(FACTIMPDET.FID_ORD_COMP, 0) = ISNULL(PEDIMPDET.PID_ORD_COMP, 0) 
			AND ISNULL(FACTIMPDET.AR_IMPMX, 0) = ISNULL(PEDIMPDET.AR_IMPMX, 0) 
			AND ISNULL(FACTIMPDET.FID_RATEEXPFO, - 1) = ISNULL(PEDIMPDET.PID_RATEEXPFO, - 1) 
			AND ISNULL(FACTIMPDET.FID_SEC_IMP, 0) = ISNULL(PEDIMPDET.PID_SEC_IMP, 0) 
			AND round(ISNULL(FACTIMPDET.FID_COS_UNI, 0),6) = round(ISNULL(PEDIMPDET.PID_COS_UNI, 0),6)
			AND ISNULL(FACTIMPDET.FID_DEF_TIP, 'G') = ISNULL(PEDIMPDET.PID_DEF_TIP, 'G') 			
			AND ISNULL(FACTIMPDET.FID_POR_DEF, - 1) = ISNULL(PEDIMPDET.PID_POR_DEF, - 1) 
			AND ISNULL(FACTIMPDET.PA_CODIGO, 0) = ISNULL(PEDIMPDET.PA_ORIGEN, 0) 
			AND ISNULL(FACTIMPDET.SPI_CODIGO, 0) = ISNULL(PEDIMPDET.SPI_CODIGO, 0) 
			AND ISNULL(FACTIMPDET.CS_CODIGO, 8) = isnull(PEDIMPDET.CS_CODIGO ,8)			
			INNER JOIN FACTIMP ON PEDIMPDET.PI_CODIGO = FACTIMP.PI_CODIGO AND FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
			LEFT OUTER JOIN  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO
			LEFT OUTER JOIN  ARANCEL ARANCEL_1 ON PEDIMPDET.AR_IMPMX = ARANCEL_1.AR_CODIGO		
			INNER JOIN PEDIMP ON PEDIMPDET.PI_CODIGO= PEDIMP.PI_CODIGO
			LEFT OUTER JOIN CONFIGURACLAVEPED ON PEDIMP.CP_CODIGO=CONFIGURACLAVEPED.CP_CODIGO
			WHERE ccp_tipo in ('IA', 'IM')
			and PEDIMPDET.pi_codigo in (select codigo from pi_codigo_temp group by codigo)
			and PEDIMPDET.pi_codigo in (SELECT PI_CODIGO FROM PEDIMPSAAICONFIG WHERE PICF_SAAIDETDIVFACT<>'S')


	
	
				UPDATE FACTIMPDET
				SET     FACTIMPDET.PID_INDICEDLIGA =PEDIMPDET.PID_INDICED
				FROM         FACTIMPDET INNER JOIN
		                      PEDIMPDET ON FACTIMPDET.MA_CODIGO = PEDIMPDET.MA_CODIGO 			
				AND FACTIMPDET.FID_NOPARTE = PEDIMPDET.PID_NOPARTE 
				AND  ISNULL(FACTIMPDET.ME_CODIGO, 0) = ISNULL(PEDIMPDET.ME_CODIGO, 0) 
				AND ISNULL(FACTIMPDET.MA_GENERICO, 0) = ISNULL(PEDIMPDET.MA_GENERICO, 0) 
				AND ISNULL(FACTIMPDET.FID_ORD_COMP, 0) = ISNULL(PEDIMPDET.PID_ORD_COMP, 0) 
				AND ISNULL(FACTIMPDET.AR_IMPMX, 0) = ISNULL(PEDIMPDET.AR_IMPMX, 0) 
				AND ISNULL(FACTIMPDET.FID_RATEEXPFO, - 1) = ISNULL(PEDIMPDET.PID_RATEEXPFO, - 1) 
				AND ISNULL(FACTIMPDET.FID_SEC_IMP, 0) = ISNULL(PEDIMPDET.PID_SEC_IMP, 0) 
				AND ISNULL(FACTIMPDET.FID_DEF_TIP, 'G') = ISNULL(PEDIMPDET.PID_DEF_TIP, 'G') 
				AND ISNULL(FACTIMPDET.FID_POR_DEF, - 1) = ISNULL(PEDIMPDET.PID_POR_DEF, - 1) 
				AND ISNULL(FACTIMPDET.PA_CODIGO, 0) = ISNULL(PEDIMPDET.PA_ORIGEN, 0) 
				AND ISNULL(FACTIMPDET.SPI_CODIGO, 0) = ISNULL(PEDIMPDET.SPI_CODIGO, 0) 
				AND ISNULL(FACTIMPDET.CS_CODIGO, 8) = isnull(PEDIMPDET.CS_CODIGO ,8)			
				AND isnull(PEDIMPDET.PID_CODIGOFACT, 0) = isnull(FACTIMPDET.FI_CODIGO, 0)
				INNER JOIN FACTIMP ON PEDIMPDET.PI_CODIGO = FACTIMP.PI_CODIGO AND FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
				LEFT OUTER JOIN  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO
				LEFT OUTER JOIN  ARANCEL ARANCEL_1 ON PEDIMPDET.AR_IMPMX = ARANCEL_1.AR_CODIGO			
				INNER JOIN PEDIMP ON PEDIMPDET.PI_CODIGO= PEDIMP.PI_CODIGO
				LEFT OUTER JOIN CONFIGURACLAVEPED ON PEDIMP.CP_CODIGO=CONFIGURACLAVEPED.CP_CODIGO
				WHERE ccp_tipo not in ('IA', 'IM', 'RE')
				and PEDIMPDET.pi_codigo in (select codigo from pi_codigo_temp group by codigo)
				and PEDIMPDET.pi_codigo in (SELECT PI_CODIGO FROM PEDIMPSAAICONFIG WHERE PICF_SAAIDETDIVFACT='S')


				UPDATE FACTIMPDET
				SET     FACTIMPDET.PID_INDICEDLIGA =PEDIMPDET.PID_INDICED
				FROM         FACTIMPDET INNER JOIN
		                      PEDIMPDET ON FACTIMPDET.MA_CODIGO = PEDIMPDET.MA_CODIGO 			
				AND FACTIMPDET.FID_NOPARTE = PEDIMPDET.PID_NOPARTE 
				AND  ISNULL(FACTIMPDET.ME_CODIGO, 0) = ISNULL(PEDIMPDET.ME_CODIGO, 0) 
				AND ISNULL(FACTIMPDET.MA_GENERICO, 0) = ISNULL(PEDIMPDET.MA_GENERICO, 0) 
				AND ISNULL(FACTIMPDET.FID_ORD_COMP, 0) = ISNULL(PEDIMPDET.PID_ORD_COMP, 0) 
				AND ISNULL(FACTIMPDET.AR_IMPMX, 0) = ISNULL(PEDIMPDET.AR_IMPMX, 0) 
				AND ISNULL(FACTIMPDET.FID_RATEEXPFO, - 1) = ISNULL(PEDIMPDET.PID_RATEEXPFO, - 1) 
				AND ISNULL(FACTIMPDET.FID_SEC_IMP, 0) = ISNULL(PEDIMPDET.PID_SEC_IMP, 0) 
				AND ISNULL(FACTIMPDET.FID_DEF_TIP, 'G') = ISNULL(PEDIMPDET.PID_DEF_TIP, 'G') 				
				AND ISNULL(FACTIMPDET.FID_POR_DEF, - 1) = ISNULL(PEDIMPDET.PID_POR_DEF, - 1) 
				AND ISNULL(FACTIMPDET.PA_CODIGO, 0) = ISNULL(PEDIMPDET.PA_ORIGEN, 0) 
				AND ISNULL(FACTIMPDET.SPI_CODIGO, 0) = ISNULL(PEDIMPDET.SPI_CODIGO, 0) 
				AND ISNULL(FACTIMPDET.CS_CODIGO, 8) = isnull(PEDIMPDET.CS_CODIGO ,8)			
--				AND  ISNULL(FACTIMPDET.FID_CANT_ST, 0) = ISNULL(PEDIMPDET.PID_CANT, 0) 
				INNER JOIN FACTIMP ON PEDIMPDET.PI_CODIGO = FACTIMP.PI_CODIGO AND FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
				LEFT OUTER JOIN  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO
				LEFT OUTER JOIN  ARANCEL ARANCEL_1 ON PEDIMPDET.AR_IMPMX = ARANCEL_1.AR_CODIGO			
				INNER JOIN PEDIMP ON PEDIMPDET.PI_CODIGO= PEDIMP.PI_CODIGO
				LEFT OUTER JOIN CONFIGURACLAVEPED ON PEDIMP.CP_CODIGO=CONFIGURACLAVEPED.CP_CODIGO
				WHERE ccp_tipo not in ('IA', 'IM', 'RE')
				and PEDIMPDET.pi_codigo in (select codigo from pi_codigo_temp group by codigo)	
				and PEDIMPDET.pi_codigo in (SELECT PI_CODIGO FROM PEDIMPSAAICONFIG WHERE PICF_SAAIDETDIVFACT<>'S')


				--R1 DE ACTIVO FIJO

					UPDATE FACTIMPDET
					SET     FACTIMPDET.PID_INDICEDLIGAR1 =PEDIMPDET.PID_INDICED
					FROM         FACTIMPDET INNER JOIN
			                      PEDIMPDET ON FACTIMPDET.MA_CODIGO = PEDIMPDET.MA_CODIGO 
					AND FACTIMPDET.FID_NOPARTE = PEDIMPDET.PID_NOPARTE 
					AND FACTIMPDET.FID_NOMBRE = PEDIMPDET.PID_NOMBRE
					AND  ISNULL(FACTIMPDET.ME_CODIGO, 0) = ISNULL(PEDIMPDET.ME_CODIGO, 0) 
					AND ISNULL(FACTIMPDET.MA_GENERICO, 0) = ISNULL(PEDIMPDET.MA_GENERICO, 0) 
					AND ISNULL(FACTIMPDET.FID_ORD_COMP, 0) = ISNULL(PEDIMPDET.PID_ORD_COMP, 0) 
					AND ISNULL(FACTIMPDET.AR_IMPMX, 0) = ISNULL(PEDIMPDET.AR_IMPMX, 0) 
					AND ISNULL(FACTIMPDET.FID_RATEEXPFO, - 1) = ISNULL(PEDIMPDET.PID_RATEEXPFO, - 1) 
					AND ISNULL(FACTIMPDET.FID_SEC_IMP, 0) = ISNULL(PEDIMPDET.PID_SEC_IMP, 0) 
					AND round(ISNULL(FACTIMPDET.FID_COS_UNI, 0),6) = round(ISNULL(PEDIMPDET.PID_COS_UNI, 0) ,6)
					AND ISNULL(FACTIMPDET.FID_DEF_TIP, 'G') = ISNULL(PEDIMPDET.PID_DEF_TIP, 'G') 
					AND ISNULL(FACTIMPDET.FID_POR_DEF, - 1) = ISNULL(PEDIMPDET.PID_POR_DEF, - 1) 			
					AND ISNULL(FACTIMPDET.PA_CODIGO, 0) = ISNULL(PEDIMPDET.PA_ORIGEN, 0) 
					AND ISNULL(FACTIMPDET.SPI_CODIGO, 0) = ISNULL(PEDIMPDET.SPI_CODIGO, 0) 
					AND ISNULL(FACTIMPDET.CS_CODIGO, 8) = isnull(PEDIMPDET.CS_CODIGO ,8)
					AND isnull(PEDIMPDET.PID_CODIGOFACT, 0) = isnull(FACTIMPDET.FI_CODIGO, 0)
					INNER JOIN
			                      FACTIMP ON PEDIMPDET.PI_CODIGO = FACTIMP.PI_RECTIFICA AND FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
					LEFT OUTER JOIN  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO
					LEFT OUTER JOIN  ARANCEL ARANCEL_1 ON PEDIMPDET.AR_IMPMX = ARANCEL_1.AR_CODIGO			
					INNER JOIN PEDIMP ON PEDIMPDET.PI_CODIGO= PEDIMP.PI_CODIGO
					LEFT OUTER JOIN CONFIGURACLAVEPED ON PEDIMP.CP_CODIGO=CONFIGURACLAVEPED.CP_CODIGO
					LEFT OUTER JOIN CONFIGURACLAVEPED C2 ON PEDIMP.CP_RECTIFICA=C2.CP_CODIGO
					WHERE CONFIGURACLAVEPED.ccp_tipo ='RE' AND C2.CCP_TIPO in ('IA', 'IM')
					and PEDIMP.pi_codigo in (SELECT PI_CODIGO FROM PEDIMPSAAICONFIG WHERE PICF_SAAIDETDIVFACT='S')


					UPDATE FACTIMPDET
					SET     FACTIMPDET.PID_INDICEDLIGAR1 =PEDIMPDET.PID_INDICED
					FROM         FACTIMPDET INNER JOIN
			                      PEDIMPDET ON FACTIMPDET.MA_CODIGO = PEDIMPDET.MA_CODIGO 
					AND FACTIMPDET.FID_NOPARTE = PEDIMPDET.PID_NOPARTE 
					AND FACTIMPDET.FID_NOMBRE = PEDIMPDET.PID_NOMBRE
					AND  ISNULL(FACTIMPDET.ME_CODIGO, 0) = ISNULL(PEDIMPDET.ME_CODIGO, 0) 
					AND ISNULL(FACTIMPDET.MA_GENERICO, 0) = ISNULL(PEDIMPDET.MA_GENERICO, 0) 
					AND ISNULL(FACTIMPDET.FID_ORD_COMP, 0) = ISNULL(PEDIMPDET.PID_ORD_COMP, 0) 
					AND ISNULL(FACTIMPDET.AR_IMPMX, 0) = ISNULL(PEDIMPDET.AR_IMPMX, 0) 
					AND ISNULL(FACTIMPDET.FID_RATEEXPFO, - 1) = ISNULL(PEDIMPDET.PID_RATEEXPFO, - 1) 
					AND ISNULL(FACTIMPDET.FID_SEC_IMP, 0) = ISNULL(PEDIMPDET.PID_SEC_IMP, 0) 
					AND round(ISNULL(FACTIMPDET.FID_COS_UNI, 0),6) = round(ISNULL(PEDIMPDET.PID_COS_UNI, 0) ,6)
					AND ISNULL(FACTIMPDET.FID_DEF_TIP, 'G') = ISNULL(PEDIMPDET.PID_DEF_TIP, 'G') 
					AND ISNULL(FACTIMPDET.FID_POR_DEF, - 1) = ISNULL(PEDIMPDET.PID_POR_DEF, - 1) 			
					AND ISNULL(FACTIMPDET.PA_CODIGO, 0) = ISNULL(PEDIMPDET.PA_ORIGEN, 0) 
					AND ISNULL(FACTIMPDET.SPI_CODIGO, 0) = ISNULL(PEDIMPDET.SPI_CODIGO, 0) 
					AND ISNULL(FACTIMPDET.CS_CODIGO, 8) = isnull(PEDIMPDET.CS_CODIGO ,8)
					INNER JOIN
			                      FACTIMP ON PEDIMPDET.PI_CODIGO = FACTIMP.PI_RECTIFICA AND FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
					LEFT OUTER JOIN  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO
					LEFT OUTER JOIN  ARANCEL ARANCEL_1 ON PEDIMPDET.AR_IMPMX = ARANCEL_1.AR_CODIGO			
					INNER JOIN PEDIMP ON PEDIMPDET.PI_CODIGO= PEDIMP.PI_CODIGO
					LEFT OUTER JOIN CONFIGURACLAVEPED ON PEDIMP.CP_CODIGO=CONFIGURACLAVEPED.CP_CODIGO
					LEFT OUTER JOIN CONFIGURACLAVEPED C2 ON PEDIMP.CP_RECTIFICA=C2.CP_CODIGO
					WHERE CONFIGURACLAVEPED.ccp_tipo ='RE' AND C2.CCP_TIPO in ('IA', 'IM')
					and PEDIMP.pi_codigo in (SELECT PI_CODIGO FROM PEDIMPSAAICONFIG WHERE PICF_SAAIDETDIVFACT<>'S')




				--R1 <> DE ACTIVO FIJO
	
					UPDATE FACTIMPDET
					SET     FACTIMPDET.PID_INDICEDLIGAR1 =PEDIMPDET.PID_INDICED
					FROM         FACTIMPDET INNER JOIN
			                      PEDIMPDET ON FACTIMPDET.MA_CODIGO = PEDIMPDET.MA_CODIGO 
					AND FACTIMPDET.FID_NOPARTE = PEDIMPDET.PID_NOPARTE 
					AND  ISNULL(FACTIMPDET.ME_CODIGO, 0) = ISNULL(PEDIMPDET.ME_CODIGO, 0) 
					AND ISNULL(FACTIMPDET.MA_GENERICO, 0) = ISNULL(PEDIMPDET.MA_GENERICO, 0) 
					AND ISNULL(FACTIMPDET.FID_ORD_COMP, 0) = ISNULL(PEDIMPDET.PID_ORD_COMP, 0) 
					AND ISNULL(FACTIMPDET.AR_IMPMX, 0) = ISNULL(PEDIMPDET.AR_IMPMX, 0) 
					AND ISNULL(FACTIMPDET.FID_RATEEXPFO, - 1) = ISNULL(PEDIMPDET.PID_RATEEXPFO, - 1) 
					AND ISNULL(FACTIMPDET.FID_SEC_IMP, 0) = ISNULL(PEDIMPDET.PID_SEC_IMP, 0) 
					AND ISNULL(FACTIMPDET.FID_DEF_TIP, 'G') = ISNULL(PEDIMPDET.PID_DEF_TIP, 'G') 
					AND ISNULL(FACTIMPDET.FID_POR_DEF, - 1) = ISNULL(PEDIMPDET.PID_POR_DEF, - 1) 			
					AND ISNULL(FACTIMPDET.PA_CODIGO, 0) = ISNULL(PEDIMPDET.PA_ORIGEN, 0) 
					AND ISNULL(FACTIMPDET.SPI_CODIGO, 0) = ISNULL(PEDIMPDET.SPI_CODIGO, 0) 
					AND ISNULL(FACTIMPDET.CS_CODIGO, 8) = isnull(PEDIMPDET.CS_CODIGO ,8)
--					AND isnull(FACTIMPDET.FID_NOPARTEAUX,'')=isnull(PEDIMPDET.PID_NOPARTEAUX,'')
					AND isnull(PEDIMPDET.PID_CODIGOFACT, 0) = isnull(FACTIMPDET.FI_CODIGO, 0)
					INNER JOIN
			                      FACTIMP ON PEDIMPDET.PI_CODIGO = FACTIMP.PI_RECTIFICA AND FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
					LEFT OUTER JOIN  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO
					LEFT OUTER JOIN  ARANCEL ARANCEL_1 ON PEDIMPDET.AR_IMPMX = ARANCEL_1.AR_CODIGO			
					INNER JOIN PEDIMP ON PEDIMPDET.PI_CODIGO= PEDIMP.PI_CODIGO
					LEFT OUTER JOIN CONFIGURACLAVEPED ON PEDIMP.CP_CODIGO=CONFIGURACLAVEPED.CP_CODIGO
					LEFT OUTER JOIN CONFIGURACLAVEPED C2 ON PEDIMP.CP_RECTIFICA=C2.CP_CODIGO
					WHERE CONFIGURACLAVEPED.ccp_tipo ='RE' AND C2.CCP_TIPO NOT in ('IA', 'IM')
					and PEDIMP.pi_codigo in (SELECT PI_CODIGO FROM PEDIMPSAAICONFIG WHERE PICF_SAAIDETDIVFACT='S')


					UPDATE FACTIMPDET
					SET     FACTIMPDET.PID_INDICEDLIGAR1 =PEDIMPDET.PID_INDICED
					FROM         FACTIMPDET INNER JOIN
			                      PEDIMPDET ON FACTIMPDET.MA_CODIGO = PEDIMPDET.MA_CODIGO 
					AND FACTIMPDET.FID_NOPARTE = PEDIMPDET.PID_NOPARTE 
					AND  ISNULL(FACTIMPDET.ME_CODIGO, 0) = ISNULL(PEDIMPDET.ME_CODIGO, 0) 
					AND ISNULL(FACTIMPDET.MA_GENERICO, 0) = ISNULL(PEDIMPDET.MA_GENERICO, 0) 
					AND ISNULL(FACTIMPDET.FID_ORD_COMP, 0) = ISNULL(PEDIMPDET.PID_ORD_COMP, 0) 
					AND ISNULL(FACTIMPDET.AR_IMPMX, 0) = ISNULL(PEDIMPDET.AR_IMPMX, 0) 
					AND ISNULL(FACTIMPDET.FID_RATEEXPFO, - 1) = ISNULL(PEDIMPDET.PID_RATEEXPFO, - 1) 
					AND ISNULL(FACTIMPDET.FID_SEC_IMP, 0) = ISNULL(PEDIMPDET.PID_SEC_IMP, 0) 
					AND ISNULL(FACTIMPDET.FID_DEF_TIP, 'G') = ISNULL(PEDIMPDET.PID_DEF_TIP, 'G') 
					AND ISNULL(FACTIMPDET.FID_POR_DEF, - 1) = ISNULL(PEDIMPDET.PID_POR_DEF, - 1) 			
					AND ISNULL(FACTIMPDET.PA_CODIGO, 0) = ISNULL(PEDIMPDET.PA_ORIGEN, 0) 
					AND ISNULL(FACTIMPDET.SPI_CODIGO, 0) = ISNULL(PEDIMPDET.SPI_CODIGO, 0) 
					AND ISNULL(FACTIMPDET.CS_CODIGO, 8) = isnull(PEDIMPDET.CS_CODIGO ,8)
--					AND isnull(FACTIMPDET.FID_NOPARTEAUX,'')=isnull(PEDIMPDET.PID_NOPARTEAUX,'')
					INNER JOIN
			                      FACTIMP ON PEDIMPDET.PI_CODIGO = FACTIMP.PI_RECTIFICA AND FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
					LEFT OUTER JOIN  ARANCEL ON FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO
					LEFT OUTER JOIN  ARANCEL ARANCEL_1 ON PEDIMPDET.AR_IMPMX = ARANCEL_1.AR_CODIGO			
					INNER JOIN PEDIMP ON PEDIMPDET.PI_CODIGO= PEDIMP.PI_CODIGO
					LEFT OUTER JOIN CONFIGURACLAVEPED ON PEDIMP.CP_CODIGO=CONFIGURACLAVEPED.CP_CODIGO
					LEFT OUTER JOIN CONFIGURACLAVEPED C2 ON PEDIMP.CP_RECTIFICA=C2.CP_CODIGO
					WHERE CONFIGURACLAVEPED.ccp_tipo ='RE' AND C2.CCP_TIPO NOT in ('IA', 'IM')
					and PEDIMP.pi_codigo in (SELECT PI_CODIGO FROM PEDIMPSAAICONFIG WHERE PICF_SAAIDETDIVFACT<>'S')


	exec sp_droptable 'pi_codigo_temp'


GO
