SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO









CREATE PROCEDURE [dbo].[SP_DOWNLOADMENSUAL]   as

		/*UPDATE BOM_STRUCT
	SET     BOM_STRUCT.PA_CODIGO= MAESTRO.PA_ORIGEN
	FROM        BOM_STRUCT INNER JOIN
	                  MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO 
	WHERE BOM_STRUCT.PA_CODIGO <> MAESTRO.PA_ORIGEN OR BOM_STRUCT.PA_CODIGO IS NULL
	*/
	EXEC SP_ACTUALIZAEQ_TASA_MAESTROALL

	
	EXEC SP_CALCULABOMCOSTOACTALL


	EXEC SP_CALCULALABORCOSTOALL

	EXEC SP_ACTUALIZATASABAJAMA


	EXEC SP_FILLBOMARANCEL9801ALL


	UPDATE MAESTROCOST
	SET     MA_COSTO= ROUND(MA_GRAV_MP + MA_GRAV_ADD + MA_GRAV_EMP + MA_GRAV_GI + MA_GRAV_GI_MX + MA_GRAV_MO + MA_NG_MP +
	                      MA_NG_ADD + MA_NG_EMP,6)
	FROM         MAESTROCOST
	WHERE TCO_CODIGO=1 AND MA_PERINI <=GETDATE() and MA_PERFIN>= GETDATE() AND
	MA_COSTO<> ROUND(MA_GRAV_MP + MA_GRAV_ADD + MA_GRAV_EMP + MA_GRAV_GI + MA_GRAV_GI_MX + MA_GRAV_MO + MA_NG_MP +
	                      MA_NG_ADD + MA_NG_EMP,6)








GO
