SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CHECA_MASTER_BOM]  @BSU INTEGER OUTPUT, @BST INTEGER OUTPUT   as

SET NOCOUNT ON 


	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA)
	SELECT     'No existe el Componente MA_NOPARTE: '+dbo.IMPORTTEMPBOM.BST_NOPARTE+' en el Cat. Maestro', 18
	FROM         dbo.IMPORTTEMPBOM
	WHERE  dbo.IMPORTTEMPBOM.BST_NOPARTE +'-'+
	                      dbo.IMPORTTEMPBOM.BST_NOPARTEAUX NOT IN
	(SELECT MA_NOPARTE+'-'+MA_NOPARTEAUX FROM MAESTRO
	UNION
	SELECT MA_NOPARTE+'-'+MA_NOPARTEAUX FROM MAESTROREFER)


	select @BST=count(*) from IMPORTLOG where IML_CBFORMA=18 and IML_MENSAJE like 'No existe el Componente MA_NOPARTE:%'

	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA)
	SELECT     'No existe el Padre MA_NOPARTE: '+dbo.IMPORTTEMPBOM.BSU_NOPARTE+' en el Cat. Maestro', 18
	FROM         dbo.IMPORTTEMPBOM
	WHERE  dbo.IMPORTTEMPBOM.BSU_NOPARTE +'-'+
	                      dbo.IMPORTTEMPBOM.BSU_NOPARTEAUX NOT IN
	(SELECT MA_NOPARTE+'-'+MA_NOPARTEAUX FROM MAESTRO
	UNION
	SELECT MA_NOPARTE+'-'+MA_NOPARTEAUX FROM MAESTROREFER)

	if @BST=0
	select @BSU=count(*) from IMPORTLOG where IML_CBFORMA=18 and IML_MENSAJE like 'No existe el Padre MA_NOPARTE:%'

GO
