SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE dbo.SP_GETPORCENTARA_DEFUNI (@MA_CODIGO INT)   as

DECLARE @TIMPUESTO VARCHAR(1), @FRACC INTEGER, @PAIS INTEGER, @TSECTOR VARCHAR(1), @SECTOR INTEGER, @SPI SMALLINT,
@AR_PORCENT decimal(38,6)
/*
	SELECT @TIMPUESTO=MA_DEF_TIP, @FRACC = AR_IMPMX, @PAIS=PA_ORIGEN, @SECTOR =MA_SEC_IMP, 
	@SPI = SPI_CODIGO FROM MAESTRO WHERE MA_CODIGO=@MA_CODIGO
	IF @TIMPUESTO = 'G' 
	begin
		SELECT @AR_PORCENT = AR_ADVDEF
		FROM ARANCEL
		WHERE AR_CODIGO = @FRACC
		UPDATE MAESTRO 
		SET MA_POR_DEF=ISNULL(@AR_PORCENT,-1) WHERE MA_CODIGO=@MA_CODIGO
	end
	if @TIMPUESTO = 'R'
	begin
		SELECT @AR_PORCENT = AR_PORCENT_8VA
		FROM ARANCEL
		WHERE AR_CODIGO = @FRACC 
		UPDATE MAESTRO SET MA_POR_DEF=ISNULL(@AR_PORCENT,-1) WHERE MA_CODIGO=@MA_CODIGO
	end

	if @TIMPUESTO = 'P'
	begin
		SELECT @AR_PORCENT = PAR_BEN
		FROM PAISARA 
		WHERE AR_CODIGO = @FRACC AND PA_CODIGO = @PAIS AND
		SPI_CODIGO=@SPI
		UPDATE MAESTRO SET MA_POR_DEF=ISNULL(@AR_PORCENT,-1) WHERE MA_CODIGO=@MA_CODIGO
	end

	if @TSECTOR = 'S'
	begin
		SELECT @AR_PORCENT = SA_PORCENT
		FROM SECTORARA 
		WHERE AR_CODIGO = @FRACC AND SE_CODIGO = @SECTOR 
		UPDATE MAESTRO SET MA_POR_DEF=ISNULL(@AR_PORCENT,-1) WHERE MA_CODIGO=@MA_CODIGO
	end
*/

GO
