SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_ACTUALIZAIDENTIFICA] (@picodigo int)   as

declare @existe int, @existe1 int, @CONSECUTIVO INT, @pi_movimiento char(1), @cp_codigo int, @ccptipo varchar(2),
@FID_INDICED int, @FED_INDICED int, @IDE_CODIGO int, @IDED_CODIGO int, @FIID_DESC varchar(40), @FEID_DESC varchar(40)



	select @pi_movimiento=pi_movimiento, @cp_codigo=cp_codigo from pedimp where pi_codigo=@picodigo

	SELECT @ccptipo = CCP_TIPO
	FROM CONFIGURACLAVEPED
	where CP_CODIGO = @cp_codigo



	if @pi_movimiento='E'
	begin
		if @ccptipo <> 'RE'
		begin


			-- identidicadores a nivel partida
				DELETE FROM FACTIMPDETIDENTIFICA WHERE FID_INDICED IN 
					(SELECT    dbo.FACTIMPDET.FID_INDICED
					FROM         dbo.PEDIMPDETB INNER JOIN
					                      dbo.PEDIMPDETIDENTIFICA ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB INNER JOIN
					                      dbo.PEDIMPDET ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB INNER JOIN
					                      dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGA INNER JOIN
					                      dbo.IDENTIFICA ON dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO
					WHERE dbo.PEDIMPDET.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND
					dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPDETIDENTIFICA WHERE FID_INDICED=dbo.FACTIMPDET.FID_INDICED)
					GROUP BY dbo.FACTIMPDET.FID_INDICED, dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO, dbo.PEDIMPDETIDENTIFICA.IDED_CODIGO, 
					                      ISNULL(dbo.PEDIMPDETIDENTIFICA.PIID_DESC,''))


			declare cur_IdentDet cursor for
				SELECT    dbo.FACTIMPDET.FID_INDICED, dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO, dbo.PEDIMPDETIDENTIFICA.IDED_CODIGO, 
				                      ISNULL(dbo.PEDIMPDETIDENTIFICA.PIID_DESC,'')
				FROM         dbo.PEDIMPDETB INNER JOIN
				                      dbo.PEDIMPDETIDENTIFICA ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB INNER JOIN
				                      dbo.PEDIMPDET ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB INNER JOIN
				                      dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGA INNER JOIN
				                      dbo.IDENTIFICA ON dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO
				WHERE dbo.PEDIMPDET.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND
				dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPDETIDENTIFICA WHERE FID_INDICED=dbo.FACTIMPDET.FID_INDICED)
--				and dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO in (SELECT MAX(PEDIMPDETIDENTIFICA_1.PIID_CODIGO) FROM PEDIMPDETIDENTIFICA PEDIMPDETIDENTIFICA_1 WHERE PEDIMPDETIDENTIFICA_1.PIB_INDICEB=dbo.PEDIMPDETB.PIB_INDICEB)
				GROUP BY dbo.FACTIMPDET.FID_INDICED, dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO, dbo.PEDIMPDETIDENTIFICA.IDED_CODIGO, 
				                      ISNULL(dbo.PEDIMPDETIDENTIFICA.PIID_DESC,'')
			open cur_IdentDet
		
			FETCH NEXT FROM cur_IdentDet INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC
		
			WHILE (@@FETCH_STATUS = 0) 
			BEGIN
		

				 EXEC SP_GETCONSECUTIVO @TIPO='FIID', @VALUE=@CONSECUTIVO OUTPUT
			
			
				INSERT INTO FACTIMPDETIDENTIFICA(FIID_CODIGO, FID_INDICED, IDE_CODIGO, IDED_CODIGO, FIID_DESC)

				VALUES (@CONSECUTIVO, @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC)		

		
		
			FETCH NEXT FROM cur_IdentDet INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC
		
			END
			
			CLOSE cur_IdentDet
			DEALLOCATE cur_IdentDet
			

			-- identidicadores a nivel pedimento		

				DELETE FROM FACTIMPIDENTIFICA WHERE FI_CODIGO IN 
					(SELECT    dbo.FACTIMP.FI_CODIGO
					FROM         dbo.PEDIMPIDENTIFICA INNER JOIN
				                      dbo.IDENTIFICA ON dbo.PEDIMPIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO INNER JOIN
				                      dbo.FACTIMP ON dbo.PEDIMPIDENTIFICA.PI_CODIGO = dbo.FACTIMP.PI_CODIGO
					WHERE dbo.PEDIMPIDENTIFICA.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND 
					dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPIDENTIFICA WHERE FI_CODIGO=dbo.FACTIMP.FI_CODIGO) AND
					dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE='RC')
					GROUP BY dbo.FACTIMP.FI_CODIGO, dbo.PEDIMPIDENTIFICA.IDE_CODIGO, dbo.PEDIMPIDENTIFICA.IDED_CODIGO, 
					                      ISNULL(dbo.PEDIMPIDENTIFICA.PII_DESC,''))


			declare cur_IdentCar cursor for
				SELECT    dbo.FACTIMP.FI_CODIGO, dbo.PEDIMPIDENTIFICA.IDE_CODIGO, dbo.PEDIMPIDENTIFICA.IDED_CODIGO, 
				                      ISNULL(dbo.PEDIMPIDENTIFICA.PII_DESC,'')
				FROM         dbo.PEDIMPIDENTIFICA INNER JOIN
			                      dbo.IDENTIFICA ON dbo.PEDIMPIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO INNER JOIN
			                      dbo.FACTIMP ON dbo.PEDIMPIDENTIFICA.PI_CODIGO = dbo.FACTIMP.PI_CODIGO
				WHERE dbo.PEDIMPIDENTIFICA.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND 
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPIDENTIFICA WHERE FI_CODIGO=dbo.FACTIMP.FI_CODIGO) AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE='RC')
--				and dbo.PEDIMPIDENTIFICA.PII_CODIGO in (SELECT MAX(PEDIMPIDENTIFICA_1.PII_CODIGO) FROM PEDIMPIDENTIFICA PEDIMPIDENTIFICA_1 WHERE PEDIMPIDENTIFICA_1.PI_CODIGO=dbo.PEDIMPIDENTIFICA.PI_CODIGO)
				GROUP BY dbo.FACTIMP.FI_CODIGO, dbo.PEDIMPIDENTIFICA.IDE_CODIGO, dbo.PEDIMPIDENTIFICA.IDED_CODIGO, 
				                      ISNULL(dbo.PEDIMPIDENTIFICA.PII_DESC,'')
			open cur_IdentCar
		
			FETCH NEXT FROM cur_IdentCar INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC
		
			WHILE (@@FETCH_STATUS = 0) 
			BEGIN
		


				 EXEC SP_GETCONSECUTIVO @TIPO='FII', @VALUE=@CONSECUTIVO OUTPUT
	
			
				INSERT INTO FACTIMPIDENTIFICA(FII_CODIGO, FI_CODIGO, IDE_CODIGO, IDED_CODIGO, FII_DESC)
				VALUES (@CONSECUTIVO, @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC)		

		
		
			FETCH NEXT FROM cur_IdentCar INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC
		
			END
			
			CLOSE cur_IdentCar
			DEALLOCATE cur_IdentCar

				

			

		end
		else
		begin
			-- identidicadores a nivel partida
			DELETE FROM FACTIMPDETIDENTIFICA WHERE FID_INDICED IN 
				(SELECT    dbo.FACTIMPDET.FID_INDICED
				FROM         dbo.PEDIMPDETB INNER JOIN
				                      dbo.PEDIMPDETIDENTIFICA ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB INNER JOIN
				                      dbo.PEDIMPDET ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB INNER JOIN
				                      dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGAR1 INNER JOIN
				                      dbo.IDENTIFICA ON dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO
				WHERE dbo.PEDIMPDET.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPDETIDENTIFICA.PIID_DESC IS NOT NULL AND
				dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPDETIDENTIFICA WHERE FID_INDICED=dbo.FACTIMPDET.FID_INDICED)
				and dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO in (SELECT MAX(PEDIMPDETIDENTIFICA_1.PIID_CODIGO) FROM PEDIMPDETIDENTIFICA PEDIMPDETIDENTIFICA_1 WHERE PEDIMPDETIDENTIFICA_1.PIB_INDICEB=dbo.PEDIMPDETB.PIB_INDICEB))


			declare cur_IdentDetR1 cursor for
				SELECT    dbo.FACTIMPDET.FID_INDICED, dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO, dbo.PEDIMPDETIDENTIFICA.IDED_CODIGO, 
				                      dbo.PEDIMPDETIDENTIFICA.PIID_DESC
				FROM         dbo.PEDIMPDETB INNER JOIN
				                      dbo.PEDIMPDETIDENTIFICA ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB INNER JOIN
				                      dbo.PEDIMPDET ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB INNER JOIN
				                      dbo.FACTIMPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTIMPDET.PID_INDICEDLIGAR1 INNER JOIN
				                      dbo.IDENTIFICA ON dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO
				WHERE dbo.PEDIMPDET.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPDETIDENTIFICA.PIID_DESC IS NOT NULL AND
				dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPDETIDENTIFICA WHERE FID_INDICED=dbo.FACTIMPDET.FID_INDICED)
				and dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO in (SELECT MAX(PEDIMPDETIDENTIFICA_1.PIID_CODIGO) FROM PEDIMPDETIDENTIFICA PEDIMPDETIDENTIFICA_1 WHERE PEDIMPDETIDENTIFICA_1.PIB_INDICEB=dbo.PEDIMPDETB.PIB_INDICEB)
			open cur_IdentDetR1
		
			FETCH NEXT FROM cur_IdentDetR1 INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC
		
			WHILE (@@FETCH_STATUS = 0) 
			BEGIN
		

				 EXEC SP_GETCONSECUTIVO @TIPO='FIID', @VALUE=@CONSECUTIVO OUTPUT
			
			
				INSERT INTO FACTIMPDETIDENTIFICA(FIID_CODIGO, FID_INDICED, IDE_CODIGO, IDED_CODIGO, FIID_DESC)

				VALUES (@CONSECUTIVO, @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC)		

		
		
			FETCH NEXT FROM cur_IdentDetR1 INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC
		
			END
			
			CLOSE cur_IdentDetR1
			DEALLOCATE cur_IdentDetR1
			

			-- identidicadores a nivel pedimento	
			DELETE FROM FACTIMPIDENTIFICA WHERE FI_CODIGO IN	
				(SELECT    dbo.FACTIMP.FI_CODIGO
				FROM         dbo.PEDIMPIDENTIFICA INNER JOIN
			                      dbo.IDENTIFICA ON dbo.PEDIMPIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO INNER JOIN
			                      dbo.FACTIMP ON dbo.PEDIMPIDENTIFICA.PI_CODIGO = dbo.FACTIMP.PI_RECTIFICA
				WHERE dbo.PEDIMPIDENTIFICA.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPIDENTIFICA.PII_DESC IS NOT NULL AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPIDENTIFICA WHERE FI_CODIGO=dbo.FACTIMP.FI_CODIGO) AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE='RC') and
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPIDENTIFICA WHERE FI_CODIGO=dbo.FACTIMP.FI_CODIGO)
				and dbo.PEDIMPIDENTIFICA.PII_CODIGO in (SELECT MAX(PEDIMPIDENTIFICA_1.PII_CODIGO) FROM PEDIMPIDENTIFICA PEDIMPIDENTIFICA_1 WHERE PEDIMPIDENTIFICA_1.PI_CODIGO=dbo.PEDIMPIDENTIFICA.PI_CODIGO))


			declare cur_IdentCarR1 cursor for
				SELECT    dbo.FACTIMP.FI_CODIGO, dbo.PEDIMPIDENTIFICA.IDE_CODIGO, dbo.PEDIMPIDENTIFICA.IDED_CODIGO, 
				                      dbo.PEDIMPIDENTIFICA.PII_DESC
				FROM         dbo.PEDIMPIDENTIFICA INNER JOIN
			                      dbo.IDENTIFICA ON dbo.PEDIMPIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO INNER JOIN
			                      dbo.FACTIMP ON dbo.PEDIMPIDENTIFICA.PI_CODIGO = dbo.FACTIMP.PI_RECTIFICA
				WHERE dbo.PEDIMPIDENTIFICA.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPIDENTIFICA.PII_DESC IS NOT NULL AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPIDENTIFICA WHERE FI_CODIGO=dbo.FACTIMP.FI_CODIGO) AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE='RC') and
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTIMPIDENTIFICA WHERE FI_CODIGO=dbo.FACTIMP.FI_CODIGO)
				and dbo.PEDIMPIDENTIFICA.PII_CODIGO in (SELECT MAX(PEDIMPIDENTIFICA_1.PII_CODIGO) FROM PEDIMPIDENTIFICA PEDIMPIDENTIFICA_1 WHERE PEDIMPIDENTIFICA_1.PI_CODIGO=dbo.PEDIMPIDENTIFICA.PI_CODIGO)
			open cur_IdentCarR1
		
			FETCH NEXT FROM cur_IdentCarR1 INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC
		
			WHILE (@@FETCH_STATUS = 0) 
			BEGIN
		

				 EXEC SP_GETCONSECUTIVO @TIPO='FII', @VALUE=@CONSECUTIVO OUTPUT
	
			
				INSERT INTO FACTIMPIDENTIFICA(FII_CODIGO, FI_CODIGO, IDE_CODIGO, IDED_CODIGO, FII_DESC)
				VALUES (@CONSECUTIVO, @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC)		

		
		
			FETCH NEXT FROM cur_IdentCarR1 INTO @FID_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FIID_DESC
		
			END
			
			CLOSE cur_IdentCarR1
			DEALLOCATE cur_IdentCarR1

				
		
		end	
	
	end
	else
	begin
		if @ccptipo <> 'RE'
		begin


			-- identidicadores a nivel partida
				DELETE FROM FACTEXPDETIDENTIFICA WHERE FED_INDICED IN
					(SELECT    dbo.FACTEXPDET.FED_INDICED
					FROM         dbo.PEDIMPDETB INNER JOIN
					                      dbo.PEDIMPDETIDENTIFICA ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB INNER JOIN
					                      dbo.PEDIMPDET ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB INNER JOIN
					                      dbo.FACTEXPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTEXPDET.PID_INDICEDLIGA INNER JOIN
					                      dbo.IDENTIFICA ON dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO
					WHERE dbo.PEDIMPDET.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPDETIDENTIFICA.PIID_DESC IS NOT NULL AND
					dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPDETIDENTIFICA WHERE FED_INDICED=dbo.FACTEXPDET.FED_INDICED)
					and dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO in (SELECT MAX(PEDIMPDETIDENTIFICA_1.PIID_CODIGO) FROM PEDIMPDETIDENTIFICA PEDIMPDETIDENTIFICA_1 WHERE PEDIMPDETIDENTIFICA_1.PIB_INDICEB=dbo.PEDIMPDETB.PIB_INDICEB))

			declare cur_IdentDetExp cursor for
				SELECT    dbo.FACTEXPDET.FED_INDICED, dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO, dbo.PEDIMPDETIDENTIFICA.IDED_CODIGO, 
				                      dbo.PEDIMPDETIDENTIFICA.PIID_DESC
				FROM         dbo.PEDIMPDETB INNER JOIN
				                      dbo.PEDIMPDETIDENTIFICA ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB INNER JOIN
				                      dbo.PEDIMPDET ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB INNER JOIN
				                      dbo.FACTEXPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTEXPDET.PID_INDICEDLIGA INNER JOIN
				                      dbo.IDENTIFICA ON dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO
				WHERE dbo.PEDIMPDET.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPDETIDENTIFICA.PIID_DESC IS NOT NULL AND
				dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPDETIDENTIFICA WHERE FED_INDICED=dbo.FACTEXPDET.FED_INDICED)
				and dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO in (SELECT MAX(PEDIMPDETIDENTIFICA_1.PIID_CODIGO) FROM PEDIMPDETIDENTIFICA PEDIMPDETIDENTIFICA_1 WHERE PEDIMPDETIDENTIFICA_1.PIB_INDICEB=dbo.PEDIMPDETB.PIB_INDICEB)
			open cur_IdentDetExp
		
			FETCH NEXT FROM cur_IdentDetExp INTO @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC
		
			WHILE (@@FETCH_STATUS = 0) 
			BEGIN
		

				 EXEC SP_GETCONSECUTIVO @TIPO='FEID', @VALUE=@CONSECUTIVO OUTPUT
			
			
				INSERT INTO FACTEXPDETIDENTIFICA(FEID_CODIGO, FED_INDICED, IDE_CODIGO, IDED_CODIGO, FEID_DESC)

				VALUES (@CONSECUTIVO, @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC)		

		
		
			FETCH NEXT FROM cur_IdentDetExp INTO @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC
		
			END
			
			CLOSE cur_IdentDetExp
			DEALLOCATE cur_IdentDetExp
			

			-- identidicadores a nivel pedimento		
			DELETE FROM FACTEXPIDENTIFICA WHERE FE_CODIGO IN 
				(SELECT    dbo.FACTEXP.FE_CODIGO
				FROM         dbo.PEDIMPIDENTIFICA INNER JOIN
			                      dbo.IDENTIFICA ON dbo.PEDIMPIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO INNER JOIN
			                      dbo.FACTEXP ON dbo.PEDIMPIDENTIFICA.PI_CODIGO = dbo.FACTEXP.PI_CODIGO
				WHERE dbo.PEDIMPIDENTIFICA.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPIDENTIFICA.PII_DESC IS NOT NULL AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPIDENTIFICA WHERE FE_CODIGO=dbo.FACTEXP.FE_CODIGO) AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE='RC') and
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPIDENTIFICA WHERE FE_CODIGO=dbo.FACTEXP.FE_CODIGO)
				and dbo.PEDIMPIDENTIFICA.PII_CODIGO in (SELECT MAX(PEDIMPIDENTIFICA_1.PII_CODIGO) FROM PEDIMPIDENTIFICA PEDIMPIDENTIFICA_1 WHERE PEDIMPIDENTIFICA_1.PI_CODIGO=dbo.PEDIMPIDENTIFICA.PI_CODIGO))


			declare cur_IdentCarExp cursor for
				SELECT    dbo.FACTEXP.FE_CODIGO, dbo.PEDIMPIDENTIFICA.IDE_CODIGO, dbo.PEDIMPIDENTIFICA.IDED_CODIGO, 
				                      dbo.PEDIMPIDENTIFICA.PII_DESC
				FROM         dbo.PEDIMPIDENTIFICA INNER JOIN
			                      dbo.IDENTIFICA ON dbo.PEDIMPIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO INNER JOIN
			                      dbo.FACTEXP ON dbo.PEDIMPIDENTIFICA.PI_CODIGO = dbo.FACTEXP.PI_CODIGO
				WHERE dbo.PEDIMPIDENTIFICA.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPIDENTIFICA.PII_DESC IS NOT NULL AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPIDENTIFICA WHERE FE_CODIGO=dbo.FACTEXP.FE_CODIGO) AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE='RC') and
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPIDENTIFICA WHERE FE_CODIGO=dbo.FACTEXP.FE_CODIGO)
				and dbo.PEDIMPIDENTIFICA.PII_CODIGO in (SELECT MAX(PEDIMPIDENTIFICA_1.PII_CODIGO) FROM PEDIMPIDENTIFICA PEDIMPIDENTIFICA_1 WHERE PEDIMPIDENTIFICA_1.PI_CODIGO=dbo.PEDIMPIDENTIFICA.PI_CODIGO)
			open cur_IdentCarExp
		
			FETCH NEXT FROM cur_IdentCarExp INTO @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC
		
			WHILE (@@FETCH_STATUS = 0) 
			BEGIN
		

				 EXEC SP_GETCONSECUTIVO @TIPO='FEI', @VALUE=@CONSECUTIVO OUTPUT
	
			
				INSERT INTO FACTEXPIDENTIFICA(FEI_CODIGO, FE_CODIGO, IDE_CODIGO, IDED_CODIGO, FEI_DESC)
				VALUES (@CONSECUTIVO, @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC)		

		
		
			FETCH NEXT FROM cur_IdentCarExp INTO @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC
		
			END
			
			CLOSE cur_IdentCarExp
			DEALLOCATE cur_IdentCarExp

				

			

		end
		else
		begin
			-- identidicadores a nivel partida
			DELETE FROM FACTEXPDETIDENTIFICA WHERE FED_INDICED IN
				(SELECT    dbo.FACTEXPDET.FED_INDICED
				FROM         dbo.PEDIMPDETB INNER JOIN
				                      dbo.PEDIMPDETIDENTIFICA ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB INNER JOIN
				                      dbo.PEDIMPDET ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB INNER JOIN
				                      dbo.FACTEXPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTEXPDET.PID_INDICEDLIGAR1 INNER JOIN
				                      dbo.IDENTIFICA ON dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO
				WHERE dbo.PEDIMPDET.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPDETIDENTIFICA.PIID_DESC IS NOT NULL AND
				dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPDETIDENTIFICA WHERE FED_INDICED=dbo.FACTEXPDET.FED_INDICED)
				and dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO in (SELECT MAX(PEDIMPDETIDENTIFICA_1.PIID_CODIGO) FROM PEDIMPDETIDENTIFICA PEDIMPDETIDENTIFICA_1 WHERE PEDIMPDETIDENTIFICA_1.PIB_INDICEB=dbo.PEDIMPDETB.PIB_INDICEB))


			declare cur_IdentDetExpR1 cursor for
				SELECT    dbo.FACTEXPDET.FED_INDICED, dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO, dbo.PEDIMPDETIDENTIFICA.IDED_CODIGO, 
				                      dbo.PEDIMPDETIDENTIFICA.PIID_DESC
				FROM         dbo.PEDIMPDETB INNER JOIN
				                      dbo.PEDIMPDETIDENTIFICA ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDETIDENTIFICA.PIB_INDICEB INNER JOIN
				                      dbo.PEDIMPDET ON dbo.PEDIMPDETB.PIB_INDICEB = dbo.PEDIMPDET.PIB_INDICEB INNER JOIN
				                      dbo.FACTEXPDET ON dbo.PEDIMPDET.PID_INDICED = dbo.FACTEXPDET.PID_INDICEDLIGAR1 INNER JOIN
				                      dbo.IDENTIFICA ON dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO
				WHERE dbo.PEDIMPDET.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPDETIDENTIFICA.PIID_DESC IS NOT NULL AND
				dbo.PEDIMPDETIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPDETIDENTIFICA WHERE FED_INDICED=dbo.FACTEXPDET.FED_INDICED)
				and dbo.PEDIMPDETIDENTIFICA.PIID_CODIGO in (SELECT MAX(PEDIMPDETIDENTIFICA_1.PIID_CODIGO) FROM PEDIMPDETIDENTIFICA PEDIMPDETIDENTIFICA_1 WHERE PEDIMPDETIDENTIFICA_1.PIB_INDICEB=dbo.PEDIMPDETB.PIB_INDICEB)
			open cur_IdentDetExpR1
		
			FETCH NEXT FROM cur_IdentDetExpR1 INTO @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC
		
			WHILE (@@FETCH_STATUS = 0) 
			BEGIN
		

				 EXEC SP_GETCONSECUTIVO @TIPO='FEID', @VALUE=@CONSECUTIVO OUTPUT
			
			
				INSERT INTO FACTEXPDETIDENTIFICA(FEID_CODIGO, FED_INDICED, IDE_CODIGO, IDED_CODIGO, FEID_DESC)

				VALUES (@CONSECUTIVO, @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC)		

		
		
			FETCH NEXT FROM cur_IdentDetExpR1 INTO @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC
		
			END
			
			CLOSE cur_IdentDetExpR1
			DEALLOCATE cur_IdentDetExpR1
			

			-- identidicadores a nivel pedimento		
			DELETE FROM FACTEXPIDENTIFICA WHERE FE_CODIGO IN
				(SELECT    dbo.FACTEXP.FE_CODIGO
				FROM         dbo.PEDIMPIDENTIFICA INNER JOIN
			                      dbo.IDENTIFICA ON dbo.PEDIMPIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO INNER JOIN
			                      dbo.FACTEXP ON dbo.PEDIMPIDENTIFICA.PI_CODIGO = dbo.FACTEXP.PI_RECTIFICA
				WHERE dbo.PEDIMPIDENTIFICA.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPIDENTIFICA.PII_DESC IS NOT NULL AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPIDENTIFICA WHERE FE_CODIGO=dbo.FACTEXP.FE_CODIGO) AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE='RC') and
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPIDENTIFICA WHERE FE_CODIGO=dbo.FACTEXP.FE_CODIGO)
				and dbo.PEDIMPIDENTIFICA.PII_CODIGO in (SELECT MAX(PEDIMPIDENTIFICA_1.PII_CODIGO) FROM PEDIMPIDENTIFICA PEDIMPIDENTIFICA_1 WHERE PEDIMPIDENTIFICA_1.PI_CODIGO=dbo.PEDIMPIDENTIFICA.PI_CODIGO))


			declare cur_IdentCarExpR1 cursor for
				SELECT    dbo.FACTEXP.FE_CODIGO, dbo.PEDIMPIDENTIFICA.IDE_CODIGO, dbo.PEDIMPIDENTIFICA.IDED_CODIGO, 
				                      dbo.PEDIMPIDENTIFICA.PII_DESC
				FROM         dbo.PEDIMPIDENTIFICA INNER JOIN
			                      dbo.IDENTIFICA ON dbo.PEDIMPIDENTIFICA.IDE_CODIGO = dbo.IDENTIFICA.IDE_CODIGO INNER JOIN
			                      dbo.FACTEXP ON dbo.PEDIMPIDENTIFICA.PI_CODIGO = dbo.FACTEXP.PI_RECTIFICA
				WHERE dbo.PEDIMPIDENTIFICA.PI_CODIGO =@picodigo AND dbo.IDENTIFICA.IDE_USAFACT = 'S' AND dbo.PEDIMPIDENTIFICA.PII_DESC IS NOT NULL AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPIDENTIFICA WHERE FE_CODIGO=dbo.FACTEXP.FE_CODIGO) AND
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM IDENTIFICA WHERE IDE_CLAVE='RC') and
				dbo.PEDIMPIDENTIFICA.IDE_CODIGO NOT IN (SELECT IDE_CODIGO FROM FACTEXPIDENTIFICA WHERE FE_CODIGO=dbo.FACTEXP.FE_CODIGO)
				and dbo.PEDIMPIDENTIFICA.PII_CODIGO in (SELECT MAX(PEDIMPIDENTIFICA_1.PII_CODIGO) FROM PEDIMPIDENTIFICA PEDIMPIDENTIFICA_1 WHERE PEDIMPIDENTIFICA_1.PI_CODIGO=dbo.PEDIMPIDENTIFICA.PI_CODIGO)
			open cur_IdentCarExpR1
		
			FETCH NEXT FROM cur_IdentCarExpR1 INTO @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC
		
			WHILE (@@FETCH_STATUS = 0) 
			BEGIN
		

				 EXEC SP_GETCONSECUTIVO @TIPO='FEI', @VALUE=@CONSECUTIVO OUTPUT
	
			
				INSERT INTO FACTEXPIDENTIFICA(FEI_CODIGO, FE_CODIGO, IDE_CODIGO, IDED_CODIGO, FEI_DESC)
				VALUES (@CONSECUTIVO, @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC)		

		
		
			FETCH NEXT FROM cur_IdentCarExpR1 INTO @FED_INDICED, @IDE_CODIGO, @IDED_CODIGO, @FEID_DESC
		
			END
			
			CLOSE cur_IdentCarExpR1
			DEALLOCATE cur_IdentCarExpR1

				
		
		end	
	
	end











GO
