SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

























CREATE PROCEDURE [dbo].[SP_FILL_BOM_DESCTEMP1] (@FED_INDICED INT, @BST_PT INT, @BST_HIJO INT, @BST_ENTRAVIGOR DATETIME, @BST_PERINI DATETIME, @FED_CANT decimal(38,6), @CODIGOFACTURA INT, @BST_INCORPOR1 decimal(38,6), @nivel int, @mensaje char(1) output)   as

SET NOCOUNT ON 
declare @BST_HIJO1 int, @BST_INCORPOR decimal(38,6), @BST_PERINI1 datetime, @nivelr int, @BST_TIPODESC VARCHAR(5), @incorporacionfinal decimal(38,6),@TEmbarque char(1)


	SET @nivelr=@nivel+1

	SELECT     @TEmbarque = CFQ_TIPO
	FROM CONFIGURATEMBARQUE 
	WHERE TQ_CODIGO IN (SELECT TQ_CODIGO FROM FACTEXP WHERE FE_CODIGO=@CODIGOFACTURA)


	if @TEmbarque='D'
	set @BST_TIPODESC='D'
	else 
	set @BST_TIPODESC='N'
	

			insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
			    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
			   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)

			SELECT     dbo.BOM_STRUCT.BST_HIJO, sum((BOM_STRUCT.BST_INCORPOR+(CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and
					isnull(MAESTRO.MA_POR_DESP,0)<>0 then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) 
					         else 0 end))) * @BST_INCORPOR1 AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
			                      case when dbo.CONFIGURATIPO.CFT_TIPO in ('P', 'S') then 'R' else dbo.CONFIGURATIPO.CFT_TIPO end, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
			                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
			                      dbo.BOM_STRUCT.BST_TIP_ENS, @FED_CANT, @CODIGOFACTURA, 'B'+convert(varchar(5),@nivelr), @BST_TIPODESC AS BST_TIPODESC,
					@BST_HIJO, @FED_INDICED, @BST_PT, @BST_ENTRAVIGOR, dbo.MAESTRO.MA_PESO_KG, isnull((SELECT MA_COSTO FROM VMAESTROCOST
				WHERE MA_CODIGO=dbo.BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
			FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
			                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
			                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
			WHERE ((dbo.CONFIGURATIPO.CFT_TIPO<>'P' and dbo.CONFIGURATIPO.CFT_TIPO<>'S') and (dbo.BOM_STRUCT.BST_TIP_ENS='C' or dbo.BOM_STRUCT.BST_TIP_ENS is null))
			or ((dbo.CONFIGURATIPO.CFT_TIPO='P' or dbo.CONFIGURATIPO.CFT_TIPO='S') and (dbo.BOM_STRUCT.BST_TIP_ENS='C' or dbo.BOM_STRUCT.BST_TIP_ENS='A' or dbo.BOM_STRUCT.BST_TIP_ENS='E' or dbo.BOM_STRUCT.BST_TIP_ENS='O'))
			GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
			                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
			                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
			                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.MAESTRO.MA_PESO_KG
			HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
			AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
			AND SUM(dbo.BOM_STRUCT.BST_INCORPOR) >0

DECLARE @CursorVar CURSOR

SET @CursorVar = CURSOR SCROLL DYNAMIC FOR
SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_INCORPOR) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_PERINI
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN 
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
WHERE     (dbo.CONFIGURATIPO.CFT_TIPO = 'P' OR dbo.CONFIGURATIPO.CFT_TIPO = 'S') 
	AND (dbo.BOM_STRUCT.BST_TIP_ENS = 'F' OR  dbo.BOM_STRUCT.BST_TIP_ENS IS NULL)
	AND (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
	AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL 
	AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)

GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_PERINI
HAVING   SUM(dbo.BOM_STRUCT.BST_INCORPOR) >0
 OPEN @CursorVar
  FETCH NEXT FROM @CursorVar INTO @BST_HIJO1, @BST_INCORPOR, @BST_PERINI1

  WHILE (@@fetch_status = 0) 
  BEGIN  

	set @incorporacionfinal=@BST_INCORPOR* @BST_INCORPOR1


		if @@NESTLEVEL <31
			exec  SP_FILL_BOM_DESCTEMP1 @FED_INDICED, @BST_PT, @BST_HIJO1, @BST_ENTRAVIGOR, @BST_PERINI1, 
			@FED_CANT, @CODIGOFACTURA, @incorporacionfinal, @nivelr, @mensaje=@mensaje output
		else
		begin
			set @mensaje='S'
			break
		end



	  FETCH NEXT FROM @CursorVar INTO @BST_HIJO1, @BST_INCORPOR, @BST_PERINI1
END
	CLOSE @CursorVar
	DEALLOCATE @CursorVar


GO
