SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[CopiaComponentes] (@BDOrigen varchar(50), @BDDestino varchar(50))    as



exec CopiaFracciones @BDOrigen, @BDDestino 

	IF  NOT EXISTS (SELECT name 
		   FROM  [tempdb].dbo.sysobjects 
		   WHERE  (name = '##MAESTRO' )
		   AND 	 ( type = 'U'))
	begin
		CREATE TABLE [##MAESTRO] (
			[MA_CODIGO] [int] IDENTITY (1, 1) NOT NULL ,
			[MA_NOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
			[MA_INV_GEN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_INV_GEN] DEFAULT ('I'),
			[TI_CODIGO] [smallint] NOT NULL ,
			[CS_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_MAESTRO_CS_CODIGO] DEFAULT (8),
			[MA_NOMBRE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
			[MA_NAME] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
			[MA_TIP_ENS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_TIP_ENS] DEFAULT ('C'),
			[ME_COM] [int] NOT NULL ,
			[ME_ALM] [int] NULL ,
			[EQ_GEN] [decimal](28, 14) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_GEN] DEFAULT (1),
			[EQ_IMPMX] [decimal](28, 14) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_IMPMX] DEFAULT (1),
			[EQ_ALM] [decimal](28, 14) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_ALM] DEFAULT (1),
			[EQ_EXPMX] [decimal](28, 14) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_EXPMX] DEFAULT (1),
			[EQ_IMPFO] [decimal](28, 14) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_IMPFO] DEFAULT (1),
			[EQ_RETRA] [decimal](28, 14) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_RETRA] DEFAULT (1),
			[EQ_DESP] [decimal](28, 14) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_DESP] DEFAULT (1),
			[EQ_EXPFO] [decimal](28, 14) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_EXPFO] DEFAULT (1),
			[PA_ORIGEN] [int] NOT NULL ,
			[PA_PROCEDE] [int] NOT NULL ,
			[MA_CONSTA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_CONSTA] DEFAULT ('N'),
			[MA_GENERICO] [int] NOT NULL CONSTRAINT [DF_MAESTRO_MA_GENERICO] DEFAULT (0),
			[MA_FAMILIA] [int] NOT NULL CONSTRAINT [DF_MAESTRO_MA_FAMILIA] DEFAULT (0),
			[MA_FAMILIAMP] [int] NOT NULL CONSTRAINT [DF_MAESTRO_MA_FAMILIAMP] DEFAULT (0),
			[MA_EXPENS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_EXPENS] DEFAULT ('N'),
			[MA_DEF_TIP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_DEF_TIP] DEFAULT ('G'),
			[MA_PESO_KG] [decimal](38, 6) NOT NULL CONSTRAINT [DF_MAESTRO_MA_PESO_KG] DEFAULT (0),
			[MA_PESO_LB] [decimal](38, 6) NOT NULL CONSTRAINT [DF_MAESTRO_MA_PESO_LB] DEFAULT (0),
			[MA_EST_MAT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_EST_MAT] DEFAULT ('A'),
			[MA_MARCA] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_MARCA] DEFAULT (''),
			[MA_COLOR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_COLOR] DEFAULT (''),
			[MA_MODELO] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_MODELO] DEFAULT (''),
			[MP_CODIGO] [smallint] NULL ,
			[MA_EMP_PEL] [int] NOT NULL CONSTRAINT [DF_MAESTRO_MA_EMP_PEL] DEFAULT (0),
			[MA_IDENTI] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_IDENTI] DEFAULT (''),
			[AR_IMPMX] [int] NULL ,
			[AR_EXPMX] [int] NULL ,
			[AR_IMPFO] [int] NULL ,
			[AR_RETRA] [int] NULL ,
			[AR_DESP] [int] NULL ,
			[AR_EXPFO] [int] NULL ,
			[CX_CODIGO] [smallint] NULL ,
			[MA_TALLA] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_TALLA] DEFAULT (''),
			[MA_ESTILO] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_ESTILO] DEFAULT (''),
			[MA_DISCHARGE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_DISCHARGE] DEFAULT ('S'),
			[SE_CODIGO] [smallint] NULL ,
			[MA_SEC_IMP] [smallint] NULL ,
			[SPI_CODIGO] [smallint] NULL ,
			[MA_REPARA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_REPARA] DEFAULT ('N'),
			[MA_GENERA_EMP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_GENERA_EMP] DEFAULT ('D'),
			[MA_EMPAQUE] [int] NULL ,
			[MA_CANTEMP] [decimal](38, 6) NOT NULL CONSTRAINT [DF_MAESTRO_MA_CANTEMP] DEFAULT (0),
			[MA_NOPARTEAUX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_NOPARTEAUX] DEFAULT (''),
			[CC_CODIGO] [int] NULL ,
			[MA_PELIGROSO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_PELIGROSO] DEFAULT ('N'),
			[AR_IMPFOUSA] [int] NULL ,
			[EQ_IMPFOUSA] [decimal](38, 6) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_IMPFOUSA] DEFAULT (1),
			[AR_IMPEMPFOUSA] [int] NULL ,
			[EQ_IMPEMPFOUSA] [decimal](38, 6) NULL ,
			[MA_SEL] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_SEL] DEFAULT ('N'),
			[MA_EMPFACT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_EMPFACT] DEFAULT ('S'),
			[MA_TIEMPOENSMIN] [decimal](38, 6) NOT NULL CONSTRAINT [DF_MAESTRO_MA_TIEMPOENSMIN] DEFAULT (0),
			[TEM_CODIGO] [int] NULL ,
			[MA_SERVICIO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_SERVICIO] DEFAULT ('N'),
			[MA_OCULTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_OCULTO] DEFAULT ('N'),
			[MA_TONMAQUINAS] [decimal](38, 6) NULL ,
			[PA_CORTE] [int] NULL ,
			[MA_TRANS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_TRANS] DEFAULT ('N'),
			[MA_SOLOBOM] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_SOLOBOM] DEFAULT ('N'),
			[MA_ESTRUCTURA] [int] NULL ,
			[MA_DESCOSTOARR] [smallint] NOT NULL CONSTRAINT [DF_MAESTRO_MA_DESCOSTOARR] DEFAULT (10),
			[MA_DESCOSTOABA] [smallint] NOT NULL CONSTRAINT [DF_MAESTRO_MA_DESCOSTOABA] DEFAULT (10),
			[MA_ENUSO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_ENUSO] DEFAULT ('S'),
			[MA_YEAR] [int] NULL ,
			[EQ_EXPFO2] [decimal](28, 14) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_EXPFO2] DEFAULT (1),
			[LIN_CODIGO] [int] NULL ,
			[MA_ULTIMAMODIF] [datetime] NULL ,
			[MA_MULTIPAIS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_MULTIPAIS] DEFAULT ('N'),
			[MA_NAFTATEMP] [smallint] NOT NULL CONSTRAINT [DF_MAESTRO_MA_NAFTATEMP] DEFAULT (0),
			[AR_DESPMX] [int] NULL ,
			[EQ_DESPMX] [decimal](38, 6) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_DESPMX] DEFAULT (1),
			[AR_IMPMXR8] [int] NULL ,
			[EQ_IMPMXR8] [decimal](38, 6) NOT NULL CONSTRAINT [DF_MAESTRO_EQ_IMPMXR8] DEFAULT (1),
			[MA_SEC_IMPCERTDEF] [int] NOT NULL CONSTRAINT [DF_MAESTRO_MA_SEC_IMPCERTDEF] DEFAULT (0),
			[MA_NOMBREDESP] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[MA_NAMEDESP] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[MA_RETRABAJO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_MAESTRO_MA_RETRABAJO] DEFAULT ('N'),
			[MA_COSTOUNITLC] [decimal](38, 6) NOT NULL CONSTRAINT [DF_MAESTRO_MA_COSTOUNITLC] DEFAULT (0),
			[MA_COSTOVATLC] [decimal](38, 6) NOT NULL CONSTRAINT [DF_MAESTRO_MA_COSTOVATLC] DEFAULT (0),
			CONSTRAINT [PK_MAESTRO] PRIMARY KEY  NONCLUSTERED 
			(
				[MA_NOPARTE],
				[MA_INV_GEN],
				[MA_NOPARTEAUX]
			)  ON [PRIMARY] ,
			CONSTRAINT [IX_MAESTRO] UNIQUE  NONCLUSTERED 
			(
				[MA_CODIGO]
			)  ON [PRIMARY] 
		) ON [PRIMARY]

	end


	DECLARE @MAXIMO INT
	
	SELECT @MAXIMO=ISNULL(MAX(MA_CODIGO),0)+1 FROM MAESTRO
	
	
	DBCC CHECKIDENT ([##MAESTRO], RESEED, @MAXIMO)


	
	exec('INSERT INTO ##MAESTRO(MA_NOPARTE, MA_INV_GEN, TI_CODIGO, CS_CODIGO, MA_NOMBRE, MA_NAME, MA_TIP_ENS, ME_COM, ME_ALM, EQ_GEN, 
	                      EQ_IMPMX, EQ_ALM, EQ_EXPMX, EQ_IMPFO, EQ_RETRA, EQ_DESP, EQ_EXPFO, PA_ORIGEN, PA_PROCEDE, MA_CONSTA, MA_GENERICO, 
	                      MA_FAMILIA, MA_FAMILIAMP, MA_EXPENS, MA_DEF_TIP, MA_PESO_KG, MA_PESO_LB, MA_EST_MAT, MA_MARCA, MA_COLOR, MA_MODELO, 
	                      MP_CODIGO, MA_EMP_PEL, MA_IDENTI, AR_IMPMX, AR_EXPMX, AR_IMPFO, AR_RETRA, AR_DESP, AR_EXPFO, CX_CODIGO, MA_TALLA, 
	                      MA_ESTILO, MA_DISCHARGE, SE_CODIGO, MA_SEC_IMP, SPI_CODIGO, MA_REPARA, MA_GENERA_EMP, MA_EMPAQUE, MA_CANTEMP, 
	                      MA_NOPARTEAUX, CC_CODIGO, MA_PELIGROSO, AR_IMPFOUSA, EQ_IMPFOUSA, AR_IMPEMPFOUSA, EQ_IMPEMPFOUSA, MA_SEL, MA_EMPFACT, 
	                      MA_TIEMPOENSMIN, TEM_CODIGO, MA_SERVICIO, MA_OCULTO, MA_TONMAQUINAS, PA_CORTE, MA_TRANS, MA_SOLOBOM, MA_ESTRUCTURA, 
	                      MA_DESCOSTOARR, MA_DESCOSTOABA, MA_ENUSO, MA_YEAR, EQ_EXPFO2, LIN_CODIGO, MA_ULTIMAMODIF, MA_MULTIPAIS, MA_NAFTATEMP, 
	                      AR_DESPMX, EQ_DESPMX, AR_IMPMXR8, EQ_IMPMXR8, MA_SEC_IMPCERTDEF, MA_NOMBREDESP, MA_NAMEDESP, MA_RETRABAJO, 
	                      MA_COSTOUNITLC, MA_COSTOVATLC)

	SELECT     MA_NOPARTE, MA_INV_GEN, TI_CODIGO, MAESTROOrig.CS_CODIGO, MA_NOMBRE, MA_NAME, MA_TIP_ENS, ME_COM, ME_ALM, EQ_GEN, 
	                      EQ_IMPMX, EQ_ALM, EQ_EXPMX, EQ_IMPFO, EQ_RETRA, EQ_DESP, EQ_EXPFO, PA_ORIGEN, PA_PROCEDE, MA_CONSTA, MA_GENERICO, 
	                      MA_FAMILIA, MA_FAMILIAMP, MA_EXPENS, MA_DEF_TIP, MA_PESO_KG, MA_PESO_LB, MA_EST_MAT, MA_MARCA, MA_COLOR, MA_MODELO, 
	                      MP_CODIGO, MA_EMP_PEL, MA_IDENTI, (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_1.AR_FRACCION AND PA_CODIGO=ARANCEL_1.PA_CODIGO)
			      AS AR_IMPMX, (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_2.AR_FRACCION AND PA_CODIGO=ARANCEL_2.PA_CODIGO) AS AR_EXPMX, 
			      (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_3.AR_FRACCION AND PA_CODIGO=ARANCEL_3.PA_CODIGO) AS AR_IMPFO, 
			      (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_4.AR_FRACCION AND PA_CODIGO=ARANCEL_4.PA_CODIGO) AS AR_RETRA,
			      (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_5.AR_FRACCION AND PA_CODIGO=ARANCEL_5.PA_CODIGO)AS AR_DESP, 
			      (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_6.AR_FRACCION AND PA_CODIGO=ARANCEL_6.PA_CODIGO) AS AR_EXPFO, CX_CODIGO, MA_TALLA, 
	                      MA_ESTILO, MA_DISCHARGE, SE_CODIGO, MA_SEC_IMP, SPI_CODIGO, MA_REPARA, MA_GENERA_EMP, MA_EMPAQUE, MA_CANTEMP, 
	                      MA_NOPARTEAUX, CC_CODIGO, MA_PELIGROSO, 
			      (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_7.AR_FRACCION AND PA_CODIGO=ARANCEL_7.PA_CODIGO) AS AR_IMPFOUSA, EQ_IMPFOUSA,
			      (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_8.AR_FRACCION AND PA_CODIGO=ARANCEL_8.PA_CODIGO) AS AR_IMPEMPFOUSA, EQ_IMPEMPFOUSA, MA_SEL, 
			      MA_EMPFACT, MA_TIEMPOENSMIN, TEM_CODIGO, MA_SERVICIO, MA_OCULTO, MA_TONMAQUINAS, PA_CORTE, MA_TRANS, MA_SOLOBOM, MA_ESTRUCTURA, 
	                      MA_DESCOSTOARR, MA_DESCOSTOABA, MA_ENUSO, MA_YEAR, EQ_EXPFO2, LIN_CODIGO, GETDATE(), MA_MULTIPAIS, MA_NAFTATEMP, 
	                      (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_9.AR_FRACCION AND PA_CODIGO=ARANCEL_9.PA_CODIGO) AS AR_DESPMX, EQ_DESPMX, 
		         (SELECT max(AR_CODIGO) FROM ARANCEL WHERE AR_FRACCION=ARANCEL_10.AR_FRACCION AND PA_CODIGO=ARANCEL_10.PA_CODIGO) AS AR_IMPMXR8, EQ_IMPMXR8, MA_SEC_IMPCERTDEF, MA_NOMBREDESP, MA_NAMEDESP, MA_RETRABAJO, 
	                      MA_COSTOUNITLC, MA_COSTOVATLC
	FROM         '+@BDOrigen+'.DBO.ARANCEL ARANCEL_10 RIGHT OUTER JOIN
	                      '+@BDOrigen+'.DBO.MAESTRO MAESTROOrig ON ARANCEL_10.AR_CODIGO = MAESTROOrig.AR_IMPMXR8 LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_9 ON MAESTROOrig.AR_DESPMX = ARANCEL_9.AR_CODIGO LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_8 ON MAESTROOrig.AR_IMPEMPFOUSA = ARANCEL_8.AR_CODIGO LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_7 ON MAESTROOrig.AR_IMPFOUSA = ARANCEL_7.AR_CODIGO LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_6 ON MAESTROOrig.AR_EXPFO = ARANCEL_6.AR_CODIGO LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_5 ON MAESTROOrig.AR_DESP = ARANCEL_5.AR_CODIGO LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_4 ON MAESTROOrig.AR_RETRA = ARANCEL_4.AR_CODIGO LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_3 ON MAESTROOrig.AR_IMPFO = ARANCEL_3.AR_CODIGO LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_2 ON MAESTROOrig.AR_EXPMX = ARANCEL_2.AR_CODIGO LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_1 ON MAESTROOrig.AR_IMPMX = ARANCEL_1.AR_CODIGO
	WHERE MA_NOPARTE NOT IN (SELECT MA_NOPARTE FROM MAESTRO)')



	INSERT INTO MAESTRO(MA_CODIGO, MA_NOPARTE, MA_INV_GEN, TI_CODIGO, CS_CODIGO, MA_NOMBRE, MA_NAME, MA_TIP_ENS, ME_COM, ME_ALM, EQ_GEN, 
	                      EQ_IMPMX, EQ_ALM, EQ_EXPMX, EQ_IMPFO, EQ_RETRA, EQ_DESP, EQ_EXPFO, PA_ORIGEN, PA_PROCEDE, MA_CONSTA, MA_GENERICO, 
	                      MA_FAMILIA, MA_FAMILIAMP, MA_EXPENS, MA_DEF_TIP, MA_PESO_KG, MA_PESO_LB, MA_EST_MAT, MA_MARCA, MA_COLOR, MA_MODELO, 
	                      MP_CODIGO, MA_EMP_PEL, MA_IDENTI, AR_IMPMX, AR_EXPMX, AR_IMPFO, AR_RETRA, AR_DESP, AR_EXPFO, CX_CODIGO, MA_TALLA, 
	                      MA_ESTILO, MA_DISCHARGE, SE_CODIGO, MA_SEC_IMP, SPI_CODIGO, MA_REPARA, MA_GENERA_EMP, MA_EMPAQUE, MA_CANTEMP, 
	                      MA_NOPARTEAUX, CC_CODIGO, MA_PELIGROSO, AR_IMPFOUSA, EQ_IMPFOUSA, AR_IMPEMPFOUSA, EQ_IMPEMPFOUSA, MA_SEL, MA_EMPFACT, 
	                      MA_TIEMPOENSMIN, TEM_CODIGO, MA_SERVICIO, MA_OCULTO, MA_TONMAQUINAS, PA_CORTE, MA_TRANS, MA_SOLOBOM, MA_ESTRUCTURA, 
	                      MA_DESCOSTOARR, MA_DESCOSTOABA, MA_ENUSO, MA_YEAR, EQ_EXPFO2, LIN_CODIGO, MA_ULTIMAMODIF, MA_MULTIPAIS, MA_NAFTATEMP, 
	                      AR_DESPMX, EQ_DESPMX, AR_IMPMXR8, EQ_IMPMXR8, MA_SEC_IMPCERTDEF, MA_NOMBREDESP, MA_NAMEDESP, MA_RETRABAJO, 
	                      MA_COSTOUNITLC, MA_COSTOVATLC)

	SELECT MA_CODIGO, MA_NOPARTE, MA_INV_GEN, TI_CODIGO, CS_CODIGO, MA_NOMBRE, MA_NAME, MA_TIP_ENS, ME_COM, ME_ALM, EQ_GEN, 
	                      EQ_IMPMX, EQ_ALM, EQ_EXPMX, EQ_IMPFO, EQ_RETRA, EQ_DESP, EQ_EXPFO, PA_ORIGEN, PA_PROCEDE, MA_CONSTA, MA_GENERICO, 
	                      MA_FAMILIA, MA_FAMILIAMP, MA_EXPENS, MA_DEF_TIP, MA_PESO_KG, MA_PESO_LB, MA_EST_MAT, MA_MARCA, MA_COLOR, MA_MODELO, 
	                      MP_CODIGO, MA_EMP_PEL, MA_IDENTI, AR_IMPMX, AR_EXPMX, AR_IMPFO, AR_RETRA, AR_DESP, AR_EXPFO, CX_CODIGO, MA_TALLA, 
	                      MA_ESTILO, MA_DISCHARGE, SE_CODIGO, MA_SEC_IMP, SPI_CODIGO, MA_REPARA, MA_GENERA_EMP, MA_EMPAQUE, MA_CANTEMP, 
	                      MA_NOPARTEAUX, CC_CODIGO, MA_PELIGROSO, AR_IMPFOUSA, EQ_IMPFOUSA, AR_IMPEMPFOUSA, EQ_IMPEMPFOUSA, MA_SEL, MA_EMPFACT, 
	                      MA_TIEMPOENSMIN, TEM_CODIGO, MA_SERVICIO, MA_OCULTO, MA_TONMAQUINAS, PA_CORTE, MA_TRANS, MA_SOLOBOM, MA_ESTRUCTURA, 
	                      MA_DESCOSTOARR, MA_DESCOSTOABA, MA_ENUSO, MA_YEAR, EQ_EXPFO2, LIN_CODIGO, MA_ULTIMAMODIF, MA_MULTIPAIS, MA_NAFTATEMP, 
	                      AR_DESPMX, EQ_DESPMX, AR_IMPMXR8, EQ_IMPMXR8, MA_SEC_IMPCERTDEF, MA_NOMBREDESP, MA_NAMEDESP, MA_RETRABAJO, 
	                      MA_COSTOUNITLC, MA_COSTOVATLC
	FROM ##MAESTRO

	update consecutivo
	set cv_codigo =  isnull((select max(MA_CODIGO) from MAESTRO),0) + 1
	where cv_tipo = 'MA'




	drop table ##MAESTRO


	EXEC('INSERT INTO MAESTROCATEG(MA_CODIGO, CPE_CODIGO, EQ_CANT)
		SELECT     MAESTRO_1.MA_CODIGO, CATEGPERMISO_2.CPE_CODIGO, MAESTROCATEG.EQ_CANT
	FROM         MAESTROCATEG INNER JOIN
	                      '+@BDOrigen+'.DBO.MAESTRO MAESTROOrig ON MAESTROCATEG.MA_CODIGO = MAESTROOrig.MA_CODIGO INNER JOIN
	                      MAESTRO MAESTRO_1 ON MAESTROOrig.MA_NOPARTE = MAESTRO_1.MA_NOPARTE AND 
	                      MAESTROOrig.MA_INV_GEN = MAESTRO_1.MA_INV_GEN INNER JOIN
	                      '+@BDOrigen+'.DBO.CATEGPERMISO CATEGPERMISO_1 ON MAESTROCATEG.CPE_CODIGO = CATEGPERMISO_1.CPE_CODIGO INNER JOIN
	                      CATEGPERMISO CATEGPERMISO_2 ON CATEGPERMISO_1.CPE_CORTO = CATEGPERMISO_2.CPE_CORTO
	WHERE CONVERT(VARCHAR(50),MAESTRO_1.MA_CODIGO)+''-''+ CONVERT(VARCHAR(50),CATEGPERMISO_2.CPE_CODIGO)  NOT
	IN (SELECT CONVERT(VARCHAR(50),MA_CODIGO) +''-''+ CONVERT(VARCHAR(50),CPE_CODIGO) FROM MAESTROCATEG)')


	exec('INSERT INTO MAESTROSUST(MA_CODIGO, MA_CODIGOSUST, EQ_CANT)
		SELECT     MAESTRO_2.MA_CODIGO, MAESTRO_3.MA_CODIGO, MAESTROSUST1.EQ_CANT
		FROM         '+@BDOrigen+'.DBO.MAESTROSUST MAESTROSUST1 INNER JOIN
		                      '+@BDOrigen+'.DBO.MAESTRO MAESTROOrig ON MAESTROSUST1.MA_CODIGO = MAESTROOrig.MA_CODIGO INNER JOIN
		                      MAESTRO MAESTRO_2 ON MAESTROOrig.MA_NOPARTE = MAESTRO_2.MA_NOPARTE AND 
		                      MAESTROOrig.MA_INV_GEN = MAESTRO_2.MA_INV_GEN INNER JOIN
		                      '+@BDOrigen+'.DBO.MAESTRO MAESTROOrig_1 ON MAESTROSUST1.MA_CODIGOSUST = MAESTROOrig_1.MA_CODIGO INNER JOIN
		                      MAESTRO MAESTRO_3 ON MAESTROOrig_1.MA_NOPARTE = MAESTRO_3.MA_NOPARTE AND 
		                      MAESTROOrig_1.MA_INV_GEN = MAESTRO_3.MA_INV_GEN
		WHERE convert(varchar(50),MAESTRO_2.MA_CODIGO)+convert(varchar(50),MAESTRO_3.MA_CODIGO) not in
		(select convert(varchar(50),MA_CODIGO)+convert(varchar(50),MA_CODIGOSUST) from MAESTROSUST)')

GO
