SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE dbo.SP_TFACCONSTEXP ( @TIPO VARCHAR(1))   as

SET NOCOUNT ON 
BEGIN
 IF @TIPO = 'I' 
   SELECT * FROM TFACTURA WHERE TF_TIPO = 'R' OR TF_TIPO = 'C'
 ELSE IF @TIPO = 'V'
   SELECT * FROM TFACTURA WHERE TF_TIPO = 'V'
END




GO
