SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

/* Inserta en la tabla pedimento de importacion y detalle lo generado en la tabla implementarel*/
CREATE PROCEDURE [dbo].[SP_ImplementaInsert]   as

SET NOCOUNT ON 
declare @PI_FOLIO varchar(15), @PI_FECHA datetime, @AGT_CODIGO smallint, 
	@AD_CODIGO int, @PR_CODIGO int, @CL_CODIGO int, @CONSECUTIVO INT, @PI_TIP_CAM decimal(38,6), @CP_CODIGO INT




declare cur_pedimpinsert cursor for
	SELECT     dbo.IMPLEMENTAPEDIMP.PI_FOLIO, dbo.IMPLEMENTAPEDIMP.PI_FECHA, dbo.IMPLEMENTAPEDIMP.AGT_CODIGO, 
	                      dbo.IMPLEMENTAPEDIMP.AD_CODIGO, dbo.IMPLEMENTAPEDIMP.PR_CODIGO, dbo.IMPLEMENTAPEDIMP.CL_CODIGO, 
	                      dbo.IMPLEMENTAPEDIMP.PI_TIP_CAM, dbo.IMPLEMENTAPEDIMP.CP_CODIGO
	FROM         dbo.IMPLEMENTAPEDIMP RIGHT OUTER JOIN
	                      dbo.IMPLEMENTAREL ON dbo.IMPLEMENTAPEDIMP.PI_CODIGOIMP = dbo.IMPLEMENTAREL.PI_CODIGOIMP LEFT OUTER JOIN
	                      dbo.PEDIMP ON dbo.IMPLEMENTAPEDIMP.PI_FOLIO = dbo.PEDIMP.PI_FOLIO
	WHERE     (dbo.PEDIMP.PI_FOLIO IS NULL)
	GROUP BY dbo.IMPLEMENTAPEDIMP.PI_FOLIO, dbo.IMPLEMENTAPEDIMP.PI_FECHA, dbo.IMPLEMENTAPEDIMP.AGT_CODIGO, 
	                      dbo.IMPLEMENTAPEDIMP.AD_CODIGO, dbo.IMPLEMENTAPEDIMP.PR_CODIGO, dbo.IMPLEMENTAPEDIMP.CL_CODIGO, 
	                      dbo.IMPLEMENTAPEDIMP.PI_TIP_CAM, dbo.IMPLEMENTAPEDIMP.CP_CODIGO
open cur_pedimpinsert 
	

FETCH NEXT FROM cur_pedimpinsert INTO @PI_FOLIO, @PI_FECHA, @AGT_CODIGO, @AD_CODIGO, @PR_CODIGO, @CL_CODIGO, @PI_TIP_CAM,
@CP_CODIGO
WHILE (@@FETCH_STATUS = 0) 

BEGIN

SELECT @CONSECUTIVO=ISNULL(MAX(PI_CODIGO),0) FROM PEDIMP

SET @CONSECUTIVO=@CONSECUTIVO+1

	INSERT INTO PEDIMP(PI_CODIGO, PI_FOLIO, PI_FEC_PAG, AGT_CODIGO, AD_DES, PR_CODIGO, CL_CODIGO, PI_TIP_CAM,
				PI_TIPO, CP_CODIGO)
	VALUES (@CONSECUTIVO, @PI_FOLIO, @PI_FECHA, @AGT_CODIGO, @AD_CODIGO, 
		ISNULL(@PR_CODIGO,0), ISNULL(@CL_CODIGO,0), @PI_TIP_CAM, 'A', @CP_CODIGO)


	FETCH NEXT FROM cur_pedimpinsert INTO @PI_FOLIO, @PI_FECHA, @AGT_CODIGO, @AD_CODIGO, @PR_CODIGO, @CL_CODIGO, @PI_TIP_CAM, 
            @CP_CODIGO

END

CLOSE cur_pedimpinsert
DEALLOCATE cur_pedimpinsert






GO
