SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
































CREATE PROCEDURE [dbo].[SP_ACTUALIZAEQGENMODIF] (@fecha varchar(25))   as

SET NOCOUNT ON 
DECLARE @ME_KILOGRAMOS int

	select @ME_KILOGRAMOS=ME_KILOGRAMOS from configuracion


		update dbo.MAESTRO
		SET     dbo.MAESTRO.EQ_GEN = 1
		WHERE dbo.MAESTRO.EQ_GEN <> 1


		if exists (SELECT dbo.MAESTRO.EQ_GEN FROM dbo.MAESTRO INNER JOIN
			                      dbo.MAESTRO MAESTRO_1 ON dbo.MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO INNER JOIN
			                      dbo.EQUIVALE ON dbo.MAESTRO.ME_COM = dbo.EQUIVALE.ME_CODIGO1 AND MAESTRO_1.ME_COM = dbo.EQUIVALE.ME_CODIGO2)
			update dbo.MAESTRO
			SET     dbo.MAESTRO.EQ_GEN= dbo.EQUIVALE.EQ_CANT
			FROM         dbo.MAESTRO INNER JOIN
			                      dbo.MAESTRO MAESTRO_1 ON dbo.MAESTRO.MA_GENERICO = MAESTRO_1.MA_CODIGO INNER JOIN
			                      dbo.EQUIVALE ON dbo.MAESTRO.ME_COM = dbo.EQUIVALE.ME_CODIGO1 AND MAESTRO_1.ME_COM = dbo.EQUIVALE.ME_CODIGO2
			WHERE dbo.MAESTRO.EQ_GEN<> dbo.EQUIVALE.EQ_CANT and convert(varchar(11),dbo.MAESTRO.MA_ULTIMAMODIF,101)=@FECHA

		if exists (SELECT MA_CODIGO FROM MAESTRO WHERE MA_INV_GEN='G' AND ME_COM=@ME_KILOGRAMOS)
		begin
			UPDATE MAESTRO
			SET EQ_GEN = MA_PESO_KG
			WHERE MA_PESO_KG>0 and EQ_GEN <> MA_PESO_KG AND MA_GENERICO IN
			(SELECT MA_CODIGO FROM MAESTRO WHERE MA_INV_GEN='G' AND ME_COM=@ME_KILOGRAMOS)
			and convert(varchar(11),dbo.MAESTRO.MA_ULTIMAMODIF,101)=@FECHA


			UPDATE MAESTRO
			SET EQ_GEN = 1
			WHERE MA_PESO_KG=0 and EQ_GEN <> 1
			AND ME_COM not in (SELECT ME_CODIGO1 FROM EQUIVALE WHERE ME_CODIGO2 in (select ME_KILOGRAMOS from configuracion))
			AND MA_GENERICO IN (SELECT MA_CODIGO FROM MAESTRO WHERE MA_INV_GEN='G' AND ME_COM=@ME_KILOGRAMOS)
			and convert(varchar(11),dbo.MAESTRO.MA_ULTIMAMODIF,101)=@FECHA

			UPDATE MAESTRO
			SET EQ_GEN = 1
			WHERE EQ_GEN <> 1 and ME_COM in (select ME_KILOGRAMOS from configuracion)
			AND MA_GENERICO IN (SELECT MA_CODIGO FROM MAESTRO WHERE MA_INV_GEN='G' AND ME_COM=@ME_KILOGRAMOS)
			and convert(varchar(11),dbo.MAESTRO.MA_ULTIMAMODIF,101)=@FECHA

		end































GO
