SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[CopiaClientes] (@BDOrigen varchar(50), @BDDestino varchar(50))    as


EXEC('INSERT INTO CLIENTE(CL_RAZON, AC_CODIGO, CL_GIRO, CL_RFC, CL_REP_RFC, CL_REP_PAT, CL_REP_MAT, CL_REP_NOM, PO_CODIGO, CL_REP_EMAIL, CL_REP_TEL, 
                      CL_REP_FAX, CL_REP_CURP, TE_CODIGO, CL_CON_VEN, CL_LIMCRE, CL_COD_FAB, CL_CRH, CL_EIN, CL_RNIE, CL_IRS, CL_EXPED, CL_RNIM, 
                      CL_ANIOPPS, CL_NOPPS, CL_ALTEX, CL_TIPO, CL_EMPRESA, CL_REGPEDCONS, CL_PRODUCTOS, SE_CODIGO, CL_CORTO, CL_ANIOMAQ, 
                      CL_NOMAQ, CL_REGOCTAVA, VI_CODIGO, CL_MATRIZ, AG_MEX, AG_USA, CL_TRAFICO, CL_CURP, IT_ENTRADA, IT_SALIDA, MO_CODIGO, 
                      CT_CODIGO, AD_CODIGO, AD_SALIDA, PU_CARGA, PU_SALIDA, PU_ENTRADA, PU_DESTINO, SPI_CODIGO, PU_CARGAS, PU_SALIDAS, 
                      PU_ENTRADAS, PU_DESTINOS, ZO_CODIGO, CL_PASARCONTENEDOR, BT_BTIPO, CL_REGPRONAC, CL_TIPOPRODUCTOR, ET_TYPECODE1, 
                      ET_TYPECODE2, ET_TYPECODEENT, ET_TYPECODEENT2, US_CODIGO, MT_CODIGO, CL_FIRMSCODE, FE_INVOICETYPE, CL_DESC_GRAL, 
                      FE_HEADER, FE_FOOTER, FI_INVOICETYPE, FI_DESC_GRAL, FI_HEADER, FI_FOOTER, CL_CLAVEABT, CL_VIRTPAGACONTRIB, TN_ENTRADA, 
                      TN_SALIDA, CL_CODEHTC, CL_EMPCERTIFICADA, CL_AUTFRONTERIZA, TV_CODIGO, CL_REPLEGTESTNOTARIAL, CL_FECHAREPLEG, 
                      CL_REGREVORIGEN, CL_EMANIFESTCODE, CL_TIPOPROVEE, CL_IMMEX)

SELECT     CL_RAZON, AC_CODIGO, CL_GIRO, CL_RFC, CL_REP_RFC, CL_REP_PAT, CL_REP_MAT, CL_REP_NOM, PO_CODIGO, CL_REP_EMAIL, CL_REP_TEL, 
                      CL_REP_FAX, CL_REP_CURP, TE_CODIGO, CL_CON_VEN, CL_LIMCRE, CL_COD_FAB, CL_CRH, CL_EIN, CL_RNIE, CL_IRS, CL_EXPED, CL_RNIM, 
                      CL_ANIOPPS, CL_NOPPS, CL_ALTEX, CL_TIPO, CL_EMPRESA, CL_REGPEDCONS, CL_PRODUCTOS, SE_CODIGO, CL_CORTO, CL_ANIOMAQ, 
                      CL_NOMAQ, CL_REGOCTAVA, VI_CODIGO, CL_MATRIZ, AG_MEX, AG_USA, CL_TRAFICO, CL_CURP, IT_ENTRADA, IT_SALIDA, MO_CODIGO, 
                      CT_CODIGO, AD_CODIGO, AD_SALIDA, PU_CARGA, PU_SALIDA, PU_ENTRADA, PU_DESTINO, SPI_CODIGO, PU_CARGAS, PU_SALIDAS, 
                      PU_ENTRADAS, PU_DESTINOS, ZO_CODIGO, CL_PASARCONTENEDOR, BT_BTIPO, CL_REGPRONAC, CL_TIPOPRODUCTOR, ET_TYPECODE1, 
                      ET_TYPECODE2, ET_TYPECODEENT, ET_TYPECODEENT2, US_CODIGO, MT_CODIGO, CL_FIRMSCODE, FE_INVOICETYPE, CL_DESC_GRAL, 
                      FE_HEADER, FE_FOOTER, FI_INVOICETYPE, FI_DESC_GRAL, FI_HEADER, FI_FOOTER, CL_CLAVEABT, CL_VIRTPAGACONTRIB, TN_ENTRADA, 
                      TN_SALIDA, CL_CODEHTC, CL_EMPCERTIFICADA, CL_AUTFRONTERIZA, TV_CODIGO, CL_REPLEGTESTNOTARIAL, CL_FECHAREPLEG, 
                      CL_REGREVORIGEN, CL_EMANIFESTCODE, CL_TIPOPROVEE, CL_IMMEX
FROM         '+@BDOrigen+'.DBO.CLIENTE
WHERE CL_RAZON NOT IN (SELECT CL_RAZON FROM CLIENTE)')


exec('insert into DIR_CLIENTE(CL_CODIGO, DI_IDENTIF, DI_CALLE, DI_NOEXT, DI_NOINT, DI_COL, DI_CP, DI_POBOX, DI_CIUDAD, DI_MUNIC, ES_CODIGO, 
                      PA_CODIGO, DI_REFER, DI_TEL1, DI_TEL2, DI_FAX, DI_FISCAL, DI_EMAIL, PU_CODIGO, ADL_IDADMON, DI_COD_FAB, DI_LOCPLANTA, 
                      DI_PLANTA, DI_TIPO, MU_CODIGO, DI_FECHAINI, DI_FECHAFIN, DI_ENVIARSAAI)

SELECT     CLIENTE_1.CL_CODIGO, DIR_CLIENTEOrig.DI_IDENTIF, DIR_CLIENTEOrig.DI_CALLE, DIR_CLIENTEOrig.DI_NOEXT, DIR_CLIENTEOrig.DI_NOINT, 
                      DIR_CLIENTEOrig.DI_COL, DIR_CLIENTEOrig.DI_CP, DIR_CLIENTEOrig.DI_POBOX, DIR_CLIENTEOrig.DI_CIUDAD, DIR_CLIENTEOrig.DI_MUNIC, DIR_CLIENTEOrig.ES_CODIGO, 
                      DIR_CLIENTEOrig.PA_CODIGO, DIR_CLIENTEOrig.DI_REFER, DIR_CLIENTEOrig.DI_TEL1, DIR_CLIENTEOrig.DI_TEL2, DIR_CLIENTEOrig.DI_FAX, DIR_CLIENTEOrig.DI_FISCAL, 
                      DIR_CLIENTEOrig.DI_EMAIL, DIR_CLIENTEOrig.PU_CODIGO, DIR_CLIENTEOrig.ADL_IDADMON, DIR_CLIENTEOrig.DI_COD_FAB, DIR_CLIENTEOrig.DI_LOCPLANTA, 
                      DIR_CLIENTEOrig.DI_PLANTA, DIR_CLIENTEOrig.DI_TIPO, DIR_CLIENTEOrig.MU_CODIGO, DIR_CLIENTEOrig.DI_FECHAINI, DIR_CLIENTEOrig.DI_FECHAFIN, 
                      DIR_CLIENTEOrig.DI_ENVIARSAAI
FROM         '+@BDOrigen+'.DBO.DIR_CLIENTE DIR_CLIENTEOrig INNER JOIN
                      '+@BDOrigen+'.DBO.CLIENTE CLIENTEOrig ON DIR_CLIENTEOrig.CL_CODIGO = CLIENTEOrig.CL_CODIGO INNER JOIN
                      CLIENTE CLIENTE_1 ON CLIENTEOrig.CL_RAZON = CLIENTE_1.CL_RAZON
WHERE DIR_CLIENTEOrig.DI_IDENTIF NOT IN (SELECT CL1.DI_IDENTIF FROM DIR_CLIENTE CL1)')

GO
