SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[SP_FILL_BOM_DESCTEMP] (@FED_INDICED INT, @BST_PT Int, @BST_ENTRAVIGOR DateTime, @FED_CANT decimal(38,6), @CODIGOFACTURA INT, @MENSAJE1 char(1)='N' output)   as

SET NOCOUNT ON 
declare @BST_HIJO int, @BST_INCORPOR decimal(38,6), @BST_PERINI datetime, @BST_PERINI2 datetime, @ma_struct int, @fed_tip_ens char(1), @TEmbarque char(1),
    @BST_TIPODESC varchar(5)

	exec sp_CreaBOM_DESCTEMP


set @MENSAJE1='N'

if (select cf_estructalt from configuracion)='S'
begin
	select @ma_struct=ma_struct, @fed_tip_ens=fed_tip_ens from factexpdet where fed_indiced=@FED_INDICED


	IF @ma_struct is not null and @ma_struct>0 and exists(select * from bom_struct where bsu_subensamble=@ma_struct and bst_perini<=@BST_ENTRAVIGOR and bst_perini>=@BST_ENTRAVIGOR)
	set @BST_PT=@ma_struct
end



	SELECT     @TEmbarque = CFQ_TIPO
	FROM CONFIGURATEMBARQUE 
	WHERE TQ_CODIGO IN (SELECT TQ_CODIGO FROM FACTEXP WHERE FE_CODIGO=@CODIGOFACTURA)


	if @TEmbarque='D'
	set @BST_TIPODESC='D'
	else 
	set @BST_TIPODESC='N'
	

			insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
			    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
			   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)

			SELECT     dbo.BOM_STRUCT.BST_HIJO, sum((BOM_STRUCT.BST_INCORPOR+(CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and
					isnull(MAESTRO.MA_POR_DESP,0)<>0 then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) 
					else 0 end))) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
			                      case when dbo.CONFIGURATIPO.CFT_TIPO in ('P', 'S') then 'R' else dbo.CONFIGURATIPO.CFT_TIPO end, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
			                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
			                      dbo.BOM_STRUCT.BST_TIP_ENS, @FED_CANT, @CODIGOFACTURA, 'B1', @BST_TIPODESC,
					@BST_PT, @FED_INDICED, @BST_PT, @BST_ENTRAVIGOR, dbo.MAESTRO.MA_PESO_KG, isnull((SELECT MA_COSTO FROM VMAESTROCOST
				WHERE MA_CODIGO=dbo.BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
			FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
			                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
			                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
			WHERE ((dbo.CONFIGURATIPO.CFT_TIPO<>'P' and dbo.CONFIGURATIPO.CFT_TIPO<>'S') and (dbo.BOM_STRUCT.BST_TIP_ENS='C' or dbo.BOM_STRUCT.BST_TIP_ENS is null))
			or ((dbo.CONFIGURATIPO.CFT_TIPO='P' or dbo.CONFIGURATIPO.CFT_TIPO='S') and (dbo.BOM_STRUCT.BST_TIP_ENS='C' or dbo.BOM_STRUCT.BST_TIP_ENS='A' or dbo.BOM_STRUCT.BST_TIP_ENS='E' or dbo.BOM_STRUCT.BST_TIP_ENS='O'))

			GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
			                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
			                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
			                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.MAESTRO.MA_PESO_KG
			HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_PT) 
			AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
			AND SUM(dbo.BOM_STRUCT.BST_INCORPOR) >0

	/* explosion de subensambles */
	declare CUR_BOMSTRUCT cursor for
		SELECT     dbo.BOM_STRUCT.BST_HIJO, sum(BOM_STRUCT.BST_INCORPOR) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_PERINI
		FROM         dbo.BOM_STRUCT LEFT OUTER JOIN dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
		                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
		WHERE     (dbo.CONFIGURATIPO.CFT_TIPO = 'P' OR dbo.CONFIGURATIPO.CFT_TIPO = 'S') 
			AND (dbo.BOM_STRUCT.BST_TIP_ENS = 'F' OR dbo.BOM_STRUCT.BST_TIP_ENS IS NULL)
			AND (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_PT) 
			AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
		GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_PERINI
		HAVING SUM(dbo.BOM_STRUCT.BST_INCORPOR) >0
	
	 OPEN CUR_BOMSTRUCT
	
	
		FETCH NEXT FROM CUR_BOMSTRUCT INTO @BST_HIJO, @BST_INCORPOR, @BST_PERINI
		
	
	  WHILE (@@fetch_status = 0) 
	
	  BEGIN  
	
			exec  SP_FILL_BOM_DESCTEMP1 @FED_INDICED, @BST_PT, @BST_HIJO, @BST_ENTRAVIGOR, @BST_PERINI, 
			@FED_CANT, @CODIGOFACTURA, @BST_INCORPOR, 1, @MENSAJE=@MENSAJE1 OUTPUT
	
			if @MENSAJE1='S'
			begin				
				--print @MENSAJE1
				break
			end
	
	
	
		FETCH NEXT FROM CUR_BOMSTRUCT INTO @BST_HIJO, @BST_INCORPOR, @BST_PERINI	
	END
	
	CLOSE CUR_BOMSTRUCT
	DEALLOCATE CUR_BOMSTRUCT

GO
