SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO













CREATE PROCEDURE [dbo].[SP_FACTIMPREVSIONIMPRESION] (@FI_CODIGO INT)   as

declare @sinGrupo char(1), @CFV_PEDCONSOLIDA CHAR(1), @CFV_NOREMESA CHAR(1), @CFV_NOGUIA CHAR(1), @CFV_CTRANSPOR CHAR(1), 
      @CFV_MEDIOTRANS CHAR(1), @CFV_PLACASMX CHAR(1), @CFV_PLACASUSA CHAR(1), @CFV_REGISTRO CHAR(1), 
      @CFV_BULTOS CHAR(1), @CFV_NOMBRE CHAR(1), @CFV_COSTOUNI CHAR(1), @CFV_CANTIDAD CHAR(1), @CFV_TARIFAUSA CHAR(1), 
      @CFV_TARIFAMX CHAR(1), @CFV_TASAMX CHAR(1), @CFV_GRUPOGEN CHAR(1), @CFV_PESONETO CHAR(1), 
      @CFV_PESOBRUTO CHAR(1), @CFV_ORDCOMPRA CHAR(1), @CFV_ORDTRABAJO CHAR(1), @CFV_NOENTRADA CHAR(1)

	delete from FACTIMPADVERTENCIA where fi_codigo=@FI_CODIGO

	
	SELECT  @CFV_PEDCONSOLIDA=CFV_PEDCONSOLIDA, 
		@CFV_NOREMESA=CFV_NOREMESA, 
		@CFV_NOGUIA=CFV_NOGUIA, 
		@CFV_CTRANSPOR=CFV_CTRANSPOR, 
		@CFV_MEDIOTRANS=CFV_MEDIOTRANS, 
		@CFV_PLACASMX=CFV_PLACASMX, 
		@CFV_PLACASUSA=CFV_PLACASUSA, 
		@CFV_REGISTRO=CFV_REGISTRO, 
	        @CFV_BULTOS=CFV_BULTOS, 
		-- detalle
		@CFV_NOMBRE=CFV_NOMBRE,  -- ya
		@CFV_COSTOUNI=CFV_COSTOUNI, -- ya
		@CFV_CANTIDAD=CFV_CANTIDAD, -- ya
		@CFV_TARIFAUSA=CFV_TARIFAUSA, -- ya
		@CFV_TARIFAMX=CFV_TARIFAMX, -- ya
		@CFV_TASAMX=CFV_TASAMX, -- ya
		@CFV_GRUPOGEN=CFV_GRUPOGEN,  -- ya
		@CFV_PESONETO=CFV_PESONETO, 
		@CFV_PESOBRUTO=CFV_PESOBRUTO, 
		@CFV_ORDCOMPRA=CFV_ORDCOMPRA, 
		@CFV_ORDTRABAJO=CFV_ORDTRABAJO, 
		@CFV_NOENTRADA=CFV_NOENTRADA
	FROM         CONFIGURAREVISAVAL
	WHERE     (CFV_FORMATAG = 44)




	if @CFV_PEDCONSOLIDA = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* No. Pedimento Consoliado Vacio' 
	FROM       FACTIMP
	WHERE   (FC_CODIGO = 0 OR FC_CODIGO IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO) 
	AND CP_CODIGO IN (SELECT CP_CODIGO FROM CLAVEPED WHERE CP_CONSOLIDADO='S')


	if @CFV_NOREMESA = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* No. Remesa Vacia' 
	FROM       FACTIMP
	WHERE   (FI_CONSECUTIVOPED = '' OR FI_CONSECUTIVOPED IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO) 
	AND CP_CODIGO IN (SELECT CP_CODIGO FROM CLAVEPED WHERE CP_CONSOLIDADO='S')


	if @CFV_NOGUIA = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* No. Guia Vacia' 
	FROM       FACTIMP
	WHERE   (FI_GUIA = '' OR FI_GUIA IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO) 


	if @CFV_CTRANSPOR = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Comp. Transportista Vacia' 
	FROM       FACTIMP
	WHERE   (CT_CODIGO = 0 OR CT_CODIGO IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO) 


	if @CFV_MEDIOTRANS = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Medio de Transporte Vacio' 
	FROM       FACTIMP
	WHERE   (MT_CODIGO = 0 OR MT_CODIGO IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO)

	if @CFV_PLACASMX = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Placas Mx. Vacias' 
	FROM       FACTIMP
	WHERE   (FI_TRAC_MX = '' OR FI_TRAC_MX IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO)


	if @CFV_PLACASUSA = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Placas US. Vacias' 
	FROM       FACTIMP
	WHERE   (FI_TRAC_US = '' OR FI_TRAC_US IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO)

	if @CFV_REGISTRO = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Registro del Contenedor Vacio' 
	FROM       FACTIMP
	WHERE   (FI_CONT_REG = '' OR FI_CONT_REG IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO)

	if @CFV_BULTOS = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Total de Bultos Vacio' 
	FROM       FACTIMP
	WHERE   (FI_TOTALB = 0 OR FI_TOTALB IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO)

	/*  Factores de conversion */
/*
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)

	SELECT     dbo.FACTIMP.FI_CODIGO, 
	                      '* Posible Factor de Conversion erroneo, No. Parte: ' + dbo.FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTIMPDET.FID_CANT_ST) + ', UM No. Parte:' + MEDIDA_2.ME_CORTO + ', UM Generico:' + isnull(MEDIDA_1.ME_CORTO,'')
	FROM         dbo.FACTIMP INNER JOIN
	                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTIMPDET.ME_GEN = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_2 ON dbo.FACTIMPDET.ME_CODIGO = MEDIDA_2.ME_CODIGO
	WHERE     (dbo.FACTIMPDET.ME_CODIGO <> dbo.FACTIMPDET.ME_GEN) AND (dbo.FACTIMPDET.EQ_GEN = 1)
	and (FACTIMP.FI_CODIGO = @FI_CODIGO) AND isnull(MEDIDA_1.ME_CORTO,'')<>'SET' AND  isnull(MEDIDA_2.ME_CORTO,'')<>'RLL' AND isnull(MEDIDA_1.ME_CORTO,'')<>''
*/

	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)

	SELECT     dbo.FACTIMP.FI_CODIGO, 
	                      '* Registro en Detalle con posible Factor de Conversion erroneo, No. Parte: ' + dbo.FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTIMPDET.FID_CANT_ST) + ', UM No. Parte:' + MEDIDA_2.ME_CORTO + ', UM Generico:' + isnull(MEDIDA_1.ME_CORTO,'')
	FROM         dbo.FACTIMP INNER JOIN
	                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTIMPDET.ME_GEN = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_2 ON dbo.FACTIMPDET.ME_CODIGO = MEDIDA_2.ME_CODIGO
	WHERE     (dbo.FACTIMPDET.ME_CODIGO = dbo.FACTIMPDET.ME_GEN) AND (dbo.FACTIMPDET.EQ_GEN <> 1)
	and (FACTIMP.FI_CODIGO = @FI_CODIGO)



	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)

	SELECT     dbo.FACTIMP.FI_CODIGO, 
	                      '* Registro en Detalle con Factor de Conversion erroneo Grupo Gen en KG, No. Parte: ' + dbo.FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTIMPDET.FID_CANT_ST) + ', UM Generico: KG, Peso Unitario Kg:'+CONVERT(varchar(50),dbo.FACTIMPDET.FID_PES_UNI)+' <> Factor de Conversion: '+CONVERT(varchar(50),dbo.FACTIMPDET.EQ_GEN)
	FROM         dbo.FACTIMP INNER JOIN
	                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
	WHERE     dbo.FACTIMPDET.ME_GEN=(SELECT ME_KILOGRAMOS FROM CONFIGURACION) AND (round(dbo.FACTIMPDET.EQ_GEN,6) <> ROUND(dbo.FACTIMPDET.FID_PES_UNI,6))
	and (FACTIMP.FI_CODIGO = @FI_CODIGO)



	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)

	SELECT     dbo.FACTIMP.FI_CODIGO, 
	                      '* Registro en Detalle con Factor de Conversion erroneo F. Arancelaria Imp. Mx en KG, No. Parte: ' + dbo.FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTIMPDET.FID_CANT_ST) + ', UM F. Arancelaria: KG, Peso Unitario Kg:'+CONVERT(varchar(50),dbo.FACTIMPDET.FID_PES_UNI)+' <> Factor de Conversion: '+CONVERT(varchar(50),dbo.FACTIMPDET.EQ_IMPMX)
	FROM         dbo.FACTIMP INNER JOIN
	                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
	WHERE     dbo.FACTIMPDET.ME_ARIMPMX=(SELECT ME_KILOGRAMOS FROM CONFIGURACION) AND (round(dbo.FACTIMPDET.EQ_IMPMX,6) <> ROUND(dbo.FACTIMPDET.FID_PES_UNI,6))
	and (FACTIMP.FI_CODIGO = @FI_CODIGO)



	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)

	SELECT     dbo.FACTIMP.FI_CODIGO, 
	                      '* Registro en Detalle con Factor de Conversion erroneo Grupo VS F. Arancelaria, No. Parte: ' + dbo.FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      dbo.FACTIMPDET.FID_CANT_ST) + ', UM F. Arancelaria:' + MEDIDA_2.ME_CORTO + ', UM Generico:' + isnull(MEDIDA_1.ME_CORTO,'')
	FROM         dbo.FACTIMP INNER JOIN
	                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTIMPDET.ME_GEN = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_2 ON dbo.FACTIMPDET.ME_ARIMPMX = MEDIDA_2.ME_CODIGO
	WHERE     (dbo.FACTIMPDET.ME_ARIMPMX = dbo.FACTIMPDET.ME_GEN) AND (round(dbo.FACTIMPDET.EQ_GEN,6) <> round(dbo.FACTIMPDET.EQ_IMPMX,6))
	and (FACTIMP.FI_CODIGO = @FI_CODIGO)


	if @CFV_CANTIDAD='S'
	begin
		INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	
		SELECT     dbo.FACTIMP.FI_CODIGO, 
		                      '* Registro en Detalle con Cantidad Erronea, Con la UM Seleccionada no se permite la Cantidad con punto decimal, No. Parte: ' + dbo.FACTIMPDET.FID_NOPARTE +', UM : ' + MEDIDA_1.ME_CORTO 
		FROM         dbo.FACTIMP INNER JOIN
		                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
		                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTIMPDET.ME_CODIGO = MEDIDA_1.ME_CODIGO 
		WHERE     (ME_CLA_PED in ('15', '6', '12', '9')) AND ROUND(FID_CANT_ST, 6) - dbo.Trunc(ROUND(FID_CANT_ST, 6), 0)>0
		--AND (CHARINDEX('.', CONVERT(varchar(50), FID_CANT_ST)) <> 0) 
		and (FACTIMP.FI_CODIGO = @FI_CODIGO)


		INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	
		SELECT     dbo.FACTIMP.FI_CODIGO, 
		                      '* Registro en Detalle Sin Cantidad, No. Parte: ' + dbo.FACTIMPDET.FID_NOPARTE +', UM : ' + MEDIDA_1.ME_CORTO 
		FROM         dbo.FACTIMP INNER JOIN
		                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
		                      dbo.MEDIDA MEDIDA_1 ON dbo.FACTIMPDET.ME_CODIGO = MEDIDA_1.ME_CODIGO 
		WHERE   (FACTIMPDET.FID_CANT_ST =0 OR FACTIMPDET.FID_CANT_ST IS NULL) 
		and (FACTIMP.FI_CODIGO = @FI_CODIGO)


	
	end




	if @CFV_NOMBRE='S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FACTIMP.FI_CODIGO, '* Registro en Detalle Sin Descripcion en espa¤ol, No. Parte: ' + FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTIMPDET.FID_CANT_ST) + ' ' + MEDIDA.ME_CORTO 
	FROM         FACTIMP INNER JOIN
	                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTIMPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTIMPDET.FID_NOMBRE IS NULL OR FACTIMPDET.FID_NOMBRE='' OR FACTIMPDET.FID_NOMBRE='TEMP' OR FACTIMPDET.FID_NOMBRE='.') 
	and (FACTIMP.FI_CODIGO = @FI_CODIGO)


	/* Costos */
	if @CFV_COSTOUNI='S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FACTIMP.FI_CODIGO, '* Registro en Detalle Sin Costo Unitario, No. Parte: ' + FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTIMPDET.FID_CANT_ST) + ' ' + MEDIDA.ME_CORTO 
	FROM         FACTIMP INNER JOIN
	                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTIMPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTIMPDET.FID_COS_UNI IS NULL OR FACTIMPDET.FID_COS_UNI=0) 
	and (FACTIMP.FI_CODIGO = @FI_CODIGO)


	
	if @CFV_TASAMX='S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FACTIMP.FI_CODIGO, '* Registro en Detalle Sin Tasa de Importacion Mx, No. Parte: ' + FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTIMPDET.FID_CANT_ST) + ' ' + MEDIDA.ME_CORTO AS Expr1
	FROM         FACTIMP INNER JOIN
	                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTIMPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTIMP.FI_CODIGO = @FI_CODIGO) AND (FACTIMPDET.FID_POR_DEF= -1)



	if (SELECT     Count(*)
	FROM         FACTIMP INNER JOIN
	                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTIMPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTIMPDET.MA_GENERICO = 0 OR
	                      FACTIMPDET.MA_GENERICO IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO))>0
	set @sinGrupo='S'



	IF @CFV_GRUPOGEN = 'S' -- grupo generico
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FACTIMP.FI_CODIGO, '* Registro en Detalle Sin Grupo Generico, No. Parte: ' + FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTIMPDET.FID_CANT_ST) + ' ' + MEDIDA.ME_CORTO 
	FROM         FACTIMP INNER JOIN
	                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTIMPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTIMPDET.MA_GENERICO = 0 OR
	                      FACTIMPDET.MA_GENERICO IS NULL) AND (FACTIMP.FI_CODIGO = @FI_CODIGO)


	if @CFV_TARIFAUSA = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Registro en Detalle con Fraccion Exp. USA Incorrecta, No. Parte: ' + FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), FID_CANT_ST)
	FROM       FACTIMPDET
	WHERE   (AR_EXPFO = 0 OR AR_EXPFO IS NULL) AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 


	if @CFV_TARIFAMX = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Registro en Detalle con Fraccion Imp. MX Incorrecta, No. Parte: ' + FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), FID_CANT_ST)
	FROM       FACTIMPDET left outer join ARANCEL on FACTIMPDET.AR_IMPMX = ARANCEL.AR_CODIGO
	WHERE   (AR_IMPMX = 0 OR AR_IMPMX IS NULL OR ARANCEL.AR_FRACCION='SINFRACCION' OR ARANCEL.AR_FRACCION='SIN FRACCION' OR ARANCEL.AR_FRACCION='00000000'
		OR ARANCEL.AR_FRACCION='99999999')
		 AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 


	IF(SELECT CF_PESOS_IMP FROM CONFIGURACION)='K'
	begin
		if @CFV_PESONETO='S'
		INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
		SELECT     FACTIMPDET.FI_CODIGO, '* Registro en Detalle con Peso Neto en cero (Kg) en No. Parte: '+ FACTIMPDET.FID_NOPARTE +' Peso Bruto: ' +convert(varchar(50),FID_PES_BRU)
		FROM         FACTIMPDET
		WHERE     (FID_PES_NET=0) AND (FID_CANTEMP = 0)
		AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 

		if @CFV_PESOBRUTO='S'
		INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
		SELECT     FACTIMPDET.FI_CODIGO, '* Registro en Detalle con Peso Bruto en cero (Kg) en No. Parte: '+ FACTIMPDET.FID_NOPARTE +' Peso Neto: ' +convert(varchar(50),FID_PES_NET)
		FROM         FACTIMPDET
		WHERE     (FID_PES_BRU=0) AND (FID_CANTEMP = 0)
		AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 
	end
	else
	begin
		if @CFV_PESONETO='S'
		INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
		SELECT     FACTIMPDET.FI_CODIGO, '* Registro en Detalle con Peso Neto en cero (Lb) en No. Parte: '+ FACTIMPDET.FID_NOPARTE +' Peso Bruto: ' +convert(varchar(50),FID_PES_BRULB)
		FROM         FACTIMPDET
		WHERE     (FID_PES_NETLB=0) AND (FID_CANTEMP = 0)
		AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 

		if @CFV_PESOBRUTO='S'
		INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
		SELECT     FACTIMPDET.FI_CODIGO, '* Registro en Detalle con Peso Bruto en cero (Lb) en No. Parte: '+ FACTIMPDET.FID_NOPARTE +' Peso Neto: ' +convert(varchar(50),FID_PES_NETLB)
		FROM         FACTIMPDET
		WHERE     (FID_PES_BRULB=0) AND (FID_CANTEMP = 0)
		AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 
	end



	if @CFV_ORDCOMPRA = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Registro en Detalle con Orden de Compra Vacia, No. Parte: ' + FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), FID_CANT_ST)
	FROM       FACTIMPDET
	WHERE   (FID_ORD_COMP = '' OR FID_ORD_COMP IS NULL) AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 


	if @CFV_ORDTRABAJO = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Registro en Detalle con Orden de Trabajo Vacia, No. Parte: ' + FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), FID_CANT_ST)
	FROM       FACTIMPDET
	WHERE   (FID_NOORDEN = '' OR FID_NOORDEN IS NULL) AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 



	if @CFV_NOENTRADA = 'S'
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FI_CODIGO, '* Registro en Detalle con No. de Entrada Vacia, No. Parte: ' + FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), FID_CANT_ST)
	FROM       FACTIMPDET
	WHERE   (FID_NUM_ENT = '' OR FID_NUM_ENT IS NULL) AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 
/*	
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FACTIMP.FI_CODIGO, '* Sin Sector (Tipo de tasa PPS), No. Parte: ' + FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTIMPDET.FID_CANT_ST) + ' ' + MEDIDA.ME_CORTO 
	FROM         FACTIMP INNER JOIN
	                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTIMPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTIMPDET.FID_SEC_IMP = 0 OR
	                      FACTIMPDET.FID_SEC_IMP IS NULL) AND (FACTIMPDET.FID_DEF_TIP = 'S') AND (FACTIMP.FI_CODIGO = @FI_CODIGO)

	
	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FACTIMP.FI_CODIGO, '* Sin Tratado (Tipo de tasa Bajo Tratado), No. Parte: ' + FACTIMPDET.FID_NOPARTE + ' Cantidad: ' + CONVERT(varchar(50), 
	                      FACTIMPDET.FID_CANT_ST) + ' ' + MEDIDA.ME_CORTO
	FROM         FACTIMP INNER JOIN
	                      FACTIMPDET ON FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO LEFT OUTER JOIN
	                      MEDIDA ON FACTIMPDET.ME_CODIGO = MEDIDA.ME_CODIGO
	WHERE     (FACTIMPDET.FID_DEF_TIP = 'P') AND (FACTIMP.FI_CODIGO = @FI_CODIGO) AND (FACTIMPDET.SPI_CODIGO = 0 OR
	                      FACTIMPDET.SPI_CODIGO IS NULL)

	INSERT INTO FACTIMPADVERTENCIA(FI_CODIGO, FI_COMENTARIO)
	SELECT     FACTIMPDET.FI_CODIGO, '* Peso Bruto (Kg) Incorrecto en No. Parte: '+ FACTIMPDET.FID_NOPARTE +' PB: ' +convert(varchar(50),FID_PES_BRU)+' mayor que PN: '+ convert(varchar(50),FID_PES_NET)+' y sin Cantidad de Empaque' 
	FROM         FACTIMPDET
	WHERE     (FID_PES_BRU > FID_PES_NET) AND (FID_CANTEMP = 0)
	AND (FACTIMPDET.FI_CODIGO = @FI_CODIGO) 
*/

GO
