SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE dbo.SP_DELREL_FACTEXPEMP     as

BEGIN
DELETE  FROM FACTEXPRELEMPAQUE WHERE FED_INDICED NOT IN (SELECT FACTEXPRELEMPAQUE.FED_INDICED FROM FACTEXPRELEMPAQUE,FACTEXPDET WHERE FACTEXPRELEMPAQUE.FED_INDICED = FACTEXPDET.FED_INDICED);
DELETE FROM  FACTEXPRELEMPAQUE WHERE FEE_INDICE NOT IN (SELECT FACTEXPRELEMPAQUE.FEE_INDICE FROM FACTEXPRELEMPAQUE,FACTEXPEMPAQUE WHERE FACTEXPRELEMPAQUE.FEE_INDICE = FACTEXPEMPAQUE.FEE_INDICE);
END




GO
