SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CORRIGELISTAEXPSALDOSFE] (@FE_CODIGO INT)   as


ALTER TABLE LISTAEXPDET DISABLE trigger [Update_LISTAEXPDet]


	UPDATE LISTAEXPDET
	SET     LED_SALDO = LED_CANT - isnull((SELECT SUM(FACTEXPDET.FED_CANT) FROM FACTEXPDET 
			    WHERE FACTEXPDET.LED_INDICED = LISTAEXPDET.LED_INDICED),0)
	WHERE LED_SALDO <> LED_CANT - isnull((SELECT SUM(FACTEXPDET.FED_CANT) FROM FACTEXPDET 
			    WHERE FACTEXPDET.LED_INDICED = LISTAEXPDET.LED_INDICED),0)
	AND LED_INDICED IN (SELECT LED_INDICED FROM FACTEXPDET WHERE FE_CODIGO=@FE_CODIGO AND LED_INDICED IS NOT NULL)


	UPDATE LISTAEXPDET
	SET     LED_ENUSO='N'
	WHERE     (LED_SALDO = LED_CANT) AND (LED_ENUSO <> 'N' OR LED_ENUSO IS NULL)
	AND LED_INDICED IN (SELECT LED_INDICED FROM FACTEXPDET WHERE FE_CODIGO=@FE_CODIGO AND LED_INDICED IS NOT NULL)

	UPDATE LISTAEXPDET
	SET     LED_ENUSO='S'
	WHERE     (LED_SALDO <> LED_CANT) AND (LED_ENUSO <> 'S' OR LED_ENUSO IS NULL)	
	AND LED_INDICED IN (SELECT LED_INDICED FROM FACTEXPDET WHERE FE_CODIGO=@FE_CODIGO AND LED_INDICED IS NOT NULL)

	UPDATE LISTAEXP
	SET LE_ESTATUS='A'
	WHERE LE_CODIGO IN
	(SELECT LE_CODIGO FROM LISTAEXPDET WHERE LISTAEXPDET.LE_CODIGO=LISTAEXP.LE_CODIGO AND
	LED_ENUSO='N' GROUP BY LE_CODIGO)
	AND LE_CODIGO IN (SELECT LE_CODIGO FROM FACTEXPDET WHERE FE_CODIGO=@FE_CODIGO AND LE_CODIGO IS NOT NULL)


	UPDATE LISTAEXP
	SET LE_ESTATUS='C'
	WHERE LE_CODIGO IN
	(SELECT LE_CODIGO FROM LISTAEXPDET WHERE LISTAEXPDET.LE_CODIGO=LISTAEXP.LE_CODIGO 
	GROUP BY LE_CODIGO HAVING SUM(LED_SALDO) = 0 AND SUM(LED_CANT)>0)
	AND LE_CODIGO IN (SELECT LE_CODIGO FROM FACTEXPDET WHERE FE_CODIGO=@FE_CODIGO AND LE_CODIGO IS NOT NULL)

ALTER TABLE LISTAEXPDET ENABLE trigger [Update_LISTAEXPDet]





GO
