SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




























CREATE PROCEDURE dbo.SP_REPPPSMDONACMAT ( @DAPCODIGO INT)   as

SET NOCOUNT ON 

DECLARE @MERCADONAC decimal(38,6), @MERCADONACdlls decimal(38,6)


if exists (select * 	FROM VREPPPSMDONACMAT WHERE DAP_CODIGO=@DAPCODIGO)
begin
	DECLARE CUR_DECANUALPPSTMDONACMAT CURSOR FOR
	
		SELECT SUM(VALOR), SUM(PID_CTOT_DLS)
		FROM VREPPPSMDONACMAT
		WHERE DAP_CODIGO=@DAPCODIGO
		GROUP BY DAP_CODIGO 
	
	OPEN CUR_DECANUALPPSTMDONACMAT
			
	FETCH NEXT FROM CUR_DECANUALPPSTMDONACMAT INTO @MERCADONAC, @MERCADONACdlls
	
	WHILE (@@FETCH_STATUS = 0) 
	BEGIN
	
	
		UPDATE DECANUALPPS
		SET DAP_MERCADONACMAT= floor(round(@MERCADONAC, 0)/1000),  DAP_MERCADONACMATUSD= floor(round(@MERCADONACdlls, 0)/1000) 
		WHERE DECANUALPPS.DAP_CODIGO = @DAPCODIGO
	
		FETCH NEXT FROM CUR_DECANUALPPSTMDONACMAT INTO @MERCADONAC, @MERCADONACdlls
	
	END
	
	
	CLOSE CUR_DECANUALPPSTMDONACMAT
	DEALLOCATE CUR_DECANUALPPSTMDONACMAT
end
else
begin
	UPDATE DECANUALPPS
	SET DAP_MERCADONACMAT=0,  DAP_MERCADONACMATUSD= 0
	WHERE DECANUALPPS.DAP_CODIGO = @DAPCODIGO

end





GO
