SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CreaTablaBOM_REP]   as

exec sp_droptable 'BOM_REP'
CREATE TABLE [dbo].[BOM_REP] (
	[BSR_CODIGO] [int] IDENTITY (1, 1) NOT NULL ,
	[BST_CODIGO] [int] NULL ,
	[BST_PT] [int] NULL ,
	[BST_CODIGOPT] [int] NULL ,
	[BST_PERTENECE] [int] NULL ,
	[BST_NIVEL] [int] NULL ,
	[BST_ENTRAVIGOR] [datetime] NULL ,
	[BST_HIJO] [int] NULL ,
	[BST_INCORPOR] decimal(38,6) NULL CONSTRAINT [DF_BOM_REP_BST_INCORPOR] DEFAULT (1),
	[BST_DISCH] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BOM_REP_BST_DISCH] DEFAULT ('S'),
	[TI_CODIGO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ME_CODIGO] [int] NULL ,
	[FACTCONV] decimal(28,14) NULL CONSTRAINT [DF_BOM_REP_FACTCONV] DEFAULT (1),
	[BST_PERINI] [datetime] NULL ,
	[BST_PERFIN] [datetime] NULL CONSTRAINT [DF_BOM_REP_BST_PERFIN] DEFAULT ('01/01/9999'),
	[ME_GEN] [int] NULL ,
	[BST_TRANS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_BOM_REP_BST_TRANS] DEFAULT ('N'),
	[BST_TIPOCOSTO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MA_TIP_ENS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PA_CODIGO] [int] NULL ,
	[BST_TIPO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SPI_CODIGO] [int] NULL ,
	[SPI_PT] [int] NULL,
	[BST_SEC] [smallint] NULL ,
	[PA_ORIGEN] [int] NULL ,
	[BSR_GRAV_MP] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_GRAV_MP] DEFAULT (0),
	[BSR_GRAV_ADD] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_GRAV_ADD] DEFAULT (0),
	[BSR_GRAV_EMP] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_GRAV_EMP] DEFAULT (0),
	[BSR_GRAV_GI] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_GRAV_GI] DEFAULT (0),
	[BSR_GRAV_GI_MX] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_GRAV_GI_MX] DEFAULT (0),
	[BSR_GRAV_MO] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_GRAV_MO] DEFAULT (0),
	[BSR_NG_MP] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_NG_MP] DEFAULT (0),
	[BSR_NG_ADD] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_NG_ADD] DEFAULT (0),
	[BSR_NG_EMP] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_NG_EMP] DEFAULT (0),
	[BSR_COSTO] [decimal](38, 6) NULL CONSTRAINT [DF_BOM_REP_BSR_COSTO] DEFAULT (0),
	[BSR_DEF_TIP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
	) ON [PRIMARY]



GO
