SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CAMBIAFILTROFORMULA]   as



DECLARE @PXS_CODIGO INTEGER,@PXS_CODIGONVO INTEGER,@PXF_CODIGO INTEGER,@PXF_CODIGONVO INTEGER



DECLARE CUR_SECCIONES CURSOR FOR
SELECT TempPlntExpSecc.PXS_CODIGO,TempPlntExpSecc.PXS_CODIGONVO FROM PLNTEXPSECC
INNER JOIN TempPlntExpSecc ON PLNTEXPSECC.PXS_CODIGO = TempPlntExpSecc.PXS_CODIGONVO
WHERE PLNTEXPSECC.PXS_FILTROFORMULA IS NOT NULL and PLNTEXPSECC.PXS_FILTROFORMULA <> ''
OPEN CUR_SECCIONES
FETCH NEXT FROM CUR_SECCIONES INTO @PXS_CODIGO,@PXS_CODIGONVO
WHILE (@@FETCH_STATUS = 0)
BEGIN
	DECLARE CUR_FORMULAS CURSOR FOR	
	SELECT PXF_CODIGO,PXF_CODIGONVO FROM TempPlntExpFormula
	WHERE PXS_CODIGO = @PXS_CODIGO
	OPEN CUR_FORMULAS
	FETCH NEXT FROM CUR_FORMULAS INTO @PXF_CODIGO,@PXF_CODIGONVO
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		UPDATE PLNTEXPSECC SET PXS_FILTROFORMULA = REPLACE(PXS_FILTROFORMULA,'@F'+CONVERT(VARCHAR(20),@PXF_CODIGO)+'F','@F'+CONVERT(VARCHAR(20),@PXF_CODIGONVO)+'F')
			WHERE PXS_CODIGO = @PXS_CODIGONVO
		FETCH NEXT FROM CUR_FORMULAS INTO @PXF_CODIGO,@PXF_CODIGONVO
	END
	CLOSE CUR_FORMULAS
	DEALLOCATE CUR_FORMULAS

	FETCH NEXT FROM CUR_SECCIONES INTO @PXS_CODIGO,@PXS_CODIGONVO
END

CLOSE CUR_SECCIONES
DEALLOCATE CUR_SECCIONES
GO
