SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[CAMBIA_FRACCION] (@anterior int, @nuevo int)   as


UPDATE ARANCELENTRY
SET AR_CODIGO=@nuevo
WHERE AR_CODIGO=@anterior

UPDATE BOM_ARANCEL
SET AR_CODIGO=@nuevo
WHERE AR_CODIGO=@anterior

UPDATE COMMINVDET
SET AR_IMPFO=@nuevo
WHERE AR_IMPFO=@anterior


UPDATE COSTSUBBASC247DET
SET AR_CODIGO=@nuevo
WHERE AR_CODIGO=@anterior

UPDATE DECANUALNVADET
SET AR_CODIGO=@nuevo
WHERE AR_CODIGO=@anterior

UPDATE DECANUALPPSDET
SET AR_CODIGO=@nuevo
WHERE AR_CODIGO=@anterior

UPDATE ENTRYSUMARA
SET AR_CODIGO=@nuevo
WHERE AR_CODIGO=@anterior

UPDATE ENTRYSUMARA
SET AR_ORIG=@nuevo
WHERE AR_ORIG=@anterior

UPDATE ENTRYSUMARA
SET AR_NG_EMP=@nuevo
WHERE AR_NG_EMP=@anterior

UPDATE FACTEXPBOM_ARANCEL
SET AR_CODIGO=@nuevo
WHERE AR_CODIGO=@anterior

UPDATE FACTEXPDET
SET AR_IMPMX=@nuevo
WHERE AR_IMPMX=@anterior

UPDATE FACTEXPDET
SET AR_EXPMX=@nuevo
WHERE AR_EXPMX=@anterior

UPDATE FACTEXPDET
SET AR_IMPFO=@nuevo
WHERE AR_IMPFO=@anterior


UPDATE FACTEXPDET
SET AR_ORIG=@nuevo
WHERE AR_ORIG=@anterior

UPDATE FACTEXPDET
SET AR_NG_EMP=@nuevo
WHERE AR_NG_EMP=@anterior

UPDATE FACTIMPDET
SET AR_IMPMX=@nuevo
WHERE AR_IMPMX=@anterior

UPDATE FACTIMPDET
SET AR_EXPFO=@nuevo
WHERE AR_EXPFO=@anterior

UPDATE MAESTRO
SET AR_IMPMX=@nuevo
WHERE AR_IMPMX=@anterior

UPDATE MAESTRO
SET AR_EXPMX=@nuevo
WHERE AR_EXPMX=@anterior

UPDATE MAESTRO
SET AR_IMPFO=@nuevo
WHERE AR_IMPFO=@anterior

UPDATE MAESTRO
SET AR_RETRA=@nuevo
WHERE AR_RETRA=@anterior

UPDATE MAESTRO
SET AR_DESP=@nuevo
WHERE AR_DESP=@anterior

UPDATE MAESTRO
SET AR_EXPFO=@nuevo
WHERE AR_EXPFO=@anterior

UPDATE MAESTRO
SET AR_IMPFOUSA=@nuevo
WHERE AR_IMPFOUSA=@anterior

UPDATE MAESTRO
SET AR_IMPEMPFOUSA=@nuevo
WHERE AR_IMPEMPFOUSA=@anterior

UPDATE PEDIMPDET
SET AR_IMPMX=@nuevo
WHERE AR_IMPMX=@anterior

UPDATE PEDIMPDET
SET AR_EXPFO=@nuevo
WHERE AR_EXPFO=@anterior

UPDATE PEDIMPDETB
SET AR_IMPMX=@nuevo
WHERE AR_IMPMX=@anterior

UPDATE PEDIMPDETB
SET AR_EXPFO=@nuevo
WHERE AR_EXPFO=@anterior

UPDATE PERMISO
SET AR_CODIGO=@nuevo
WHERE AR_CODIGO=@anterior

UPDATE PERMISODET
SET AR_IMPMX=@nuevo
WHERE AR_IMPMX=@anterior

UPDATE PERMISODET
SET AR_EXPMX=@nuevo
WHERE AR_EXPMX=@anterior

UPDATE PERMISOPT
SET AR_CODIGO=@nuevo
WHERE AR_CODIGO=@anterior

























GO
