SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_IMPEXCELRELPEDIMPFACT]   as

SET NOCOUNT ON 
DECLARE @NOPEDIMENTO VARCHAR(20), @TIPOMOVIMIENTO CHAR(1), @PICODIGO INT, @CCP_TIPO VARCHAR(5)


DELETE FROM IMPORTLOG WHERE IML_CBFORMA=35

if (select count(*) from IMPORTLOG)=0
DBCC CHECKIDENT (IMPORTLOG, RESEED, 0) WITH NO_INFOMSGS

delete from IMPEXCELRELPEDIMPFACT where FOLIOFACTURA=''

if exists(SELECT dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	FROM         dbo.FACTIMP RIGHT OUTER JOIN
	                      dbo.IMPEXCELRELPEDIMPFACT ON dbo.FACTIMP.FI_FOLIO = dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	WHERE     (dbo.FACTIMP.FI_FOLIO IS NULL) and dbo.IMPEXCELRELPEDIMPFACT.TIPOMOVIMIENTO='E')

	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR LA RELACION CON LA FACTURA CON FOLIO : ' +dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA +' POR QUE NO EXISTE EN LOS DOCUMENTOS DE ENTRADA', 35 
	FROM         dbo.FACTIMP RIGHT OUTER JOIN
	                      dbo.IMPEXCELRELPEDIMPFACT ON dbo.FACTIMP.FI_FOLIO = dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	WHERE     (dbo.FACTIMP.FI_FOLIO IS NULL) and dbo.IMPEXCELRELPEDIMPFACT.TIPOMOVIMIENTO='E'



if exists(SELECT dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	FROM         dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.IMPEXCELRELPEDIMPFACT ON dbo.FACTEXP.FE_FOLIO = dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	WHERE     (dbo.FACTEXP.FE_FOLIO IS NULL) and dbo.IMPEXCELRELPEDIMPFACT.TIPOMOVIMIENTO='S')

	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR LA RELACION CON LA FACTURA CON FOLIO : ' +dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA +' POR QUE NO EXISTE EN LOS DOCUMENTOS DE SALIDA', 35
	FROM         dbo.FACTEXP RIGHT OUTER JOIN
	                      dbo.IMPEXCELRELPEDIMPFACT ON dbo.FACTEXP.FE_FOLIO = dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	WHERE     (dbo.FACTEXP.FE_FOLIO IS NULL) and dbo.IMPEXCELRELPEDIMPFACT.TIPOMOVIMIENTO='S'



if exists(SELECT dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO
	FROM         dbo.PEDIMP RIGHT OUTER JOIN
	                      dbo.IMPEXCELRELPEDIMPFACT ON dbo.PEDIMP.PI_FOLIO = RIGHT(dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO,7)
	WHERE     (dbo.PEDIMP.PI_FOLIO IS NULL))

	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR LA RELACION CON EL PEDIMENTO FOLIO : ' +dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO +' POR QUE NO EXISTE EN LOS PEDIMENTOS', 35
	FROM         dbo.PEDIMP RIGHT OUTER JOIN
	                      dbo.IMPEXCELRELPEDIMPFACT ON RIGHT(dbo.PEDIMP.PI_FOLIO,7) = dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	WHERE     (dbo.PEDIMP.PI_FOLIO IS NULL) 



if exists (SELECT     IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	FROM         FACTIMP INNER JOIN
	                      RELTFACTCLAPED INNER JOIN
	                      IMPEXCELRELPEDIMPFACT INNER JOIN
	                      PEDIMP ON RIGHT(IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 7) = PEDIMP.PI_FOLIO ON RELTFACTCLAPED.CP_CODIGO = PEDIMP.CP_CODIGO ON 
	                      FACTIMP.FI_FOLIO = IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	WHERE     (NOT (FACTIMP.TF_CODIGO IN
	                          (SELECT     TF_CODIGO
	                            FROM          RELTFACTCLAPED))))

	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR LA RELACION CON LA FACTURA CON FOLIO : ' +IMPEXCELRELPEDIMPFACT.FOLIOFACTURA+'SU TIPO DE FACTURA NO EXISTE EN LA RELACION CLAVE PEDIMENTO-TIPO FACTURA', 35
	FROM         FACTIMP INNER JOIN
	                      RELTFACTCLAPED INNER JOIN
	                      IMPEXCELRELPEDIMPFACT INNER JOIN
	                      PEDIMP ON RIGHT(IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 7) = PEDIMP.PI_FOLIO ON RELTFACTCLAPED.CP_CODIGO = PEDIMP.CP_CODIGO ON 
	                      FACTIMP.FI_FOLIO = IMPEXCELRELPEDIMPFACT.FOLIOFACTURA
	WHERE     (NOT FACTIMP.TF_CODIGO IN
	                          (SELECT     TF_CODIGO
	                            FROM          RELTFACTCLAPED))


/* se actualiza el pi_codigo o el pi_rectifica de las facturas */

	UPDATE dbo.FACTIMP
	SET     dbo.FACTIMP.PI_CODIGO= dbo.PEDIMP.PI_CODIGO
	FROM         dbo.IMPEXCELRELPEDIMPFACT INNER JOIN
	                      dbo.PEDIMP ON RIGHT(dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 7) = dbo.PEDIMP.PI_FOLIO INNER JOIN
	                      dbo.AGENCIAPATENTE ON LEFT(dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 4) = dbo.AGENCIAPATENTE.AGT_PATENTE AND 
	                      dbo.PEDIMP.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO INNER JOIN
	                      dbo.FACTIMP ON dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA = dbo.FACTIMP.FI_FOLIO LEFT OUTER JOIN
	                      dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
	WHERE     (dbo.IMPEXCELRELPEDIMPFACT.TIPOMOVIMIENTO = 'E') AND (dbo.CONFIGURACLAVEPED.CCP_TIPO <> 'RE')

	UPDATE dbo.FACTIMP
	SET     dbo.FACTIMP.PI_RECTIFICA= dbo.PEDIMP.PI_CODIGO
	FROM         dbo.IMPEXCELRELPEDIMPFACT INNER JOIN
	                      dbo.PEDIMP ON RIGHT(dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 7) = dbo.PEDIMP.PI_FOLIO INNER JOIN
	                      dbo.AGENCIAPATENTE ON LEFT(dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 4) = dbo.AGENCIAPATENTE.AGT_PATENTE AND 
	                      dbo.PEDIMP.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO INNER JOIN
	                      dbo.FACTIMP ON dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA = dbo.FACTIMP.FI_FOLIO LEFT OUTER JOIN
	                      dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
	WHERE     (dbo.IMPEXCELRELPEDIMPFACT.TIPOMOVIMIENTO = 'E') AND (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'RE')

	UPDATE dbo.FACTEXP
	SET     dbo.FACTEXP.PI_CODIGO= dbo.PEDIMP.PI_CODIGO
	FROM         dbo.IMPEXCELRELPEDIMPFACT INNER JOIN
	                      dbo.PEDIMP ON RIGHT(dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 7) = dbo.PEDIMP.PI_FOLIO INNER JOIN
	                      dbo.AGENCIAPATENTE ON LEFT(dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 4) = dbo.AGENCIAPATENTE.AGT_PATENTE AND 
	                      dbo.PEDIMP.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO INNER JOIN
	                      dbo.FACTEXP ON dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA = dbo.FACTEXP.FE_FOLIO LEFT OUTER JOIN
	                      dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
	WHERE     (dbo.IMPEXCELRELPEDIMPFACT.TIPOMOVIMIENTO = 'S') AND (dbo.CONFIGURACLAVEPED.CCP_TIPO <> 'RE')

	UPDATE dbo.FACTEXP
	SET     dbo.FACTEXP.PI_RECTIFICA= dbo.PEDIMP.PI_CODIGO
	FROM         dbo.IMPEXCELRELPEDIMPFACT INNER JOIN
	                      dbo.PEDIMP ON RIGHT(dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 7) = dbo.PEDIMP.PI_FOLIO INNER JOIN
	                      dbo.AGENCIAPATENTE ON LEFT(dbo.IMPEXCELRELPEDIMPFACT.NOPEDIMENTO, 4) = dbo.AGENCIAPATENTE.AGT_PATENTE AND 
	                      dbo.PEDIMP.AGT_CODIGO = dbo.AGENCIAPATENTE.AGT_CODIGO INNER JOIN
	                      dbo.FACTEXP ON dbo.IMPEXCELRELPEDIMPFACT.FOLIOFACTURA = dbo.FACTEXP.FE_FOLIO LEFT OUTER JOIN
	                      dbo.CONFIGURACLAVEPED ON dbo.PEDIMP.CP_CODIGO = dbo.CONFIGURACLAVEPED.CP_CODIGO
	WHERE     (dbo.IMPEXCELRELPEDIMPFACT.TIPOMOVIMIENTO = 'S') AND (dbo.CONFIGURACLAVEPED.CCP_TIPO = 'RE')


/* se ejecutan los procedimientos para llenar el detalle */

DECLARE CUR_IMPEXCELREL CURSOR FOR
SELECT NOPEDIMENTO,TIPOMOVIMIENTO FROM IMPEXCELRELPEDIMPFACT
WHERE FOLIOFACTURA IS NOT NULL AND NOPEDIMENTO IS NOT NULL  
GROUP BY NOPEDIMENTO,TIPOMOVIMIENTO
OPEN CUR_IMPEXCELREL
FETCH NEXT FROM CUR_IMPEXCELREL INTO @NOPEDIMENTO, @TIPOMOVIMIENTO
WHILE (@@FETCH_STATUS = 0) 
BEGIN

	SELECT @PICODIGO= PI_CODIGO FROM PEDIMP WHERE PI_FOLIO = RIGHT(RTRIM(@NOPEDIMENTO),7)
		AND AGT_CODIGO IN (SELECT AGT_CODIGO FROM AGENCIAPATENTE WHERE AGT_PATENTE = LEFT(LTRIM(@NOPEDIMENTO),4))


	exec sp_fillpedimento @picodigo, 1, @TIPOMOVIMIENTO



	
	FETCH NEXT FROM CUR_IMPEXCELREL INTO @NOPEDIMENTO, @TIPOMOVIMIENTO
END
CLOSE CUR_IMPEXCELREL
DEALLOCATE CUR_IMPEXCELREL



























GO
