SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


/* inventario de materia prima, partes y componentes para declaracion anual prosec*/
CREATE PROCEDURE [dbo].[SP_INVENTARIOFECHAPROSEC] (@fecha datetime, @DAP_CODIGO INT) with encryption as
SET NOCOUNT ON 
declare @PID_SALDOGEN decimal(38,6), @VALOR decimal(38,6), @valor2 decimal(38,6), @owner varchar(150)

if not exists (select * from dbo.sysobjects where name='#INVENTARIOPPS')
CREATE TABLE [dbo].[#INVENTARIOPPS]
		(PID_SALDOGEN decimal(38,6),
		VALOR decimal(38,6))


	insert into #INVENTARIOPPS (PID_SALDOGEN,	VALOR)
	/* se suma el saldo de los pedimentos */
	SELECT     SUM(dbo.PIDESCARGA.PID_SALDOGEN) AS PID_SALDOGEN, SUM(dbo.PIDESCARGA.PID_SALDOGEN*dbo.PEDIMPDET.PID_COS_UNIGEN*dbo.VPEDIMP.PI_TIP_CAM) AS VALOR
	FROM         dbo.AGENCIAPATENTE RIGHT OUTER JOIN
	                      dbo.VPEDIMP ON dbo.AGENCIAPATENTE.AGT_CODIGO = dbo.VPEDIMP.AGT_CODIGO RIGHT OUTER JOIN
	                      dbo.SPI RIGHT OUTER JOIN
	                      dbo.PEDIMPDET ON dbo.SPI.SPI_CODIGO = dbo.PEDIMPDET.SPI_CODIGO LEFT OUTER JOIN
	                      dbo.SECTOR ON dbo.PEDIMPDET.PID_SEC_IMP = dbo.SECTOR.SE_CODIGO ON 
	                      dbo.VPEDIMP.PI_CODIGO = dbo.PEDIMPDET.PI_CODIGO LEFT OUTER JOIN
	                      dbo.ARANCEL ON dbo.PEDIMPDET.AR_IMPMX = dbo.ARANCEL.AR_CODIGO LEFT OUTER JOIN
	                      dbo.MAESTRO ON dbo.PEDIMPDET.MA_GENERICO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_1 ON dbo.PEDIMPDET.ME_CODIGO = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_2 ON dbo.PEDIMPDET.ME_GENERICO = MEDIDA_2.ME_CODIGO   LEFT OUTER JOIN
		      dbo.PIDESCARGA ON dbo.PEDIMPDET.PID_INDICED = dbo.PIDESCARGA.PID_INDICED
	WHERE     (dbo.VPEDIMP.PI_ESTATUS <> 'R')and dbo.PEDIMPDET.TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE
			CFT_TIPO IN ('R', 'E', 'L', 'M', 'O', 'T')) AND dbo.VPEDIMP.PI_FEC_ENT<=@fecha 
			and dbo.PEDIMPDET.PID_DEF_TIP='S'
	GROUP BY dbo.AGENCIAPATENTE.AG_PATENTE + '-' + dbo.VPEDIMP.PI_FOLIO, dbo.VPEDIMP.PI_FEC_PAG, MEDIDA_2.ME_CORTO, MEDIDA_1.ME_CORTO, dbo.ARANCEL.AR_FRACCION, 
	                      dbo.PEDIMPDET.PID_POR_DEF, dbo.PEDIMPDET.PID_DEF_TIP, dbo.SECTOR.SE_CLAVE, dbo.SPI.SPI_CLAVE, 
	                      dbo.PEDIMPDET.MA_CODIGO, dbo.PEDIMPDET.TI_CODIGO, dbo.PEDIMPDET.PID_NOPARTE, dbo.VPEDIMP.PI_FEC_ENT
	HAVING      (SUM(dbo.PIDESCARGA.PID_SALDOGEN) > 0) AND (dbo.AGENCIAPATENTE.AG_PATENTE + '-' + dbo.VPEDIMP.PI_FOLIO IS NOT NULL)
	UNION
	/* se suma la cantidad que ha sido descargada en base a la fecha de la factura de exportacion */
	SELECT   SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC) AS PID_SALDOGEN,  SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC*dbo.PEDIMPDET.PID_COS_UNIGEN*dbo.VPEDIMP.PI_TIP_CAM) AS VALOR
	FROM         dbo.SECTOR RIGHT OUTER JOIN
	                      dbo.VINVENTARIOKARSUM RIGHT OUTER JOIN
	                      dbo.PEDIMPDET ON dbo.VINVENTARIOKARSUM.KAP_INDICED_PED = dbo.PEDIMPDET.PID_INDICED LEFT OUTER JOIN
	                      dbo.SPI ON dbo.PEDIMPDET.SPI_CODIGO = dbo.SPI.SPI_CODIGO ON dbo.SECTOR.SE_CODIGO = dbo.PEDIMPDET.PID_SEC_IMP LEFT OUTER JOIN
	                      dbo.AGENCIAPATENTE RIGHT OUTER JOIN
	                      dbo.VPEDIMP ON dbo.AGENCIAPATENTE.AGT_CODIGO = dbo.VPEDIMP.AGT_CODIGO ON 
	                      dbo.PEDIMPDET.PI_CODIGO = dbo.VPEDIMP.PI_CODIGO LEFT OUTER JOIN
	                      dbo.ARANCEL ON dbo.PEDIMPDET.AR_IMPMX = dbo.ARANCEL.AR_CODIGO LEFT OUTER JOIN
	                      dbo.MAESTRO ON dbo.PEDIMPDET.MA_GENERICO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_1 ON dbo.PEDIMPDET.ME_CODIGO = MEDIDA_1.ME_CODIGO LEFT OUTER JOIN
	                      dbo.MEDIDA MEDIDA_2 ON dbo.PEDIMPDET.ME_GENERICO = MEDIDA_2.ME_CODIGO
	WHERE     (dbo.VPEDIMP.PI_ESTATUS <> 'R')and dbo.PEDIMPDET.TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE
			CFT_TIPO IN ('R', 'E', 'L', 'M', 'O', 'T'))  AND dbo.VINVENTARIOKARSUM.FE_FECHA<=@fecha
			and dbo.PEDIMPDET.PID_DEF_TIP='S'
	GROUP BY dbo.AGENCIAPATENTE.AG_PATENTE + '-' + dbo.VPEDIMP.PI_FOLIO, MEDIDA_2.ME_CORTO, MEDIDA_1.ME_CORTO, dbo.ARANCEL.AR_FRACCION, 
	                      dbo.PEDIMPDET.PID_POR_DEF, dbo.PEDIMPDET.PID_DEF_TIP, dbo.SECTOR.SE_CLAVE, dbo.SPI.SPI_CLAVE, 
	                      dbo.PEDIMPDET.MA_CODIGO, dbo.PEDIMPDET.TI_CODIGO, dbo.PEDIMPDET.PID_NOPARTE, dbo.VINVENTARIOKARSUM.FE_FECHA, dbo.VPEDIMP.PI_FEC_PAG
	HAVING      (dbo.AGENCIAPATENTE.AG_PATENTE + '-' + dbo.VPEDIMP.PI_FOLIO IS NOT NULL) AND (SUM(dbo.VINVENTARIOKARSUM.KAP_CANTDESC) > 0)



	select @valor2= sum(VALOR)
	from #INVENTARIOPPS


	update 	DECANUALPPS
	SET DAP_INVENTARIOCOMP=isnull(@valor2,0)
	where dap_codigo=@DAP_CODIGO



	exec sp_droptable '#INVENTARIOPPS'
GO
