SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_FILL_TempBOM_DESCALM1] (@END_INDICED INT, @BST_PT INT, @BST_HIJO INT, @BST_ENTRAVIGOR DATETIME, @BST_PERINI DATETIME, @END_CANT decimal(38,6), @CODIGOFACTURA INT, @CF_USATIPOADQUISICION char(1), @BST_INCORPOR1 decimal(38,6), @CF_NIVELES int, @nivel int,  @ALMORIGEN INT, @ALMDESTINO INT)   as


declare @BST_HIJO1 int, @BST_INCORPOR decimal(38,6), @BST_DISCH char(1), @TI_CODIGO char(1), @ME_CODIGO int, @FACTCONVALM decimal(38,6), 
    @BST_PERINI1 datetime, @BST_PERFIN datetime, @ME_ALM int, @BST_TRANS char(1), @MA_TIP_ENS char(1), @nivelr int, @bst_perini2 datetime, @BST_TIPODESC VARCHAR(5), @incorporacionfinal decimal(38,6)

/*DECLARE @CursorVar CURSOR

SET @CursorVar = CURSOR SCROLL DYNAMIC FOR
SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_INCORPOR) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONVALM, 
                      dbo.BOM_STRUCT.ME_ALM, dbo.BOM_STRUCT.BST_TRANS, 
                      dbo.BOM_STRUCT.BST_TIP_ENS, 'N' AS BST_TIPODESC
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
                      dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, 
                      dbo.BOM_STRUCT.BST_TRANS, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
                      dbo.BOM_STRUCT.BST_INCORPOR
HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
AND SUM(dbo.BOM_STRUCT.BST_INCORPOR) >0
UNION
SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_DESP) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONVALM, 
                      dbo.BOM_STRUCT.ME_ALM, dbo.BOM_STRUCT.BST_TRANS, 
                      dbo.BOM_STRUCT.BST_TIP_ENS, 'D' AS BST_TIPODESC
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
                      dbo.BOM_STRUCT.FACTCONVALM, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_ALM, 
                      dbo.BOM_STRUCT.BST_TRANS, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
                      dbo.BOM_STRUCT.BST_INCORPOR
HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
AND SUM(dbo.BOM_STRUCT.BST_DESP) >0
UNION
SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_MERMA) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONVALM, dbo.BOM_STRUCT.BST_PERINI, 
                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_ALM, dbo.BOM_STRUCT.BST_TRANS, 
                      dbo.BOM_STRUCT.BST_TIP_ENS, 'M' AS BST_TIPODESC
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
                      dbo.BOM_STRUCT.FACTCONVALM, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_ALM, 
                      dbo.BOM_STRUCT.BST_TRANS, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
                      dbo.BOM_STRUCT.BST_INCORPOR
HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
AND SUM(dbo.BOM_STRUCT.BST_MERMA) >0

 OPEN @CursorVar
  FETCH NEXT FROM @CursorVar
	INTO @BST_HIJO1, @BST_INCORPOR, @BST_DISCH, @TI_CODIGO, @ME_CODIGO, 
	@FACTCONVALM, @BST_PERINI1, @BST_PERFIN, @ME_ALM, @BST_TRANS, @MA_TIP_ENS, @BST_TIPODESC

  WHILE (@@fetch_status = 0) 
  BEGIN  

	set @incorporacionfinal=@BST_INCORPOR* @BST_INCORPOR1

	SET @nivelr=@nivel+1

	if @TI_CODIGO<>'P' and @TI_CODIGO<>'S'

	begin
		if  @MA_TIP_ENS ='C'  
		begin

			--print 'entra aqui cc'
			insert into TempBOM_DESCALM(END_INDICED, BST_PT, BST_HIJO, BST_INCORPOR, 
			    BST_DISCH, TI_CODIGO, ME_CODIGO, FACTCONVALM, ME_ALM, 
			    BST_TRANS, MA_TIP_ENS, END_CANT, EN_CODIGO, BST_NIVEL, BST_TIPODESC, 
			    ALM_ORIGEN, ALM_DESTINO)
			values
			(@END_INDICED, @BST_PT, @BST_HIJO1, @incorporacionfinal, @BST_DISCH, @TI_CODIGO, @ME_CODIGO, 
			@FACTCONVALM, @ME_ALM, @BST_TRANS, @MA_TIP_ENS, @END_CANT, @CODIGOFACTURA, 
			'B'+convert(varchar(5),@nivelr), @BST_TIPODESC, @ALMORIGEN, @ALMDESTINO)
		end

	end
	else
	begin

		if @CF_USATIPOADQUISICION='S'
		begin		

			if @MA_TIP_ENS='F' 
			begin
				exec  SP_FILL_TempBOM_DESCALM1 @END_INDICED, @BST_PT, @BST_HIJO1, 
				@END_CANT, @CODIGOFACTURA, @CF_USATIPOADQUISICION, @incorporacionfinal, @CF_NIVELES, @nivelr, @ALMORIGEN, @ALMDESTINO
			end

			if @MA_TIP_ENS='C' or @MA_TIP_ENS='A' or @MA_TIP_ENS='E' or @MA_TIP_ENS='O' 

			begin
				insert into TempBOM_DESCALM(END_INDICED, BST_PT, BST_HIJO, BST_INCORPOR, 
				    BST_DISCH, TI_CODIGO, ME_CODIGO, FACTCONVALM, ME_ALM, 
				    BST_TRANS, MA_TIP_ENS, END_CANT, EN_CODIGO, BST_NIVEL, BST_TIPODESC, 
				ALM_ORIGEN, ALM_DESTINO)
				values
				(@END_INDICED, @BST_PT, @BST_HIJO1, @incorporacionfinal, @BST_DISCH, @TI_CODIGO, @ME_CODIGO, 
				@FACTCONVALM, @ME_ALM, @BST_TRANS, 
				@MA_TIP_ENS, @END_CANT, @CODIGOFACTURA, 'B'+convert(varchar(5),@nivelr), @BST_TIPODESC, @ALMORIGEN, @ALMDESTINO)

			end

		end
		else

		begin

			exec  SP_FILL_TempBOM_DESCALM1 @END_INDICED, @BST_PT, @BST_HIJO1, @BST_ENTRAVIGOR, 
			@BST_PERINI1, @END_CANT, @CODIGOFACTURA, @CF_USATIPOADQUISICION, @incorporacionfinal, @CF_NIVELES, @nivelr, @ALMORIGEN, @ALMDESTINO
		end

	end

	FETCH NEXT FROM @CursorVar INTO @BST_HIJO1, @BST_INCORPOR, @BST_DISCH, @TI_CODIGO, 			
	@ME_CODIGO, @FACTCONVALM, @BST_PERINI1, @BST_PERFIN, @ME_ALM, @BST_TRANS, 
	@MA_TIP_ENS, @BST_TIPODESC

END
	CLOSE @CursorVar
	DEALLOCATE @CursorVar














*/













GO
