SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_COPIA_REG_PCKLIST] (@FUENTE INT,@DESTINO INT)  as

SET NOCOUNT ON 
declare @PLD_indiced int, @PLC_INDICEC int

	exec sp_droptable 'PckListDetTemp'

CREATE TABLE [dbo].[PckListDetTemp] (
	[PLD_INDICED] [int] IDENTITY (1, 1) NOT NULL ,
	[PLD_INDICEDant] [int] NOT NULL ,
	[PL_CODIGO] [int] NOT NULL ,
	[PLD_CANT_ST] decimal(38,6) NULL ,
	[PLD_COS_UNI] decimal(38,6) NULL ,
	[PLD_NOMBRE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLD_NAME] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLD_NOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PckListDetTemp_PLD_NOPARTE] DEFAULT (''),
	[OR_CODIGO] [int] NULL ,
	[PLD_ORD_COMP] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ORD_INDICED] [int] NULL ,
	[PLD_NOORDEN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLD_ENVIO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLD_SALDO] decimal(38,6) NULL ,
	[PLD_PES_UNI] decimal(38,6) NULL ,
	[PLD_PES_NET] decimal(38,6) NULL ,
	[PLD_PES_BRU] decimal(38,6) NULL ,
	[PLD_PES_UNILB] decimal(38,6) NULL ,
	[PLD_PES_NETLB] decimal(38,6) NULL ,
	[PLD_PES_BRULB] decimal(38,6) NULL ,
	[PLD_COS_TOT] decimal(38,6) NULL ,
	[PLD_FEC_ENT] [datetime] NULL ,
	[PLD_NUM_ENT] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLD_SEC_IMP] [smallint] NULL ,
	[PLD_DEF_TIP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PckListDetTemp_PLD_DEF_TIP] DEFAULT ('G'),
	[PLD_POR_DEF] decimal(38,6) NOT NULL CONSTRAINT [DF_PckListDetTemp_PLD_POR_DEF] DEFAULT ((-1)),
	[PLD_ENUSO] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PckListDetTemp_PLD_ENUSO] DEFAULT ('N'),
	[PLD_FEC_EST] [smalldatetime] NULL ,
	[PLD_FECHA] [smalldatetime] NULL ,
	[MV_CODIGO] [int] NULL ,
	[MA_CODIGO] [int] NOT NULL ,
	[PA_CODIGO] [int] NULL ,
	[AR_IMPMX] [int] NULL ,
	[AR_EXPFO] [int] NULL ,
	[MA_GENERICO] [int] NOT NULL CONSTRAINT [DF_PckListDetTemp_MA_GENERICO] DEFAULT (0),
	[ME_CODIGO] [int] NULL ,
	[ME_ARIMPMX] [int] NULL ,
	[EQ_IMPMX] decimal(28,14) NOT NULL CONSTRAINT [DF_PckListDetTemp_EQ_IMPMX] DEFAULT (1),
	[EQ_EXPFO] decimal(28,14) NOT NULL CONSTRAINT [DF_PckListDetTemp_EQ_EXPFO] DEFAULT (1),
	[EQ_EXPFO2] decimal(28,14) NOT NULL CONSTRAINT [DF_PckListDetTemp_EQ_EXPFO2] DEFAULT (1),
	[EQ_GEN] decimal(28,14) NOT NULL CONSTRAINT [DF_PckListDetTemp_EQ_GEN] DEFAULT (1),
	[PLD_RATEEXPFO] decimal(38,6) NULL ,
	[TI_CODIGO] [int] NOT NULL ,
	[ME_GEN] [int] NULL ,
	[MA_EMPAQUE] [int] NULL ,
	[PLD_CANTEMP] decimal(38,6) NULL ,
	[PLD_FEC_ENV] [datetime] NULL ,
	[SPI_CODIGO] [smallint] NULL ,
	[TCO_CODIGO] [smallint] NULL ,
	[PLD_NOPARTEAUX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	CONSTRAINT [PK_PckListDetTemp] PRIMARY KEY  NONCLUSTERED 
	(
		[PLD_INDICED],
		[PL_CODIGO]
	)  ON [PRIMARY] 
) ON [PRIMARY]

		select @PLD_INDICED= isnull(max(PLD_indiced),0)+1 from PckListDet

		DBCC CHECKIDENT (PckListDetTEMP, RESEED, @PLD_INDICED) WITH NO_INFOMSGS

	exec sp_droptable 'PckListContTemp'

CREATE TABLE [dbo].[PCKLISTCONTTemp] (
	[PLC_INDICEC] [int] IDENTITY (1, 1) NOT NULL ,
	[PLD_INDICED] [int] NOT NULL ,
	[PL_CODIGO] [int] NOT NULL ,
	[PLC_MARCA] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLC_MODELO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLC_SERIE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PLC_EQUIPADOCON] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PCKLISTCONTTemp_PLC_EQUIPADOCON] DEFAULT (''),
	[PLC_ENUSO] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PCKLISTCONTTemp_PLC_ENUSO] DEFAULT ('N'),
	CONSTRAINT [PK_PCKLISTCONTTemp] PRIMARY KEY  NONCLUSTERED 
	(
		[PLC_INDICEC],
		[PLD_INDICED],
		[PL_CODIGO]
	)  ON [PRIMARY] 
) ON [PRIMARY]



		select @PLC_INDICEC= isnull(max(PLC_indicec),0)+1 from PckListCont

		DBCC CHECKIDENT (PckListContTemp, RESEED, @PLC_INDICEC) WITH NO_INFOMSGS


-- insercion a tabla temporal
	insert into PckListDetTemp(PL_CODIGO, PLD_INDICEDANT, PLD_CANT_ST, PLD_COS_UNI, PLD_NOMBRE, PLD_NAME, PLD_NOPARTE, OR_CODIGO, PLD_ORD_COMP, 
	                      ORD_INDICED, PLD_NOORDEN, PLD_ENVIO, PLD_SALDO, PLD_PES_UNI, PLD_PES_NET, PLD_PES_BRU, PLD_PES_UNILB, PLD_PES_NETLB, 
	                      PLD_PES_BRULB, PLD_COS_TOT, PLD_FEC_ENT, PLD_NUM_ENT, PLD_SEC_IMP, PLD_DEF_TIP, PLD_POR_DEF, PLD_ENUSO, PLD_FEC_EST, 
	                      PLD_FECHA, MV_CODIGO, MA_CODIGO, PA_CODIGO, AR_IMPMX, AR_EXPFO, MA_GENERICO, ME_CODIGO, ME_ARIMPMX, EQ_IMPMX, EQ_EXPFO, EQ_EXPFO2,
	                      EQ_GEN, PLD_RATEEXPFO, TI_CODIGO, ME_GEN, MA_EMPAQUE, PLD_CANTEMP, PLD_FEC_ENV, SPI_CODIGO, TCO_CODIGO, 
	                      PLD_NOPARTEAUX)
	

	SELECT     @DESTINO, PLD_INDICED, PLD_CANT_ST, PLD_COS_UNI, PLD_NOMBRE, PLD_NAME, PLD_NOPARTE, OR_CODIGO, PLD_ORD_COMP, 
	                      ORD_INDICED, PLD_NOORDEN, PLD_ENVIO, PLD_CANT_ST, PLD_PES_UNI, PLD_PES_NET, PLD_PES_BRU, PLD_PES_UNILB, PLD_PES_NETLB, 
	                      PLD_PES_BRULB, PLD_COS_TOT, PLD_FEC_ENT, PLD_NUM_ENT, PLD_SEC_IMP, PLD_DEF_TIP, PLD_POR_DEF, PLD_ENUSO, PLD_FEC_EST, 
	                      PLD_FECHA, MV_CODIGO, MA_CODIGO, PA_CODIGO, AR_IMPMX, AR_EXPFO, MA_GENERICO, ME_CODIGO, ME_ARIMPMX, EQ_IMPMX, EQ_EXPFO, EQ_EXPFO2,
	                      EQ_GEN, PLD_RATEEXPFO, TI_CODIGO, ME_GEN, MA_EMPAQUE, PLD_CANTEMP, PLD_FEC_ENV, SPI_CODIGO, TCO_CODIGO, 
	                      PLD_NOPARTEAUX
	FROM         PCKLISTDET WHERE PL_CODIGO=@FUENTE
	

-- insercion en detalle
	insert into PckListDet(PL_CODIGO, PLD_INDICED, PLD_CANT_ST, PLD_COS_UNI, PLD_NOMBRE, PLD_NAME, PLD_NOPARTE, OR_CODIGO, PLD_ORD_COMP, 
	                      ORD_INDICED, PLD_NOORDEN, PLD_ENVIO, PLD_SALDO, PLD_PES_UNI, PLD_PES_NET, PLD_PES_BRU, PLD_PES_UNILB, PLD_PES_NETLB, 
	                      PLD_PES_BRULB, PLD_COS_TOT, PLD_FEC_ENT, PLD_NUM_ENT, PLD_SEC_IMP, PLD_DEF_TIP, PLD_POR_DEF, PLD_ENUSO, PLD_FEC_EST, 
	                      PLD_FECHA, MV_CODIGO, MA_CODIGO, PA_CODIGO, AR_IMPMX, AR_EXPFO, MA_GENERICO, ME_CODIGO, ME_ARIMPMX, EQ_IMPMX, EQ_EXPFO, EQ_EXPFO2,
	                      EQ_GEN, PLD_RATEEXPFO, TI_CODIGO, ME_GEN, MA_EMPAQUE, PLD_CANTEMP, PLD_FEC_ENV, SPI_CODIGO, TCO_CODIGO, 
	                      PLD_NOPARTEAUX)
	SELECT    PL_CODIGO, PLD_INDICED, PLD_CANT_ST, PLD_COS_UNI, PLD_NOMBRE, PLD_NAME, PLD_NOPARTE, OR_CODIGO, PLD_ORD_COMP, 
	                      ORD_INDICED, PLD_NOORDEN, PLD_ENVIO, PLD_SALDO, PLD_PES_UNI, PLD_PES_NET, PLD_PES_BRU, PLD_PES_UNILB, PLD_PES_NETLB, 
	                      PLD_PES_BRULB, PLD_COS_TOT, PLD_FEC_ENT, PLD_NUM_ENT, PLD_SEC_IMP, PLD_DEF_TIP, PLD_POR_DEF, PLD_ENUSO, PLD_FEC_EST, 
	                      PLD_FECHA, MV_CODIGO, MA_CODIGO, PA_CODIGO, AR_IMPMX, AR_EXPFO, MA_GENERICO, ME_CODIGO, ME_ARIMPMX, EQ_IMPMX, EQ_EXPFO, EQ_EXPFO2,
	                      EQ_GEN, PLD_RATEEXPFO, TI_CODIGO, ME_GEN, MA_EMPAQUE, PLD_CANTEMP, PLD_FEC_ENV, SPI_CODIGO, TCO_CODIGO, 
	                      PLD_NOPARTEAUX
	FROM         PckListDetTemp


/*	update PckList
	set PL_cuentadet=(select isnull(count(PckListDet.PL_codigo),0) from PckListDet where PckListDet.PL_codigo =PckList.PL_codigo)
	where PL_codigo =@DESTINO
*/

	INSERT INTO PCKLISTCONTTemp(PLD_INDICED, PL_CODIGO, PLC_MARCA, PLC_MODELO, PLC_SERIE,PLC_EQUIPADOCON)

	SELECT PckListDetTemp.PLD_INDICED, PckListDetTemp.PL_CODIGO, PLC_MARCA, PLC_MODELO, PLC_SERIE, PLC_EQUIPADOCON 
	FROM PCKLISTCONT INNER JOIN PckListDetTemp ON PCKLISTCONT.PLD_INDICED=PckListDetTemp.PLD_INDICEDant


	INSERT INTO PCKLISTCONT(PLD_INDICED, PLC_INDICEC, PL_CODIGO, PLC_MARCA, PLC_MODELO, PLC_SERIE,PLC_EQUIPADOCON)
	SELECT PLD_INDICED, PLC_INDICEC, PL_CODIGO, PLC_MARCA, PLC_MODELO, PLC_SERIE,PLC_EQUIPADOCON FROM PCKLISTCONTTemp

		select @PLD_INDICED= max(PLD_indiced) from PckListDet

		update consecutivo
		set cv_codigo =  isnull(@PLD_indiced,0) + 1
		where cv_tipo = 'PLD'

	exec sp_droptable 'PckListDetTemp'

		select @PLC_INDICEC= max(PLC_indicec) from PckListCont

		update consecutivo
		set cv_codigo =  isnull(@PLC_indicec,0) + 1
		where cv_tipo = 'PLC'


	exec sp_droptable 'PckListContTemp'





GO
