SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO























CREATE PROCEDURE [dbo].[SP_ACTUALIZAEQBOM]   as

		UPDATE BOM_STRUCT
	SET     BOM_STRUCT.FACTCONV= MAESTRO.EQ_GEN
	FROM         MAESTRO MAESTRO_1 INNER JOIN
	                      MAESTRO ON MAESTRO_1.MA_CODIGO = MAESTRO.MA_GENERICO INNER JOIN
	                      BOM_STRUCT ON MAESTRO.MA_CODIGO = BOM_STRUCT.BST_HIJO AND MAESTRO.ME_COM = BOM_STRUCT.ME_CODIGO AND 
	                      MAESTRO_1.ME_COM = BOM_STRUCT.ME_GEN AND MAESTRO.EQ_GEN <> BOM_STRUCT.FACTCONV
	WHERE BOM_STRUCT.FACTCONV<> MAESTRO.EQ_GEN
	
	
	UPDATE BOM_STRUCT
	SET     FACTCONV= MAESTRO.MA_PESO_KG
	FROM    BOM_STRUCT INNER JOIN MAESTRO 
	ON MAESTRO.MA_CODIGO = BOM_STRUCT.BST_HIJO AND MAESTRO.ME_COM = BOM_STRUCT.ME_CODIGO
	WHERE ME_GEN IN (SELECT ME_KILOGRAMOS from configuracion) 
	AND MAESTRO.MA_PESO_KG>0 AND FACTCONV<> MAESTRO.MA_PESO_KG
	
	
	UPDATE BOM_STRUCT
	SET     FACTCONV= MAESTRO.MA_PESO_LB
	FROM    BOM_STRUCT INNER JOIN MAESTRO 
	ON MAESTRO.MA_CODIGO = BOM_STRUCT.BST_HIJO AND MAESTRO.ME_COM = BOM_STRUCT.ME_CODIGO
	WHERE ME_GEN IN (SELECT ME_CODIGO FROM MEDIDA WHERE ME_CORTO='LB') 
	AND MAESTRO.MA_PESO_LB>0 AND FACTCONV<> MAESTRO.MA_PESO_LB

	
	update BOM_STRUCT
	SET     BOM_STRUCT.FACTCONV= EQUIVALE.EQ_CANT
	FROM         BOM_STRUCT INNER JOIN
	                      EQUIVALE ON BOM_STRUCT.ME_CODIGO = EQUIVALE.ME_CODIGO1 
			AND BOM_STRUCT.ME_GEN = EQUIVALE.ME_CODIGO2
	WHERE BOM_STRUCT.FACTCONV<> EQUIVALE.EQ_CANT





GO
