SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_TEMPIMPORT141] AS
DECLARE @Col_2 varchar(8000),@Col_3 varchar(8000),@Col_4 varchar(8000),@Col_5 varchar(8000),@Col_6 varchar(8000),@Col_7 varchar(8000),@Col_8 varchar(8000),@MAESTROCOST#MA_COSTO float,@MAESTRO#MA_INV_GEN char,@MAESTRO#MA_NOPARTEAUX varchar(8000),@MAESTROCOST#TCO_CODIGO smallint,@MAESTROCOST#SPI_CODIGO int,@MAESTROCOST#MA_PERINI datetime,@IMPORTTEMPBOM#BST_PERFIN datetime,@IMPORTTEMPBOM#BST_TRANS char,@IMPORTTEMPBOM#BST_SEC smallint,@IMPORTTEMPBOM#BST_PERINI datetime,@IMPORTTEMPBOM#BST_NOPARTEAUX varchar(8000),@IMPORTTEMPBOM#BSU_NOPARTEAUX varchar(8000),@IMPORTTEMPBOM#BSU_NOPARTE varchar(8000),@MAESTRO#MA_NOPARTE varchar(8000),@IMPORTTEMPBOM#BST_NOPARTE varchar(8000),@MAESTROCOST#MA_GRAV_MP float,@IMPORTTEMPBOM#BST_INCORPOR float,@MAESTROCOST#MA_NG_MP float,@MAESTROCOST#MA_GRAV_EMP float,@MAESTROCOST#MA_NG_EMP float,@MAESTROCOST#MA_GRAV_ADD float,@MAESTROCOST#MA_GRAV_GI_MX float,@MAESTROCOST#MA_GRAV_MO float,@MAESTRODEF#MA_DEFNO1 int
DECLARE @ACTUALIZA bit,@ANEXA bit,@CONSECUTIVO int,@CONSDET int,@CONSANEX int,@CONSCONT int
DECLARE @CAMPOSMASTER varchar(255),@temp_str varchar(20)
SELECT @ACTUALIZA=1
SELECT @ANEXA=0
DELETE FROM REGISTROSIMPORTADOS
-- Variables para campos de caratula
-- Variables para campos de detalle
DECLARE CUR_TEMPIMPORT141 CURSOR FOR
SELECT MAX(Col_2),MAX(Col_3),MAX(Col_4),MAX(Col_5),MAX(Col_6),MAX(Col_7),MAX(Col_8),MAESTRO0#MA_INV_GEN,MAESTRO0#MA_NOPARTEAUX,MAESTRO0#MA_NOPARTE,MAX(MAESTRODEF0#MA_DEFNO1) FROM TEMPIMPORT141 GROUP BY MAESTRO0#MA_INV_GEN,MAESTRO0#MA_NOPARTEAUX,MAESTRO0#MA_NOPARTE
OPEN CUR_TEMPIMPORT141
FETCH NEXT FROM CUR_TEMPIMPORT141 INTO @Col_2 ,@Col_3 ,@Col_4 ,@Col_5 ,@Col_6 ,@Col_7 ,@Col_8 ,@MAESTRO#MA_INV_GEN ,@MAESTRO#MA_NOPARTEAUX ,@MAESTRO#MA_NOPARTE ,@MAESTRODEF#MA_DEFNO1 
WHILE (@@FETCH_STATUS = 0)
BEGIN
   IF EXISTS(SELECT MA_CODIGO FROM MAESTRO WHERE MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX)
  BEGIN
          IF @ACTUALIZA=1
          BEGIN
              begin tran UPDATE MAESTRO SET MA_ULTIMAMODIF=GETDATE() WHERE MA_CODIGO=@CONSECUTIVO  commit tran 
                  SELECT @CONSECUTIVO=(SELECT MA_CODIGO FROM MAESTRO  WHERE MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX)
              begin tran UPDATE MAESTRO SET MA_INV_GEN=@MAESTRO#MA_INV_GEN, MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX, MA_NOPARTE=@MAESTRO#MA_NOPARTE WHERE MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX commit tran 
               INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO,RI_TIPO,RI_CBFORMA) VALUES                                               ('MA_NOPARTE = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTE)+', '+'MA_INV_GEN = '+CONVERT(varchar(100),@MAESTRO#MA_INV_GEN)+', '+'MA_NOPARTEAUX = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTEAUX),'A',28) 
 if exists (select * from sysobjects where name='sysusrlog41')     insert into sysusrlog41 (user_id, mov_id, referencia, frmtag, fechahora) values                                                        (9, 2 ,'MA_NOPARTE = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTE)+', '+'MA_INV_GEN = '+CONVERT(varchar(100),@MAESTRO#MA_INV_GEN)+', '+'MA_NOPARTEAUX = '+CONVERT(varchar(100),@MAESTRO#MA_NOPARTEAUX),41, getdate()) 
             IF NOT EXISTS (SELECT MA_CODIGO FROM MAESTRODEF WHERE MA_CODIGO=@CONSECUTIVO)
          BEGIN
                            EXEC SP_GETCONSECUTIVO @TIPO='MAD',@VALUE=@CONSANEX OUTPUT
                            begin tran INSERT INTO MAESTRODEF (MAD_CODIGO,MA_CODIGO,MA_DEFNO1 ) VALUES (@CONSANEX,@CONSECUTIVO,@MAESTRODEF#MA_DEFNO1 ) commit tran 
                        END
          ELSE   begin tran  update MAESTRODEF set MA_DEFNO1 =@MAESTRODEF#MA_DEFNO1  where MA_CODIGO=@CONSECUTIVO commit tran 
                      DECLARE CUR_TEMPIMPORT141DET CURSOR FOR
                       SELECT MAX(Col_2),MAX(Col_3),MAX(Col_4),MAX(Col_5),MAX(Col_6),MAX(Col_7),MAX(Col_8),MAX(MAESTROCOST0#MA_COSTO),MAX(MAESTROCOST0#TCO_CODIGO),MAX(MAESTROCOST0#SPI_CODIGO),MAX(MAESTROCOST0#MA_PERINI),MAX(MAESTROCOST0#MA_GRAV_MP),MAX(MAESTROCOST0#MA_NG_MP),MAX(MAESTROCOST0#MA_GRAV_EMP),MAX(MAESTROCOST0#MA_NG_EMP),MAX(MAESTROCOST0#MA_GRAV_ADD),MAX(MAESTROCOST0#MA_GRAV_GI_MX),MAX(MAESTROCOST0#MA_GRAV_MO) FROM TEMPIMPORT141  WHERE MAESTRO0#MA_NOPARTE=@MAESTRO#MA_NOPARTE AND MAESTRO0#MA_INV_GEN=@MAESTRO#MA_INV_GEN AND MAESTRO0#MA_NOPARTEAUX=@MAESTRO#MA_NOPARTEAUX
                      OPEN CUR_TEMPIMPORT141DET
                      FETCH NEXT FROM CUR_TEMPIMPORT141DET INTO @Col_2 ,@Col_3 ,@Col_4 ,@Col_5 ,@Col_6 ,@Col_7 ,@Col_8 ,@MAESTROCOST#MA_COSTO ,@MAESTROCOST#TCO_CODIGO ,@MAESTROCOST#SPI_CODIGO ,@MAESTROCOST#MA_PERINI ,@MAESTROCOST#MA_GRAV_MP ,@MAESTROCOST#MA_NG_MP ,@MAESTROCOST#MA_GRAV_EMP ,@MAESTROCOST#MA_NG_EMP ,@MAESTROCOST#MA_GRAV_ADD ,@MAESTROCOST#MA_GRAV_GI_MX ,@MAESTROCOST#MA_GRAV_MO 
                      WHILE (@@FETCH_STATUS = 0)
                      BEGIN
                             IF NOT EXISTS (SELECT TCO_CODIGO,SPI_CODIGO,MA_PERINI FROM MAESTROCOST WHERE MA_CODIGO = @CONSECUTIVO AND TCO_CODIGO=@MAESTROCOST#TCO_CODIGO AND SPI_CODIGO=@MAESTROCOST#SPI_CODIGO AND MA_PERINI=@MAESTROCOST#MA_PERINI)
                    BEGIN
                         IF ISNULL(convert(varchar(10),@MAESTROCOST#TCO_CODIGO),'zzzzzzzz') <> 'zzzzzzzz' AND ISNULL(convert(varchar(10),@MAESTROCOST#SPI_CODIGO),'zzzzzzzz') <> 'zzzzzzzz' AND ISNULL(convert(varchar(10),@MAESTROCOST#MA_PERINI),'zzzzzzzz') <> 'zzzzzzzz'
                           BEGIN
                                IF EXISTS(SELECT * FROM MAESTROCOST WHERE MA_CODIGO = @CONSECUTIVO AND TCO_CODIGO=@MAESTROCOST#TCO_CODIGO AND SPI_CODIGO=@MAESTROCOST#SPI_CODIGO AND MA_PERINI<=@MAESTROCOST#MA_PERINI AND MA_PERFIN >=@MAESTROCOST#MA_PERINI)
                                BEGIN
                                  begin tran UPDATE MAESTROCOST SET MAESTROCOST.MA_PERFIN =convert(varchar(11),@MAESTROCOST#MA_PERINI-1,101) 
                                  WHERE MAESTROCOST.MAC_CODIGO in (SELECT MAX(MAC_CODIGO) FROM MAESTROCOST WHERE MA_PERINI IN (SELECT MAX(MA_PERINI) FROM MAESTROCOST 
                                                                   WHERE MA_CODIGO = @CONSECUTIVO AND TCO_CODIGO=@MAESTROCOST#TCO_CODIGO AND SPI_CODIGO=@MAESTROCOST#SPI_CODIGO) 
                                                                   AND MA_CODIGO = @CONSECUTIVO AND TCO_CODIGO=@MAESTROCOST#TCO_CODIGO AND SPI_CODIGO=@MAESTROCOST#SPI_CODIGO) 
                                  commit tran
                                END
                                  begin tran INSERT INTO MAESTROCOST (MA_CODIGO,MA_COSTO ,TCO_CODIGO ,SPI_CODIGO ,MA_PERINI ,MA_GRAV_MP ,MA_NG_MP ,MA_GRAV_EMP ,MA_NG_EMP ,MA_GRAV_ADD ,MA_GRAV_GI_MX ,MA_GRAV_MO ) VALUES (@CONSECUTIVO,@MAESTROCOST#MA_COSTO ,@MAESTROCOST#TCO_CODIGO ,@MAESTROCOST#SPI_CODIGO ,@MAESTROCOST#MA_PERINI ,@MAESTROCOST#MA_GRAV_MP ,@MAESTROCOST#MA_NG_MP ,@MAESTROCOST#MA_GRAV_EMP ,@MAESTROCOST#MA_NG_EMP ,@MAESTROCOST#MA_GRAV_ADD ,@MAESTROCOST#MA_GRAV_GI_MX ,@MAESTROCOST#MA_GRAV_MO ) commit tran
 
                           END
                    END
                          ELSE
                          BEGIN
                                 begin tran UPDATE MAESTROCOST SET MA_COSTO=@MAESTROCOST#MA_COSTO, TCO_CODIGO=@MAESTROCOST#TCO_CODIGO, SPI_CODIGO=@MAESTROCOST#SPI_CODIGO, MA_PERINI=@MAESTROCOST#MA_PERINI, MA_GRAV_MP=@MAESTROCOST#MA_GRAV_MP, MA_NG_MP=@MAESTROCOST#MA_NG_MP, MA_GRAV_EMP=@MAESTROCOST#MA_GRAV_EMP, MA_NG_EMP=@MAESTROCOST#MA_NG_EMP, MA_GRAV_ADD=@MAESTROCOST#MA_GRAV_ADD, MA_GRAV_GI_MX=@MAESTROCOST#MA_GRAV_GI_MX, MA_GRAV_MO=@MAESTROCOST#MA_GRAV_MO WHERE MA_CODIGO = @CONSECUTIVO AND TCO_CODIGO=@MAESTROCOST#TCO_CODIGO AND SPI_CODIGO=@MAESTROCOST#SPI_CODIGO AND MA_PERINI=@MAESTROCOST#MA_PERINI commit tran 
                          END
                      FETCH NEXT FROM CUR_TEMPIMPORT141DET INTO @Col_2 ,@Col_3 ,@Col_4 ,@Col_5 ,@Col_6 ,@Col_7 ,@Col_8 ,@MAESTROCOST#MA_COSTO ,@MAESTROCOST#TCO_CODIGO ,@MAESTROCOST#SPI_CODIGO ,@MAESTROCOST#MA_PERINI ,@MAESTROCOST#MA_GRAV_MP ,@MAESTROCOST#MA_NG_MP ,@MAESTROCOST#MA_GRAV_EMP ,@MAESTROCOST#MA_NG_EMP ,@MAESTROCOST#MA_GRAV_ADD ,@MAESTROCOST#MA_GRAV_GI_MX ,@MAESTROCOST#MA_GRAV_MO 
        END
        CLOSE CUR_TEMPIMPORT141DET
        DEALLOCATE CUR_TEMPIMPORT141DET
          END
  END
  FETCH NEXT FROM CUR_TEMPIMPORT141 INTO @Col_2 ,@Col_3 ,@Col_4 ,@Col_5 ,@Col_6 ,@Col_7 ,@Col_8 ,@MAESTRO#MA_INV_GEN ,@MAESTRO#MA_NOPARTEAUX ,@MAESTRO#MA_NOPARTE ,@MAESTRODEF#MA_DEFNO1 
END
CLOSE CUR_TEMPIMPORT141
DEALLOCATE CUR_TEMPIMPORT141
GO
