SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE dbo.[SP_GENAUTFACTEXPPOFI] (@PI_CODIGO INT, @FI_CODIGO INT)   as

DECLARE @AG_MEX INT, @AG_USA INT, @CL_CODIGO INT, @CL_MATRIZ INT, @CL_TRAFICO INT, @CT_CODIGO INT, @MT_CODIGO INT,
@PU_CARGA INT, @PU_DESTINO INT, @PU_ENTRADA INT, @PU_SALIDA INT, @ZO_CODIGO INT, @IT_ENTRADA INT, @MO_CODIGO INT,
@DIRPRINC INT, @DIRMATRIZ INT, @cp_codigo INT, @cl_destino INT, @fi_fecha DATETIME, @DIRDESTINO INT, @fe_folio VARCHAR(25),
@folio VARCHAR(25), @tq_codigo INT, @TF_CODIGO INT, @Ord_Compra VARCHAR(50), @CONSECUTIVO INT, @maximo INT, @Numero INT

         SELECT @AG_MEX=AG_MEX,  @AG_USA=AG_USA, @CL_CODIGO=CL_CODIGO, @CL_MATRIZ=CL_MATRIZ, @CL_TRAFICO=CL_TRAFICO, 
		@CT_CODIGO=CT_CODIGO, @MT_CODIGO=MT_CODIGO, @PU_CARGA=PU_CARGA, @PU_DESTINO=PU_DESTINO, 
		@PU_ENTRADA=PU_ENTRADA, @PU_SALIDA=PU_SALIDA, @ZO_CODIGO=ZO_CODIGO,
		@IT_ENTRADA= IT_ENTRADA, @MO_CODIGO=MO_CODIGO, 
 		@DIRPRINC=(SELECT DI_INDICE FROM DIR_CLIENTE WHERE DI_FISCAL='S' AND CL_CODIGO=CLIENTE.CL_CODIGO),
		@DIRMATRIZ=(SELECT DI_INDICE FROM DIR_CLIENTE WHERE DI_FISCAL='S' AND CL_CODIGO=CLIENTE.CL_MATRIZ)
	 FROM CLIENTE    WHERE CL_EMPRESA='S'

	select @cp_codigo=cp_codigo from claveped where cp_clave='V1'


	--exec Sp_GeneraTablaTemp 'FACTEXPDET'

	IF EXISTS (SELECT name FROM  [tempdb].dbo.sysobjects 
	   WHERE name = '##TempImportFACTEXPDET'  AND  type = 'U')
	begin
		drop table ##TempImportFACTEXPDET
	end

	CREATE TABLE [##TempImportFACTEXPDET] (
		[FED_INDICED] [int] IDENTITY (1, 1) NOT NULL ,
		[FE_CODIGO] [int] NOT NULL ,
		[MA_CODIGO] [int] NOT NULL ,
		[FED_NOMBRE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
		[FED_NOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
		[FED_NAME] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
		[ME_CODIGO] [int] NULL ,
		[FED_OBSERVA] [varchar] (1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FED_CANT] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_CANT] DEFAULT (0),
		[FED_GRA_MP] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_GRA_MP] DEFAULT (0),
		[FED_GRA_MO] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_GRA_MO] DEFAULT (0),
		[FED_GRA_EMP] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_GRA_EMP] DEFAULT (0),
		[FED_GRA_ADD] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_GRA_ADD] DEFAULT (0),
		[FED_GRA_GI] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_GRA_GI] DEFAULT (0),
		[FED_GRA_GI_MX] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_GRA_GI_MX] DEFAULT (0),
		[FED_NG_MP] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_NG_MP] DEFAULT (0),
		[FED_NG_EMP] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_NG_EMP] DEFAULT (0),
		[FED_NG_ADD] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_NG_ADD] DEFAULT (0),
		[FED_NG_USA] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_NG_USA] DEFAULT (0),
		[FED_COS_UNI] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_COS_UNI] DEFAULT (0),
		[FED_COS_TOT] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_COS_TOT] DEFAULT (0),
		[FED_PES_UNI] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_PES_UNI] DEFAULT (0),
		[FED_PES_NET] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_PES_NET] DEFAULT (0),
		[FED_PES_BRU] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_PES_BRU] DEFAULT (0),
		[FED_PES_UNILB] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_PES_UNILB] DEFAULT (0),
		[FED_PES_NETLB] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_PES_NETLB] DEFAULT (0),
		[FED_PES_BRULB] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_PES_BRULB] DEFAULT (0),
		[FED_SEC_IMP] [smallint] NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_SEC_IMP] DEFAULT (0),
		[FED_DEF_TIP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_DEF_TIP] DEFAULT ('G'),
		[FED_POR_DEF] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_POR_DEF] DEFAULT ((-1)),
		[FED_LOTE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[AR_IMPMX] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_AR_IMPMX] DEFAULT (0),
		[AR_EXPMX] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_AR_EXPMX] DEFAULT (0),
		[AR_IMPFO] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_AR_IMPFO] DEFAULT (0),
		[FED_CON_PED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_CON_PED] DEFAULT ('N'),
		[MA_GENERICO] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_MA_GENERICO] DEFAULT (0),
		[PA_CODIGO] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_PA_CODIGO] DEFAULT (0),
		[LE_CODIGO] [int] NULL ,
		[LED_INDICED] [int] NULL ,
		[EX_CODIGO] [int] NULL ,
		[FED_ORD_COMP] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_ORD_COMP] DEFAULT (''),
		[FED_NOORDEN] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_NOORDEN] DEFAULT (''),
		[FED_USO_COMMINV] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_USO_COMMINV] DEFAULT ('N'),
		[EQ_GEN] [decimal](28, 14) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_EQ_GEN] DEFAULT (1),
		[EQ_IMPFO] [decimal](28, 14) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_EQ_IMPFO] DEFAULT (1),
		[EQ_EXPMX] [decimal](28, 14) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_EQ_EXPMX] DEFAULT (1),
		[TI_CODIGO] [smallint] NOT NULL ,
		[FED_TENVIO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FED_INBOND] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FED_TIPOINBOND] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FED_RATEEXPMX] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_RATEEXPMX] DEFAULT ((-1)),
		[FED_RATEIMPFO] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_RATEIMPFO] DEFAULT ((-1)),
		[FED_RELEMP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_RELEMP] DEFAULT ('N'),
		[FED_FECHA_STRUCT] [datetime] NULL ,
		[FED_DISCHARGE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_DISCHARGE] DEFAULT ('S'),
		[LE_FOLIO] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[SPI_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_SPI_CODIGO] DEFAULT (0),
		[FED_SALDO] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_SALDO] DEFAULT (0),
		[FED_RETRABAJO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_RETRABAJO] DEFAULT ('N'),
		[ADE_CODIGO] [int] NULL ,
		[MA_EMPAQUE] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_MA_EMPAQUE] DEFAULT (0),
		[FED_CANTEMP] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_CANTEMP] DEFAULT (0),
		[FED_FAC_NUM] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FED_FEC_ENV] [datetime] NULL ,
		[FED_CANTGEN] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_CANTGEN] DEFAULT (0),
		[MO_CODIGO] [int] NULL ,
		[FED_DESCARGADO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_DESCARGADO] DEFAULT ('N'),
		[FED_PARTTYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[ME_GENERICO] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_ME_GENERICO] DEFAULT (0),
		[FED_TIP_ENS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[PID_INDICED] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_PID_INDICED] DEFAULT ((-1)),
		[MA_NOPARTECL] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[ME_AREXPMX] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_ME_AREXPMX] DEFAULT (0),
		[FED_NAFTA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_NAFTA] DEFAULT ('N'),
		[FED_DEFTXT1] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_DEFTXT1] DEFAULT (''),
		[FED_DEFTXT2] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_DEFTXT2] DEFAULT (''),
		[FED_DEFNO3] [decimal](38, 6) NULL ,
		[FED_DEFNO4] [decimal](38, 6) NULL ,
		[PID_INDICEDLIGA] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_PID_INDICEDLIGA] DEFAULT ((-1)),
		[PID_INDICEDLIGAR1] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_PID_INDICEDLIGAR1] DEFAULT ((-1)),
		[TCO_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_TCO_CODIGO] DEFAULT (0),
		[PI_ORIGENKITPADRE] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_PI_ORIGENKITPADRE] DEFAULT ((-1)),
		[CS_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_CS_CODIGO] DEFAULT (0),
		[SE_CODIGO] [smallint] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_SE_CODIGO] DEFAULT (0),
		[FED_RELCAJAS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[END_INDICED] [int] NULL ,
		[EN_CODIGO] [int] NULL ,
		[FED_SALDOTRANS] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_SALDOTRANS] DEFAULT (0),
		[FED_USOTRANS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_USOTRANS] DEFAULT ('N'),
		[FED_USOSALDO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_USOSALDO] DEFAULT ('N'),
		[CL_CODIGO] [int] NULL ,
		[MA_STRUCT] [int] NULL ,
		[FED_DESTNAFTA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[AR_ORIG] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_AR_ORIG] DEFAULT (0),
		[AR_NG_EMP] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_AR_NG_EMP] DEFAULT (0),
		[FED_NOPARTEAUX] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[ETA_CODIGO] [int] NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_ETA_CODIGO] DEFAULT ((-1)),
		[FED_NOPARTESTRUCT] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
		[FED_NG_MX] [decimal](38, 6) NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_NG_MX] DEFAULT (0),
		[FED_GENERA_EMPDET] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_GENERA_EMPDET] DEFAULT ('D'),
		[FED_GRAVA_VA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_##TempImportFACTEXPDET_FED_GRAVA_VA] DEFAULT ('S'),
		[FED_PARTIDA] [int] NULL ,
		[FED_SECF4] [int] NULL ,
		[FED_PRECIO_UNI] [decimal](38, 6) NULL ,
		[FED_PRECIO_TOT] [decimal](38, 6) NULL CONSTRAINT [DF_##TempImportFACTEXPDET_LED_PRECIO_TOT] DEFAULT (0),
		[FED_PIDSECUENCIA] [int] NULL ,
		[mc_noparte] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_##TempImportFACTEXPDET_mc_noparte] DEFAULT (''),		
		CONSTRAINT [PK_##TempImportFACTEXPDET] PRIMARY KEY  NONCLUSTERED 
		(
			[FED_INDICED]
		)  ON [PRIMARY] 
	) ON [PRIMARY]









	Declare Cur_FactImp cursor for
		SELECT     ISNULL(FACTIMPDET.CL_CODIGO,@CL_MATRIZ), FACTIMP.FI_FECHA, FACTIMP.TQ_CODIGO, FACTIMPDET.FID_ORD_COMP
		FROM         FACTIMPDET INNER JOIN
		                      FACTIMP ON FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
		WHERE     (FACTIMP.FI_CODIGO = @FI_CODIGO) and FACTIMPDET.FID_ORD_COMP NOT IN (SELECT FED_ORD_COMP FROM FACTEXPDET INNER JOIN FACTEXP ON FACTEXPDET.FE_CODIGO=FACTEXP.FE_CODIGO
								WHERE ISNULL(FED_ORD_COMP,'') <>'' AND FACTEXP.FE_TIPO='V')
			AND FACTIMPDET.FID_ORD_COMP NOT LIKE 'OP%'
			AND FACTIMPDET.FID_ORD_COMP NOT LIKE 'OT%'			
		GROUP BY FACTIMPDET.CL_CODIGO, FACTIMP.FI_FECHA, FACTIMP.TQ_CODIGO, FACTIMPDET.FID_ORD_COMP
	Open Cur_FactImp
	Fetch Next from Cur_FactImp into @cl_destino, @fi_fecha, @tq_codigo, @Ord_Compra
	While (@@fetch_status =0 )
	begin
	
		TRUNCATE TABLE ##TempImportFACTEXPDET

		dbcc checkident(##TempImportFACTEXPDET, reseed, 1)


		SELECT @DIRDESTINO=DI_INDICE FROM DIR_CLIENTE WHERE DI_FISCAL='S' AND CL_CODIGO=@CL_DESTINO
	
		SET @folio='REM'
	
			if exists (select * from factexp where fe_folio like @folio+'%' and fe_folio not like @folio+' %')
			begin
				SELECT @Numero=max(convert(int,REPLACE(RIGHT(fe_folio, 5), '_', '')))+1  FROM factexp where fe_folio like @folio+'%' and fe_folio not like @folio+' %'

			               SET @fe_folio= @folio+replicate('0', 5-(len(@Numero)))+convert(varchar(50),@Numero)
			end
			else
			       SET @fe_folio= @folio+'00001'
	
	
	
	
			 EXEC SP_GETCONSECUTIVO @TIPO='FE', @VALUE=@CONSECUTIVO OUTPUT
	
	
	
		          INSERT INTO FACTEXP (FE_CODIGO, FE_FECHA, FE_TIPOCAMBIO, FE_FOLIO, FE_TIPO, TF_CODIGO, TQ_CODIGO, 
				AG_MX, AG_US, CL_COMP, CL_DESTFIN, CL_DESTINI, CL_EXP, CL_IMP, CL_PROD, CL_VEND,
				CT_COMPANY1, DI_COMP, DI_DESTFIN, DI_DESTINI, DI_EXP, DI_IMP, DI_PROD,  DI_VEND, FE_PFINAL, FE_PINICIAL, IT_COMPANY1,
				MO_CODIGO, MT_COMPANY1, PU_CARGA, PU_DESTINO, PU_ENTRADA, PU_SALIDA, CL_EXPFIN, DI_EXPFIN, AGT_CODIGO, CP_CODIGO) 
	
	
		           SELECT @CONSECUTIVO, @FI_FECHA, dbo.ExchangeRate(@FI_FECHA), @fe_folio, 'V', 12, @TQ_CODIGO, 
				@AG_MEX, @AG_USA, @CL_DESTINO, @CL_DESTINO, @CL_DESTINO, @CL_CODIGO, @CL_DESTINO, @CL_CODIGO, @CL_CODIGO, 
				@CT_CODIGO, @DIRDESTINO, @DIRDESTINO, @DIRDESTINO, @DIRPRINC, @DIRDESTINO, @DIRPRINC, @DIRPRINC, @FI_FECHA, @FI_FECHA, 
				@IT_ENTRADA, @MO_CODIGO, @MT_CODIGO, @PU_CARGA, @PU_DESTINO, @PU_ENTRADA, @PU_SALIDA,  @CL_CODIGO, @DIRPRINC,
				isnull((SELECT AGT_CODIGO FROM AGENCIAPATENTE WHERE AGT_DEFAULT = 'S' AND AG_CODIGO = @AG_MEX),0), @cp_codigo

	

			UPDATE FACTEXP
			SET FC_CODIGO=
			(SELECT     MIN(dbo.FACTCONS.FC_CODIGO)
			FROM         dbo.FACTCONS INNER JOIN
			                      dbo.RELTFACTCLAPED ON dbo.FACTCONS.CP_CODIGO = dbo.RELTFACTCLAPED.CP_CODIGO RIGHT OUTER JOIN
			                      dbo.CLAVEPED ON dbo.FACTCONS.CP_CODIGO = dbo.CLAVEPED.CP_CODIGO
			WHERE     (dbo.FACTCONS.FC_TIPO = 'S') AND 
			FACTCONS.FC_FIN >= FACTEXP.FE_FECHA AND FACTCONS.FC_INI <= FACTEXP.FE_FECHA
			   AND dbo.FACTCONS.AGT_CODIGO = FACTEXP.AGT_CODIGO AND 
			   dbo.RELTFACTCLAPED.TF_CODIGO = 12 AND PR_CODIGO= FACTEXP.CL_DESTINI)
			WHERE FE_CODIGO=@CONSECUTIVO



			INSERT INTO ##TempImportFACTEXPDET(FE_CODIGO, FED_COS_UNI, FED_COS_TOT, PID_INDICED, FED_NOPARTE, 
			                      FED_NOMBRE, FED_NAME, FED_CANT, 
			                      MA_CODIGO, FED_PES_UNI, FED_PES_NET, FED_PES_BRU, FED_PES_UNILB, 
			                      FED_PES_NETLB, FED_PES_BRULB, FED_ORD_COMP, FED_NOORDEN, 
			                      FED_SEC_IMP, FED_POR_DEF, FED_DEF_TIP, ME_CODIGO, MA_GENERICO, 
			                      ME_AREXPMX, PA_CODIGO, EQ_GEN, EQ_EXPMX, EQ_IMPFO, 
			                      MA_EMPAQUE, FED_CANTEMP, SPI_CODIGO, TI_CODIGO, ME_GENERICO,  ma_nopartecl)	

			SELECT     @CONSECUTIVO, FACTIMPDET.FID_PRECIO_UNI, ROUND(FACTIMPDET.FID_PRECIO_UNI*FACTIMPDET.FID_CANT_ST,6), FACTIMPDET.PID_INDICEDLIGA, FACTIMPDET.FID_NOPARTE, 
			                      FACTIMPDET.FID_NOMBRE, FACTIMPDET.FID_NAME, FACTIMPDET.FID_CANT_ST, 
			                      FACTIMPDET.MA_CODIGO, FACTIMPDET.FID_PES_UNI, FACTIMPDET.FID_PES_NET, FACTIMPDET.FID_PES_BRU, FACTIMPDET.FID_PES_UNILB, 
			                      FACTIMPDET.FID_PES_NETLB, FACTIMPDET.FID_PES_BRULB, FACTIMPDET.FID_ORD_COMP, FACTIMPDET.FID_NOORDEN, 
			                      FACTIMPDET.FID_SEC_IMP, FACTIMPDET.FID_POR_DEF, FACTIMPDET.FID_DEF_TIP, FACTIMPDET.ME_CODIGO, FACTIMPDET.MA_GENERICO, 
			                      FACTIMPDET.ME_ARIMPMX, FACTIMPDET.PA_CODIGO, FACTIMPDET.EQ_GEN, FACTIMPDET.EQ_IMPMX, FACTIMPDET.EQ_EXPFO, 
			                      FACTIMPDET.MA_EMPAQUE, FACTIMPDET.FID_CANTEMP, FACTIMPDET.SPI_CODIGO, FACTIMPDET.TI_CODIGO, FACTIMPDET.ME_GEN,
					      (select mc_noparte from maestrocliente mc where mc.ma_codigo = FACTIMPDET.MA_CODIGO and mc.cl_codigo = @CL_DESTINO) 
			FROM         FACTIMPDET INNER JOIN FACTIMP ON FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
			WHERE     (FACTIMP.FI_CODIGO = @FI_CODIGO) AND FACTIMPDET.FID_ORD_COMP NOT LIKE 'OP%'
			AND FACTIMPDET.FID_ORD_COMP NOT LIKE 'OT%' AND ISNULL(FACTIMPDET.CL_CODIGO,@CL_MATRIZ)=@cl_destino AND FACTIMPDET.FID_ORD_COMP=@Ord_Compra


			select @maximo= isnull(max(FED_INDICED),0) from FACTEXPDET	

			INSERT INTO FACTEXPDET(FED_INDICED, FE_CODIGO, FED_COS_UNI, FED_COS_TOT, PID_INDICED, FED_NOPARTE, 
			                      FED_NOMBRE, FED_NAME, FED_CANT, 
			                      MA_CODIGO, FED_PES_UNI, FED_PES_NET, FED_PES_BRU, FED_PES_UNILB, 
			                      FED_PES_NETLB, FED_PES_BRULB, FED_ORD_COMP, FED_NOORDEN, 
			                      FED_SEC_IMP, FED_POR_DEF, FED_DEF_TIP, ME_CODIGO, MA_GENERICO, 
			                      ME_AREXPMX, PA_CODIGO, EQ_GEN, EQ_EXPMX, EQ_IMPFO, 
			                      MA_EMPAQUE, FED_CANTEMP, SPI_CODIGO, TI_CODIGO, ME_GENERICO, ma_nopartecl)
	
			SELECT FED_INDICED+@maximo, FE_CODIGO, FED_COS_UNI, FED_COS_TOT, PID_INDICED, FED_NOPARTE, 
			                      FED_NOMBRE, FED_NAME, FED_CANT, 
			                      MA_CODIGO, FED_PES_UNI, FED_PES_NET, FED_PES_BRU, FED_PES_UNILB, 
			                      FED_PES_NETLB, FED_PES_BRULB, FED_ORD_COMP, FED_NOORDEN, 
			                      FED_SEC_IMP, FED_POR_DEF, FED_DEF_TIP, ME_CODIGO, MA_GENERICO, 
			                      ME_AREXPMX, PA_CODIGO, EQ_GEN, EQ_EXPMX, EQ_IMPFO, 
			                      MA_EMPAQUE, FED_CANTEMP, SPI_CODIGO, TI_CODIGO, ME_GENERICO,ma_nopartecl

			FROM ##TempImportFACTEXPDET
			WHERE FE_CODIGO=@CONSECUTIVO



			UPDATE PIDESCARGA
			SET PID_SALDOGEN=PID_SALDOGEN-(SELECT SUM(FED_CANT*EQ_GEN) FROM ##TempImportFACTEXPDET WHERE PID_INDICED=PIDESCARGA.PID_INDICED)
			WHERE PID_INDICED IN (SELECT PID_INDICED FROM ##TempImportFACTEXPDET WHERE PID_INDICED IS NOT NULL AND PID_INDICED<>-1)



			select @maximo= isnull(max(FED_INDICED),0) from FACTEXPDET
	
	
			update consecutivo
			set cv_codigo =  @maximo+1
			where cv_tipo = 'FED'

			Fetch Next from Cur_FactImp into @cl_destino, @fi_fecha, @tq_codigo, @Ord_Compra
		end
	
	        Close Cur_FactImp
	        Deallocate Cur_FactImp




	--exec SP_ACTUALIZAESTATUSPEDIMP @PI_CODIGO


	IF EXISTS (SELECT name FROM  [tempdb].dbo.sysobjects 
	   WHERE name = '##TempImportFACTEXPDET'  AND  type = 'U')
	begin
		drop table ##TempImportFACTEXPDET
	end


GO
