SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_IMPORTPTTYCO] (@TABLA VARCHAR(150), @USER INT)   as

			DELETE FROM REGISTROSIMPORTADOS WHERE RI_CBFORMA=28


                  UPDATE MAESTRO SET MA_ULTIMAMODIF=GETDATE() 
		  WHERE MA_NOPARTE+'-'+MA_NOPARTEAUX IN 
			(SELECT MAESTRO0#MA_NOPARTE+'-'+MAESTRO0#MA_NOPARTE
			FROM TEMPIMPORT141 
			GROUP BY MAESTRO0#MA_NOPARTE+'-'+MAESTRO0#MA_NOPARTE)
          
          
          update TempImport141
          set
             MAESTRO0#AR_EXPFO = (select [AR_Codigo]
                                  from   Arancel ar
                                  where  [AR_Fraccion] = (select Arancel.[AR_Fraccion]
                                                          from   Arancel
                                                          where  Arancel.[AR_Codigo] = TempImport141.[MAESTRO0#AR_EXPFO])
                                         and ar.[AR_Tipo] = 'E'
                                         and ar.[PA_Codigo] <> 154)
             , MAESTRO0#AR_IMPFO = (select [AR_Codigo]
                                    from   Arancel ar
                                    where  [AR_Fraccion] = (select Arancel.[AR_Fraccion]
                                                            from   Arancel
                                                            where  Arancel.[AR_Codigo] = TempImport141.[MAESTRO0#AR_IMPFO])
                                           and ar.[AR_Tipo] = 'I'
                                           and ar.[PA_Codigo] <> 154)
          
          
          
          
          

          UPDATE MAESTRO 
		  SET MA_EXPENS=MAESTRO0#MA_EXPENS, 
			MA_TIP_ENS=MAESTRO0#MA_TIP_ENS, 
			TI_CODIGO=MAESTRO0#TI_CODIGO, 
			MA_NOMBRE=MAESTRO0#MA_NOMBRE, 
			MA_NAME=MAESTRO0#MA_NAME, 
			ME_COM=MAESTRO0#ME_COM, 
			PA_ORIGEN=MAESTRO0#PA_ORIGEN, 
			PA_PROCEDE=MAESTRO0#PA_PROCEDE, 
			MA_GENERICO=MAESTRO0#MA_GENERICO, 
			AR_IMPMX=MAESTRO0#AR_IMPMX, 
			AR_EXPMX=MAESTRO0#AR_EXPMX, 
			--2010-11-26
            AR_IMPFOUSA = /*TempImport141.MAESTRO0#AR_IMPFOUSA, */
                   (select ar.[AR_Codigo]
                    from   Arancel ar
                    where  ar.[AR_Fraccion] = (select Arancel.[AR_Fraccion]
                                               from   Arancel
                                               where  Arancel.[AR_Codigo] = TempImport141.[MAESTRO0#AR_IMPFO])
					       and ar.[AR_Tipo] = 'I'
					       and ar.[PA_Codigo] <> 154
				   ),
            AR_EXPFO = /*TempImport141.MAESTRO0#AR_EXPFO, */
                   (select ar.[AR_Codigo]
                    from   Arancel ar
                    where  ar.[AR_Fraccion] = (select Arancel.[AR_Fraccion]
                                               from   Arancel
                                               where  Arancel.[AR_Codigo] = TempImport141.[MAESTRO0#AR_EXPFO])
                           and ar.[AR_Tipo] = 'E'
                           and ar.[PA_Codigo] <> 154
                   ),
            AR_IMPFO = /*TempImport141.MAESTRO0#AR_IMPFO, */
                   (select [AR_Codigo]
                    from   Arancel ar
                    where  [AR_Fraccion] = (select Arancel.[AR_Fraccion]
                                            from   Arancel
                                            where  Arancel.[AR_Codigo] = TempImport141.[MAESTRO0#AR_IMPFO])
                           and ar.[AR_Tipo] = 'I'
                           and ar.[PA_Codigo] <> 154
                   ),
			MA_DEF_TIP=MAESTRO0#MA_DEF_TIP, 
			SE_CODIGO=MAESTRO0#SE_CODIGO, 
			MA_PESO_LB=MAESTRO0#MA_PESO_LB, 
			MA_TIEMPOENSMIN=MAESTRO0#MA_TIEMPOENSMIN, 
			CC_CODIGO=MAESTRO0#CC_CODIGO 
 		  FROM MAESTRO INNER JOIN
		                      TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND
				MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
		  WHERE (MAESTRO.MA_INV_GEN = 'I') and MAESTRO0#MA_TIP_ENS<>'A'


		--2010-11-26
		--agregar actualizar Factores de conversion
		--Fraccion IMP USA
			DECLARE @ma_codigo int, @ar_codigo int
			
			
			DECLARE fracciones_cursor CURSOR FOR
			select ma_codigo, ar_impfo as ar_codigo
			FROM MAESTRO INNER JOIN TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE 
			AND MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
			WHERE (MAESTRO.MA_INV_GEN = 'I')
			order by maestro.ma_codigo
			
			OPEN fracciones_cursor
			
			FETCH NEXT FROM fracciones_cursor
			INTO @ma_codigo, @ar_codigo
			
			WHILE @@FETCH_STATUS = 0
			BEGIN
			
			   exec SP_ACTUALIZAEQARANCEL @ar_codigo,  @ma_codigo
			
			   FETCH NEXT FROM fracciones_cursor
			   INTO @ma_codigo, @ar_codigo
			END
			
			CLOSE fracciones_cursor
			DEALLOCATE fracciones_cursor
		
		--Fraccion IMP USA orig
			set @ma_codigo = 0 
			set @ar_codigo = 0
		
			DECLARE fracciones_cursor CURSOR FOR
			select ma_codigo, AR_IMPFOUSA as ar_codigo
			FROM MAESTRO INNER JOIN TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE 
			AND MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
			WHERE (MAESTRO.MA_INV_GEN = 'I')
			order by maestro.ma_codigo
			
			OPEN fracciones_cursor
			
			FETCH NEXT FROM fracciones_cursor
			INTO @ma_codigo, @ar_codigo
			
			WHILE @@FETCH_STATUS = 0
			BEGIN
			
			   exec SP_ACTUALIZAEQARANCEL @ar_codigo,  @ma_codigo
			
			   FETCH NEXT FROM fracciones_cursor
			   INTO @ma_codigo, @ar_codigo
			END
			
			CLOSE fracciones_cursor
			DEALLOCATE fracciones_cursor
		
		--Fraccion IMP USA
			DECLARE fracciones_cursor CURSOR FOR
			select ma_codigo, AR_EXPFO as ar_codigo
			FROM MAESTRO INNER JOIN TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE 
			AND MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
			WHERE (MAESTRO.MA_INV_GEN = 'I')
			order by maestro.ma_codigo
			
			OPEN fracciones_cursor
			
			FETCH NEXT FROM fracciones_cursor
			INTO @ma_codigo, @ar_codigo
			
			WHILE @@FETCH_STATUS = 0
			BEGIN
			
			   exec SP_ACTUALIZAEQARANCEL @ar_codigo,  @ma_codigo
			
			   FETCH NEXT FROM fracciones_cursor
			   INTO @ma_codigo, @ar_codigo
			END
			
			CLOSE fracciones_cursor
			DEALLOCATE fracciones_cursor

                  UPDATE MAESTRO 
		  SET MA_EXPENS=MAESTRO0#MA_EXPENS, 
			MA_TIP_ENS=MAESTRO0#MA_TIP_ENS, 
			TI_CODIGO=MAESTRO0#TI_CODIGO, 
			ME_COM=MAESTRO0#ME_COM, 
			PA_PROCEDE=MAESTRO0#PA_PROCEDE, 
			MA_DEF_TIP=MAESTRO0#MA_DEF_TIP, 
			SE_CODIGO=MAESTRO0#SE_CODIGO, 
			MA_PESO_LB=MAESTRO0#MA_PESO_LB, 
			MA_TIEMPOENSMIN=MAESTRO0#MA_TIEMPOENSMIN, 
			CC_CODIGO=MAESTRO0#CC_CODIGO 
 		  FROM MAESTRO INNER JOIN
		                      TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND
				MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
		  WHERE (MAESTRO.MA_INV_GEN = 'I') and MAESTRO0#MA_TIP_ENS='A'

	        exec SP_CREATABLALOG 41
	        insert into sysusrlog41 (user_id, mov_id, referencia, frmtag, fechahora) 
 	        SELECT     @USER, 2, 'Actualizacion de pt Info. (No. Parte: '+MAESTRO.MA_NOPARTE+')', 41, getdate()
		  FROM MAESTRO INNER JOIN
	                      TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND
			MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
	        WHERE (MAESTRO.MA_INV_GEN = 'I')


		-- REGISTROS ACTUALIZADOS
                INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO,RI_TIPO,RI_CBFORMA) 
		SELECT 'MA_NOPARTE = '+CONVERT(varchar(100),MAESTRO0#MA_NOPARTE)+', MA_INV_GEN = I, MA_NOPARTEAUX = '+CONVERT(varchar(100),MAESTRO0#MA_NOPARTEAUX),'A',28
		FROM MAESTRO INNER JOIN
		                    TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND
				MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
		WHERE (MAESTRO.MA_INV_GEN = 'I')


		-- REGISTROS ANEXADOS
                INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO,RI_TIPO,RI_CBFORMA) 
		SELECT 'MA_NOPARTE = '+CONVERT(varchar(100),MAESTRO0#MA_NOPARTE)+', MA_INV_GEN = I, MA_NOPARTEAUX = '+CONVERT(varchar(100),MAESTRO0#MA_NOPARTEAUX),'I',28
		FROM TempImport141
		WHERE MAESTRO0#MA_NOPARTE+'-'+MAESTRO0#MA_NOPARTEAUX NOT IN (SELECT MA_NOPARTE+'-'+MA_NOPARTEAUX FROM MAESTRO WHERE MA_INV_GEN='I')


		exec Sp_GeneraTablaTemp 'MAESTRO'



	       INSERT INTO TempImportMAESTRO (MA_EXPENS ,MA_INV_GEN ,MA_NOPARTEAUX ,MA_TIP_ENS ,MA_NOPARTE ,TI_CODIGO ,MA_NOMBRE ,
		MA_NAME ,ME_COM ,PA_ORIGEN ,PA_PROCEDE ,MA_GENERICO ,AR_IMPMX ,AR_EXPMX ,AR_IMPFO ,AR_EXPFO ,MA_DEF_TIP ,SE_CODIGO ,
		MA_PESO_LB ,MA_TIEMPOENSMIN ,CC_CODIGO) 


		SELECT MAESTRO0#MA_EXPENS, MAESTRO0#MA_INV_GEN, MAESTRO0#MA_NOPARTEAUX, MAESTRO0#MA_TIP_ENS, MAESTRO0#MA_NOPARTE, 
		MAESTRO0#TI_CODIGO, MAESTRO0#MA_NOMBRE, MAESTRO0#MA_NAME, MAESTRO0#ME_COM, MAESTRO0#PA_ORIGEN, MAESTRO0#PA_PROCEDE, 
		MAESTRO0#MA_GENERICO, MAESTRO0#AR_IMPMX, MAESTRO0#AR_EXPMX, MAESTRO0#AR_IMPFO, MAESTRO0#AR_EXPFO, MAESTRO0#MA_DEF_TIP, 
		MAESTRO0#SE_CODIGO, MAESTRO0#MA_PESO_LB, MAESTRO0#MA_TIEMPOENSMIN, MAESTRO0#CC_CODIGO
		FROM TempImport141
		WHERE MAESTRO0#MA_NOPARTE+'-'+MAESTRO0#MA_NOPARTEAUX NOT IN (SELECT MA_NOPARTE+'-'+MA_NOPARTEAUX FROM MAESTRO WHERE MA_INV_GEN='I')


		INSERT INTO MAESTRO(MA_CODIGO, MA_EXPENS ,MA_INV_GEN ,MA_NOPARTEAUX ,MA_TIP_ENS ,MA_NOPARTE ,TI_CODIGO ,MA_NOMBRE ,
			MA_NAME ,ME_COM ,PA_ORIGEN ,PA_PROCEDE ,MA_GENERICO ,AR_IMPMX ,AR_EXPMX ,AR_IMPFO ,AR_EXPFO ,MA_DEF_TIP ,SE_CODIGO ,
			MA_PESO_LB ,MA_TIEMPOENSMIN ,CC_CODIGO, MA_ULTIMAMODIF)

		SELECT MA_CODIGO, MA_EXPENS ,MA_INV_GEN ,MA_NOPARTEAUX ,MA_TIP_ENS ,MA_NOPARTE ,TI_CODIGO ,MA_NOMBRE ,
			MA_NAME ,ME_COM ,PA_ORIGEN ,PA_PROCEDE ,MA_GENERICO ,AR_IMPMX ,AR_EXPMX ,AR_IMPFO ,AR_EXPFO ,MA_DEF_TIP ,SE_CODIGO ,
			MA_PESO_LB ,MA_TIEMPOENSMIN ,CC_CODIGO, GETDATE()
		FROM TempImportMAESTRO

		declare @maximo int

		select @maximo= max(MA_CODIGO) from MAESTRO

		if exists(select * from maestrorefer) and (select isnull(max(ma_codigo),0) from maestrorefer)>@maximo
		select @maximo= isnull(max(MA_CODIGO),0) from MAESTROREFER

		update consecutivo
		set cv_codigo =  @maximo+1
		where cv_tipo = 'MA'

		/* ============ ANEXO24 ===========*/

		INSERT INTO ANEXO24(MA_CODIGO)
		SELECT MAESTRO.MA_CODIGO	                  
 		  FROM MAESTRO INNER JOIN
		                      TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND
				MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
		  WHERE (MAESTRO.MA_INV_GEN = 'I') and MAESTRO0#MA_TIP_ENS='A' AND MAESTRO.MA_CODIGO NOT IN (SELECT MA_CODIGO FROM ANEXO24)

		
	               UPDATE ANEXO24
		  SET MA_NOMBREFIS=MAESTRO0#MA_NOMBRE, 
			MA_NAMEFIS=MAESTRO0#MA_NAME, 
			PA_ORIGENFIS=MAESTRO0#PA_ORIGEN, 
			MA_GENERICOFIS=MAESTRO0#MA_GENERICO, 
			AR_EXPMXFIS=MAESTRO0#AR_EXPMX, 
			AR_IMPFOFIS=MAESTRO0#AR_IMPFO
 		  FROM MAESTRO INNER JOIN
		                      TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND
				MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
			INNER JOIN ANEXO24 ON MAESTRO.MA_CODIGO=ANEXO24.MA_CODIGO
		  WHERE (MAESTRO.MA_INV_GEN = 'I') and MAESTRO0#MA_TIP_ENS='A'






		/* ============ MARESTROCATEG ===========*/

   		-- yolanda  25-abril-06
		DELETE FROM MAESTROCATEG WHERE MA_CODIGO IN
		(SELECT MAESTRO.MA_CODIGO
		FROM TempImport141 INNER JOIN
		     MAESTRO ON TempImport141.MAESTRO0#MA_NOPARTE = MAESTRO.MA_NOPARTE
		AND TempImport141.MAESTRO0#MA_NOPARTEAUX = MAESTRO.MA_NOPARTEAUX
		WHERE MAESTROCATEG0#CPE_CODIGO IS NOT NULL
                	AND MAESTRO.TI_CODIGO=14
		GROUP BY MAESTRO.MA_CODIGO)
		-- yolanda  25-abril-06

		INSERT INTO MAESTROCATEG (MA_CODIGO,CPE_CODIGO )
		SELECT MAESTRO.MA_CODIGO, MAESTROCATEG0#CPE_CODIGO
		FROM TempImport141 INNER JOIN
		     MAESTRO ON TempImport141.MAESTRO0#MA_NOPARTE = MAESTRO.MA_NOPARTE AND
		     TempImport141.MAESTRO0#MA_NOPARTEAUX = MAESTRO.MA_NOPARTEAUX
		WHERE CONVERT(VARCHAR(150),MAESTRO.MA_CODIGO)+'-'+CONVERT(VARCHAR(150),MAESTROCATEG0#CPE_CODIGO)
		NOT IN (SELECT CONVERT(VARCHAR(150),MA_CODIGO)+'-'+CONVERT(VARCHAR(150),CPE_CODIGO) FROM MAESTROCATEG)


		/* ============ MARESTRODEF ===========*/

		exec Sp_GeneraTablaTemp 'MAESTRODEF'


		UPDATE MAESTRODEF
		SET  MA_DEFTXT1= TempImport141.MAESTRODEF0#MA_DEFTXT1, 
		     MA_DEFTXT2=TempImport141.MAESTRODEF0#MA_DEFTXT2, 
		     MA_DEFNO1=TempImport141.MAESTRODEF0#MA_DEFNO1, 
		     MA_DEFNO2=TempImport141.MAESTRODEF0#MA_DEFNO2, 
		     MA_DEFBOL1=TempImport141.MAESTRODEF0#MA_DEFBOL1, 
		     MA_DEFBOL2=TempImport141.MAESTRODEF0#MA_DEFBOL2, 
                     MA_DEFDATE1=TempImport141.MAESTRODEF0#MA_DEFDATE1, 
		     MA_DEFDATE2=TempImport141.MAESTRODEF0#MA_DEFDATE2,
		     MA_DEFDATE3=TempImport141.MAESTRODEF0#MA_DEFDATE3
		FROM         TempImport141 INNER JOIN
		                      MAESTRO ON TempImport141.MAESTRO0#MA_NOPARTE = MAESTRO.MA_NOPARTE AND
				TempImport141.MAESTRO0#MA_NOPARTEAUX = MAESTRO.MA_NOPARTEAUX INNER JOIN
		                      MAESTRODEF ON MAESTRO.MA_CODIGO = MAESTRODEF.MA_CODIGO



		insert into TempImportMAESTRODEF (MA_CODIGO,MA_DEFTXT1 ,MA_DEFTXT2 ,MA_DEFBOL1 ,MA_DEFBOL2 ,MA_DEFDATE1 ,MA_DEFDATE2, MA_DEFDATE3, MA_DEFNO1 ,MA_DEFNO2 )
		SELECT MAESTRO.MA_CODIGO, MAESTRODEF0#MA_DEFTXT1 ,MAESTRODEF0#MA_DEFTXT2, MAESTRODEF0#MA_DEFBOL1 ,
		MAESTRODEF0#MA_DEFBOL2 ,MAESTRODEF0#MA_DEFDATE1, MAESTRODEF0#MA_DEFDATE2, MAESTRODEF0#MA_DEFDATE3,
		MAESTRODEF0#MA_DEFNO1, MAESTRODEF0#MA_DEFNO2
		FROM TempImport141 INNER JOIN
		     MAESTRO ON TempImport141.MAESTRO0#MA_NOPARTE = MAESTRO.MA_NOPARTE AND
			TempImport141.MAESTRO0#MA_NOPARTEAUX = MAESTRO.MA_NOPARTEAUX
		WHERE MAESTRO.MA_CODIGO NOT IN (SELECT M1.MA_CODIGO FROM MAESTRODEF M1)


		INSERT INTO MAESTRODEF(MAD_CODIGO, MA_CODIGO,MA_DEFTXT1 ,MA_DEFTXT2 ,MA_DEFBOL1 ,MA_DEFBOL2 ,MA_DEFDATE1 ,MA_DEFDATE2, MA_DEFDATE3, MA_DEFNO1 ,MA_DEFNO2)
		SELECT MAD_CODIGO, MA_CODIGO,MA_DEFTXT1 ,MA_DEFTXT2 ,MA_DEFBOL1 ,MA_DEFBOL2 ,MA_DEFDATE1 ,MA_DEFDATE2, MA_DEFDATE3, MA_DEFNO1 ,MA_DEFNO2
		FROM TempImportMAESTRODEF


		update consecutivo
		set cv_codigo =  isnull((select max(MAD_CODIGO) from MAESTRODEF),0) + 1
		where cv_tipo = 'MAD'


		/* ============ MARESTROCOST ===========*/
  	        exec SP_CREATABLALOG 41
	        insert into sysusrlog41 (user_id, mov_id, referencia, frmtag, fechahora) 
		SELECT     @USER, 2, 'Act. Imp. Datos, No. Parte: '+MAESTRO.MA_NOPARTE+', Costo Unitario: '+convert(varchar(50),MAESTROCOST.MA_COSTO), 41, getdate()
		FROM         MAESTRO INNER JOIN
		                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO INNER JOIN
		                      TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND
			         MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX AND 
		                      MAESTROCOST.TCO_CODIGO = TempImport141.MAESTROCOST0#TCO_CODIGO AND 
		                      MAESTROCOST.SPI_CODIGO = TempImport141.MAESTROCOST0#SPI_CODIGO 


		UPDATE MAESTROCOST
		SET     MAESTROCOST.MA_COSTO= TempImport141.MAESTROCOST0#MA_COSTO,
			MAESTROCOST.MA_GRAV_MO= TempImport141.MAESTROCOST0#MA_GRAV_MO
		FROM         MAESTRO INNER JOIN
		                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO INNER JOIN
		                      TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND 
			        MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX AND
		                      MAESTROCOST.TCO_CODIGO = TempImport141.MAESTROCOST0#TCO_CODIGO AND 
		                      MAESTROCOST.SPI_CODIGO = TempImport141.MAESTROCOST0#SPI_CODIGO 


                   INSERT INTO MAESTROCOST (MA_CODIGO,SPI_CODIGO ,TCO_CODIGO ,MA_PERINI ,MA_COSTO, MA_GRAV_MO ) 
		   SELECT MAESTRO.MA_CODIGO, MAESTROCOST0#SPI_CODIGO, MAESTROCOST0#TCO_CODIGO, MIN(MAESTROCOST0#MA_PERINI), MAX(MAESTROCOST0#MA_COSTO), max(MAESTROCOST0#MA_GRAV_MO)
		   FROM TempImport141 INNER JOIN
		        MAESTRO ON TempImport141.MAESTRO0#MA_NOPARTE = MAESTRO.MA_NOPARTE AND
			TempImport141.MAESTRO0#MA_NOPARTEAUX = MAESTRO.MA_NOPARTEAUX
		   WHERE convert(varchar(150),MAESTRO.MA_CODIGO)+ convert(varchar(150),MAESTROCOST0#SPI_CODIGO)+convert(varchar(150),MAESTROCOST0#TCO_CODIGO) not in
			(select convert(varchar(150),maestrocost.MA_CODIGO)+ convert(varchar(150),maestrocost.SPI_CODIGO)+convert(varchar(150),maestrocost.TCO_CODIGO)
			from maestrocost where maestrocost.ma_codigo=MAESTRO.MA_CODIGO)
		   GROUP BY MAESTRO.MA_CODIGO, MAESTROCOST0#SPI_CODIGO, MAESTROCOST0#TCO_CODIGO
		


/*                  UPDATE MAESTROCOST 
		  SET MAESTROCOST.MA_PERFIN =convert(varchar(11),getdate()-1,101) 
                  WHERE MAESTROCOST.MAC_CODIGO in (SELECT MAESTROCOST.MAC_CODIGO
						FROM TempImport141 INNER JOIN
						                      MAESTRO ON TempImport141.MAESTRO0#MA_NOPARTE = MAESTRO.MA_NOPARTE INNER JOIN
						                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO AND 
						                      TempImport141.MAESTROCOST0#TCO_CODIGO = MAESTROCOST.TCO_CODIGO AND 
						                      TempImport141.MAESTROCOST0#SPI_CODIGO = MAESTROCOST.SPI_CODIGO
						GROUP BY MAESTROCOST.MAC_CODIGO)


		UPDATE MAESTROCOST
		SET     MAESTROCOST.MA_COSTO= TempImport141.MAESTROCOST0#MA_COSTO,
			MAESTROCOST.MA_GRAV_MO= TempImport141.MAESTROCOST0#MA_GRAV_MO
		FROM         MAESTRO INNER JOIN
		                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO INNER JOIN
		                      TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND 
		                      MAESTROCOST.TCO_CODIGO = TempImport141.MAESTROCOST0#TCO_CODIGO AND 
		                      MAESTROCOST.MA_PERINI = TempImport141.MAESTROCOST0#MA_PERINI AND 
		                      MAESTROCOST.SPI_CODIGO = TempImport141.MAESTROCOST0#SPI_CODIGO 


                   INSERT INTO MAESTROCOST (MA_CODIGO,SPI_CODIGO ,TCO_CODIGO ,MA_PERINI ,MA_COSTO, MA_GRAV_MO ) 
		   SELECT MAESTRO.MA_CODIGO, MAESTROCOST0#SPI_CODIGO, MAESTROCOST0#TCO_CODIGO, MAESTROCOST0#MA_PERINI, MAX(MAESTROCOST0#MA_COSTO), max(MAESTROCOST0#MA_GRAV_MO)
		   FROM TempImport141 INNER JOIN
		        MAESTRO ON TempImport141.MAESTRO0#MA_NOPARTE = MAESTRO.MA_NOPARTE
		   WHERE convert(varchar(150),MAESTRO.MA_CODIGO)+ convert(varchar(150),MAESTROCOST0#SPI_CODIGO)+convert(varchar(150),MAESTROCOST0#TCO_CODIGO)+convert(varchar(150),MAESTROCOST0#MA_PERINI) not in
			(select convert(varchar(150),maestrocost.MA_CODIGO)+ convert(varchar(150),maestrocost.SPI_CODIGO)+convert(varchar(150),maestrocost.TCO_CODIGO)+convert(varchar(150),maestrocost.MA_PERINI) 
			from maestrocost where maestrocost.ma_codigo=MAESTRO.MA_CODIGO)
		   GROUP BY MAESTRO.MA_CODIGO, MAESTROCOST0#SPI_CODIGO, MAESTROCOST0#TCO_CODIGO, MAESTROCOST0#MA_PERINI



              update MAESTROCOST 
	      set MA_GRAV_MO = round(CENTROCOSTO$2453_1.CC_MO*Col_25,6)
              FROM         dbo.TempImport141 INNER JOIN
                      dbo.MAESTRO ON dbo.TempImport141.MAESTRO0#MA_NOPARTE = dbo.MAESTRO.MA_NOPARTE RIGHT OUTER JOIN
                      dbo.MAESTROCOST ON dbo.TempImport141.MAESTROCOST0#TCO_CODIGO = dbo.MAESTROCOST.TCO_CODIGO AND 
                      dbo.TempImport141.NAFTA0#SPI_CODIGO = dbo.MAESTROCOST.SPI_CODIGO AND 
                      dbo.TempImport141.MAESTROCOST0#MA_PERINI = dbo.MAESTROCOST.MA_PERINI AND 
                      dbo.MAESTRO.MA_CODIGO = dbo.MAESTROCOST.MA_CODIGO LEFT OUTER JOIN
                      dbo.CENTROCOSTO CENTROCOSTO$2453_1 ON dbo.MAESTRO.CC_CODIGO = CENTROCOSTO$2453_1.CC_CODIGO
		WHERE CENTROCOSTO$2453_1.CC_MO*Col_25 IS NOT NULL


              update MAESTROCOST 
	      set MA_COSTO = round(( MAESTROCOST.MA_GRAV_EMP+MAESTROCOST.MA_NG_EMP +MAESTROCOST.MA_GRAV_GI_MX +MAESTROCOST.MA_GRAV_GI+MAESTROCOST.MA_GRAV_MO+MAESTROCOST.MA_GRAV_ADD + MAESTROCOST.MA_GRAV_MP +MAESTROCOST.MA_NG_MP ),6)
	      FROM MAESTRO INNER JOIN
                      MAESTROCOST ON MAESTRO.MA_CODIGO = MAESTROCOST.MA_CODIGO INNER JOIN
                      TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND 
                      MAESTROCOST.TCO_CODIGO = TempImport141.MAESTROCOST0#TCO_CODIGO AND 
                      MAESTROCOST.MA_PERINI = TempImport141.MAESTROCOST0#MA_PERINI AND 
                      MAESTROCOST.SPI_CODIGO = TempImport141.MAESTROCOST0#SPI_CODIGO 
*/


		/* ============ NAFTA ===========*/
		exec Sp_GeneraTablaTemp 'NAFTA'

	        INSERT INTO TempImportNAFTA (MA_CODIGO,SPI_CODIGO ,PA_CLASE ,NFT_CRITERIO ,NFT_FABRICA ,NFT_PERINI ,NFT_PERFIN ,NFT_NETCOST ,
			NFT_OTRASINST, NFT_CALIFICO, NFT_NOPARTE, NFT_NOPARTEAUX) 
		SELECT MAESTRO.MA_CODIGO, NAFTA0#SPI_CODIGO, NAFTA0#PA_CLASE, NAFTA0#NFT_CRITERIO, NAFTA0#NFT_FABRICA, NAFTA0#NFT_PERINI, 
		  NAFTA0#NFT_PERFIN, NAFTA0#NFT_NETCOST, NAFTA0#NFT_OTRASINST, 'S', TempImport141.MAESTRO0#MA_NOPARTE, TempImport141.MAESTRO0#MA_NOPARTEAUX
		FROM MAESTRO INNER JOIN
		                    TempImport141 ON MAESTRO.MA_NOPARTE = TempImport141.MAESTRO0#MA_NOPARTE AND
				MAESTRO.MA_NOPARTEAUX = TempImport141.MAESTRO0#MA_NOPARTEAUX
		WHERE CONVERT(VARCHAR(150),NAFTA0#NFT_PERINI)+ CONVERT(VARCHAR(150),NAFTA0#SPI_CODIGO)
			NOT IN (SELECT CONVERT(VARCHAR(150),NAFTA.NFT_PERINI)+ CONVERT(VARCHAR(150),NAFTA.SPI_CODIGO)
				FROM NAFTA WHERE NAFTA.MA_CODIGO=MAESTRO.MA_CODIGO)
		AND (MAESTRO.MA_INV_GEN = 'I') and NAFTA0#SPI_CODIGO=22
		


		INSERT INTO NAFTA(NFT_CODIGO,MA_CODIGO,SPI_CODIGO ,PA_CLASE ,NFT_CRITERIO ,NFT_FABRICA ,NFT_PERINI ,NFT_PERFIN ,NFT_NETCOST ,
		NFT_OTRASINST, NFT_CALIFICO, NFT_NOPARTE, NFT_NOPARTEAUX)
		SELECT NFT_CODIGO,MA_CODIGO,SPI_CODIGO ,PA_CLASE ,NFT_CRITERIO ,NFT_FABRICA ,NFT_PERINI ,NFT_PERFIN ,NFT_NETCOST ,
		NFT_OTRASINST, NFT_CALIFICO, NFT_NOPARTE, NFT_NOPARTEAUX
		FROM TempImportNAFTA


		update consecutivo
		set cv_codigo =  isnull((select max(NFT_CODIGO) from NAFTA),0) + 1
		where cv_tipo = 'NFT'


		IF (SELECT AR_RETORNOUSA FROM CONFIGURACION) IS NOT NULL
		UPDATE MAESTRO
		SET MAESTRO.AR_IMPFOUSA=(SELECT AR_RETORNOUSA FROM CONFIGURACION)
		WHERE MA_CODIGO IN
		(SELECT     MAESTRO.MA_CODIGO
		FROM         MAESTRO INNER JOIN
		                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO INNER JOIN
		                      ARANCEL ON MAESTRO.AR_IMPFOUSA = ARANCEL.AR_CODIGO
		WHERE     (NOT (ARANCEL.AR_FRACCION LIKE '980%')) AND ((CONFIGURATIPO.CFT_TIPO <> 'S' AND
		                      CONFIGURATIPO.CFT_TIPO <> 'P') OR MAESTRO.MA_TIP_ENS='C' OR MAESTRO.MA_TIP_ENS='A'))


		IF (SELECT AR_INSERTO FROM CONFIGURACION) IS NOT NULL
		UPDATE MAESTRO
		SET MAESTRO.AR_IMPFOUSA=(SELECT AR_INSERTO FROM CONFIGURACION)
		WHERE MA_CODIGO IN
		(SELECT     MAESTRO.MA_CODIGO
		FROM         MAESTRO INNER JOIN
		                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO INNER JOIN
		                      ARANCEL ON MAESTRO.AR_IMPFOUSA = ARANCEL.AR_CODIGO
		WHERE     NOT (ARANCEL.AR_FRACCION LIKE '980%') AND ((CONFIGURATIPO.CFT_TIPO = 'S' OR
		                      CONFIGURATIPO.CFT_TIPO = 'P') AND MAESTRO.MA_TIP_ENS<>'A' AND MAESTRO.MA_TIP_ENS<>'C'))


		UPDATE MAESTROCOST
		SET     MA_COSTO= ROUND(MA_GRAV_MP + MA_GRAV_ADD + MA_GRAV_EMP + MA_GRAV_GI + MA_GRAV_GI_MX + MA_GRAV_MO + MA_NG_MP +
		                      MA_NG_ADD + MA_NG_EMP,6)
		FROM         MAESTROCOST
		WHERE TCO_CODIGO=1 AND 
		MA_COSTO<> ROUND(MA_GRAV_MP + MA_GRAV_ADD + MA_GRAV_EMP + MA_GRAV_GI + MA_GRAV_GI_MX + MA_GRAV_MO + MA_NG_MP +
		                      MA_NG_ADD + MA_NG_EMP,6)


		
		UPDATE MAESTRO
		SET     MA_DISCHARGE='N'
		WHERE MA_TIP_ENS='F' AND (MA_DISCHARGE='S' OR MA_DISCHARGE IS NULL)


GO
