SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





































CREATE PROCEDURE [dbo].[SP_ACTUALIZAEQGENALMDESP] (@FE_CODIGO int)   as

SET NOCOUNT ON 
		-- existe en equivalencias
		if exists (SELECT dbo.ALMACENDESP.EQ_GENERICO
		FROM         dbo.EQUIVALE INNER JOIN
		                      dbo.ALMACENDESP ON dbo.EQUIVALE.ME_CODIGO1 = dbo.ALMACENDESP.ME_CODIGO LEFT OUTER JOIN
		                      dbo.MAESTRO ON dbo.EQUIVALE.ME_CODIGO2 = dbo.MAESTRO.ME_COM AND 
		                      dbo.ALMACENDESP.MA_GENERICO = dbo.MAESTRO.MA_CODIGO
		WHERE     dbo.MAESTRO.ME_COM<>(SELECT ME_KILOGRAMOS FROM CONFIGURACION) AND dbo.ALMACENDESP.FETR_CODIGO = @FE_CODIGO)

		UPDATE dbo.ALMACENDESP
		SET     dbo.ALMACENDESP.EQ_GENERICO= dbo.EQUIVALE.EQ_CANT
		FROM         dbo.EQUIVALE INNER JOIN
		                      dbo.ALMACENDESP ON dbo.EQUIVALE.ME_CODIGO1 = dbo.ALMACENDESP.ME_CODIGO LEFT OUTER JOIN
		                      dbo.MAESTRO ON dbo.EQUIVALE.ME_CODIGO2 = dbo.MAESTRO.ME_COM AND 
		                      dbo.ALMACENDESP.MA_GENERICO = dbo.MAESTRO.MA_CODIGO
		WHERE     (dbo.ALMACENDESP.FETR_CODIGO = @FE_CODIGO) AND dbo.MAESTRO.ME_COM<>(SELECT ME_KILOGRAMOS FROM CONFIGURACION)
		

		-- me_gen igual a Kg
		UPDATE dbo.ALMACENDESP
		SET     dbo.ALMACENDESP.EQ_GENERICO= isnull(dbo.ALMACENDESP.ADE_PESO_UNIKG,1)
		FROM       dbo.ALMACENDESP LEFT OUTER JOIN dbo.MAESTRO ON
                           dbo.ALMACENDESP.MA_GENERICO = dbo.MAESTRO.MA_CODIGO
		WHERE     (dbo.ALMACENDESP.FETR_CODIGO = @FE_CODIGO) AND (dbo.MAESTRO.ME_COM=(SELECT ME_KILOGRAMOS FROM CONFIGURACION)
		OR dbo.ALMACENDESP.EQ_GENERICO IS NULL)

		UPDATE dbo.ALMACENDESP
		SET     dbo.ALMACENDESP.EQ_GENERICO=1
		FROM       dbo.ALMACENDESP LEFT OUTER JOIN dbo.MAESTRO ON
                           dbo.ALMACENDESP.MA_GENERICO = dbo.MAESTRO.MA_CODIGO
		WHERE     (dbo.ALMACENDESP.FETR_CODIGO = @FE_CODIGO) AND dbo.MAESTRO.ME_COM=(SELECT ME_KILOGRAMOS FROM CONFIGURACION)
		AND dbo.ALMACENDESP.ME_CODIGO=(SELECT ME_KILOGRAMOS FROM CONFIGURACION)




































GO
