SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CREAVIMPORTTEMPBOM] (@sumaIncorpor char(1), @TipoActualizacion char(1))   as

Declare @X Int,@POS Varchar(100)
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[VIMPORTTEMPBOM]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [dbo].[VIMPORTTEMPBOM]
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[VIMPORTTEMPBOM]') and OBJECTPROPERTY(id, N'IsTable') = 1)
drop table [dbo].[VIMPORTTEMPBOM]
	
	if(SELECT CF_USABOMSEC FROM CONFIGURACION)='S' and exists(select * from IMPORTTEMPBOM where (bst_sec=0 or bst_sec=-1))
	begin
		Select Consecutivo,bsu_noparte, bst_sec
		Into dbo.[#Temps]
		From IMPORTTEMPBOM 
		where (bst_sec =0 or bst_sec =-1)
		Order by Consecutivo
	
		SET @X=0
		SET @POS=''
		Update #Temps 
		SET bst_sec=@X,@X=CASE WHEN @POS = bsu_noparte THEN @X+1 ELSE 1 END,
                                  @POS=CASE WHEN @POS = bsu_noparte THEN @POS ELSE bsu_noparte END
	
		
		Update IMPORTTEMPBOM 
		SET bst_sec=T.bst_sec 
		From #Temps T inner join IMPORTTEMPBOM on T.Consecutivo=IMPORTTEMPBOM.Consecutivo

	end

	if @TipoActualizacion='H'
	begin
		-- borra los regstros que tienen mismo padre, mismo componente y misma fecha final, solo deja la ultima
		DELETE FROM IMPORTTEMPBOM 
		WHERE BSU_NOPARTE+BST_NOPARTE+CONVERT(VARCHAR(11),BST_PERFIN,101)+CONVERT(VARCHAR(11),BST_SEC) IN 
			(SELECT BSU_NOPARTE+BST_NOPARTE+CONVERT(VARCHAR(11),BST_PERFIN,101)+CONVERT(VARCHAR(11),BST_SEC)
			FROM IMPORTTEMPBOM 
			GROUP BY BSU_NOPARTE+BST_NOPARTE+CONVERT(VARCHAR(11),BST_PERFIN,101)+CONVERT(VARCHAR(11),BST_SEC) 
			HAVING COUNT(*) >1)
		AND CONSECUTIVO NOT IN
			(SELECT MAX(CONSECUTIVO)
			FROM IMPORTTEMPBOM 
			GROUP BY BSU_NOPARTE+BST_NOPARTE+CONVERT(VARCHAR(11),BST_PERFIN,101)+CONVERT(VARCHAR(11),BST_SEC) 
			HAVING COUNT(*) >1)
			
	end
	if @sumaIncorpor='S'
	begin	
		exec ('SELECT     MAX(CONSECUTIVO) AS CONSECUTIVO, ISNULL(MAESTROHIJO.MA_CODIGO, MAESTROREFERHIJO.MA_CODIGO) AS BST_HIJO, ISNULL(MAESTROPADRE.MA_CODIGO, MAESTROREFERPADRE.MA_CODIGO) AS BSU_SUBENSAMBLE, 
				      ISNULL(MAESTROHIJO.TI_CODIGO, MAESTROREFERHIJO.TI_CODIGO) AS TI_CODIGO, 
				      ISNULL(dbo.IMPORTTEMPBOM.ME_CODIGO, ISNULL(MAESTROHIJO.ME_COM,MAESTROREFERHIJO.ME_COM))  AS ME_CODIGO, 
		                      ISNULL(dbo.IMPORTTEMPBOM.FACTCONV, ISNULL(MAESTROHIJO.EQ_GEN, MAESTROREFERHIJO.EQ_GEN)) AS FACTCONV, 
					dbo.IMPORTTEMPBOM.BST_PERINI, 
		                      ISNULL(dbo.IMPORTTEMPBOM.BST_PERFIN, CONVERT(DATETIME, ''9999-01-01 00:00:00'', 102)) AS BST_PERFIN, 
		                      ISNULL(ISNULL(dbo.IMPORTTEMPBOM.ME_GEN, MAESTROGEN.ME_COM), 19) AS ME_GEN, ISNULL(dbo.IMPORTTEMPBOM.BST_TRANS, ''N'') 
		                      AS BST_TRANS, dbo.IMPORTTEMPBOM.BSU_NOPARTE, dbo.IMPORTTEMPBOM.BST_NOPARTE, ISNULL(MAESTROHIJO.PA_ORIGEN, MAESTROREFERHIJO.PA_ORIGEN) AS PA_CODIGO, ISNULL(dbo.IMPORTTEMPBOM.BST_PERCAMBIO, ''S'') AS BST_PERCAMBIO, 
		                      dbo.IMPORTTEMPBOM.BSU_NOPARTEAUX, dbo.IMPORTTEMPBOM.BST_NOPARTEAUX, ISNULL(ISNULL(dbo.IMPORTTEMPBOM.BST_DISCH, 
		                      MAESTROHIJO.MA_DISCHARGE), ''N'') AS BST_DISCH, SUM(dbo.IMPORTTEMPBOM.BST_INCORPOR) AS BST_INCORPOR, 
		                      case when ISNULL(dbo.IMPORTTEMPBOM.BST_TIP_ENS, ISNULL(MAESTROHIJO.MA_TIP_ENS, MAESTROREFERHIJO.MA_TIP_ENS))=''A'' then
					''F'' else ISNULL(dbo.IMPORTTEMPBOM.BST_TIP_ENS, ISNULL(MAESTROHIJO.MA_TIP_ENS, MAESTROREFERHIJO.MA_TIP_ENS)) end AS BST_TIP_ENS, ISNULL(max(ISNULL(MAESTROHIJO.MA_PESO_KG,MAESTROREFERHIJO.MA_PESO_KG)),0) as MA_PESO_KG,
			isnull(max(MAESTROHIJO.AR_IMPFO),0) as AR_IMPFO, dbo.IMPORTTEMPBOM.BST_SEC
			INTO dbo.VIMPORTTEMPBOM
			FROM         dbo.IMPORTTEMPBOM LEFT OUTER JOIN
			                      dbo.MAESTRO MAESTROPADRE ON dbo.IMPORTTEMPBOM.BSU_NOPARTEAUX = MAESTROPADRE.MA_NOPARTEAUX AND 
			                      dbo.IMPORTTEMPBOM.BSU_NOPARTE = MAESTROPADRE.MA_NOPARTE LEFT OUTER JOIN
			                      dbo.MAESTRO MAESTROHIJO ON dbo.IMPORTTEMPBOM.BST_NOPARTE = MAESTROHIJO.MA_NOPARTE AND 
			                      dbo.IMPORTTEMPBOM.BST_NOPARTEAUX = MAESTROHIJO.MA_NOPARTEAUX LEFT OUTER JOIN
			                      dbo.MAESTRO MAESTROGEN ON MAESTROHIJO.MA_GENERICO = MAESTROGEN.MA_CODIGO LEFT OUTER JOIN
			                      dbo.MAESTROREFER MAESTROREFERHIJO ON dbo.IMPORTTEMPBOM.BST_NOPARTE = MAESTROREFERHIJO.MA_NOPARTE AND 
			                      dbo.IMPORTTEMPBOM.BST_NOPARTEAUX = MAESTROREFERHIJO.MA_NOPARTEAUX LEFT OUTER JOIN
			                      dbo.MAESTROREFER MAESTROREFERPADRE ON dbo.IMPORTTEMPBOM.BSU_NOPARTEAUX = MAESTROREFERPADRE.MA_NOPARTEAUX AND 
			                      dbo.IMPORTTEMPBOM.BSU_NOPARTE = MAESTROREFERPADRE.MA_NOPARTE
			 where MAESTROHIJO.MA_INV_GEN <> ''G'' and MAESTROPADRE.MA_INV_GEN <> ''G''
			GROUP BY ISNULL(MAESTROHIJO.MA_CODIGO, MAESTROREFERHIJO.MA_CODIGO), ISNULL(MAESTROPADRE.MA_CODIGO, MAESTROREFERPADRE.MA_CODIGO), 
				      ISNULL(MAESTROHIJO.TI_CODIGO, MAESTROREFERHIJO.TI_CODIGO), 
				      ISNULL(dbo.IMPORTTEMPBOM.ME_CODIGO, ISNULL(MAESTROHIJO.ME_COM,MAESTROREFERHIJO.ME_COM)), 
		                      ISNULL(dbo.IMPORTTEMPBOM.FACTCONV, ISNULL(MAESTROHIJO.EQ_GEN, MAESTROREFERHIJO.EQ_GEN)), 
					dbo.IMPORTTEMPBOM.BST_PERINI, 
		                      ISNULL(dbo.IMPORTTEMPBOM.BST_PERFIN, CONVERT(DATETIME, ''9999-01-01 00:00:00'', 102)), 
		                      ISNULL(ISNULL(dbo.IMPORTTEMPBOM.ME_GEN, MAESTROGEN.ME_COM), 19), ISNULL(dbo.IMPORTTEMPBOM.BST_TRANS, ''N'') 
		                      , dbo.IMPORTTEMPBOM.BSU_NOPARTE, dbo.IMPORTTEMPBOM.BST_NOPARTE, ISNULL(MAESTROHIJO.PA_ORIGEN, MAESTROREFERHIJO.PA_ORIGEN), ISNULL(dbo.IMPORTTEMPBOM.BST_PERCAMBIO, ''S''), 
		                      dbo.IMPORTTEMPBOM.BSU_NOPARTEAUX, dbo.IMPORTTEMPBOM.BST_NOPARTEAUX, ISNULL(ISNULL(dbo.IMPORTTEMPBOM.BST_DISCH, 
		                      MAESTROHIJO.MA_DISCHARGE), ''N''), case when ISNULL(dbo.IMPORTTEMPBOM.BST_TIP_ENS, ISNULL(MAESTROHIJO.MA_TIP_ENS, MAESTROREFERHIJO.MA_TIP_ENS))=''A'' then
					''F'' else ISNULL(dbo.IMPORTTEMPBOM.BST_TIP_ENS, ISNULL(MAESTROHIJO.MA_TIP_ENS, MAESTROREFERHIJO.MA_TIP_ENS)) end, 
			              dbo.IMPORTTEMPBOM.BST_SEC')
	end
	else
	begin
		exec ('SELECT     MAX(CONSECUTIVO) AS CONSECUTIVO, ISNULL(MAESTROHIJO.MA_CODIGO,MAESTROREFERHIJO.MA_CODIGO) AS BST_HIJO, 
				      ISNULL(MAESTROPADRE.MA_CODIGO,MAESTROREFERPADRE.MA_CODIGO) AS BSU_SUBENSAMBLE, 
		                      ISNULL(MAESTROHIJO.TI_CODIGO,MAESTROREFERHIJO.TI_CODIGO) AS TI_CODIGO, ISNULL(dbo.IMPORTTEMPBOM.ME_CODIGO, 
				      ISNULL(MAESTROHIJO.ME_COM,MAESTROREFERHIJO.ME_COM)) AS ME_CODIGO, 
		                      ISNULL(dbo.IMPORTTEMPBOM.FACTCONV, ISNULL(MAESTROHIJO.EQ_GEN,MAESTROREFERHIJO.EQ_GEN)) AS FACTCONV, dbo.IMPORTTEMPBOM.BST_PERINI, 
		                      ISNULL(dbo.IMPORTTEMPBOM.BST_PERFIN, CONVERT(DATETIME, ''9999-01-01 00:00:00'', 102)) AS BST_PERFIN, 
		                      ISNULL(ISNULL(dbo.IMPORTTEMPBOM.ME_GEN, MAESTROGEN.ME_COM), 19) AS ME_GEN, ISNULL(dbo.IMPORTTEMPBOM.BST_TRANS, ''N'') 
		                      AS BST_TRANS, dbo.IMPORTTEMPBOM.BSU_NOPARTE, dbo.IMPORTTEMPBOM.BST_NOPARTE, ISNULL(MAESTROHIJO.PA_ORIGEN,MAESTROREFERHIJO.PA_ORIGEN) AS PA_CODIGO, ISNULL(dbo.IMPORTTEMPBOM.BST_PERCAMBIO, ''S'') AS BST_PERCAMBIO, 
		                      dbo.IMPORTTEMPBOM.BSU_NOPARTEAUX, dbo.IMPORTTEMPBOM.BST_NOPARTEAUX, ISNULL(dbo.IMPORTTEMPBOM.BST_DISCH, 
		                      ISNULL(MAESTROHIJO.MA_DISCHARGE,''N'')) AS BST_DISCH, dbo.IMPORTTEMPBOM.BST_INCORPOR AS BST_INCORPOR, 
		                      case when ISNULL(dbo.IMPORTTEMPBOM.BST_TIP_ENS, ISNULL(MAESTROHIJO.MA_TIP_ENS,MAESTROREFERHIJO.MA_TIP_ENS))=''A'' then ''F''
				      else ISNULL(dbo.IMPORTTEMPBOM.BST_TIP_ENS, ISNULL(MAESTROHIJO.MA_TIP_ENS,MAESTROREFERHIJO.MA_TIP_ENS)) end AS BST_TIP_ENS, 
				      isnull(max(ISNULL(MAESTROHIJO.MA_PESO_KG,MAESTROREFERHIJO.MA_PESO_KG)),0) as MA_PESO_KG,
			isnull(max(MAESTROHIJO.AR_IMPFO),0) as AR_IMPFO, dbo.IMPORTTEMPBOM.BST_SEC
		INTO dbo.VIMPORTTEMPBOM
		FROM         dbo.IMPORTTEMPBOM LEFT OUTER JOIN
		                      dbo.MAESTRO MAESTROPADRE ON dbo.IMPORTTEMPBOM.BSU_NOPARTEAUX = MAESTROPADRE.MA_NOPARTEAUX AND 
		                      dbo.IMPORTTEMPBOM.BSU_NOPARTE = MAESTROPADRE.MA_NOPARTE LEFT OUTER JOIN
		                      dbo.MAESTRO MAESTROHIJO ON dbo.IMPORTTEMPBOM.BST_NOPARTE = MAESTROHIJO.MA_NOPARTE AND 
		                      dbo.IMPORTTEMPBOM.BST_NOPARTEAUX = MAESTROHIJO.MA_NOPARTEAUX LEFT OUTER JOIN
		                      dbo.MAESTRO MAESTROGEN ON MAESTROHIJO.MA_GENERICO = MAESTROGEN.MA_CODIGO LEFT OUTER JOIN
		                      dbo.MAESTROREFER MAESTROREFERHIJO ON dbo.IMPORTTEMPBOM.BST_NOPARTE = MAESTROREFERHIJO.MA_NOPARTE AND 
		                      dbo.IMPORTTEMPBOM.BST_NOPARTEAUX = MAESTROREFERHIJO.MA_NOPARTEAUX LEFT OUTER JOIN
		                      dbo.MAESTROREFER MAESTROREFERPADRE ON dbo.IMPORTTEMPBOM.BSU_NOPARTEAUX = MAESTROREFERPADRE.MA_NOPARTEAUX AND 
		                      dbo.IMPORTTEMPBOM.BSU_NOPARTE = MAESTROREFERPADRE.MA_NOPARTE
		where MAESTROHIJO.MA_INV_GEN <> ''G'' and MAESTROPADRE.MA_INV_GEN <> ''G''
		GROUP BY ISNULL(MAESTROHIJO.MA_CODIGO,MAESTROREFERHIJO.MA_CODIGO), 
				      ISNULL(MAESTROPADRE.MA_CODIGO,MAESTROREFERPADRE.MA_CODIGO), 
		                      ISNULL(MAESTROHIJO.TI_CODIGO,MAESTROREFERHIJO.TI_CODIGO), ISNULL(dbo.IMPORTTEMPBOM.ME_CODIGO, 
				      ISNULL(MAESTROHIJO.ME_COM,MAESTROREFERHIJO.ME_COM)), 
		                      ISNULL(dbo.IMPORTTEMPBOM.FACTCONV, ISNULL(MAESTROHIJO.EQ_GEN,MAESTROREFERHIJO.EQ_GEN)), dbo.IMPORTTEMPBOM.BST_PERINI, 
		                      ISNULL(dbo.IMPORTTEMPBOM.BST_PERFIN, CONVERT(DATETIME, ''9999-01-01 00:00:00'', 102)), 
		                      ISNULL(ISNULL(dbo.IMPORTTEMPBOM.ME_GEN, MAESTROGEN.ME_COM), 19), ISNULL(dbo.IMPORTTEMPBOM.BST_TRANS, ''N'') 
		                      , dbo.IMPORTTEMPBOM.BSU_NOPARTE, dbo.IMPORTTEMPBOM.BST_NOPARTE, ISNULL(MAESTROHIJO.PA_ORIGEN,MAESTROREFERHIJO.PA_ORIGEN), ISNULL(dbo.IMPORTTEMPBOM.BST_PERCAMBIO, ''S''), 
		                      dbo.IMPORTTEMPBOM.BSU_NOPARTEAUX, dbo.IMPORTTEMPBOM.BST_NOPARTEAUX, ISNULL(dbo.IMPORTTEMPBOM.BST_DISCH, 
		                      ISNULL(MAESTROHIJO.MA_DISCHARGE,''N'')), dbo.IMPORTTEMPBOM.BST_INCORPOR, 
		                      case when ISNULL(dbo.IMPORTTEMPBOM.BST_TIP_ENS, ISNULL(MAESTROHIJO.MA_TIP_ENS,MAESTROREFERHIJO.MA_TIP_ENS))=''A'' then ''F''
				      else ISNULL(dbo.IMPORTTEMPBOM.BST_TIP_ENS, ISNULL(MAESTROHIJO.MA_TIP_ENS,MAESTROREFERHIJO.MA_TIP_ENS)) end,
		                      dbo.IMPORTTEMPBOM.BST_SEC')
	end
GO
