SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_IMPEXCELPRODUCCION] @Codigo int   as

SET NOCOUNT ON 
DECLARE @Prod_indiced INT, @consecutivo INT
--borra los registros de la tabla que se hayan importado sin numero de parte
delete from IMPEXCELPROD where NOPARTE=''

DELETE FROM IMPORTLOG WHERE IML_CBFORMA=109
if (select count(*) from IMPORTLOG)=0
DBCC CHECKIDENT (IMPORTLOG, RESEED, 0) WITH NO_INFOMSGS
-- revisa si existen en el catalogo maestro
if exists(SELECT dbo.IMPEXCELPROD.NOPARTE
	FROM         dbo.MAESTRO RIGHT OUTER JOIN
	                      dbo.IMPEXCELPROD ON dbo.MAESTRO.MA_NOPARTE = dbo.IMPEXCELPROD.NOPARTE
	WHERE     (dbo.MAESTRO.MA_NOPARTE IS NULL))
	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR NO. PARTE : ' +dbo.IMPEXCELPROD.NOPARTE +' POR QUE NO EXISTE EN EL CAT. MAESTRO', 109
	FROM         dbo.MAESTRO RIGHT OUTER JOIN
	                      dbo.IMPEXCELPROD ON dbo.MAESTRO.MA_NOPARTE = dbo.IMPEXCELPROD.NOPARTE
	WHERE     (dbo.MAESTRO.MA_NOPARTE IS NULL) 
-- revisa si es producto terminado o subensamble
if exists(SELECT dbo.IMPEXCELPROD.NOPARTE
	FROM         dbo.MAESTRO RIGHT OUTER JOIN
	                      dbo.IMPEXCELPROD ON dbo.MAESTRO.MA_NOPARTE = dbo.IMPEXCELPROD.NOPARTE
	WHERE     dbo.MAESTRO.TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE CFT_TIPO<>'P' AND CFT_TIPO<>'S'))
	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR NO. PARTE : ' +dbo.IMPEXCELPROD.NOPARTE +' POR QUE ES DIFERENTE DE PRODUCTO TERMINADO Y SUBENSAMBLE' , 109
	FROM         dbo.MAESTRO RIGHT OUTER JOIN
	                      dbo.IMPEXCELPROD ON dbo.MAESTRO.MA_NOPARTE = dbo.IMPEXCELPROD.NOPARTE
	WHERE     dbo.MAESTRO.TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE CFT_TIPO<>'P' AND CFT_TIPO<>'S')

	select @consecutivo=cv_codigo from consecutivo
	where cv_tipo = 'PID'
-- insercion a la tabla producdet
INSERT INTO PRODUCDET     (PRO_CODIGO, PROD_INDICED, MA_CODIGO, PROD_NOPARTE, PROD_NOMBRE, PROD_CANT, ME_CODIGO, MA_FAMILIA, PROD_CANTPEND)
SELECT     @Codigo, IMPEXCELPROD.ORDEN+@consecutivo, MAESTRO.MA_CODIGO, IMPEXCELPROD.NOPARTE, MAESTRO.MA_NOMBRE, IMPEXCELPROD.CANTIDAD, 
                      MAESTRO.ME_COM, MAESTRO.MA_FAMILIA, IMPEXCELPROD.CANTIDAD
FROM         IMPEXCELPROD LEFT OUTER JOIN
                      MAESTRO ON IMPEXCELPROD.NOPARTE = MAESTRO.MA_NOPARTE
WHERE     (MAESTRO.MA_INV_GEN = 'I') AND MAESTRO.TI_CODIGO IN (SELECT TI_CODIGO FROM CONFIGURATIPO WHERE CFT_TIPO='P' OR CFT_TIPO='S')
ORDER BY IMPEXCELPROD.ORDEN

select @Prod_indiced= max(prod_indiced) from producdet
	update consecutivo
	set cv_codigo =  isnull(@prod_indiced,0) + 1
	where cv_tipo = 'PROD'

GO
