SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_FILL_BOM_DESCTEMP1_INV] (@FED_INDICED INT, @BST_PT INT, @BST_HIJO INT, @BST_ENTRAVIGOR DATETIME, @BST_PERINI DATETIME, @FED_CANT decimal(38,6), @CODIGOFACTURA INT, @CF_USATIPOADQUISICION char(1), @BST_INCORPOR1 decimal(38,6), @CF_NIVELES int, @nivel int)   as

SET NOCOUNT ON 
declare @BST_HIJO1 int, @BST_INCORPOR decimal(38,6), @BST_DISCH char(1), @TI_CODIGO char(1), @ME_CODIGO int, @Factconv decimal(28,14), 
    @BST_PERINI1 datetime, @BST_PERFIN datetime, @ME_GEN int, @BST_TRANS char(1), @BST_TIPOCOSTO char(1), 
    @MA_TIP_ENS char(1), @nivelr int, @BST_TIPODESC VARCHAR(5), @incorporacionfinal decimal(38,6), @BST_PESO_KG decimal(38,6)


	SET @nivelr=@nivel+1

	--if @BST_HIJO=5359
	--print '5359'
	--print @BST_PERINI

			insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
			    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
			   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO, FACT_INV)

			SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_INCORPOR) * @BST_INCORPOR1 AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
			                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
			                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
			                      dbo.BOM_STRUCT.BST_TIP_ENS, @FED_CANT, @CODIGOFACTURA, 'B'+convert(varchar(5),@nivelr), 'N' AS BST_TIPODESC,
					@BST_HIJO, @FED_INDICED, @BST_PT, @BST_ENTRAVIGOR, dbo.MAESTRO.MA_PESO_KG, isnull((SELECT MA_COSTO FROM VMAESTROCOST
				WHERE MA_CODIGO=dbo.BOM_STRUCT.BST_HIJO),0), 'I'
			FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
			                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
			                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
			WHERE (dbo.CONFIGURATIPO.CFT_TIPO<>'P' and dbo.CONFIGURATIPO.CFT_TIPO<>'S') and dbo.BOM_STRUCT.BST_TIP_ENS='C'
			GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
			                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
			                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
			                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.MAESTRO.MA_PESO_KG
			HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
			AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
			AND SUM(dbo.BOM_STRUCT.BST_INCORPOR) >0
			/*UNION
			--desperdicio
			SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_DESP) * @BST_INCORPOR1 AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
			                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
			                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
			                      dbo.BOM_STRUCT.BST_TIP_ENS, @FED_CANT, @CODIGOFACTURA, 'B'+convert(varchar(5),@nivelr), 'D' AS BST_TIPODESC,
					@BST_HIJO, @FED_INDICED, @BST_PT, @BST_ENTRAVIGOR, dbo.BOM_STRUCT.BST_PESO_KG, isnull((SELECT MA_COSTO FROM VMAESTROCOST
				WHERE MA_CODIGO=dbo.BOM_STRUCT.BST_HIJO),0)
			FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
			                      dbo.CONFIGURATIPO ON dbo.BOM_STRUCT.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
			                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO
			WHERE (dbo.CONFIGURATIPO.CFT_TIPO<>'P' and dbo.CONFIGURATIPO.CFT_TIPO<>'S') and dbo.BOM_STRUCT.BST_TIP_ENS='C'
			GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
			                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
			                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
			                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.BOM_STRUCT.BST_PESO_KG
			HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
			AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
			AND SUM(dbo.BOM_STRUCT.BST_DESP) >0
			UNION
			--merma
			SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_MERMA) * @BST_INCORPOR1 AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
			                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
			                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
			                      dbo.BOM_STRUCT.BST_TIP_ENS, @FED_CANT, @CODIGOFACTURA, 'B'+convert(varchar(5),@nivelr), 'M' AS BST_TIPODESC,
					@BST_HIJO, @FED_INDICED, @BST_PT, @BST_ENTRAVIGOR, dbo.BOM_STRUCT.BST_PESO_KG, isnull((SELECT MA_COSTO FROM VMAESTROCOST
				WHERE MA_CODIGO=dbo.BOM_STRUCT.BST_HIJO),0), 'I'
			FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
			                      dbo.CONFIGURATIPO ON dbo.BOM_STRUCT.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
			                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO
			WHERE (dbo.CONFIGURATIPO.CFT_TIPO<>'P' and dbo.CONFIGURATIPO.CFT_TIPO<>'S') and dbo.BOM_STRUCT.BST_TIP_ENS='C'
			GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
			                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
			                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
			                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.BOM_STRUCT.BST_PESO_KG
			HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
			AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
			AND SUM(dbo.BOM_STRUCT.BST_MERMA) >0
			*/


DECLARE @CursorVar CURSOR

SET @CursorVar = CURSOR SCROLL DYNAMIC FOR
SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_INCORPOR) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
                      dbo.BOM_STRUCT.BST_TIP_ENS, 'N' AS BST_TIPODESC, dbo.MAESTRO.MA_PESO_KG
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
WHERE dbo.CONFIGURATIPO.CFT_TIPO='P' OR dbo.CONFIGURATIPO.CFT_TIPO='S'
GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.MAESTRO.MA_PESO_KG
HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
AND SUM(dbo.BOM_STRUCT.BST_INCORPOR) >0
/*UNION
SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_DESP) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
                      dbo.BOM_STRUCT.BST_TIP_ENS, 'D' AS BST_TIPODESC, dbo.BOM_STRUCT.BST_PESO_KG
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
WHERE dbo.CONFIGURATIPO.CFT_TIPO='P' OR dbo.CONFIGURATIPO.CFT_TIPO='S'
GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.BOM_STRUCT.BST_PESO_KG
HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
AND SUM(dbo.BOM_STRUCT.BST_DESP) >0
UNION
SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_MERMA) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
                      dbo.BOM_STRUCT.BST_TIP_ENS, 'M' AS BST_TIPODESC, dbo.BOM_STRUCT.BST_PESO_KG
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
WHERE dbo.CONFIGURATIPO.CFT_TIPO='P' OR dbo.CONFIGURATIPO.CFT_TIPO='S'
GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.BOM_STRUCT.BST_PESO_KG
HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR)
AND SUM(dbo.BOM_STRUCT.BST_MERMA) >0
*/
 OPEN @CursorVar
  FETCH NEXT FROM @CursorVar
	INTO @BST_HIJO1, @BST_INCORPOR, @BST_DISCH, @TI_CODIGO, @ME_CODIGO, 
	@FACTCONV, @BST_PERINI1, @BST_PERFIN, @ME_GEN, @BST_TRANS, @BST_TIPOCOSTO,
	@MA_TIP_ENS, @BST_TIPODESC, @BST_PESO_KG

  WHILE (@@fetch_status = 0) 
  BEGIN  

	set @incorporacionfinal=@BST_INCORPOR* @BST_INCORPOR1


	begin

		if @CF_USATIPOADQUISICION='S'
		begin		

			if @MA_TIP_ENS='F' 
			begin
				exec  SP_FILL_BOM_DESCTEMP1_INV @FED_INDICED, @BST_PT, @BST_HIJO1, @BST_ENTRAVIGOR, @BST_PERINI1, 
				@FED_CANT, @CODIGOFACTURA, @CF_USATIPOADQUISICION, @incorporacionfinal, @CF_NIVELES, @nivelr
			end

			if @MA_TIP_ENS='C' or @MA_TIP_ENS='A' or @MA_TIP_ENS='E' or @MA_TIP_ENS='O' 

			begin
				insert into bom_desctemp(FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_HIJO, BST_INCORPOR, 
				    BST_DISCH, TI_CODIGO, ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
				    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC, BST_PERTENECE,
				    BST_PESO_KG, BST_COSTO, FACT_INV)
				select
				@FED_INDICED, @BST_PT, @BST_ENTRAVIGOR, @BST_HIJO1, @incorporacionfinal, @BST_DISCH, @TI_CODIGO, @ME_CODIGO, 
				@FACTCONV, @BST_PERINI1, @BST_PERFIN, @ME_GEN, @BST_TRANS, @BST_TIPOCOSTO,
				@MA_TIP_ENS, @FED_CANT, @CODIGOFACTURA, 'B'+convert(varchar(5),@nivelr), @BST_TIPODESC, @BST_HIJO, @BST_PESO_KG, isnull((SELECT MA_COSTO FROM VMAESTROCOST
				WHERE MA_CODIGO=@BST_HIJO1),0), 'I'

			end

		end
		else

		begin

			exec  SP_FILL_BOM_DESCTEMP1_INV @FED_INDICED, @BST_PT, @BST_HIJO1, @BST_ENTRAVIGOR, 
			@BST_PERINI1, @FED_CANT, @CODIGOFACTURA, @CF_USATIPOADQUISICION, @incorporacionfinal, @CF_NIVELES, @nivelr
		end

	end

	FETCH NEXT FROM @CursorVar INTO @BST_HIJO1, @BST_INCORPOR, @BST_DISCH, @TI_CODIGO, 			
	@ME_CODIGO, @FACTCONV, @BST_PERINI1, @BST_PERFIN, @ME_GEN, @BST_TRANS, @BST_TIPOCOSTO,
	@MA_TIP_ENS, @BST_TIPODESC, @BST_PESO_KG

END
	CLOSE @CursorVar
	DEALLOCATE @CursorVar















































GO
