SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_IMPGENLISTA_CAMPOS2]  @TABLA varchar(100), @TablaTEMPIMPORT1 varchar(100), @ESPECIFICACION varchar(5),@CAMPOS varchar(4096)  OUTPUT, @CAMPOSINSERT varchar(4096) OUTPUT, @LOCALESINSERT varchar(4096) OUTPUT,  @LOCALES varchar(4096) OUTPUT,@EXTERNOS varchar(4096) OUTPUT,@ARCHIVO varchar(4096) OUTPUT    as

SET NOCOUNT ON 
DECLARE @temp_str varchar(100),@TABLA_TEMP varchar(100),@campo_str varchar(100)

SELECT @CAMPOS='',@LOCALES='',@EXTERNOS='',@CAMPOSINSERT='',@LOCALESINSERT='',@ARCHIVO = ''


DECLARE CUR_CAMPOS CURSOR FOR

	SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TablaTEMPIMPORT1
	AND TABLE_SCHEMA='DBO'
	AND CHARINDEX('#',COLUMN_NAME) <> 0 AND CHARINDEX(@TABLA,SUBSTRING(COLUMN_NAME,1,CHARINDEX('#',COLUMN_NAME)))>0
OPEN CUR_CAMPOS
FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
WHILE (@@FETCH_STATUS = 0) 
BEGIN

	SELECT @TABLA_TEMP=REPLACE(SUBSTRING (@temp_str,1,CHARINDEX('#',@temp_str)-1),@ESPECIFICACION,'')		
	IF @TABLA = @TABLA_TEMP
	BEGIN
		SELECT @campo_str=SUBSTRING (@temp_str,CHARINDEX('#',@temp_str)+1,LEN(@temp_str))
		IF @CAMPOS <> ''
			SELECT @CAMPOS = @CAMPOS+','+@temp_str+' ', @LOCALES = @LOCALES+',@'+REPLACE(@temp_str,@ESPECIFICACION+'#','#')+' '
		ELSE
			SELECT @CAMPOS = @temp_str+' ', @LOCALES = '@'+REPLACE(@temp_str,@ESPECIFICACION+'#','#')+' '
		 IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TABLA AND
	                                              COLUMN_NAME=@campo_str)
		BEGIN
			IF @CAMPOSINSERT<>'' 
				SELECT @CAMPOSINSERT=@CAMPOSINSERT+','+@campo_str+' ', @LOCALESINSERT = @LOCALESINSERT+',@'+REPLACE(@temp_str,@ESPECIFICACION+'#','#')+' '
			ELSE
				SELECT @CAMPOSINSERT=@campo_str+' ', @LOCALESINSERT = '@'+REPLACE(@temp_str,@ESPECIFICACION+'#','#')+' '
		END
	END	
	FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
END
CLOSE CUR_CAMPOS
DEALLOCATE CUR_CAMPOS

DECLARE CUR_CAMPOS CURSOR FOR
	SELECT IMF_FIELDNAME   FROM IMPORTFIELDS WHERE IMF_SELECTMASTER <>''  AND 
	IMF_TABLENAME=@TABLA 
	AND (IMF_TABLENAME+@ESPECIFICACION+'#'+IMF_FIELDNAME) NOT IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TablaTEMPIMPORT1
	AND CHARINDEX('#',COLUMN_NAME) <> 0)
	ORDER BY IMF_ORDENSELECTMASTER
OPEN CUR_CAMPOS
FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
WHILE (@@FETCH_STATUS = 0) 
BEGIN
	IF @EXTERNOS <> ''
		SELECT @EXTERNOS = @EXTERNOS+','+@temp_str+' '
	ELSE
   		SELECT @EXTERNOS = @temp_str+' '

	
	FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
END
CLOSE CUR_CAMPOS
DEALLOCATE CUR_CAMPOS



DECLARE CUR_CAMPOS CURSOR FOR
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TablaTEMPIMPORT1
AND TABLE_SCHEMA='DBO'
AND CHARINDEX('#',COLUMN_NAME) = 0
OPEN CUR_CAMPOS
FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
WHILE (@@FETCH_STATUS = 0) 
BEGIN
	
	IF @ARCHIVO<>'' 
		SELECT @ARCHIVO=@ARCHIVO+',@'+@temp_str+' '
	ELSE
		SELECT @ARCHIVO='@'+@temp_str+' '
	
	FETCH NEXT FROM CUR_CAMPOS INTO @temp_str
END
CLOSE CUR_CAMPOS
DEALLOCATE CUR_CAMPOS


GO
