SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[CopiaPermisos] (@BDOrigen varchar(50), @BDDestino varchar(50))    as


		exec CopiaFracciones @BDOrigen, @BDDestino 
	
	/*=== categorias para permiso ===*/
	exec('insert into CATEGPERMISO (CPE_CORTO, CPE_DESC, CPE_COSTO, AR_CODIGO, ME_CODIGO, SE_CODIGO, TI_CODIGO, CPE_CAS_NUM, IDE_CODIGO, 
	                      CPE_APLICAALMACEN)
	
		SELECT     CPE_CORTO, CPE_DESC, CPE_COSTO, AR_CODIGO, ME_CODIGO, SE_CODIGO, TI_CODIGO, CPE_CAS_NUM, IDE_CODIGO, 
		                      CPE_APLICAALMACEN
		FROM         '+@BDOrigen+'.DBO.CATEGPERMISO
		WHERE CPE_CORTO NOT IN (SELECT CATEGPERMISO1.CPE_CORTO FROM CATEGPERMISO CATEGPERMISO1)')
	
		
	/*== caratula permiso == */
	
		IF  NOT EXISTS (SELECT name 
			   FROM  [tempdb].dbo.sysobjects 
			   WHERE  (name = '##PERMISO' )
			   AND 	 ( type = 'U'))
		begin
			CREATE TABLE [##PERMISO] (
				[PE_CODIGO] [int] IDENTITY (1, 1) NOT NULL ,
				[PE_PERMISO] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
				[PE_COMPLE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_FOLIO] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
				[PE_FECHA] [smalldatetime] NOT NULL ,
				[PE_PRODUC] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PERMISO_PE_PRODUC] DEFAULT (''),
				[PE_TIPO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
				[PE_ORIGEN] [int] NULL ,
				[TC_CANT] [decimal](38, 6) NULL ,
				[AD_CODIGO] [int] NULL ,
				[AD_ALTERNA] [int] NULL ,
				[CL_CODIGO] [int] NOT NULL CONSTRAINT [DF_PERMISO_CL_CODIGO] DEFAULT (1),
				[DI_CODIGO] [int] NULL ,
				[PE_APROBADO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PERMISO_PE_APROBADO] DEFAULT ('S'),
				[US_CODIGO] [smallint] NULL ,
				[IDE_CODIGO] [smallint] NULL ,
				[PE_FECHAVENC] [datetime] NULL ,
				[PE_FIRMAELEC] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_ANIO] [smallint] NULL ,
				[PE_REGIMEN] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_PAISESIMP] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_PERIODOCONS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_IDENTMCIA] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_IDENTMCIAOTRO] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_USOMCIA] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_DESCMCIA] [varchar] (1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[AR_CODIGO] [int] NULL ,
				[PE_CONSUMOMCIA] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_OBSERVACIONES] [varchar] (1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_DATOSCOMPL] [varchar] (1100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
				[PE_CANT] [decimal](38, 6) NOT NULL CONSTRAINT [DF_PERMISO_PE_CANT] DEFAULT (0),
				[PE_COSTOT] [decimal](38, 6) NOT NULL CONSTRAINT [DF_PERMISO_PE_COSTOT] DEFAULT (0),
				[PE_SALDO] [decimal](38, 6) NOT NULL CONSTRAINT [DF_PERMISO_PE_SALDO] DEFAULT (0),
				[PE_SALDOCOSTOT] [decimal](38, 6) NOT NULL CONSTRAINT [DF_PERMISO_PE_SALDOCOSTOT] DEFAULT (0),
				[PE_ENUSO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PERMISO_PE_ENUSO] DEFAULT ('N'),
				[PE_ENUSOCOSTOT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PERMISO_PE_ENUSOCOSTOT] DEFAULT ('N'),
				[PE_ESTATUS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PERMISO_PE_ESTATUS] DEFAULT ('A'),
				CONSTRAINT [PK_PERMISO] PRIMARY KEY  NONCLUSTERED 
				(
					[PE_PERMISO],
					[PE_FOLIO]
				)  ON [PRIMARY] ,
				CONSTRAINT [IX_PERMISO] UNIQUE  NONCLUSTERED 
				(
					[PE_CODIGO]
				)  ON [PRIMARY] 
			) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
		end
	
	DECLARE @MAXIMO INT
	
	SELECT @MAXIMO=ISNULL(MAX(PE_CODIGO),0)+1 FROM PERMISO
	
	
	DBCC CHECKIDENT ([##PERMISO], RESEED, @MAXIMO)
	
	EXEC('INSERT INTO ##PERMISO(PE_PERMISO, PE_COMPLE, PE_FOLIO, PE_FECHA, PE_PRODUC, PE_TIPO, PE_ORIGEN, TC_CANT, AD_CODIGO, AD_ALTERNA, 
	                      CL_CODIGO, DI_CODIGO, PE_APROBADO, US_CODIGO, IDE_CODIGO, PE_FECHAVENC, PE_FIRMAELEC, PE_ANIO, PE_REGIMEN, PE_PAISESIMP, 
	                      PE_PERIODOCONS, PE_IDENTMCIA, PE_IDENTMCIAOTRO, PE_USOMCIA, PE_DESCMCIA, AR_CODIGO, PE_CONSUMOMCIA, PE_OBSERVACIONES, 
	                      PE_DATOSCOMPL, PE_CANT, PE_COSTOT, PE_SALDO, PE_SALDOCOSTOT, PE_ENUSO, PE_ENUSOCOSTOT, PE_ESTATUS)
	
	
	SELECT     PE_PERMISO, PE_COMPLE, PE_FOLIO, PE_FECHA, PE_PRODUC, PE_TIPO, PE_ORIGEN, TC_CANT, AD_CODIGO, AD_ALTERNA, 
	                      CL_CODIGO, DI_CODIGO, PE_APROBADO, US_CODIGO, IDE_CODIGO, PE_FECHAVENC, PE_FIRMAELEC, PE_ANIO, PE_REGIMEN, PE_PAISESIMP, 
	                      PE_PERIODOCONS, PE_IDENTMCIA, PE_IDENTMCIAOTRO, PE_USOMCIA, PE_DESCMCIA, AR_CODIGO, PE_CONSUMOMCIA, PE_OBSERVACIONES, 
	                      PE_DATOSCOMPL, PE_CANT, PE_COSTOT, PE_SALDO, PE_SALDOCOSTOT, PE_ENUSO, PE_ENUSOCOSTOT, PE_ESTATUS
	FROM         '+@BDOrigen+'.DBO.PERMISO
	WHERE PE_PERMISO+''&''+PE_FOLIO not in (SELECT PE_PERMISO+''&''+PE_FOLIO FROM PERMISO)')
	
	INSERT INTO PERMISO(PE_CODIGO, PE_PERMISO, PE_COMPLE, PE_FOLIO, PE_FECHA, PE_PRODUC, PE_TIPO, PE_ORIGEN, TC_CANT, AD_CODIGO, AD_ALTERNA, 
	                      CL_CODIGO, DI_CODIGO, PE_APROBADO, US_CODIGO, IDE_CODIGO, PE_FECHAVENC, PE_FIRMAELEC, PE_ANIO, PE_REGIMEN, PE_PAISESIMP, 
	                      PE_PERIODOCONS, PE_IDENTMCIA, PE_IDENTMCIAOTRO, PE_USOMCIA, PE_DESCMCIA, AR_CODIGO, PE_CONSUMOMCIA, PE_OBSERVACIONES, 
	                      PE_DATOSCOMPL, PE_CANT, PE_COSTOT, PE_SALDO, PE_SALDOCOSTOT, PE_ENUSO, PE_ENUSOCOSTOT, PE_ESTATUS)
	
	SELECT PE_CODIGO, PE_PERMISO, PE_COMPLE, PE_FOLIO, PE_FECHA, PE_PRODUC, PE_TIPO, PE_ORIGEN, TC_CANT, AD_CODIGO, AD_ALTERNA, 
	                      CL_CODIGO, DI_CODIGO, PE_APROBADO, US_CODIGO, IDE_CODIGO, PE_FECHAVENC, PE_FIRMAELEC, PE_ANIO, PE_REGIMEN, PE_PAISESIMP, 
	                      PE_PERIODOCONS, PE_IDENTMCIA, PE_IDENTMCIAOTRO, PE_USOMCIA, PE_DESCMCIA, AR_CODIGO, PE_CONSUMOMCIA, PE_OBSERVACIONES, 
	                      PE_DATOSCOMPL, PE_CANT, PE_COSTOT, PE_SALDO, PE_SALDOCOSTOT, PE_ENUSO, PE_ENUSOCOSTOT, PE_ESTATUS
	FROM ##PERMISO
	





	update consecutivo
	set cv_codigo =  isnull((select max(PE_CODIGO) from PERMISO),0) + 1
	where cv_tipo = 'PE'

/*== permiso detalle ==*/

	IF  NOT EXISTS (SELECT name 
		   FROM  [tempdb].dbo.sysobjects 
		   WHERE  (name = '##PERMISODET' )
		   AND 	 ( type = 'U'))
	begin
		CREATE TABLE [##PERMISODET] (
			[PED_INDICED] [int] IDENTITY (1, 1) NOT NULL ,
			[PE_CODIGO] [int] NOT NULL ,
			[PED_REGISTROTIPO] [smallint] NULL ,
			[MA_GENERICO] [int] NOT NULL ,
			[MA_NOPARTE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PERMISODET_MA_NOPARTE] DEFAULT (''),
			[PED_OBSERVA] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[PED_NOMBRE] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[TI_CODIGO] [smallint] NULL ,
			[ME_COM] [int] NULL ,
			[AR_IMPMX] [int] NULL ,
			[AR_EXPMX] [int] NULL ,
			[PED_ID_SUBORD] [int] NOT NULL CONSTRAINT [DF_PERMISODET_PED_ID_SUBORD] DEFAULT (0),
			[PED_CONSECUTIVO] [int] NULL ,
			[PED_CANT] [decimal](38, 6) NOT NULL CONSTRAINT [DF_PERMISODET_PED_CANT] DEFAULT (0),
			[SE_CODIGO] [int] NULL ,
			[PED_COSTO] [decimal](38, 6) NULL ,
			[PED_COSTOT] [decimal](38, 6) NULL ,
			[PED_ENUSO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PERMISODET_PED_ENUSO] DEFAULT ('N'),
			[PED_SALDO] [decimal](38, 6) NOT NULL CONSTRAINT [DF_PERMISODET_PED_SALDO] DEFAULT (0),
			[PED_ENUSOCOSTOT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_PERMISODET_PED_ENUSOCOSTOT] DEFAULT ('N'),
			[PED_SALDOCOSTOT] [decimal](38, 6) NOT NULL CONSTRAINT [DF_PERMISODET_PED_SALDOCOSTOT] DEFAULT (0),
			[PED_CAS_NUM] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
			[PA_CODIGO] [int] NULL ,
			/*CONSTRAINT [PK_PERMISODET] PRIMARY KEY  NONCLUSTERED 
			(
				[PE_CODIGO],
				[MA_GENERICO],
				[PED_ID_SUBORD]
			)  ON [PRIMARY] ,*/
			CONSTRAINT [IX_PERMISODET] UNIQUE  NONCLUSTERED 
			(
				[PED_INDICED]
			)  ON [PRIMARY] 
		) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
		
	end		


	EXEC('DELETE FROM PERMISODET
		WHERE PE_CODIGO IN
	(SELECT     PERMISO_1.PE_CODIGO
	FROM         '+@BDOrigen+'.DBO.PERMISO PERMISOOrig INNER JOIN
	                      PERMISO PERMISO_1 ON PERMISOOrig.PE_PERMISO = PERMISO_1.PE_PERMISO AND PERMISOOrig.PE_FOLIO = PERMISO_1.PE_FOLIO)')

	
	
	exec('insert into ##PERMISODET(PE_CODIGO, MA_GENERICO, MA_NOPARTE, PED_OBSERVA, PED_NOMBRE, 
	                      TI_CODIGO, ME_COM, AR_IMPMX, AR_EXPMX, PED_ID_SUBORD, 
	                      PED_CONSECUTIVO, PED_CANT, SE_CODIGO, PED_COSTO, PED_COSTOT, 
	                      PED_ENUSO, PED_SALDO, PED_ENUSOCOSTOT, PED_SALDOCOSTOT, 
	                      PED_CAS_NUM, PA_CODIGO, PED_REGISTROTIPO)
	
	SELECT     PERMISO_1.PE_CODIGO, CATEGPERMISO_1.CPE_CODIGO, PERMISODETOrig.MA_NOPARTE, PERMISODETOrig.PED_OBSERVA, PERMISODETOrig.PED_NOMBRE, 
	                      PERMISODETOrig.TI_CODIGO, PERMISODETOrig.ME_COM, ARANCEL_1.AR_CODIGO, ARANCEL_3.AR_CODIGO, PERMISODETOrig.PED_ID_SUBORD, 
	                      PERMISODETOrig.PED_CONSECUTIVO, PERMISODETOrig.PED_CANT, PERMISODETOrig.SE_CODIGO, PERMISODETOrig.PED_COSTO, PERMISODETOrig.PED_COSTOT, 
	                      PERMISODETOrig.PED_ENUSO, PERMISODETOrig.PED_SALDO, PERMISODETOrig.PED_ENUSOCOSTOT, PERMISODETOrig.PED_SALDOCOSTOT, 
	                      PERMISODETOrig.PED_CAS_NUM, PERMISODETOrig.PA_CODIGO, PERMISODETOrig.PED_REGISTROTIPO
	FROM         '+@BDOrigen+'.DBO.PERMISODET PERMISODETOrig INNER JOIN
	                      '+@BDOrigen+'.DBO.PERMISO PERMISOOrig ON PERMISODETOrig.PE_CODIGO = PERMISOOrig.PE_CODIGO INNER JOIN
	                      PERMISO PERMISO_1 ON PERMISOOrig.PE_PERMISO = PERMISO_1.PE_PERMISO AND PERMISOOrig.PE_FOLIO = PERMISO_1.PE_FOLIO INNER JOIN
	                      '+@BDOrigen+'.DBO.CATEGPERMISO CATEGPERMISOOrig ON PERMISODETOrig.MA_GENERICO = CATEGPERMISOOrig.CPE_CODIGO INNER JOIN
	                      CATEGPERMISO CATEGPERMISO_1 ON CATEGPERMISOOrig.CPE_CORTO = CATEGPERMISO_1.CPE_CORTO  LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCELOrig ON PERMISODETOrig.AR_IMPMX = ARANCELOrig.AR_CODIGO  LEFT OUTER JOIN
	                      ARANCEL ARANCEL_1 ON ARANCELOrig.AR_FRACCION = ARANCEL_1.AR_FRACCION AND ARANCELOrig.PA_CODIGO = ARANCEL_1.PA_CODIGO   LEFT OUTER JOIN
	                      '+@BDOrigen+'.DBO.ARANCEL ARANCEL_2 ON PERMISODETOrig.AR_EXPMX = ARANCEL_2.AR_CODIGO  LEFT OUTER JOIN
	                      ARANCEL ARANCEL_3 ON ARANCEL_2.AR_FRACCION = ARANCEL_3.AR_FRACCION AND ARANCEL_2.PA_CODIGO = ARANCEL_3.PA_CODIGO
	')
	
	
		INSERT INTO PERMISODET(PED_INDICED, PE_CODIGO, MA_GENERICO, MA_NOPARTE,  PED_NOMBRE, 
	                      TI_CODIGO, ME_COM, AR_IMPMX, AR_EXPMX, PED_ID_SUBORD, 
	                      PED_CONSECUTIVO, PED_CANT, SE_CODIGO, PED_COSTO, PED_COSTOT, 
	                      PED_ENUSO, PED_SALDO, PED_ENUSOCOSTOT, PED_SALDOCOSTOT, 
	                      PED_CAS_NUM, PA_CODIGO, PED_REGISTROTIPO)


	
		SELECT MAX(PED_INDICED), PE_CODIGO, MA_GENERICO, MA_NOPARTE, PED_NOMBRE, 
	                      TI_CODIGO, ME_COM, AR_IMPMX, AR_EXPMX, PED_ID_SUBORD, 
	                      PED_CONSECUTIVO, PED_CANT, SE_CODIGO, PED_COSTO, PED_COSTOT, 
	                      PED_ENUSO, PED_SALDO, PED_ENUSOCOSTOT, PED_SALDOCOSTOT, 
	                      PED_CAS_NUM, PA_CODIGO, PED_REGISTROTIPO
		FROM ##PERMISODET
		GROUP BY PE_CODIGO, MA_GENERICO, MA_NOPARTE, PED_NOMBRE, 
	                      TI_CODIGO, ME_COM, AR_IMPMX, AR_EXPMX, PED_ID_SUBORD, 
	                      PED_CONSECUTIVO, PED_CANT, SE_CODIGO, PED_COSTO, PED_COSTOT, 
	                      PED_ENUSO, PED_SALDO, PED_ENUSOCOSTOT, PED_SALDOCOSTOT, 
	                      PED_CAS_NUM, PA_CODIGO, PED_REGISTROTIPO




	update consecutivo
	set cv_codigo =  isnull((select max(PED_INDICED) from PERMISODET),0) + 1
	where cv_tipo = 'PED'

drop table ##PERMISO
drop table ##PERMISODET

GO
