SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CODBARRAS] (@CODIGO VARCHAR(20), @ARANCEL INT, @INICIAL VARCHAR(20), @FINAL VARCHAR(20))   as

SET NOCOUNT ON 

BEGIN
	UPDATE ARANCEL SET RA_CODIGO = @CODIGO
	WHERE AR_FRACCION >= @INICIAL 
	AND AR_FRACCION <= @FINAL
	AND AR_CODIGO <> @ARANCEL
	AND AR_TIPO = 'I'
	AND PA_CODIGO NOT IN (SELECT CF_PAIS_MX FROM CONFIGURACION)
END


GO
