SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_COPIABOM] @DESTINO INT, @ORIGEN INT   as

SET NOCOUNT ON 
	-- INSERTAMOS LOS DE BOM_STRUCT
	EXEC SP_COPIABOMSTRUCT   @ORIGEN, @DESTINO



GO
