SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


/* actualiza los costos de CLASIFICATLC */
CREATE PROCEDURE [dbo].[SP_ACTUALIZATIPOMATORIG] (@BSTPT INT, @NFT_CODIGO INT)   as

SET NOCOUNT ON 

DECLARE @CLT_CODIGO INT, @BST_TIPOCOSTO CHAR(1), @COSTO decimal(38,6), @COS_UNI decimal(38,6), @SPI_CODIGO INT, @NFT_FECHA DATETIME,
@spi_codigo2 int

	SELECT @spi_codigo2=SPI_CODIGO, @NFT_FECHA=NFT_FECHA FROM NAFTA WHERE NFT_CODIGO=@NFT_CODIGO



	IF (SELECT SPI_CODIGO FROM SPI WHERE SPI_CLAVE='MX' )= @spi_codigo2
	SELECT @spi_codigo= SPI_CODIGO FROM SPI WHERE SPI_CLAVE='NAFTA'
	ELSE
	SET @spi_codigo=@spi_codigo2


	exec SP_CreaVMAESTROCOST1tlc @NFT_FECHA


	

		-- empaque
		UPDATE dbo.CLASIFICATLC
		SET BST_EMPAQUE = isnull(round(dbo.CLASIFICATLC.BST_INCORPOR * VMAESTROCOSTtlc.MA_COSTO/isnull(VMAESTROCOSTtlc.EQ_GEN,1)*isnull(dbo.CLASIFICATLC.FACTCONV,1),6),0), 
		BST_TIPOORIG = 'E' 
		FROM    dbo.CLASIFICATLC INNER JOIN
		        VMAESTROCOSTtlc ON dbo.CLASIFICATLC.BST_HIJO = VMAESTROCOSTtlc.MA_CODIGO 
		WHERE (dbo.CLASIFICATLC.NFT_CODIGO = @NFT_CODIGO) AND BST_TIPOCOSTO in ('E', 'F') 


		-- materia prima originaria
		UPDATE dbo.CLASIFICATLC
		SET BST_MATORIG = isnull(round(dbo.CLASIFICATLC.BST_INCORPOR * VMAESTROCOSTtlc.MA_COSTO/isnull(VMAESTROCOSTtlc.EQ_GEN,1)*isnull(dbo.CLASIFICATLC.FACTCONV,1),6),0),
		BST_TIPOORIG = 'O' 
		FROM    dbo.CLASIFICATLC INNER JOIN
		        VMAESTROCOSTtlc ON dbo.CLASIFICATLC.BST_HIJO = VMAESTROCOSTtlc.MA_CODIGO 
		WHERE (dbo.CLASIFICATLC.NFT_CODIGO = @NFT_CODIGO) AND BST_TIPOCOSTO in ('C', 'D', 'N', 'P')

	
		-- materia prima no originaria
		UPDATE dbo.CLASIFICATLC
		SET BST_MATNOORIG = isnull(round(dbo.CLASIFICATLC.BST_INCORPOR * VMAESTROCOSTtlc.MA_COSTO/isnull(VMAESTROCOSTtlc.EQ_GEN,1)*isnull(dbo.CLASIFICATLC.FACTCONV,1),6),0),
		BST_TIPOORIG = 'N' 
		FROM    dbo.CLASIFICATLC INNER JOIN
		        VMAESTROCOSTtlc ON dbo.CLASIFICATLC.BST_HIJO = VMAESTROCOSTtlc.MA_CODIGO 
		WHERE (dbo.CLASIFICATLC.NFT_CODIGO = @NFT_CODIGO) AND BST_TIPOCOSTO in ('A', 'B')


		UPDATE dbo.CLASIFICATLC
		SET BST_COS_UNI = round(VMAESTROCOSTtlc.MA_COSTO/isnull(VMAESTROCOSTtlc.EQ_GEN,1)*isnull(dbo.CLASIFICATLC.FACTCONV,1),6)
		FROM    dbo.CLASIFICATLC INNER JOIN
		        VMAESTROCOSTtlc ON dbo.CLASIFICATLC.BST_HIJO = VMAESTROCOSTtlc.MA_CODIGO 
		WHERE (dbo.CLASIFICATLC.NFT_CODIGO = @NFT_CODIGO) 
		AND dbo.CLASIFICATLC.BST_TIPOCOSTO<>'S'
	
	



		UPDATE dbo.CLASIFICATLC
		SET BST_MATORIG = 
			isnull((SELECT isnull(round(CTLC.BST_INCORPOR * VMAESTROCOSTtlc.MA_COSTO/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(CTLC.FACTCONV,1),6),0)
			FROM    dbo.CLASIFICATLC CTLC LEFT OUTER JOIN
			              VMAESTROCOSTtlc ON CTLC.BST_HIJO = VMAESTROCOSTtlc.MA_CODIGO LEFT OUTER JOIN
			              dbo.MAESTRO ON CTLC.BST_HIJO = dbo.MAESTRO.MA_CODIGO 
			WHERE     VMAESTROCOSTtlc.SPI_CODIGO=@SPI_CODIGO AND CTLC.CLT_CODIGO= dbo.CLASIFICATLC.CLT_CODIGO),0),

		          BST_TIPOORIG = 'O', 

		          BST_COS_UNI = 
			isnull((SELECT round(VMAESTROCOSTtlc.MA_COSTO/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(dbo.CLASIFICATLC.FACTCONV,1),6)
			FROM    dbo.CLASIFICATLC CTLC LEFT OUTER JOIN
			              VMAESTROCOSTtlc ON CTLC.BST_HIJO = VMAESTROCOSTtlc.MA_CODIGO LEFT OUTER JOIN
			              dbo.MAESTRO ON CTLC.BST_HIJO = dbo.MAESTRO.MA_CODIGO 
			WHERE     VMAESTROCOSTtlc.SPI_CODIGO=@SPI_CODIGO AND CTLC.CLT_CODIGO= dbo.CLASIFICATLC.CLT_CODIGO),0)
		WHERE  (dbo.CLASIFICATLC.NFT_CODIGO = @NFT_CODIGO)  AND BST_TIPOCOSTO='S' and BST_TRANS='S'



		-- si para los subensambles no existe el costo segun el tratado toma el declarado en nafta.
		UPDATE dbo.CLASIFICATLC
		SET BST_MATORIG = 
			isnull((SELECT isnull(round(CTLC.BST_INCORPOR * VMAESTROCOSTtlc.MA_COSTO/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(CTLC.FACTCONV,1),6),0)
			FROM    dbo.CLASIFICATLC CTLC LEFT OUTER JOIN
			              VMAESTROCOSTtlc ON CTLC.BST_HIJO = VMAESTROCOSTtlc.MA_CODIGO LEFT OUTER JOIN
			              dbo.MAESTRO ON CTLC.BST_HIJO = dbo.MAESTRO.MA_CODIGO 
			WHERE     VMAESTROCOSTtlc.SPI_CODIGO=22 AND CTLC.CLT_CODIGO= dbo.CLASIFICATLC.CLT_CODIGO),0),

		          BST_TIPOORIG = 'O', 

		          BST_COS_UNI = 
			isnull((SELECT round(VMAESTROCOSTtlc.MA_COSTO/isnull(dbo.MAESTRO.EQ_GEN,1)*isnull(dbo.CLASIFICATLC.FACTCONV,1),6)
			FROM    dbo.CLASIFICATLC CTLC LEFT OUTER JOIN
			              VMAESTROCOSTtlc ON CTLC.BST_HIJO = VMAESTROCOSTtlc.MA_CODIGO LEFT OUTER JOIN
			              dbo.MAESTRO ON CTLC.BST_HIJO = dbo.MAESTRO.MA_CODIGO 
			WHERE     VMAESTROCOSTtlc.SPI_CODIGO=22 AND CTLC.CLT_CODIGO= dbo.CLASIFICATLC.CLT_CODIGO),0)

		WHERE  (dbo.CLASIFICATLC.NFT_CODIGO = @NFT_CODIGO)  AND BST_TIPOCOSTO='S' and BST_TRANS='S' and isnull(BST_COS_UNI,0)=0 



	UPDATE dbo.CLASIFICATLC
	SET BST_EMPAQUE = 0
	WHERE BST_EMPAQUE IS NULL
	AND NFT_CODIGO=@NFT_CODIGO


	UPDATE dbo.CLASIFICATLC
	SET BST_MATORIG = 0 
	WHERE BST_MATORIG IS NULL
	AND NFT_CODIGO=@NFT_CODIGO


	UPDATE dbo.CLASIFICATLC
	SET BST_MATNOORIG = 0
	WHERE BST_MATNOORIG IS NULL
	AND NFT_CODIGO=@NFT_CODIGO


GO
