SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




























CREATE PROCEDURE [dbo].[SP_IMPEXCELINVFIS] @Codigo int   as

SET NOCOUNT ON 
DECLARE @CONSECUTIVO INTEGER, @NOPARTE varchar(30), @CANTIDAD decimal(38,6)



DELETE FROM IMPORTLOG WHERE IML_CBFORMA=105

if (select count(*) from IMPORTLOG)=0
DBCC CHECKIDENT (IMPORTLOG, RESEED, 0) WITH NO_INFOMSGS

if exists(SELECT dbo.IMPEXCELFACTIMP.NOPARTE
	FROM         dbo.MAESTRO RIGHT OUTER JOIN
	                      dbo.IMPEXCELFACTIMP ON dbo.MAESTRO.MA_NOPARTE = dbo.IMPEXCELFACTIMP.NOPARTE
	WHERE     (dbo.MAESTRO.MA_NOPARTE IS NULL))

	INSERT INTO IMPORTLOG (IML_MENSAJE, IML_CBFORMA) 
	SELECT     'NO SE PUEDE IMPORTAR NO. PARTE : ' +dbo.IMPEXCELFACTIMP.NOPARTE +' POR QUE NO EXISTE EN EL CAT. MAESTRO', 105
	FROM         dbo.MAESTRO RIGHT OUTER JOIN
	                      dbo.IMPEXCELFACTIMP ON dbo.MAESTRO.MA_NOPARTE = dbo.IMPEXCELFACTIMP.NOPARTE
	WHERE     (dbo.MAESTRO.MA_NOPARTE IS NULL) 



-- se actualiza el costo en caso de que venga nulo o igual a cero pero solo de los comprados-fisicos
UPDATE dbo.IMPEXCELFACTIMP
SET     dbo.IMPEXCELFACTIMP.COSTO= ISNULL(dbo.MAESTROCOST.MA_COSTO, 0)
FROM         dbo.IMPEXCELFACTIMP INNER JOIN
                      dbo.MAESTRO ON dbo.IMPEXCELFACTIMP.NOPARTE = dbo.MAESTRO.MA_NOPARTE LEFT OUTER JOIN
                      dbo.MAESTROCOST ON dbo.MAESTRO.MA_CODIGO = dbo.MAESTROCOST.MA_CODIGO
WHERE dbo.MAESTROCOST.SPI_CODIGO=22 AND dbo.MAESTROCOST.MA_PERINI<=getdate() AND dbo.MAESTROCOST.MA_PERFIN>=getdate()
AND dbo.MAESTROCOST.TCO_CODIGO IN (select TCO_COMPRA from configuracion) AND
(dbo.IMPEXCELFACTIMP.COSTO=0 OR dbo.IMPEXCELFACTIMP.COSTO IS NULL)
AND dbo.MAESTRO.MA_TIP_ENS='A'


-- se actualiza el costo en caso de que venga nulo o igual a cero
UPDATE dbo.IMPEXCELFACTIMP
SET     dbo.IMPEXCELFACTIMP.COSTO= ISNULL(dbo.VMAESTROCOST.MA_COSTO, 0)
FROM         dbo.IMPEXCELFACTIMP INNER JOIN
                      dbo.MAESTRO ON dbo.IMPEXCELFACTIMP.NOPARTE = dbo.MAESTRO.MA_NOPARTE LEFT OUTER JOIN
                      dbo.VMAESTROCOST ON dbo.MAESTRO.MA_CODIGO = dbo.VMAESTROCOST.MA_CODIGO
WHERE dbo.VMAESTROCOST.SPI_CODIGO=22 AND
(dbo.IMPEXCELFACTIMP.COSTO=0 OR dbo.IMPEXCELFACTIMP.COSTO IS NULL)


UPDATE dbo.IMPEXCELFACTIMP
SET     dbo.IMPEXCELFACTIMP.COSTO= 0
WHERE dbo.IMPEXCELFACTIMP.COSTO IS NULL


-- se actualiza el peso en caso de que venga nulo o igual a cero
IF (SELECT     CF_PESOS_IMP
	FROM         dbo.CONFIGURACION)='K'
BEGIN
UPDATE dbo.IMPEXCELFACTIMP
SET  dbo.IMPEXCELFACTIMP.PESO = isnull(dbo.MAESTRO.MA_PESO_KG,0)
FROM         dbo.MAESTRO INNER JOIN
                      dbo.IMPEXCELFACTIMP ON dbo.MAESTRO.MA_NOPARTE = dbo.IMPEXCELFACTIMP.NOPARTE
WHERE MA_EST_MAT = 'A' AND MA_NOPARTE=IMPEXCELFACTIMP.NOPARTE AND (PESO IS NULL OR PESO =0.0)
END
ELSE
BEGIN
UPDATE dbo.IMPEXCELFACTIMP
SET  dbo.IMPEXCELFACTIMP.PESO = isnull(dbo.MAESTRO.MA_PESO_LB,0)
FROM         dbo.MAESTRO INNER JOIN
                      dbo.IMPEXCELFACTIMP ON dbo.MAESTRO.MA_NOPARTE = dbo.IMPEXCELFACTIMP.NOPARTE
WHERE MA_EST_MAT = 'A' AND MA_NOPARTE=IMPEXCELFACTIMP.NOPARTE AND (PESO IS NULL OR PESO =0.0)
END



DECLARE CUR_IMPEXCELINVFIS CURSOR FOR
	SELECT NOPARTE,CANTIDAD FROM IMPEXCELFACTIMP
	WHERE NOT (COSTO IS NULL OR PESO IS NULL  OR NOPARTE NOT IN
	(SELECT MA_NOPARTE FROM MAESTRO WHERE MA_INV_GEN = 'I'  
	                                             AND MA_EST_MAT = 'A' AND MA_NOPARTE=NOPARTE) )
OPEN CUR_IMPEXCELINVFIS
FETCH NEXT FROM CUR_IMPEXCELINVFIS INTO @NOPARTE,@CANTIDAD
WHILE (@@FETCH_STATUS = 0) 
BEGIN
	EXEC SP_GETCONSECUTIVO @TIPO='IVFD',@VALUE=@CONSECUTIVO OUTPUT
	INSERT INTO  INVENTARIOFISDET(IVFD_INDICED, IVF_CODIGO, IVFD_NOPARTE, MA_CODIGO,  IVFD_NOMBRE, IVFD_NAME, IVFD_CANT, IVFD_CANT_SINTRANS, ME_CODIGO, MA_GENERICO, ME_GENERICO, 
	                      EQ_GENERICO, IVFD_CAN_GEN, TI_CODIGO, IVFD_CONCILIADO)

                SELECT @CONSECUTIVO, @Codigo, @NOPARTE, MA_CODIGO, MA_NOMBRE, MA_NAME, @CANTIDAD, @CANTIDAD, ME_COM, MA_GENERICO, isnull((SELECT ME_COM FROM VMAESTRO_GENERICO AS MAESTRO1 WHERE MA_CODIGO=MA_GENERICO),me_com),
			EQ_GEN, @CANTIDAD*EQ_GEN, TI_CODIGO, 'N'
		FROM MAESTRO WHERE MA_INV_GEN = 'I'  
                                     AND MA_EST_MAT = 'A' AND MA_NOPARTE=@NOPARTE
	
             FETCH NEXT FROM CUR_IMPEXCELINVFIS INTO @NOPARTE,@CANTIDAD
END
CLOSE CUR_IMPEXCELINVFIS
DEALLOCATE CUR_IMPEXCELINVFIS



	TRUNCATE TABLE IMPEXCELFACTIMP












GO
