SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_TEMPIMPORT144_7] AS
DECLARE @FACTIMPDET#FID_PES_UNILB float,@FACTIMP#DI_COMP int,@FACTIMP#TF_CODIGO smallint,@FACTIMP#SPI_CODIGO smallint,@FACTIMP#CL_VEND int,@FACTIMP#DI_VEND int,@FACTIMP#CL_EXP int,@FACTIMP#DI_EXP int,@FACTIMP#CP_CODIGO smallint,@FACTIMP#FI_TIPO char,@FACTIMPDET#FID_NOPARTEAUX varchar(8000),@FACTIMPDET#FID_DEF_TIP char,@FACTIMP#PR_CODIGO int,@FACTIMP#DI_PROVEE int,@FACTIMP#TQ_CODIGO smallint,@FACTIMP#CL_PROD int,@FACTIMP#DI_PROD int,@FACTIMP#CL_COMP int,@FACTIMP#FI_FOLIO varchar(8000),@FACTIMP#FI_FECHA datetime,@FACTIMPDET#FID_NOPARTE varchar(8000),@FACTIMPDET#FID_CANT_ST float,@FACTIMPDET#FID_COS_UNI float,@FACTIMPDET#FID_COS_TOT float,@FACTIMPDET#FID_PES_BRULB float,@Cod_3 varchar(8000)
DECLARE @ACTUALIZA bit,@ANEXA bit,@CONSECUTIVO int,@CONSDET int,@CONSANEX int,@CONSCONT int
DECLARE @CAMPOSMASTER varchar(255),@temp_str varchar(20)
SELECT @ACTUALIZA=0
SELECT @ANEXA=1
DELETE FROM REGISTROSIMPORTADOS where RI_USERID = 7
-- Variables para campos de caratula
           DECLARE @FACTIMP#FI_HEADER varchar(8000)
           DECLARE @FACTIMP#FI_FOOTER varchar(8000)
           DECLARE @FACTIMP#FI_DESCRIPTION1 varchar(8000)
           DECLARE @FACTIMP#AG_MEX int
           DECLARE @FACTIMP#AG_USA int
           DECLARE @FACTIMP#CL_DESTINT int
           DECLARE @FACTIMP#DI_DESTINT int
           DECLARE @FACTIMP#CL_DESTFIN int
           DECLARE @FACTIMP#DI_DESTFIN int
           DECLARE @FACTIMP#CL_IMP int
           DECLARE @FACTIMP#DI_IMP int
           DECLARE @FACTIMP#ZO_CODIGO smallint
           DECLARE @FACTIMP#PU_CARGA int
           DECLARE @FACTIMP#PU_SALIDA int
           DECLARE @FACTIMP#PU_ENTRADA int
           DECLARE @FACTIMP#PU_DESTINO int
           DECLARE @FACTIMP#MT_CODIGO smallint
           DECLARE @FACTIMP#CT_CODIGO int
           DECLARE @FACTIMP#FI_TIPOCAMBIO decimal(38,14)
           DECLARE @FACTIMP#MO_CODIGO int
           DECLARE @FACTIMP#IT_CODIGO smallint
           DECLARE @FACTIMP#FI_PINICIAL datetime
           DECLARE @FACTIMP#FI_PFINAL datetime
           DECLARE @FACTIMP#AGT_CODIGO int
-- Variables para campos de detalle
           DECLARE @FACTIMPDET#TCO_CODIGO smallint
           DECLARE @FACTIMPDET#PA_CODIGO int
           DECLARE @FACTIMPDET#SPI_CODIGO smallint
           DECLARE @FACTIMPDET#AR_IMPMX int
           DECLARE @FACTIMPDET#FID_PES_UNI decimal(38,14)
           DECLARE @FACTIMPDET#FID_SEC_IMP smallint
           DECLARE @FACTIMPDET#FID_POR_DEF decimal(38,14)
           DECLARE @FACTIMPDET#AR_EXPFO int
           DECLARE @FACTIMPDET#ME_CODIGO int
           DECLARE @FACTIMPDET#MA_GENERICO int
           DECLARE @FACTIMPDET#PR_CODIGO int
           DECLARE @FACTIMPDET#EQ_GEN decimal(38,14)
           DECLARE @FACTIMPDET#EQ_IMPMX decimal(38,14)
           DECLARE @FACTIMPDET#EQ_EXPFO decimal(38,14)
           DECLARE @FACTIMPDET#TI_CODIGO int
           DECLARE @FACTIMPDET#FID_NOMBRE varchar(8000)
           DECLARE @FACTIMPDET#FID_NAME varchar(8000)
           DECLARE @FACTIMPDET#ME_GEN int
           DECLARE @FACTIMPDET#MA_CODIGO int
           DECLARE @FACTIMPDET#ME_ARIMPMX int
           DECLARE @FACTIMPDET#CS_CODIGO smallint
           DECLARE @FACTIMPDET#EQ_EXPFO2 decimal(38,14)
DECLARE CUR_TEMPIMPORT144_7 CURSOR FOR
SELECT MAX(Cod_3),MAX(FACTIMP7#DI_COMP),MAX(FACTIMP7#TF_CODIGO),MAX(FACTIMP7#SPI_CODIGO),MAX(FACTIMP7#CL_VEND),MAX(FACTIMP7#DI_VEND),MAX(FACTIMP7#CL_EXP),MAX(FACTIMP7#DI_EXP),MAX(FACTIMP7#CP_CODIGO),FACTIMP7#FI_TIPO,MAX(FACTIMP7#PR_CODIGO),MAX(FACTIMP7#DI_PROVEE),MAX(FACTIMP7#TQ_CODIGO),MAX(FACTIMP7#CL_PROD),MAX(FACTIMP7#DI_PROD),MAX(FACTIMP7#CL_COMP),FACTIMP7#FI_FOLIO,MAX(FACTIMP7#FI_FECHA) FROM TEMPIMPORT144_7 WHERE FACTIMP7#FI_FOLIO NOT IN (select factimp.fi_folio from factimp WHERE factimp.fi_estatus in ('A', 'C', 'L') or fi_iniciocruce='S') GROUP BY FACTIMP7#FI_TIPO,FACTIMP7#FI_FOLIO
OPEN CUR_TEMPIMPORT144_7
FETCH NEXT FROM CUR_TEMPIMPORT144_7 INTO @Cod_3 ,@FACTIMP#DI_COMP ,@FACTIMP#TF_CODIGO ,@FACTIMP#SPI_CODIGO ,@FACTIMP#CL_VEND ,@FACTIMP#DI_VEND ,@FACTIMP#CL_EXP ,@FACTIMP#DI_EXP ,@FACTIMP#CP_CODIGO ,@FACTIMP#FI_TIPO ,@FACTIMP#PR_CODIGO ,@FACTIMP#DI_PROVEE ,@FACTIMP#TQ_CODIGO ,@FACTIMP#CL_PROD ,@FACTIMP#DI_PROD ,@FACTIMP#CL_COMP ,@FACTIMP#FI_FOLIO ,@FACTIMP#FI_FECHA 
WHILE (@@FETCH_STATUS = 0)
BEGIN
   IF NOT EXISTS(SELECT FI_CODIGO FROM FACTIMP WHERE FI_FOLIO=@FACTIMP#FI_FOLIO AND FI_TIPO=@FACTIMP#FI_TIPO AND TQ_CODIGO=@FACTIMP#TQ_CODIGO)
  IF @ANEXA=1
  BEGIN
           SELECT @FACTIMP#FI_HEADER=(SELECT CONVERT(VARCHAR(150),FI_HEADER) FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#FI_HEADER IS NULL
                SELECT @FACTIMP#FI_HEADER=''
           SELECT @FACTIMP#FI_FOOTER=(SELECT CONVERT(VARCHAR(150),FI_FOOTER) FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#FI_FOOTER IS NULL
                SELECT @FACTIMP#FI_FOOTER=''
           SELECT @FACTIMP#FI_DESCRIPTION1=(SELECT CONVERT(VARCHAR(30),FI_DESC_GRAL) FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#FI_DESCRIPTION1 IS NULL
                SELECT @FACTIMP#FI_DESCRIPTION1=''
           SELECT @FACTIMP#AG_MEX=(SELECT AG_MEX FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#AG_MEX IS NULL
                SELECT @FACTIMP#AG_MEX=0
           SELECT @FACTIMP#AG_USA=(SELECT AG_USA FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#AG_USA IS NULL
                SELECT @FACTIMP#AG_USA=0
           SELECT @FACTIMP#CL_DESTINT=(SELECT CL_CODIGO FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#CL_DESTINT IS NULL
                SELECT @FACTIMP#CL_DESTINT=-1
           SELECT @FACTIMP#DI_DESTINT=(SELECT DI_INDICE FROM DIR_CLIENTE WHERE DI_FISCAL='S' AND CL_CODIGO =@FACTIMP#CL_DESTINT)
            IF @FACTIMP#DI_DESTINT IS NULL
                SELECT @FACTIMP#DI_DESTINT=0
           SELECT @FACTIMP#CL_DESTFIN=(SELECT CL_CODIGO FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#CL_DESTFIN IS NULL
                SELECT @FACTIMP#CL_DESTFIN=-1
           SELECT @FACTIMP#DI_DESTFIN=(SELECT DI_INDICE FROM DIR_CLIENTE WHERE DI_FISCAL='S' AND CL_CODIGO =@FACTIMP#CL_DESTFIN)
            IF @FACTIMP#DI_DESTFIN IS NULL
                SELECT @FACTIMP#DI_DESTFIN=0
           SELECT @FACTIMP#CL_IMP=(SELECT CL_TRAFICO FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#CL_IMP IS NULL
                SELECT @FACTIMP#CL_IMP=0
           SELECT @FACTIMP#DI_IMP=(SELECT DI_INDICE FROM DIR_CLIENTE WHERE DI_FISCAL='S' AND CL_CODIGO =@FACTIMP#CL_IMP)
            IF @FACTIMP#DI_IMP IS NULL
                SELECT @FACTIMP#DI_IMP=0
           SELECT @FACTIMP#ZO_CODIGO=(SELECT ZO_CODIGO FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#ZO_CODIGO IS NULL
                SELECT @FACTIMP#ZO_CODIGO=0
           SELECT @FACTIMP#PU_CARGA=(SELECT PU_CARGA FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#PU_CARGA IS NULL
                SELECT @FACTIMP#PU_CARGA=0
           SELECT @FACTIMP#PU_SALIDA=(SELECT PU_SALIDA FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#PU_SALIDA IS NULL
                SELECT @FACTIMP#PU_SALIDA=0
           SELECT @FACTIMP#PU_ENTRADA=(SELECT PU_ENTRADA FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#PU_ENTRADA IS NULL
                SELECT @FACTIMP#PU_ENTRADA=0
           SELECT @FACTIMP#PU_DESTINO=(SELECT PU_DESTINO FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#PU_DESTINO IS NULL
                SELECT @FACTIMP#PU_DESTINO=0
           SELECT @FACTIMP#MT_CODIGO=(SELECT MT_CODIGO FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#MT_CODIGO IS NULL
                SELECT @FACTIMP#MT_CODIGO=0
           SELECT @FACTIMP#CT_CODIGO=(SELECT CT_CODIGO FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#CT_CODIGO IS NULL
                SELECT @FACTIMP#CT_CODIGO=0
           SELECT @FACTIMP#FI_TIPOCAMBIO=(SELECT TC_CANT FROM TCAMBIO WHERE TC_FECHA=@FACTIMP#FI_FECHA)
            IF @FACTIMP#FI_TIPOCAMBIO IS NULL
                SELECT @FACTIMP#FI_TIPOCAMBIO=-1
           SELECT @FACTIMP#MO_CODIGO=(SELECT MO_CODIGO FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#MO_CODIGO IS NULL
                SELECT @FACTIMP#MO_CODIGO=0
           SELECT @FACTIMP#IT_CODIGO=(SELECT IT_ENTRADA FROM CLIENTE WHERE CL_EMPRESA='S')
            IF @FACTIMP#IT_CODIGO IS NULL
                SELECT @FACTIMP#IT_CODIGO=0
           SELECT @FACTIMP#FI_PINICIAL=(convert(varchar(10),getdate(),101))
            IF @FACTIMP#FI_PINICIAL IS NULL
                SELECT @FACTIMP#FI_PINICIAL=''
           SELECT @FACTIMP#FI_PFINAL=(convert(varchar(10),getdate(),101))
            IF @FACTIMP#FI_PFINAL IS NULL
                SELECT @FACTIMP#FI_PFINAL=''
           SELECT @FACTIMP#AGT_CODIGO=(SELECT AGT_CODIGO FROM AGENCIAPATENTE WHERE AGT_DEFAULT='S' AND AG_CODIGO IN (SELECT AG_MEX FROM CLIENTE WHERE CL_EMPRESA='S'))
            IF @FACTIMP#AGT_CODIGO IS NULL
                SELECT @FACTIMP#AGT_CODIGO=0
          EXEC SP_GETCONSECUTIVO @TIPO='FI',@VALUE=@CONSECUTIVO OUTPUT
          INSERT INTO FACTIMP (FI_CODIGO,DI_COMP ,TF_CODIGO ,SPI_CODIGO ,CL_VEND ,DI_VEND ,CL_EXP ,DI_EXP ,CP_CODIGO ,FI_TIPO ,PR_CODIGO ,DI_PROVEE ,TQ_CODIGO ,CL_PROD ,DI_PROD ,CL_COMP ,FI_FOLIO ,FI_FECHA ,FI_HEADER ,FI_FOOTER ,FI_DESCRIPTION1 ,AG_MEX ,AG_USA ,CL_DESTINT ,DI_DESTINT ,CL_DESTFIN ,DI_DESTFIN ,CL_IMP ,DI_IMP ,ZO_CODIGO ,PU_CARGA ,PU_SALIDA ,PU_ENTRADA ,PU_DESTINO ,MT_CODIGO ,CT_CODIGO ,FI_TIPOCAMBIO ,MO_CODIGO ,IT_CODIGO ,FI_PINICIAL ,FI_PFINAL ,AGT_CODIGO ) VALUES (@CONSECUTIVO,@FACTIMP#DI_COMP ,@FACTIMP#TF_CODIGO ,@FACTIMP#SPI_CODIGO ,@FACTIMP#CL_VEND ,@FACTIMP#DI_VEND ,@FACTIMP#CL_EXP ,@FACTIMP#DI_EXP ,@FACTIMP#CP_CODIGO ,@FACTIMP#FI_TIPO ,@FACTIMP#PR_CODIGO ,@FACTIMP#DI_PROVEE ,@FACTIMP#TQ_CODIGO ,@FACTIMP#CL_PROD ,@FACTIMP#DI_PROD ,@FACTIMP#CL_COMP ,@FACTIMP#FI_FOLIO ,@FACTIMP#FI_FECHA ,@FACTIMP#FI_HEADER,@FACTIMP#FI_FOOTER,@FACTIMP#FI_DESCRIPTION1,@FACTIMP#AG_MEX,@FACTIMP#AG_USA,@FACTIMP#CL_DESTINT,@FACTIMP#DI_DESTINT,@FACTIMP#CL_DESTFIN,@FACTIMP#DI_DESTFIN,@FACTIMP#CL_IMP,@FACTIMP#DI_IMP,@FACTIMP#ZO_CODIGO,@FACTIMP#PU_CARGA,@FACTIMP#PU_SALIDA,@FACTIMP#PU_ENTRADA,@FACTIMP#PU_DESTINO,@FACTIMP#MT_CODIGO,@FACTIMP#CT_CODIGO,@FACTIMP#FI_TIPOCAMBIO,@FACTIMP#MO_CODIGO,@FACTIMP#IT_CODIGO,@FACTIMP#FI_PINICIAL,@FACTIMP#FI_PFINAL,@FACTIMP#AGT_CODIGO)
               INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO,RI_TIPO,RI_CBFORMA, RI_USERID) VALUES                                               ('FI_FOLIO = '+CONVERT(varchar(100),@FACTIMP#FI_FOLIO)+', '+'FI_FECHA = '+CONVERT(varchar(100),@FACTIMP#FI_FECHA),'I',21,7) 
 if exists (select * from sysobjects where name='sysusrlog44')                 insert into sysusrlog44 (user_id, mov_id, referencia, frmtag, fechahora) values                                                        (7, 1 ,'FI_FOLIO = '+CONVERT(varchar(100),@FACTIMP#FI_FOLIO)+', '+'FI_FECHA = '+CONVERT(varchar(100),@FACTIMP#FI_FECHA),44, getdate()) 
        DECLARE CUR_TEMPIMPORT144_7DET CURSOR FOR
        SELECT MAX(Cod_3),MAX(FACTIMPDET7#FID_PES_UNILB),FACTIMPDET7#FID_NOPARTEAUX,FACTIMPDET7#FID_DEF_TIP,FACTIMPDET7#FID_NOPARTE,SUM(FACTIMPDET7#FID_CANT_ST),FACTIMPDET7#FID_COS_UNI,SUM(FACTIMPDET7#FID_COS_TOT),SUM(FACTIMPDET7#FID_PES_BRULB) FROM TEMPIMPORT144_7  WHERE FACTIMP7#FI_FOLIO=@FACTIMP#FI_FOLIO AND FACTIMP7#FI_TIPO=@FACTIMP#FI_TIPO AND FACTIMP7#TQ_CODIGO=@FACTIMP#TQ_CODIGO GROUP BY FACTIMPDET7#FID_NOPARTEAUX,FACTIMPDET7#FID_DEF_TIP,FACTIMPDET7#FID_NOPARTE,FACTIMPDET7#FID_COS_UNI
        OPEN CUR_TEMPIMPORT144_7DET
                      FETCH NEXT FROM CUR_TEMPIMPORT144_7DET INTO @Cod_3 ,@FACTIMPDET#FID_PES_UNILB ,@FACTIMPDET#FID_NOPARTEAUX ,@FACTIMPDET#FID_DEF_TIP ,@FACTIMPDET#FID_NOPARTE ,@FACTIMPDET#FID_CANT_ST ,@FACTIMPDET#FID_COS_UNI ,@FACTIMPDET#FID_COS_TOT ,@FACTIMPDET#FID_PES_BRULB 
        WHILE (@@FETCH_STATUS = 0)
        BEGIN
           SELECT @FACTIMPDET#TCO_CODIGO=ISNULL((SELECT 'TCO_CODIGO'=CASE WHEN MA_TIP_ENS='C' OR (MA_TIP_ENS='A' AND (SELECT CF_TCOCOMPRAIMP FROM CONFIGURACION)='S') THEN (SELECT TCO_COMPRA FROM CONFIGURACION) ELSE (SELECT TCO_MANUFACTURA FROM CONFIGURACION) END FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),3)
            IF @FACTIMPDET#TCO_CODIGO IS NULL
                SELECT @FACTIMPDET#TCO_CODIGO=0
           SELECT @FACTIMPDET#PA_CODIGO=ISNULL((SELECT isnull(PA_ORIGEN,0) FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),233)
            IF @FACTIMPDET#PA_CODIGO IS NULL
                SELECT @FACTIMPDET#PA_CODIGO=0
           SELECT @FACTIMPDET#SPI_CODIGO=ISNULL((SELECT isnull(SPI_CODIGO,0) FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),0)
            IF @FACTIMPDET#SPI_CODIGO IS NULL
                SELECT @FACTIMPDET#SPI_CODIGO=0
           SELECT @FACTIMPDET#AR_IMPMX=(SELECT 'AR_IMPMX'=CASE WHEN @FACTIMPDET#FID_DEF_TIP ='R' THEN isnull(AR_IMPMXR8,isnull(AR_IMPMX,0)) ELSE isnull(AR_IMPMX,0) END FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX)
            IF @FACTIMPDET#AR_IMPMX IS NULL
                SELECT @FACTIMPDET#AR_IMPMX=0
           SELECT @FACTIMPDET#FID_PES_UNI=ISNULL((SELECT MA_PESO_KG FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),0)
            IF @FACTIMPDET#FID_PES_UNI IS NULL
                SELECT @FACTIMPDET#FID_PES_UNI=0
           SELECT @FACTIMPDET#FID_SEC_IMP=(SELECT 'FID_SEC_IMP'=CASE WHEN (SELECT TF_CODIGO FROM FACTIMP WHERE FI_CODIGO=@CONSECUTIVO) IN (SELECT TF_CODIGO FROM CONFIGURATFACT WHERE CFF_TIPO IN ('IF','IA','IT')) AND ISNULL((SELECT CL_EMPCERTIFICADA FROM CLIENTE WHERE CL_EMPRESA ='S'),'')<>'' THEN MA_SEC_IMPCERTDEF ELSE MA_SEC_IMP END FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX)
            IF @FACTIMPDET#FID_SEC_IMP IS NULL
                SELECT @FACTIMPDET#FID_SEC_IMP=0
           SELECT @FACTIMPDET#FID_POR_DEF=ISNULL((SELECT dbo.GetAdvalorem(@FACTIMPDET#AR_IMPMX, @FACTIMPDET#PA_CODIGO, @FACTIMPDET#FID_DEF_TIP, @FACTIMPDET#FID_SEC_IMP, @FACTIMPDET#SPI_CODIGO) FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),-1)
            IF @FACTIMPDET#FID_POR_DEF IS NULL
                SELECT @FACTIMPDET#FID_POR_DEF=-1
           SELECT @FACTIMPDET#AR_EXPFO=(SELECT isnull(AR_EXPFO,0)  FROM MAESTRO WHERE MA_INV_GEN='I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX)
            IF @FACTIMPDET#AR_EXPFO IS NULL
                SELECT @FACTIMPDET#AR_EXPFO=0
           SELECT @FACTIMPDET#ME_CODIGO=ISNULL((SELECT isnull(ME_COM,19) FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),19)
            IF @FACTIMPDET#ME_CODIGO IS NULL
                SELECT @FACTIMPDET#ME_CODIGO=0
           SELECT @FACTIMPDET#MA_GENERICO=(SELECT isnull(MA_GENERICO,0) FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX)
            IF @FACTIMPDET#MA_GENERICO IS NULL
                SELECT @FACTIMPDET#MA_GENERICO=0
           SELECT @FACTIMPDET#PR_CODIGO=(SELECT PR_CODIGO FROM FACTIMP WHERE FI_CODIGO=@CONSECUTIVO)
            IF @FACTIMPDET#PR_CODIGO IS NULL
                SELECT @FACTIMPDET#PR_CODIGO=0
           SELECT @FACTIMPDET#EQ_GEN=(SELECT isnull(EQ_GEN,1) FROM MAESTRO WHERE MA_INV_GEN='I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX)
            IF @FACTIMPDET#EQ_GEN IS NULL
                SELECT @FACTIMPDET#EQ_GEN=-1
           SELECT @FACTIMPDET#EQ_IMPMX=(SELECT isnull(EQ_IMPMX,1) FROM MAESTRO WHERE MA_INV_GEN='I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX)
            IF @FACTIMPDET#EQ_IMPMX IS NULL
                SELECT @FACTIMPDET#EQ_IMPMX=-1
           SELECT @FACTIMPDET#EQ_EXPFO=(SELECT isnull(EQ_EXPFO,1)  FROM MAESTRO WHERE MA_INV_GEN='I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX)
            IF @FACTIMPDET#EQ_EXPFO IS NULL
                SELECT @FACTIMPDET#EQ_EXPFO=-1
           SELECT @FACTIMPDET#TI_CODIGO=ISNULL((SELECT isnull(TI_CODIGO,0) FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),10)
            IF @FACTIMPDET#TI_CODIGO IS NULL
                SELECT @FACTIMPDET#TI_CODIGO=-10
           SELECT @FACTIMPDET#FID_NOMBRE=ISNULL((SELECT MA_NOMBRE FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),'TEMP')
            IF @FACTIMPDET#FID_NOMBRE IS NULL
                SELECT @FACTIMPDET#FID_NOMBRE=''
           SELECT @FACTIMPDET#FID_NAME=ISNULL((SELECT MA_NAME FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),'TEMP')
            IF @FACTIMPDET#FID_NAME IS NULL
                SELECT @FACTIMPDET#FID_NAME=''
           SELECT @FACTIMPDET#ME_GEN=(SELECT isnull(ME_COM,0) FROM MAESTRO WHERE MA_CODIGO=@FACTIMPDET#MA_GENERICO)
            IF @FACTIMPDET#ME_GEN IS NULL
                SELECT @FACTIMPDET#ME_GEN=0
           SELECT @FACTIMPDET#MA_CODIGO=ISNULL((SELECT MA_CODIGO FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX),0)
            IF @FACTIMPDET#MA_CODIGO IS NULL
                SELECT @FACTIMPDET#MA_CODIGO=0
           SELECT @FACTIMPDET#ME_ARIMPMX=(SELECT isnull(ME_CODIGO,0) FROM ARANCEL WHERE AR_CODIGO=(SELECT AR_IMPMX FROM MAESTRO WHERE MA_INV_GEN='I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX))
            IF @FACTIMPDET#ME_ARIMPMX IS NULL
                SELECT @FACTIMPDET#ME_ARIMPMX=0
           SELECT @FACTIMPDET#CS_CODIGO=(SELECT CS_CODIGO FROM MAESTRO WHERE MA_INV_GEN = 'I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX)
            IF @FACTIMPDET#CS_CODIGO IS NULL
                SELECT @FACTIMPDET#CS_CODIGO=-8
           SELECT @FACTIMPDET#EQ_EXPFO2=(SELECT isnull(EQ_EXPFO2,1)  FROM MAESTRO WHERE MA_INV_GEN='I' AND MA_NOPARTE=@FACTIMPDET#FID_NOPARTE AND MA_NOPARTEAUX=@FACTIMPDET#FID_NOPARTEAUX)
            IF @FACTIMPDET#EQ_EXPFO2 IS NULL
                SELECT @FACTIMPDET#EQ_EXPFO2=-1
          EXEC SP_GETCONSECUTIVO @TIPO='FID',@VALUE=@CONSDET OUTPUT
                INSERT INTO FACTIMPDET (FID_INDICED,FI_CODIGO,FID_PES_UNILB ,FID_NOPARTEAUX ,FID_DEF_TIP ,FID_NOPARTE ,FID_CANT_ST ,FID_COS_UNI ,FID_COS_TOT ,FID_PES_BRULB ,TCO_CODIGO ,PA_CODIGO ,SPI_CODIGO ,AR_IMPMX ,FID_PES_UNI ,FID_SEC_IMP ,FID_POR_DEF ,AR_EXPFO ,ME_CODIGO ,MA_GENERICO ,PR_CODIGO ,EQ_GEN ,EQ_IMPMX ,EQ_EXPFO ,TI_CODIGO ,FID_NOMBRE ,FID_NAME ,ME_GEN ,MA_CODIGO ,ME_ARIMPMX ,CS_CODIGO ,EQ_EXPFO2 ) VALUES (@CONSDET,@CONSECUTIVO,@FACTIMPDET#FID_PES_UNILB ,@FACTIMPDET#FID_NOPARTEAUX ,@FACTIMPDET#FID_DEF_TIP ,@FACTIMPDET#FID_NOPARTE ,@FACTIMPDET#FID_CANT_ST ,@FACTIMPDET#FID_COS_UNI ,@FACTIMPDET#FID_COS_TOT ,@FACTIMPDET#FID_PES_BRULB ,@FACTIMPDET#TCO_CODIGO,@FACTIMPDET#PA_CODIGO,@FACTIMPDET#SPI_CODIGO,@FACTIMPDET#AR_IMPMX,@FACTIMPDET#FID_PES_UNI,@FACTIMPDET#FID_SEC_IMP,@FACTIMPDET#FID_POR_DEF,@FACTIMPDET#AR_EXPFO,@FACTIMPDET#ME_CODIGO,@FACTIMPDET#MA_GENERICO,@FACTIMPDET#PR_CODIGO,@FACTIMPDET#EQ_GEN,@FACTIMPDET#EQ_IMPMX,@FACTIMPDET#EQ_EXPFO,@FACTIMPDET#TI_CODIGO,@FACTIMPDET#FID_NOMBRE,@FACTIMPDET#FID_NAME,@FACTIMPDET#ME_GEN,@FACTIMPDET#MA_CODIGO,@FACTIMPDET#ME_ARIMPMX,@FACTIMPDET#CS_CODIGO,@FACTIMPDET#EQ_EXPFO2)
              update FACTIMPDET set FID_PES_UNILB = ( FACTIMPDET.FID_PES_BRULB /FACTIMPDET.FID_CANT_ST )
              from FACTIMPDET
              left outer join FACTIMP on  
             FACTIMP.FI_CODIGO = FACTIMPDET.FI_CODIGO
              where FACTIMPDET.FID_INDICED = @CONSDET
                      FETCH NEXT FROM CUR_TEMPIMPORT144_7DET INTO @Cod_3 ,@FACTIMPDET#FID_PES_UNILB ,@FACTIMPDET#FID_NOPARTEAUX ,@FACTIMPDET#FID_DEF_TIP ,@FACTIMPDET#FID_NOPARTE ,@FACTIMPDET#FID_CANT_ST ,@FACTIMPDET#FID_COS_UNI ,@FACTIMPDET#FID_COS_TOT ,@FACTIMPDET#FID_PES_BRULB 
        END
        CLOSE CUR_TEMPIMPORT144_7DET
        DEALLOCATE CUR_TEMPIMPORT144_7DET
  END
  FETCH NEXT FROM CUR_TEMPIMPORT144_7 INTO @Cod_3 ,@FACTIMP#DI_COMP ,@FACTIMP#TF_CODIGO ,@FACTIMP#SPI_CODIGO ,@FACTIMP#CL_VEND ,@FACTIMP#DI_VEND ,@FACTIMP#CL_EXP ,@FACTIMP#DI_EXP ,@FACTIMP#CP_CODIGO ,@FACTIMP#FI_TIPO ,@FACTIMP#PR_CODIGO ,@FACTIMP#DI_PROVEE ,@FACTIMP#TQ_CODIGO ,@FACTIMP#CL_PROD ,@FACTIMP#DI_PROD ,@FACTIMP#CL_COMP ,@FACTIMP#FI_FOLIO ,@FACTIMP#FI_FECHA 
END
CLOSE CUR_TEMPIMPORT144_7
DEALLOCATE CUR_TEMPIMPORT144_7
GO
