SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_BOMCICLO1] (@BST_PT INT, @BST_HIJO INT, @BST_ENTRAVIGOR DATETIME, @nivel int)   as

--SET NOCOUNT ON 
declare @BST_HIJO1 int, @nivelr INT


	SET @nivelr=@nivel+1
	
	begin

		DECLARE @CursorVar CURSOR
		
		SET @CursorVar = CURSOR SCROLL DYNAMIC FOR
			SELECT     dbo.BOM_STRUCT.BST_HIJO
			FROM         dbo.BOM_STRUCT LEFT OUTER JOIN dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN 
			                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO 
					LEFT OUTER JOIN dbo.MAESTROREFER ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTROREFER.MA_CODIGO LEFT OUTER JOIN
			                      dbo.CONFIGURATIPO CONFIGURATIPO2 ON dbo.MAESTROREFER.TI_CODIGO = CONFIGURATIPO2.TI_CODIGO
			WHERE   (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_HIJO) 
				AND (dbo.BOM_STRUCT.BST_PERINI <= @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>= @BST_ENTRAVIGOR) 
				AND (ISNULL(dbo.CONFIGURATIPO.CFT_TIPO, CONFIGURATIPO2.CFT_TIPO) = 'P' OR ISNULL(dbo.CONFIGURATIPO.CFT_TIPO, CONFIGURATIPO2.CFT_TIPO) = 'S') 
				AND (dbo.BOM_STRUCT.BST_TIP_ENS <> 'C') AND (dbo.BOM_STRUCT.BST_TIP_ENS <> 'P')
				AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL 
				AND (dbo.BOM_STRUCT.BST_INCORPOR) >0
				--AND dbo.BOM_STRUCT.BSU_SUBENSAMBLE NOT IN (SELECT BST_PT FROM BOMCICLO WHERE ENTRAVIGOR=@BST_ENTRAVIGOR)
			GROUP BY dbo.BOM_STRUCT.BST_HIJO
		
		 OPEN @CursorVar
		  FETCH NEXT FROM @CursorVar INTO @BST_HIJO1
		
		  WHILE (@@fetch_status = 0) 
		  BEGIN  
	
				if @@NESTLEVEL <31
				begin
		
					exec  SP_BOMCICLO1 @BST_PT, @BST_HIJO1, @BST_ENTRAVIGOR, @nivelr
				end
				else
				begin
					IF @BST_PT NOT IN (SELECT BST_PT FROM BOMCICLO WHERE ENTRAVIGOR=@BST_ENTRAVIGOR)
						insert into BOMCICLO(BST_PT, ENTRAVIGOR)
						values(@BST_PT, CONVERT(VARCHAR(10),@BST_ENTRAVIGOR,101))

					break
				end
		
		
		
			  FETCH NEXT FROM @CursorVar INTO @BST_HIJO1
		END
			CLOSE @CursorVar
			DEALLOCATE @CursorVar
	end


GO
