SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



























CREATE PROCEDURE [dbo].[SP_INSERTIDENTIFICAFACTCONS]  (@FC_CODIGO INT, @TIPOMOV CHAR(1), @CP_CODIGO INT)   as

SET NOCOUNT ON 

declare @FCI_CODIGO INT, @IDE_CODIGO int, @IDED_CODIGO int, @IDEG_DESC varchar(40), @IDEG_DESC2 varchar(40), @IDED_CODIGO2 int


	delete from FACTCONSIDENTIFICA where fc_codigo=@FC_CODIGO

DECLARE cur_identificadores CURSOR FOR
	SELECT     IDE_CODIGO, ISNULL(IDED_CODIGO, 0) AS IDED_CODIGO, ISNULL(IDEG_DESC, '') AS IDEG_DESC, ISNULL(IDEG_DESC2, '') AS IDEG_DESC2, 
	                      ISNULL(IDED_CODIGO2, 0) AS IDED_CODIGO2
	FROM         IDENTIFICAGRAL
	WHERE     (IDEG_NIVEL = 'G') AND (IDEG_MOVIMIENTO = 'A' OR
	                      IDEG_MOVIMIENTO =@TIPOMOV) AND (IDEG_TIPO = 'T') AND (CP_CODIGO = @CP_CODIGO)
open cur_identificadores  


	FETCH NEXT FROM cur_identificadores into @IDE_CODIGO, @IDED_CODIGO, @IDEG_DESC, @IDEG_DESC2, @IDED_CODIGO2

	WHILE (@@FETCH_STATUS = 0) 
	BEGIN
		EXEC  SP_GETCONSECUTIVO 'FCI', @VALUE = @FCI_CODIGO OUTPUT
	
		begin tran
			insert into FACTCONSIDENTIFICA(FCI_CODIGO, FC_CODIGO, IDE_CODIGO, IDED_CODIGO, FCI_DESC, FCI_DESC2, IDED_CODIGO2)
			VALUES (@FCI_CODIGO, @FC_CODIGO, @IDE_CODIGO, @IDED_CODIGO, @IDEG_DESC, @IDEG_DESC2, @IDED_CODIGO2)
		commit tran




	FETCH NEXT FROM cur_identificadores into @IDE_CODIGO, @IDED_CODIGO, @IDEG_DESC, @IDEG_DESC2, @IDED_CODIGO2

END

CLOSE cur_identificadores
DEALLOCATE cur_identificadores

























GO
