SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_CARGARENTRIES]   as



DECLARE @CONSECUTIVO INT, @ETC_CODIGO int, @ETC_ENTRY_NO varchar(20), @ETC_FEC_ENTRYS datetime, @EA_ENTRADA int, @EB_ENTRADA int,
@hoy datetime


select @hoy=convert(varchar(11), getdate())

declare cur_entries cursor for
	SELECT     ETC_CODIGO, REPLACE(ETC_ENTRY_NO,' ',''), ETC_FEC_ENTRYS, EA_ENTRADA, EB_ENTRADA
	FROM         ENTRYCONS
	WHERE ETC_SEL='S' AND
	ETC_CODIGO NOT IN (SELECT ETC_CODIGO FROM ENTRYSUM)
open cur_entries


	FETCH NEXT FROM cur_entries INTO @ETC_CODIGO, @ETC_ENTRY_NO, @ETC_FEC_ENTRYS, @EA_ENTRADA, @EB_ENTRADA

	WHILE (@@FETCH_STATUS = 0) 
	BEGIN
		UPDATE ENTRYCONS
		SET ETC_ESTATUS='C'
		WHERE ETC_CODIGO=@ETC_CODIGO

		EXEC SP_GETCONSECUTIVO @TIPO='ET', @VALUE=@CONSECUTIVO OUTPUT


		INSERT INTO ENTRYSUM(ET_CODIGO, ETC_CODIGO, ET_ENTRY_NO, ET_FEC_ENTRYS, EA_ENTRADA, EB_ENTRADA, ET_FEC_IMP, ET_FEC_GEN, ET_FEC_ENTRY)
		VALUES (@CONSECUTIVO, @ETC_CODIGO, @ETC_ENTRY_NO, @ETC_FEC_ENTRYS, @EA_ENTRADA, @EB_ENTRADA, @ETC_FEC_ENTRYS, @hoy, @ETC_FEC_ENTRYS)


		UPDATE FACTEXP
		SET ET_CODIGO=@CONSECUTIVO
		WHERE ETC_CODIGO=@ETC_CODIGO


	FETCH NEXT FROM cur_entries INTO @ETC_CODIGO, @ETC_ENTRY_NO, @ETC_FEC_ENTRYS, @EA_ENTRADA, @EB_ENTRADA

END

CLOSE cur_entries
DEALLOCATE cur_entries


GO
