SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


/* inserta en la tabla TempBOM_NIVEL  para calculo de costos de todos los productos*/
CREATE PROCEDURE [dbo].[SP_fill_bom_desctempFed] (@FED_INDICED INT)   as

--SET NOCOUNT ON 

DECLARE @existe INT, @BST_TIPODESC CHAR(1), @NIVEL SMALLINT


	--exec sp_droptable 'BOM_DESCTEMP'

	exec Sp_CreaBOM_DESCTEMP

	delete from bom_struct where bsu_subensamble = bst_hijo


	SET @NIVEL=1

	--  No se utilizan el tipo de adquisicion Comprados-Fisicos
	if (select CF_FISCOMP_EXPDESC from configuracion)='X' 
	begin

					insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
					    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
					   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)
		
					SELECT     BOM_STRUCT.BST_HIJO, (BOM_STRUCT.BST_INCORPOR+
					        (CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and isnull(MAESTRO.MA_POR_DESP,0)<>0 
						then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) else 0 end)) AS BST_INCORPOR, 
						         'BST_DISCH'=case when BOM_STRUCT.BST_TIP_ENS = 'F' then 'N' else BOM_STRUCT.BST_DISCH end,
					                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
					                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, BOM_STRUCT.BST_TRANS, MAESTRO.BST_TIPOCOSTO, 
					                      REPLACE(BOM_STRUCT.BST_TIP_ENS,'A','F'), FED_CANT, FE_CODIGO, 'B1', @BST_TIPODESC,
						        FACTEXPDET.MA_CODIGO, FED_INDICED, FACTEXPDET.MA_CODIGO, FACTEXPDET.FED_FECHA_STRUCT, MAESTRO.MA_PESO_KG, isnull((SELECT max(MA_COSTO) FROM VMAESTROCOST
						WHERE MA_CODIGO=BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
					FROM         BOM_STRUCT INNER JOIN
					                      FACTEXPDET ON BOM_STRUCT.BSU_SUBENSAMBLE = FACTEXPDET.MA_CODIGO AND 
					                      BOM_STRUCT.BST_PERINI <= FACTEXPDET.FED_FECHA_STRUCT AND 
					                      BOM_STRUCT.BST_PERFIN >= FACTEXPDET.FED_FECHA_STRUCT LEFT OUTER JOIN
					                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
					                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
						        CONFIGURATIPO CONFIGURATIPO_2 ON FACTEXPDET.TI_CODIGO = CONFIGURATIPO_2.TI_CODIGO 
					WHERE FACTEXPDET.FED_INDICED=@FED_INDICED
						AND (CONFIGURATIPO_2.CFT_TIPO = 'S' OR
					                      CONFIGURATIPO_2.CFT_TIPO = 'P') AND (FACTEXPDET.FED_RETRABAJO = 'N'
						        or FACTEXPDET.FED_RETRABAJO = 'C' or FACTEXPDET.FED_RETRABAJO = 'A')
						AND (FACTEXPDET.FED_TIP_ENS = 'F' OR FACTEXPDET.FED_TIP_ENS = 'E'or FACTEXPDET.FED_TIP_ENS = 'O') 
							AND (FACTEXPDET.FED_CANT > 0) 
						AND FACTEXPDET.PID_INDICED=-1
					AND     BOM_STRUCT.BST_HIJO IS NOT NULL AND BOM_STRUCT.BST_INCORPOR >0
					
	

		inicio0:
	
		SET @nivel=@nivel+1


	
	
				insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
				    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
				   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)
	
				SELECT     BOM_STRUCT.BST_HIJO, BOM_DESCTEMP.BST_INCORPOR * (BOM_STRUCT.BST_INCORPOR+
					        (CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and isnull(MAESTRO.MA_POR_DESP,0)<>0 
						then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) else 0 end)) AS BST_INCORPOR, 

					         'BST_DISCH'=case when BOM_STRUCT.BST_TIP_ENS = 'F' then 'N' else BOM_STRUCT.BST_DISCH end,
				                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
				                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, BOM_STRUCT.BST_TRANS, MAESTRO.BST_TIPOCOSTO, 
				                      REPLACE(BOM_STRUCT.BST_TIP_ENS,'A','F'), FED_CANT, FE_CODIGO, 'B'+CONVERT(VARCHAR(20),@nivel), @BST_TIPODESC,
					        BST_PT, FED_INDICED, BSU_SUBENSAMBLE, BST_ENTRAVIGOR, MAESTRO.MA_PESO_KG, isnull((SELECT max(MA_COSTO) FROM VMAESTROCOST
					WHERE MA_CODIGO=BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
				FROM    BOM_DESCTEMP INNER JOIN
	                      		BOM_STRUCT ON BOM_DESCTEMP.BST_HIJO = BOM_STRUCT.BSU_SUBENSAMBLE AND
				                      BOM_STRUCT.BST_PERINI <= BOM_DESCTEMP.BST_ENTRAVIGOR AND 
				                      BOM_STRUCT.BST_PERFIN >= BOM_DESCTEMP.BST_ENTRAVIGOR LEFT OUTER JOIN
						      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
				                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
				WHERE BOM_DESCTEMP.FED_INDICED=@FED_INDICED AND (BOM_DESCTEMP.MA_TIP_ENS ='F' OR BOM_DESCTEMP.MA_TIP_ENS IS NULL)
					AND CONVERT(INT,REPLACE(BOM_DESCTEMP.BST_NIVEL,'B',''))=@nivel-1
				AND BOM_STRUCT.BST_HIJO IS NOT NULL AND BOM_STRUCT.BST_INCORPOR >0



			if (SELECT     COUNT(*)
			    FROM         BOM_DESCTEMP
			    WHERE     CONVERT(INT,REPLACE(BOM_DESCTEMP.BST_NIVEL,'B','')) =@nivel-1
			    AND FED_INDICED=@FED_INDICED
			    AND (TI_CODIGO='S' OR TI_CODIGO='P') 
			    AND MA_TIP_ENS<>'P' AND MA_TIP_ENS<>'C')>0
	
			set @existe=1
			else
			set @existe=0
	
	
		while (@existe>0)	
		begin
	
			goto inicio0
	
	
		end


	end
	else
	begin

			if (select CF_FISCOMP_EXPDESC from configuracion)='S' -- la explosion lo hace durante el el proceso de descarga
			BEGIN
					insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
					    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
					   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)
		
					SELECT     BOM_STRUCT.BST_HIJO, (BOM_STRUCT.BST_INCORPOR+
					        (CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and isnull(MAESTRO.MA_POR_DESP,0)<>0 
						then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) else 0 end)) AS BST_INCORPOR, 
						         'BST_DISCH'=case when BOM_STRUCT.BST_TIP_ENS = 'F' OR (BOM_STRUCT.BST_TIP_ENS = 'A' AND BOM_STRUCT.BST_HIJO NOT IN (SELECT MA_CODIGO FROM VPIDESCARGA)) then 'N' else BOM_STRUCT.BST_DISCH end,
					                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
					                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, BOM_STRUCT.BST_TRANS, MAESTRO.BST_TIPOCOSTO, 
					                      'BST_TIP_ENS'=CASE WHEN BOM_STRUCT.BST_TIP_ENS = 'A' AND BOM_STRUCT.BST_HIJO NOT IN (SELECT MA_CODIGO FROM VPIDESCARGA) THEN 'F' ELSE
						         BOM_STRUCT.BST_TIP_ENS END, FED_CANT, FE_CODIGO, 'B1', @BST_TIPODESC,
						        FACTEXPDET.MA_CODIGO, FED_INDICED, FACTEXPDET.MA_CODIGO, FACTEXPDET.FED_FECHA_STRUCT, MAESTRO.MA_PESO_KG, isnull((SELECT max(MA_COSTO) FROM VMAESTROCOST
						WHERE MA_CODIGO=BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
					FROM         BOM_STRUCT INNER JOIN
					                      FACTEXPDET ON BOM_STRUCT.BSU_SUBENSAMBLE = FACTEXPDET.MA_CODIGO AND 
					                      BOM_STRUCT.BST_PERINI <= FACTEXPDET.FED_FECHA_STRUCT AND 
					                      BOM_STRUCT.BST_PERFIN >= FACTEXPDET.FED_FECHA_STRUCT LEFT OUTER JOIN
					                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
					                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
						        CONFIGURATIPO CONFIGURATIPO_2 ON FACTEXPDET.TI_CODIGO = CONFIGURATIPO_2.TI_CODIGO 
					WHERE FACTEXPDET.FED_INDICED=@FED_INDICED
						AND (CONFIGURATIPO_2.CFT_TIPO = 'S' OR
					                      CONFIGURATIPO_2.CFT_TIPO = 'P') AND (FACTEXPDET.FED_RETRABAJO = 'N'
						        or FACTEXPDET.FED_RETRABAJO = 'C' or FACTEXPDET.FED_RETRABAJO = 'A')
						AND (FACTEXPDET.FED_TIP_ENS = 'F' OR FACTEXPDET.FED_TIP_ENS = 'E'or FACTEXPDET.FED_TIP_ENS = 'O') 
							AND (FACTEXPDET.FED_CANT > 0) 
						AND FACTEXPDET.PID_INDICED=-1
					AND BOM_STRUCT.BST_HIJO IS NOT NULL AND BOM_STRUCT.BST_INCORPOR >0	


			END
			ELSE
			BEGIN

				--PRINT @nivel

					insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
					    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
					   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)
		
					SELECT     BOM_STRUCT.BST_HIJO, (BOM_STRUCT.BST_INCORPOR+
					        (CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and isnull(MAESTRO.MA_POR_DESP,0)<>0 
						then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) else 0 end)) AS BST_INCORPOR, 
						         'BST_DISCH'=case when BOM_STRUCT.BST_TIP_ENS = 'F' or BOM_STRUCT.BST_TIP_ENS = 'A' then 'N' else BOM_STRUCT.BST_DISCH end,
					                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
					                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, BOM_STRUCT.BST_TRANS, MAESTRO.BST_TIPOCOSTO, 
					                      'BST_TIP_ENS'=case when BOM_STRUCT.BST_TIP_ENS='A' then 'F' else BOM_STRUCT.BST_TIP_ENS end, FED_CANT, FE_CODIGO, 'B1', @BST_TIPODESC,
						        FACTEXPDET.MA_CODIGO, FED_INDICED, FACTEXPDET.MA_CODIGO, FACTEXPDET.FED_FECHA_STRUCT, MAESTRO.MA_PESO_KG, isnull((SELECT max(MA_COSTO) FROM VMAESTROCOST
						WHERE MA_CODIGO=BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
					FROM         BOM_STRUCT INNER JOIN
					                      FACTEXPDET ON BOM_STRUCT.BSU_SUBENSAMBLE = FACTEXPDET.MA_CODIGO AND 
					                      BOM_STRUCT.BST_PERINI <= FACTEXPDET.FED_FECHA_STRUCT AND 
					                      BOM_STRUCT.BST_PERFIN >= FACTEXPDET.FED_FECHA_STRUCT LEFT OUTER JOIN
					                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
					                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO LEFT OUTER JOIN
						        CONFIGURATIPO CONFIGURATIPO_2 ON FACTEXPDET.TI_CODIGO = CONFIGURATIPO_2.TI_CODIGO 
					WHERE FACTEXPDET.FED_INDICED=@FED_INDICED
						AND (CONFIGURATIPO_2.CFT_TIPO = 'S' OR
					                      CONFIGURATIPO_2.CFT_TIPO = 'P') AND (FACTEXPDET.FED_RETRABAJO = 'N'
						        or FACTEXPDET.FED_RETRABAJO = 'C' or FACTEXPDET.FED_RETRABAJO = 'A')
						AND (FACTEXPDET.FED_TIP_ENS = 'F' OR FACTEXPDET.FED_TIP_ENS = 'E'or FACTEXPDET.FED_TIP_ENS = 'O' OR
							(FACTEXPDET.FED_TIP_ENS = 'A' AND dbo.FACTEXPDET.MA_CODIGO NOT IN (SELECT MA_CODIGO FROM VPIDESCARGA))) 
							AND (FACTEXPDET.FED_CANT > 0) 
						AND FACTEXPDET.PID_INDICED=-1
						AND BOM_STRUCT.BST_HIJO IS NOT NULL AND BOM_STRUCT.BST_INCORPOR >0


			END
	

	
	inicio:
	
		SET @nivel=@nivel+1
	
		if (select CF_FISCOMP_EXPDESC from configuracion)='S' -- la explosion lo hace durante el el proceso de descarga
		BEGIN
	
	
				-- hijos de los fisicos
				insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
				    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
				   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)
	
				SELECT     BOM_STRUCT.BST_HIJO, BOM_DESCTEMP.BST_INCORPOR * (BOM_STRUCT.BST_INCORPOR+
					        (CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and isnull(MAESTRO.MA_POR_DESP,0)<>0 
						then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) else 0 end)) AS BST_INCORPOR, 
					         'BST_DISCH'=case when BOM_STRUCT.BST_TIP_ENS = 'F' OR (BOM_STRUCT.BST_TIP_ENS = 'A' AND BOM_STRUCT.BST_HIJO NOT IN (SELECT MA_CODIGO FROM VPIDESCARGA)) then 'N' else BOM_STRUCT.BST_DISCH end,
				                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
				                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, BOM_STRUCT.BST_TRANS, MAESTRO.BST_TIPOCOSTO, 
				                      'BST_TIP_ENS'=CASE WHEN BOM_STRUCT.BST_TIP_ENS = 'A' AND BOM_STRUCT.BST_HIJO NOT IN (SELECT MA_CODIGO FROM VPIDESCARGA) THEN 'F' ELSE
					        BOM_STRUCT.BST_TIP_ENS END, FED_CANT, FE_CODIGO, 'B'+CONVERT(VARCHAR(20),@nivel), @BST_TIPODESC,
					        BST_PT, FED_INDICED, BSU_SUBENSAMBLE, BST_ENTRAVIGOR, MAESTRO.MA_PESO_KG, isnull((SELECT max(MA_COSTO) FROM VMAESTROCOST
					WHERE MA_CODIGO=BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
				FROM         BOM_DESCTEMP INNER JOIN
	                      		BOM_STRUCT ON BOM_DESCTEMP.BST_HIJO = BOM_STRUCT.BSU_SUBENSAMBLE AND
				                      BOM_STRUCT.BST_PERINI <= BOM_DESCTEMP.BST_ENTRAVIGOR AND 
				                      BOM_STRUCT.BST_PERFIN >= BOM_DESCTEMP.BST_ENTRAVIGOR LEFT OUTER JOIN
				                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
				                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
				WHERE BOM_DESCTEMP.FED_INDICED=@FED_INDICED AND (BOM_DESCTEMP.MA_TIP_ENS ='F' OR BOM_DESCTEMP.MA_TIP_ENS IS NULL)
					AND CONVERT(INT,REPLACE(BOM_DESCTEMP.BST_NIVEL,'B',''))=@nivel-1
				AND BOM_STRUCT.BST_HIJO IS NOT NULL AND BOM_STRUCT.BST_INCORPOR >0

	
		END
		ELSE
		if (select CF_FISCOMP_EXPDESC from configuracion)='N' -- la explosion de los fisico-comprados lo hace cuando explosiona la factura
		BEGIN
			if @nivel=2
			begin
	
				--PRINT 'B'
				--PRINT @nivel
	
				insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
				    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
				   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)
	
				SELECT     BOM_STRUCT.BST_HIJO, BOM_DESCTEMP.BST_INCORPOR * (BOM_STRUCT.BST_INCORPOR+
					        (CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and isnull(MAESTRO.MA_POR_DESP,0)<>0 
						then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) else 0 end)) AS BST_INCORPOR, 
					         'BST_DISCH'=case when BOM_STRUCT.BST_TIP_ENS = 'F' or BOM_STRUCT.BST_TIP_ENS = 'A' then 'N' else BOM_STRUCT.BST_DISCH end,
				                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
				                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, BOM_STRUCT.BST_TRANS, MAESTRO.BST_TIPOCOSTO, 
				                      'MA_TIP_ENS'=case when BOM_DESCTEMP.MA_TIP_ENS = 'A' then 'C' else 'F'end, 
						FED_CANT, FE_CODIGO, 'B'+CONVERT(VARCHAR(20),@nivel), @BST_TIPODESC,
					        BST_PT, FED_INDICED, BSU_SUBENSAMBLE, BST_ENTRAVIGOR, MAESTRO.MA_PESO_KG, isnull((SELECT max(MA_COSTO) FROM VMAESTROCOST
					WHERE MA_CODIGO=BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
				FROM         BOM_DESCTEMP INNER JOIN
	                      		BOM_STRUCT ON BOM_DESCTEMP.BST_HIJO = BOM_STRUCT.BSU_SUBENSAMBLE AND
				                      BOM_STRUCT.BST_PERINI <= BOM_DESCTEMP.BST_ENTRAVIGOR AND 
				                      BOM_STRUCT.BST_PERFIN >= BOM_DESCTEMP.BST_ENTRAVIGOR LEFT OUTER JOIN
				                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
				                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
				WHERE BOM_DESCTEMP.FED_INDICED=@FED_INDICED AND (BOM_DESCTEMP.MA_TIP_ENS ='F' OR BOM_DESCTEMP.MA_TIP_ENS IS NULL OR
					(BOM_DESCTEMP.MA_TIP_ENS = 'A' AND BOM_DESCTEMP.BST_PERTENECE NOT IN (SELECT MA_CODIGO FROM VPIDESCARGA)))
					AND CONVERT(INT,REPLACE(BOM_DESCTEMP.BST_NIVEL,'B',''))=@nivel-1
				AND BOM_STRUCT.BST_HIJO IS NOT NULL AND BOM_STRUCT.BST_INCORPOR >0

	
			end
			else
			begin
	
				--PRINT 'C'
				--PRINT @nivel
	
				insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
				    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
				   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)
	
				SELECT     BOM_STRUCT.BST_HIJO, BOM_DESCTEMP.BST_INCORPOR * (BOM_STRUCT.BST_INCORPOR+
					        (CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and isnull(MAESTRO.MA_POR_DESP,0)<>0 
						then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) else 0 end)) AS BST_INCORPOR, 
					         'BST_DISCH'=case when BOM_STRUCT.BST_TIP_ENS = 'F' then 'N' else BOM_STRUCT.BST_DISCH end,
				                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
				                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, BOM_STRUCT.BST_TRANS, MAESTRO.BST_TIPOCOSTO, 
				                      BOM_STRUCT.BST_TIP_ENS, FED_CANT, FE_CODIGO, 'B'+CONVERT(VARCHAR(20),@nivel), @BST_TIPODESC,
					        BST_PT, FED_INDICED, BSU_SUBENSAMBLE, BST_ENTRAVIGOR, MAESTRO.MA_PESO_KG, isnull((SELECT max(MA_COSTO) FROM VMAESTROCOST
					WHERE MA_CODIGO=BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
				FROM         BOM_DESCTEMP INNER JOIN
	                      		BOM_STRUCT ON BOM_DESCTEMP.BST_HIJO = BOM_STRUCT.BSU_SUBENSAMBLE AND
				                      BOM_STRUCT.BST_PERINI <= BOM_DESCTEMP.BST_ENTRAVIGOR AND 
				                      BOM_STRUCT.BST_PERFIN >= BOM_DESCTEMP.BST_ENTRAVIGOR LEFT OUTER JOIN
				                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
				                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
				WHERE BOM_DESCTEMP.FED_INDICED=@FED_INDICED AND (BOM_DESCTEMP.MA_TIP_ENS ='F' OR BOM_DESCTEMP.MA_TIP_ENS IS NULL)
					AND CONVERT(INT,REPLACE(BOM_DESCTEMP.BST_NIVEL,'B',''))=@nivel-1
				AND BOM_STRUCT.BST_HIJO IS NOT NULL AND BOM_STRUCT.BST_INCORPOR >0
	
			end
		END
		ELSE
		BEGIN
	
				--PRINT 'D'
				--PRINT @nivel
	
	
				insert into bom_desctemp (BST_HIJO, BST_INCORPOR, BST_DISCH, TI_CODIGO,  ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
				    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, FED_CANT, FE_CODIGO, BST_NIVEL, BST_TIPODESC,
				   BST_PERTENECE, FED_INDICED, BST_PT, BST_ENTRAVIGOR, BST_PESO_KG, BST_COSTO)
	
				SELECT     BOM_STRUCT.BST_HIJO, BOM_DESCTEMP.BST_INCORPOR * (BOM_STRUCT.BST_INCORPOR+
					        (CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and isnull(MAESTRO.MA_POR_DESP,0)<>0 
						then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100) else 0 end)) AS BST_INCORPOR, 
					         'BST_DISCH'=case when BOM_STRUCT.BST_TIP_ENS = 'F' or BOM_STRUCT.BST_TIP_ENS = 'A' then 'N' else BOM_STRUCT.BST_DISCH end,
				                      CONFIGURATIPO.CFT_TIPO, BOM_STRUCT.ME_CODIGO, BOM_STRUCT.FACTCONV, BOM_STRUCT.BST_PERINI, 
				                      BOM_STRUCT.BST_PERFIN, BOM_STRUCT.ME_GEN, BOM_STRUCT.BST_TRANS, MAESTRO.BST_TIPOCOSTO, 
					         REPLACE(BOM_STRUCT.BST_TIP_ENS,'A','F'), FED_CANT, FE_CODIGO, 'B'+CONVERT(VARCHAR(20),@nivel), @BST_TIPODESC,
					        BST_PT, FED_INDICED, BSU_SUBENSAMBLE, BST_ENTRAVIGOR, MAESTRO.MA_PESO_KG, isnull((SELECT max(MA_COSTO) FROM VMAESTROCOST
					WHERE MA_CODIGO=BOM_STRUCT.BST_HIJO and spi_codigo=22),0)
				FROM         BOM_DESCTEMP INNER JOIN
	                      		BOM_STRUCT ON BOM_DESCTEMP.BST_HIJO = BOM_STRUCT.BSU_SUBENSAMBLE AND
				                      BOM_STRUCT.BST_PERINI <= BOM_DESCTEMP.BST_ENTRAVIGOR AND 
				                      BOM_STRUCT.BST_PERFIN >= BOM_DESCTEMP.BST_ENTRAVIGOR LEFT OUTER JOIN
				                      MAESTRO ON BOM_STRUCT.BST_HIJO = MAESTRO.MA_CODIGO LEFT OUTER JOIN
				                      CONFIGURATIPO ON MAESTRO.TI_CODIGO = CONFIGURATIPO.TI_CODIGO
				WHERE BOM_DESCTEMP.FED_INDICED=@FED_INDICED AND (BOM_DESCTEMP.MA_TIP_ENS ='F' OR BOM_DESCTEMP.MA_TIP_ENS IS NULL OR
					(BOM_DESCTEMP.MA_TIP_ENS = 'A' AND BOM_DESCTEMP.BST_PERTENECE NOT IN (SELECT MA_CODIGO FROM VPIDESCARGA)))
					AND CONVERT(INT,REPLACE(BOM_DESCTEMP.BST_NIVEL,'B',''))=@nivel-1
				AND BOM_STRUCT.BST_HIJO IS NOT NULL AND BOM_STRUCT.BST_INCORPOR >0
	
	
		END
	
	
	
	
			if (SELECT     COUNT(*)
			    FROM         BOM_DESCTEMP
			    WHERE     CONVERT(INT,REPLACE(BOM_DESCTEMP.BST_NIVEL,'B','')) =@nivel-1
			    AND FED_INDICED=@FED_INDICED
			    AND (TI_CODIGO='S' OR TI_CODIGO='P') 
			    AND MA_TIP_ENS<>'P' AND MA_TIP_ENS<>'C')>0
	
			set @existe=1
			else
			set @existe=0
	
	
		while (@existe>0)	
		begin
	
			goto inicio
	
	
		end

	end
GO
