SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE dbo.SP_CHECAPERFACTCONS (@FC_FOLIO VARCHAR(15),@FC_TIPO CHAR, @CP_CODIGO INTEGER,@FC_INI DATETIME,@FC_FIN DATETIME,@AGT_CODIGO INTEGER,@RESULT BIT OUTPUT)   as

SET NOCOUNT ON 

DECLARE @INICIAL DATETIME,@FINAL DATETIME;
DECLARE CURSOR_CHKFCTCONS CURSOR FOR
	SELECT FC_INI,FC_FIN FROM FACTCONS 
	WHERE FC_FOLIO=@FC_FOLIO AND FC_TIPO=@FC_TIPO AND CP_CODIGO=@CP_CODIGO AND AGT_CODIGO=@AGT_CODIGO
OPEN CURSOR_CHKFCTCONS
FETCH NEXT FROM CURSOR_CHKFCTCONS INTO @INICIAL,@FINAL
SELECT @RESULT = 1
WHILE (@@FETCH_STATUS = 0) AND (@RESULT = 1)
BEGIN

	IF @FC_INI > @INICIAL
	BEGIN
              	IF @FC_FIN < @FINAL
			SELECT @RESULT=0
                   
	END
	ELSE
	IF @FC_INI < @INICIAL
	BEGIN
		IF @FC_FIN > @FINAL
			SELECT @RESULT=0
	END
	ELSE
		SELECT @RESULT=0

	FETCH NEXT FROM CURSOR_CHKFCTCONS INTO @INICIAL,@FINAL
END
CLOSE CURSOR_CHKFCTCONS
DEALLOCATE CURSOR_CHKFCTCONS
RETURN


GO
