SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO






/* hace la suma de peso mp por subensamble*/
CREATE PROCEDURE [dbo].[SP_CALCULABOMPESOMP]  (@bst_pertenece int, @perini Datetime)   as

SET NOCOUNT ON 
DECLARE @BA_CODIGO INT, @MA_CODIGO INT, @BA_PESO decimal(38,6), @VALUE INT, @Fecha DateTime

	SET @Fecha =convert(datetime, convert(varchar(11), getdate(),101))



DECLARE CUR_BOMPESTOT CURSOR FOR

/*Costo Materia prima */
SELECT     dbo.BOM_STRUCT.BSU_SUBENSAMBLE, SUM(isnull(dbo.MAESTRO.MA_PESO_KG,0) * isnull(dbo.BOM_STRUCT.BST_INCORPOR,0)) AS MA_PESO
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
WHERE     (dbo.BOM_STRUCT.BST_PERFIN >= @perini) AND (dbo.BOM_STRUCT.BST_PERINI <= @perini)
AND      (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @bst_pertenece) AND --(dbo.CONFIGURATIPO.CFT_TIPO <> 'S') AND 
		(dbo.CONFIGURATIPO.CFT_TIPO <> 'P')
GROUP BY dbo.BOM_STRUCT.BSU_SUBENSAMBLE



OPEN CUR_BOMPESTOT

FETCH NEXT FROM CUR_BOMPESTOT INTO @MA_CODIGO,  @BA_PESO

WHILE (@@FETCH_STATUS = 0) 
BEGIN

	begin tran
	UPDATE MAESTRO
	SET MA_PESO_KG = round(@BA_PESO,6)
	WHERE MA_CODIGO = @MA_CODIGO


	UPDATE MAESTRO
	SET MA_PESO_LB = round(@BA_PESO*2.20462442018378,6)
	WHERE MA_CODIGO = @MA_CODIGO

	commit tran

FETCH NEXT FROM CUR_BOMPESTOT INTO @MA_CODIGO,  @BA_PESO

END

CLOSE CUR_BOMPESTOT
DEALLOCATE CUR_BOMPESTOT





GO
