SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO





































/* inserta en la tabla TempBOM_CALCULABASE  los del nivel diferentes del 1 el bom  para calculo de costos y calculo de aranceles*/
CREATE PROCEDURE [dbo].[SP_FILL_BOMDESCTEMP1base] (@BST_PT INT, @BST_HIJO INT, @BST_ENTRAVIGOR DATETIME, @BST_PERINI DATETIME, @CF_USATIPOADQUISICION char(1), @BST_INCORPOR1 decimal(38,6), @CF_NIVELES int, @nivel int)   as

SET NOCOUNT ON 
declare @BST_HIJO1 int, @BST_INCORPOR decimal(38,6), @BST_PERINI1 datetime, @nivelr int, @bst_perini2 datetime, @incorporacionfinal decimal(38,6), @cf_pais_mx int 

select @cf_pais_mx=cf_pais_mx from configuracion

	SET @nivelr=@nivel+1

			insert into TempBOM_CALCULABASE(BST_CODIGO,BST_PT, BST_ENTRAVIGOR, BST_HIJO, BST_INCORPOR, 
			    BST_DISCH, TI_CODIGO, ME_CODIGO, FACTCONV, BST_PERINI, BST_PERFIN, ME_GEN, 
			    BST_TRANS, BST_TIPOCOSTO, MA_TIP_ENS, BST_NIVEL, BST_PERTENECE, PA_CODIGO, AR_CODIGO)

			SELECT BST_CODIGO,@BST_PT, @BST_ENTRAVIGOR, dbo.BOM_STRUCT.BST_HIJO, 
				sum((BOM_STRUCT.BST_INCORPOR+(CASE WHEN isnull(MAESTRO.MA_POR_DESP,0)<0 and isnull(MAESTRO.MA_POR_DESP,0)<>0 then ((BOM_STRUCT.BST_INCORPOR*MAESTRO.MA_POR_DESP)/100)
					         else 0 end)))*@BST_INCORPOR1 AS BST_INCORPOR, dbo.BOM_STRUCT.BST_DISCH, 
			                      dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, 
			                      dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, 
			                      dbo.BOM_STRUCT.BST_TIP_ENS, @nivelr, @BST_HIJO,
				dbo.MAESTRO.PA_ORIGEN, MAX(dbo.MAESTRO.AR_IMPFO)
			FROM         dbo.BOM_STRUCT LEFT OUTER JOIN
				                      dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN
				                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
			WHERE ((dbo.CONFIGURATIPO.CFT_TIPO<>'P' and dbo.CONFIGURATIPO.CFT_TIPO<>'S') and (dbo.BOM_STRUCT.BST_TIP_ENS='C' or dbo.BOM_STRUCT.BST_TIP_ENS is null))
			or ((dbo.CONFIGURATIPO.CFT_TIPO='P' or dbo.CONFIGURATIPO.CFT_TIPO='S') and (dbo.BOM_STRUCT.BST_TIP_ENS='C' or dbo.BOM_STRUCT.BST_TIP_ENS='A' or dbo.BOM_STRUCT.BST_TIP_ENS='E' or dbo.BOM_STRUCT.BST_TIP_ENS='O'))
			GROUP BY BST_CODIGO, dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_DISCH, dbo.CONFIGURATIPO.CFT_TIPO, dbo.BOM_STRUCT.ME_CODIGO, 
			                      dbo.BOM_STRUCT.FACTCONV, dbo.BOM_STRUCT.BST_PERINI, dbo.BOM_STRUCT.BST_PERFIN, dbo.BOM_STRUCT.ME_GEN, 
			                      dbo.BOM_STRUCT.BST_TRANS, dbo.MAESTRO.BST_TIPOCOSTO, dbo.BOM_STRUCT.BST_TIP_ENS, dbo.BOM_STRUCT.BSU_SUBENSAMBLE, 
			                      dbo.BOM_STRUCT.BST_INCORPOR, dbo.MAESTRO.PA_ORIGEN
			HAVING     (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_hijo) 
			AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <=  @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>=  @BST_ENTRAVIGOR)
			AND dbo.BOM_STRUCT.BST_INCORPOR >0 AND (dbo.BOM_STRUCT.BST_TIP_ENS<>'P')
			ORDER BY dbo.BOM_STRUCT.BST_HIJO



DECLARE @CursorVar CURSOR

SET @CursorVar = CURSOR SCROLL DYNAMIC FOR

SELECT     dbo.BOM_STRUCT.BST_HIJO, SUM(dbo.BOM_STRUCT.BST_INCORPOR) AS BST_INCORPOR, dbo.BOM_STRUCT.BST_PERINI
FROM         dbo.BOM_STRUCT LEFT OUTER JOIN dbo.MAESTRO ON dbo.BOM_STRUCT.BST_HIJO = dbo.MAESTRO.MA_CODIGO LEFT OUTER JOIN 
                      dbo.CONFIGURATIPO ON dbo.MAESTRO.TI_CODIGO = dbo.CONFIGURATIPO.TI_CODIGO
WHERE     (dbo.CONFIGURATIPO.CFT_TIPO = 'P' OR dbo.CONFIGURATIPO.CFT_TIPO = 'S') 
	AND (dbo.BOM_STRUCT.BST_TIP_ENS = 'F' OR dbo.BOM_STRUCT.BST_TIP_ENS IS NULL)
	AND (dbo.BOM_STRUCT.BSU_SUBENSAMBLE = @BST_hijo) 
	AND dbo.BOM_STRUCT.BST_HIJO IS NOT NULL AND (dbo.BOM_STRUCT.BST_PERINI <=  @BST_ENTRAVIGOR and dbo.BOM_STRUCT.BST_PERFIN>=  @BST_ENTRAVIGOR)
	AND dbo.BOM_STRUCT.BST_INCORPOR >0 AND (dbo.BOM_STRUCT.BST_TIP_ENS<>'P')
GROUP BY dbo.BOM_STRUCT.BST_HIJO, dbo.BOM_STRUCT.BST_PERINI
ORDER BY dbo.BOM_STRUCT.BST_HIJO


 OPEN @CursorVar

	FETCH NEXT FROM @CursorVar INTO @BST_HIJO1, @BST_INCORPOR, @BST_PERINI1

  WHILE (@@fetch_status = 0) 

  BEGIN  

	set @incorporacionfinal=@BST_INCORPOR* @BST_INCORPOR1

	exec  SP_FILL_BOMDESCTEMP1base @BST_PT, @BST_HIJO1, @BST_ENTRAVIGOR,
	@BST_PERINI1, @CF_USATIPOADQUISICION, @incorporacionfinal, @CF_NIVELES, @nivelr

	FETCH NEXT FROM @CursorVar INTO @BST_HIJO1, @BST_INCORPOR, @BST_PERINI1

END

	CLOSE @CursorVar
	DEALLOCATE @CursorVar

return 0















GO
