SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_GENERAFACTEXPF4SEPARA] (@FE_CODIGO INT)   as

declare @folio varchar(25), @PI_CODIGO int, @fe_folio varchar(25), @CONSECUTIVO int, @fe_fecha varchar(11), @fed_indiced int

	select @folio=fe_folio, @fe_fecha=convert(varchar(11),fe_fecha,101) from factexp where fe_codigo=@FE_CODIGO

	exec sp_CreaFactExpDetTempF4
	
	DECLARE CUR_FACTEXPF4 CURSOR FOR
		SELECT     PEDIMPDET.PI_CODIGO
		FROM         KARDESPED INNER JOIN
		                      PEDIMPDET ON KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED INNER JOIN
		                      MAESTRO ON PEDIMPDET.MA_CODIGO = MAESTRO.MA_CODIGO
		WHERE     (KARDESPED.KAP_FACTRANS = @FE_CODIGO)
		AND (KARDESPED.KAP_INDICED_PED IS NOT NULL)
		GROUP BY PEDIMPDET.PI_CODIGO
		ORDER BY PEDIMPDET.PI_CODIGO

	OPEN CUR_FACTEXPF4
	
	FETCH NEXT FROM CUR_FACTEXPF4 INTO @PI_CODIGO
	
	WHILE (@@FETCH_STATUS = 0) 
	BEGIN

		if exists (select * from factexp where fe_folio like @folio+'_%' and fe_folio not like @folio+' _%')
		begin
	               --SET @fe_folio= @folio+'_'+convert(varchar(50),(SELECT max(convert(smallint,REPLACE(RIGHT(fe_folio, 2), '_', '')))+1  FROM factexp where fe_folio like @folio+'_%' and fe_folio not like @folio+' _%'))
			--Yolanda Avila (2009-05-19)
			SET @fe_folio= @folio+'_'+convert(varchar(50),(select max(convert(smallint, replace(REPLACE(fe_folio, @folio,''), '_','')))+1 from factexp  where fe_folio like @folio+'_%' and fe_folio not like @folio+' _%'))

		end
		else
		       SET @fe_folio= @folio+'_02'


		 EXEC SP_GETCONSECUTIVO @TIPO='FE', @VALUE=@CONSECUTIVO OUTPUT


		INSERT INTO FACTEXP(FE_CODIGO, FE_FOLIO, FE_FECHA, TF_CODIGO, TQ_CODIGO, FE_TIPO, FE_PINICIAL, FE_PFINAL, FC_CODIGO, TN_CODIGO, FE_NO_SEM, 
		                      FE_DOCUMENTO, FE_DESTINO, AG_MX, AG_US, CL_PROD, DI_PROD, CL_COMP, DI_COMP, CO_COMP, CL_COMPFIN, DI_COMPFIN, CO_COMPFIN, 
		                      CL_EXP, DI_EXP, CL_EXPFIN, DI_EXPFIN, CL_DESTINI, DI_DESTINI, CO_DESTINI, CL_DESTFIN, DI_DESTFIN, CO_DESTFIN, CL_VEND, DI_VEND, 
		                      CL_IMP, DI_IMP, CO_IMP, PU_CARGA, PU_SALIDA, PU_ENTRADA, PU_DESTINO, FE_FEC_ENV, FE_FEC_ARR, FE_NUM_ENV, FE_ENV_INST, 
		                      FE_ORD_COMP, FE_NUM_CTL, FE_NUM_INBON, FE_TIPO_INBON, FE_FEC_INBON, FE_FIRMS, FE_COMENTA, FE_COMENTAUS, US_CODIGO, 
		                      CT_COMPANY1, CA_COMPANY1, CJ_COMPANY1, CT_COMPANY2, CA_COMPANY2, CJ_COMPANY2, FE_TRAC_US1, FE_TRAC_MX1, FE_CONT1_REG, 
		                      FE_CONT1_US, FE_CONT1_SELL, TCA_CONT1, PG_COMPANY1, FE_TRAC_CHO1, FE_LIM1, RU_COMPANY1, FE_TPAGO_FLETE1, 
		                      FE_TPAGO_FLETE2, IT_COMPANY1, MT_COMPANY1, FE_GUIA1, FE_TRAC_US2, FE_TRAC_MX2, 
		                      FE_CONT2_REG, FE_CONT2_US, FE_CONT2_SELL, TCA_CONT2, PG_COMPANY2, FE_TRAC_CHO2, FE_LIM2, RU_COMPANY2, 
		                      IT_COMPANY2, MT_COMPANY2, FE_GUIA2, FE_TOTALB, FE_TIPOCAMBIO, FE_MANIF, FE_MANIF_DATE, 
		                      FE_AWB, FE_INCOTLUGAR1, FE_INCOTLUGAR2, FE_LAGNO, FE_DESCARGADA, FE_FACTAGRU, FE_ESTATUS, FE_CANCELADO, FE_MOSTRARDIV, 
		                      MO_CODIGO, SPI_CODIGO, FE_CON_PEDCR, FE_DESCRIPTION1, FE_DESCRIPTION2, FE_INVOICETYPE, FE_HEADER, FE_FOOTER, FE_COMENTACO, 
		                      ALM_CODIGO, FE_DISCHCONTENEDOR1, PI_CODIGO, PI_RECTIFICA, PI_TRANS, FE_DESCARGABLE, FE_USACONSOLIDADO, FE_SEL, FE_AUXDESC, 
		                      FE_BARCODE, FE_PREVIADESC, FE_DESCSUST, BC_CODIGO, FE_DESCITALICA, FE_FECHADESCARGA, FE_CUENTADET, FE_CONSECUTIVOPED, 
		                      FE_TRANSNOORIG, FE_TRANSNO, FE_GAFETECHOFER, AGT_CODIGO, FE_DESCMANUAL, ETC_CODIGO, ET_CODIGO, FE_NUMVEHICULOS, 
		                      FE_PRIORIDAD, CP_CODIGO, FE_USAPESODESP, FEG_CODIGO, FE_PROCESOSUBMAQ, FE_INICIOCRUCE, FE_FIRMAAVISO, FE_FIRMAELECTAVANZ, 
		                      FE_BARCODEREMESA, BC_REMESA)
		
		
		SELECT     @CONSECUTIVO, @fe_folio, FE_FECHA, TF_CODIGO, TQ_CODIGO, FE_TIPO, FE_PINICIAL, FE_PFINAL, FC_CODIGO, TN_CODIGO, FE_NO_SEM, 
		                      FE_DOCUMENTO, FE_DESTINO, AG_MX, AG_US, CL_PROD, DI_PROD, CL_COMP, DI_COMP, CO_COMP, CL_COMPFIN, DI_COMPFIN, CO_COMPFIN, 
		                      CL_EXP, DI_EXP, CL_EXPFIN, DI_EXPFIN, CL_DESTINI, DI_DESTINI, CO_DESTINI, CL_DESTFIN, DI_DESTFIN, CO_DESTFIN, CL_VEND, DI_VEND, 
		                      CL_IMP, DI_IMP, CO_IMP, PU_CARGA, PU_SALIDA, PU_ENTRADA, PU_DESTINO, FE_FEC_ENV, FE_FEC_ARR, FE_NUM_ENV, FE_ENV_INST, 
		                      FE_ORD_COMP, FE_NUM_CTL, FE_NUM_INBON, FE_TIPO_INBON, FE_FEC_INBON, FE_FIRMS, FE_COMENTA, FE_COMENTAUS, US_CODIGO, 
		                      CT_COMPANY1, CA_COMPANY1, CJ_COMPANY1, CT_COMPANY2, CA_COMPANY2, CJ_COMPANY2, FE_TRAC_US1, FE_TRAC_MX1, FE_CONT1_REG, 
		                      FE_CONT1_US, FE_CONT1_SELL, TCA_CONT1, PG_COMPANY1, FE_TRAC_CHO1, FE_LIM1, RU_COMPANY1, FE_TPAGO_FLETE1, 
		                      FE_TPAGO_FLETE2, IT_COMPANY1, MT_COMPANY1, FE_GUIA1, FE_TRAC_US2, FE_TRAC_MX2, 
		                      FE_CONT2_REG, FE_CONT2_US, FE_CONT2_SELL, TCA_CONT2, PG_COMPANY2, FE_TRAC_CHO2, FE_LIM2, RU_COMPANY2, 
		                      IT_COMPANY2, MT_COMPANY2, FE_GUIA2, FE_TOTALB, FE_TIPOCAMBIO, FE_MANIF, FE_MANIF_DATE, 
		                      FE_AWB, FE_INCOTLUGAR1, FE_INCOTLUGAR2, FE_LAGNO, FE_DESCARGADA, FE_FACTAGRU, FE_ESTATUS, FE_CANCELADO, FE_MOSTRARDIV, 
		                      MO_CODIGO, SPI_CODIGO, FE_CON_PEDCR, FE_DESCRIPTION1, FE_DESCRIPTION2, FE_INVOICETYPE, FE_HEADER, FE_FOOTER, FE_COMENTACO, 
		                      ALM_CODIGO, FE_DISCHCONTENEDOR1, PI_CODIGO, PI_RECTIFICA, PI_TRANS, FE_DESCARGABLE, FE_USACONSOLIDADO, FE_SEL, FE_AUXDESC, 
		                      FE_BARCODE, FE_PREVIADESC, FE_DESCSUST, BC_CODIGO, FE_DESCITALICA, FE_FECHADESCARGA, FE_CUENTADET, FE_CONSECUTIVOPED, 
		                      FE_TRANSNOORIG, FE_TRANSNO, FE_GAFETECHOFER, AGT_CODIGO, FE_DESCMANUAL, ETC_CODIGO, ET_CODIGO, FE_NUMVEHICULOS, 
		                      FE_PRIORIDAD, CP_CODIGO, FE_USAPESODESP, FEG_CODIGO, FE_PROCESOSUBMAQ, FE_INICIOCRUCE, FE_FIRMAAVISO, FE_FIRMAELECTAVANZ, 
		                      FE_BARCODEREMESA, BC_REMESA
		FROM         FACTEXP
		WHERE FE_CODIGO=@FE_CODIGO



		INSERT INTO FactExpDetTempF4 (FE_CODIGO, FED_CANT, FED_NOPARTE, MA_CODIGO, PID_INDICED, FED_COS_UNI, TI_CODIGO,
		FED_NOMBRE, FED_NAME, FED_PES_UNI, PA_CODIGO, MA_GENERICO, EQ_GEN, AR_EXPMX, AR_IMPFO, EQ_IMPFO, FED_DISCHARGE, FED_TIP_ENS,
		FED_RATEIMPFO, ME_CODIGO, ME_GENERICO, ME_AREXPMX, FED_GRA_MP, FED_GRA_MO, FED_GRA_EMP, FED_GRA_ADD, 
		FED_GRA_GI, FED_GRA_GI_MX, FED_NG_MP, FED_NG_EMP, FED_NG_ADD, FED_NG_USA, TCO_CODIGO, FED_NAFTA, FED_DEF_TIP, FED_POR_DEF, FED_SECF4)

		SELECT    @CONSECUTIVO, SUM(dbo.Trunc(KARDESPED.KAP_CANTDESC / ISNULL(PEDIMPDET.EQ_GENERICO, 1), 6)), 
		                      PEDIMPDET.PID_NOPARTE, PEDIMPDET.MA_CODIGO, PEDIMPDET.PID_INDICED, MAX(PEDIMPDET.PID_COS_UNI), 
		                      PEDIMPDET.TI_CODIGO, PEDIMPDET.PID_NOMBRE, PEDIMPDET.PID_NAME, 'MA_PESO_KG'=CASE WHEN MAX(PEDIMPDET.ME_CODIGO)=36 then 1 when MAX(PEDIMPDET.ME_CODIGO)=43 then 0.453592 else isnull(MAX(MAESTRO.MA_PESO_KG),0) end,
			        MAX(PEDIMPDET.PA_ORIGEN), PEDIMPDET.MA_GENERICO, EQ_GENERICO, ISNULL(PEDIMPDET.AR_IMPMX,0), ISNULL(MAX(MAESTRO.AR_IMPFO),0), MAESTRO.EQ_IMPFO, 
			        'S', MAX(MAESTRO.MA_TIP_ENS), 0, MAX(PEDIMPDET.ME_CODIGO),
			        isnull((SELECT ME_COM FROM VMAESTRO_GENERICO WHERE MA_CODIGO=PEDIMPDET.MA_GENERICO),19), 
			        isnull((SELECT ME_CODIGO FROM ARANCEL WHERE AR_CODIGO = PEDIMPDET.AR_IMPMX),0),0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			        isnull(MAX(PEDIMPDET.TCO_CODIGO),0), 'N', MAX(PEDIMPDET.PID_DEF_TIP), MAX(PEDIMPDET.PID_POR_DEF), PEDIMPDET.PID_SECUENCIA
		FROM         KARDESPED INNER JOIN
		                      PEDIMPDET ON KARDESPED.KAP_INDICED_PED = PEDIMPDET.PID_INDICED INNER JOIN
		                      MAESTRO ON PEDIMPDET.MA_CODIGO = MAESTRO.MA_CODIGO
		WHERE     (KARDESPED.KAP_FACTRANS = @FE_CODIGO) AND (PEDIMPDET.PI_CODIGO=@PI_CODIGO)
		GROUP BY PEDIMPDET.PI_CODIGO, PEDIMPDET.PID_NOPARTE, PEDIMPDET.MA_CODIGO, PEDIMPDET.PID_INDICED, PEDIMPDET.AR_IMPMX, 
		                      KARDESPED.KAP_INDICED_PED, PEDIMPDET.TI_CODIGO, PEDIMPDET.PID_NOMBRE, PEDIMPDET.PID_NAME, EQ_GENERICO, MAESTRO.EQ_IMPFO,
			        PEDIMPDET.MA_GENERICO, PEDIMPDET.PID_SECUENCIA
		HAVING      (KARDESPED.KAP_INDICED_PED IS NOT NULL)
		ORDER BY KARDESPED.KAP_INDICED_PED




		FETCH NEXT FROM CUR_FACTEXPF4 INTO @PI_CODIGO
	
	END
	
	CLOSE CUR_FACTEXPF4
	DEALLOCATE CUR_FACTEXPF4



	if (select tf_codigo from factexp where fe_codigo=@FE_CODIGO)= (select tf_codigo from tfactura where tf_nombre='REGULARIZACION (MATERIAL VENCIDO)')
	begin

		UPDATE FactExpDetTempF4
		SET FED_DEF_TIP='G',
			FED_POR_DEF=(select ar_advdef from arancel where ar_codigo=AR_EXPMX),
			SPI_CODIGO=0,
			FED_SEC_IMP=0
		WHERE FE_CODIGO in (select fe_codigo from FactExpDetTempF4)

	end


	-- calculos despues de la insercion
	UPDATE FactExpDetTempF4
	SET FED_NAFTA=dbo.GetNafta (@fe_fecha, FactExpDetTempF4.MA_CODIGO, FactExpDetTempF4.AR_IMPMX, FactExpDetTempF4.PA_CODIGO, FactExpDetTempF4.FED_DEF_TIP, FactExpDetTempF4.FED_TIP_ENS)
	WHERE FE_CODIGO in (select fe_codigo from FactExpDetTempF4)

	UPDATE FactExpDetTempF4
	SET FED_RATEIMPFO=(CASE WHEN FED_NAFTA='S' THEN 0 ELSE dbo.GetAdvalorem(AR_IMPFO, 0, 'G', 0, 0) END)
	WHERE FE_CODIGO in (select fe_codigo from FactExpDetTempF4)


	UPDATE FactExpDetTempF4
	SET FED_COS_TOT= round(isnull(FED_COS_UNI*FED_CANT,0),6),
	FED_PES_NET= round(isnull(FED_CANT* FED_PES_UNI,0),6), 
	FED_PES_NETLB=round(isnull(FED_CANT* FED_PES_UNI * 2.20462442018378,0),6),
	FED_PES_BRU=round(isnull(FED_CANT* FED_PES_UNI,0),6), 
	FED_PES_BRULB=round(isnull(FED_CANT* FED_PES_UNI * 2.20462442018378,0),6),
	FED_PES_UNILB=round(isnull(FED_PES_UNI*2.20462442018378,0),6)
	WHERE FE_CODIGO in (select fe_codigo from FactExpDetTempF4)

	UPDATE FactExpDetTempF4
	SET ME_AREXPMX=isnull((SELECT ME_CODIGO FROM ARANCEL WHERE AR_CODIGO = FactExpDetTempF4.AR_EXPMX),19)
	WHERE FE_CODIGO in (select fe_codigo from FactExpDetTempF4)


	  if (SELECT CF_USACARGOCOSTO FROM CONFIGURACION) <> 'N'  
	  begin
		  if (SELECT CF_USACARGOCOSTO FROM CONFIGURACION) = 'S' 
		  begin
			INSERT INTO FactExpDetTempF4CARGO(CAR_CODIGO, FEG_VALOR, FEG_TIPO, FE_CODIGO, FED_INDICED)
			SELECT     dbo.CARGORELARANCEL.CAR_CODIGO, dbo.CARGODET.CARD_VALOR, dbo.CARGO.CAR_TIPO,  dbo.FactExpDetTempF4.FE_CODIGO, 
			                      dbo.FactExpDetTempF4.FED_INDICED
			FROM         dbo.FactExpDetTempF4 INNER JOIN
			                      dbo.MAESTRO ON dbo.FactExpDetTempF4.MA_CODIGO = dbo.MAESTRO.MA_CODIGO INNER JOIN
			                      dbo.FACTEXP ON dbo.FactExpDetTempF4.FE_CODIGO = dbo.FACTEXP.FE_CODIGO INNER JOIN
			                      dbo.CARGORELARANCEL INNER JOIN
			                      dbo.CARGODET ON dbo.CARGORELARANCEL.CAR_CODIGO = dbo.CARGODET.CAR_CODIGO INNER JOIN
			                      dbo.CARGO ON dbo.CARGORELARANCEL.CAR_CODIGO = dbo.CARGO.CAR_CODIGO ON 
			                      dbo.FACTEXP.FE_FECHA >= dbo.CARGODET.CARD_FECHAINI AND dbo.FACTEXP.FE_FECHA <= dbo.CARGODET.CARD_FECHAFIN AND 
			                      dbo.FACTEXP.CL_DESTINI = dbo.CARGORELARANCEL.CL_CODIGO AND dbo.MAESTRO.AR_EXPMX = dbo.CARGORELARANCEL.AR_CODIGO
			WHERE dbo.FactExpDetTempF4.FE_CODIGO in (select fe_codigo from FactExpDetTempF4)
		  end
		  else
		  begin
			INSERT INTO FactExpDetTempF4CARGO(CAR_CODIGO, FEG_VALOR, FEG_TIPO, FE_CODIGO, FED_INDICED)
			SELECT     dbo.CARGORELARANCEL.CAR_CODIGO, dbo.CARGODET.CARD_VALOR, dbo.CARGO.CAR_TIPO,  dbo.FactExpDetTempF4.FE_CODIGO, 
			                      dbo.FactExpDetTempF4.FED_INDICED
			FROM         dbo.FactExpDetTempF4 INNER JOIN
			                      dbo.MAESTRO ON dbo.FactExpDetTempF4.MA_CODIGO = dbo.MAESTRO.MA_CODIGO INNER JOIN
			                      dbo.FACTEXP ON dbo.FactExpDetTempF4.FE_CODIGO = dbo.FACTEXP.FE_CODIGO INNER JOIN
			                      dbo.CARGORELARANCEL INNER JOIN
			                      dbo.CARGODET ON dbo.CARGORELARANCEL.CAR_CODIGO = dbo.CARGODET.CAR_CODIGO INNER JOIN
			                      dbo.CARGO ON dbo.CARGORELARANCEL.CAR_CODIGO = dbo.CARGO.CAR_CODIGO ON 
			                      dbo.FACTEXP.FE_FECHA >= dbo.CARGODET.CARD_FECHAINI AND dbo.FACTEXP.FE_FECHA <= dbo.CARGODET.CARD_FECHAFIN AND 
			                      dbo.FACTEXP.CL_DESTINI = dbo.CARGORELARANCEL.CL_CODIGO AND dbo.MAESTRO.LIN_CODIGO = dbo.CARGORELARANCEL.LIN_CODIGO
			WHERE dbo.FactExpDetTempF4.FE_CODIGO in (select fe_codigo from FactExpDetTempF4)
		  end
	end	



	update FactExpDetTempF4	set ar_orig= case when fed_nafta='S' then
		 0 else ( case when isnull((select max(ar_codigo) from bom_arancel where ba_tipocosto='N' and bom_arancel.ma_codigo=FactExpDetTempF4.ma_codigo),0)=0 
		then  isnull((select AR_IMPFOUSA from maestro where maestro.ma_codigo=FactExpDetTempF4.ma_codigo),0)  else isnull((select max(ar_codigo) from bom_arancel where ba_tipocosto='N' and bom_arancel.ma_codigo=FactExpDetTempF4.ma_codigo),0) end) end
	where (ar_orig is null or ar_orig =0) and fed_retrabajo<>'R' and ti_codigo in (select ti_codigo from configuratipo where cft_tipo='P' or cft_tipo='S') and fed_tip_ens<>'C'
	and fed_ng_usa>0 and fe_codigo in (select fe_codigo from FactExpDetTempF4)
	

	update FactExpDetTempF4
	set ar_ng_emp= case when fed_nafta='S' then
	 0 else isnull((select max(ar_codigo) from bom_arancel where ba_tipocosto='3' and bom_arancel.ma_codigo=FactExpDetTempF4.ma_codigo),0) end
	where (ar_ng_emp is null or ar_ng_emp =0) and fed_retrabajo<>'R' and ti_codigo in (select ti_codigo from configuratipo where cft_tipo='P' or cft_tipo='S') and fed_tip_ens<>'C'
	and fed_ng_emp>0 and fe_codigo in (select fe_codigo from FactExpDetTempF4)


	UPDATE dbo.FactExpDetTempF4
	SET     dbo.FactExpDetTempF4.FED_DESTNAFTA= CASE 
	when dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT CF_PAIS_MX FROM CONFIGURACION) THEN 'M'
	 when dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT CF_PAIS_USA FROM CONFIGURACION) or dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT CF_PAIS_CA FROM CONFIGURACION)
	then 'N'  WHEN 	  dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT PA_CODIGO FROM PAIS WHERE SPI_CODIGO IN ( SELECT SPI_CODIGO FROM SPI WHERE SPI_CLAVE='MX-UE')) 
	then 'U' when 	  dbo.DIR_CLIENTE.PA_CODIGO IN (SELECT PA_CODIGO FROM PAIS WHERE SPI_CODIGO IN ( SELECT SPI_CODIGO FROM SPI WHERE SPI_CLAVE='AELC')) 
	then 'A'  else 'F' end
	FROM         dbo.FactExpDetTempF4 INNER JOIN
	                      dbo.FACTEXP ON dbo.FactExpDetTempF4.FE_CODIGO = dbo.FACTEXP.FE_CODIGO LEFT OUTER JOIN
	                      dbo.DIR_CLIENTE ON dbo.FACTEXP.DI_DESTFIN = dbo.DIR_CLIENTE.DI_INDICE
	where  dbo.FactExpDetTempF4.FE_CODIGO in (select fe_codigo from FactExpDetTempF4)



	INSERT INTO FACTEXPDET(FED_INDICED, FE_CODIGO, MA_CODIGO, FED_NOMBRE, FED_NOPARTE, FED_NAME, ME_CODIGO, FED_OBSERVA, FED_CANT, FED_GRA_MP, 
	                      FED_GRA_MO, FED_GRA_EMP, FED_GRA_ADD, FED_GRA_GI, FED_GRA_GI_MX, FED_NG_MP, FED_NG_EMP, FED_NG_ADD, FED_NG_USA, 
	                      FED_COS_UNI, FED_COS_TOT, FED_PES_UNI, FED_PES_NET, FED_PES_BRU, FED_PES_UNILB, FED_PES_NETLB, FED_PES_BRULB, 
	                      FED_SEC_IMP, FED_DEF_TIP, FED_POR_DEF, FED_LOTE, AR_IMPMX, AR_EXPMX, AR_IMPFO, FED_CON_PED, MA_GENERICO, PA_CODIGO, 
	                      LE_CODIGO, LED_INDICED, EX_CODIGO, FED_ORD_COMP, FED_NOORDEN, FED_USO_COMMINV, EQ_GEN, EQ_IMPFO, EQ_EXPMX, TI_CODIGO, 
	                      FED_TENVIO, FED_INBOND, FED_TIPOINBOND, FED_RATEEXPMX, FED_RATEIMPFO, FED_RELEMP, FED_FECHA_STRUCT, FED_DISCHARGE, 
	                      LE_FOLIO, SPI_CODIGO, FED_SALDO, FED_RETRABAJO, ADE_CODIGO, MA_EMPAQUE, FED_CANTEMP, FED_FAC_NUM, FED_FEC_ENV, 
	                      FED_CON_CERTORIG, FED_COS_UNI_CO, FED_GRA_MAT_CO, FED_EMP_CO, FED_NG_MAT_CO, FED_VA_CO, FED_CANTGEN, MO_CODIGO, 
	                      FED_DESCARGADO, FED_PARTTYPE, ME_GENERICO, FED_TIP_ENS, PID_INDICED, MA_NOPARTECL, ME_AREXPMX, FED_NAFTA, FED_DEFTXT1, 
	                      FED_DEFTXT2, FED_DEFNO3, FED_DEFNO4, PID_INDICEDLIGA, PID_INDICEDLIGAR1, TCO_CODIGO, PI_ORIGENKITPADRE, CS_CODIGO, 
	                      SE_CODIGO, FED_RELCAJAS, END_INDICED, EN_CODIGO, FED_SALDOTRANS, FED_USOTRANS, FED_USOSALDO, CL_CODIGO, MA_STRUCT, 
	                      FED_DESTNAFTA, AR_ORIG, AR_NG_EMP, FED_NOPARTEAUX, ETA_CODIGO, FED_NG_MX, FED_NOPARTESTRUCT, FED_GENERA_EMPDET, FED_SECF4)
	
	
	SELECT     FED_INDICED, FE_CODIGO, MA_CODIGO, FED_NOMBRE, FED_NOPARTE, FED_NAME, ME_CODIGO, FED_OBSERVA, FED_CANT, FED_GRA_MP, 
	                      FED_GRA_MO, FED_GRA_EMP, FED_GRA_ADD, FED_GRA_GI, FED_GRA_GI_MX, FED_NG_MP, FED_NG_EMP, FED_NG_ADD, FED_NG_USA, 
	                      FED_COS_UNI, FED_COS_TOT, FED_PES_UNI, FED_PES_NET, FED_PES_BRU, FED_PES_UNILB, FED_PES_NETLB, FED_PES_BRULB, 
	                      FED_SEC_IMP, FED_DEF_TIP, FED_POR_DEF, FED_LOTE, ISNULL(AR_IMPMX,0), ISNULL(AR_EXPMX,AR_IMPMX), ISNULL(AR_IMPFO,0), FED_CON_PED, MA_GENERICO, PA_CODIGO, 
	                      LE_CODIGO, LED_INDICED, EX_CODIGO, FED_ORD_COMP, FED_NOORDEN, FED_USO_COMMINV, EQ_GEN, EQ_IMPFO, EQ_EXPMX, TI_CODIGO, 
	                      FED_TENVIO, FED_INBOND, FED_TIPOINBOND, FED_RATEEXPMX, FED_RATEIMPFO, FED_RELEMP, FED_FECHA_STRUCT, FED_DISCHARGE, 
	                      LE_FOLIO, SPI_CODIGO, FED_SALDO, FED_RETRABAJO, ADE_CODIGO, MA_EMPAQUE, FED_CANTEMP, FED_FAC_NUM, FED_FEC_ENV, 
	                      FED_CON_CERTORIG, FED_COS_UNI_CO, FED_GRA_MAT_CO, FED_EMP_CO, FED_NG_MAT_CO, FED_VA_CO, FED_CANTGEN, MO_CODIGO, 
	                      FED_DESCARGADO, FED_PARTTYPE, ME_GENERICO, FED_TIP_ENS, PID_INDICED, MA_NOPARTECL, ME_AREXPMX, FED_NAFTA, FED_DEFTXT1, 
	                      FED_DEFTXT2, FED_DEFNO3, FED_DEFNO4, PID_INDICEDLIGA, PID_INDICEDLIGAR1, TCO_CODIGO, PI_ORIGENKITPADRE, CS_CODIGO, 
	                      SE_CODIGO, FED_RELCAJAS, END_INDICED, EN_CODIGO, FED_SALDOTRANS, FED_USOTRANS, FED_USOSALDO, CL_CODIGO, MA_STRUCT, 
	                      FED_DESTNAFTA, AR_ORIG, AR_NG_EMP, FED_NOPARTEAUX, ETA_CODIGO, FED_NG_MX, FED_NOPARTESTRUCT, FED_GENERA_EMPDET, FED_SECF4
	FROM         FactExpDetTempF4




	UPDATE FACTEXPDET
	SET FED_POR_CERT= CASE WHEN FACTEXPDET.MA_CODIGO IN
			(SELECT  CERTORIGMPDET.MA_CODIGO
			FROM  CERTORIGMPDET INNER JOIN CERTORIGMP ON CERTORIGMPDET.CMP_CODIGO = CERTORIGMP.CMP_CODIGO 
			WHERE  CERTORIGMP.CMP_TIPO<> 'P' AND CERTORIGMPDET.PA_CLASE=FACTEXPDET.PA_CODIGO 
			AND LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCION,'.',''),6)=LEFT(REPLACE(ARANCEL.AR_FRACCION,'.',''),6) AND  CERTORIGMP.SPI_CODIGO IN (SELECT spi_codigo FROM spi  WHERE spi_clave = 'nafta')
			AND CERTORIGMP.CMP_ESTATUS='V' AND  CERTORIGMP.CMP_IFECHA<=FACTEXP.FE_FECHA AND CERTORIGMP.CMP_FECHATRANS>=FACTEXP.FE_FECHA 
			AND CERTORIGMPDET.MA_CODIGO=FACTEXPDET.MA_CODIGO) AND FACTEXPDET.PA_CODIGO  IN (SELECT PA_CODIGO FROM PAIS WHERE PA_CORTO IN ('USA', 'MX', 'CA')) THEN 
			ISNULL((SELECT PAR_BEN FROM PAISARA WHERE AR_CODIGO=FACTEXPDET.AR_EXPMX AND PA_CODIGO=FACTEXPDET.PA_CODIGO),0) ELSE -1 END
	FROM FACTEXPDET INNER JOIN FACTEXP ON FACTEXPDET.FE_CODIGO=FACTEXP.FE_CODIGO 
	LEFT OUTER JOIN ARANCEL ON FACTEXPDET.AR_EXPMX=ARANCEL.AR_CODIGO
	WHERE FACTEXPDET.FE_CODIGO in (select fe_codigo from FactExpDetTempF4) 






	UPDATE FACTEXPDET
	SET FED_FOLIO_CERT= (SELECT  CERTORIGMP.CMP_FOLIO
			FROM  CERTORIGMPDET INNER JOIN CERTORIGMP ON CERTORIGMPDET.CMP_CODIGO = CERTORIGMP.CMP_CODIGO 
			WHERE  CERTORIGMP.CMP_TIPO<> 'P' AND CERTORIGMPDET.PA_CLASE=FACTEXPDET.PA_CODIGO 
			AND LEFT(REPLACE(CERTORIGMPDET.CMP_FRACCION,'.',''),6)=LEFT(REPLACE(ARANCEL.AR_FRACCION,'.',''),6) AND  CERTORIGMP.SPI_CODIGO IN (SELECT spi_codigo FROM spi  WHERE spi_clave = 'nafta')
			AND CERTORIGMP.CMP_ESTATUS='V' AND  CERTORIGMP.CMP_IFECHA<=FACTEXP.FE_FECHA AND CERTORIGMP.CMP_FECHATRANS>=FACTEXP.FE_FECHA 
			AND CERTORIGMPDET.MA_CODIGO=FACTEXPDET.MA_CODIGO)
	FROM FACTEXPDET INNER JOIN FACTEXP ON FACTEXPDET.FE_CODIGO=FACTEXP.FE_CODIGO 
	LEFT OUTER JOIN ARANCEL ON FACTEXPDET.AR_EXPMX=ARANCEL.AR_CODIGO
	WHERE FACTEXPDET.FE_CODIGO in (select fe_codigo from FactExpDetTempF4) AND FACTEXPDET.FED_POR_CERT<>-1




		update factexp
		set fe_cuentadet=(select isnull(count(factexpdet.fe_codigo),0) from factexpdet where factexpdet.fe_codigo =factexp.fe_codigo)
		where fe_codigo  in (select fe_codigo from FactExpDetTempF4)


		UPDATE KARDESPED
		SET     KARDESPED.KAP_FACTRANS= FACTEXPDET.FE_CODIGO, KARDESPED.KAP_INDICED_FACT= FACTEXPDET.FED_INDICED
		FROM         KARDESPED INNER JOIN
		                      FACTEXPDET ON KARDESPED.KAP_INDICED_PED = FACTEXPDET.PID_INDICED
		WHERE     (KARDESPED.KAP_FACTRANS = @FE_CODIGO) AND (FACTEXPDET.FE_CODIGO IN
		                          (SELECT     fe_codigo
		                            FROM          FactExpDetTempF4))


		select @fed_indiced= max(fed_indiced) from factexpdet

		update consecutivo
		set cv_codigo =  isnull(@fed_indiced,0) + 1
		where cv_tipo = 'FED'


		delete from factexp where fe_codigo=@FE_CODIGO

		delete from factexpdet where fe_codigo not in (select fe_codigo from factexp)

	exec sp_droptable 'FactExpDetTempF4'



GO
