SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
































CREATE PROCEDURE [dbo].[SP_temp_13028]   as



		SET IDENTITY_INSERT CATEGPERMISO ON

	UPDATE PERMISODET
	SET     PERMISODET.MA_GENERICO= MAESTRO.MA_CODIGO
	FROM         MAESTRO INNER JOIN
	                      PERMISODET ON MAESTRO.MA_NOPARTE = PERMISODET.MA_NOPARTE 
		       AND MAESTRO.MA_CODIGO <> PERMISODET.MA_GENERICO AND 
	                      MAESTRO.TI_CODIGO = PERMISODET.TI_CODIGO


	INSERT INTO CATEGPERMISO(CPE_CODIGO, CPE_CORTO, CPE_DESC, TI_CODIGO, ME_CODIGO, AR_CODIGO, CPE_CAS_NUM, CPE_COSTO, SE_CODIGO, IDE_CODIGO)
	SELECT     min(PERMISODET.MA_GENERICO), PERMISODET.MA_NOPARTE, MAX(PERMISODET.PED_NOMBRE), MAX(PERMISODET.TI_CODIGO), 
	                      MAX(PERMISODET.ME_COM), MAX(PERMISODET.AR_IMPMX), MAX(PERMISODET.PED_CAS_NUM), MAX(PERMISODET.PED_COSTO), 
	                      MAX(PERMISODET.SE_CODIGO), MAX(PERMISO.IDE_CODIGO)
	FROM         PERMISODET INNER JOIN
	                      PERMISO ON PERMISODET.PE_CODIGO = PERMISO.PE_CODIGO
	GROUP BY PERMISODET.MA_NOPARTE
	HAVING PERMISODET.MA_NOPARTE NOT IN (SELECT CPE_CORTO FROM CATEGPERMISO)
             ORDER BY PERMISODET.MA_NOPARTE

	--ORDER BY  PERMISODET.MA_GENERICO

	SET IDENTITY_INSERT CATEGPERMISO OFF


	/*UPDATE IMPORTSPECDET
	SET     IMPORTSPECDET.IMD_SACARMAESTRO=IMPORTFIELDS.IMF_SACARMAESTRO, IMPORTSPECDET.IMD_SELECTMASTER=
	                      IMPORTFIELDS.IMF_SELECTMASTER
	FROM         IMPORTSPECDET INNER JOIN
	                      IMPORTFIELDS ON IMPORTSPECDET.IMF_CODIGO = IMPORTFIELDS.IMF_CODIGO
           */






























GO
