SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
















CREATE PROCEDURE [dbo].[SP_IMPORTINSERTPERMISODET] (@tabla varchar(150), @ims_cbforma int, @Insert char(1))   as

DECLARE @consecutivo int, @user varchar(10)

select @user = substring(@tabla,charindex('_',@tabla)+1,len(@tabla))

	if @ims_cbforma=21 and @Insert='S'
	begin
		if (select cf_permisoaviso from configuracion)='S'
		begin
			exec ('INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO, RI_CBFORMA,  RI_TIPO, RI_USERID) 
			SELECT ''EL NO. PARTE: '' + MAESTRO.MA_NOPARTE+'' CON FRACCION ''+ARANCEL.AR_FRACCION+'' NO CUENTA CON PERMISO DE IMPORTACION'', 21, ''I'','+@user+
			' FROM         MAESTRO INNER JOIN '+@tabla+' ON MAESTRO.MA_NOPARTE = '+@tabla+'.FACTIMPDET'+@user+'#FID_NOPARTE LEFT OUTER JOIN ARANCEL ON
				MAESTRO.AR_IMPMX=ARANCEL.AR_CODIGO
			WHERE     MAESTRO.MA_INV_GEN = ''I'' AND (convert(varchar(30),MAESTRO.MA_CODIGO)+ convert(varchar(20),MAESTRO.AR_IMPMX) NOT IN
				(SELECT     convert(varchar(30),MAESTROCATEG.MA_CODIGO)+convert(varchar(20),PERMISODET.AR_IMPMX)
				FROM MAESTROCATEG INNER JOIN
				     PERMISODET ON MAESTROCATEG.CPE_CODIGO = PERMISODET.MA_GENERICO LEFT OUTER JOIN
				     IDENTIFICA INNER JOIN
				     PERMISO ON IDENTIFICA.IDE_CODIGO = PERMISO.IDE_CODIGO ON PERMISODET.PE_CODIGO = PERMISO.PE_CODIGO
				WHERE     (PERMISO.PE_APROBADO = ''S'') AND (IDENTIFICA.IDE_CLAVE IN (''MQ'', ''PX''))) OR
				
				MAESTRO.MA_CODIGO NOT IN (SELECT MA_CODIGO FROM MAESTROCATEG WHERE MA_CODIGO=MAESTRO.MA_CODIGO))
			GROUP BY MAESTRO.MA_NOPARTE, ARANCEL.AR_FRACCION')
	
	
	
		end
		else
		if (select cf_permisoaviso from configuracion)='X'
		begin
			exec ('INSERT INTO REGISTROSIMPORTADOS (RI_REGISTRO, RI_CBFORMA, RI_TIPO, RI_USERID) 
			SELECT ''NO SE PUEDE IMPORTAR NO. PARTE: '' + MAESTRO.MA_NOPARTE+'' CON FRACCION ''+ARANCEL.AR_FRACCION+'' PORQUE NO CUENTA CON PERMISO DE IMPORTACION'', 21, ''I'','+@user+
			' FROM         MAESTRO INNER JOIN '+@tabla+' ON MAESTRO.MA_NOPARTE = '+@tabla+'.FACTIMPDET'+@user+'#FID_NOPARTE LEFT OUTER JOIN ARANCEL ON
				MAESTRO.AR_IMPMX=ARANCEL.AR_CODIGO
			WHERE     MAESTRO.MA_INV_GEN = ''I'' AND (convert(varchar(30),MAESTRO.MA_CODIGO)+ convert(varchar(20),MAESTRO.AR_IMPMX) NOT IN
				(SELECT     convert(varchar(30),MAESTROCATEG.MA_CODIGO)+convert(varchar(20),PERMISODET.AR_IMPMX)
				FROM MAESTROCATEG INNER JOIN
				     PERMISODET ON MAESTROCATEG.CPE_CODIGO = PERMISODET.MA_GENERICO LEFT OUTER JOIN
				     IDENTIFICA INNER JOIN
				     PERMISO ON IDENTIFICA.IDE_CODIGO = PERMISO.IDE_CODIGO ON PERMISODET.PE_CODIGO = PERMISO.PE_CODIGO
				WHERE     (PERMISO.PE_APROBADO = ''S'') AND (IDENTIFICA.IDE_CLAVE IN (''MQ'', ''PX''))) OR

				MAESTRO.MA_CODIGO NOT IN (SELECT MA_CODIGO FROM MAESTROCATEG WHERE MA_CODIGO=MAESTRO.MA_CODIGO))
			GROUP BY MAESTRO.MA_NOPARTE, ARANCEL.AR_FRACCION')
	
	
			DELETE FROM FACTIMPDET WHERE FACTIMPDET.FID_NOPARTE IN (SELECT MAESTRO.MA_NOPARTE
				FROM         MAESTRO INNER JOIN FACTIMPDET ON MAESTRO.MA_NOPARTE = FACTIMPDET.FID_NOPARTE
				WHERE     MAESTRO.MA_INV_GEN = 'I' AND convert(varchar(30),MAESTRO.MA_CODIGO)+ convert(varchar(20),MAESTRO.AR_IMPMX) NOT IN
					(SELECT convert(varchar(30),MAESTROCATEG.MA_CODIGO)+convert(varchar(20),PERMISODET.AR_IMPMX) 
					FROM MAESTROCATEG INNER JOIN
					     PERMISODET ON MAESTROCATEG.CPE_CODIGO = PERMISODET.MA_GENERICO LEFT OUTER JOIN
					     IDENTIFICA INNER JOIN
					     PERMISO ON IDENTIFICA.IDE_CODIGO = PERMISO.IDE_CODIGO ON PERMISODET.PE_CODIGO = PERMISO.PE_CODIGO
					WHERE     (PERMISO.PE_APROBADO = 'S') AND (IDENTIFICA.IDE_CLAVE IN ('MQ', 'PX')))
				GROUP BY MAESTRO.MA_NOPARTE)
			AND FI_CODIGO IN (SELECT FI_CODIGO FROM FACTIMP WHERE FI_FOLIO IN 
						(SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FI_FOLIO = ','') FROM REGISTROSIMPORTADOS
						WHERE RI_REGISTRO LIKE 'FI_FOLIO%' AND RI_TIPO='I'))


		end
	end



	DELETE FACTIMPPERM 
	FROM FACTIMPPERM LEFT OUTER JOIN VPERMISODETAR ON FACTIMPPERM.PED_INDICED=VPERMISODETAR.PED_INDICED
		LEFT OUTER JOIN PERMISO ON VPERMISODETAR.PE_CODIGO=PERMISO.PE_CODIGO 
		LEFT OUTER JOIN IDENTIFICA ON PERMISO.IDE_CODIGO=IDENTIFICA.IDE_CODIGO
		LEFT OUTER JOIN FACTIMP ON FACTIMPPERM.FI_CODIGO=FACTIMP.FI_CODIGO
	WHERE FACTIMP.FI_FOLIO  IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FI_FOLIO = ','') FROM REGISTROSIMPORTADOS
						WHERE RI_REGISTRO LIKE 'FI_FOLIO%' AND RI_TIPO='I')




	exec sp_droptable 'FactImpPermTmp'
	CREATE TABLE [dbo].[FactImpPermTmp] (
		[FIR_CODIGO] [int] IDENTITY (1, 1) NOT NULL ,
		[FID_INDICED] [int] NOT NULL ,
		[FI_CODIGO] [int] NOT NULL ,
		[PE_CODIGO] [int] NOT NULL ,
		[PED_INDICED] [int] NOT NULL ,
		[CPE_CODIGO] [int] NULL ,
		[EQ_CANT] decimal(38,6) NULL ,
		[FIP_ESTATUSAFECTA] [smallint] NOT NULL CONSTRAINT [DF_FactImpPermTmp_FIP_ESTATUSAFECTA] DEFAULT (0)
	        ) ON [PRIMARY]
	

	set @consecutivo =(select isnull(max(FIR_CODIGO),0) from FACTIMPPERM)+1

	dbcc checkident (FactImpPermTmp, reseed, @consecutivo) WITH NO_INFOMSGS

	IF (SELECT CF_USADESCSICEX FROM CONFIGURACION)='S' 
	BEGIN

		INSERT INTO FactImpPermTmp(FID_INDICED, FI_CODIGO, PED_INDICED, PE_CODIGO, CPE_CODIGO)
		SELECT     FACTIMPDET.FID_INDICED, FACTIMPDET.FI_CODIGO, MIN(VPERMISODETAR.PED_INDICED) AS PED_INDICED,
			(SELECT PERMISODET2.PE_CODIGO FROM PERMISODET PERMISODET2 WHERE PERMISODET2.PED_INDICED=MIN(VPERMISODETAR.PED_INDICED)),
			(SELECT C1. MA_GENERICO FROM PERMISODET C1 WHERE C1.PED_INDICED=MIN(VPERMISODETAR.PED_INDICED))
		FROM         MAESTROCATEG INNER JOIN
		                      FACTIMPDET INNER JOIN
		                      VPERMISODETAR ON FACTIMPDET.MA_GENERICO = VPERMISODETAR.MA_GENERICO ON 
		                      MAESTROCATEG.MA_CODIGO = FACTIMPDET.MA_CODIGO AND 
		                      VPERMISODETAR.PED_NOMBRE = FACTIMPDET.FID_NOMBRE AND 
		                      MAESTROCATEG.CPE_CODIGO = VPERMISODETAR.MA_GENERICO LEFT OUTER JOIN
		                      PERMISO LEFT OUTER JOIN
		                      IDENTIFICA ON PERMISO.IDE_CODIGO = IDENTIFICA.IDE_CODIGO ON 
				      VPERMISODETAR.PE_CODIGO = PERMISO.PE_CODIGO LEFT OUTER JOIN FACTIMP ON
				      FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
		WHERE     (PERMISO.PE_APROBADO = 'S') AND (PERMISO.PE_FECHA <= FACTIMP.FI_FECHA) AND (IDENTIFICA.IDE_CLAVE IN ('MQ','PX'))
		GROUP BY FACTIMPDET.FID_INDICED, FACTIMPDET.FI_CODIGO, FACTIMP.FI_FOLIO
		HAVING      (FACTIMP.FI_FOLIO  IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FI_FOLIO = ','') FROM REGISTROSIMPORTADOS
							WHERE RI_REGISTRO LIKE 'FI_FOLIO%' AND RI_TIPO='I'))
	END
	ELSE
	BEGIN
		INSERT INTO FactImpPermTmp(FID_INDICED, FI_CODIGO, PED_INDICED, PE_CODIGO, CPE_CODIGO)
		SELECT     FACTIMPDET.FID_INDICED, FACTIMPDET.FI_CODIGO, MIN(VPERMISODETAR.PED_INDICED) AS PED_INDICED,
			(SELECT PERMISODET2.PE_CODIGO FROM PERMISODET PERMISODET2 WHERE PERMISODET2.PED_INDICED=MIN(VPERMISODETAR.PED_INDICED)),
			(SELECT C1. MA_GENERICO FROM PERMISODET C1 WHERE C1.PED_INDICED=MIN(VPERMISODETAR.PED_INDICED))
		FROM         MAESTROCATEG INNER JOIN
		                      FACTIMPDET INNER JOIN
		                      VPERMISODETAR ON FACTIMPDET.MA_GENERICO = VPERMISODETAR.MA_GENERICO ON 
		                      MAESTROCATEG.MA_CODIGO = FACTIMPDET.MA_CODIGO AND 
		                      MAESTROCATEG.CPE_CODIGO = VPERMISODETAR.MA_GENERICO LEFT OUTER JOIN
		                      PERMISO LEFT OUTER JOIN
		                      IDENTIFICA ON PERMISO.IDE_CODIGO = IDENTIFICA.IDE_CODIGO ON 
				      VPERMISODETAR.PE_CODIGO = PERMISO.PE_CODIGO LEFT OUTER JOIN FACTIMP ON
				      FACTIMPDET.FI_CODIGO = FACTIMP.FI_CODIGO
		WHERE     (PERMISO.PE_APROBADO = 'S') AND (PERMISO.PE_FECHA <= FACTIMP.FI_FECHA) AND (IDENTIFICA.IDE_CLAVE IN ('MQ','PX'))
		GROUP BY FACTIMPDET.FID_INDICED, FACTIMPDET.FI_CODIGO, FACTIMP.FI_FOLIO
		HAVING      (FACTIMP.FI_FOLIO  IN (SELECT REPLACE(LEFT(RI_REGISTRO,CHARINDEX(',',RI_REGISTRO)-1),'FI_FOLIO = ','') FROM REGISTROSIMPORTADOS
							WHERE RI_REGISTRO LIKE 'FI_FOLIO%' AND RI_TIPO='I'))

	END	




	UPDATE FactImpPermTmp
	SET EQ_CANT = ISNULL((SELECT EQ_CANT FROM MAESTROCATEG WHERE MA_CODIGO  IN 
			  (SELECT MA_CODIGO FROM FACTIMPDET WHERE FID_INDICED=FactImpPermTmp.FID_INDICED) 
			AND CPE_CODIGO=FactImpPermTmp.CPE_CODIGO),1)


	INSERT INTO FACTIMPPERM(FIR_CODIGO, FID_INDICED, FI_CODIGO, PE_CODIGO, PED_INDICED, FIP_ESTATUSAFECTA, CPE_CODIGO, EQ_CANT)
	
	SELECT     FIR_CODIGO, FID_INDICED, FI_CODIGO, PE_CODIGO, PED_INDICED, FIP_ESTATUSAFECTA, CPE_CODIGO, EQ_CANT
	FROM         FactImpPermTmp



	
	
	update consecutivo
	set cv_codigo =  (select isnull(max(FIR_CODIGO),0) from FACTIMPPERM) + 1
	where cv_tipo = 'FIR'


	exec sp_droptable 'FactImpPermTmp'


GO
