SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO























CREATE PROCEDURE [dbo].[SP_DescExplosionFedBomAdicion] (@FED_INDICED Int)   as

SET NOCOUNT ON 

declare @FE_CODIGO INT, @BST_PT INT, @FED_CANT decimal(38,6), @FED_FECHA_STRUCT DATETIME, @countbom int, 
@incorpor decimal(38,6)


declare CUR_EXPLOADICION cursor for
-- selecciona Producto Terminados o Subensambles que esten incluidos en adicion a descarga 
	SELECT     dbo.FACTEXPDET.FE_CODIGO, dbo.RETRABAJO.MA_HIJO, SUM(dbo.RETRABAJO.RE_INCORPOR) AS RE_INCORPOR, convert(varchar(10),dbo.FACTEXP.FE_FECHA,101)
	FROM         dbo.FACTEXP INNER JOIN
	                      dbo.FACTEXPDET ON dbo.FACTEXP.FE_CODIGO = dbo.FACTEXPDET.FE_CODIGO RIGHT OUTER JOIN
	                      dbo.RETRABAJO ON /*dbo.FACTEXPDET.MA_CODIGO = dbo.RETRABAJO.MA_HIJO AND */
	                      dbo.FACTEXPDET.FED_INDICED = dbo.RETRABAJO.FETR_INDICED AND dbo.RETRABAJO.TIPO_FACTRANS = 'F' LEFT OUTER JOIN
	                      dbo.CONFIGURATIPO ON dbo.RETRABAJO.TI_HIJO = dbo.CONFIGURATIPO.TI_CODIGO
	WHERE (dbo.CONFIGURATIPO.CFT_TIPO IN ('S', 'P')) AND (dbo.FACTEXPDET.FED_RETRABAJO = 'A') 
	      AND (dbo.FACTEXPDET.PID_INDICED = - 1) AND dbo.FACTEXPDET.FED_INDICED=@FED_INDICED 
	GROUP BY dbo.FACTEXPDET.FED_INDICED, dbo.RETRABAJO.MA_HIJO, dbo.FACTEXPDET.FED_RETRABAJO, 
	                      dbo.FACTEXPDET.PID_INDICED, dbo.FACTEXP.FE_FECHA, dbo.FACTEXPDET.FE_CODIGO
	HAVING      (SUM(dbo.RETRABAJO.RE_INCORPOR) > 0) 
	ORDER BY dbo.FACTEXPDET.FED_INDICED, dbo.RETRABAJO.MA_HIJO

 OPEN CUR_EXPLOADICION

  FETCH NEXT FROM CUR_EXPLOADICION
	INTO @FE_CODIGO, @BST_PT, @FED_CANT, @FED_FECHA_STRUCT

  WHILE (@@fetch_status = 0) 
  BEGIN  

	select @countbom = count(*) from bom_struct where  bsu_subensamble=@BST_PT and bst_perini<=@FED_FECHA_STRUCT and bst_perfin>=@FED_FECHA_STRUCT

	if @countbom >0 AND @FED_CANT>0
	EXEC SP_FILL_BOM_DESCTEMP @FED_INDICED, @BST_PT, @FED_FECHA_STRUCT, @FED_CANT, @FE_CODIGO

	FETCH NEXT FROM CUR_EXPLOADICION INTO @FE_CODIGO, @BST_PT, @FED_CANT, @FED_FECHA_STRUCT

END

	CLOSE CUR_EXPLOADICION
	DEALLOCATE CUR_EXPLOADICION
























GO
