SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE dbo.SP_UPDATE_SALDO_PCKLIST(@CODIGOPCK INT, @SALDO decimal(38,6))   as

SET NOCOUNT ON 
BEGIN
	DECLARE @SALDO_ACTUAL decimal(38,6), @CANTIDAD_ST decimal(38,6), @PACKINGLIST INT,  @SUMA_SALDO decimal(38,6), @EN_USO INT

	-- Obtener el saldo actual y la cantidad, y el packing list al que pertenece
	SELECT @SALDO_ACTUAL = PLD_SALDO FROM PCKLISTDET WHERE PLD_INDICED = @CODIGOPCK
	SELECT @CANTIDAD_ST = PLD_CANT_ST FROM PCKLISTDET WHERE PLD_INDICED = @CODIGOPCK
	SELECT @PACKINGLIST = PL_CODIGO FROM PCKLISTDET WHERE PLD_INDICED = @CODIGOPCK


	-- actualizar el Saldo
	UPDATE PCKLISTDET SET PLD_SALDO = @SALDO_ACTUAL + @SALDO WHERE PLD_INDICED = @CODIGOPCK

	-- obtener el saldo actualizado
	SELECT @SALDO_ACTUAL = PLD_SALDO FROM PCKLISTDET WHERE PLD_INDICED = @CODIGOPCK
	
	-- obtener la sumatoria del saldo
	SELECT @SUMA_SALDO = SUM(PLD_SALDO) FROM PCKLISTDET WHERE PL_CODIGO = @PACKINGLIST

	-- obtener si hay alguno que no est, en uso
	SELECT @EN_USO = COUNT(*) FROM PCKLISTDET WHERE PL_CODIGO = @PACKINGLIST AND PLD_ENUSO = 'N'


	-- si la cantidad es igual al saldo quiere decir que no est~ en uso
--	IF @SALDO_ACTUAL = @CANTIDAD_ST 
	--BEGIN
		UPDATE PCKLISTDET SET PLD_ENUSO = 'N'  WHERE PLD_INDICED = @CODIGOPCK  AND (PLD_SALDO = PLD_CANT_ST)
--	END
	

	IF (@SUMA_SALDO = 0) AND (@EN_USO = 0)
		UPDATE PCKLIST SET PL_ESTATUS = 'C' WHERE PL_CODIGO = @PACKINGLIST
	ELSE 
		UPDATE PCKLIST SET PL_ESTATUS = 'A' WHERE PL_CODIGO = @PACKINGLIST

END



























GO
EXEC sp_addextendedproperty N'MS_Description', N'dsdsdds', 'SCHEMA', N'dbo', 'PROCEDURE', N'SP_UPDATE_SALDO_PCKLIST', NULL, NULL
GO
