SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO


















CREATE PROCEDURE dbo.SP_GENERATE_ENTRYAJ (@CS_CODIGO INT)    as

SET NOCOUNT ON 
BEGIN
  BEGIN TRAN
  DECLARE @ERRORES INT
SET @ERRORES = 0

	DELETE FROM COSTSUBAJ WHERE CS_CODIGO=@CS_CODIGO



	INSERT INTO COSTSUBAJ(CS_CODIGO, ETA_CODIGO, ET_CODIGO, FE_CODIGO, ETD_LINE, ETAJ_NAME, AR_CODIGO, AR_ORIG, AR_NG_EMP, AR_CODIGOREC, PA_CODIGO, ETAJ_RATE, ETAJ_NAFTA, 
	                      ETAJ_NAFTAREC, ETAJ_CANT, ETAJ_CANTREC, ETAJ_VAL_GRAV, ETAJ_VAL_GRAVREC, ETAJ_VAL_NOGRAV9802, ETAJ_VAL_NOGRAV9802REC, ETAJ_COS_TOT, ETAJ_COS_TOTREC, ETAJ_DLLS_IRC, ETAJ_DLLS_VISA, 
	                      ETAJ_DLLS_MPF, ETAJ_DLLS_RATE, ETAJ_DLLS_IRCREC, ETAJ_DLLS_VISAREC, ETAJ_DLLS_MPFREC, ETAJ_DLLS_RATEREC, ETAJ_RETRABAJO, 
	                      CFT_TIPO)

	SELECT      @CS_CODIGO, ETA_CODIGO, dbo.ENTRYSUM.ET_CODIGO, dbo.ENTRYSUMARA.FE_CODIGO, ETD_LINE, ETA_NAME, dbo.ENTRYSUMARA.AR_CODIGO, AR_ORIG, AR_NG_EMP, dbo.ENTRYSUMARA.AR_CODIGO, dbo.ENTRYSUMARA.PA_CODIGO, ETA_RATE, MA_NAFTA, 
	                      MA_NAFTA, ETA_CANT, ETA_CANT, ROUND(ETA_GRAV_VA + ETA_GRAV_MAT,6), ROUND(ETA_GRAV_VA + ETA_GRAV_MAT,6), ETA_NG_MAT, ETA_NG_MAT, ETA_COS_TOT, ETA_COS_TOT, ETA_DLLS_IRC, ETA_DLLS_VISA, 
	                      ETA_DLLS_MPF, ETA_DLLS_RATE, ETA_DLLS_IRC, ETA_DLLS_VISA, ETA_DLLS_MPF, ETA_DLLS_RATE, ETA_RETRABAJO, 
	                      CFT_TIPO
	FROM         dbo.FACTEXP INNER JOIN
	                      dbo.COSTSUBPER ON dbo.FACTEXP.CL_DESTINI = dbo.COSTSUBPER.CL_CODIGO FULL OUTER JOIN
	                      dbo.ENTRYSUMARA RIGHT OUTER JOIN
	                      dbo.ENTRYSUM ON dbo.ENTRYSUMARA.ET_CODIGO = dbo.ENTRYSUM.ET_CODIGO ON 
	                      dbo.COSTSUBPER.CS_FECHAINI <= dbo.ENTRYSUM.ET_FEC_ENTRYS AND 
	                      dbo.COSTSUBPER.CS_FECHAFIN >= dbo.ENTRYSUM.ET_FEC_ENTRYS AND dbo.FACTEXP.FE_CODIGO = dbo.ENTRYSUMARA.FE_CODIGO
	WHERE     (dbo.FACTEXP.TN_CODIGO = 2 OR
	                      dbo.FACTEXP.TN_CODIGO = 5 OR
	                      dbo.FACTEXP.TN_CODIGO = 6 OR
	                      dbo.FACTEXP.TN_CODIGO = 7 OR dbo.FACTEXP.TN_CODIGO = 8 OR dbo.FACTEXP.TN_CODIGO = 9) and dbo.ENTRYSUM.ET_ENTRY_NO is not null
	AND dbo.COSTSUBPER.CS_CODIGO=@CS_CODIGO
	ORDER BY dbo.FACTEXP.FE_FOLIO

  IF (@@ERROR >0 ) SET @ERRORES =1
  COMMIT TRAN
IF @ERRORES = 0
  RETURN(0)

ELSE BEGIN
  ROLLBACK TRAN
  RETURN(1)

END
END




GO
