SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE dbo.SP_PEDIMPDETB (@PI_CODIGO INTEGER)   as

SET NOCOUNT ON 
BEGIN 
  DECLARE @CONSDETB INT
  DECLARE @ERRORES INT
  SET @ERRORES = 0
  BEGIN TRAN
	DELETE FROM PEDIMPDETB WHERE PI_CODIGO = @PI_CODIGO
	IF (@@ERROR <> 0 ) SET @ERRORES = 1

	/* Consecutivo del contenido */
	EXEC SP_GETCONSECUTIVO 'PIB',@TIPO =  @CONSDETB        

          INSERT INTO PEDIMPDETB (PI_CODIGO,PIB_INDICEB,PIB_VAL_FAC, PIB_VAL_ADU,PIB_VAL_US)
          SELECT @PI_CODIGO,@CONSDETB,SUM(PEDIMPDET.PID_CTOT_DLS * PEDIMP.PI_TIP_CAM), SUM(PID_VAL_ADU),SUM(PID_CTOT_DLS)
          FROM PEDIMPDET LEFT OUTER JOIN PEDIMP ON PEDIMPDET.PI_CODIGO=PEDIMP.PI_CODIGO
	  GROUP BY AR_IMPMX
	IF (@@ERROR <> 0 ) SET @ERRORES = 1

	UPDATE PEDIMPDETB  SET PIB_ESTADO = A.AR_CODIGO 
        FROM PEDIMPDETB AS P,ARANCEL AS A 
	WHERE P.PI_CODIGO = @PI_CODIGO AND A.AR_CODIGO = P.AR_IMPMX
	IF (@@ERROR <> 0 ) SET @ERRORES = 1

 COMMIT TRAN DETALLEB
  IF @ERRORES = 0
 RETURN(0)
ELSE
BEGIN
  ROLLBACK TRAN DETALLEB
  RETURN(1)
END
END



























GO
