SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO































CREATE PROCEDURE [dbo].[SP_FACTIMPITN] (@FI_CODIGO int)   as

declare @FI_TIP_CAM decimal(38,6)

	select @FI_TIP_CAM=FI_TIPOCAMBIO from factimp where fi_codigo=@FI_CODIGO

INSERT INTO FACTIMPITN (fi_codigo, ITN_TEXTO, ITN_TIPO)
SELECT    @FI_CODIGO, REPLACE(FI_NUM_INBON, '/', ''), 'B'
FROM         FACTIMP
WHERE     (TN_CODIGO = 1) AND (fi_codigo = @FI_CODIGO)
AND REPLACE(FI_NUM_INBON, '/', '') IS NOT NULL



--OPCION 4

INSERT INTO FACTIMPITN (fi_codigo, ITN_TEXTO, ITN_TIPO)
SELECT     @FI_CODIGO, CLIENTE.CL_EIN + '-' + CLIENTE_1.AG_RFC, 'O'
FROM         FACTIMP INNER JOIN
                      CLIENTE ON FACTIMP.PR_CODIGO = CLIENTE.CL_CODIGO INNER JOIN
                      AGENCIA CLIENTE_1 ON FACTIMP.AG_USA = CLIENTE_1.AG_CODIGO
WHERE     (FACTIMP.TN_CODIGO = 11) AND (FACTIMP.fi_codigo = @FI_CODIGO)
AND (CLIENTE.CL_EIN + CLIENTE_1.AG_RFC) IS NOT NULL


-- ITN
INSERT INTO FACTIMPITN (fi_codigo, ITN_TEXTO, ITN_TIPO)
SELECT     @FI_CODIGO, REPLACE(FI_ITN, '/', ''), 'I'
FROM         FACTIMP
WHERE     (TN_CODIGO = 10) AND (fi_codigo = @FI_CODIGO)
AND REPLACE(FI_ITN, '/', '') IS NOT NULL


--<=2500
INSERT INTO FACTIMPITN (fi_codigo, ITN_TEXTO, ITN_TIPO)
SELECT     @FI_CODIGO, round(SUM(dbo.FACTIMPDET.FID_COS_TOT),0), 'M'
FROM         dbo.FACTIMP INNER JOIN
                      dbo.FACTIMPDET ON dbo.FACTIMP.FI_CODIGO = dbo.FACTIMPDET.FI_CODIGO
WHERE     (dbo.FACTIMP.TN_CODIGO = 12) AND (dbo.FACTIMP.fi_codigo = @FI_CODIGO)





GO
