SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO




























CREATE PROCEDURE dbo.SP_UPDATE_VAMAESTRO(@ADDPORCENT decimal(38,6), @TAFFECT INTEGER, @GIM CHAR(1), @GIU CHAR(1), @MO CHAR(1), @AFFECTED INTEGER OUTPUT)  as

DECLARE @TCO_MANUFACTURA INT

	SELECT    @TCO_MANUFACTURA=TCO_MANUFACTURA FROM dbo.CONFIGURACION

	BEGIN TRAN
	             -- AFFECT PT
  		IF @TAFFECT = 1
  		BEGIN
			IF @GIM='S'
				UPDATE MAESTROCOST SET MA_GRAV_GI_MX = MA_GRAV_GI_MX + (MA_GRAV_GI_MX * (@ADDPORCENT/100))
				WHERE MA_CODIGO IN (SELECT MA_CODIGO FROM MAESTRO WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM  CONFIGURATIPO WHERE CFT_TIPO = 'P'))
				AND TCO_CODIGO=@TCO_MANUFACTURA

        			IF @GIU='S'
				UPDATE MAESTROCOST SET MA_GRAV_GI    = MA_GRAV_GI  +  (MA_GRAV_GI * (@ADDPORCENT/100))   
				WHERE MA_CODIGO IN (SELECT MA_CODIGO FROM MAESTRO WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM  CONFIGURATIPO WHERE CFT_TIPO = 'P'))
				AND TCO_CODIGO=@TCO_MANUFACTURA

        			IF @MO='S'
				UPDATE MAESTROCOST SET MA_GRAV_MO    = MA_GRAV_MO +  (MA_GRAV_MO * (@ADDPORCENT/100))  
				WHERE MA_CODIGO IN (SELECT MA_CODIGO FROM MAESTRO WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM  CONFIGURATIPO WHERE CFT_TIPO = 'P'))
				AND TCO_CODIGO=@TCO_MANUFACTURA

		             SET @AFFECTED = @@ROWCOUNT  	
		END
             
  		-- AFECT SUB
  		IF @TAFFECT = 2
  		BEGIN
			IF @GIM='S'
				UPDATE MAESTROCOST SET MA_GRAV_GI_MX = MA_GRAV_GI_MX + (MA_GRAV_GI_MX * (@ADDPORCENT/100))
				WHERE MA_CODIGO IN (SELECT MA_CODIGO FROM MAESTRO WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM  CONFIGURATIPO WHERE CFT_TIPO = 'S'))
				AND TCO_CODIGO=@TCO_MANUFACTURA

        			IF @GIU='S'
				UPDATE MAESTROCOST SET MA_GRAV_GI    = MA_GRAV_GI  +  (MA_GRAV_GI * (@ADDPORCENT/100))   
				WHERE MA_CODIGO IN (SELECT MA_CODIGO FROM MAESTRO WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM  CONFIGURATIPO WHERE CFT_TIPO = 'S'))
				AND TCO_CODIGO=@TCO_MANUFACTURA


        			IF @MO='S'
				UPDATE MAESTROCOST SET MA_GRAV_MO    = MA_GRAV_MO +  (MA_GRAV_MO * (@ADDPORCENT/100))  
				WHERE MA_CODIGO IN (SELECT MA_CODIGO FROM MAESTRO WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM  CONFIGURATIPO WHERE CFT_TIPO = 'S'))
				AND TCO_CODIGO=@TCO_MANUFACTURA

      			SET @AFFECTED = @@ROWCOUNT
  		END

  		-- AFECT BOTH
  		IF @TAFFECT = 3
  		BEGIN
			IF @GIM='S'
				UPDATE MAESTROCOST SET MA_GRAV_GI_MX = MA_GRAV_GI_MX + (MA_GRAV_GI_MX * (@ADDPORCENT/100))
				WHERE MA_CODIGO IN (SELECT MA_CODIGO FROM MAESTRO WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM  CONFIGURATIPO WHERE (CFT_TIPO = 'S' OR CFT_TIPO = 'P')))
				AND TCO_CODIGO=@TCO_MANUFACTURA



        			IF @GIU='S'
				UPDATE MAESTROCOST SET MA_GRAV_GI    = MA_GRAV_GI  +  (MA_GRAV_GI * (@ADDPORCENT/100))   
				WHERE MA_CODIGO IN (SELECT MA_CODIGO FROM MAESTRO WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM  CONFIGURATIPO WHERE (CFT_TIPO = 'S' OR CFT_TIPO = 'P')))
				AND TCO_CODIGO=@TCO_MANUFACTURA


        			IF @MO='S'
				UPDATE MAESTROCOST SET MA_GRAV_MO    = MA_GRAV_MO +  (MA_GRAV_MO * (@ADDPORCENT/100))  
				WHERE MA_CODIGO IN (SELECT MA_CODIGO FROM MAESTRO WHERE TI_CODIGO IN (SELECT TI_CODIGO FROM  CONFIGURATIPO WHERE (CFT_TIPO = 'S' OR CFT_TIPO = 'P')))
				AND TCO_CODIGO=@TCO_MANUFACTURA

			SET @AFFECTED = @@ROWCOUNT
		END

	COMMIT TRAN




		UPDATE MAESTROCOST
		SET     MA_COSTO= ROUND(MA_GRAV_MP + MA_GRAV_ADD + MA_GRAV_EMP + MA_GRAV_GI + MA_GRAV_GI_MX + MA_GRAV_MO + MA_NG_MP +
		                      MA_NG_ADD + MA_NG_EMP,6)
		FROM         MAESTROCOST
		WHERE TCO_CODIGO=1 AND MA_PERINI <=GETDATE() and MA_PERFIN>= GETDATE() AND
		MA_COSTO<> ROUND(MA_GRAV_MP + MA_GRAV_ADD + MA_GRAV_EMP + MA_GRAV_GI + MA_GRAV_GI_MX + MA_GRAV_MO + MA_NG_MP +
		                      MA_NG_ADD + MA_NG_EMP,6)





















GO
