SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO











CREATE PROCEDURE [dbo].[sp_temp_20022]   as




UPDATE NAFTA
SET     NAFTA.NFT_NOPARTEAUX= MAESTRO.MA_NOPARTEAUX
FROM         MAESTRO INNER JOIN
                      NAFTA ON MAESTRO.MA_CODIGO = NAFTA.MA_CODIGO


DELETE CLAVEPEDIDENTIFICA
FROM         CLAVEPEDIDENTIFICA INNER JOIN
                      CLAVEPED ON CLAVEPEDIDENTIFICA.CP_CODIGO = CLAVEPED.CP_CODIGO
WHERE     (CLAVEPED.CP_CLAVE = 'IN')


INSERT INTO CLAVEPEDIDENTIFICA (CP_CODIGO, IDE_CODIGO, IDE_NIVEL, CP_MOVIMIENTO, CP_COMPLEMENTO)

SELECT     (SELECT CP_CODIGO FROM CLAVEPED WHERE CP_CLAVE='IN'), CLAVEPEDIDENTIFICA.IDE_CODIGO, CLAVEPEDIDENTIFICA.IDE_NIVEL, CLAVEPEDIDENTIFICA.CP_MOVIMIENTO, 
                      CLAVEPEDIDENTIFICA.CP_COMPLEMENTO
FROM         CLAVEPEDIDENTIFICA INNER JOIN
                      CLAVEPED ON CLAVEPEDIDENTIFICA.CP_CODIGO = CLAVEPED.CP_CODIGO
WHERE     (CLAVEPED.CP_CLAVE = 'H2')




DELETE CLAVEPEDIDENTIFICA
FROM         CLAVEPEDIDENTIFICA INNER JOIN
                      CLAVEPED ON CLAVEPEDIDENTIFICA.CP_CODIGO = CLAVEPED.CP_CODIGO
WHERE     (CLAVEPED.CP_CLAVE = 'RT')


INSERT INTO CLAVEPEDIDENTIFICA (CP_CODIGO, IDE_CODIGO, IDE_NIVEL, CP_MOVIMIENTO, CP_COMPLEMENTO)

SELECT     (SELECT CP_CODIGO FROM CLAVEPED WHERE CP_CLAVE='RT'), CLAVEPEDIDENTIFICA.IDE_CODIGO, CLAVEPEDIDENTIFICA.IDE_NIVEL, CLAVEPEDIDENTIFICA.CP_MOVIMIENTO, 
                      CLAVEPEDIDENTIFICA.CP_COMPLEMENTO
FROM         CLAVEPEDIDENTIFICA INNER JOIN
                      CLAVEPED ON CLAVEPEDIDENTIFICA.CP_CODIGO = CLAVEPED.CP_CODIGO
WHERE     (CLAVEPED.CP_CLAVE = 'J1')



DELETE CLAVEPEDIDENTIFICA
FROM         CLAVEPEDIDENTIFICA INNER JOIN
                      CLAVEPED ON CLAVEPEDIDENTIFICA.CP_CODIGO = CLAVEPED.CP_CODIGO
WHERE     (CLAVEPED.CP_CLAVE = 'AF')


INSERT INTO CLAVEPEDIDENTIFICA (CP_CODIGO, IDE_CODIGO, IDE_NIVEL, CP_MOVIMIENTO, CP_COMPLEMENTO)

SELECT     (SELECT CP_CODIGO FROM CLAVEPED WHERE CP_CLAVE='AF'), CLAVEPEDIDENTIFICA.IDE_CODIGO, CLAVEPEDIDENTIFICA.IDE_NIVEL, CLAVEPEDIDENTIFICA.CP_MOVIMIENTO, 
                      CLAVEPEDIDENTIFICA.CP_COMPLEMENTO
FROM         CLAVEPEDIDENTIFICA INNER JOIN
                      CLAVEPED ON CLAVEPEDIDENTIFICA.CP_CODIGO = CLAVEPED.CP_CODIGO
WHERE     (CLAVEPED.CP_CLAVE = 'H3')

GO
